### ISSUE TITLE
⌘+C for Clear is a bit weird

### ISSUE THREAD

**Issue by CodeBrauer** [p0deje/Maccy#1]
When you open Maccy with `⌘+⇧+C` and then press `⌘+C` by accident, you clear all your work. Maybe give an option to edit or disable this (or even a confirm dialog/Undo last action).

**Comment by p0deje** [comment]
What if I just drop the keybinding altogether?

**Comment by CodeBrauer** [comment]
I mean, actually if somebody is a keyboard-heavy user you can also just tap <kbd>↓</kbd> down and then <kbd>Enter</kbd>
So yes, maybe this wouldn't be to bad.

Only making the global shortcut configurable would be nice

**Comment by p0deje** [comment]
Please try 0.3.0.

It also [allows to configure global hotkey](https://github.com/p0deje/Maccy#popup-hotkey).

**Comment by CodeBrauer** [comment]
Awesome! Finally can use this instead of ClipMenu. The search feature is awesome.
