### ISSUE TITLE
Not possible to avoid pasteboard of Bitwarden

### ISSUE THREAD

**Issue by silvestre125** [p0deje/Maccy#100]
Hello,

I am trying to prevent Maccy from crawling my clipboard in certain applications, for example Bitwarden (a password manager).

I executed the following command without success:
`defaults to write org.p0deje.Maccy ignored PasteboardTypes -array-add "com.bitwarden.desktop"`
`defaults to write org.p0deje.Maccy ignored PasteboardTypes -array-add "com.bitwarden.desktop.safafi"`

I've checked that they are the correct domains for the app.
Any idea what might be happening?

Thanks in advance.

**Comment by p0deje** [comment]
First of all, this feature has not been released yet, so unless you built Maccy from Github manually - it won't work. 

Second, the command you are using is wrong, it should be:

```
defaults write org.p0deje.Maccy ignoredPasteboardTypes -array-add "com.bitwarden.desktop"
```

Third, you need to use pasteboard type, not the app domain. But specifying a custom pasteboard type seems to be unsupported in Bitwarden (https://github.com/bitwarden/desktop/issues/90) so I don't think you can exclude it now.

Closing as nothing to be done in Maccy.

**Comment by TickDracy** [comment]
> First of all, this feature has not been released yet, so unless you built Maccy from Github manually - it won't work.
> 
> Second, the command you are using is wrong, it should be:
> 
> ```
> defaults write org.p0deje.Maccy ignoredPasteboardTypes -array-add "com.bitwarden.desktop"
> ```
> 
> Third, you need to use pasteboard type, not the app domain. But specifying a custom pasteboard type seems to be unsupported in Bitwarden ([bitwarden/clients#2633](https://github.com/bitwarden/clients/issues/2633)) so I don't think you can exclude it now.
> 
> Closing as nothing to be done in Maccy.

Hello @p0deje, it seems Bitwarden has fixed it, right?https://github.com/bitwarden/clients/issues/2633#issuecomment-2352909466

Could you please kindly explain on how to exclude Bitwarden from Maccy, then?

**Comment by p0deje** [comment]
@TickDracy It should be excluded automatically since they now add `org.nspasteboard.ConcealedType` to pasteboard types. If that's not the case, can you inspect the copy using Pasteboard Viewer app and share what types are present?

**Comment by TickDracy** [comment]
> @TickDracy It should be excluded automatically since they now add `org.nspasteboard.ConcealedType` to pasteboard types. If that's not the case, can you inspect the copy using Pasteboard Viewer app and share what types are present?

Thanks. Do you mean [this](https://apps.apple.com/us/app/pasteboard-viewer/id1499215709) app?  
That one requires macOS 14.4, so I can't install/test it. Do you know if there is another workaround to get the pasteboard types?
