### ISSUE TITLE
Clearer seperation between clips

### ISSUE THREAD

**Issue by Gittykittymitty** [p0deje/Maccy#1000]
### Before Submitting Your Feature Request

- [X] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

Its difficult to see which clips are the same and which are different. 

### Solution

Add thin lines between the clips, that way its much clearer.

**Comment by p0deje** [comment]
The UI resembles standard macOS menus, there are no thin lines there.
