### ISSUE TITLE
Apple Passwords still get captured in clipboard history when using menubar app.

### ISSUE THREAD

**Issue by Gittykittymitty** [p0deje/Maccy#1008]
### Before Submitting Your Bug Report

- [X] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Description

Even though I Have set Apple Passwords as an ignored app, sometimes Maccy still picks up these texts. This doesent happen when I have opened the Passwords app through Launch Pad, but only when I copy passwords from the menubar extension.

**Comment by p0deje** [comment]
When used in the menubar, the Passwords app doesn't report itself as a passwords app, but instead as a currently active application. There is no way to detect it.
