### ISSUE TITLE
Latency when pasting

### ISSUE THREAD

**Issue by philihub** [p0deje/Maccy#104]
When pasting from Maccy it takes a 1-2 seconds until an item from the list (not the last item) is pasted. If a regular copy & paste is applied there is no latency.

**Comment by p0deje** [comment]
I cannot reproduce. For me, it happens instantly. Are you using the latest Maccy version? What OS version?

Not sure how to investigate the problem so any additional information is appreciated.

**Comment by philihub** [comment]
Sorry, you are right. Here is more info: macOS 10.15.4, latest Maccy version. Can I send you a screen cap of the action somewhere?

**Comment by p0deje** [comment]
Yeah, can you please add screen recording. You can attach to this issue in comment.

**Comment by philihub** [comment]
@p0deje Does this work for you?
[maccy-latancy.mov.zip](https://github.com/p0deje/Maccy/files/4649408/maccy-latancy.mov.zip)

**Comment by p0deje** [comment]
Yes, thank you. Just to be clear, your computer is not loaded when it happens, right?

**Comment by philihub** [comment]
Loaded in terms of under heavy load? Not really, just regular daily use. 
<img width="594" alt="image" src="https://user-images.githubusercontent.com/16780277/82309688-ba361380-99c3-11ea-97d7-3b1aed2d46e7.png">

**Comment by p0deje** [comment]
Does it matter what you paste? Is it the same for pasting images?

**Comment by philihub** [comment]
It is the same, yes. I think I have the standard length of entries displayed and mostly about 85–90% text in the clipboard.

**Comment by philihub** [comment]
Just FYI: I played around with the settings and now it is about twice as fast, 2/3s of a second compared to about 1,5 before. I might have set my history to 100 instead of 200 but I am not sure if it even was more than 100 before. Certainly not more than 200 which is the default.

**Comment by philihub** [comment]
Thinking of it has something to do with this: https://mjtsai.com/blog/2020/05/22/macos-10-15-slow-by-design/

Any way I could test that?

**Comment by p0deje** [comment]
I guess the only way to test it would be to disable SIP. It can be done by following the steps in https://www.imore.com/how-turn-system-integrity-protection-macos.

However, if it really is security issue, I'd expect you to see delays in all applications, not just Maccy.

**Comment by p0deje** [comment]
I've added some additional performance logic to the code. Can you please run the attached version of Maccy and try to paste something from Maccy. Then open "Console" app, search logs for "Process: Maccy" and comment here about what is found. I'm interested in your values for the following similar messages:

```
default	17:53:41.755568-0400	Maccy	Accessibility checked for 0.012987517
default	17:53:41.792944-0400	Maccy	Paste events sent for 0.016086448
```

[Maccy.app.zip](https://github.com/p0deje/Maccy/files/4672593/Maccy.app.zip)

**Comment by philihub** [comment]
Mine says

standard	09:23:55.577996+0200	Maccy	Accessibility checked for 2.7499e-05
standard	09:23:55.827054+0200	Maccy	Paste events sent for 0.000532103

A second time:
standard	09:24:47.424922+0200	Maccy	Accessibility checked for 2.6789e-05
standard	09:24:47.675395+0200	Maccy	Paste events sent for 0.000645499

**Comment by p0deje** [comment]
Can you try version 0.10.0 and let me know if it still happens?

**Comment by philihub** [comment]
It’s very snappy now. Would say it is fixed 👍🏼

**Comment by p0deje** [comment]
Ok, don't know what exactly happened, but please re-open if it happens again.

**Comment by zacnoo** [comment]
https://github.com/p0deje/Maccy/assets/3452866/24c72ea1-8afc-4e0d-98fc-834f4eb60066

Not sure if this is the same issue or not.

**Comment by zacnoo** [comment]
> Screen.Recording.2023-10-06.at.1.11.10.PM.mov 
> 
> Not sure if this is the same issue or not.

Clearing the history seems to have fixed the issue. Although I've never experienced any measurable latency issues in the last couple years, even with 999 items always visible.
