### ISSUE TITLE
Set up shortcut to Command+Ñ

### ISSUE THREAD

**Issue by alejandrosnz** [p0deje/Maccy#108]
Hi there!

Is there a way to set up the shortcut to be command+Ñ?

I have been trying to set it up in terminal using `defaults write org.p0deje.Maccy hotKey command+ñ` but no luck.

btw, where is the Preferences window? I can't find it :(

Thanks for this great app!
Alex

**Comment by p0deje** [comment]
what is command+Ñ? what physical key on keyboard does it point to?

also, preferences are in master but not released yet - will be soon on 0.10.0

**Comment by alejandrosnz** [comment]
Sorry, forgot to explain
Is a Spanish letter, is to the right of the letter "L" on the Spanish layout keyboards

**Comment by p0deje** [comment]
In Maccy 0.10.0 (released yesterday) there is a preferences window where you can record a custom shortcut. Can you try and let me know if it works?

**Comment by alejandrosnz** [comment]
Sadly it does not, but no worries, I´ll habituate myself to the new shortcut.

Thanks again

**Comment by p0deje** [comment]
Strange - it should just work. I've tried recording shortcuts on the Russian keyboard and it had problems at all. Can you try to experiment with other key combinations?

**Comment by alejandrosnz** [comment]
Find my results below:

| shortcut | works? |
|----------|--------| 
|  command+Ñ               |  NO       |
|  control+Ñ               |  NO       |
|  alt+Ñ               |  NO       |
|  command+´               |  NO       |
|  command+`               |  YES       |
|  command+ç               |  YES       |
|  command++               |  NO       |
|  command+-               |  YES       |
|  command+.               |  YES       |
|  command+,               |  YES       |
|  command+¡               |  NO       |

Note that the Spanish layout has the symbols in a different location than the US ones

![spanish-mac-keyboard-layout-keyshorts](https://user-images.githubusercontent.com/20269734/84358999-448b2500-abc8-11ea-94de-e02644fa8bf1.png)


Thanks!
Alex

**Comment by p0deje** [comment]
It seems like it can be solved by using https://github.com/sindresorhus/KeyboardShortcuts instead of https://github.com/Clipy/KeyHolder and https://github.com/Clipy/Magnet.

I tried but couldn't figure out because of https://github.com/sindresorhus/KeyboardShortcuts/issues/14. Needs more work.
