### ISSUE TITLE
Partial or whole screenshot sent to clipboard doesn't register

### ISSUE THREAD

**Issue by julesallen** [p0deje/Maccy#110]
If you take a partial screenshot that's sent to the clipboard (⌘^4, select an area with the crosshairs) it doesn't show up in Maccy. Same with full screen (⌘^3).

**Comment by p0deje** [comment]
@julesallen Are you using 0.10.0? I just tried on this version and it worked.

**Comment by p0deje** [comment]
Closing since I cannot reproduce it on 0.10+ and there was no response for two weeks. Feel free to reopen if the issue is still there.
