### ISSUE TITLE
Maccy can't be updated from 0.9 to 0.10

### ISSUE THREAD

**Issue by MaxDesiatov** [p0deje/Maccy#111]
After I select "Check for updates" menu item and wait for the update download to complete, I always get this error:

<img width="417" alt="Screenshot 2020-06-04 at 13 40 17" src="https://user-images.githubusercontent.com/112310/84026451-40bb9080-a985-11ea-9897-feda4aca5c67.png">

This is stably reproducible for me on macOS 10.15.5 (19F101)

**Comment by p0deje** [comment]
Hm, can't reproduce locally. Can you try downloading from Github and running? Maybe that will give an insight.

**Comment by MaxDesiatov** [comment]
I've downloaded from GitHub, but then after launching it from that archive I get this error:

<img width="420" alt="Screenshot 2020-06-08 at 13 48 44" src="https://user-images.githubusercontent.com/112310/84032195-dd366080-a98e-11ea-89f2-86db191208f9.png">

I know I can disable Gatekeeper or give an exemption to this single binary, but I'm not going to do that for obvious security reasons. I wish Maccy binaries were notarised for macOS.

**Comment by p0deje** [comment]
Maccy 0.9 is not notarized as well, so I don't follow why you are fine running 0.9 but not 0.10. I believe that might be a cause of update problems. Feel free to stick to 0.9 if you don't want to exempt 0.10.

I currently work on 0.11 which will also be notarized (see #52 for more information).

**Comment by MaxDesiatov** [comment]
Sorry about the confusion, now I remember that I've built 0.9 from sources to sign it with my own cert. Rebuilding 0.10 now 🙂

I'd like to join the rest of the people in #52: I appreciate your hard work and would definitely buy Maccy on the Mac App Store when it's available there 👍

**Comment by p0deje** [comment]
Oh, that makes total sense. The good news is that I've already made notarization work so hopefully, nobody will need to re-sign by themselves for that matter. Unless they want it, of course.

**Comment by FernandoMiguel** [comment]
you can open Application, click app and Option and it will allow you to execute.
that's why i upgraded mine

**Comment by MaxDesiatov** [comment]
@FernandoMiguel I know about that, that's what I meant by "give an exemption to this single binary". I'm not doing that for any binary under any circumstances due to security reasons, as I mentioned. In no way I'm suggesting that this binary contains any malware, I just think that rebuilding from sources and signing with my own cert is more secure than a habit of giving exemption to any binaries.
