### ISSUE TITLE
How to access Preferences once the footer is hidden?

### ISSUE THREAD

**Issue by danilokleber** [p0deje/Maccy#112]
I tried quitting the app and running it again, right-clicking the menu bar icon, pressing `Cmd + ,` while Maccy window is open but nothing seemed to work. Is there any way not documented?

**Comment by dallanlee** [comment]
Your issue didn't exist when I looked for this issue before opening my own just now 😂 

Until this is fixed, you can at least run `defaults write org.p0deje.Maccy hideFooter false` in the terminal 👌🏼

**Comment by p0deje** [comment]
Let's continue in #113
