### ISSUE TITLE
Hiding the footer causes the user to not be able to open the Preferences window

### ISSUE THREAD

**Issue by dallanlee** [p0deje/Maccy#113]
The recent commit [Add preferences window](https://github.com/p0deje/Maccy/commit/ec2e41be7d65788ad5583e6f502c4c52e9ed427e), seems to have an oversight where choosing to uncheck 'Show footer' (ie hiding the footer) removes the 'Preferences…' option in the footer of the Maccy dropdown—which isn't totally unexpected and may be an acceptable UX. But where I think it really becomes a problem is that it also disabled the <kbd>COMMAND (⌘)</kbd> + <kbd>,</kbd> shortcut. So a user ends up in a situation where they can't get to the Preferences window unless they look through the repo and can figure out how to run a certain command in the terminal.

After discovering the issue and trying to resolve it by: removing the app, restarting the computer, reinstalling the app, checking for the 'Preferences…' choice and not seeing it, removing the app again and the associated Maccy files and directories in `Library` and `ApplicationSupport`, restarting the computer again, and installing the app again I couldn't get the default settings back (the footer remained hidden), I started looking through the repo. I finally figured out running `defaults write org.p0deje.Maccy hideFooter false` could fix it.

I'm unable to be of any help fixing the issue so that a user can always get to the Preferences window (at least via the keyboard shortcut) since I don't know the first thing about Swift. But hopefully someone can look into this.

By the way, the app seems great as I've used it for about a year and I recommend it to my Mac-user friends. So thank you.

**Comment by p0deje** [comment]
Thanks for the report. In the next version, it will be possible to use CMD+, to open Preferences even if the footer is hidden.

**Comment by p0deje** [comment]
I think we can do the following:

* option+⌫ removes the individual entry
* command+⌫ removes all unpinned entries
* command+option+⌫ removes all items

please let me know if it sounds good?

**Comment by Gsazraetr** [comment]
It’s really admirable of you to be giving such consideration to a random user’s ideas.

Yes that would work absolutely fine—ultimately it’s a matter of getting used to whatever the shortcut is. 
Feel free to go ahead and implement this, or whatever you feel best fits your vision for your app.

Very personally, for me, I don’t really see myself ever using the **`Clear all`** feature, footer or no footer. There was a reason the pinned items were pinned, and if I did want to delete any I would only do so individually.
As for the regular unpinned **`Clear`**, I would personally ideally prefer the shortcut to be more complex than the one for individual items, i.e. using one more modifier key.
(With this reasoning, perhaps **`Clear all`** could use yet one more key.)

Thanks once again, and keep up the great work, whatever you decide.

PS: I just noticed that the original hidden footer issue also applies to **`Quit`** ⌘+Q.

**Comment by p0deje** [comment]
The shortcuts added in 9ee385906e6c8798a3491214196087c1330e3865:

*  <kbd>⌥+⌫</kbd> removes an individual entry
*  <kbd>⌘+⌥+⌫</kbd> removes all unpinned entries
* <kbd>⇧+⌘+⌥+⌫</kbd> removes all unpinned entries

They will also work with the hidden footer. Will be released in the next version

**Comment by Gsazraetr** [comment]
Bravo.

**Comment by abderrahmane-tj** [comment]
👋🏼 @p0deje I think there is a bigger issue at work here. I think the size of the history is dictating the height of the popup, these last 4 entries on it 
![image](https://user-images.githubusercontent.com/302837/202163220-7d0bdec1-8898-46bc-b1c6-c60fe3f8376e.png)
are treated as just any other element on the list rather their own separate section.
would it be possible to make 

- Search bar
- Container of the history items
- Container of footer actions

be separate visual components that would make them always visible and close to hand for visual need and for access with the mouse?
Then the `Container of the history items` could be set to a reasonable size and make it scrollable perhaps.

Another option is to only have 

- Container to header items
  - Maccy
  - Search bar
  - Cog wheel, which opens a sub menu
    - Clear all
    - Preferences
    - About
    - Quit
- Container of the history items

What do you think?
