### ISSUE TITLE
Maccy crashes daily

### ISSUE THREAD

**Issue by philihub** [p0deje/Maccy#114]
With Version 10 Maccy crashes once every day. I cannot make out the reason or any condition that makes it crash.

system-log says
`Jun  9 13:50:24 Macbook com.apple.xpc.launchd[1] (org.p0deje.Maccy.24604[524]): Service exited due to SIGILL | sent by exc handler[524]`

**Comment by p0deje** [comment]
1. Could you please post the results of running `defaults read org.p0deje.Maccy` in Terminal?
2. Do you happen to use XCode? I've just found that copying certain things in Interface Builder could cause a crash.

**Comment by philihub** [comment]
1:
```
{
    "NSStatusItem Visible Item-0" = 0;
    "NSWindow Frame SUUpdateAlert" = "-1006 536 620 392 -1440 173 1440 877 ";
    "NSWindow Frame com.sindresorhus.Preferences.FrameAutosaveName" = "-956 342 519 595 -1440 173 1440 877 ";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2020-06-07 19:20:34 +0000";
    SUSendProfileInfo = 0;
    SUUpdateRelaunchingMarker = 0;
    fuzzySearch = true;
    hideSearch = true;
    hideTitle = true;
    history = {length = 20250733, bytes = 0x62706c69 73743030 af10c800 01000b00 ... 00000000 0134ecdd };
    historySize = 200;
    hotKey = "command+control+x";
    ignoredPasteboardTypes =     (
        "Pasteboard generator type",
        "com.typeit4me.clipping",
        "de.petermaurer.TransientPasteboardType"
    );
    imageMaxHeight = 40;
    migrations =     {
        "2020-02-22-history-item-add-copied-at" = 1;
        "2020-02-22-history-item-add-number-of-copies" = 1;
        "2020-02-22-introduce-history-item" = 1;
        "2020-04-18-switch-storage-to-core-data" = 1;
        "2020-04-25-allow-custom-ignored-types" = 1;
    };
    pasteByDefault = true;
    popupPosition = cursor;
    showInStatusBar = 0;
}

```

2: nope, no XCode running

**Comment by saifat29** [comment]
I am facing this issue too.

**Comment by p0deje** [comment]
Could you try with 0.11.0? Please note that auto-update won't work since the newer version of the app is notarized, so you'll need to download it from the releases page.

**Comment by saifat29** [comment]
I can confirm that after installing v0.11.0 Maccy is stable and hasn't crashed even once since yesterday.

**Comment by fschroder-slyp** [comment]
Same here, new version hasn't crashed once in 48hs

**Comment by p0deje** [comment]
@philihub What about you?

**Comment by philihub** [comment]
@p0deje Can confirm, it is stable now. Took a bit more time cause I wanted to make sure 🙂 👍🏼
