### ISSUE TITLE
Crashes with 44342 illegal hardware instruction

### ISSUE THREAD

**Issue by synox** [p0deje/Maccy#115]
on macOS 10.15.4 (19E287)
and Maccy 0.10.0 and also 0.11.0

    defaults delete org.p0deje.Maccy
    brew cask reinstall maccy

Open Maccy in Finder to approve unsigned application

In terminal: 

    /Applications/Maccy.app/Contents/MacOS/Maccy

click the try icon. Then the terminal prints and quits Maccy with exit code `132`: 

    [1]    44342 illegal hardware instruction  /Applications/Maccy.app/Contents/MacOS/Maccy

❯ defaults read org.p0deje.Maccy
```
{
    SUHasLaunchedBefore = 1;
    history = {length = 42, bytes = 0x62706c69 73743030 a0080000 00000000 ... 00000000 00000009 };
    ignoredPasteboardTypes =     (
        "de.petermaurer.TransientPasteboardType",
        "com.agilebits.onepassword",
        "com.typeit4me.clipping",
        "Pasteboard generator type"
    );
    migrations =     {
        "2020-02-22-history-item-add-copied-at" = 1;
        "2020-02-22-history-item-add-number-of-copies" = 1;
        "2020-04-18-switch-storage-to-core-data" = 1;
        "2020-04-25-allow-custom-ignored-types" = 1;
    };
    showInStatusBar = 1;
}
```

**Comment by synox** [comment]
All binaries crashed. Removing the Library folders worked. 

![image](https://user-images.githubusercontent.com/2250964/84352155-19e79f00-abbd-11ea-98fe-1d3c387f69a0.png)

**Comment by p0deje** [comment]
Please upgrade to 0.12. In order to upgrade, either install from Github if you can't start Maccy or cleanup the history by removing `~/Library/Application Support/Maccy/Storage.sqlite` file - that should allow Maccy to start so you could upgrade.
