### ISSUE TITLE
accessibility request

### ISSUE THREAD

**Issue by FernandoMiguel** [p0deje/Maccy#119]
i keep getting this
<img width="456" alt="Screenshot 2020-06-11 at 12 40 53" src="https://user-images.githubusercontent.com/168366/84381372-d99a1800-abe0-11ea-8c27-027da7883dd0.png">

but i've granted it access and restarted the app
<img width="637" alt="Screenshot 2020-06-11 at 12 41 54" src="https://user-images.githubusercontent.com/168366/84381427-f33b5f80-abe0-11ea-8a64-4cb1d839865b.png">

**Comment by p0deje** [comment]
0.11 is now notarized so macOS thinks of it as a new app. Please, unlock, remove Maccy.app and then try to grant permissions again.

**Comment by FernandoMiguel** [comment]
worked great
