### ISSUE TITLE
Customizable key bindings

### ISSUE THREAD

**Issue by ilearnio** [p0deje/Maccy#12]
Right now I have to adjust the key binding in the sources manually and compile the project myself because I got used to `cmd+shift+v`, but the default keybinding is hardcoded as `cmd+shift+c` which feels more like copying to me, rather than pasting.

Would be cool if there would be an option in preferences or at least some config file where it can be changed.

**Comment by frank-f** [comment]
Does 
`$ defaults write org.p0deje.Maccy hotKey command+shift+v`
like suggested in the description not work?

**Comment by ilearnio** [comment]
Hm, I guess missed that part when went through readme. Good to know, that's even better than any configs 😄👍Will close the issue
