### ISSUE TITLE
Preview for copied images

### ISSUE THREAD

**Issue by PkAIR** [p0deje/Maccy#122]
I was using maccy for two days in a row and finally came across this idea:
currently when you open main window you’ll see a list of copied items and you can browse through them using arrow keys. when text doesn’t fit the maccy window you can choose it using keys and a new section next to the line will show you full copied text. 

unfortunately this function doesn’t work for images (it shows only hint how to delete or pin this item). 

so, my idea is to bring similar functionality for copied images like when you choose a copied screenshot a larger preview should pop up next to its miniature. 

what do you think?

**Comment by p0deje** [comment]
I had this idea, but I haven't found a simple way to implement it. The popup is implemented using `toolTip` of `NSMenuItem` and it only allows to render text.

PRs are more than welcome until I find a way to implement this. 😄

**Comment by PkAIR** [comment]
@p0deje I see 😃will think about it

**Comment by p0deje** [comment]
Closing as there is no progress.
