### ISSUE TITLE
Editable list of copies

### ISSUE THREAD

**Issue by damenleeturks** [p0deje/Maccy#127]
It'd be convenient to be able to see and edit the list of copied text without needing to pull up the menu. Even something as simple as a plist file.

**Comment by p0deje** [comment]
It's a bit more complex than just a plist file. Why would you want to do that?

**Comment by damenleeturks** [comment]
I often need to jump between the tasks I need the multiple pasteboard values for and other tasks that need copying and pasting (e.g., moving code back and forth from Confluence and my code editor). It'd be nice to be able to either toggle Maccy on and off or be able to clear out entries en masse.

**Comment by p0deje** [comment]
You can toggle Maccy on/off in Advanced preferences or using https://github.com/p0deje/Maccy#ignore-copied-items. Would that work in your case?

**Comment by damenleeturks** [comment]
It would if I could remember to do it. :)

Honestly, it might help if there were a keyboard shortcut for toggling it on and off. Is there?

**Comment by p0deje** [comment]
No, there is no such shortcut. You could potentially automate this with AppleScript and assign it to keybinding, but I'm not sure this should be a part of Maccy itself. I also know some folks do this from Bash scripts and it works fine for them.

For everyone, please react with 👍 if you believe this feature (global shortcut to turn off Maccy) would be useful for you or react with 👎 if not.

**Comment by pokekrishna** [comment]
It'd be really useful while doing extremely sensitive copy-paste actions.

Example: during banking log-ins where people copy their credentials. I know its not ideal to copy-paste credentials but ...

**Comment by p0deje** [comment]
> Example: during banking log-ins where people copy their credentials. I know its not ideal to copy-paste credentials but ...

There are already mechanisms to ignore copied credentials via pasteboard types.

**Comment by p0deje** [comment]
I lean towards closing as since:

1. There is already a mechanism to turn off Maccy programmatically (using `defaults`).
2. There is already a mechanism to ignore pasteboard types.

Feel free to reopen if you believe these 2 are insufficient. In the future, I might add support for ignored apps list which will make it even easier.
