### ISSUE TITLE
Feature suggestion: Snippets like ClipMenu

### ISSUE THREAD

**Issue by programmieraffe** [p0deje/Maccy#130]
Maccy does a good job as Clipboard Manager, thanks for providing it as Open Source! I especially love that it ignores 1password paste actions.

But I came from ClipMenu and I loved the snippets feature as well
https://github.com/naotaka/ClipMenu

![image](https://user-images.githubusercontent.com/777278/86108797-ed3fec80-bac3-11ea-9407-360865ba9a8a.png)

Use-Case: Store and paste your work phone number

ClipMenu is outdated and crashes sometimes, I would really love to see a similar feature in Maccy :-) Keep up the good work and thanks agaign for providing it as OS!

**Comment by p0deje** [comment]
You can pin your phone number so it will stay on top (or bottom) of the list. Would that be enough?

**Comment by p0deje** [comment]
Please go with pins for now.

**Comment by programmieraffe** [comment]
Thanks @p0deje for the answer, sorry that I didn't reply earlier. I'll try the pin feature :+1:
