### ISSUE TITLE
How to open Preferences if footer is disabled

### ISSUE THREAD

**Issue by Loreno10** [p0deje/Maccy#131]
Hello,
I'd like to change some things in the preferences pane, however, I do not know how to open it. When I still had access to it, I unchecked the "show footer" option. After that, there is not clear option to open Preferences. At least I do not see it. Am I missing something?

**Comment by MonwF** [comment]
try with `COMMAND (⌘) + c`

**Comment by p0deje** [comment]
I guess I need to create FAQ :)

<img width="307" alt="Screen Shot 2020-07-06 at 20 35 01" src="https://user-images.githubusercontent.com/665846/86676014-32828380-bfc8-11ea-8abf-8b5c20f9b405.png">

**Comment by iamrajukh** [comment]
If anyone still face the issues; Just press the shortcut to open Maccy clipboard, then press (⌘,) ✅ ✅
