### ISSUE TITLE
Slow response

### ISSUE THREAD

**Issue by saeedseyfi** [p0deje/Maccy#133]
> Maccy is a lightweight clipboard manager...

Hey @p0deje,
Thanks for the new updates, but it seems Maccy is going the wrong way, getting slower and slower.
Please consider improving the performance (and I would suggest stop adding features, keep it simple and fast).

As a user I want to use the maximum history capacity (999), and when I press the shortcut it loads the popup quickly, I can search quickly, and if I copy a huge item that makes the clipboard manager slow, it might can skip saving it (if this is the reason).

**Comment by p0deje** [comment]
Fair enough, I'll set myself to use 999 size and compare performance with older versions.

**Comment by saeedseyfi** [comment]
Can I export the items saved in Maccy somehow?
Then I will be able to analyse what is wrong with it. i.e I might have copied multiple huge file contents that slows Maccy down.

With the analyse results, we can come up with solution like _dropping huge items earlier than others_.

**Comment by p0deje** [comment]
The history is stored in `~/Library/Application Support/Maccy/Storage.sqlite` and you can analyze it with any database explorer which supports SQLite.

**Comment by saeedseyfi** [comment]
history size is set to 999:
<img width="580" alt="Screenshot 2020-07-07 at 14 24 02" src="https://user-images.githubusercontent.com/5411866/86781874-bdae5880-c05e-11ea-8e5f-965d783d9372.png">

2000 rows in historyitem table
<img width="307" alt="Screenshot 2020-07-07 at 14 23 06" src="https://user-images.githubusercontent.com/5411866/86781902-c69f2a00-c05e-11ea-9353-2cc737cead2e.png">

8136 rows in historyitemcontent table
<img width="363" alt="Screenshot 2020-07-07 at 14 22 37" src="https://user-images.githubusercontent.com/5411866/86781922-cdc63800-c05e-11ea-9494-662b7d737b02.png">

historyitemcontent table ordered by value length
the top contents are code, image, and font
<img width="1060" alt="Screenshot 2020-07-07 at 14 26 51" src="https://user-images.githubusercontent.com/5411866/86781958-d7e83680-c05e-11ea-90a4-ff3cae06c689.png">

**Comment by p0deje** [comment]
Hm, there definitely should not be 2k of items.
It would be helpful if I could also inspect the database assuming there is nothing confidential there. If not, I'll see how I could set something similar up.

**Comment by saeedseyfi** [comment]
Yep I'm not quite confident to share the database. But I can check anything you need, just let me know.

**Comment by saeedseyfi** [comment]
One interesting thing, I just cleared the history using the option in the menu. Then I checked the DB again.
160 rows in historyitem table, and around 670 items in historyitemcontent. Seems strange.

**Comment by p0deje** [comment]
Any chance those might be pinned?
Could you manually inspect some of these items and contents?

**Comment by p0deje** [comment]
Also, can you show the output of `defaults read org.p0deje.Maccy`?

**Comment by p0deje** [comment]
So far I've identified 1 place for improvement. When the menu opens it builds all menu items from scratch. In the beginning, I used to keep the menu items in memory which was faster but was a pain to keep in sync with all the possible changes (sorting, adding new copies, moving old copies, removing). Eventually, I abandoned this approach in favor of building the list every time the menu opens. Now the performance is too slow.

I'm going to rework this and return on keeping the menu items list in memory. This is not a trivial task given all the possible changes the list needs to take into account. Still, it will make the initial menu popup and up(pinning) items almost instant. Hopefully, the new architecture will also make make search faster.

**Comment by saeedseyfi** [comment]
Sorry for the late reply

> Any chance those might be pinned?

Nope, I have no items pinned. Also after clearing, I verified the menu was complete empty.

> Could you manually inspect some of these items and contents? Maybe there is something strange there.

They were mostly copied code from my IDE
I cleaned the history again, this time it left less items in the database, some code again.

> Also, can you show the output of defaults read org.p0deje.Maccy?

```
{
    "KeyboardShortcuts_popup" = "{\\"carbonModifiers\\":768,\\"carbonKeyCode\\":9}";
    "NSStatusItem Visible Item-0" = 0;
    "NSWindow Frame SUUpdateAlert" = "330 301 620 392 0 0 1280 777 ";
    "NSWindow Frame com.sindresorhus.Preferences.FrameAutosaveName" = "380 158 486 528 0 0 1280 777 ";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2020-07-13 11:30:53 +0000";
    SUSendProfileInfo = 0;
    SUUpdateRelaunchingMarker = 0;
    history = {length = 353279, bytes = 0x62706c69 73743030 af1107d0 0001000a ... 00000000 0004c25b };
    historySize = 2000;
    hotKey = "command+shift+v";
    ignoredPasteboardTypes =     (
        "com.typeit4me.clipping",
        "com.agilebits.onepassword",
        "Pasteboard generator type",
        "de.petermaurer.TransientPasteboardType"
    );
    maxMenuItems = 20;
    migrations =     {
        "2020-02-22-history-item-add-copied-at" = 1;
        "2020-02-22-history-item-add-number-of-copies" = 1;
        "2020-02-22-introduce-history-item" = 1;
        "2020-04-18-switch-storage-to-core-data" = 1;
        "2020-04-25-allow-custom-ignored-types" = 1;
        "2020-06-19-use-keyboardshortcuts" = 1;
    };
    pasteByDefault = true;
    showInStatusBar = 0;
}
```

**Comment by saeedseyfi** [comment]
Not sure if holding a copy of all the content in memory is the best approach, since it will grow over time and it's redundant. Syncing memory and database will be another challenge soon.

**Comment by saeedseyfi** [comment]
There are some points I would consider when building the menu, that improves the performance, not sure if Maccy is already doing:
- Limit the select query by the number of items that is going to be shown in the menu.
- Index the first few charters (or thumbnail for images) in another column and select and build the menu with them (instead of full content, that might be huge, even larger than a MB).
- Drop the items that are bigger than a threshold (maybe configurable in preferences) earlier. For instance if I copy an image that is bigger than 500k Maccy it can drop it after a day. It can happen for text (especially code) when we copy a huge json file for example, Maccy is keeping it (and searching in it) for ever.

**Comment by p0deje** [comment]
> historySize = 2000;

This explains why you had so many items in history.

**Comment by saeedseyfi** [comment]
Yeah I can remember I have set the history size to 2000 when there was no preferences window.

**Comment by saeedseyfi** [comment]
What is the fix for it? Should I set it manually to 999?

**Comment by p0deje** [comment]
Yes, I just tried to set it to 2000 in Terminal and then changed to 999 successfully using preferences.

**Comment by p0deje** [comment]
I've just pushed 6bd7738e67c862421e285411b5a56f3f304923a8 which makes the popup much faster. I'm going to spend a few days to gather 999 history items and see how it behaves.

With the search, the slowest part is hiding/showing menu items and there is not much we can do about it. To make search fast, you can also limit visible menu items size to avoid slow hide/show operations. Another idea I have is to only execute the search when typing is finished - this will allow to only perform slow operations when necessary.

**Comment by p0deje** [comment]
Please try to use 0.14.0 - the popups should be much faster now.

**Comment by saeedseyfi** [comment]
I have installed it and TBH it's really faster now 👍

**Comment by p0deje** [comment]
Great! What do you say if we close this issue for now and open a specific one for other parts that are slow?

**Comment by saeedseyfi** [comment]
Sure
