### ISSUE TITLE
Request: Save Text Only (Ignore Images)

### ISSUE THREAD

**Issue by clarkewd** [p0deje/Maccy#134]
First, thank you for writing such a wonderful tool and also for making it open source ☺️

It would be nice if there was an easy way to prevent things other than text from being added to the history.

For now I've added a few entries to the "Ignored pasteboard types" and this seems to be working:

<img width="598" alt="Window 2020-07-09 at 12 40 37" src="https://user-images.githubusercontent.com/156377/87066978-697fb180-c1e1-11ea-88ac-baad94f8c8fc.png">

I saw that Apple recognizes a type `public.image` but this didn't seem to work so I used the `ClipboardViewer.app` mentioned [here](https://superuser.com/questions/246714/app-to-view-clipboard-contents-on-osx-in-unformatted-hex-form) to try and determine the types I should exclude:

<img width="474" alt="Window 2020-07-09 at 12 45 20" src="https://user-images.githubusercontent.com/156377/87067471-15c19800-c1e2-11ea-9214-dee9694a564f.png">

It was a little tricky but so far I've come up with:

    public.tiff
    public.png
    public.jpeg
    public.gif

I use the clipboard manager for coding so if there is an easy way to create an option to "save only text" ( text, rtf, html, etc - but not images, video, sounds, etc ) that would be ideal. 

### If that is too complicated maybe even just add info on the current pasteboard type to the bottom of the "Advanced" preferences tab to help in figuring out what types users could add?

Thank you again for creating such a wonderful software.

**Comment by p0deje** [comment]
Currently, Maccy only maintains the history of the following types https://github.com/p0deje/Maccy/blob/8d3bb5ed2c5789972f8726b8191e261f684b521f/Maccy/Clipboard.swift#L19-L24. I should probably make this list configurable via preferences (with all enabled by default) so you could just disable "Images" or "Files" if you want.

**Comment by p0deje** [comment]
I've been working on this configuration and I would like to hear your and others' opinion on this. 

It's now possible to configure types of data to store:

<img width="455" alt="Screen Shot 2020-08-04 at 16 29 12" src="https://user-images.githubusercontent.com/665846/89341671-a3709600-d66f-11ea-8bb1-02e408c9f6f3.png">

It works great for simple copies, but it's not clear what to do for more complicated ones. Imagine you have "Images" disabled and "Text" enabled. What should happen when we copy something that contains _both_ image and text. What should happen to such copy:

1. Maccy should ignore the whole copy.
2. Maccy should store the whole copy
3.. Maccy should alter the copied data and remove images?

An example of such a scenario is copying multiple cells in Number.app. They are copied as rich text, string, and image.

**Comment by p0deje** [comment]
@clarkewd Any thoughts on ☝️?

**Comment by p0deje** [comment]
> LGTM

Which option exactly? 😄 I proposed 3 different ones for behavior.

**Comment by FernandoMiguel** [comment]
2)
all data, and do its best to paste as was

**Comment by p0deje** [comment]
But then a user would still see images even though they explicitly unchecked keeping images. That seems like a bad UX.

**Comment by fturcheti** [comment]
I'm interested in this feature mostly because I'd like to disable the storage of files in the clipboard, but giving my feedback on the question above:

> What should happen when we copy something that contains _both_ image and text. What should happen to such copy:
> 
>     1. Maccy should ignore the whole copy.
>     2. Maccy should store the whole copy
>     3. Maccy should alter the copied data and remove images?

I think the correct would be 3. If I want to store texts and don't want to store images, I'd like to get the textual part of the selection and get rid of the images in between.

**Comment by clarkewd** [comment]
Sorry for the delayed reply. Your addition looks great and I think will be very helpful for folks trying to disable images. As for mixed types, I'd be in favor of option 3:

> Maccy should alter the copied data and remove images?

This is pretty similar to how [Ditto Clipboard Manager](https://ditto-cp.sourceforge.io/) can be setup.

It has options for which types you want to store, so I was able to remove non-text formats. See below. On mixed types, it just copies the text but not the image.

![Screen Region 2020-12-14 at 21 13 55](https://user-images.githubusercontent.com/156377/102159347-60120980-3e51-11eb-8f95-a38c4eb24e3e.png)

I also really liked that Ditto allowed me to easily paste **plain text** anywhere, and to set that as the default paste option, even if I had copied rich-formatted text, with their "Text Only Paste" option:

![Screen Region 2020-12-14 at 21 15 52](https://user-images.githubusercontent.com/156377/102159780-30afcc80-3e52-11eb-94e8-73e09a9decdb.png)

So with that software my workflows were this:

### Normal Behavior

1. Copy an image, file, rich text, etc. as normal
1. Paste it normally using `control+v` ( good for Photoshop, Word, Emails, moving files, etc. - doesn't require any re-learning and works with all existing programs )

### Plain text

1. Copy rich text as normal
1. Paste plain text using customizable shortcut ( mine was `control+shift+v` on Windows - allows quickly and easily removing formatting, which I need quite often )

### Search / paste plain

1. Launch the clipboard manager - I think the default shortcut is `control + ~`
1. Another amazing thing is that typing after this shortcut in Ditto immediately searches / narrows the list without any additional clicks or arrow keys, and will automatically highlight the topmost result allowing it to be pasted by pressing `return` 
1. It's possible to configure this behavior so that selecting the result always pastes it as plain text
1. If images and other types are allowed to be saved via the previously mentioned "Supported Types" preference they will be shown in the list alongside the other text - but after removing the supported types only the plain text of whatever was copied ( if applicable ) will be saved in the history. For me that was the main purpose of opening this feature request.

Alex, thank you for your work on Maccy. It is by far the BEST, fastest, and most intuitive clipboard manager for OS X that I've found and since I found it I've been using it heavily every day. Before finding it I spent tens of hours searching, researching, testing, and comparing different clipboard managers. So thank you very much.

**Comment by p0deje** [comment]
Thanks for a detailed explanation, I'll wrap up the work on supported types by altering the copy entry and removing the undesirable types before pasting.

**Comment by clarkewd** [comment]
Thank you!
