### ISSUE TITLE
bug: window moves up when delete search text

### ISSUE THREAD

**Issue by nemoii** [p0deje/Maccy#137]
1. open search window and type some text that will match nothing, and we get an empty search result.  
2. delete the search text, and then the search window moves up a little.

**Comment by nemoii** [comment]
software version: 0.13.0
os version: 10.15.5

**Comment by p0deje** [comment]
I can see this happening sometimes, but I am not aware of any way to control the window. This happens automatically by macOS menu window resizing logic. The window is hardcoded NSCarbonMenuWindow which cannot be customized.

Please re-open if there is a way to make it work more reliably.
