### ISSUE TITLE
Allow searching for a substring

### ISSUE THREAD

**Issue by grossjohann** [p0deje/Maccy#138]
If I have, say, `bla.xml` and `/Users/jrl/git/foo/bla.xml` in my list of snippets, and I type `bla` into the search field at the top, I find `bla.xml` but not `/Users/jrl/git/foo/bla.xml`.

Yes, I can search for `/Users` to find the absolute file name I'm looking for, but all of my absolute file names start like that, so it's not a good differentiator...

I tried to search for `.*bla` (inspired by regexes), `*bla` (inspired by shell globs), and `%bla` (inspired by SQL "LIKE" wildcards).

**Comment by p0deje** [comment]
I cannot reproduce with your examples. Both entries are found both with simple and fuzzy search.

<img width="469" alt="Screen Shot 2020-07-21 at 05 46 25" src="https://user-images.githubusercontent.com/665846/88039476-9c953f80-cb15-11ea-9981-4febf201de68.png">

**Comment by grossjohann** [comment]
Thank you, yes, indeed.  It is working for the example I gave, but it fails for this one:

`/Users/jrl/git/foo/bar/baz/foo/bar/baz/foo/bar/baz/some/long/directory/name/here/bla.xml`

The above one I can't find by searching for "bla".

**Comment by grossjohann** [comment]
I notice that the long example I just gave is truncated in the list, and only the tooltip shows the full string.

**Comment by p0deje** [comment]
I still can't reproduce. What version of Maccy do you have?

**Comment by p0deje** [comment]
<img width="740" alt="Screen Shot 2020-07-21 at 09 30 33" src="https://user-images.githubusercontent.com/665846/88061902-1dfcca00-cb36-11ea-855f-9c936fe75e14.png">

**Comment by grossjohann** [comment]
Interesting.  I have 0.13.0, installed via Homebrew.

**Comment by grossjohann** [comment]
Hm.  So I tried copying this string again, and "bla" found it, but it was listed way down.  I have fuzzy search turned on.  I wonder if the problem is the similiarity score?  I intuitively expected the strings to be listed by time.  (The corresponding setting is "sort by time of last copy".)  But perhaps fuzzy search adds some other ranking?

**Comment by p0deje** [comment]
Fuzzy search ranks differently, so the default sorting is ignored during a search. It seems like a simple search will fit better in your case.

> I hit the hotkey for Maccy (which I have changed to cmd-shift-V). So I was expecting that the long string should be listed near the top. But actually it was way below the first nine positions, at position 12 or 13 or so.

Do you have any items pinned? Can you show what you running `defaults read org.p0deje.Maccy` prints in Terminal?

**Comment by grossjohann** [comment]
I haven't consciously pinned any items.  I see that option-P does this and I tried to never hit it.

What is the difference between simple search and fuzzy search?  Perhaps it is that entering "abc" into fuzzy search will find "axxbxxcxx"?

Command shown below.

```
~ $ defaults read org.p0deje.Maccy
{
    "KeyboardShortcuts_popup" = "{\\"carbonModifiers\\":768,\\"carbonKeyCode\\":9}";
    "NSWindow Frame SUUpdateAlert" = "659 498 620 392 0 0 3840 2137 ";
    "NSWindow Frame com.sindresorhus.Preferences.FrameAutosaveName" = "717 314 581 506 0 0 1920 1057 ";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2020-07-21 05:52:25 +0000";
    SUUpdateRelaunchingMarker = 0;
    fuzzySearch = 1;
    history = {length = 42, bytes = 0x62706c69 73743030 a0080000 00000000 ... 00000000 00000009 };
    hotKey = "command+shift+V";
    ignoredPasteboardTypes =     (
        "de.petermaurer.TransientPasteboardType",
        "com.agilebits.onepassword",
        "Pasteboard generator type",
        "com.typeit4me.clipping"
    );
    migrations =     {
        "2020-02-22-history-item-add-copied-at" = 1;
        "2020-02-22-history-item-add-number-of-copies" = 1;
        "2020-04-18-switch-storage-to-core-data" = 1;
        "2020-04-25-allow-custom-ignored-types" = 1;
        "2020-06-19-use-keyboardshortcuts" = 1;
    };
    pasteByDefault = 1;
    popupPosition = center;
}
```

**Comment by grossjohann** [comment]
I can confirm that normal search finds the items as I expected, and shows them in chronological order.

I will go with normal search for the time being, and I guess I will notice whether I miss the fuzzy search.

But if fuzzy search ranks longer strings lower than shorter strings for the same query, then I feel this is not a good ranking.  The queries will always tend to be short (user enters just enough characters to find the thing they are looking for), but the user will not prefer shorter strings to longer strings.

For example, if the history has "foobar" and "foobarquux" in it, and I enter "foo" as a search string (using fuzzy search), I don't think that we should rank "foobarquux" lower than "foobar".

And if the history has "axxbxx" in it as well as "ab0123456789", and I search for "ab", then I guess I prefer "ab0123456789" over "axxbxx" because the former contains "ab" as a substring.

**Comment by p0deje** [comment]
Thanks for the input! I'm not sure how exactly the fuzzy search is implemented as I simply use https://github.com/krisk/fuse-swift package for that. I believe we can consider this issue closed and if you believe there are fundamental issues with the current fuzzy search implementation, let's raise a separate issue with more examples of what you'd expect vs what you get.
