### ISSUE TITLE
Request: Edit entries

### ISSUE THREAD

**Issue by alexsereno** [p0deje/Maccy#140]
Enable action (option+e?) to edit text-based clipboard items. 

- Allows you to have a reference open while you make a edit to a URL, for example.
- Allows you to remove part of a clipping after copy if it wasn't intended
- Allows you to strip sensitive parts of a copy if needed
- Allows you to add text searchable by maccy to find specific copies relating to things, in lieu of a titling system (ex: can manually throw in "[Xcode]“ in front of "Copied item 12" so that I can later search for "Xcode" and get any Xcode-related clippings)

**Comment by p0deje** [comment]
> Allows you to have a reference open while you make a edit to a URL, for example.

Can you elaborate? I don't understand what this means.

> Allows you to remove part of a clipping after copy if it wasn't intended
> Allows you to strip sensitive parts of a copy if needed

I don't intend to implement this. Maccy is designed to be a simple solution so if you need to edit part of copy, it's recommended to do it in the editor.

> Allows you to add text searchable by maccy to find specific copies relating to things, in lieu of a titling system (ex: can manually throw in "[Xcode]“ in front of "Copied item 12" so that I can later search for "Xcode" and get any Xcode-related clippings)

I plan to implement aliases (or editable titles) for pinned items. The work will be tracked in #89.

**Comment by alexsereno** [comment]
Makes sense, thanks! #89 resolves
