### ISSUE TITLE
Donation method

### ISSUE THREAD

**Issue by seupedro** [p0deje/Maccy#142]
Hi, do you have a paypal account? Cause I would like to contribute with this project. But after the coronavirus, the dollar became really expensive here. 💸

Anyways I still would like to contribute and pay to you a coffee cost of my country. Although it gonna be remains more symbolic than valuable. 🎁

**Comment by p0deje** [comment]
Thank you for the offer, I am touched and appreciate it! I'm going to set up https://www.buymeacoffee.com account for donations in the future, but that's yet to be done.

**Comment by p0deje** [comment]
I've signed up for https://www.buymeacoffee.com/p0deje and I'll be grateful for donations there.

**Comment by p0deje** [comment]
it doesn't work with Russia

**Comment by FernandoMiguel** [comment]
you got 5 coffees on me.
thank you for your work

**Comment by FernandoMiguel** [comment]
![image](https://user-images.githubusercontent.com/168366/91055679-e7c2d680-e61c-11ea-8826-d16e65d8d491.png)
what a shame
