### ISSUE TITLE
Paste automatically doesn't work

### ISSUE THREAD

**Issue by foray1010** [p0deje/Maccy#148]
HI! I just migrating from [clipy](https://github.com/Clipy/Clipy) to maccy. My setting is as following image, I expected when I click the copied item in maccy's clipboard menu, the value will be automatically paste to the editor like clipy, but nothing happened unless I manually paste.

I am using version 0.15.0 on macOS 10.15.6

<img width="735" alt="Screenshot 2020-08-15 at 9 20 38 AM" src="https://user-images.githubusercontent.com/3212221/90302409-96a63a80-ded8-11ea-86db-a854e2a483c0.png">

**Comment by p0deje** [comment]
Can you confirm Maccy has accessibility permissions? You should see it in "System Preferences" -> "Security & Privacy" -> "Accessibility":
<img width="780" alt="Screen Shot 2020-08-15 at 10 17 38" src="https://user-images.githubusercontent.com/665846/90314287-8e51fd80-dee0-11ea-8bf8-4bb4271ec79d.png">

**Comment by foray1010** [comment]
Maccy doesn't appear in the list of my privacy setting page. Maccy didn't ask for my permission to enable Accessibility neither, which I recall other software usually did.

**Comment by shadanan** [comment]
PR #149

**Comment by foray1010** [comment]
I solved it by manually adding accessibility permission to Maccy

**Comment by adrianbj** [comment]
Even with those accessibility permissions, I still can't get this to work. Running High Sierra - any chance that might be contributing to the problem?

**Comment by p0deje** [comment]
@adrianbj Have you tried to remove Maccy from the list and then add again? If it doesn't help, I might need to set up High Sierra to test there.

**Comment by adrianbj** [comment]
@p0deje - yeah, I have tried that with no luck.

**Comment by p0deje** [comment]
@adrianbj Can I ask you to please create a new issue with more details about Maccy and macOS version?

**Comment by p0deje** [comment]
@adrianbj Just to confirm, the pasting fails, but it doesn't ask for permissions. I can reproduce this on High Sierra. I've created #161 for this.

**Comment by Brachacz** [comment]
For posterity - had the same problem, adding Maccy to Accessiblity manually, removing it, adding it again and restarting Maccy fixed it.
Probably just adding it once would've sufficed too - restarting the app was the secret sauce.

I'm on MacOS Monterey 12.1, Intel.

**Comment by zjxs1997** [comment]
> For posterity - had the same problem, adding Maccy to Accessiblity manually, removing it, adding it again and restarting Maccy fixed it. Probably just adding it once would've sufficed too - restarting the app was the secret sauce.
> 
> I'm on MacOS Monterey 12.1, Intel.

I have the same problem. MacOS Monterey 12.3, Intel

**Comment by krispetkov** [comment]
I'm also facing the same issue. My version is Monterey 12.5.1
I have tried manually adding and removing Maccy from Accessibility, restarting it and so on but it's not working. When I press my shortcut the Maccy's context menu appears (and takes the focus) and when I select an item (with mouse click, shortcut or enter) it just beeps, closes the context menu and nothing is being pasted.

@p0deje am I doing something wrong or am I missing some setting?

**Comment by Meowzen** [comment]
I also have this problem, the workaround doesn't work for me. It just makes a beep noise and doesn't paste. It would be awesome if this could be fixed!
MacOS Monterey 12.5.1, Intel

**Comment by 1Mark** [comment]
In case anyone else has the same issue, I had assumed `Paste automatically` was on by default (and not configurable) so make sure this is on, in addition to the advice [here](https://github.com/p0deje/Maccy/issues/482#issuecomment-1296291391) 
<img width="544" alt="image" src="https://user-images.githubusercontent.com/15360245/209866704-00c406aa-2b87-454b-844a-9dafd00f77a1.png">

**Comment by nicolasalbani** [comment]
> Can you confirm Maccy has accessibility permissions? You should see it in "System Preferences" -> "Security & Privacy" -> "Accessibility": <img alt="Screen Shot 2020-08-15 at 10 17 38" width="780" src="https://user-images.githubusercontent.com/665846/90314287-8e51fd80-dee0-11ea-8bf8-4bb4271ec79d.png">

This comment is still relevant in 2025

**Comment by stanzaalley** [comment]
I've had this issue also. 
The Settings>Privacy & Security>Accessibility Maccy toggle is on.
Sequoia 15.6.1
