### ISSUE TITLE
Show in menu bar what's currently stored in clipboard?

### ISSUE THREAD

**Issue by orschiro** [p0deje/Maccy#152]
Hi @p0deje , 

What do you think of a feature to show the currently stored item next to the icon in the menu bar?

Would be handy see at one glance what's currently stored in clipboard!

**Comment by p0deje** [comment]
That might be useful, but few questions:

1. How should it show long text? 
2. How images should be shown? Smaller versions?
3. How files should be shown?

**Comment by orschiro** [comment]
1. Maybe limit to X characters, e.g. 20
2./3. I would start with text for now and if others deem useful, this can be expanded to images and files in the future. 

What do you think?

**Comment by Stickyhavr** [comment]
Oooh, this is an interesting option. I think ~20 characters would be enough for text. For an image it could just say [image] and for a file it could say [filename.ext] or [truncatedfilen....ext] where the filename shows the first 15 or so characters and then the extension.

**Comment by orschiro** [comment]
Great start indeed!

Stickyhavr <notifications@github.com> schrieb am Mi. 9. Sep. 2020 um 00:49:

**Comment by sbeinlich** [comment]
Was looking into working on this issue. Would this be an optional feature, or the default? 

The reason I ask this--I do not believe there is a way to display both the Maccy logo **and** the current contents of the clipboard in the menu bar with the current Apple APIs.

**Comment by orschiro** [comment]
I think this should be an optional feature! Others may prefer to only have
the Maccy logo.

**Comment by sbeinlich** [comment]
Cool, actually think I found a way to include the logo with the text, I'll look into it

**Comment by orschiro** [comment]
Now, that would be sweet! :)

**Comment by sbeinlich** [comment]
@p0deje I'll try to look into this one if that's okay!

**Comment by p0deje** [comment]
I actually made it work already but haven't finished the configuration setting with all the localizations. I'll be happy to merge PR given it's fully complete.

**Comment by orschiro** [comment]
Wow, nice! :)
