### ISSUE TITLE
Maccy cannot copy from or paste to itself in 0.15.0

### ISSUE THREAD

**Issue by whornsby** [p0deje/Maccy#153]
Trying to copy from either the preferences or about window of Maccy does not work, and neither does trying to copy any text typed into the search bar (in toolbar or popup widget). The same is true for trying to past into the search bar or the ignored pasteboard types list. 

This shouldn't be a problem 90% of the time and is more than an inconvenience than anything, but it might be frustrating trying to copy the command to turn off copying or trying to paste a pasted board type to ignore. I am not impacted by this in anyway so feel free to close/ignore as wish, but I wanted to make you aware of the issue if you weren't already.

**Comment by p0deje** [comment]
The problem with preferences/about is actually a known Apple issue. You can observe the same behavior in standard apps like Safari. You can still copy/paste using a context menu, but standard keybindings don't work indeed. I'm not sure how this can be addressed in general and I'll leave that for https://github.com/sindresorhus/Preferences.
