### ISSUE TITLE
Handle context menu like apps for safety reasons 

### ISSUE THREAD

**Issue by FernandoMiguel** [p0deje/Maccy#155]
I use extensively iterm2 with a hotkey window that for all purposes behaves like a background context menu.

A recent maccy feature changed the behaviour of how this sort of apps are handled.

Since I have to access maccy to find data and sometimes even tokens to paste into the terminal, losing iterm2 window can lead to the risk of pasting sensitive information into other applications.

The sheer number of times I ended up with nonsense snippets in vscode alone, shows how pertinent the support for this is.

**Comment by p0deje** [comment]
Since 4102d7b it's possible to disable the behavior in Advanced preferences.

**Comment by FernandoMiguel** [comment]
yay
cant wait for a new release so i can test this!! :D
