### ISSUE TITLE
Ability to always keep certain items and to label/name them

### ISSUE THREAD

**Issue by sprdnja** [p0deje/Maccy#156]
Hi,

From time to time i copy and paste my server passwords and other things that are used at least once per day. It would be very convenient if we get the ability to always keep certain items in the copied items list and also to name/label them for easier searching. Because my server passwords are random characters it is very hard to remember characters from it for searching the list so naming it or labelling it would save us ton of job.

Thanks.

**Comment by p0deje** [comment]
You can already keep items by pinning them using Option+P. As for labeling, it has been requested in #89 so I'm going to close this issue in favor of it.
