### ISSUE TITLE
Option + click menu bar icon to “turn off”

### ISSUE THREAD

**Issue by Stickyhavr** [p0deje/Maccy#158]
It would be great if there were a quick way to temporarily disable Maccy without closing it. Currently you have to go to preferences and check “turn off” but it would be slick if that option existed in the footer, or if there was a hot key for it.

Perhaps the best solution would be option + click the menu bar icon. The same way you can option-click the Notification Center to turn on Do Not Disturb and the icon goes dark. Maccy could do the same thing.

I’m new to Maccy so I apologize if there is already a quick way to do this. Thanks

**Comment by p0deje** [comment]
Sounds good, I'll see if this can be done.
