### ISSUE TITLE
Accessibility permissions request does not automatically appear

### ISSUE THREAD

**Issue by EeveeEmma** [p0deje/Maccy#159]
When first attempting to paste an item from the menu, I'm prompted to give Maccy accessibility permissions; however, Maccy does not automatically appear in the list of apps in System Preferences. I'm able to add it manually using the + button, but most apps that request permissions are usually already in the list and just need to be checked by the user.

- macOS Catalina 10.15.6
- Maccy 0.15.1

**Comment by p0deje** [comment]
This is a known problem but I'm not sure how to work it around.

**Comment by EsteveAguilera** [comment]
It might be useful to add instructions about how to manually add the app to give it the needed permissions in order to work... I've spent some minutes trying to find the app on the Accessibility apps list, and some more searching for a solution, which I just found here 😅

**Comment by abhidp** [comment]
is this being looked at? its really getting annoyingly annoying

**Comment by p0deje** [comment]
It is not at the moment.

**Comment by p0deje** [comment]
It is not at the moment.

**Comment by abhidp** [comment]
@p0deje any workaround meanwhile?

**Comment by p0deje** [comment]
The workaround is to add Maccy to the list manually using **+** button. Are there any other workarounds?

**Comment by abhidp** [comment]
thanks a ton @p0deje . 
I was about to uninstall Maccy and look for alternatives. 
Manually adding workaround saved it

**Comment by thekaleidoscope** [comment]
calling https://developer.apple.com/documentation/applicationservices/1459186-axisprocesstrustedwithoptions on launch post installation should fix this right?

**Comment by p0deje** [comment]
@thekaleidoscope It's being called, the problem is that sandboxed apps aren't added to the list automatically.

**Comment by marcbrazil** [comment]
just search maccy, maybe can find it at donwloads parte....but even adding the feature does not work

**Comment by josh-panther** [comment]
Encountered this myself, adding my +

**Comment by p0deje** [comment]
I've added GIF that shows how to add Maccy, hopefully it won't be a problem anymore.

**Comment by svenjr** [comment]
Does this still work on Mac OS Ventura? I am not getting this to work with the new setting layout

**Comment by Dellu** [comment]
It is not working on Ventura. 
Even if I added it manually, it keep on asking for permission, rather than pasting.

**Comment by p0deje** [comment]
@Dellu It could happen if you happen to have added a different version of Maccy (e.g. App Store or GitHub). Please remove Maccy from the list and make sure you add exactly the one that you run.
