### ISSUE TITLE
Focus on "Quit" on search

### ISSUE THREAD

**Issue by saeedseyfi** [p0deje/Maccy#16]
Hi,
Thanks for the nice app <3
There is an issue with search functionality:

**What happens:**
- When I start typing(searching), it sets the focus on Quit. Even if there is a result for search!

**Whats expected:**
1. Quit will close the app completely, so it never should get a focus automatically.
2. If there is a result for the searched text, it should focus on the first item.
3. (Optional) You can add Hide option that hides the menu. On search, if there is no result, it can focus on Hide.

Screen record: [Record.mov.zip](https://github.com/p0deje/Maccy/files/3411130/Record.mov.zip)

**Comment by p0deje** [comment]
Thank you for the report!

I have fixed this issue in b5fcf193f15a0b8e87242d394d4d0b59a1bafb7e, but it's not released yet.

**Comment by p0deje** [comment]
Please try v0.3.7 - it should be fixed.

**Comment by saeedseyfi** [comment]
@p0deje How can I get the update by brew?

**Comment by p0deje** [comment]
@saeedseyfi Somebody needs to update https://github.com/Homebrew/homebrew-cask/blob/master/Casks/maccy.rb as it points to 0.3.6

**Comment by saeedseyfi** [comment]
What is the new `sha256` for 0.3.7? I'll create a pr to update the cask.

**Comment by p0deje** [comment]
08e079ae2071bea7e1f011f47ba601b79d9440daa8e80aa5d3946d558a80ab43

**Comment by saeedseyfi** [comment]
@p0deje What do you think if cask gets the latest version?
https://github.com/Homebrew/homebrew-cask/pull/66608/files

**Comment by saeedseyfi** [comment]
@p0deje Please take a look at the this, the build is failing because of the specified `depends_on` in the cask file: https://travis-ci.org/Homebrew/homebrew-cask/builds/562531636
What do you think?

**Comment by p0deje** [comment]
This failure was introduced in #65568, so your changes are unrelated. I don't know how brew/cask maintainers handle such situations.

**Comment by p0deje** [comment]
I should also be possible to just point to the latest version to avoid the need to bump it every time:

```diff
diff --git a/Casks/maccy.rb b/Casks/maccy.rb
index 27abe054d..68a20a450 100644
--- a/Casks/maccy.rb
+++ b/Casks/maccy.rb
@@ -1,8 +1,8 @@
 cask 'maccy' do
-  version '0.3.6'
-  sha256 '314d56cddd34a89443af3995b1a3ddbc63a8d18db12b043309b76ded260c5d83'
+  version :latest
+  sha256 :no_check

-  url "https://github.com/p0deje/Maccy/releases/download/#{version}/Maccy.app.zip"
+  url 'https://github.com/p0deje/Maccy/releases/latest/download/Maccy.app.zip'
   appcast 'https://github.com/p0deje/Maccy/releases.atom'
   name 'Maccy'
   homepage 'https://github.com/p0deje/Maccy'
```

**Comment by saeedseyfi** [comment]
@p0deje Actually I tried this in the first pace: https://github.com/Homebrew/homebrew-cask/pull/66608
But the `appcast` does not recognise `latest` as a valid version. That's why I closed my first PR.
