### ISSUE TITLE
Request: keep the menu icon hidden when re-launching the app

### ISSUE THREAD

**Issue by lulor** [p0deje/Maccy#160]
Currently, if Maccy has the menu bar hidden and it is re-launched, the menu bar icon is restored.
I personally think it would be more intuitive to leave the icon hidden (as set in the preferences) when re-launching the app and open the preferences window instead (or do nothing at all)

**Comment by p0deje** [comment]
That's an old feature that was added back when there was no preference window. @artginzburg What do you think about dropping this feature?

**Comment by lulor** [comment]
Hey @p0deje , I'm sorry to bother you, but is there any "news" about this request? Thank you for considering it in the first place BTW!

**Comment by p0deje** [comment]
I wanted to get feedback from @artginzburg before implementing it.

**Comment by artginzburg** [comment]
> That's an old feature that was added back when there was no preference window. @artginzburg What do you think about dropping this feature?

Sorry for the long wait.
Well, I think the preferences window that is opening on re-launch may get quite annoying for the user. Instead, it would be cool to temporarily show the menu bar item with the clipboard history menu (I've seen this feature in some other app. This is handy).

So, if the user forgets that he already has the app running and re-launches it, he won't be annoyed by the preferences window popping up or by the necessity to manually hide the menu bar item again. At the same time, if he, for example, forgets the combination he set to open the clipboard history, he can just Spotlight > `Maccy` > `⌘` `,` and take a look at the right hotkey.

**Comment by lulor** [comment]
@artginzburg your idea actually sounds much better than mine

**Comment by p0deje** [comment]
I'm going to just popup Maccy menu when the application is opened again. But keep the menu bar visibility intact. Sounds good?

**Comment by lulor** [comment]
@p0deje sounds perfect to me, thank you very much!
