### ISSUE TITLE
Two Features I See Missing

### ISSUE THREAD

**Issue by amer-riaz** [p0deje/Maccy#162]
1. Edit copied text items.
2. iCloud sync.

**Comment by p0deje** [comment]
1. No plans to support this.
2. Why would you need iCloud sync?

**Comment by amer-riaz** [comment]
1. The Editing feature will be helpful and avoid the workaround of deleting a text item and adding a new one.
2. I use two mac computers and iCloud sync will help me reducing effort of adding new items on one computer and then adding them to the other one. I have found a workaround if there will be no iCloud sync: use the Notes app to maintain a list of text items for Maccy.
