### ISSUE TITLE
Pop-up not showing when extra display is positioned above main display

### ISSUE THREAD

**Issue by jorisroovers** [p0deje/Maccy#163]
Thanks for creating Maccy - I just discovered it, it seems like a great tool :-)

The issue I ran into is that the Maccy doesn't show its popup when you have a multi-monitor setup and you have a monitor that is positioned **above** your main display, like so:

![2020-09-06 at 12 51](https://user-images.githubusercontent.com/575086/92324256-500fb000-f040-11ea-82d2-4e8be8f83c45.png)

Repositioning the display to the right/left/bottom of the main display solves this issue. Similarly, I found it easy to reproduce this issue by just positioning any other display above the main display.

I'm on MacOS Catalina (10.15.6) in case that matters.

**Comment by p0deje** [comment]
> The issue I ran into is that the Maccy doesn't show its popup when you have a multi-monitor setup and you have a monitor that is positioned above your main display

Do you mean that Maccy doesn't popup at all or the popup positioned somewhere incorrectly? Also, can you please provide the output of `defaults read org.p0deje.Maccy`?

**Comment by lulor** [comment]
@p0deje I experienced the same issue, there's no popup at all (at least in my case).
Here's my output of `defaults read org.p0deje.Maccy`:

```
{
    "KeyboardShortcuts_popup" = "{\\"carbonModifiers\\":768,\\"carbonKeyCode\\":9}";
    "NSStatusItem Preferred Position Item-0" = "421.0703";
    "NSStatusItem Visible Item-0" = 1;
    "NSWindow Frame SUUpdateAlert" = "650 588 620 392 0 0 1920 1177 ";
    "NSWindow Frame com.sindresorhus.Preferences.FrameAutosaveName" = "685 275 623 611 0 0 1920 1177 ";
    SUEnableAutomaticChecks = 0;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2020-09-05 22:32:38 +0000";
    SUSendProfileInfo = 0;
    hideFooter = 0;
    hideTitle = 1;
    history = {length = 42, bytes = 0x62706c69 73743030 a0080000 00000000 ... 00000000 00000009 };
    ignoredPasteboardTypes =     (
        "Pasteboard generator type",
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "com.agilebits.onepassword"
    );
    maxMenuItems = 50;
    migrations =     {
        "2020-02-22-history-item-add-copied-at" = 1;
        "2020-02-22-history-item-add-number-of-copies" = 1;
        "2020-04-18-switch-storage-to-core-data" = 1;
        "2020-04-25-allow-custom-ignored-types" = 1;
        "2020-06-19-use-keyboardshortcuts" = 1;
    };
    pasteByDefault = 1;
    showInStatusBar = 1;
}
```

**Comment by p0deje** [comment]
By default, it should just pop up at the current cursor location (https://developer.apple.com/documentation/appkit/nsevent/1533380-mouselocation). I don't really have a second screen to debug this issue, so any help is appreciated.

**Comment by jorisroovers** [comment]
Same for me: no pop-up at all.

I just discovered that this issue only happens when **clicking** the tray icon. When using the `SHIFT+CMD+C` keyboard shortcut, Maccy functions as expected - I tried with all 3 Popup locations (Cursor, Screen Center, Menu icon). I did notice some wrong pop-up offset when choosing the *Menu Icon* location (see screenshot), but I believe that might be a different issue.

![2020-09-07 at 10 25](https://user-images.githubusercontent.com/575086/92366897-07b2c980-f0f6-11ea-9cc6-5db4f7a633bf.png)


The currently active window does have it's title-bar "blink" when clicking the Maccy icon, see GIF.


![2020-09-07 at 10 35](https://user-images.githubusercontent.com/575086/92366955-1d27f380-f0f6-11ea-8be6-7a6fd1a41ccc.gif)


Output from `defaults read org.p0deje.Maccy`
```
{
    "KeyboardShortcuts_popup" = "{\\"carbonModifiers\\":768,\\"carbonKeyCode\\":8}";
    "NSStatusItem Preferred Position Item-0" = 418;
    "NSWindow Frame com.sindresorhus.Preferences.FrameAutosaveName" = "621 346 550 540 0 0 1792 1097 ";
    SUHasLaunchedBefore = 1;
    history = {length = 42, bytes = 0x62706c69 73743030 a0080000 00000000 ... 00000000 00000009 };
    ignoredPasteboardTypes =     (
        "de.petermaurer.TransientPasteboardType",
        "Pasteboard generator type",
        "com.agilebits.onepassword",
        "com.typeit4me.clipping"
    );
    migrations =     {
        "2020-02-22-history-item-add-copied-at" = 1;
        "2020-02-22-history-item-add-number-of-copies" = 1;
        "2020-04-18-switch-storage-to-core-data" = 1;
        "2020-04-25-allow-custom-ignored-types" = 1;
        "2020-06-19-use-keyboardshortcuts" = 1;
    };
    pinTo = top;
    popupPosition = cursor;
}
```

Thanks for your help! Any suggestions on how to help debug further?

**Comment by p0deje** [comment]
>  I did notice some wrong pop-up offset when choosing the Menu Icon location (see screenshot), but I believe that might be a different issue.

Yeah, it's positioned a bit differently - I need to change it to just simulate user clicking on the menu bar icon.

> I just discovered that this issue only happens when clicking the tray icon. 

This is interesting. I still need to debug this though, but basically what happens when you click is the following small code which assigns menu to the button and then clicks it again:

https://github.com/p0deje/Maccy/blob/5eb60fd6f1aa5481e2e5233c71641b7e797b8fce/Maccy/Maccy.swift#L136-L144

**Comment by cub-uanic** [comment]
I also have two monitors, and "Screen center" doesn't work properly for me: it pop's up on my "main" screen (and for the first time not by the center of it), but I'm expecting it to appear on the "active" screen.
How I can help to debug it?

**Comment by p0deje** [comment]
> I also have two monitors, and "Screen center" doesn't work properly for me: it pop's up on my "main" screen (and for the first time not by the center of it), but I'm expecting it to appear on the "active" screen.

What do you mean by "main" and "active" screen? I'm using [`NSScreen.main`](https://developer.apple.com/documentation/appkit/nsscreen/1388371-main) to pick the screen to show popup at and according to documentation it should pick the one that has the currently active window:

> The main screen is not necessarily the same screen that contains the menu bar or has its origin at (0, 0). The main screen refers to the screen containing the window that is currently receiving keyboard events. It is the main screen because it is the one with which the user is most likely interacting.

**Comment by cub-uanic** [comment]
"Main" - the display with menu bar, as you see in the Display Preferences.
"Active" -  the display with the application in focus (highlighted menu bar and takes keyboard input).

As I see, my definition of the "active" is most corresponds with Apple's definition of "main".
Sorry for the confusion, I'm a relatively new-comer to MacOS.

**Comment by p0deje** [comment]
> "Active" - the display with the application in focus (highlighted menu bar and takes keyboard input).

That's exactly the screen that is used to calculate the position of menu to popup. I'll need to investigate if maybe there is some other bug there.

**Comment by matoelorriaga** [comment]
I have this exact same issue :)

**Comment by p0deje** [comment]
Should be better in the next version of Maccy. Please create a new issue if the positioning is still invalid.
