### ISSUE TITLE
Feature: Ignore Copies over size of xy characters or filesize

### ISSUE THREAD

**Issue by kmplngj** [p0deje/Maccy#166]
Hello,

I copied large Excel tables in the last days and found Maccy unusable slow after this. 

Would it be possible to set a max size limit in den prefs to prevent this?

I think the clipboard of Launchbar for example does not have this problem at all. Perhaps it just has to do with the amount of data loaded to display the menu. Perhaps this could be optimised. 
 

Thanks
Jan

**Comment by p0deje** [comment]
Any chance you can upload an excel table for me to try to copy? I also copy huge tables using Pages but it never slows Maccy down.

**Comment by p0deje** [comment]
Closing since no response for 2 months. Feel free to reopen and provide more info.
