### ISSUE TITLE
Adjust Max History Size

### ISSUE THREAD

**Issue by rickenwing** [p0deje/Maccy#167]
Hello,

I was wondering if there is a way to edit the history size to go beyond 999 or set it to unlimited. Coming from ditto (on windows) and copyq, I'd like to be able to set a much larger history size (fully aware of the performance implications). 

Thank you!

**Comment by p0deje** [comment]
You can try to adjust it manually using something like this in Terminal:

```bash
defaults write org.p0deje.Maccy historySize 2000
```

Keep in mind that it will still show 999 in Preferences.

**Comment by rickenwing** [comment]
Thank you for the adjustment recommendation. I will use this. Cheers!

**Comment by xmicro** [comment]
This should be baked into the UI, just saying. Pushing this "feature" to be this hidden has caused unneeded amounts of annoyance and data loss for myself but I'm sure many others as well.

**Comment by spanow-o** [comment]
i agree with @xmicro. if there is an issue with performance, then adding an UI warning would be more helpful instead of just blocking.
