### ISSUE TITLE
The shortcut for Pin/Unpin action should be configurable

### ISSUE THREAD

**Issue by cub-uanic** [p0deje/Maccy#169]

**Comment by p0deje** [comment]
The current key is hardcoded to make sure it doesn't conflict with pins or other keybindings. Making it configurable opens the question of handling conflicting keybindings (e.g. you bind it to `OPTION+F` and there is a pinned item with `F` pin). Any suggestion on how to handle these cases?

**Comment by cub-uanic** [comment]
Yep, my suggestion is to implement #172.
When shortcuts for both Pin/Unpin action and pinned items will be configurable, then this will be the user's responsibility to not mess things.
And also, you can check that shortcuts don't overlap right in the Preferences window when changing any of the shortcuts.

**Comment by p0deje** [comment]
After giving it another thought, I feel like we should keep it as-is. The key is selected for its mnemonic (P for pin) so I don't think it is going to be very useful to allow to customize it.
