### ISSUE TITLE
Incorrect shortcut handling with custom keyboard layout

### ISSUE THREAD

**Issue by cub-uanic** [p0deje/Maccy#170]
I'm using the Workman layout.

As a global shortcut, I'm using <kbd>SHIFT</kbd>+<kbd>COMMAND</kbd>+<kbd>V</kbd> (which is on hardware key <kbd>B</kbd> actually), and it works fine and displayed in `Preferences` as <kbd>⇧⌘V</kbd>.

As a shortcut to `Pin/Unpin` I have to use <kbd>OPTION (⌥)</kbd> + <kbd>P</kbd>, as there is no way to change it for now. But in the Workman layout, the <kbd>P</kbd> symbol is on <kbd>O</kbd> key, and the <kbd>P</kbd> key is mapped to the <kbd>;</kbd> symbol. And so actually - taking into account my layout - I have to use <kbd>OPTION (⌥)</kbd> + <kbd>;</kbd>, which is annoying.

I think this problem is not Workman-specific and most probably will be reproducible with any non-standard layout (including localized languages).

**Comment by p0deje** [comment]
Would you prefer the keybinding to respect layout, not the physical key so you have to press `OPTION+0` instead of `OPTION+;`?

**Comment by cub-uanic** [comment]
Yep, that would be preferred (assuming that you've made a typo and meant <key>OPTION+O</key> instead of  <key>OPTION+0</key>), because almost all ("good") programs behave like this.

I've done a small research about <key>SHIFT+COMMAND+V</key>, and found that it also works not fully properly. I've assigned it when the Workman layout was active (read as when the <key>V</key> symbol was on the <key>B</key> hardware key) - and now the shortcut is tied to <key>B</key> hardware key all the time, regarding the layout.

For example, this is how Google Chrome works. The <key>OPTION+COMMAND+B</key> opens new tab with my bookmarks. On the US/ABC layout it's tied to the hardware key <key>B</key>, on the Workman layout it's tied to the hardware key <key>T</key>. In the menu, the shortcut is always displayed as <kbd>⌥⌘B</kbd> all the times, regarding the current layout.

I'm not always using the Workman layout (like when roaming with MBP without an external keyboard), so I'm actually using both layouts and had to remember which h/w key I need to use, and this hurts my brains each time (and my butt a little ;).

**Comment by cub-uanic** [comment]
Just found the other case when the layout is not handled properly: the <kbd>OPTION (⌥) + SHIFT (⇧) + n</kbd> shortcuts.
I'm using a modification of the Workman with shifted number row - Workman for Programmers, where the top row with numbers emits special symbols (!@#) *like* <kbd>SHIFT</kbd> was pressed but without pressing it, and emits numbers (123) when <kbd>SHIFT</kbd> *is actually pressed*.

Surprisingly, the pinned items shortcuts work fine - with both Workman and US layouts.

**Comment by p0deje** [comment]
> Just found the other case when the layout is not handled properly: the OPTION (⌥) + SHIFT (⇧) + n shortcuts.

This is handled by default macOS shortcuts for NSMenuItem. Does the menu items in any other Apple application that uses <kbd> SHIFT</kbd> modifier works. For example, in Findder.app there is <kbd>COMMAND (⌘) + SHIFT (⇧) + F</kbd> item in "Go" menu.

**Comment by cub-uanic** [comment]
Unfortunately, I don't have any experience of programming for Mac's, so *NSMenuItem* doesn't explain too much for me.
But I can check how it works when the Workman layout is active.

When I press <kbd>COMMAND (⌘) + SHIFT (⇧) + F</kbd>, where <kbd>F</kbd> is the hardware key - it's mapped to <kbd>T</kbd>, and works as <kbd>COMMAND (⌘) + SHIFT (⇧) + T</kbd> (View -> Show Tab Bar).

When I press <kbd>COMMAND (⌘) + SHIFT (⇧) + F</kbd>, where <kbd>F</kbd> is the symbol in the Workman layout (which is mapped from <kbd>U</kbd> hardware key) - it works as <kbd>COMMAND (⌘) + SHIFT (⇧) + F</kbd> (Go -> Recents).

So in both cases, it uses the key from the active layout and behaves exactly as I'm expecting.

**Comment by p0deje** [comment]
Can you also try if shortcuts work in "Finder.app" -> "View" -> "Sort by" using Workman for Programmers?

**Comment by cub-uanic** [comment]
If you're about "Veiw -> as Icons" (<kbd>⌘+1</kbd>), "Veiw -> as List" (<kbd>⌘+2</kbd>)...

To trigger a shortcut, I need to press <kbd>⌘+⇧+1</kbd> - the same way as I need to press <kbd>⇧+1</kbd> to get the symbol <kbd>1</kbd>.

**Comment by p0deje** [comment]
I mean these ones:

<img width="439" alt="Screen Shot 2020-09-15 at 08 44 48" src="https://user-images.githubusercontent.com/665846/93211798-b88d1a00-f72f-11ea-8404-8aec746ee852.png">

**Comment by cub-uanic** [comment]
Wow...
This is a bit surprising.

First of all, I'm on High Sierra, and there is an "Arrange By" submenu, instead of "Sort By" - not sure if this matters...
But my shortcuts are different - <kbd>CONTROL(⌃) + OPTION(⌥) + digit</kbd>
![Screen Shot 2020-09-15 at 16 30 00](https://user-images.githubusercontent.com/75673/93219096-a7fe9300-f773-11ea-8023-d4ed39e11ab5.png)


So, here is the full picture (below I'll write **hardware keys**, but please remember that as I'm using "for Programmers", the numbers row is shifted):
- <kbd>⌘1</kbd>: does nothing
- <kbd>⇧⌘1</kbd>: does "as Icons"
- <kbd>⌃⌘1</kbd>: does "as Icons"

- <kbd>⌘2</kbd>: does nothing
- <kbd>⇧⌘2</kbd>: does "as List"
- <kbd>⌃⌘2</kbd>: does "as List"

- <kbd>⌘3</kbd>: does nothing
- <kbd>⇧⌘3</kbd>: does "Take screenshot" (global shortcut)
- <kbd>⌃⌘3</kbd>: does "as Columns"

- <kbd>⌘4</kbd>: does nothing
- <kbd>⇧⌘4</kbd>: does "Selection screenshot" (global shortcut)
- <kbd>⌃⌘4</kbd>: does "as Cover Flow"

- <kbd>⌘5</kbd>: does nothing
- <kbd>⇧⌘5</kbd>: does nothing
- <kbd>⌃⌘5</kbd>: does "Arrange by -> Date Modified"

With <kbd>6</kbd>, <kbd>7</kbd> and <kbd>0</kbd> - it works in the same manner as for <kbd>5</kbd> - nothing + nothing + menu item from "Arrange By".

I was not able to find how to trigger "Arrange by -> Name", "Arrange by -> Kind", "Arrange by -> Date Last Opened" and "Arrange by -> Date Added".

And so, I'm pretty sure that the Finder (as well as other applications) have some bugs in this area, and most probably this is not even Finder but at a system level.
But still, for non-shifted keys (like letters), most of the programs including non-Apple products (like Google Chrome), takes layout into account, and this work as expected.

**Comment by cub-uanic** [comment]
> I was not able to find how to trigger "Arrange by -> Name", "Arrange by -> Kind", "Arrange by -> Date Last Opened" and "Arrange by -> Date Added".

The only option to trigger them is to use <kbd>1</kbd>, <kbd>2</kbd>, <kbd>3</kbd> and <kbd>4</kbd> on NumPad.
With NumPad keys (which are NOT shifted), everything works **exactly** as on my screenshot of the menu: in combination with <kbd>⌘</kbd> or <kbd>⌃⌘</kbd>, and does nothing when <kbd>⇧</kbd> is pressed along with other key modifiers.

**Comment by p0deje** [comment]
> And so, I'm pretty sure that the Finder (as well as other applications) have some bugs in this area, and most probably this is not even Finder but at a system level.
But still, for non-shifted keys (like letters), most of the programs including non-Apple products (like Google Chrome), takes layout into account, and this work as expected.

Yeah, I think this is a system issue so there is no straightforward way to make `SHIFT+OPTION+1` (and other shortcuts with numbers) work in _Workman for Programmer_ mode in Maccy.

As for the letter, I'll need to look into it more. I remember that I made it work for DVORAK, but I'll need to check out Workman.

**Comment by winstonhenke** [comment]
I think I'm also seeing this issue. I have a global shortcut setup for `ctrl+c` and `ctrl+p` for copy/past and Maccy doesn't seem to paste after selecting a entry from the popup

**Comment by vbauerster** [comment]
> I remember that I made it work for DVORAK,

I confirm that shourtcuts doesn't align properly in Dvorak layout. For example to pin default is (⌥+P), I have to press (⌥+L) on Dvorak layout.

**Comment by eproxus** [comment]
This is also a problem when _Paste automatically_ is enabled. When using e.g. Dvorak that setting should emit ⌘V but on Dvorak that becomes ⌘K which is the menu item _Add link.._ in most programs.

**Comment by p0deje** [comment]
I think it should be better now. Any chance anyone can try this build?

[Maccy.app.zip](https://github.com/p0deje/Maccy/files/6193751/Maccy.app.zip)

**Comment by vbauerster** [comment]
I confirm that build works with dvorak layout. Thank you!

**Comment by p0deje** [comment]
Awesome, I'm going to close this and it will be shipped in the next release. Thank you!
