### ISSUE TITLE
mSecure ignore pasteboard types

### ISSUE THREAD

**Issue by davidbdeath** [p0deje/Maccy#171]
I can't figure out how to ignore pasteboard types.  I tried using Pasteboard viewer without success. The application id is com.mseven.msecuremac and the type is public.utf8-plain-text

**Comment by georgesnow** [comment]
my understanding is pasteboard types don't id on the bundle id. it id's the type itself of what is in the pasteboard. so in this case mSecure sets the type to:  public.utf8-plain-text

the type would need to be one of ignored. so mSecure would need to assign a type as:
 transient or concealed etc.. 
I believe the type 1Password uses is  org.nspasteboard.ConcealedType
which then Maccy would ignore. This relies on the app developer to implement it. I opened another ticket about ignoring based on focusable/active application. not sure if it is something the main developer is still considering. it would require some tweaking/testing to get it to work well. it also might not be perfect.

**Comment by davidbdeath** [comment]
I think most of the other pasteboard managers I tried allowed me to ignore mSecure. A lot of them had gimmicky UI, including the ones included in setapp. :(

**Comment by p0deje** [comment]
If mSecure only provides public.utf8-plain-text as pasteboard type, there is no way to ignore it currently in Maccy. A different app-based ignore list can be implemented in #135
