### ISSUE TITLE
Random symbols should be configurable for permanent keyboard shortcut for pinned items

### ISSUE THREAD

**Issue by cub-uanic** [p0deje/Maccy#172]
At my understanding, the peoples that are using clipboard management software, are (almost all) addicted to the keyboard. And this means that we should have highly configurable keyboard shortcuts.

One of the best examples in my opinion is the Vimium extension for Chrome.
There is the opinion named "Characters used for link hints" (see the first part of https://github.com/philc/vimium/wiki/Using-Link-Hints).
And this is what I would like to be implemented in the Maccy.

Obviously, the keys on the home row are most convenient to use, and the different layouts have different keys on the home row.
And so for the pinned items, for most peoples with QWERTY layout, it will be convenient if the "random" symbols will be one of "asdfg"+"hjkl;", while for Workman more convenient will be "ashtg"+"yneoi".

In my opinion, the most convenient way to implement this will be to give the end-user possibility to configure set of the symbols to be used for pinned items, with a reasonable default.
Also, it will be handy if the order of symbols in this setting will be taken into account, for example, "ashtgyneoi" and "yneoiashtg" could be used by left-handed and right-handed users, to get <kbd>COMMAND+A</kbd> or <kbd>COMMAND+Y</kbd> for the first pinned item.

**Comment by Stickyhavr** [comment]
There have been a few requests for more control over the pinned hotkeys. It's probably something that will happen eventually, in the future. But with every added layer of complexity you run the risk of losing the light-weight feel of Maccy. So it's definitely a balance that p0deje has to weigh carefully.

In the meantime, just hit option-p (⌥P) a bunch of times until you get the hotkey you want. By the way, the ones I currently use are: W,X,U,S,L,C,E, and T—In my use, the ease of remembering what's what outweighs being on the home row most of the time.

**Comment by cub-uanic** [comment]
I don't see what is the risk of losing the light-weight feel of Maccy, if there will be sane default.

**Comment by p0deje** [comment]
It's possible to change pinned items hotkeys in preference in 0.21. I hope that's good enough for this case!
