### ISSUE TITLE
Formatting question

### ISSUE THREAD

**Issue by horak** [p0deje/Maccy#173]
Maybe I'm missing something but is there anyway to clear formatting without selecting the to-be-pasted item from the list? So just once I've copied it using cmd-c and then try and paste it immediately after. Thanks!

**Comment by p0deje** [comment]
No, there is no such shortcut. The shortest way to clear formatting is to open the Maccy menu and then press `SHIFT+OPTION+ENTER`.

**Comment by horak** [comment]
Don't you think this is a worthwhile feature?
