### ISSUE TITLE
Search bar does not follow Readline conventions

### ISSUE THREAD

**Issue by jmbaur** [p0deje/Maccy#174]
With most native macOS apps, any input field follows GNU Readline conventions:
- C-u for delete line
- C-h for backspace
- C-w for delete word
- and so on...

where C-* means a key combination while holding down the Ctrl key.

The Maccy search bar does not implement any of these bindings. Is there a way to get this to work or is this feature purposefully omitted?

P.S.: I am SO happy to find an open source clipboard manager on macOS! I appreciate your work!

**Comment by p0deje** [comment]
I've just checked Safari and Finder and they only implement `C-h`. 
Maccy only implements `C-w`now.

I'm happy to add readline conventions though. I'd appreciate some links that describe all Readline keybidings if you happen to have one.

**Comment by jmbaur** [comment]
This is the best link that I can find: https://en.m.wikipedia.org/wiki/GNU_Readline. And yes, sorry about that, I think the main ones that macOS has natively are:
- C-h for backspace
- C-a for beginning of line
- C-e for end of line
- C-f for move forward one character
- C-b for move backward one character

I would argue those are the most important though! 

It might also have C-k for kill to end of line, but I have not tested yet.

**Comment by p0deje** [comment]
I've added support for `C-h`, but the rest assumes you operate with the cursor and Maccy always expects the cursor to be at the end of the string. The cursor is not even shown in this case.

Keeping that in mind, it makes no sense to implement keybindings that move the cursor. If you really want to do that, you can click on the search field which will place the cursor, make it visible and then all the Readline keybindings will work as in any other macOS text field.
