### ISSUE TITLE
Organize pinned items into folders

### ISSUE THREAD

**Issue by vurtomatic** [p0deje/Maccy#176]
Hello @p0deje ! I'm exploring Maccy coming from Clipy. I love the UI like many Maccy users.

The only thing I find lacking so far is the ability to organize pinned items into folders.

**Comment by p0deje** [comment]
I have no plans to add this feature. I don't think that the clipboard manager should be a note-taking app or snippets organizer. I will consider any PRs implementing it given this feature is intuitive and doesn't spoil current UX.

**Comment by vurtomatic** [comment]
That's too bad, I think of it as a way to organize visually and reduce the vertical length of the list; especially since pinned items are meant to be "permanent"—I have pinned items for different purposes and find it convenient to group them categorically, also makes it easier to find them as I seldom maintain such a long list that I'd use search.

**Comment by p0deje** [comment]
This is reasonable and I believe Clipy could be a better solution for your needs then!

**Comment by vurtomatic** [comment]
I appreciate you hearing me out and discussing it! I'll use both for a while and hope you'll reconsider in future :)

**Comment by rmasci** [comment]
This is the very feature I am looking for in a clipboard manager. I am not looking for a note-taking app, just something to store commonly used items.  Think about it, if I had this in a note somewhere, you have to go to the note, copy / paste into the application. Its a lot easier if its in a tool like maccy, select item, push button and it pastes in.  Until then...
==> Uninstalling Cask maccy
==> Backing App 'Maccy.app' up to '/usr/local/Caskroom/maccy/0.17.0/Maccy.app'.
==> Removing App '/Applications/Maccy.app'.
==> Purging files for version 0.17.0 of Cask maccy
