### ISSUE TITLE
Can't Paste

### ISSUE THREAD

**Issue by xDenzil** [p0deje/Maccy#177]
Hello, I've been unable to paste today since installing the new version. I'm on MacOS Big Sur Beta, but I also tried with my other computer on macOS Catalina. Clicking the text from the Maccy toolbar just won't paste it, nothing happens.

**Comment by xDenzil** [comment]
My apologies, I didn't recall having to use cmd+p after selecting what I want in Maccy, I thought double clicking would auto paste. My bad.

**Comment by p0deje** [comment]
You can change in preferences so that it pastes automatically.
