### ISSUE TITLE
Feature request: auto clear history items older than x minutes

### ISSUE THREAD

**Issue by vacekj** [p0deje/Maccy#178]
First of all, I would like to use this opportunity to thank you for making Maccy _and_ making it free and open-source. I appreciate it a lot. 

Now, for the issue. I do a lot of copy-pasting password. I would love the option to automatically clear history items older than x minutes / hours etc. It would make it harder to steal sensitive information from history. 

Please let me know if you would be interested in implementing this feature. I would love to help, but I only just started learning Swift.

Cheers

**Comment by p0deje** [comment]
Thank you @vacekj.

Would just limiting the history size be a decent alternative for you? For example, keep no more than 20 items? I understand this is not exactly the same, but maybe it's a good workaround.

Potentially, I'll be happy to merge PR with such a feature given it is complete:

1. The logic which clears the history that exceeds the time limit.
2. Preference setting allowing to customize the time limit. Localization included.

**Comment by p0deje** [comment]
Closing since no response for more than 1 month. Feel free to reopen and provide more info.
