### ISSUE TITLE
Can't open Preferences anymore

### ISSUE THREAD

**Issue by andriy-appuchino** [p0deje/Maccy#179]
After I disabled the menu icon and footer I can't open Preferences. To be precise, I can, because I found a key combination on the screenshot in Google, but it's not good to leave it that way. You can add some small gear icon so that user can open the preferences on it.

**Comment by p0deje** [comment]
What gear icon and where should it be placed?

**Comment by andriy-appuchino** [comment]
For example, in the Alfred app, this is in the upper right corner (see screenshot).
![](https://images.techhive.com/images/article/2015/02/alfred-mac-chrome-100567453-large.png)

**Comment by p0deje** [comment]
It's not so easy to place it in the NSMenu implementation. The preferences clearly say how to open when footer is hidden, so I lean towards not changing it now.
<img width="320" alt="Screen Shot 2020-10-04 at 10 36 16" src="https://user-images.githubusercontent.com/665846/95018420-ad8e2100-062d-11eb-8325-75fbe2ca3d8b.png">

**Comment by grimalschi** [comment]
It does not work. I am pressing left cmd, right cmd even both and nothing happening.

**Comment by pakerwreah** [comment]
There should really be some quotes around that shortcut. It looks like it's just a comma separating the text. 
I spent 15 minutes pressing CMD and trying every possible thing, even reinstalled the app.

Another issue is... how am I supposed to remember that?
A small hint at the bottom of the menu would help a lot.
But I agree that a tiny gear icon would be much better.

**Comment by p0deje** [comment]
> Another issue is... how am I supposed to remember that?

That's just a common macOS shortcut - preferences are opened using `Command+,`. You can skip remembering that, but then also consider keeping the footer enabled.

> There should really be some quotes around that shortcut. It looks like it's just a comma separating the text.

That's how any macOS application shows this shortcut. Take a look at Safari:

<img width="296" alt="Screen Shot 2021-03-30 at 09 52 23" src="https://user-images.githubusercontent.com/665846/113026237-b58ecf80-913d-11eb-8fdb-1d1f970d849f.png">

If you are talking about the hint in the "Preferences" window, then it already has a ⌘ symbol. Even if I wrap it with quotes, somebody else would say that it's not noticeable enough.

I'm seriously frustrated that it's not okay to read a simple line of text (and waste a fraction of a second) but it's okay to ask the developer to spend at least an hour creating some workaround for this.

**Comment by pakerwreah** [comment]
Well, yes, I think it is ok to ask features to the developer that will probably improve the experience of the app.
That's just a suggestion, feel free to ignore it, but you should never blame the user.
