### ISSUE TITLE
Shortcut for copying highlighted item

### ISSUE THREAD

**Issue by diego-vieira** [p0deje/Maccy#183]
Hi, is it possible to add a shortcut to copy the highlighted item by pressing CMD + C and close Maccy?

I'm coming from Paste which let's you press `SHIFT + CMD + V` (thanks for adding the binding to allow this) to pop up and `CMD + C` to copy the selected item.

![image](https://user-images.githubusercontent.com/930792/95055914-dffe5380-06eb-11eb-9f99-7e87fe4824d3.png)

Many thanks

**Comment by p0deje** [comment]
Why Enter is not enough for this use case?

**Comment by diego-vieira** [comment]
@p0deje thanks for your reply. I didn't knew you could press Enter to paste. Thanks
