### ISSUE TITLE
Regex Search

### ISSUE THREAD

**Issue by ShubhamThakkar** [p0deje/Maccy#184]
Hi Team,

It will be great if feature of Regex Search is available on Maccy. Feature request is similar to already present on Ditto (Clipboard Manager for Windows). 
Sometimes item I copied is there in many of the copied items (example - part of URL copied), so when I search for that part all items comes up having that part. But to copy the item with only that part separately, I have to scroll down a lot. It would be better, if in search I type ^ (regex for start of string) and then few characters of that part and then it comes as first item.

Thanks for your help, it is a great product.

**Comment by p0deje** [comment]
I technically see no problem in adding support for regexps, but I'm not sure how UX should look like. Can you provide some examples of URLs you have, what you'd type into search field and what you'd expect to see in results?

**Comment by ShubhamThakkar** [comment]
Example

- Let's say there are 3 copied items : 'abcde', 'abcdefg', 'delhi'
- Now when I type and search 'de' in the Maccy, all 3 options shows and let's say 'delhi' is last item.
- Now to select 'delhi', I have to go down using down arrows to select 'delhi'
- But it would be better, if in search I type '^de', indicating item should start with 'de', now only 'delhi' shows up and that too first item.
- So now item can be easily copied without using down arrows.
- This example just covers basic few items, let's say sometimes I want 'xyz'  at end, so I will search 'xyz$' in Maccy.
- This regex search will be very useful according to me if there are many items and we want to select particular item without clicking multiple times on down arrow.

Let me know, if I can provide some other inputs. 

Thanks for your help.

**Comment by p0deje** [comment]
In the upcoming version of Maccy, you can enable searching by regular expression in Preference. It might be a bit incovenient to go to preferences whenever you need to change search type, but adding UI in a search bar is more complex that implementing the search itself. I'll probably add it later or implement a mixed search where the search mode will be detected from the search term.

**Comment by p0deje** [comment]
I've also added "mixed" search which is a combination of all the searches order by most restrictive to least restrictive:
1. search using exact search;
2. if there are no results, search using regular expressions;
3. if there are no results, search using fuzzy search.

Hopefully it can be useful for these advanced cases and it would allow to avoid changing search mode in preferences.

**Comment by ShubhamThakkar** [comment]
Thanks a lot Alex for working on this.
