### ISSUE TITLE
Error: maccy: macOS Mojave or newer is required.

### ISSUE THREAD

**Issue by cub-uanic** [p0deje/Maccy#185]
Tried to update via brew and got: "Error: maccy: macOS Mojave or newer is required."
Why force Mojave?
Do you have any **real** reason?
Is your code using anything Mojave-specific?

I'm on High Sierra, which is greatly supported by Homebrew.
I will never update to Mojave due to my games on Steam and broken support of 32bit by Mojave.

I'd like to keep using Maccy and receive updates on HS, at least while it's supported by Homebrew.
Thanks.

**Comment by p0deje** [comment]
That's blocked by #161

**Comment by p0deje** [comment]
Now that Big Sur is coming, I think it's fair to support the most recent 3 versions of macOS: Mojave, Catalina and Big Sur. I'll still be happy to support High Sierra but not willing to invest any more time into it - PRs are always welcome.
