### ISSUE TITLE
Maccy takes focus from the focused app when activated

### ISSUE THREAD

**Issue by nilsou** [p0deje/Maccy#186]
When using an visor like app that disappears when it loses focus, you can't paste from Maccy because it takes focus when activated.

Most clipboard managers don't steal focus from the focus app when activated.

Maccy should probably also not do that.

Info on how to do this here: https://stackoverflow.com/questions/46023769/how-to-show-a-window-without-stealing-focus-on-macos

**Comment by p0deje** [comment]
That's by design to allow language input helpers to work when searching. It will be possible to disable this behavior in preferences in the next version (see 4102d7b5fadb61743c196e83b4d2788a6305c60b).
