### ISSUE TITLE
Entries on the clipboard goes missing after some time

### ISSUE THREAD

**Issue by madqueendany** [p0deje/Maccy#187]
Hello,

I'm experiencing this weird scenario where I have a couple of entries pinned, and then after some time the pinned items and some of the non-pinned items are lost.

The band-aid is to quit the app and restart it, after that the pinned items returns.

I can't really explain it more clearly than that sorry. ✌🏼

---

I'm currently on 0.17.0

---

Here I experienced it just now

Original and ideal state

![image](https://user-images.githubusercontent.com/47292665/95953532-fc487180-0e0a-11eb-9a7a-a6d4bba21293.png)

I tried pasting one of the pinned (by pressing CMD+W)

And then after some time this happened

![image](https://user-images.githubusercontent.com/47292665/95953479-e935a180-0e0a-11eb-917f-fca46aa13183.png)

**Comment by p0deje** [comment]
I know exactly why this is happening and it's a regression bug in 0.17.0 (cd81ac0a3a7dc06dde1c08fb7a5a22d94331fa8f). However, I haven't found a reliable solution yet.

**Comment by madqueendany** [comment]
Thanks! I've reverted to 0.14.1 for the meantime

**Comment by MarqueIV** [comment]
Was just experiencing some issues myself around this very thing (pinned items.) In my case, also using 0.17.0, the pinned items were still there, but you couldn't actually choose them.  When you did, you'd here a 'bonk' sound and nothing would be copied/pasted.  A couple back-and-forths to the list, and just like this poster said, they would not be where I was expecting.

**Comment by p0deje** [comment]
Hopefully this is now fixed in 0.18. Please try upgrading
