### ISSUE TITLE
Search/filter is slow

### ISSUE THREAD

**Issue by indigoviolet** [p0deje/Maccy#189]
Maccy is a really cool app, thank you for it. My one complaint with it is that the filtering (in the popup or menu) is slow - given 999 items I'd expect it to be much faster. I can see a noticeable lag between typing a word and it appearing in the search box and the items filtering down to match the word.

**Comment by p0deje** [comment]
Unfortunately there is no much to be improved here - the actual slow part is how items are made hidden/visible in UI. This is done by removing/adding them to `NSMenu` and that is the slowest thing, but it's internal to `NSMenu` implementation. I'll be happy to make it faster, but out of ideas now.

I can recommend limiting visible menu items (e.g. 50) - it will make search run much smoother.

**Comment by indigoviolet** [comment]
Thanks for the quick response. In my experience, limiting menu items (to 25) has not made a difference, I see a beachball and lag every time I type.

**Comment by p0deje** [comment]
Hm, there might be something else then. Can you record a quick video showing the lag?

**Comment by p0deje** [comment]
Closing since no response for a month. Please reopen with more details.

**Comment by mo2menelzeiny** [comment]
I can confirm I'm having the same issue, basically whenever I search there is a lag that freezes the tool window for 1 second and then it comes back to life

**Comment by p0deje** [comment]
@mo2menelzeiny Please create a new issue and fill all the details in the form. Thanks!
