### ISSUE TITLE
Copy actual file instead of the path

### ISSUE THREAD

**Issue by sajadabedi** [p0deje/Maccy#194]
currently, when you copy a file the path will copy to the clipboard instead of the actual file.
is there a way or solution to change this?

**Comment by p0deje** [comment]
When you paste "FilePath" it should be treated similar to pasting a file - internally macOS also copies file path when you copy file.

Is there a particular scenario when this doesn't work?

**Comment by sajadabedi** [comment]
When I copy image file and want to paste it in a different application like Figma, it pastes "FilePath" instead of the actual image.

**Comment by p0deje** [comment]
Does it paste as an image in Figma when you copy without Maccy?

**Comment by p0deje** [comment]
Closing since no response for a month. Please reopen with more details.
