### ISSUE TITLE
Unable to install latest update

### ISSUE THREAD

**Issue by orschiro** [p0deje/Maccy#196]
Error happening with this screen:

![image](https://user-images.githubusercontent.com/170947/98940930-12218300-24ec-11eb-97f0-7965e60c2e3b.png)

Anyone else?

**Comment by p0deje** [comment]
1. Do you upgrade from 0.170.0? 
2. Are you sure you have 0.17.0 downloaded from Github and not built on your own?

**Comment by orschiro** [comment]
Wow, I am still on version 10!
Actually, cannot remember how I installed it. 
What's the best way?
Remove entirely and install from scratch?

![image](https://user-images.githubusercontent.com/170947/98945745-3765bf80-24f3-11eb-8091-e6a247a45300.png)

**Comment by p0deje** [comment]
Yes, somewhere between 0.10 and 0.17, I have enabled sandbox and app notarization so the update will fail. The best way is to just grab the latest version from Github (or maccy.app).

Closing for now, feel free to reopen if anything goes wrong.

**Comment by orschiro** [comment]
That worked, thank you!
