### ISSUE TITLE
keeps on scrolling

### ISSUE THREAD

**Issue by FernandoMiguel** [p0deje/Maccy#197]
* cmd+shift-c
* arrow up

expected:
* to stay in the bottom of the list

what happens instead
* the highlight keeps scrolling to the top in a loop

details:
v0.18 
large list (100?) bigger than the screen size

**Comment by p0deje** [comment]
That's by design. Any reason why the scrolling should stop when reaching the top/bottom?

**Comment by FernandoMiguel** [comment]
Maybe I'm not being clear.
It scrolls by it self... Non stop.
So I can't select what is at the bottom, like preferences

**Comment by p0deje** [comment]
Wait, what? Can you record a video? I can't reproduce.

**Comment by FernandoMiguel** [comment]
Yeah freaky 😊
I'll try tomorrow when I'm back at work..

At least one time it didn't behave like that.

Could it be it was still updating something after installing the new version?

**Comment by FernandoMiguel** [comment]
I remember I couldn't click in the task bar icon and open the list at the time.

**Comment by p0deje** [comment]
Closing since no news for a month. Please reopen with more details.
