### ISSUE TITLE
Feature request: Clear history on shutdown/reboot

### ISSUE THREAD

**Issue by mandrasch** [p0deje/Maccy#198]
Thanks again for providing this very useful software as open source!

I would really like the optional setting of clearing the history on shutdown or reboot. 

Background: Sometimes copied passwords or other sensitive data is still in my history, therefore clearing it on shutdown/reboot would be a good protection. (I know that there is the option of pasteboard types for password managers which can be ignored, great feature)

Thanks in advance!

**Comment by Fongeme** [comment]
It sounds like the more appropriate solution would be to delete the data on app shutdown and not on pc shutdown?
If that sounds good, i'd like to get going on this :)

**Comment by Fongeme** [comment]
I've created #292

**Comment by mandrasch** [comment]
Nice, thanks very much @Fongeme! (Don't have the skills to test the PR, hope it all goes well :-))
