### ISSUE TITLE
Apple Silicon build

### ISSUE THREAD

**Issue by MaxDesiatov** [p0deje/Maccy#199]
Apparently the Apple Silicon binary slice is absent in the bundle for 0.18, as the architecture is displayed as Intel when running on Apple Silicon hardware.

<img width="730" alt="Screenshot 2020-11-14 at 21 35 45" src="https://user-images.githubusercontent.com/112310/99157512-5c0f9200-26c1-11eb-97ac-e530403ddf50.png">

**Comment by p0deje** [comment]
Yeah, I've been trying to figure out how to build both architectures, but no luck so far.

**Comment by VictorPuga** [comment]
To build a universal binary you need to build the project using Xcode on an Apple Silicon Mac. It is simple, but you need the M1 processor to have it done.

**Comment by p0deje** [comment]
According to https://developer.apple.com/documentation/xcode/building_a_universal_macos_binary, it's possible to build on Intel using Xcode 12.2. I haven't upgraded yet but this will be the first on my list to do.

**Comment by pdaire** [comment]
is there a compiling directions to try to this by our selfs?

**Comment by thysm00** [comment]
Hi i'm new to your software (it's pretty cool), but as i just transitioned to an M1 mac, i'm having a few problems, first, it's not optimized for M1, but that's not a huge deal as it works just fine when it's on, but it does not seem to want to be launched at login and i have to launch it manually. It is listed in the login items, but in the "Kind" column, it says "unknown" which might explain why it does not get launched. So if you made progress on an apple silicon build, i'm very interested ;)

**Comment by p0deje** [comment]
Available to in 0.19.0.

**Comment by thysm00** [comment]
Thank you so much! It works very well ;)
