### ISSUE TITLE
Cannot select with arrow keys after using mouse

### ISSUE THREAD

**Issue by p0deje** [p0deje/Maccy#2]
After using Maccy for some time, selecting with arrow keys and Enter stops working. This bug can be easily reproduced with the following steps:

1. Pop up Maccy.
2. Hit down arrow key a couple of times.
3. Move mouse on top of "Maccy" title field.
4. Move mouse outside of the menu
5. Click. Menu is closed now.
6. Pop up Maccy.
7. Hit down arrow key a couple of times.
8. Move mouse on top of "Maccy" title field.
9. Move mouse outside of the menu
10. Click. Menu is closed now.
11. Pop up Maccy.
12. Hit down arrow key.

At this point selecting with arrow keys stops working. 

It seems like the problem lies somewhere in the chain of event handlers **below** the one Maccy defines. If I change our event handler to call the next one:

```diff
diff --git a/Maccy/FilterMenuItemView.swift b/Maccy/FilterMenuItemView.swift
index 7d04f74..ebab227 100644
--- a/Maccy/FilterMenuItemView.swift
+++ b/Maccy/FilterMenuItemView.swift
@@ -86,7 +86,7 @@ class FilterMenuItemView: NSView, NSTextFieldDelegate {
         let eventProcessorPointer = UnsafeMutablePointer<Any>.allocate(capacity: 1)
         eventProcessorPointer.initialize(to: processInterceptedEvent)

-        let eventHandlerCallback: EventHandlerUPP = { _, eventRef, userData in
+        let eventHandlerCallback: EventHandlerUPP = { eventHandlerCallRef, eventRef, userData in
           guard let event = eventRef else { return noErr }
           guard let callbackPointer = userData else { return noErr }

@@ -97,7 +97,9 @@ class FilterMenuItemView: NSView, NSTextFieldDelegate {
           if eventProcessed {
             return noErr
           } else {
-            return OSStatus(Carbon.eventNotHandledErr)
+            let response = CallNextEventHandler(eventHandlerCallRef, event)
+            print("Response \(response)")
+            return response
           }
         }
```

The in a normal behavior it prints "Response 0" all the time, but when the bug starts it prints "Response -9874" (`eventNotHandledErr`).

Any help is much appreciated because frankly I have no idea how to fix or workaround this issue.

**Comment by runforprogram** [comment]
also happen 。
