### ISSUE TITLE
The popup obscures the menu bar in Big Sur

### ISSUE THREAD

**Issue by moriwang** [p0deje/Maccy#201]
Hi Maccy team,

I am a new user of Maccy after I upgrade my Mac to Big Sur.
I found the popup windows obscures the menu bar. Is it a bug?

<img width="366" alt="截屏2020-11-15 下午7 06 15" src="https://user-images.githubusercontent.com/9151525/99183349-f4ffe500-2775-11eb-927c-2a0e90c37411.png">

This screenshot is more clear.

<img width="353" alt="截屏2020-11-15 下午7 13 39" src="https://user-images.githubusercontent.com/9151525/99183442-bdde0380-2776-11eb-9470-f6fcee83b4c9.png">

**Version**
macOS 11.0.1
Maccy 0.18.0

**Comment by moriwang** [comment]
And another little UI flaw.
<img width="456" alt="image" src="https://user-images.githubusercontent.com/9151525/99183509-4e1c4880-2777-11eb-9d45-4774ec0a32b4.png">

**Comment by p0deje** [comment]
Thanks for the bug report!

Can you share the output of ` defaults read org.p0deje.Maccy`?

**Comment by p0deje** [comment]
Fixed and will be released in new version.
