### ISSUE TITLE
Feature Request: Trim spaces 

### ISSUE THREAD

**Issue by rochakagrawal** [p0deje/Maccy#207]
I am finally migrating to Maccy after using ClipMenu for atleast 8 years. So far its good except one feature I miss in Clipmenu - it allowed me to optionally remove spaces between text when pasting. Very handy when I am inputting credit card number and the clipboard content contains credit card number in 4 digit blocks.  I could press Control + click on the menu history option and it would remove spaces between the text. 

Please could you implement that?

**Comment by p0deje** [comment]
Frankly, I'm not convinced Maccy should support it. There is already OPTION+CLICK which pastes and SHIFT+OPTION+CLICK which clears formatting and pastes and I don't want to add yet another modifier to handle this particular case. I think it's too specific to implement a custom feature in Maccy.
