### ISSUE TITLE
Bug : Maccy not storing some content types

### ISSUE THREAD

**Issue by rochakagrawal** [p0deje/Maccy#209]
I am trying to migrate from clipmenu which i have found very reliable over the years

This morning I noticed that clipmenu had saved far more history items compared to maccy. see attached scrrenshot and link [https://take.ms/7pAP0](https://take.ms/7pAP0)

How can we get Maccy to store all content types and not miss anything? 

![Type 2020-11-23 11-43-58](https://user-images.githubusercontent.com/3668160/99927742-70b6ee80-2d81-11eb-8d36-5465b9cadf18.png)

**Comment by p0deje** [comment]
I'm not sure how ClipMenu works, but Maccy should properly save all the types on the screenshot.
It would help if you provide an example of a copy that is saved by ClipMenu but not Maccy.

**Comment by p0deje** [comment]
Closing since no response for more than a month. Please reopen with more details.
