### ISSUE TITLE
Maccy using much RAW

### ISSUE THREAD

**Issue by philihub** [p0deje/Maccy#216]
How can I fix this? I am on the latest macOS with the latest Maccy.

<img width="491" alt="image" src="https://user-images.githubusercontent.com/16780277/101163489-f5ccbe00-3633-11eb-8138-553d9c699a83.png">

**Comment by p0deje** [comment]
This is weird - I have it running with 999 history size and it's using no more than 60MB. Maybe this is related to Big Sur, but definitely needs more investigation.
<img width="724" alt="Screen Shot 2020-12-07 at 08 35 16" src="https://user-images.githubusercontent.com/665846/101357317-46782d00-3867-11eb-8d45-ac67b6a55b10.png">

**Comment by p0deje** [comment]
I feel like this is related to #217. Can you please report if the memory consumption is better once you exclude Excel from stored copies?

**Comment by philihub** [comment]
Will do!

**Comment by philihub** [comment]
Tested today and seems to be resolved by excluding Excel.
