### ISSUE TITLE
Lag when copying tables in Excel

### ISSUE THREAD

**Issue by philihub** [p0deje/Maccy#217]
It seems that copy/pasting 100000s of columns in Excel is slowed down by Maccy by several seconds. Is there a way to avoid that? I have to regularly cops and past this stuff but not keeping it in store for more than 1 or 2 operations within a short timeframe.

**Comment by p0deje** [comment]
I think as long as you copy huge data there is not much to improve in Maccy as it needs to store the whole copy data in memory. The only thing that comes to my mind is to completely ignore copies from Excel in Maccy (using proper pasteboard type).

**Comment by philihub** [comment]
Happy to exclude excel form Maccy. How would I do that?

**Comment by p0deje** [comment]
Follow the instructions from https://github.com/p0deje/Maccy#ignore-custom-copy-types.

Thank you,
Alex

**Comment by philihub** [comment]
Nice, thank you!

**Comment by p0deje** [comment]
Guess it can be closed now.
