### ISSUE TITLE
Maccy shortcut not bringing up window.

### ISSUE THREAD

**Issue by horak** [p0deje/Maccy#218]
When I use my shortcut mapping the screen flashes briefly but then the window doesn't show up. 

The process is listed as running in my application monitor.

I've tried removing and reinstalling the app using both the package downloadable here as well as brew. Nothing gives.

Is there anyway that I can debug this?

**Comment by p0deje** [comment]
Is it shown when you click on the menu icon? Can you record a video of the screen to demonstrate the issue?

Also, it would be helpful if you paste an output of running `defaults read org.p0deje.Maccy` in Terminal.app

**Comment by horak** [comment]
That's part of the problem, I've hidden the menu icon haha.

Here's a lofi screen recording. You'll see two flashes — those are my using my hot key. 

![Screen Recording 2020-12-07 at 9 43 29 AM](https://user-images.githubusercontent.com/1111424/101372054-16358c00-3871-11eb-948a-d26838f01805.gif)

Here's the output:
{
    "KeyboardShortcuts_popup" = "{\\"carbonModifiers\\":2816,\\"carbonKeyCode\\":8}";
    "NSStatusItem Visible Item-0" = 0;
    "NSWindow Frame SUStatusFrame" = "878 569 400 129 0 0 1440 877 ";
    "NSWindow Frame SUUpdateAlert" = "410 372 620 392 0 0 1440 877 ";
    "NSWindow Frame com.sindresorhus.Preferences.FrameAutosaveName" = "189 351 486 516 0 0 1440 877 ";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2020-12-01 16:35:14 +0000";
    fuzzySearch = 1;
    hideFooter = 0;
    hideSearch = 0;
    hideTitle = 1;
    history = {length = 42, bytes = 0x62706c69 73743030 a0080000 00000000 ... 00000000 00000009 };
    historySize = 201;
    ignoredPasteboardTypes =     (
        "Pasteboard generator type",
        "com.agilebits.onepassword",
        "com.typeit4me.clipping",
        "net.antelle.keeweb",
        "de.petermaurer.TransientPasteboardType"
    );
    maxMenuItems = 20;
    migrations =     {
        "2020-02-22-history-item-add-copied-at" = 1;
        "2020-02-22-history-item-add-number-of-copies" = 1;
        "2020-04-18-switch-storage-to-core-data" = 1;
        "2020-04-25-allow-custom-ignored-types" = 1;
        "2020-06-19-use-keyboardshortcuts" = 1;
        "2020-09-01-ignore-keeweb" = 1;
    };
    pasteByDefault = 1;
    popupPosition = statusItem;
    removeFormattingByDefault = 1;
    showInStatusBar = 0;
    sortBy = lastCopiedAt;
}

**Comment by p0deje** [comment]
I don't know how you ended up in this state, but your `popupPosition` is set to show at the menu icon and there is no menu icon. Fix it by `defaults remove org.p0deje.Maccy popupPosition`.

**Comment by horak** [comment]
Nice find! Where is this file located? It seems I have a few? Is it in the application bundle?
<img width="645" alt="Screen Shot 2020-12-07 at 3 58 54 PM" src="https://user-images.githubusercontent.com/1111424/101410590-2f583000-38a5-11eb-8fda-b3e890c4c2fb.png">

**Comment by p0deje** [comment]
You don't need to edit files, just run the command `defaults remove org.p0deje.Maccy popupPosition`

**Comment by horak** [comment]
There we are, thank you!

**Comment by montanaflynn** [comment]
Happened to me as well, not sure how it got into that state. Might want to add this to the readme?
