### ISSUE TITLE
Option+select isn't pasting

### ISSUE THREAD

**Issue by lakamsani** [p0deje/Maccy#222]
Hi, thanks for making this available.  I installed it today on my Macbook  (Catalina 10.15.7) via  `brew cask install maccy`. 

When I try `Option+select` it shows me this popup. 
![Screen Shot 2020-12-13 at 11 03 40 AM](https://user-images.githubusercontent.com/3322496/102021229-3662c080-3d33-11eb-9146-279afabe199b.png)

And then it shows the following. The second is another unrelated app I blacked out for security reasons. Is `AEServer`  related to `Maccy` or should there be something else? 
![Screen Shot 2020-12-13 at 11 04 19 AM](https://user-images.githubusercontent.com/3322496/102021232-39f64780-3d33-11eb-8a83-b04959e65f08.png)

**Comment by EsteveAguilera** [comment]
As commented on #159 **Maccy** does not appear automatically on the apps list, you have to add it manually by selecting the `+` button.

`AEServer` is the **Apple Events Server**. It is used to control Apple Events that come in from other Macs

**Comment by lakamsani** [comment]
@EsteveAguilera  thanks. That worked. Closing this.
