### ISSUE TITLE
Allow removal of specific entry in clipboard

### ISSUE THREAD

**Issue by Phlogi** [p0deje/Maccy#225]
Add feature to enable single entry removal, rather than clearing the whole clipboard. This is essentially helpful when copying clear-text passwords.

**Comment by Phlogi** [comment]
This could mitigate / workaround issue https://github.com/p0deje/Maccy/issues/157 which is more complex to save.

**Comment by ZT742** [comment]
Point 6 of the readme says:

To delete the history item, press OPTION (⌥) + DELETE (⌫).

Is this the feature you mean?

**Comment by Phlogi** [comment]
Yes, exactly - it even says it on the hover help text. Sorry and thanks for the excellent piece of software!

**Comment by laserpez** [comment]
It seems that the OPTION (⌥) + DELETE (⌫) combo doesn't work anymore on Sonoma 14.0.

**Comment by p0deje** [comment]
@laserpez Please update to the recent version of Maccy.

**Comment by froyston** [comment]
@p0deje I am on Sonoma `14.7.2`  and on the latest version of Maccy `2.3.0` but still I am not able to delete one particular entry.. I can delete the entire history. Please advice

**Comment by p0deje** [comment]
@froyston 
1. do you press Option+Delete? 
2. can you double check in Maccy preferences that the shortcut to delete items is set up?

**Comment by froyston** [comment]
> @froyston
> do you press Option+Delete?
can you double check in Maccy preferences that the shortcut to delete items is set up?

@p0deje I see it was an issue with my Mac settings for Maccy... it didnt have the required permissions. Solved now, thanks! :)
