### ISSUE TITLE
Limit the size of the popup but leave older items

### ISSUE THREAD

**Issue by thysm00** [p0deje/Maccy#229]
I know i can limit the number of items in the list manually, but when i do that, i can no longer access them unless i search for them (which means i remember what they contained). I've seen that in other apps, but wouldn't it be possible to have a submenu under the list the show the rest of the items that Maccy remembers?
This way, the menu stays small for most usage but when you need to find an older item, you can still do it even if you don't remember precisely what it was.

**Comment by p0deje** [comment]
How would you find the item if you don't remember what it was? If you remember at least a part of the text, this should be enough, shouldn't it?

**Comment by thysm00** [comment]
Well, if it's for example a phone number, a name or email, a serial number (i sell softwares), it's usually impossible to remember any part of it. I've been using clipmenu for years, and it happened to me hundreds of times to have to copy something i did not remember.

**Comment by thysm00** [comment]
That's why being able to go through the whole list is important even if and i agree, searching through them is good.
The other reason why submenus could be useful is that you still get a small popup but it can contain many items.

**Comment by allomorphy** [comment]
My 2c:
I find it useful to have an arbitrary tag for pinned entries. I have tons of pinned entries for things like URLs of public facing documentation, contracts, registration and bank account numbers.
What I do now, is put save some text in UPPERCASE: <whatever the target is here>
Works super for searching, typically I just use the keyboard and do not even look an my MANUAL: url is pasted.
(Problem is that I have to delete the tag preceding a URL when I paste into a browser, that could be solved by a tag that is not by default pasted)

-- one day all computers will be made this way 🤔   Thanks Alex for this master-work 😊

**Comment by sveggiani** [comment]
I second @thysm00's request. I think having the last X items displayed and the rest of them under a submenu would be nice to un-clutter the main menu. I love how ClipMenu handles this:

![image](https://user-images.githubusercontent.com/560791/112480080-6b2fdc00-8d54-11eb-95da-b7825f209973.png)

![image](https://user-images.githubusercontent.com/560791/112480170-826ec980-8d54-11eb-8e6a-4e38165e8f1f.png)

**Comment by p0deje** [comment]
I think I've found a way to show a smaller popup and then the rest could be scrolled. It will look like this:
<img width="495" alt="Screen Shot 2021-07-02 at 12 50 33" src="https://user-images.githubusercontent.com/665846/124322426-48237e00-db34-11eb-9249-d1caa923fed3.png">

Would that work for your case?

**Comment by thysm00** [comment]
Yes, that would definitely work for me! And would indeed be even better than the sub menus!

**Comment by sveggiani** [comment]
@p0deje I think the scrollable would work and solve the inconvenience of having a very long list of items.

**Comment by borekb** [comment]
Another use case is having a weird Unicode character in the history, like a middle dot or something – that cannot be easily searched for.

Scrolling as shown [above](https://github.com/p0deje/Maccy/issues/229#issuecomment-873225855) looks like a great solution! 👍

**Comment by kerryj89** [comment]
I was going to suggest this but I am happy to see the author came to the same conclusion.

**Comment by juarezr** [comment]
An alternative approach could be:

- using more than 1 column for viewing the list of text on the popup menu
- using the arrow down/up keys for selecting the desired text as currently
- using the arrow left/right keys for going forward/backward in the pagination
- moving the shortcut keys ( ⌘1 to ⌘9 ) along the pagination

**Comment by robert-d-94** [comment]
@p0deje Has there been any progress in implementing this feature? I would love to be able to limit the height of the popup to 20 items, but be able to scroll through my entire history.

**Comment by p0deje** [comment]
Nothing new since my last comment. On Aug 18, 2023, at 14:16, robert-d-94 ***@***.***> wrote:﻿
@p0deje Has there been any progress in implementing this feature? I would love to be able to limit the height of the popup to 20 items, but be able to scroll through my entire history.

**Comment by itdhsc** [comment]
This would be awesome!

**Comment by chenxiccc** [comment]
> I think I've found a way to show a smaller popup and then the rest could be scrolled. It will look like this: <img alt="Screen Shot 2021-07-02 at 12 50 33" width="495" src="https://user-images.githubusercontent.com/665846/124322426-48237e00-db34-11eb-9249-d1caa923fed3.png">
> 
> Would that work for your case?

This is a very good solution!
But i found only at the botton of the screen, this type of popup will function, is it possible to limit all popup height anywhere it appears?

**Comment by p0deje** [comment]
This has been implemented since Maccy 2.0

**Comment by PerezChilli** [comment]
I have a problem now with the feature - it only shows one line and there is no option to expand window

![Image](https://github.com/user-attachments/assets/44ee3581-7a8f-4181-9d27-5ccbebdee2ba)

**Comment by p0deje** [comment]
@PerezChilli 
1. check your settings and ensure the storage size is bigger than 1
2. resize the main Maccy window as you resize all other macOS windows

**Comment by PerezChilli** [comment]
> [@PerezChilli](https://github.com/PerezChilli)
> 
> 1. check your settings and ensure the storage size is bigger than 1
> 2. resize the main Maccy window as you resize all other macOS windows

1. It's bigger than one. Items are scrolling in this one line.
2. Hmmm I can't resize it cause it's a popup

**Comment by p0deje** [comment]
> Hmmm I can't resize it cause it's a popup

you can by clicking on the bottom right corner and dragging to resize.

**Comment by hw0603** [comment]
Pop-up windows are generally perceived to be unsizeable, so I think it would be a better UX if there was an explanation inside the app.
Also, there seems to be only one clipboard history currently displayed by default. I hope there's a setting where you can see the latest N lists, and scroll the rest

**Comment by p0deje** [comment]
@hw0603 you can resize the main Maccy popup to fit as many items as you want.

**Comment by hw0603** [comment]
@p0deje Yes I understood that, but the size of the pop-up window that I adjusted is not saved after the pop-up is closed.
When I reopen the clipboard, a pop-up of the size that always shows about one record opens up, so to see multiple histories, I always have to drag it to the mouse and resize it, which I find inconvenient.

The adjustable size of the pop-up is a very comfortable feature, but it would be better if the size of the adjusted pop-up window is maintained or if there is an option to specify the default size.

**Comment by p0deje** [comment]
@hw0603 It should be saved once you change the size manually. If it's reset, this is a bug, can you please create a new issue for this?
