### ISSUE TITLE
Dependency on macOS 10.14

### ISSUE THREAD

**Issue by wildeyes** [p0deje/Maccy#23]
Is it possible to support 10.13?

**Comment by p0deje** [comment]
I don't have 10.13 to test, but can you try the attached version and let me know if it works? Particularly, can you verify that automatic pasting (when you select with ⌥ pressed) works? [Maccy.app.zip](https://github.com/p0deje/Maccy/files/3530122/Maccy.app.zip)

**Comment by wildeyes** [comment]
So this happens
[image: image.png]

**Comment by wildeyes** [comment]
Automatic pasting works.

**Comment by p0deje** [comment]
The image is not shown, what exactly happens?

**Comment by wildeyes** [comment]
![image](https://user-images.githubusercontent.com/1652108/63521472-2cde9500-c4ff-11e9-8283-829cac4b503f.png)

**Comment by NghiaTranUIT** [comment]
@p0deje You can install macOS 10.13 on Parallels or some sort of virtual apps to test it. I got same issue on 10.13 too

**Comment by p0deje** [comment]
It seems to be non-trivial to fix all the issues on 10.13:

1. Search doesn't work.
2. Selecting menu with Cmd+N doesn't work.

I've set up a virtual machine and I will try to fix these.

**Comment by p0deje** [comment]
Can you guys please give a shot to the following build?
[Maccy.app.zip](https://github.com/p0deje/Maccy/files/3609707/Maccy.app.zip)

**Comment by p0deje** [comment]
I haven't received any response so I'll consider this fixed. Try 0.5.1.

**Comment by neocryptek** [comment]
Anything preventing it from supporting 10.12? :)

**Comment by p0deje** [comment]
Yes, some of Maccy dependencies are require at least 10.13 (e.g. https://github.com/krisk/fuse-swift)
