### ISSUE TITLE
Unable to open settings

### ISSUE THREAD

**Issue by MelkorNemesis** [p0deje/Maccy#230]
Hello,

I have disabled footer through Maccy settings and now I'm unable to open the settings at all. Neither through cmd + shift + c nor clicking at the Maccy icon in the tray.

Any help appreciated. Thanks!

**Comment by MelkorNemesis** [comment]
For anyone facing the same issue I was able to bring it back by pasting `defaults write org.p0deje.Maccy hideFooter 0` to the terminal.

**Comment by kmplngj** [comment]
You could also just press command + , when the app has focus. (As in every good macOS app).

**Comment by MelkorNemesis** [comment]
Thanks, I didn't think of that. But it's still confusing when you don't see the Preferences option when you click on the icon (when you disable footer in settings).

**Comment by moredhel** [comment]
I'm having the same issue.

It works if the footer is visible, but if I hide it then `command+,` stops working.

**Comment by artginzburg** [comment]
In Maccy's Preferences, under Appearance > Show footer, it is said:
> Press <kbd>⌘</kbd><kbd>,</kbd> to open preferences when footer is hidden.

So it would be strange to expect to see Preferences in footer after reading this label and disabling the footer...

Btw, <kbd>⌘</kbd><kbd>,</kbd> works fine for me in Maccy v0.18.2 (3), even if the footer is disabled.

**Comment by moredhel** [comment]
@artginzburg I'm not sure what you mean by:

> So it would be strange to expect to see Preferences in footer after reading this label and disabling the footer...

Perhaps we are misunderstanding.

If I go into preferences, then untick 'Show footer'. Then I close preferences, open Maccy & press `⌘,` then nothing happens.

I'm running the same version:

<img width="280" alt="image" src="https://user-images.githubusercontent.com/1742172/105808302-8383b480-5fb8-11eb-9341-38887bb11c3a.png">

Is there anything else I can try?

**Comment by p0deje** [comment]
@moredhel It might be a bug that `⌘,` doesn't open it because it should. Do you use regular English QWERTY layout?

**Comment by moredhel** [comment]
I use Dvorak, but I both the physical button `</,` & the remapped key with no success unfortunately.

You’ve got it :) I added a qwerty layout & I get the following behaviour (remapping ctrl+shift+a -> ctrl+cmd+v:

(Note, all keybindings are referenced by what is printed on the key)

- Dvorak layout: ctrl+cmd+. (V in Dvorak) opens maccy
- Dvorak layout with Maccy open: cmd+, || cmd+w nothing happens
- Qwerty layout: ctrl+cmd+. Opens Maccy ctrl+cmd+v no effect
- Qwerty layout Maccy open: cmd+, opens preferences as expected.

Hopefully that is enough to guide things. Is there anything I can provide to help?

Thanks :)

**Comment by p0deje** [comment]
Yeah, with other layouts it's getting complicated. I use #170 to track work related to this.

**Comment by moredhel** [comment]
Thanks @p0deje, I'll refer to that thread :)

**Comment by jakubkasparek** [comment]
+1

**Comment by jakubkasparek** [comment]
can be better to right click on icon 🙏

**Comment by Daku24** [comment]
I am still having this issue. I disabled the footer and now I can enter the setting. I am running Mac os 15.

**Comment by p0deje** [comment]
@Daku24 What's macOS 15? The latest is Sonoma 14. If you are running it, see https://github.com/p0deje/Maccy/issues/555 for workarounds.

**Comment by iamrajukh** [comment]
Just press the shortcut to **open Maccy clipboard, then press (⌘,)**

**Comment by kzaoaai** [comment]
for me it was confusing because I read the comma as part of the sentence, and was frustrated to have the CMD key not open the settings 😆. So yeah:
**CMD + ,**

**Comment by sanjarcode** [comment]
> for me it was confusing because I read the comma as part of the sentence, and was frustrated to have the CMD key not open the settings 😆. So yeah: **CMD + ,**

you mean `Cmd + ,`

**Comment by Eloren1** [comment]
<img width="324" height="77" alt="Image" src="https://github.com/user-attachments/assets/36c87297-d102-4a6b-b9ab-a5f35dae0619" />

It literally look like a part of the sentence

**Comment by Eloren1** [comment]
<img width="324" height="77" alt="Image" src="https://github.com/user-attachments/assets/51aa0df7-2209-4f73-8ede-c4eded09fd22" />

It literally looks as a part of the sentence

I came back exactly to this thread 1 year later because I forgot how to fix this

**Comment by p0deje** [comment]
Should be more clear in 5d963d5721cbfaac284882af6b6f0dd7d5907f98
