### ISSUE TITLE
Maccy didn't appear in Security & Privacy

### ISSUE THREAD

**Issue by alexpopov** [p0deje/Maccy#231]
Prompt came up. 

![Prompt](https://user-images.githubusercontent.com/903856/104742879-fec3ab80-5718-11eb-88f9-4f786b0a4e58.png)

But Maccy did not appear in Security & Preferences under Accessibility. 

![Pane](https://user-images.githubusercontent.com/903856/104742893-0420f600-5719-11eb-8e4a-ba8075d2ff83.png)

I tried restarting. I made sure SIP was enabled. I tried denying and then checking. 

It turns out that you can drag apps from `/Applications` directly into the pane and that auto-allows them. That worked for me.

Thank you for the beautiful app, devs. Just wanted to highlight this bug (in macOS?) and provide a solution if someone searches for it. 

macOS Big Sur 11.1
MacBook Pro 15-inch 2018

**Comment by p0deje** [comment]
Duplicate of #159
