### ISSUE TITLE
how do i automatically paste?

### ISSUE THREAD

**Issue by bkedryna** [p0deje/Maccy#233]
Hi. I just installed this app (Version 0.18.2 (3)) and it looks nice, but when I try to paste a clip, it only copies it to the clipboard but does not paste it, I have to do command-v to paste it.
It did not prompt me to add it to the accessibility list like a few other clipboard managers I tried. I added it anyway, but it didn't help. I'm not seeing any errors. What can I do to make it automatically paste when I hit enter/click on a clip?

**Comment by p0deje** [comment]
Check preferences, there is an option to enable that.

**Comment by bkedryna** [comment]
I missed it. It works after checking that. Sorry about that. Thanks.
