### ISSUE TITLE
switches to inactive instance of editor when 2 instances are open in the same desktop

### ISSUE THREAD

**Issue by ashisherc** [p0deje/Maccy#238]
When using VS code 2 instances on the same desktop, 

1. open maccy popup using the keyboard shortcut
2. select an item to copy using arrow keys
3. hit return

Maccy switches to the vs code instance in the background.

Expected to stay on the active instance as it is.

**Comment by p0deje** [comment]
Interesting - I will take a look at this issue. In the meantime, can you try enabling "Avoid taking application focus" in advanced preferences?

**Comment by ashisherc** [comment]
a restart fixed the issue, not sure if it needs investigation anymore
