### ISSUE TITLE
Maccy not ignores SafeInCloud's sensitive data

### ISSUE THREAD

**Issue by okliv** [p0deje/Maccy#240]
I tried to add this `CFBundleIdentifier`

```xml
	<key>CFBundleIdentifier</key>
	<string>com.safeincloud.Safe-In-Cloud.OSX</string>
```
from [SafeInCloud](https://www.safe-in-cloud.com)'s `info.plist`

to "Ignored pasteboard types" in advanced preferences - no luck, Maccy still stores passwords and other sensitive data

**Comment by p0deje** [comment]
Pastebody type is not the same as Bundle identifier, so it won't work. You can follow the example in https://github.com/p0deje/Maccy/issues/125#issuecomment-646612371 to find any pasteboard type you can ignore that is coming from SafeInCloud.

**Comment by okliv** [comment]
thanks for a reply!

![image](https://user-images.githubusercontent.com/884634/108280661-30e88300-7187-11eb-8bf3-79be39c31ff6.png)
this is all i see in pasteboard viewer :(

Should i ping SafeInCloud team to resolve this issue?

**Comment by p0deje** [comment]
You can ping them to add concealed type to their copies and link to http://nspasteboard.org.

I might improve the way we handle copies in general - watch #135 for this.
