### ISSUE TITLE
Feature Request:  Can we ignore by app?

### ISSUE THREAD

**Issue by ljohnston** [p0deje/Maccy#241]
Hi,

I just installed Maccy and it seems to have all the features a clipboard manager should (at least the ones I need). In trying to add some ignored pasteboard types, however, I've found that I can't fine tune things like I'd like to.

Specifically, I want to ignore anything copied while in MacVim. I downloaded the pasteboard viewer app, and whenever I copy something from MacVim, two things happen:
- the text gets copied to `public.utf8-plain-text`
- a pasteboard type of `VimPboardType` shows up that also has the copied text, but it's embedded in an xml doc

I understand that I can't realistically add an ignore for `public.utf8-plain-text`, and adding `VimPboardType` doesn't affect things.

However, I noticed that for each of the above entries, pasteboard viewer knows what application they came from. Highlighting each entry shows a "Source" of "MacVim" in the lower left corner of the pasteboard viewer UI.

Would it be possible for Maccy to also detect the "source" application of a copy and then be able to ignore based on that criteria?

Thanks,
Lance

**Comment by georgesnow** [comment]
This is similar #135

**Comment by p0deje** [comment]
@ljohnston You have found an interesting bug by stating that VimPboardType has no effect. I've fixed it in master so in the next version of Maccy you will be able to ignore using this pasteboard type.

**Comment by 4volodin** [comment]
> Hi,
> 
> I just installed Maccy and it seems to have all the features a clipboard manager should (at least the ones I need). In trying to add some ignored pasteboard types, however, I've found that I can't fine tune things like I'd like to.
> 
> Specifically, I want to ignore anything copied while in MacVim. I downloaded the pasteboard viewer app, and whenever I copy something from MacVim, two things happen:
> 
> * the text gets copied to `public.utf8-plain-text`
> * a pasteboard type of `VimPboardType` shows up that also has the copied text, but it's embedded in an xml doc
> 
> I understand that I can't realistically add an ignore for `public.utf8-plain-text`, and adding `VimPboardType` doesn't affect things.
> 
> However, I noticed that for each of the above entries, pasteboard viewer knows what application they came from. Highlighting each entry shows a "Source" of "MacVim" in the lower left corner of the pasteboard viewer UI.
> 
> Would it be possible for Maccy to also detect the "source" application of a copy and then be able to ignore based on that criteria?
> 
> Thanks,
> Lance

the same in strongbox-password manager,
 the text gets copied to public.utf8-plain-text

**Comment by ChrisFR06** [comment]
The same thing happens when copying anything from Bitwarden 😕

**Comment by p0deje** [comment]
@ChrisFR06 You can add it to "Ignored Apps" in 0.21.

**Comment by ChrisFR06** [comment]
> @ChrisFR06 You can add it to "Ignored Apps" in 0.21.

Thanks! Is there any way to ignore the copied content from Bitwarden.app when it's a password but not when it's any other field (e-mail, secure note, etc.)?

When using [Pasteboard Viewer](https://github.com/sindresorhus/Pasteboard-Viewer) to check the Type Identifier, it is always _public.utf8-plain-text_ regardless what is copied from Bitwarden so I guess it wouldn't be possible though.

**Comment by p0deje** [comment]
@ChrisFR06 There is no way to do it now but it will work as soon as they fix https://github.com/bitwarden/desktop/issues/90.
