### ISSUE TITLE
Popup location at menu item with hidden menu item results in inability to use Maccy.

### ISSUE THREAD

**Issue by TheFoolishPupil** [p0deje/Maccy#244]
I'm installing Maccy with `brew install --cask maccy`. After running the application the keyboard shortcut does nothing and there is not menu bar icon to get to the settings.

I'm on MacOS 11.2.1

**Comment by TheFoolishPupil** [comment]
After an unspecified amount of time the menu item decided to pop up and now everything seems to work as normal

**Comment by TheFoolishPupil** [comment]
Turns out the issue persists on a reboot. I now am seeing the same unexpected behaviour.

**Comment by adomasa** [comment]
Same behavior on the newest release. After restarting Mac OS with hidden from menu bar option, I cannot access Maccy anymore. It's in the process list, but menu doesn't pop up and there is no sound when copying as well.

**Comment by TheFoolishPupil** [comment]
Thanks for the input @adomasa, Upon further testing I was able to learn a couple things:

- It appears the issue is with having the menu icon hidden, and setting the popup location to be from the menu icon.
- When I use my external monitor the combination of these settings work but the pop up is drawn in the lower left corner of my screen. I have provided screen recordings of the behaviour below.

It could be argued that it makes sense that when the menu icon is hidden the popup cannot be positioned relative to it. The breaking issue currently however, is that once applying those settings, without my external monitor I would no longer be able to access the preferences and start using Maccy again. I suppose I would need to uninstall and locate plist files to clear saved preferences. 

Ideally I don't want to have the menu icon but I also don't want to have the pop up be centred or at the cursor. The way I see it my use case would be met by having a popup location that is called pin right/pin left. That and then fixing the issues with the hidden menu icon.

I will leave the issue open so that @p0deje perhaps has a look at it but for now I can use Maccy fine with the other popup options. If I get a chance I may look into creating a pull request for alternative popup locations. 

https://user-images.githubusercontent.com/43202406/108993864-687d9080-769b-11eb-9a3f-85c8d7b7c45a.mov

https://user-images.githubusercontent.com/43202406/108993884-6f0c0800-769b-11eb-8b7f-ad8c229fe8d1.mov

**Comment by p0deje** [comment]
I've changed the preferences window so that it's no longer possible to hide the menu icon and set popup location to "Menu icon" simultaneously. It would still be possible to mess things up by change preferences via Terminal, but I believe it's safe enough.

To restore to original preferences if you have this issue, run the following in Terminal:

```
defaults remove org.p0deje.Maccy popupPosition
defaults remove org.p0deje.Maccy showInStatusBar
```
