### ISSUE TITLE
Feature request: allow "Paste without formatting" for each paste

### ISSUE THREAD

**Issue by bkedryna** [p0deje/Maccy#245]
Hi. I love this app, but one thing that's really bugging me is that it's often pasting formatted text when I just want to copy a piece of text from one app to another, which screws up the font size. So I turned on the option "Paste without formatting", but in some cases I *do* want it to keep the formatting - for example when pasting an html table.
Would it be possible to change this feature to only work when, for example, I use shift-return to paste, but if I just use return, to paste with formatting?

**Comment by p0deje** [comment]
Yes. Inside preferences, you can see all shortcuts to paste with/without formatting. You just need to figure out the proper settings that work best for you.
<img width="378" alt="Screen Shot 2021-02-24 at 20 24 27" src="https://user-images.githubusercontent.com/665846/109102714-4ce7a980-76de-11eb-9d67-4f28cfb69a84.png">

**Comment by bkedryna** [comment]
I was actually asking for an option to paste without formatting, not copy. So that things could be copied normally but pasted either with or without formatting depending on the need.
The options above don't really work for me because I mostly copy using command-c. So since pressing the command button makes it copy without formatting, and i need to press the command button to copy, all my clips are without formatting. Maybe if the key was customizable so that I could copy using shift-command-c without formatting, that would mostly work for me, but I still think it would be better to be able to copy normally and only clear formatting when pasting.

**Comment by p0deje** [comment]
I don't quite follow what the problem is. The current flow is that I copy some text using Command+C and then I open Maccy and can paste it without formatting by pressing Option+Shift+1. The formatting is removed before pasting and the copy record itself still has all the formatting so I can open Maccy again and paste with formatting by pressing Option+1.

**Comment by bkedryna** [comment]
You said you're pasting with Option+Shift+1? That doesn't work for me at all. Did you mean Command+Shift+1?

I can replicate what you said, but in reverse. When I paste the formatted text with Command+Shift+1, **it stays formatted**. But if I paste it with just Command+1, it loses all its formatting. In addition, this appears to remove the formatting from the item in Maccy, so any subsequent paste with Command+Shift+1 pastes without formatting - I can't find any key combination to paste with formatting after this.

**Comment by p0deje** [comment]
Please check your preferences - you probably enabled pasting or paste without formatting by default. It will tell you exact shortcuts that you should use.

**Comment by bkedryna** [comment]
Ok, I see. This is a bit confusing, I thought that I have to enable it to make it paste without formatting. Maybe instead of "Paste without formatting" it should be called "By default, paste without formatting" or something like that.

I don't understand what the first option does: • Select with ⌥ pressed to copy item. (when Paste automatically is selected).
The option key doesn't seem to be doing anything for me. Option+Command+C doesn't copy the item, it opens some auto-correction feature in Outlook. In iTerm2 it seems to be doing something weird with the background of the copied item, but I'm not sure how that is relevant for Maccy.

Using Shift+Command+1 is great, but the problem is that it permanently erases the formatting, so if I accidentally paste without formatting but realize that I actually want formatting, I can't open Maccy again and paste it with Command+1, I have to go back to the original source of the item and copy it again.
This is also a problem with the "Paste without formatting" option checked. Since pasting without formatting permanently erases the formatting, and that's the default option, this is why I could never paste with formatting - I always tried normal paste first, which erased the formatting, and then trying Shift+Command+1 after that didn't work because the formatting was already gone.

**Comment by p0deje** [comment]
>  Select with ⌥ pressed to copy item
As opposed to copy and paste. You can select an older item in the list and it will be added to the system clipboard.

> The option key doesn't seem to be doing anything for me. Option+Command+C doesn't copy the item, it opens some auto-correction feature in Outlook. In iTerm2 it seems to be doing something weird with the background of the copied item, but I'm not sure how that is relevant for Maccy.

All these keybindings work only when Maccy window is visible.

> Using Shift+Command+1 is great, but the problem is that it permanently erases the formatting, so if I accidentally paste without formatting but realize that I actually want formatting, I can't open Maccy again and paste it with Command+1, I have to go back to the original source of the item and copy it again.

You don't, you just need to open Maccy again and press Command+1. I just tested it and I can paste the same item both with and without formatting - I don't have to copy again.

> This is also a problem with the "Paste without formatting" option checked. Since pasting without formatting permanently erases the formatting, and that's the default option, this is why I could never paste with formatting

Pasting without formating doesn't erase the formatting permanently. If it happens, it might be some particular bug so I'll need to reproduction example (what do you copy, from which app, what preferences do you have).

**Comment by bkedryna** [comment]
Ok this is what I'm going:
1. Open a new Outlook email
2. Type TestRedWhite and then select Red and change the color to red
3. Open Maccy and hit return. It pastes it exactly as it is (with Red being red)
4. Now open Maccy again, press Shift+Command+Return. It pastes it as all white (I'm in dark mode, so when I say white, it will be black for someone in normal mode)
5. Open Maccy again and hit return. It pastes it as all white now, not like it did in #3 

I have "Paste automatically" checked but "Paste without formatting" is not checked.

**Comment by p0deje** [comment]
I think when you paste in Outlook it might update the default style so it's not overwritten even when you paste plain/colored text. I don't have Outlook to check, but I can observe this behavior in Pages and it is in fact dictated by the app itself, not Maccy. If you reset styles and paste again - the colors are red, so Maccy doesn't erase formatting.

**Comment by bkedryna** [comment]
You're right, this is some weird bug in Outlook. Even when I opened a new email and pasted there, it's without formatting. I had to completely close it and re-open Outlook, and now it's behaving correctly and I'm not able to replicate the problem.
It's weird that Pages would have the same bug. It can't be a feature since it's inconsistent.
Thanks for your help.
I think you should clarify these options in the preferences page to make it clearer what they do. For example, "• Select with ⌥ pressed to copy item." sounds to me like it's about copying an item from some other app into the clipboard/Maccy. I would change it to "• Select with ⌥ pressed to move item to clipboard"
