### ISSUE TITLE
Bug: the app suddenly stops to handle copy events

### ISSUE THREAD

**Issue by Loskir** [p0deje/Maccy#248]
It happens quite often and continues until I restart the app. I haven't investigated this much, but it seems like it happens after I use "click-to-copy" on monospace text in Telegram for macOS.

I'm willing to provide any additional information.

**Comment by pnegahdar** [comment]
FWIW pasting images in telegram is also crashing Telegram for me.  Works fine in other apps though.

**Comment by Loskir** [comment]
> crashing Telegram

Can't reproduce though

**Comment by pnegahdar** [comment]
Might be a M1 thing? No clue.

**Comment by p0deje** [comment]
@Loskir Can you please provide a test case so I could reproduce?

**Comment by Loskir** [comment]
Bad news: I can't reproduce it anymore
Good news: it works fine

Is there a way to enable some debug logs to give it to you if something goes wrong?

**Comment by p0deje** [comment]
There is not really any particular debug mode and logging is rudimental in Maccy. I guess I need to make it better.

Still, whenever the crash happens, there should be something in Console.app if you search for `Process: Maccy`.

Such a silent crash could happen when copying something strange which Maccy fails to store in the database (or the code doesn't handle some esoteric data).

**Comment by Loskir** [comment]
here's how it works (sometimes, but i was able to reproduce it 3 times today)

https://user-images.githubusercontent.com/21295738/110238944-64802700-7f55-11eb-89a7-d1f2688ec969.mp4

here's some logs
<img width="1255" alt="image" src="https://user-images.githubusercontent.com/21295738/110239023-df494200-7f55-11eb-9f1b-e451b0cd8915.png">

**Comment by p0deje** [comment]
Ok, this is interesting. I'll need to investigate. Thanks for the test case and logs!

**Comment by p0deje** [comment]
Hrm, how do you create colorful messages in Telegram? I tried with monospaced, but it doesn't craash.

**Comment by Loskir** [comment]
Cmd+shift+k

**Comment by p0deje** [comment]
I've tried copying monospaced but it works fine. Not sure how to check colored messages.

**Comment by Loskir** [comment]
Monospaced text appears colored in telegram for macos. 

Seems like this issue is indeed inconsistent

**Comment by p0deje** [comment]
> Monospaced text appears colored in telegram for macos.

Hm, it's not colored for me. What Telegram version do you use?

**Comment by Loskir** [comment]
https://macos.telegram.org/

Or, more specifically, the beta one https://telegram.org/dl/macos/beta

**Comment by p0deje** [comment]
Tried getting Beta but still cannot reproduce. According to the error you have shown, it looks like it's trying to add a new copy to the Maccy popup menu but it doesn't properly calculate its position (according to various configuration settings). Can you please also share the output of running `defaults read org.p0deje.Maccy` in Terminal.app?

**Comment by Loskir** [comment]
```
{
    "KeyboardShortcuts_popup" = "{\\"carbonModifiers\\":768,\\"carbonKeyCode\\":8}";
    "NSStatusItem Visible Item-0" = 0;
    "NSWindow Frame SUUpdateAlert" = "390 357 660 398 0 0 1440 875 ";
    "NSWindow Frame com.sindresorhus.Preferences.FrameAutosaveName" = "478 102 669 773 0 0 1440 875 ";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2021-03-02 10:43:52 +0000";
    SUSendProfileInfo = 0;
    enabledPasteboardTypes =     (
        "public.utf8-plain-text",
        "public.tiff",
        "public.png",
        "public.file-url"
    );
    fuzzySearch = 1;
    hideTitle = 1;
    history = {length = 42, bytes = 0x62706c69 73743030 a0080000 00000000 ... 00000000 00000009 };
    historySize = 999;
    ignoreEvents = 0;
    ignoredPasteboardTypes =     (
        "com.agilebits.onepassword",
        "com.typeit4me.clipping",
        "net.antelle.keeweb"
    );
    maxMenuItems = 20;
    migrations =     {
        "2020-02-22-history-item-add-copied-at" = 1;
        "2020-02-22-history-item-add-number-of-copies" = 1;
        "2020-04-18-switch-storage-to-core-data" = 1;
        "2020-04-25-allow-custom-ignored-types" = 1;
        "2020-06-19-use-keyboardshortcuts" = 1;
        "2020-09-01-ignore-keeweb" = 1;
        "2021-02-20-allow-to-customize-supported-types" = 1;
    };
    pasteByDefault = 1;
    playSounds = 1;
    showInStatusBar = 0;
    showRecentCopyInMenuBar = 0;
    sortBy = firstCopiedAt;
}
```

**Comment by p0deje** [comment]
I have a feeling that combination of `sortBy = firstCopiedAt` and `maxMenuItems = 20` ends up with crash. I'm going to switch to similar settings and see if I can reproduce during the normal usage.
