### ISSUE TITLE
Option to disable "Are you sure you want to clear the history?" confirmation dialog

### ISSUE THREAD

**Issue by mikewindow** [p0deje/Maccy#249]
Thank you for this great app.

In the latest release the app started asking "Are you sure you want to clear the history?" when I try to clear the history. How can the confirmation dialog be disabled?

When getting ready for a screenshare session right before a meeting even a few seconds are critical, especially with back-to-back meetings 😬

**Comment by mikewindow** [comment]
https://github.com/p0deje/Maccy/issues/208 added the confirmation dialog. It can't be disabled.

**Comment by mikewindow** [comment]
The [0.19.0](https://github.com/p0deje/Maccy/releases/tag/0.19.0) release has Apple Silicon support. I can downgrade to that release permanently to avoid the annoyance.

**Comment by mikewindow** [comment]
It looks pressing Enter will confirm the dialog. However if you're not used to the popup window and you click on another window the popup will lose focus.

**Comment by mikewindow** [comment]
The 0.19.0 is working, is a universal build, and stays out of your way :)

**Comment by p0deje** [comment]
In the upcoming version it will be possible to select "Don't ask again" and confirmation won't be shown anymore.
