### ISSUE TITLE
[FEATURE REQUEST] Support for case insensitive fuzzy search

### ISSUE THREAD

**Issue by dodalovic** [p0deje/Maccy#25]
First of all - thanks for very promising tool!
I was wondering - would there be a way that (via configuration) enable fuzzy search so that e.g if I have entry in history: 

`Foo Bar Baz`

and if I search 

`fbb`

it matches entry from above? 

Cheers

**Comment by p0deje** [comment]
Yeah, the fuzzy search was something that I planned to add initially, but I never really found time to do that. For me personally the existing search worked fine. I'll definitely implement something like the fuzzy search with an option to turn it on/off.
