### ISSUE TITLE
Bottom-pinned clippings losing anchoring when deleting unpinned clippings above

### ISSUE THREAD

**Issue by mrzool** [p0deje/Maccy#250]
Hello and thanks for this great clipboard manager.

I stumbled upon this bug after changing the location of pinned items from top to bottom.

Steps to reproduce:

1. Pin some clippings to the bottom
2. Delete one or two unpinned clippings
3. Press `<esc>` to hide Maccy
4. Open Maccy again

Pinned items are no longer anchored to the bottom — unpinned older clippings are shown below them. Occasionally pinned items are shown twice, once in the middle of other items, once at the bottom.

This persists until a restart.

**Comment by p0deje** [comment]
1. Can you please share the output of running `defaults read org.p0deje.Maccy` in Terminal.app?
2. I'm trying to reproduce the issue, but I can't. Can you please provide more concrete steps to see it?

**Comment by mrzool** [comment]
> Can you please share the output of running defaults read org.p0deje.Maccy in Terminal.app?

Sure, here it is:

```
{
    "KeyboardShortcuts_popup" = "{\\"carbonModifiers\\":768,\\"carbonKeyCode\\":9}";
    "NSStatusItem Visible Item-0" = 0;
    "NSWindow Frame SUUpdateAlert" = "352 288 620 392 0 0 1280 777 ";
    "NSWindow Frame com.sindresorhus.Preferences.FrameAutosaveName" = "429 284 549 591 0 0 1440 875 ";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2021-03-16 22:31:33 +0000";
    WebKitDefaultFontSize = 13;
    WebKitJavaEnabled = 0;
    WebKitJavaScriptEnabled = 0;
    WebKitPluginsEnabled = 0;
    WebKitStandardFont = "-apple-system-font";
    WebKitUserStyleSheetEnabledPreferenceKey = 1;
    WebKitUserStyleSheetLocationPreferenceKey = "/Applications/Maccy.app/Contents/Frameworks/Sparkle.framework/Resources/ReleaseNotesColorStyle.css";
    enabledPasteboardTypes =     (
        "public.png",
        "public.utf8-plain-text",
        "public.file-url",
        "public.tiff"
    );
    fuzzySearch = 1;
    hideFooter = 1;
    hideTitle = 1;
    history = {length = 42, bytes = 0x62706c69 73743030 a0080000 00000000 ... 00000000 00000009 };
    ignoredPasteboardTypes =     (
        "net.antelle.keeweb",
        "com.agilebits.onepassword",
        "com.typeit4me.clipping",
        "de.petermaurer.TransientPasteboardType",
        "Pasteboard generator type"
    );
    maxMenuItems = 10;
    migrations =     {
        "2020-02-22-history-item-add-copied-at" = 1;
        "2020-02-22-history-item-add-number-of-copies" = 1;
        "2020-04-18-switch-storage-to-core-data" = 1;
        "2020-04-25-allow-custom-ignored-types" = 1;
        "2020-06-19-use-keyboardshortcuts" = 1;
        "2020-09-01-ignore-keeweb" = 1;
        "2021-02-20-allow-to-customize-supported-types" = 1;
    };
    pasteByDefault = 1;
    pinTo = bottom;
    playSounds = 0;
    popupPosition = cursor;
    removeFormattingByDefault = 1;
    showInStatusBar = 0;
    sortBy = lastCopiedAt;
}
```

> I'm trying to reproduce the issue, but I can't. Can you please provide more concrete steps to see it?

The steps I described above are really all there is to it. I'm still able to reproduce using the settings above, running on Big Sur 11.2 on an M1 MacBook Air. I pinned two clips to the bottom, then deleted two clips from the top using `alt+backspace`, pressed `esc`, opened Maccy again with my custom shortcut `cmd+shift+v`, and the pinned clips moved two steps upwards.

**Comment by mrzool** [comment]
Thanks for fixing it!
