### ISSUE TITLE
Maccy will not capture any copy events.

### ISSUE THREAD

**Issue by dustatron** [p0deje/Maccy#251]
Last week Maccy stopped capturing my copy actions entirely. 
I cleared the history and now, sadly, Maccy's list is empty and there doesn't seem to be anything I can do to get it to work again. 

I am working on an intel 13" 2019 macbook pro running macOS Mojave 10.14.6.

I have tried restarting the app, the computer, and I tried uninstalling and reinstalling.

**Comment by p0deje** [comment]
Any chance you disabled it? Can you check preferences and show screenshots of every tab?

**Comment by p0deje** [comment]
Closing since no response. Please reopen with additional details.
