### ISSUE TITLE
Maccy hangs when searching and prevents keyboard input

### ISSUE THREAD

**Issue by C-Saunders** [p0deje/Maccy#252]
MacOS version 11.2.3
Maccy version 0.20.0
defaults read org.p0deje.Maccy:
```
{
    "KeyboardShortcuts_popup" = "{\\"carbonModifiers\\":768,\\"carbonKeyCode\\":9}";
    "NSStatusItem Preferred Position Item-0" = 382;
    "NSWindow Frame SUUpdateAlert" = "970 767 620 392 0 0 2560 1415 ";
    "NSWindow Frame com.sindresorhus.Preferences.FrameAutosaveName" = "766 394 623 758 0 0 2560 1415 ";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2021-03-11 19:37:52 +0000";
    SUSendProfileInfo = 0;
    SUUpdateRelaunchingMarker = 1;
    avoidTakingFocus = 1;
    enabledPasteboardTypes =     (
        "public.utf8-plain-text",
        "public.tiff",
        "public.file-url",
        "public.png"
    );
    fuzzySearch = 1;
    history = {length = 4642931, bytes = 0x62706c69 73743030 af10c800 01000b00 ... 00000000 0046c4c7 };
    historySize = 75;
    hotKey = "command+shift+v";
    ignoredPasteboardTypes =     (
        "de.petermaurer.TransientPasteboardType",
        "Pasteboard generator type",
        "com.typeit4me.clipping",
        "net.antelle.keeweb",
        "com.agilebits.onepassword"
    );
    maxMenuItems = 28;
    migrations =     {
        "2020-02-22-history-item-add-copied-at" = 1;
        "2020-02-22-history-item-add-number-of-copies" = 1;
        "2020-04-18-switch-storage-to-core-data" = 1;
        "2020-04-25-allow-custom-ignored-types" = 1;
        "2020-06-19-use-keyboardshortcuts" = 1;
        "2020-09-01-ignore-keeweb" = 1;
        "2021-02-20-allow-to-customize-supported-types" = 1;
    };
    pasteByDefault = true;
    pinTo = top;
    popupPosition = center;
    removeFormattingByDefault = 0;
    showInStatusBar = 1;
}
```

Multiple times now I've typed a couple of letters into the search and Maccy has frozen (spinning beach ball) and prevented all keyboard input, system wide. Since it doesn't appear in the force quit menu and I can't kill it via the terminal (no keyboard input), I have to restart my computer to fix it.

You might be able to conclude this from the history length, but I recently copied some _really_ big blocks of text (like 15MB+). If this is the issue, maybe it would be good if giant items could be excluded from the history and/or search?

Thanks for taking a look and please let me know if you need any additional info!

P.S. I should add that I love Maccy! Thanks for all your work on it!

**Comment by p0deje** [comment]
@C-Saunders Any chance you could try this build and see if it's any better? [Maccy.app.zip](https://github.com/p0deje/Maccy/files/6159888/Maccy.app.zip)

**Comment by tomvardasca** [comment]
Now it works perfectly! I was having the same issue.
 Thank you for looking into it @p0deje

**Comment by p0deje** [comment]
I guess we can close it. Will be released soon.

**Comment by C-Saunders** [comment]
@p0deje sorry I never had a chance to try the new build. Thank you for putting it together and thanks @tomvardasca for testing it out!
