### ISSUE TITLE
Feature Request - Ability to tag items with meta keywords and expose them as searchable

### ISSUE THREAD

**Issue by madhurjain2095** [p0deje/Maccy#254]
Hi,

I am recent MacOS user and because of my work, I need to use a clipboard manager to copy and manage multiple meeting IDs (zoom/slack/chime) and I was wondering if there was in any way to tag them as such. Like, when you copy the meeting ID from the clipboard, there's no way to know which meeting ID corresponds to which meeting and as such, I end up going back to my calendar and copy the meeting ID again (which seems like a waste to me). I would like to tag such meeting IDs or in general, any item, with some extra meta keywords and make them searchable so that whenever I type in the meeting name, the ID should pop up and I can copy and join the meeting.

I understand that the use case I am depicting here is quite specific, but the addition of meta keywords can be very helpful in other scenarios too.

Please let me know what you think about this.

PS: I really love using Maccy since its very minimalist and has a lot of keyboard shortcuts.

**Comment by p0deje** [comment]
This is very similar to #89 where aliases for pins are requested. I'm not sure when and if I'm going to implement this, but PRs are very much welcome!
