### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by orangesunny** [p0deje/Maccy#256]
I recently started using Maccy; I like it and realized it’s not much localized. Also, I couldn’t find any official information about the translation effort.

As it’s developed in Swift, i18n should be pretty easy. For l10n, as one open-source enthusiast to another, I can say that we in [Weblate](https://github.com/WeblateOrg/weblate/) are offering the platform to libre projects for free and I am prepared to help.

**Comment by p0deje** [comment]
The current application supports the following languages:

* English
* Spanish
* French
* Russian
* Simplified Chinese
* Norwegian

I'll be happy to accept PRs which add more languages, though it takes more effort to localize because we use XIB for the interface so it needs to be localized using Xcode. An example could be https://github.com/p0deje/Maccy/commit/7f8907dc1da79213129bb959c8af4acf605e60f3 (though there has been more UI changes since this commit).

**Comment by orangesunny** [comment]
@p0deje
Thanks for the information; I understand this way.

I suggested using a continuous localization platform to raise the translations’ quality, make it easier for developers, translators, and make it continuous. Localize through manually-edited files or IDE is time-consuming for everyone and quite messy. Xcode can provide `.lproj` that are pretty easy to handle properly then.

**Comment by p0deje** [comment]
That sounds interesting, but I have no idea how using continuous localization platform would work in this case. I'm also not sure I have time to put effort into this.

**Comment by orangesunny** [comment]
That is just the thing to be easily solved :) To save your valuable time so you can develop and not care about translations.

All the strings are in [here](https://github.com/p0deje/Maccy/blob/master/Maccy/en.lproj/Localizable.strings), right?

You can set it up in a few minutes at https://hosted.weblate.org/hosting/. If you don’t want to care about it, I can set it up and give you the admin rights for possible configuration changes.

Once the translation project is up and running at Hosted Weblate, you’ll just check and merge the PRs with valid translation files once they appear. (Direct push is also possible, that is just another approach.)

**Comment by p0deje** [comment]
Closing since I have no capacity to figure out the setup.
