### ISSUE TITLE
Feature Request: popup by shortcut do not lose focus

### ISSUE THREAD

**Issue by RealHanTing** [p0deje/Maccy#257]
Thanks for providing this app as open source!

when I popup Maccy by shortcut, current app will lose focus.

I alse use another app [Clipy](https://github.com/Clipy/Clipy), which does not lose focus, but it only saves plain text.

Can you optimize that? It will be much more convenient.

![image](https://user-images.githubusercontent.com/16221901/112612490-f0e97f80-8e59-11eb-9183-860720f05c42.png)

![image](https://user-images.githubusercontent.com/16221901/112612765-42920a00-8e5a-11eb-9e43-52e45a28dd46.png)

**Comment by p0deje** [comment]
You can disable this behavior in Preferences -> Advanced.
