### ISSUE TITLE
Maccy saves clipboard contents after disabling "ignoreEvents" in plist

### ISSUE THREAD

**Issue by LiorElb** [p0deje/Maccy#260]
Hey,
I've noticed an issue with the "Ignore Copied Items" mechanism specified in the README.md file.

Scenario is:
1. set "ignoreEvents" to true
2. copy and paste something sensitive
3. set "ignoreEvents" to false

After step 3 the sensitive data you copied while Maccy was disabled will be **back in the Maccy storage**.

Also - Iv'e noticed there is a pull request open that introduces `Private Mode`.  #242 
 I believe the same issue will happen there after the private session times out.

Update:
This behaviour also reproduces when using the `Turn Off` button in the Preferences->Advanced tab

**Comment by yunus776** [comment]
> Hey,
> 
> I've noticed an issue with the "Ignore Copied Items" mechanism specified in the README.md file.
> 
> 
> 
> Scenario is:
> 
> 1. set "ignoreEvents" to true
> 
> 2. copy and paste something sensitive
> 
> 3. set "ignoreEvents" to false
> 
> 
> 
> After step 3 the sensitive data you copied while Maccy was disabled will be **back in the Maccy storage**.
> 
> 
> 
> Also - Iv'e noticed there is a pull request open that introduces `Private Mode`.  #242 
> 
>  I wonder if the same issue happens there after the private session times out.
> 
> 
> 
>

**Comment by p0deje** [comment]
Should be fixed in #261 and available in the next released.
