### ISSUE TITLE
[Feature Request] Ability to pause and resume.

### ISSUE THREAD

**Issue by harshasrisri** [p0deje/Maccy#263]
Hi,

Thanks for the great tool. Coming from Linux desktops, this functionality was sorely missing. 

I'd like to request a feature that would be useful while copying sensitive content like passwords, where I can pause Maccy from the context menu and resume it afterwards.

**Comment by p0deje** [comment]
You can Option+Click on it menu bar icon to pause/unpause. Would that be enough?

**Comment by harshasrisri** [comment]
Oh, yes! Didn't know this feature already existed. Thank you.

**Comment by kikker902** [comment]
> You can Option+Click on it menu bar icon to pause/unpause. Would that be enough?

Do I miss something? Option+Click does not pause/unpause for me. It just opens Maccy.

**Comment by p0deje** [comment]
@kikker902 Can you please record a video showing the problem?

**Comment by kikker902** [comment]
See attached video showing Maccy when I option click the menu bar icon. No pause.

https://user-images.githubusercontent.com/7262498/150123535-07e6c531-d9c0-4740-b9ad-2adaba5d3e05.mp4

**Comment by p0deje** [comment]
@kikker902 It only works when Maccy popup is closed.

**Comment by kikker902** [comment]
But when I option click or a none option key click Maccy does show its popup. There is just no different behaviour with or without the option key.

**Comment by p0deje** [comment]
Ok, can you please record how Maccy opens the popup when you option-click it? Can you also show what's happening when you cmd-click it?

**Comment by kikker902** [comment]
**Option click:**
![option](https://user-images.githubusercontent.com/7262498/150166709-01310ace-72dc-4714-bd3d-9f58b98bc4df.png)
_Opens Maccy_ 

**Command click:**
<img width="579" alt="image" src="https://user-images.githubusercontent.com/7262498/150167487-527860ad-9ae2-486b-bf9e-2a7644b40d0a.png">![command](https://user-images.githubusercontent.com/7262498/150166869-0e0d79ac-f214-46c4-a335-843ee785ee09.png)
_Icon gets lighter indicating that you can reorder the icon. Default Mac behaviour._

**Comment by p0deje** [comment]
@kikker902 Do you run the latest version of Maccy - 0.22? Please, double-check because I cannot reproduce the problem.

**Comment by harshasrisri** [comment]
I don't use this feature frequently anymore, but new comments made me test it. I'm running the latest Maccy 0.22.

Option+Click pauses Maccy as expected, but Option+Click again doesn't seem to unpause it. 

I had to go to Pref->Advanced->TurnOn. 

I'm running MacOS Monterey, if it helps.

**Comment by p0deje** [comment]
@harshasrisri Please record a video showing how you turn it off and how it doesn't turn on.

**Comment by harshasrisri** [comment]
I had to restart my mac over the last weekend. But now, I can't reproduce this behavior anymore. What I did earlier and now was the same: click on the Maccy icon holding down the Option key to pause/unpause. I'm sorry this was not of much help.
