### ISSUE TITLE
Make "customise when pasting" configurable

### ISSUE THREAD

**Issue by cub-uanic** [p0deje/Maccy#265]
Please make these modifiers configurable:
![Screenshot 2021-03-31 at 19 47 01](https://user-images.githubusercontent.com/75673/113180835-de0bec00-9259-11eb-88c6-c3652ac16075.png)

For example, I'd like to "clear formatting and paste" with Cmd+Shift.

Thanks!

**Comment by p0deje** [comment]
Sorry but I don't see much value in making this configurable. It's not much harder to press Option instead of Cmd+Shift in my opinion. Do I miss some use case?

**Comment by cub-uanic** [comment]
I'm using Kinesis Advantage with TMK, pretty sure there are many users of QMK too.
On the keyboard with custom controller and firmware, and with non-standard keys displacement, accessibility of modifiers (and moreover - several of them at once) could be really different than on usual keyboards.

Also, just because hard-coded modifier prefixes could not be convenient for all.

Hope this is good enough reason :)

**Comment by p0deje** [comment]
I'm going to close this as I don't intend to implement it. I understand there are special cases with different keyboards and different layouts but I don't have time/energy to work on this. If somebody wants to do it, I'll be glad to merge PRs:

* Allow keybindings to be configurable
* Implement some sensible UI to make this configuration
* Don't forget to cover every case to prevent the same keys bound to different actions
* Localizations
