### ISSUE TITLE
Installing on macOS High Sierra

### ISSUE THREAD

**Issue by boraoztunc** [p0deje/Maccy#266]
Can't install the latest version (0.20.0) to my old chap MacBook pro, which I recently changed its SSD and installed a fresh copy of High Sierra, version 10.13.6. Trying to get my apps back, and Maccy really made a habit, easy to use, don't want to try another one. Any change I can get it?

**Comment by p0deje** [comment]
Maccy doesn't work on High Sierra since 0.17 and there is no way to make it work there. So your only chance would be to keep using the old 0.16.0 https://github.com/p0deje/Maccy/releases/tag/0.16.0

**Comment by boraoztunc** [comment]
I'm happy with the old 0.16.0. 

Thank you Alex.
