### ISSUE TITLE
Show preview also without the use of the mouse

### ISSUE THREAD

**Issue by valentinocossar** [p0deje/Maccy#267]
Right now the only way to display a preview is to use the mouse to go over the row and open the preview popup. Would be great to add a sidebar to show the preview when a specific row is selected, no matter if you are using a mouse or a keyboard.

This is an example:
![image](https://user-images.githubusercontent.com/4087384/113448894-fec07700-93fc-11eb-8791-d3e2b26fe1d6.png)

What do you think?

**Comment by p0deje** [comment]
The preview is shown when the item is selected by keyboard/mouse/search already. What is missing?

**Comment by valentinocossar** [comment]
You're right, I'm not seen this because I've found somewhere a tip to show the content with the mouse hover, but my suggestion is a little bit different even if is working also with the keyboard.

I try to explain better what I thinking.

An option to allow the content to appear "instantly" without waiting an amount of time, maybe with a fixed sidebar as reported in the screenshot, also with larger font size and a design in line with the main Maccy window.

Is better explained in this way?

**Comment by p0deje** [comment]
Frankly, I don't see much value in this. The current implementation uses native menu item tool tips to show preview and implementing something more complicated is going to take a lot of effort. I think it's just not worth it.

The only use case for a custom preview I think reasonable is the preview of images that is completely missing now. I'm pushing it back as there aren't many requests on it, but I might implement it at some point. This will be a good time to also switch preview for text too.

Plus, I don't see myself using this at all as I rarely need to preview. Search feature always finds exactly what I need so there is no need to double check before pasting. That's my workflow, but I'm eager to learn other use cases where instant preview is useful.

**Comment by valentinocossar** [comment]
I depend a lot on preview because I copy similar texts and it's important for me to understand which one I have to select to reuse. And with a fixed sidebar to show the preview I'm faster to do this kind of task.

But I understand the effort behind an integration like this. As you pointed out, maybe the right approach is to see if people are interested or not in this implementation.

**Comment by Altair-Bueno** [comment]
Not related @valentinocossar , but how do you make the preview appear on the right side? im looking my settings and i cannot find anything like that

**Comment by valentinocossar** [comment]
@Altair-Bueno The screenshot is from another clipboard manager app not from Maccy.

**Comment by bjorndotwork** [comment]
Counter-request (kind of): option to disable previews altogether, or at least option to require some mouse hover or key press to activate them. Unnecessary visual noise for those who don't always/often need them.

**Comment by andylima** [comment]
I, too, really miss what @valentinocossar is talking about here…

A preview area with:
- a larger font (the current tooltips are harder to read)
- ability to scroll down too see many lines (incredibly useful for coding, and writing)
- clear separation between an entry's contents and the stats on it (currently it's hard to distinguish them)
- ability to preview images and other media content

Also, as mentioned:
- tooltips take too long to show up
- tooltips are actually more distracting than a fixed preview area on the right side

And I also frequently have this problem that @valentinocossar mentioned:
> I copy similar texts and it's important for me to understand which one
> I have to select to reuse. And with a fixed sidebar to show the preview
> I'm faster to do this kind of task.

**Comment by p0deje** [comment]
Per #346, it would also be great to have buttons for actions on it (pin, delete) in the richer preview.

**Comment by Drunk-Creator** [comment]
@p0deje I got Maccy via the App Store and am loving it. However, I do find myself wanting a feature like the one mentioned here or in #286. I do a copy a lot of codes and it's quite hard to read when everything is crammed into a single line with "enter key" symbols.

Maybe it could be a toggle to enable such a feature so that others who don't really like it won't be affected.

Thanks!

**Comment by p0deje** [comment]
In the upcoming version of Maccy, there will be a "rich" preview which would show multiline text and images in higher resolution, here are some examples:

<img width="1209" alt="Screenshot 2023-01-30 at 10 36 28" src="https://user-images.githubusercontent.com/665846/215565394-1f60c5de-9e65-4cea-91b2-64c76fbf6dfc.png">
<img width="1027" alt="Screenshot 2023-01-30 at 10 35 40" src="https://user-images.githubusercontent.com/665846/215565405-f8dcdcb3-5802-4bdd-9316-78ee4953fdaf.png">
