### ISSUE TITLE
Add option to disable menu bar icon (without using Bartender os similar third apps)

### ISSUE THREAD

**Issue by valentinocossar** [p0deje/Maccy#268]
Would be great to add the option to disable the menu bar icon (without using Bartender or similar third apps). If someone doesn't need this option and wants to free a slot in the menubar for other apps, this feature could be very useful.

What do you think?

**Comment by p0deje** [comment]
Ugh, have you looked into Preferences? :)

**Comment by valentinocossar** [comment]
@p0deje sorry sorry, didn't see the option! Thank you for the support! 😅
