### ISSUE TITLE
Where are the pinned shortcuts stored?

### ISSUE THREAD

**Issue by agamemnonc** [p0deje/Maccy#271]
Hi, I would like to back-up my pinned shortcuts, but I wasn't able to find the location of the config file where they are stored. Thanks!

**Comment by yunus776** [comment]
> Hi, I would like to back-up my pinned shortcuts, but I wasn't able to find the location of the config file where they are stored. Thanks!

![image](https://user-images.githubusercontent.com/80426622/113996268-af949f00-985f-11eb-8dcd-cedf3abf8185.jpeg)
- [ ] - - [ ] Edermişim @p0deje [_**![image](https://user-images.githubusercontent.com/80426622/113996384-ce933100-985f-11eb-82a6-22669a9cb99e.png)**_](https://adaptedijital.com/n/wp-content/uploads/2020/02/Gellary_img-5.jpeg)

**Comment by p0deje** [comment]
@agamemnonc It's located in `~/Library/Containers/org.p0deje.Maccy/Data/Library/Application Support/Maccy`.
