### ISSUE TITLE
中文汉字展示效果不佳（The effect of displaying Chinese characters is not good） 如图所示

### ISSUE THREAD

**Issue by shiyuenianwu** [p0deje/Maccy#272]
![https://lisan-1256186535.cos.ap-nanjing.myqcloud.com/uPic/ZKJkeQ.png](https://lisan-1256186535.cos.ap-nanjing.myqcloud.com/uPic/ZKJkeQ.png)

As shown in the figure

**Comment by p0deje** [comment]
What? You just show a screenshot of your desktop image - how is it related to Maccy? I really don't get it.

**Comment by pekcheey** [comment]
I think OP is expecting to see the actual chinese characters in the search result instead of the character codes.

**Comment by p0deje** [comment]
I'm looking at the screenshot and it shows a desktop. @pekcheey Can you elaborate?

**Comment by kidonng** [comment]
I think the OP wants to say Maccy should display the filename as-is (`IBV产品培训-0122.pptx`), not its encoded form (`IBV%E4%BA%A7%E5%93%81%E5%9F%B9%E8%AE%AD-0122.pptx`).

**Comment by kidonng** [comment]
@p0deje Thanks for the quick fix!
