### ISSUE TITLE
[FR] Run shell script on new entries

### ISSUE THREAD

**Issue by NightMachinary** [p0deje/Maccy#276]
It would be great if the app could support running shell scripts when some triggers happened:
- new item added to the clipboard (i.e., new item copied)

PS: Thanks for the great app! I have used multiple clipboard managers on macOS, and yours seems just perfect.

**Comment by p0deje** [comment]
What's the use case? Can you share more details? I definitely don't see Maccy implementing this feature specifically, but it's possible that it might support some kind of notifications that can be used in Apple Script or other scripting.

**Comment by NightMachinary** [comment]
Never mind, I implemented a polling based solution which is easier to port to Linux anyway. The use case is that now I have an fzf-enabled clipboard manager in both `zsh` and `emacs` ^_^

![image](https://user-images.githubusercontent.com/36224762/114571199-ba01cf00-9c8b-11eb-8192-a11c66c5fcc4.png)

I have even integrated emoji insertion into it:

![image](https://user-images.githubusercontent.com/36224762/114571782-2977be80-9c8c-11eb-925c-940035ce4ffa.png)

Unix is awesome.

**Comment by p0deje** [comment]
Maccy can't compete with Unix.

**Comment by NightMachinery** [comment]
> What's the use case? Can you share more details? I definitely don't see Maccy implementing this feature specifically, but it's possible that it might support some kind of notifications that can be used in Apple Script or other scripting.

How are you getting the new entries from the OS? My polling solution isn't so great for the battery life.

**Comment by p0deje** [comment]
@NightMachinery By polling, there is no other way.
