### ISSUE TITLE
[FR] Use scroller to wrap menu items

### ISSUE THREAD

**Issue by soakit** [p0deje/Maccy#277]
wrap history menu items with a scroller, and make the search area and operation menu items fixed.

It will greatly increase productivity

![image](https://user-images.githubusercontent.com/11240668/114490969-5dc98b80-9c48-11eb-8b65-53eaceb5cec1.png)

**Comment by p0deje** [comment]
Sorry, but I don't think it's possible using NSMenu and I don't plan to rework this with a custom view representation.

**Comment by p0deje** [comment]
Actually, please follow #229 as it seems like I've found a way to implement something similar.
