### ISSUE TITLE
Does not work good with auto hide menubar

### ISSUE THREAD

**Issue by kmplngj** [p0deje/Maccy#278]
Hello,

I set my menu bar to auto hide in the macOS settings.

If I click on the app and then select something in the menu with the mouse, macOS hides the menu bar again and the selection in the app no longer fits. Can this be fixed?

The standard behavior of Apple's own menu extras is that the menu bar is not hidden as long as the extra is open.

Thanks Jan

**Comment by p0deje** [comment]
You can work it around by checking "Avoid taking application focus" in the "Advanced" section of preferences, but other than that, there is not much we can do about it.

**Comment by p0deje** [comment]
Just to clarify, it might be possible to hack around and somehow make it work, but I don't have time/energy to invest into this as there is no obvious solution.
