### ISSUE TITLE
Feature Request - Allow setting the hotkey for a pinned entry 

### ISSUE THREAD

**Issue by fancygits** [p0deje/Maccy#279]
I use pins extensively in Maccy. Occasionally, I need to update something that was previously pinned. So I paste it, change it, copy it, then pin the updated clip. But when I do that, I have to pin/unpin dozens of times until I randomly get the same hotkey that I was used to.

I'm requesting a feature to specify the hotkey used for an individual pin.
![image](https://user-images.githubusercontent.com/29738198/116264625-0fd07f80-a740-11eb-80d8-709ecab2c535.png)

This might be related to https://github.com/p0deje/Maccy/issues/89

And is not related to https://github.com/p0deje/Maccy/issues/169. I don't need to change Option+P.

**Comment by drwb** [comment]
Customising the hotkey for pinned entries (not just re-pinned entries) would be very useful as I have obvious keys in my head for my pins ('c' for my cal link etc.) which I have to, as fancygits, un- and re-pin until I get.

**Comment by p0deje** [comment]
This will be available in the preferences section in the next release.
