### ISSUE TITLE
Randomly stops saving copied items

### ISSUE THREAD

**Issue by philihub** [p0deje/Maccy#280]
I cannot replicate this reliably but I feel it has something to do with the sleep/hibernation. Screenshot shows my clipboard and Maccy’s last saved entries.
[maccy.pdf](https://github.com/p0deje/Maccy/files/6445490/maccy.pdf)

**Comment by philihub** [comment]
`standard	11:58:07.216584+0200	runningboardd	Acquiring assertion targeting [app<application.org.p0deje.Maccy.103825051.103825057(501)>:3301] from originator [daemon<com.apple.coreservices.launchservicesd>:107] with description <RBSAssertionDescriptor| "frontmost:3301" ID:157-107-39576 target:3301 attributes:[
	<RBSDomainAttribute| domain:"com.apple.launchservicesd" name:"RoleUserInteractiveFocal" sourceEnvironment:"(null)">
	]>
standard	11:58:07.215122+0200	Maccy	SetFrontProcess: asn=0x0-0x38038 options=1
standard	11:58:07.216902+0200	runningboardd	Assertion 157-107-39576 (target:[app<application.org.p0deje.Maccy.103825051.103825057(501)>:3301]) will be created as active
standard	11:58:07.223896+0200	runningboardd	[app<application.org.p0deje.Maccy.103825051.103825057(501)>:3301] Ignoring jetsam update because this process is not memory-managed
standard	11:58:07.223979+0200	runningboardd	[app<application.org.p0deje.Maccy.103825051.103825057(501)>:3301] Ignoring suspend because this process is not lifecycle managed
standard	11:58:07.219615+0200	runningboardd	Calculated state for app<application.org.p0deje.Maccy.103825051.103825057(501)>: running-active (role: UserInteractiveFocal)
standard	11:58:07.228972+0200	NowPlayingTouchUI	[NowPlayingTouchUI] Reloading available apps due to workspace activating an application: NSConcreteNotification 0x600000b17ae0 {name = NSWorkspaceDidActivateApplicationNotification; object = <NSWorkspace: 0x600000778140>; userInfo = {
    NSWorkspaceApplicationKey = "<NSRunningApplication: 0x600002b70600 (org.p0deje.Maccy - 3301) LSASN:{hi=0x0;lo=0x38038}>";
}}
standard	11:58:07.224080+0200	runningboardd	[app<application.org.p0deje.Maccy.103825051.103825057(501)>:3301] Set darwin role to: UserInteractiveFocal
standard	11:58:07.229819+0200	runningboardd	[app<application.org.p0deje.Maccy.103825051.103825057(501)>:3301] Ignoring GPU update because this process is not GPU managed
standard	11:58:07.234507+0200	runningboardd	[app<application.org.p0deje.Maccy.103825051.103825057(501)>:3301] Skipping AppNap state - not lifecycle managed
standard	11:58:07.238080+0200	runningboardd	Finished acquiring assertion 157-107-39576 (target:[app<application.org.p0deje.Maccy.103825051.103825057(501)>:3301])
standard	11:58:07.241138+0200	runningboardd	Acquiring assertion targeting [app<application.org.p0deje.Maccy.103825051.103825057(501)>:3301] from originator [daemon<com.apple.coreservices.launchservicesd>:107] with description <RBSAssertionDescriptor| "notification:3301" ID:157-107-39578 target:3301 attributes:[
	<RBSDomainAttribute| domain:"com.apple.launchservicesd" name:"LSNotification" sourceEnvironment:"(null)">
	]>
standard	11:58:07.241301+0200	runningboardd	Assertion 157-107-39578 (target:[app<application.org.p0deje.Maccy.103825051.103825057(501)>:3301]) will be created as active
standard	11:58:07.242717+0200	runningboardd	Finished acquiring assertion 157-107-39578 (target:[app<application.org.p0deje.Maccy.103825051.103825057(501)>:3301])
standard	11:58:07.242768+0200	runningboardd	[app<application.org.p0deje.Maccy.103825051.103825057(501)>:3301] Ignoring jetsam update because this process is not memory-managed
standard	11:58:07.242964+0200	runningboardd	[app<application.org.p0deje.Maccy.103825051.103825057(501)>:3301] Ignoring suspend because this process is not lifecycle managed
standard	11:58:07.243740+0200	runningboardd	[app<application.org.p0deje.Maccy.103825051.103825057(501)>:3301] Ignoring GPU update because this process is not GPU managed
standard	11:58:07.244021+0200	runningboardd	[app<application.org.p0deje.Maccy.103825051.103825057(501)>:3301] Skipping AppNap state - not lifecycle managed
standard	11:58:07.243259+0200	runningboardd	Calculated state for app<application.org.p0deje.Maccy.103825051.103825057(501)>: running-active (role: UserInteractiveFocal)
standard	11:58:07.319237+0200	runningboardd	Acquiring assertion targeting [app<application.org.p0deje.Maccy.103825051.103825057(501)>:3301] from originator [daemon<com.apple.WindowServer(88)>:142] with description <RBSAssertionDescriptor| "FUSBProcessWindowState: occluded" ID:157-142-39579 target:3301 attributes:[
	<RBSDomainAttribute| domain:"com.apple.fuseboard" name:"Occluded" sourceEnvironment:"(null)">,
	<RBSAcquisitionCompletionAttribute| policy:AfterApplication>
	]>
standard	11:58:07.319384+0200	runningboardd	Assertion 157-142-39579 (target:[app<application.org.p0deje.Maccy.103825051.103825057(501)>:3301]) will be created as active
standard	11:58:07.320226+0200	runningboardd	Calculated state for app<application.org.p0deje.Maccy.103825051.103825057(501)>: running-active (role: UserInteractiveFocal)
standard	11:58:07.320239+0200	runningboardd	[app<application.org.p0deje.Maccy.103825051.103825057(501)>:3301] Ignoring jetsam update because this process is not memory-managed
standard	11:58:07.320296+0200	runningboardd	[app<application.org.p0deje.Maccy.103825051.103825057(501)>:3301] Ignoring suspend because this process is not lifecycle managed
standard	11:58:07.320399+0200	runningboardd	[app<application.org.p0deje.Maccy.103825051.103825057(501)>:3301] Ignoring GPU update because this process is not GPU managed
standard	11:58:07.321048+0200	runningboardd	[app<application.org.p0deje.Maccy.103825051.103825057(501)>:3301] Skipping AppNap state - not lifecycle managed
standard	11:58:07.321368+0200	runningboardd	Finished acquiring assertion 157-142-39579 (target:[app<application.org.p0deje.Maccy.103825051.103825057(501)>:3301])
standard	11:58:07.347124+0200	runningboardd	Acquiring assertion targeting [app<application.org.p0deje.Maccy.103825051.103825057(501)>:3301] from originator [daemon<com.apple.WindowServer(88)>:142] with description <RBSAssertionDescriptor| "FUSBProcessWindowState: visible" ID:157-142-39580 target:3301 attributes:[
	<RBSDomainAttribute| domain:"com.apple.fuseboard" name:"Visible" sourceEnvironment:"(null)">,
	<RBSAcquisitionCompletionAttribute| policy:AfterApplication>
	]>
standard	11:58:07.347321+0200	runningboardd	Assertion 157-142-39580 (target:[app<application.org.p0deje.Maccy.103825051.103825057(501)>:3301]) will be created as active
standard	11:58:07.348510+0200	runningboardd	[app<application.org.p0deje.Maccy.103825051.103825057(501)>:3301] Ignoring jetsam update because this process is not memory-managed
standard	11:58:07.348412+0200	runningboardd	Calculated state for app<application.org.p0deje.Maccy.103825051.103825057(501)>: running-active (role: UserInteractiveFocal)
standard	11:58:07.348634+0200	runningboardd	[app<application.org.p0deje.Maccy.103825051.103825057(501)>:3301] Ignoring suspend because this process is not lifecycle managed
standard	11:58:07.349071+0200	runningboardd	[app<application.org.p0deje.Maccy.103825051.103825057(501)>:3301] Ignoring GPU update because this process is not GPU managed
standard	11:58:07.349394+0200	runningboardd	[app<application.org.p0deje.Maccy.103825051.103825057(501)>:3301] Skipping AppNap state - not lifecycle managed
standard	11:58:07.349967+0200	runningboardd	Finished acquiring assertion 157-142-39580 (target:[app<application.org.p0deje.Maccy.103825051.103825057(501)>:3301])
standard	11:58:07.350506+0200	runningboardd	Invalidating assertion 157-142-39579 (target:[app<application.org.p0deje.Maccy.103825051.103825057(501)>:3301]) from originator [daemon<com.apple.WindowServer(88)>:142]
standard	11:58:07.458694+0200	runningboardd	Calculated state for app<application.org.p0deje.Maccy.103825051.103825057(501)>: running-active (role: UserInteractiveFocal)
standard	11:58:07.458863+0200	runningboardd	[app<application.org.p0deje.Maccy.103825051.103825057(501)>:3301] Ignoring jetsam update because this process is not memory-managed
standard	11:58:07.459042+0200	runningboardd	[app<application.org.p0deje.Maccy.103825051.103825057(501)>:3301] Ignoring suspend because this process is not lifecycle managed
standard	11:58:07.459117+0200	runningboardd	[app<application.org.p0deje.Maccy.103825051.103825057(501)>:3301] Ignoring GPU update because this process is not GPU managed
standard	11:58:07.459378+0200	runningboardd	[app<application.org.p0deje.Maccy.103825051.103825057(501)>:3301] Skipping AppNap state - not lifecycle managed
standard	11:58:08.882643+0200	runningboardd	Invalidating assertion 157-142-39580 (target:[app<application.org.p0deje.Maccy.103825051.103825057(501)>:3301]) from originator [daemon<com.apple.WindowServer(88)>:142]
standard	11:58:08.893687+0200	runningboardd	Invalidating assertion 157-107-39576 (target:[app<application.org.p0deje.Maccy.103825051.103825057(501)>:3301]) from originator [daemon<com.apple.coreservices.launchservicesd>:107]
standard	11:58:08.991396+0200	runningboardd	Removed last relative-start-date-defining assertion for process app<application.org.p0deje.Maccy.103825051.103825057(501)>
standard	11:58:09.007432+0200	runningboardd	[app<application.org.p0deje.Maccy.103825051.103825057(501)>:3301] Ignoring jetsam update because this process is not memory-managed
standard	11:58:09.007369+0200	runningboardd	Calculated state for app<application.org.p0deje.Maccy.103825051.103825057(501)>: running-active (role: UserInteractive)
standard	11:58:09.007582+0200	runningboardd	[app<application.org.p0deje.Maccy.103825051.103825057(501)>:3301] Ignoring suspend because this process is not lifecycle managed
standard	11:58:09.007761+0200	runningboardd	[app<application.org.p0deje.Maccy.103825051.103825057(501)>:3301] Set darwin role to: UserInteractive
standard	11:58:09.007971+0200	runningboardd	[app<application.org.p0deje.Maccy.103825051.103825057(501)>:3301] Ignoring GPU update because this process is not GPU managed
standard	11:58:09.008300+0200	runningboardd	[app<application.org.p0deje.Maccy.103825051.103825057(501)>:3301] Skipping AppNap state - not lifecycle managed
standard	11:58:12.241992+0200	runningboardd	Assertion did invalidate due to timeout: 157-107-39578 (target:[app<application.org.p0deje.Maccy.103825051.103825057(501)>:3301])
standard	11:58:12.450295+0200	runningboardd	Calculated state for app<application.org.p0deje.Maccy.103825051.103825057(501)>: running-active (role: UserInteractive)
standard	11:58:12.450294+0200	runningboardd	[app<application.org.p0deje.Maccy.103825051.103825057(501)>:3301] Ignoring jetsam update because this process is not memory-managed
standard	11:58:12.450386+0200	runningboardd	[app<application.org.p0deje.Maccy.103825051.103825057(501)>:3301] Ignoring suspend because this process is not lifecycle managed
standard	11:58:12.450472+0200	runningboardd	[app<application.org.p0deje.Maccy.103825051.103825057(501)>:3301] Ignoring GPU update because this process is not GPU managed
standard	11:58:12.450571+0200	runningboardd	[app<application.org.p0deje.Maccy.103825051.103825057(501)>:3301] Skipping AppNap state - not lifecycle managed
`

**Comment by philihub** [comment]
Does this help? I was the first time it happed again: Maccy did not save from clipboard. In this case copying something out of the Edge Browser. Latest everything macOS and Edge version.

**Comment by philihub** [comment]
The problem is persisting and still hard to pinpoint/replicate. Any betas I could test?

**Comment by p0deje** [comment]
Sorry, I was distracted from Maccy for a while. I can't see anything suspicious in your logs. I've tried sleep/wake with Maccy running - I had no problems and I also see the same messages in Console.app. Puzzling as we need more data to investigate.

Why are convinced it's related to sleep/hibernate? 

One random idea I have is that we currently check for new copies using a timer. Maybe this timer is somehow deinitilized during sleep. I can't seem to find anything on that behavior, but it might probably happen. To confirm that timer stopped working, we can try the following:

1. When everything is okay, can you run the following command in Terminal.app, note the number it prints, then copy something, wait a second and run again. The number should increase by 1.

```
sqlite3 ~/Library/Containers/org.p0deje.Maccy/Data/Library/Application\ Support/Maccy/Storage.sqlite "select count(*) from zhistoryitem;"
```

2. Do the same when Maccy stops saving copied items. If the number is not increased - it's the issue with timer and/or storage. If it's still increased but new items are not visible in Maccy UI - it's the UI issue.

**Comment by p0deje** [comment]
Can you please try 0.21 and re-open this issue if it happens again. Thanks!
