### ISSUE TITLE
Add preference for setting tooltip delay

### ISSUE THREAD

**Issue by drmikeh** [p0deje/Maccy#282]
Add a preference setting for speeding up or slowing down the tooltip delay. Currently it seems to be about 2 seconds but I would prefer it to be much faster.

**Comment by p0deje** [comment]
Tooltips are shown by macOS and I can't find a way to change the default delay. Some recommendations about changing defaults `NSInitialToolTipDelay` to lower value have no effect. I'll implement if I find a way to do so.

To get better understanding, what is the reason to change delay?

**Comment by andylima** [comment]
Came here for the same feature request. 😉

Could the history item tooltip timeout be configurable? I'd like these to show up faster when I'm checking out the history items contents… — I have many items with multiple lines and check these tooltips a lot.

Alternatively, maybe a list view like CopyLess 2 has? That would be a dream. 🤩

**Comment by p0deje** [comment]
Related to #267

**Comment by andylima** [comment]
Thanks for letting us know, @p0deje — I put together some thoughts on #267 👍

**Comment by p0deje** [comment]
In the upcoming version of Maccy, there will be a "rich" preview which would show multiline text and images in higher resolution. It will also be possible to change delay until the first preview is shown (default 1.5 seconds). If you'd like to disable the preview delay, simply set a long enough value in preferences (e.g. 60,000 ms). Here are some examples of the new preview:

<img width="1209" alt="Screenshot 2023-01-30 at 10 36 28" src="https://user-images.githubusercontent.com/665846/215565394-1f60c5de-9e65-4cea-91b2-64c76fbf6dfc.png">
<img width="1027" alt="Screenshot 2023-01-30 at 10 35 40" src="https://user-images.githubusercontent.com/665846/215565405-f8dcdcb3-5802-4bdd-9316-78ee4953fdaf.png">
