### ISSUE TITLE
A Few Contribution Ideas

### ISSUE THREAD

**Issue by JosephTLyons** [p0deje/Maccy#283]
First off, just wanted to say that Maccy has been my favorite clipboard manager so far.  Really digging it.  A few features I would probably enjoy in Maccy are:

1. AppIcons of the app that the copied text came from.  I saw this done in [Unclutter](https://unclutterapp.com)'s clipboard manager and find it to be pretty useful for visual grepping through the various pieces.  I don't know what your stance on this is.  I assume adding a tiny appicon to the left of the list could potentially slow Maccy down a bit, but if it were done using references to the same app icon when multiple texts were copied, and caching those, versus a new image for each history item, then I think it could be fine, but I don't know enough about it without actually doing the work.

2. The ability to export and import user settings via some json files.  This way, we could source control them and sync them between computers via GitHub.

3. Some sort of optional naming system.  A way to give snippets a name.  If the snippet has a name, it is displayed in the list, if it doesn't have a name, it defaults to showing the copied contents (like it does now).  This could be useful for when you have multiple pinned items that look similar (like IP addresses, etc).  I don't really know how this would work with searching, if it would search on names and also the copied content?  Not sure.

I don't have much experience in Swift development, but I'd be interested to look into either of these things if there were something that you'd be interested in.  If they aren't things you would want in Maccy, I may try work on them anyway and just keep them in my own personal fork of Maccy.  Admittedly, I've been wanting to get into Swift development for years and Maccy seems like the perfect project for me to learn from.

**Comment by JosephTLyons** [comment]
Unclutter's Clipboard Manager:

![clipboard-panel@2x](https://user-images.githubusercontent.com/19867440/118738034-0f457900-b814-11eb-99f0-a583e2318651.jpg)

**Comment by p0deje** [comment]
Thanks for feedback, please see my comment below

> AppIcons of the app that the copied text came from. I saw this done in Unclutter's clipboard manager and find it to be pretty useful for visual grepping through the various pieces. I don't know what your stance on this is. I assume adding a tiny appicon to the left of the list could potentially slow Maccy down a bit, but if it were done using references to the same app icon when multiple texts were copied, and caching those, versus a new image for each history item, then I think it could be fine, but I don't know enough about it without actually doing the work.

Maccy doesn't track what application was the source of copied data. In fact, macOS provides no such API and there seems to be no bullet-proof solution to determine where the copied data is coming from. There are workarounds, but I'm reluctant to add support for something that is known to have bugs. Moving on, showing AppIcons depend on this and is not possible at the moment. I am also now sure how UI is going to look like. Unclutter has complete custom interface while Maccy uses macOS menus for UI.

> The ability to export and import user settings via some json files. This way, we could source control them and sync them between computers via GitHub.

You can already source control preferences as they are stored as `plist` file in `~/Library/Containers/org.p0deje.Maccy/Data/Library/Application\ Support/Maccy/org.p0deje.Maccy.plist`. What is the need to export/import settings manually?

> Some sort of optional naming system. A way to give snippets a name. If the snippet has a name, it is displayed in the list, if it doesn't have a name, it defaults to showing the copied contents (like it does now). This could be useful for when you have multiple pinned items that look similar (like IP addresses, etc). I don't really know how this would work with searching, if it would search on names and also the copied content? Not sure.

This has been repeatedly asked and I would like to add such a feature, but I'm not sure yet how theses names (aliases) are going to be managed. How would you add a name to existing copy? How would you change or remove it? I'd like to make UX as seamless as possible. Would you only use that on pinned items or regular too?

**Comment by JosephTLyons** [comment]
> Maccy doesn't track what application was the source of copied data. In fact, macOS provides no such API and there seems to be no bullet-proof solution to determine where the copied data is coming from. There are workarounds, but I'm reluctant to add support for something that is known to have bugs. Moving on, showing AppIcons depend on this and is not possible at the moment. I am also now sure how UI is going to look like. Unclutter has complete custom interface while Maccy uses macOS menus for UI.

Yeah, I ended up looking through heaps of docs and doing a bunch of Google searches and sort of found out that this sort of behavior isn't supported directly.  It must be some super custom code for Unclutter.

> You can already source control preferences as they are stored as plist file in ~/Library/Containers/org.p0deje.Maccy/Data/Library/Application\ Support/Maccy/org.p0deje.Maccy.plist. What is the need to export/import settings manually?

I didn't consider this at all, so I suppose there is no need for an import/export settings feature.

> This has been repeatedly asked and I would like to add such a feature, but I'm not sure yet how theses names (aliases) are going to be managed. How would you add a name to existing copy? How would you change or remove it? I'd like to make UX as seamless as possible. Would you only use that on pinned items or regular too?

It seems like it would mostly be used for pin items.  I can't think of a reason why I might name another snippet.  As for how it would work in the UI, I'm not sure.  I assume some other sort of key combo (same as the pinning and deleting), but not sure what entering in the snippet name might look like.

**Comment by JosephTLyons** [comment]
Another thing I thought may be useful is a setting to determine the length of the text shown.  I think it is the `showMaxLength` variable, which is currently set to `50`.  A user with a larger screen may be able to use `75` or `100`.  I'm not sure how a setting like this might work, whether it would give full control to the user to input anything greater than some number or just have 3-4 preset values.

**Comment by JosephTLyons** [comment]
> You can already source control preferences as they are stored as plist file in ~/Library/Containers/org.p0deje.Maccy/Data/Library/Application\ Support/Maccy/org.p0deje.Maccy.plist. What is the need to export/import settings manually?

Also, I navigated to this directory and didn't see any `.plist` file

<img width="764" alt="CleanShot 2021-05-22 at 14 56 27@2x" src="https://user-images.githubusercontent.com/19867440/119238001-e7a12a00-bb0d-11eb-9c1a-4987e7fee843.png">

**Comment by georgesnow** [comment]
You can use 
`defaults export …`

and 

`defaults import …`

For plist settings

**Comment by p0deje** [comment]
@JosephTLyons Hm, maybe it's the wrong location. Can you you check `~/Library/Containers/org.p0deje.Maccy/Data/Library/Preferences/`?

**Comment by JosephTLyons** [comment]
Yep, seems to be in there.  They seem to be in some compressed / binary form, which makes it pretty awkward to source control, as you can't see the contents that have been changed in the diff really - any tips to make source controlling plist files?

**Comment by p0deje** [comment]
GitHub already shows plist files as XML and locally you can also configure tooling to do so. Quick googling revealed https://confusatory.org/post/133141617492/git-diff-for-binary-apple-property-list-files

Thank you,
Alex
