### ISSUE TITLE
Replace \n with ⏎

### ISSUE THREAD

**Issue by mustafa0x** [p0deje/Maccy#285]
Hi, wonderful tool, thanks.

In the list \n should be replaced with ⏎ instead of simply removing \n.

**Comment by p0deje** [comment]
@mustafa0x Can you give an example when it should be? I don't fully understand.

**Comment by mustafa0x** [comment]
Is now:
![before](https://user-images.githubusercontent.com/1473102/121699615-f41d0080-ca83-11eb-96b7-d1bb0c7c5471.png)

Should be:
![after](https://user-images.githubusercontent.com/1473102/121699603-f1221000-ca83-11eb-82b7-b214cf64d5e8.png)

**Comment by kidonng** [comment]
@p0deje I think the idea is that, right now line breaks are invisible in the clipboard menu. There should be some kind of replacement character to make them visible and we can easily distinguish different lines.

**Comment by JosephTLyons** [comment]
I agree.  I think being able to see newline characters here would be a huge benefit.

**Comment by JosephTLyons** [comment]
Awesome! Thank you.
