### ISSUE TITLE
Feature Request: Option to Show Multi Line Text

### ISSUE THREAD

**Issue by karlhorky** [p0deje/Maccy#286]
Hi @p0deje! First of all, not sure if I've mentioned this yet, but thanks so much for this - really amazing to have an open source clipboard manager with such high quality!

I've been using a bunch of different clipboard managers for years now, and although Maccy was one of my favorites, one of the biggest problems using it came from this workflow:

1. Copy a piece of code once
2. Realize you missed a piece further down, copy again
3. Copy something else / get distracted for a second
4. Come back to the previous paste that you wanted to do, and try to figure out which one was the correct one - the very short preview text is not long enough to see which is the correct one

I know there's the possibility of hovering and waiting for the tooltip, but this is pretty hard to use.

This makes it really tough to figure out which clipboard history entry was the correct one.

What do you think about showing an alternative UI for users who would want to see multiple text lines in each item of their clipboard history? I guess it's a bit different than Maccy's current very minimal UI, but the minimalism is a bit too far-reaching in some circumstances...

I have recently been trying out [Yippy](https://yippy.mattdavo.com/), and that's one of the things that I think that it does really well.

**Comment by p0deje** [comment]
It is definitely possible to show multiline text, but I feel like it's hard to comprehend the history list when you don't have fixed-height items. 

<img width="818" alt="Screen Shot 2021-06-22 at 19 43 09" src="https://user-images.githubusercontent.com/665846/123027081-14a55e80-d392-11eb-8764-e81fd57824d3.png">


Also, it would allow copying a really huge chunk of text that can take the whole screen height so you would only see a single item.

<img width="881" alt="Screen Shot 2021-06-22 at 19 44 51" src="https://user-images.githubusercontent.com/665846/123027252-5f26db00-d392-11eb-9cbd-4acc22913ea3.png">

**Comment by karlhorky** [comment]
Maybe clipped at a certain number of lines?

**Comment by p0deje** [comment]
I don't know. What would be the arbitrary value? There might be a need to sometimes show a longer text because we can still see 2 exact items if we clip them.

Frankly, I cannot see myself using this at all. If I accidentally copy something wrong, then realize that it is missing something and copy a fixed version, I'd just search for some part of the copied text and select the top one - this would be the correct version. This way I don't need to spend time reading through the item's text or tooltips.

**Comment by p0deje** [comment]
I guess the issue will be solved if there are better tooltips with customizable delay. Let me close this in favor of #282 and #267. If you disagree, please comment and I'll re-open the issue.

**Comment by karlhorky** [comment]
So it's not quite the same (comparing two values is much easier when both of them are visible at the same time), but if multi-line display doesn't match the philosophy of Maccy, I understand that you don't want to re-open.
