### ISSUE TITLE
Enhancement: Upgrade Sparkle XPC framework to support Apple Silicon

### ISSUE THREAD

**Issue by hguandl** [p0deje/Maccy#288]
Maccy is quite nice and I use it every day. Recently I switched to an M1 Mac and noticed that the updater Sparkle does not support Apple Silicon.

This can be fixed by upgrading Sparkle. Currently, Sparkle 2.0 only provides nightly builds in [GitHub Actions](https://github.com/sparkle-project/Sparkle/actions?query=branch%3A2.x+is%3Asuccess++). We can download the artifact and use the new `Sparkle.framework` and `.xpc` in XPCServices.

**Comment by p0deje** [comment]
How did you notice that Sparkle doesn't support M1? I remember upgrading it specifically for this reason - e0ffd033c989ee7f723638fc58a17d4fef10642c.

**Comment by hguandl** [comment]
I found it in the activity monitor. 

<img width="770" alt="截屏2021-06-22 21 05 19" src="https://user-images.githubusercontent.com/10684225/122929765-e463bd00-d39d-11eb-8cb8-b8d05311aa56.png">

Sparkle uses XPC services to become functional in sandboxed app. Therefore the `org.sparkle-project.*.xpc` in <https://github.com/p0deje/Maccy/tree/master/Sparkle> should also be upgraded to support Apple Silicon.

**Comment by p0deje** [comment]
I don't have M1 Mac so I'm not sure how to confirm it's working, but can you please try running this build which includes the 
latest Sparkle 2.x and XPC services?

[Maccy.app.zip](https://github.com/p0deje/Maccy/files/6698010/Maccy.app.zip)

**Comment by hguandl** [comment]
<img width="840" alt="截屏2021-06-23 10 43 59" src="https://user-images.githubusercontent.com/10684225/123027208-09911380-d410-11eb-85b1-2769b140bcdd.png">

Yes, activity monitor says they are using Apple architecture now. Thanks!

**Comment by p0deje** [comment]
Thanks!

**Comment by AJAYK-01** [comment]
> I don't have M1 Mac so I'm not sure how to confirm it's working, but can you please try running this build which includes the
> latest Sparkle 2.x and XPC services?
> 
> [Maccy.app.zip](https://github.com/p0deje/Maccy/files/6698010/Maccy.app.zip)

Thanks for the M1 build mate!

**Comment by p0deje** [comment]
You don't need to use that build, the latest version support M1 fully.
