### ISSUE TITLE
Highlight matched substrings

### ISSUE THREAD

**Issue by kidonng** [p0deje/Maccy#289]
It would be nice to highlight matched substrings, like search engines:

![image](https://user-images.githubusercontent.com/44045911/122677708-0c281900-d216-11eb-92e6-5beca84e5dd1.png)

Or [tmux-fzf-maccy](https://github.com/junegunn/tmux-fzf-maccy):

![image](https://user-images.githubusercontent.com/44045911/122677647-c703e700-d215-11eb-8831-4956f3be20f6.png)

(Speaking of fzf, the current fuzzy search package [Fuse](https://github.com/krisk/fuse-swift) isn't updated for over a year and IMO not very good... would you like to consider some alternatives, like this [FuzzyFind](https://github.com/truizlop/FuzzyFind)?)

**Comment by p0deje** [comment]
I'll see how to highlight text in NSMenuItem and if it is going to impact performance somehow. As for FuzzyFind, I'm open to the switch but I don't see a reason yet. I know it's outdated, but it works fine.

**Comment by kidonng** [comment]
> I'll see how to highlight text in NSMenuItem and if it is going to impact performance somehow.

That would be much appreciated.

> As for FuzzyFind, I'm open to the switch but I don't see a reason yet. I know it's outdated, but it works fine.

I *really* wish it can do better. The following issue happens regularly:

<img width="496" alt="Screen Shot 2021-06-24 at 01 49 55" src="https://user-images.githubusercontent.com/44045911/123146602-a6939100-d490-11eb-9cca-f4f36fae47c6.png">
<img width="489" alt="Screen Shot 2021-06-24 at 01 50 03" src="https://user-images.githubusercontent.com/44045911/123146607-a85d5480-d490-11eb-964e-25fdee007afc.png">

v.s. searching the maccy database with fzf:

![image](https://user-images.githubusercontent.com/44045911/123147067-2faac800-d491-11eb-9901-7e2dd9f1b665.png)

If you would like to address the problem we can open a new issue.

**Comment by p0deje** [comment]
Would highlighting by bold be good?
<img width="532" alt="Screen Shot 2021-06-23 at 17 29 18" src="https://user-images.githubusercontent.com/665846/123184491-a7a0d000-d448-11eb-862b-c03e0ed35b60.png">

**Comment by kidonng** [comment]
> Would highlighting by bold be good?

Much appreciated!

> I have to say it doesn't look so well with fuzzy search because it highlights way more characters:

That would be a good reason to improve the fuzzy search :)

Jokes aside, maybe we can also make the matches red. Or make unmatched texts gray. But the current state looks just fine, as far as I can say.

**Comment by kidonng** [comment]
Thank you ✨
