### ISSUE TITLE
[README] Update process looks scary

### ISSUE THREAD

**Issue by DaFuqtor** [p0deje/Maccy#29]
[This thing](//github.com/p0deje/Maccy#update) may really scare any user:
> ```sh
> brew update
> brew cask upgrade maccy
> killall Maccy # closes the app if it is running
> open /Applications/Maccy.app # opens the new version
> ```

I think it would be better to add
```rb
uninstall quit: 'org.p0deje.Maccy'
```
to the [`maccy.rb`](//github.com/Homebrew/homebrew-cask/blob/master/Casks/maccy.rb) Cask.

And shorten ["Update"](//github.com/p0deje/Maccy#update) to
```sh
brew cask upgrade maccy
open -a maccy
```

**Comment by DaFuqtor** [comment]
Hah, now I've tested it and it doesn't work that way because `uninstalling` is not the same as `updating`.

**Comment by saeedseyfi** [comment]
@p0deje `open -a maccy` doesn't work. please revert the doc update.

**Comment by DaFuqtor** [comment]
@saeedseyfi works on macOS<sup>10.15</sup> Catalina
![Kapture 2019-10-28 at 13 19 52](https://user-images.githubusercontent.com/46137336/67670821-c9049c80-f985-11e9-9f70-77994364ed07.gif)

**Comment by saeedseyfi** [comment]
> @saeedseyfi works on macOS10.15 Catalina
> ![Kapture 2019-10-28 at 13 19 52](https://user-images.githubusercontent.com/46137336/67670821-c9049c80-f985-11e9-9f70-77994364ed07.gif)

did you ever try it after an update?

**Comment by DaFuqtor** [comment]
@saeedseyfi this gif was recorded on macOS Catalina

**Comment by saeedseyfi** [comment]
> @saeedseyfi this gif was recorded on macOS Catalina

this this not a matter of os version, I use catalina as well.

to run the new version of maccy, you need to close the running app first before opening it again.
if you run `open` without `kill`ing the already running app, it DOESN'T DO ANYTHING.
in the gif you sent you already closed the app manually.
that is what you missed.

I know `open -a Maccy` opens it, fine I'm ok with keeping that, but it doesn't close it if it's running, this is the missed part.

that is why you need this step first:
```
killall Maccy # closes the app if it is running
```
and I suggest to bring this step back.

**Comment by DaFuqtor** [comment]
Yea, that's what I wrote 3 days ago:
> Hah, now I've tested it and it doesn't work that way because uninstalling is not the same as updating. So we still need to close the app and open a new version."

^_^
