### ISSUE TITLE
Feature request: Drag and Drop

### ISSUE THREAD

**Issue by nevara** [p0deje/Maccy#290]
Enabling drag and drop would be quite useful, especially for images. 
It would be also more in line with standard macOS behaviour (you can almost drag and drop anything)

**Comment by kidonng** [comment]
> It would be also more in line with standard macOS behaviour (you can almost drag and drop anything)

Just asking, how do you (think the user can) drag a menu item?

**Comment by georgesnow** [comment]
Menu bar (or status bar items) support drag and drop actions. Theoretically dragging an image onto the icon would add it to the list.

**Comment by kidonng** [comment]
> Theoretically dragging an image onto the icon would add it to the list.

That would be fun but not useful, IMO. Plus Maccy is solely a clipboard manager and nothing else. There are already many apps do what you described like Yoink.

**Comment by p0deje** [comment]
Would you drag to Maccy or from it? If the former, I don't think it's more convenient than just copying the image. If the latter, then it's very hard or impossible to implement drag&drop of menu items.

**Comment by p0deje** [comment]
I've searched a bit how this can be done and it seems to discouraged to try implementing drag&drop for NSMenuItem - https://lists.apple.com/archives/cocoa-dev/2010/Feb/msg00703.html. Closing as I don't have capacity to work on this, but PRs are of course welcome.
