### ISSUE TITLE
Ignore image copies over a certain file size

### ISSUE THREAD

**Issue by iparr** [p0deje/Maccy#291]
I've read #134 and it's great to be able to turn off images.

However, would it be possible to be more selective based on the size of the image?

My work flow is this:
- Use [Sketch](https://www.sketch.com/) to design websites
- Drag in client-supplied high-quality photographs (10+ MB jpgs)
- Cut and paste these into different parts of the design within Sketch.
- When I do this a few times, Maccy slows down to the extent that it takes minutes to open

I'd like it to ignore images of a certain size, but still remember other images (such as bits of the UI I am designing)

Thanks. Great app overall.

**Comment by p0deje** [comment]
I think it would be better if Maccy just handles big images correctly. I've tried copying 15MB image and Maccy took a couple of seconds to open if I immediately press the hotkey. However, if I open few seconds later - it opens without any slowdown. Then I can pin/search items the usual way. 

It seems fine copying 1 huge image. Can you be more specific about the steps you do when the issue happens? How many images do you copy? What are their sizes? How soon do you open Maccy?

**Comment by p0deje** [comment]
Closing since no reply for more than a month. Feel free to re-open and provide more info.
