### ISSUE TITLE
No item is getting pasted from Maccy

### ISSUE THREAD

**Issue by hussein** [p0deje/Maccy#293]
Hello,

I have iMac M1 and got the Maccy App. Maccy seems unable to paste a text that I copied earlier. Command + Shift + C shows a list of item but when selecting one, nothing is happening and no text is being pasted. I tried that with different applications.

I am using Maccy 0.20.1 running on iMac M1. Let me know how I can help.

Thanks.

**Comment by p0deje** [comment]
You have to enable "Paste automatically" in preferences first.
