### ISSUE TITLE
Adding & Deleting Pins. - Inconsistent Functionality 

### ISSUE THREAD

**Issue by JohnGenest** [p0deje/Maccy#298]
Editing pinned items (Adding and deleting) often doesn't work.  Closing and restarting the app's an ineffective resolution.  Thank you in advance!

**Comment by p0deje** [comment]
Please provide more details on what exactly do you see not working. There are also some fixes in that will be available in the next version.

**Comment by JohnGenest** [comment]
Hi!  The feature will stop working - meaning the subsequent actions can't be taken
1) Removing a pin from the pinned list (Can incur this issue whether pinned list is full or not)
2) Adding a pin to the pinned list

Troubleshooting: 
- Restarting app seems to be increasingly ineffective as an immediate and definitive resolution
- I haven't identified any recurring usage/workflow scenarios that potentially trigger 
- Have experienced the issue on two different Macs.  

Please let me know if I can provide any additional insight.  Thank you!

**Comment by p0deje** [comment]
It should work more reliably in the upcoming version, stay tuned.

**Comment by JohnGenest** [comment]
Awesome.  Maccy is one of my essential tools!  Thank you!

**Comment by p0deje** [comment]
Can you please try 0.21 and re-open this issue if it happens again? Thanks!

**Comment by JohnGenest** [comment]
Hi - I'm still having issues on both computers.  If I stick with the Apple App Store version, should I troubleshoot by deleting and downloading again?  Just want to confirm direction since I'm not sure what happens to all my pinned content by deleting. Thanks!
