### ISSUE TITLE
Copy image erases text clipboard entries

### ISSUE THREAD

**Issue by DanielSmith** [p0deje/Maccy#30]
1.  create a few text clipboard entries
2.  right click on an image on some web page:
![image](https://user-images.githubusercontent.com/167197/63604744-8ba51c80-c59a-11e9-9ae7-0a9b9e39c7a1.png)
3. note that for every image you copy, a text clipboard entry disappears

**Comment by p0deje** [comment]
Thank you for reporting, I'll look into this bug!

**Comment by DanielSmith** [comment]
thanks!
