### ISSUE TITLE
Filter out by source application

### ISSUE THREAD

**Issue by cgarrovillo** [p0deje/Maccy#300]
Pasteboard viewer has a way to tell the source of a clipboard item. It would be nice to filter out specific application or things like Keychain Access, where the pasteboard type is a utf8-plaintext,  which makes it very impossible to ignore.

![image](https://user-images.githubusercontent.com/6688713/126801127-a856383a-3b3e-46f7-bd62-b2fc20c5aa74.png)

**Comment by p0deje** [comment]
This is already implemented and will be available in the new version
