### ISSUE TITLE
Show Pinned Item Title and Text In Preferences

### ISSUE THREAD

**Issue by JosephTLyons** [p0deje/Maccy#301]
I just downloaded the newest update.  It is awesome to see the pinned items have the option to have titles.  The one thing I was wondering is if it would be possible to display the text as well.  I think that being able to see what it is is in that table would be useful in case we forgot what the pinned item actually was.  Its not difficult to just open up Maccy and copy that pinned item and paste it to find out, but I think having it in the table would be nice.

Maybe if the Title is blank, then it automatically inserts the text into both the Title and Text columns

```markdown
| Key | Title         | Text          |
|-----|---------------|---------------|
| a   | 155.19.213.66 | 155.19.213.66 |
| b   | 200.12.126.32 | 200.12.126.32 |
```

Then you can override the Title to have a different Title

```markdown
| Key | Title       | Text          |
|-----|-------------|---------------|
| a   | System 1 IP | 155.19.213.66 |
| b   | System 2 IP | 200.12.126.32 |
```

This software has become essential in my daily workflow, so I donated again and plan to continue to do so as new updates come out.  It is probably my most favorite utility application.

**Comment by p0deje** [comment]
@JosephTLyons Thanks for the proposal. Short-term, would just hovering an item and waiting until tooltip shows content?

**Comment by JosephTLyons** [comment]
Yeah I think a tooltip would work here.

**Comment by p0deje** [comment]
I'm going to close this in favor of tooltips for now.
