### ISSUE TITLE
Menu display broken on macOS 12 PB 3

### ISSUE THREAD

**Issue by philihub** [p0deje/Maccy#302]
Hate to say it, cause it worked greta again but the latest macOS Beta broke it again. Tried to add my Pins again but it did not work 😕 
<img width="502" alt="Bildschirmfoto 2021-07-29 um 10 47 39" src="https://user-images.githubusercontent.com/16780277/127461938-dbfe67bb-d7f5-487d-8ff3-c9fcb84383d8.png">
<img width="298" alt="Bildschirmfoto 2021-07-29 um 10 45 02" src="https://user-images.githubusercontent.com/16780277/127461947-eb3af023-f28b-4f06-8a52-ab6d1044134b.png">

**Comment by p0deje** [comment]
@philihub Can you try following the steps from https://gist.github.com/p0deje/72cc0b408f5d7b47f59ee82772499711 and let me know if it fixes?

**Comment by philihub** [comment]
It worked! Thanks!

**Comment by JohnGenest** [comment]
Same! Thanks!

**Comment by p0deje** [comment]
Have you accidentally ran older version of Maccy after upgrade?

**Comment by JohnGenest** [comment]
Hi - Just want to let you know that the "invisible pins" dynamic reappeared when I restarted the computer.  I was able to resolve by running the terminal command again. 

![Screen Shot 2021-08-04 at 10 40 14 AM](https://user-images.githubusercontent.com/73373019/128204901-2c380bc4-303d-4480-88da-4fd7ff65a881.png)

**Comment by p0deje** [comment]
Hmmm, are you sure you haven't run old version accidentally?

**Comment by JohnGenest** [comment]
What's the best way to update?  App store or via Github?  Thx!

**Comment by p0deje** [comment]
Github is free, App Store is paid. Feel free to choose whatever you want - they are the same.
Whatever you choose, it should auto-update itself.

**Comment by p0deje** [comment]
I'm going to close this since it looks to be a certain edge case of using various versions of Maccy together. Please reopen if issues happen again.

**Comment by JohnGenest** [comment]
Hi - I'm still having this issue on two computers.  Is it best to delete the app entirely and download again from the App Store?  And will that delete all of my pins?  Thanks in advance!
