### ISSUE TITLE
Maccy Stopped Displaying Copies After Computer Rest

### ISSUE THREAD

**Issue by JosephTLyons** [p0deje/Maccy#303]
We had a power failure in my area, so my computer shut down abruptly.  When it came back up, I opened up Maccy and it was entirely blank.  I can still click on the cells and it still copies the text into my clipboard, but I can't see what things are.  This screenshot was taken after some more things were captured, so the screenshot shows some items in Maccy, but it was entirely blank when I first started up my computer after the power failure.  

I had to cut out some items that were work-related, but you can see Maccy is blank in some areas.

<img width="499" alt="Screen Shot 2021-08-11 at 8 56 41 PM" src="https://user-images.githubusercontent.com/19867440/129122439-81269bd5-5c18-4e38-aed1-df880f3aafab.png">

**Comment by p0deje** [comment]
Ok, seems like something weird is going on. You will be able to fix this problem by following the steps in https://gist.github.com/p0deje/72cc0b408f5d7b47f59ee82772499711. However, the reason why it happened in the first place is confusing. Can you let me know:

1. What version of Maccy do you run - Github or App Store?
2. Is there any chance you have more than 1 version of Maccy on your computer?

**Comment by JosephTLyons** [comment]
I believe I used the download link on the website after donating, so it is not the App Store version.
I should only have one version installed, this version:

<img width="396" alt="Screen Shot 2021-08-12 at 10 12 48 AM" src="https://user-images.githubusercontent.com/19867440/129212375-bef7631f-b24a-4838-a045-3514f517db33.png">

**Comment by JosephTLyons** [comment]
The fix you provided seems to have worked for me.  Thanks for that.

**Comment by p0deje** [comment]
Hmm, okay. Let's consider this a weird power disruption glitch. Please reopen if this ever happens again.
