### ISSUE TITLE
Ignore items from Handoff

### ISSUE THREAD

**Issue by cgarrovillo** [p0deje/Maccy#304]
Would anyone know what the 'source' of Handoff is?  Pasteboard viewer only shows the most recent foreground application as the 'source' but is incorrect.

**Comment by p0deje** [comment]
What is handoff?

**Comment by cgarrovillo** [comment]
clipboard sync across devices

**Comment by p0deje** [comment]
You can add `com.apple.is-remote-clipboard` to ignored types.
