### ISSUE TITLE
UI/UX enhancement: Make the header and footer fixed while keeping the copied items list scrollable

### ISSUE THREAD

**Issue by ans1genie** [p0deje/Maccy#305]
Make the header and footer fixed while keeping the copied items list scrollable:
Header
![image](https://user-images.githubusercontent.com/16513804/129890696-2165f18a-90e5-44b6-ada1-82081262fd30.png)
Footer 
![image](https://user-images.githubusercontent.com/16513804/129890851-83c07ac5-b8f1-4600-a980-313dd2aacc1c.png)

**Comment by p0deje** [comment]
This is not possible using NSMenu.

**Comment by ans1genie** [comment]
another option is to move header items to the top in order to be fast accessible? 
> it's a bit annoying scrolling to the end to check the footer items!

**Comment by p0deje** [comment]
You can limit the number of menu items so that the rest is hidden by default - this way you don't need to scroll and you can access the rest using search.

Frankly, you don't often use the footer items and they have hotkeys.

**Comment by ans1genie** [comment]
true the footer is not that much used. that was just a PoV of seeing and accessibility, and wanna trigger a discussion about it. 
for me I keep scrolling cuz all the time I forgot xD.

**Comment by p0deje** [comment]
Thanks for bringing this up - I'd definitely implement the scrolling if it was possible, but unfortunately, it's not.
