### ISSUE TITLE
customize search result sorting

### ISSUE THREAD

**Issue by ans1genie** [p0deje/Maccy#306]
Is it possible to customize the behavior of search result sorting?
as in the sorting by, but a separate config for search result sorting:
![image](https://user-images.githubusercontent.com/16513804/129891186-ff24974c-70f0-4336-8f0b-b2543a0c642d.png)

**Comment by p0deje** [comment]
Without fuzzy search, the search results are also sorted using the same sorting option. 
With fuzzy search, the search results will be sorted by the fuzzy matching algorithm.

What would you like to change exactly?

**Comment by ans1genie** [comment]
I am talking about search without fuzzy algorithm, is it possible to have a own separate config related to search and not be same as "sorted by".

**Comment by p0deje** [comment]
What's the use case? Can you provide an example of when you'd want a different sorting with and without search?

**Comment by ans1genie** [comment]
would be meaningful for me to see the result of a search sorted by number of copies (as most of what i search are most used items in my daily routine)
and in normal case to see the list sorted by recent copied  (would be meaningful for me to not look for), because i switch a lot between recently copied items.

**Comment by p0deje** [comment]
> would be meaningful for me to see the result of a search sorted by number of copies (as most of what i search are most used items in my daily routine)

Would it make sense to pin often used items?

**Comment by ans1genie** [comment]
pin some items, that make sense!

**Comment by p0deje** [comment]
Awesome, please use pins then.
