### ISSUE TITLE
Search for entries copied from Excel or images

### ISSUE THREAD

**Issue by CrisVM** [p0deje/Maccy#308]
Hi,

First of all, thanks for developing and sharing this great app. I'm a former Clipy user and I think Maccy is far superior in many aspects.

But I'd like to ask a simple question: how can I use Maccy's search to find images or data copied from an Excel spreadsheet? _(which look like images on the list, BTW)_
![ZION³ 2021-08-24 at 16 59 11](https://user-images.githubusercontent.com/3301474/130682836-666aba46-43e9-4da8-9990-ec825dae8d9b.png)
Thanks in advance.
Cristiano

**Comment by p0deje** [comment]
Closing since no reply for more than a month. Feel free to re-open and provide more info.

**Comment by alankyshum** [comment]
First of all, thanks for adding support for copying images!
To the request, how about adding a filter that list out all copied images, so we can pick from that filtered list?
