### ISSUE TITLE
Launch at Login isn't working on macOS Monterey latest beta

### ISSUE THREAD

**Issue by i3p9** [p0deje/Maccy#309]
So getting this issue since upgrading to the latest beta, launch at login setting isn't sticking after a restart/app relaunch. I have the log from Console.app attached below.
[log.txt](https://github.com/p0deje/Maccy/files/7071187/log.txt)

how to reproduce:
https://user-images.githubusercontent.com/8825262/131226578-795ecf0f-f3a0-48ec-bfb1-e61644c7850b.mov

OS: 12.0 Beta (21A5304g)
Maccy version: Version 0.21.0 (7)

**Comment by p0deje** [comment]
Thanks for reporting. Should be fixed in https://github.com/Clipy/LoginServiceKit/commit/dfb9602e602621e6e3bdf6453e15e255dbe0d46f, I need to upgrade LoginServiceKit.
