### ISSUE TITLE
Can't ⌘+A (Command+A) text typed in the seach box to then delete it all at once

### ISSUE THREAD

**Issue by ChrisFR06** [p0deje/Maccy#311]
When using the search feature, it's not possible to simply ⌘+A (Command+A) the text typed into the input field to then delete (⌫) it all at once.

Instead, you currently have to hold down the backspace key until all the text you typed is gone or select the text with your mouse and delete it all with the backspace key.

**TL;DR: ⌘+A doesn't work as intended on the Maccy search field**

**Comment by p0deje** [comment]
That's by design becase the search field is never focused. To remove all the text, you can press Command+Delete (like in any other macOS text field).

**Comment by ChrisFR06** [comment]
> That's by design becase the search field is never focused. To remove all the text, you can press Command+Delete (like in any other macOS text field).

Thanks, didn't know you could do that!

Sorry for having wasted your time with this issue.
