### ISSUE TITLE
Pinned items are blank in drop down

### ISSUE THREAD

**Issue by allomorphy** [p0deje/Maccy#312]
Hey Folks,
For some days, my version 0.21.0 has had all the pinned items blank.
The  underlying data is still there so that I can paste, but I do nto know what I am pasting until I see it ;-)
The hotkeys still show.
If I pinned an image, then this is showing, but no text
And if I pin some new text, then that new text does show as a pinned item.

Recently I tried the feature for renaming an item and this worked but I am wondering f it is what caused this issue.

This is what it looks like:
<img width="544" alt="image" src="https://user-images.githubusercontent.com/50141922/131760616-72760ff7-f131-44ee-86f9-6beec321df39.png">

Any suggestions welcome,
Best wishes
Eric

**Comment by p0deje** [comment]
This can happen when you run an older version of Maccy after the upgrade. Have you?

Meanwhile, can you try following the steps in https://gist.github.com/p0deje/72cc0b408f5d7b47f59ee82772499711 - this should reset titles for all menu (so your renames will be reset as well).

**Comment by p0deje** [comment]
Closing since no response for more than month. Please re-open if issue happens again.
