### ISSUE TITLE
Add the ability to drag & drop (images) the list.

### ISSUE THREAD

**Issue by nevara** [p0deje/Maccy#313]
Add the ability to drag & drop images from the Maccy list.
At the moment you can only select one item from the list.
It would be great and more coherent with macOS to be able to drag and drop items from it. 
Useful especially for images, since you can drop images directly into an app, or as a file to the finder.

**Comment by p0deje** [comment]
Thanks for the report, but it's extremely hard to implement drag&drop in NSMenu and discouraged to do so (https://lists.apple.com/archives/cocoa-dev/2010/Feb/msg00703.html). Duplicate #290
