### ISSUE TITLE
Ability to paste directly with hot keys ⌘+1, ⌘+2, ⌘+3 ...

### ISSUE THREAD

**Issue by adamtash** [p0deje/Maccy#315]
First of all, thank you for the great app. I think it would be super useful if it was possible to paste directly with configurable hot keys (⌘+1, ⌘+2, ⌘+3 ... etc) without the need of calling the main Maccy with the hot key (⇧+⌘+C) first. I have been using [Ditto](https://ditto-cp.sourceforge.io) on Windows for years and I loved that feature. I have been looking for alternatives for mac and Maccy is the closest I could find so far. Is it possible to implement that feature? Thank you.

**Comment by p0deje** [comment]
First of all, how would you know what is in, let's say, the fourth history item? Given the clipboard changes often and every paste changes the order, it's easy to paste something if you don't see the list. For this reason I believe that pasting the second item only makes sense - the rest is too volatile.

Second of all, I would like to avoid messing with global hotkey as much as possible, so having such shortcuts would mean they need to be configurable as well and I'm not sure how it should look like (we shouldn't use numbers because many applications define their own ⌘+n, if we don't allow numbers, then what)?

I'm open to add something like this but I would like to:
* make sure the use case can't be solved in any other way
* we won't disrupt other people's workflows
* the UX is smooth

**Comment by adamtash** [comment]
Thank you for the detailed explanation. I didn't realize that every paste actually changes the order (I didn't get why is this useful?). Because of that I agree with you that the shortcut for the second item to paste would make more sense, and most of the time that's what we will need anyway. I often find myself copying unintended text right after the text I actually wanted to copy then it's very handy to paste the second item in the clipboard. 

Until this feature is implemented I found a workaround; creating a Quick Action Apple Script that sequentially keystrokes ⇧+⌘+C then ⌘+2  with Automator then assigning a shortcut to it as shown in the screenshot below does the job well.

`
on run {input, parameters}

   tell application "System Events" to keystroke "c" using {shift down, command down}
    delay 0.1
    tell application "System Events" to keystroke "2" using command down
    return input

end run
`
<img width="1692" alt="QucikAction" src="https://user-images.githubusercontent.com/5215055/134155215-fd6d0dec-c7c6-4a34-9292-9ec00d18ca12.png">

**Comment by NirSandbank** [comment]
Hi, was this change implemented? I'd love to hot keys to the pinned items.

**Comment by p0deje** [comment]
In the next version of Maccy, there will be support for Shortcuts (as long as you run macOS 11+). So far it's very basic but allows to automate selecting/pasting the clipboard history item by its number like this
<img width="862" alt="Screen Shot 2022-08-29 at 17 02 35" src="https://user-images.githubusercontent.com/665846/187319452-b64e2e2b-3d89-4fc2-a65f-2e23f6882907.png">

With this shortcut in place, it's possible to create several shortcuts to support pasting directly with ⌘+1, ⌘+2, ⌘+3 ...
The shortcut also returns the selected item title as an output so you can use it for other shortcut actions (e.g. show notification with copied title).

I think support for shortcuts is a good compromise for advanced usage without the need to introduce any complexity for the Maccy. Feel free to open new issues for any improvements of shortcuts.

**Comment by kpmainali** [comment]
I can call the main Maccy with the hot key (⇧+⌘+C). It shows me a list of copied items. However, I cannot paste the copies items with hotkeys like  ⌘+1, ⌘+2. Any idea why it is so?

**Comment by p0deje** [comment]
@kpmainali Make sure you have "Paste automatically" enabled in Maccy settings.

**Comment by p0deje** [comment]
@bastislack Pins are not special in that sense, and if you put them at the top, you can refer to them by numbers in the Shortcuts app, too. It would be more convenient to access via letters, but it's not supported at the moment.
