### ISSUE TITLE
You do not have permission to open the application "Maccy"

### ISSUE THREAD

**Issue by pindypondy** [p0deje/Maccy#316]
**Background**

I was previously running Maccy on OS 10.15 without incident.

**Steps**

1. I updated my Mac to OS 11.6 (which required a clean install)
2. I downloaded and unzipped Maccy
3. I have an Admin account on my Mac, but when I open Maccy.app I get the message `You do not have permission to open the application "Maccy".`

**Question**

How can I resolve this issue?

Thanks

**Comment by p0deje** [comment]
I don't think it's something specific to Maccy. Please try the suggestions in https://developer.apple.com/forums/thread/666611.

**Comment by pindypondy** [comment]
Thanks for the quick response. It does seem to be a Big Sur issue. Unfortunately, I think it's going to be quicker to find another clipboard app.

Thanks again.
