### ISSUE TITLE
Broken with upgrade to Big Sur 11.6

### ISSUE THREAD

**Issue by readysetawesome** [p0deje/Maccy#317]
I tried reinstalling the cask and restarting but it doesn't help. Something weird happens depends on the app that is open.  when I try to activate Maccy using cmd-shift-c :
* Browser opens inspector 
* vscode opens a new terminal window
* terminal opens a color wheel selector dialog

**Comment by rising-stark** [comment]
Well the thing is that cmd-shift-c is the default shortcut for performing those specific actions in the apps you mentioned.
Its not the issue with maccy. Even if you have a clean install of macOS 11.6, that shortcut will perform the actions you mentioned.

For a quick temporary fix you can consider changing the shortcut for opening Maccy. Change it to cmd-shift-v. It works perfectly fine for my macOS 11.6 and does not interfere with any other applications. For a proper fix and make maccy override this shortcut no matter the application open, you can only wait for the dev to reply.

**Comment by readysetawesome** [comment]
thanks!
