### ISSUE TITLE
Add support for MacOS 10.13?

### ISSUE THREAD

**Issue by MarcoAdinolfi** [p0deje/Maccy#320]
Hello,
First of all, thank you for your work. Is there a possibility that support for older MacOS versions, like 10.13 (High Sierra), will be added?
Thank you very much

**Comment by p0deje** [comment]
Unfortunately no, because of App Sandbox limitations. You can read more about High Sierra in #161

**Comment by MarcoAdinolfi** [comment]
Ok, thank you anyway
