### ISSUE TITLE
Ability to remove multiple selected items

### ISSUE THREAD

**Issue by TryTryAgain** [p0deje/Maccy#321]
This is a really great clipboard manager, thanks for your work. I've been waiting for something that could replace legacy/abandoned favorites. 

There are times when I have maybe 50/100 important things in my clipboard manager, I copy something sensitive here and there, and then want to screen share with someone but can't have those secrets visible and don't want to lose the other 80-90% of my clipboard that would still be important to me. 

It would be super if there was the ability to not only clear all contents but also selectively remove items; it would be really helpful if that functionality worked from a filtered list as well as the full/flat list.

**Comment by TryTryAgain** [comment]
Thank you, @p0deje ... yes, the thought is instead of the workflow:

1) open Maccy
2) peck and hunt for each item
3) and option + delete for each item

The workflow would feel a lot faster if we could somehow multi-select a bunch of items and then remove the whole lot at once, ie: 

1) open Maccy
2) hold some multi-select key combo "option+shift" or something similar
3) peck and hunt for each item, click them to add them to your growing list
4) remove all items with a single option + delete

Hope that makes sense.

**Comment by p0deje** [comment]
But you would still have to somehow select all these items. How is selecting with some key faster than pressing Opt-Delete on every item?

**Comment by p0deje** [comment]
Oh, so this is quite a different use case - search for old copies and then remove them at once.

What would you say if selecting “Clear” would remove only the found items? Would that satisfy your needs?

Thank you,
Alex

**Comment by TryTryAgain** [comment]
That would be a useful feature, for sure ;) but by use case wouldn't be solved by is because unfortunately the variety and complexity could never be surfaced with a filter.

**Comment by p0deje** [comment]
I think we can merge this with #239. Essentially, what the feature would look like is that there will be some mechanism to select multiple items and then perform any operations on them (pin, paste, delete).
