### ISSUE TITLE
Cannot add items to Pins

### ISSUE THREAD

**Issue by nhan-hv** [p0deje/Maccy#324]
I cannot use the Pins feature. Cannot double-click on it and enter a new value.

**Comment by nhan-hv** [comment]
That works for me. Sorry for the trouble. Thank you!

**Comment by hadifarnoud** [comment]
> You can’t add pins through this window - only edit. To add new pin, select the history item you want in normal Macy popup and press Option-P Thank you, Alex
> […](#)

that is bad UX though. I was confused too
