### ISSUE TITLE
Does or can Maccy support text transformations?

### ISSUE THREAD

**Issue by imthenachoman** [p0deje/Maccy#325]
All of us probably have a workflow we repeat all the time:
1. Copy something
2. Paste it into a temporary area
3. Modify/transform/alter the text
4. Copy 
5. Paste into the final destination

Being able to transform/alter the clipboard on paste would be wicked helpful. For example:

- Trim spaces
- Remove all letters and only leave numbers
- Extract only the email addresses (using regular expression) and comma separate 
- Extract a URL or some other string using regular expression
- Add text -- copy `Hello` and paste `<b>Hello</b>`
- ...the possibilities are endless.

Can Maccy do this? If not, any thoughts on adding it as a feature?

**Comment by zbridges-lastwall** [comment]
this would be useful for automatic redactions for things. matching a specific regex

**Comment by p0deje** [comment]
you can now do this via Shortcuts, please see my post https://www.reddit.com/r/macapps/comments/11sxz5t/maccy_026/ for some examples
