### ISSUE TITLE
可以申请退款吗？

### ISSUE THREAD

**Issue by jolly136** [p0deje/Maccy#326]
在app store误操作导致购买，请求申请退款。

**Comment by p0deje** [comment]
Please follow Apple policy on requesting refund - https://support.apple.com/en-us/HT204084.

**Comment by jolly136** [comment]
你好，我通过这个链接无法进行退款申请。苹果客服让我联系app的开发者申请退款。发自我的iPhone------------------ 原始邮件 ------------------发件人: Alex Rodionov  ***@***.***>发送时间: 2021年11月2日 05:20收件人: p0deje/Maccy ***@***.***>抄送: jolly136 ***@***.***>, Author ***@***.***>主题: Re: [p0deje/Maccy] 可以申请退款吗？ (Issue #326)
Please follow Apple policy on requesting refund - https://support.apple.com/en-us/HT204084.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/p0deje/Maccy/issues/326#issuecomment-956617045",
"url": "https://github.com/p0deje/Maccy/issues/326#issuecomment-956617045",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by p0deje** [comment]
@jolly136 Have you bought it on maccy.app or App Store? If on the website, I can refund you if you tell me your email address. If on the App Store - I cannot refund, only you can via the link I shared in the previous comment.

**Comment by jolly136** [comment]
你好，我是通过mac上的app store购买的，apple ***@***.***。我两次联系过苹果官方客服，也尝试过官方的链接进行退款操作，都不成功。发自我的iPhone------------------ 原始邮件 ------------------发件人: Alex Rodionov  ***@***.***>发送时间: 2021年11月2日 21:54收件人: p0deje/Maccy ***@***.***>抄送: jolly136 ***@***.***>, Mention ***@***.***>主题: Re: [p0deje/Maccy] 可以申请退款吗？ (Issue #326)
@jolly136 Have you bought it on maccy.app or App Store? If on the website, I can refund you if you tell me your email address. If on the App Store - I cannot refund, only you can via the link I shared in the previous comment.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/p0deje/Maccy/issues/326#issuecomment-957626987",
"url": "https://github.com/p0deje/Maccy/issues/326#issuecomment-957626987",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by p0deje** [comment]
@jolly136 Sorry, but if you purchased it in the App Store, the only way to refund is via the link I posted before. I cannot see who purchased Maccy and I cannot initiate refund from my end.
