### ISSUE TITLE
Feature request: pasting clipboard into file

### ISSUE THREAD

**Issue by caleidoscopio** [p0deje/Maccy#329]
I'd like the ability to paste the clipboard directly into a file into the current folder in Finder.

If I have an image in the clipboard it would save it into a png file in the current folder. If I have text it would paste it into a txt file, for example.

Essentially like a gui for pbpaste and pngpaste.

**Comment by p0deje** [comment]
That would make pasting behave differently if paste from Maccy or paste with regular Cmd+V. I don't think this would be intuitive for users but more confusing in my opinion. Sorry, but I don't want to implement it in the app.

**Comment by remissao** [comment]
I don't think you'd need to change the current behavior, only add a new one.

If you'd paste text into a Text editor window it would paste text. If you'd paste an image into Preview it would paste an image.

But if you'd paste any of these into a Finder window, it would generate a new file with the contents of the clipboard inside it.

This looks very intuitive to me.

**Comment by p0deje** [comment]
> If you'd paste text into a Text editor window it would paste text. If you'd paste an image into Preview it would paste an image.

This is intuitive because it behaves the same if you paste via Cmd+V or from Maccy.

> But if you'd paste any of these into a Finder window, it would generate a new file with the contents of the clipboard inside it.

This won't work if you select an old item from Maccy and then paste using Cmd+V. It would only work if you paste from Maccy directly.
