### ISSUE TITLE
History Not Showing Since Update to 0.22.0

### ISSUE THREAD

**Issue by Stickyhavr** [p0deje/Maccy#331]
Hello,
First of all just wanted to say thanks for all the amazing work you've done lately. I hadn't been following the GitHub for quite a while so I was pleasantly surprised by all the great new features in the latest release.

I'm having a little problem though: After upgrading to 0.22.0 I took a look around to appreciate all the new features. I renamed a couple of my pins, played with a few things and everything seemed to be working fine so I went about my day. Today, after a reboot, all of a sudden all of my history is not showing. It's still there, i.e. I can paste it and/or  hover my mouse over it to see what it is, but it's not displaying anything. All my pins are also affected. They're still there, just not showing. If I rename a pin, it shows. Also newly copied items (since last opening Maccy) do show. But as soon as I quit and restart Maccy, everything is gone again.

Is anything else experiencing this?  MacOS 11.6.1
![Maccy](https://user-images.githubusercontent.com/70360337/140837724-a06a4827-de86-44ac-b144-d0bc01967719.png)

**Comment by p0deje** [comment]
This can happen after running an older version of Maccy after upgrading to 0.22 (though nobody could pinpoint _how_ this happens). To fix this, please follow the steps in https://gist.github.com/p0deje/72cc0b408f5d7b47f59ee82772499711

**Comment by Stickyhavr** [comment]
Great. All fixed. Thanks!

**Comment by Stickyhavr** [comment]
Hello. I'm not sure if you'll see this message or not: I noticed in the new version that the shortcut of option + clicking the menu bar no longer disables Maccy??  Is there a way to bring back this behavior? I use it daily.  I didn't see anything in the options? (Except for going all the way into options and selecting "turn off"—is there a faster way?)

Or is my install misbehaving? Perhaps I should reinstall or something?

I suppose I can make a workflow in Alfred or in Shortcuts to use terminal to toggle these settings?
defaults write org.p0deje. Maccy ignoreEvents true # copy data
defaults write org.p0deje. Maccy ignoreEvents false

But it was much easier with the option+click. 

Thanks for your help!

**Comment by p0deje** [comment]
> Hello. I'm not sure if you'll see this message or not: I noticed in the new version that the shortcut of option + clicking the menu bar no longer disables Maccy?? Is there a way to bring back this behavior? I use it daily. I didn't see anything in the options? (Except for going all the way into options and selecting "turn off"—is there a faster way?)

It's a bug and I'll fix it.

**Comment by p0deje** [comment]
@Stickyhavr Hmmm, I think I've seen the bug but I cannot reproduce it anymore. Does it still happen for you?

**Comment by Stickyhavr** [comment]
Yes. But it may be related to the other issue because I'm still having trouble with that as well. Every time I reboot (which I don't usually do often, but have had to recently several days in a row) my history is gone. Running the terminal fix brings it back, but only until my next reboot.

So maybe I will try re-installing or something. But yes, at the moment, option+clicking on Maccy in the menu bar does not work for me.

Thanks

**Comment by p0deje** [comment]
@Stickyhavr Check your login items, maybe you have older Maccy that starts and messes up with the history.

Can you record a simple video in QuickTime showing option-click issue?

**Comment by Stickyhavr** [comment]
Hi. I'm sorry, I can't make a video right now. I reverted back to 0.20.1 which was the last version where option+clicking works on my system. (I tried 0.21.1 and 0.21.0 but it didn't work in those either, and I had the "invisible entries" bug happening as well. So I just went back to 0.20.1 for now. But I can tell you that on any of the 0.21 or later versions, option+clicking on the menu bar icon did exactly the same thing as just clicking: open the Maccy window.

Also, off topic: I had copied the Maccy folder: /Users/ME/Library/Containers/org.p0deje.Maccy/Data/Library/Application Support/Maccy which seems to have contained all of my history and pins; however, it did not contain my preferences.  Fortunately I remembered all my preferences so they were easy to set again, but for future reference where do those live so I can also restore those?  Thanks so much.

**Comment by Stickyhavr** [comment]
Oh, and yes I checked: when I was having those troubles I only had one version of Maccy installed.

**Comment by Stickyhavr** [comment]
Ok, another follow up: Just to be thorough, I tried updating Maccy on another machine in the house. An M1 MacBook Air. It upgraded flawlessly to the new version and is working perfectly, even after a reboot. Option+clicking works. All pins and history items are shown. 100% working correctly.

I wonder if it could be an Intel vs Apple silicon thing? Has anyone else reported the problem?
More information about my machine (the one having the trouble), in case it helps you pinpoint where the issue might be coming from:
macOS Big Sur
Version 11.6.1
MacBook Pro (16-inch, 2019)
Processor 2.3 GHz 8-Core Intel Core i9

**Comment by p0deje** [comment]
I've just pushed a fix that should make Option+Click work more reliably. Will be available in the next release.

As for empty history records - that only happens when you run different versions of Maccy. It can be fixed by https://gist.github.com/p0deje/72cc0b408f5d7b47f59ee82772499711 so hopefully you won't have to downgrade after I release new version.

In regards to preferences, they are stored in a different directory `$HOME/Library/Containers/org.p0deje.Maccy/Data/Library/Preferences/`

**Comment by Stickyhavr** [comment]
Ok great. I will definitely try the next release when it's available. Thank
you!
