### ISSUE TITLE
maccy.app's TLS certificate is expired, making the site inaccessible due to HSTS

### ISSUE THREAD

**Issue by NasaGeek** [p0deje/Maccy#332]
Expired 5 days ago, 2021-11-06.

**Comment by dominicpratt** [comment]
Problem persists...

**Comment by p0deje** [comment]
Thanks for the heads up, something is wrong with Github Pages and it refuses to update the certificate. I'm trying various workarounds from https://github.community/t/certificate-request-error-is-persistent-tls-certificate-cant-be-provisioned/11008 but no luck so far.

**Comment by p0deje** [comment]
Fixed, thanks everyone!
