### ISSUE TITLE
History only shows 10 items

### ISSUE THREAD

**Issue by hntee** [p0deje/Maccy#335]
Hi @p0deje ,

I have the issue that maccy only shows 10 history items, no matter what is the history size that I set.

OS: 10.15.7 Catalina
Maccy version: 0.21.1

**Comment by felixfrey** [comment]
The "history size" setting does not affect the number if items shown, you have to go to the "Appearance" tab and adjust the "menu size" setting.

**Comment by p0deje** [comment]
Please check what @felixfrey said
