### ISSUE TITLE
Make the app installation process easier

### ISSUE THREAD

**Issue by rakleed** [p0deje/Maccy#337]
Could you please make the process of installing the app more convenient either by making a DMG installer with the Applications folder and the app itself or immediately after launching, prompt the user to move the app to the Applications folder (if you determine that the app is not launched from the Applications folder)?

**Comment by p0deje** [comment]
How is the DMG easier than just downloading the archive, opening it, and moving the app to the Applications folder? It's not easier at least in my opinion, because then I also need to remember to unmount DMG and remove it manually.

**Comment by rakleed** [comment]
Most users just open the downloaded file, and on macOS, the zip archive is automatically unpacked, and it turns out that the app is launched from the Downloads folder, which causes problems.

And the overwhelming majority of apps are distributed via DMG, or at startup it offers to move the app to Applications if it is located in a different path.

Well, an unmounted DMG does not cause any issues, and when you turn off or restart your Mac, it will automatically unmount.

**Comment by jnubz** [comment]
It's not uncommon for zipped apps to require manual move to `/Applications/`.

If you are managing many users, you could pkg this in a repository like munki and send the install through MDM, or you can use ABM to purchase the app licenses in the App Store. With these options, you have control over where the .app saves.

I agree with the DMG issue too. Many of my clients never restart or log out, and their desktop become full of mounted DMGs. 😂

**Comment by p0deje** [comment]
> It's not uncommon for zipped apps to require manual move to /Applications/.

Given Maccy can work from any folder, there is no need to force moving the app.

> If you are managing many users, you could pkg this in a repository like munki and send the install through MDM, or you can use ABM to purchase the app licenses in the App Store. With these options, you have control over where the .app saves.

I actually don't know what Mungi, MDM or ABM is 🤔

**Comment by rakleed** [comment]
99% of apps in my experience are distributed via DMG, PKG, or on first launch they offer to move themselves to Applications, as this is the default path for all apps on macOS.

And if you do not like the option with DMG, then immediately after launching the app, you can prompt the user to automatically move it to Applications.

**Comment by georgesnow** [comment]
@rakleed in that context this is good guide:

https://christiantietze.de/posts/2019/09/detect-app-moved/

**Comment by p0deje** [comment]
> 99% of apps in my experience are distributed via DMG, PKG, or on first launch they offer to move themselves to Applications, as this is the default path for all apps on macOS.

Probably, but I rarely install apps like that - it's mostly either the App Store or Homebrew. I understand many people are used to DMG, but I'm yet to understand what problem adding DMG would solve for Maccy users except that "it's more common". I'd like to avoid adding anything to the project unless I'm sure it's absolutely necessary.

> And if you do not like the option with DMG, then immediately after launching the app, you can prompt the user to automatically move it to Applications.

What is the problem with running Maccy from `~/Downloads`? As far as I understand, there is no need to force moving the application to `/Applications` directory. In fact, many apps I use are installed to `~/Applications` and they seem to work just fine.

**Comment by pitschr** [comment]
App installation was extremely simple using AppStore ... try out it, and you are supporting the maintainer ;-)

**Comment by p0deje** [comment]
Closing since there was no response for a few months. Please reopen if it's still important and provide more info.

**Comment by ftphikari** [comment]
I wouldn't mind it being a .dmg instead. All my other programs are .dmg, so that's what I expect naturally. It also makes the app look more polished, but that's minor as well. I'd say just do it because that's the standard way of doing things on Mac, people are used to it.

**Comment by p0deje** [comment]
@ftphikari Pull requests are welcome!
