### ISSUE TITLE
Popup Menu Numbering

### ISSUE THREAD

**Issue by marklander** [p0deje/Maccy#340]
**Maccy is awesome!**

I've recently switched from Clipy, and find I'm missing a few things that made using it much faster in my daily workflow:

1) **'Mark menu items with numbers'** which makes the menu a numbered list (with the number on the left). Pasting items is faster because the item can be selected by number as soon as the eye/brain makes a match—your eye doesn't need to transverse the line to identify its keyboard equivalent. Seems like a small difference, but it's faster.

2) With this option, items can be selected and directly pasted by number—a modifier key is not required. I understand the logic, since Maccy has the search history feature, however, with a small number of items, selecting by number becomes more desirable than search. If 'Mark menu items with numbers' was a preference, this behavior could be enabled.  

3) **'Clear History'** keyboard shortcut. In Maccy, the menu needs to be activate, and an additional modifier is required with a keyboard shortcut. This is too cumbersome. I'm a medical complaint analyst and copy 10-20 items when working with a record—when finished, the history needs to be cleared to prevent any risk of commingling information in another record.

_Wish List:_ 
How about adding support for AppleScript? Then I could write a script for coping the same items from different records (bliss)!
JSON objects keys would make automation possible.

**Comment by marklander** [comment]
Maccy Menu:
![image](https://user-images.githubusercontent.com/95704374/145075881-ab9aa17f-7259-444d-8cef-e3cf30835269.png)

Clipy Menu with Numbers:
<img width="183" alt="Clipy Menu" src="https://user-images.githubusercontent.com/95704374/145076188-64379c6e-64cd-4981-b19a-8368ca531706.png">

**Comment by p0deje** [comment]
Hi! Thanks for the feedback:

> 'Mark menu items with numbers' which makes the menu a numbered list (with the number on the left). Pasting items is faster because the item can be selected by number as soon as the eye/brain makes a match—your eye doesn't need to transverse the line to identify its keyboard equivalent. Seems like a small difference, but it's faster.

I've got nothing against adding number prefixes. Not sure when I'll have time to implement it though. PRs are also welcome.

> With this option, items can be selected and directly pasted by number—a modifier key is not required. I understand the logic, since Maccy has the search history feature, however, with a small number of items, selecting by number becomes more desirable than search. If 'Mark menu items with numbers' was a preference, this behavior could be enabled.

I'd like to maintain search-as-you-type feature and avoid altering this behavior by numbered list. I believe it would be easy to to figure out the keyboard shortcut to use as long as the prefix is visible.

> 'Clear History' keyboard shortcut. In Maccy, the menu needs to be activate, and an additional modifier is required with a keyboard shortcut. This is too cumbersome. I'm a medical complaint analyst and copy 10-20 items when working with a record—when finished, the history needs to be cleared to prevent any risk of commingling information in another record.

So what exactly do you propose? You can probably build a script that clears `~/Library/Containers/org.p0deje.Maccy/Data/Library/Application\ Support/Maccy/Storage.*`and restart Maccy, then assign it to a global key.

> How about adding support for AppleScript? Then I could write a script for coping the same items from different records (bliss)!

Could you elaborate more? I don't quite follow that.

**Comment by marklander** [comment]
I appreciate your following up. For how I use a clipboard manager, needing the command key to paste from a list of items is not something I like very much. 

Regrading the last item, it Maccy were scriptable, with hooks for adding items, search items, transversing the list, and pasting—repetitive tasks could be automated. It's an edge use case, so probably not be worth your effort. Example: I commonly need to copy items from the same fields, over and over in different records—this can already be done by scripting the native copy command. It would be interesting to write scripts for Maccy to use in scriptable app like Numbers, Safari, or Chrome where items could be selected from Maccy's using its search feature (regular expressions, perhaps) or position in the list, and then pasted in different fields automatically. Would just need an AppleScript library for some hooks.

**Comment by marklander** [comment]
Re: clearing history
> So what exactly do you propose? 
A global shortcut for clearing history—without needing to open the list/app. Or make the current 'Clear' shortcut globally actionable, just like the 'Hotkey' to open the application.

**Comment by p0deje** [comment]
> Regrading the last item, it Maccy were scriptable, with hooks for adding items, search items, transversing the list, and pasting—repetitive tasks could be automated. It's an edge use case, so probably not be worth your effort. Example: I commonly need to copy items from the same fields, over and over in different records—this can already be done by scripting the native copy command. It would be interesting to write scripts for Maccy to use in scriptable app like Numbers, Safari, or Chrome where items could be selected from Maccy's using its search feature (regular expressions, perhaps) or position in the list, and then pasted in different fields automatically. Would just need an AppleScript library for some hooks.

I'm no expert with AppleScript, but I'd assume you can already do that by sending keystrokes, for example, send keystrokes to popup Maccy window, send keystrokes to search for a certain string, then select and paste by sending another keystroke. It might be tricky, but adding custom AppleScript commands support in Maccy is a non-trivial task.

> A global shortcut for clearing history—without needing to open the list/app. Or make the current 'Clear' shortcut globally actionable, just like the 'Hotkey' to open the application.

Have you considered my proposal for clearing `~/Library/Containers/org.p0deje.Maccy/Data/Library/Application\ Support/Maccy/Storage.*`?

**Comment by p0deje** [comment]
Here is an example of using AppleScript to paste the previous item - https://github.com/p0deje/Maccy/issues/315#issuecomment-923850126

**Comment by marklander** [comment]
Yes, I've been using a script to send keystrokes. I use a .25 second delay after invoking Maccy, then send the keystrokes to clear history. The menu briefly shows with history, then clears, which gives visual feedback that it was successful. For some reason, it occasionally fails. I clear Maccy's history after working with a customer record to prevent cross-record errors—maybe 50 times a day.

A Maccy AppleScript dictionary with a method for clearing history would be more desirable. 

Didn't try your proposal for deleting storage, thinking it could be slow to execute. I'm usually on the next record when needing to clear Maccy and begin copying new information quickly.

**Comment by p0deje** [comment]
> Didn't try your proposal for deleting storage, thinking it could be slow to execute. I'm usually on the next record when needing to clear Maccy and begin copying new information quickly.

I actually think it should be quite fast. What you can do is have a script that kills Maccy, removes the files and starts once again. If you can run the following shell script, it completes under a second on my machine:

```sh
#!/bin/sh

pkill -f Maccy.app
rm ~/Library/Containers/org.p0deje.Maccy/Data/Library/Application\ Support/Maccy/Storage.*
open /Applications/Maccy.app
```

**Comment by p0deje** [comment]
In the next version of Maccy, there will be support for Shortcuts (as long as you run macOS 11+). So far it's very basic but allows to automate clearing the clipboard history with a shortcut like this 
<img width="862" alt="Screen Shot 2022-08-29 at 17 01 35" src="https://user-images.githubusercontent.com/665846/187319305-591a98a0-72f3-4577-82b0-a5583b82eb7c.png">


I'm going to close this issue and feel free to open new issues for more advanced shortcut actions.
