### ISSUE TITLE
Deleting first entry (1) does not clear clipboard when pasting with shortcut

### ISSUE THREAD

**Issue by Phlogi** [p0deje/Maccy#343]
1. Delete current / first entry (ctrl-backspace)
2. Paste with shortcut
3. Deleted entry is pasted

Expected behavior:

- Nothing should be pasted or the new first entry (previously number 2)

**Comment by p0deje** [comment]
I think it works as expected because deleting an item only removes it from Maccy history and leaves the system clipboard intact.

**Comment by Phlogi** [comment]
> I think it works as expected because deleting an item only removes it from Maccy history and leaves the system clipboard intact.

Well i'd expect it to sync with system clipboard again and to paste the currently top item.
