### ISSUE TITLE
Save clipboard to folder

### ISSUE THREAD

**Issue by roubles** [p0deje/Maccy#347]
Good work on this tool. I am coming here from the now unmaintained project [Clipy](https://github.com/Clipy/Clipy).

The idea is that we can specify a folder (in preferences), and Maccy will **save every clipboard entry** to that specified folder.

Each clipboard entry will be stored in the specified folder in a standard sequential filename, such as:
- maccy-2022-01-02T00:19:55Z
- maccy-2022-01-02T00:17:32Z
- maccy-2022-01-02T00:11:01Z
- and so on...

This simple enhancement will make Maccy universal. For instance, if the folder you specify is in dropbox or Google Drive, then any machine (Windows, Linux, Mac, iphone, Android) where you have access to that folder, will now have access to your clipboard.

This will also build the groundwork for a true universal clipboard in Maccy in the future (if so desired).

**Comment by p0deje** [comment]
I have no intention to make Maccy a universal clipboard manager. I could see a value in synced clipboard across multiple Macs, but this could be better implemented via #182 and iCloud. In regards to other platforms you mentioned (iOS, Android, Linux) - syncing won't be useful unless there are clients for these platforms. There are none at the moment, so it doesn't seem valuable to me.

**Comment by roubles** [comment]
Good point @p0deje. From reading through the comments of #182 it seems like Maccy being local is a selling point. So, if we were to backup/sync across iCloud it would be good if that is an 'opt-in' feature.

**Comment by p0deje** [comment]
Sure, sync with iCloud would be opt-in if implemented. I'm going to close this issue for now then. Please, re-open if there is anything else missing.
