### ISSUE TITLE
Paste is not working on some applications

### ISSUE THREAD

**Issue by ofraiwan** [p0deje/Maccy#349]
JetBrains Pycharm IDE does not accept pasted elements. 
When trying to paste something from Clippy, the text is not pasted in the editor of the IDE nor in any text dialog.

Environment: macOS Monterey.
Application: PyCharm Professional 2021.3.1

**Comment by buckett** [comment]
I see the same thing in another application in the JetBrains family (IntelliJ).

**Comment by p0deje** [comment]
I just tried pasting in IntelliJ IDEA 2021.2.3 (Community Edition) and it worked without problems. Could you provide more details about the Maccy version, the output of running `defaults read org.p0deje.Maccy` in the Terminal.app and the video of the problem.

**Comment by buckett** [comment]
Thanks, I just tried again and it worked.... very strange. I'm on IntelliJ IDEA 2021.2.3 (Ultimate Edition)
I have re-started Maccy since having this problem. With it now working this is the output from `defaults`:

```❯ defaults read org.p0deje.Maccy
{
    "KeyboardShortcuts_popup" = "{\\"carbonModifiers\\":768,\\"carbonKeyCode\\":8}";
    NSNavPanelExpandedSizeForOpenMode = "{800, 448}";
    "NSWindow Frame NSNavPanelAutosaveName" = "880 725 800 448 0 0 2560 1415 ";
    "NSWindow Frame SUStatusFrame" = "1080 961 400 134 0 0 2560 1415 ";
    "NSWindow Frame com.sindresorhus.Preferences.FrameAutosaveName" = "999 377 562 713 0 0 2560 1415 ";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2022-01-05 09:28:12 +0000";
    enabledPasteboardTypes =     (
        "public.tiff",
        "public.file-url",
        "public.png",
        "public.utf8-plain-text"
    );
    history = {length = 42, bytes = 0x62706c69 73743030 a0080000 00000000 ... 00000000 00000009 };
    ignoredApps =     (
        "com.apple.keychainaccess"
    );
    ignoredPasteboardTypes =     (
        "net.antelle.keeweb",
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "Pasteboard generator type",
        "com.agilebits.onepassword"
    );
    migrations =     {
        "2020-02-22-history-item-add-copied-at" = 1;
        "2020-02-22-history-item-add-number-of-copies" = 1;
        "2020-04-18-switch-storage-to-core-data" = 1;
        "2020-04-25-allow-custom-ignored-types" = 1;
        "2020-06-19-use-keyboardshortcuts" = 1;
        "2020-09-01-ignore-keeweb" = 1;
        "2021-02-20-allow-to-customize-supported-types" = 1;
        "2021-06-28-add-title-to-history-item" = 1;
        "2021-10-16-remove-dynamic-pasteboard-types" = 1;
    };
}```

If I can manage to break it again I'll update the ticket.

**Comment by ofraiwan** [comment]
I am also able to paste texts now in PyCharm. Although I tried to restart the application and the machine previously and was not successful to paste, now it is working fine.

Will provide more info if the issue appeared again.

Thank you

**Comment by p0deje** [comment]
Mystery! I'll close the issue for now, please re-open if it happens again with more details.
