### ISSUE TITLE
Changes in Hotkey not working

### ISSUE THREAD

**Issue by davidperezgar** [p0deje/Maccy#35]
Hello, I'm using this command, but it seems that is not working...

defaults write org.p0deje.Maccy hotKey command+option+v

Anything wrong?

**Comment by davidperezgar** [comment]
The default one Command + Shift + C is the the default for inspecting webs in Chrome...

**Comment by pawelkaczmarek** [comment]
Have you tried restarting the app after making the change?

**Comment by davidperezgar** [comment]
You are right! Please update in the readme, so the people can know the procedure.

Thanks!
Regards

**Comment by p0deje** [comment]
Duplicate of #27
