### ISSUE TITLE
Enhancement - X Windows style clipboard handling

### ISSUE THREAD

**Issue by ksandvik** [p0deje/Maccy#350]
I.e. select text -> clipboard. Paste, usually the middle-mouse but a defined mouse action such as three-finger click would be fine, too.

**Comment by p0deje** [comment]
The clipboard is macOS native, there is nothing Maccy can do about it.

**Comment by KingSupernova31** [comment]
Seconded that this would be very useful. I love the Linux clipboard system with the ability to copy-paste using only the mouse, and it seems like this would be a natural fit for Maccy given that the motivation was moving from Linux.

I'm confused why you claim that this is impossible; third-party apps can absolutely modify shortcuts and other Mac features. I'm using Karabiner-Elements to do that for other things right now.

**Comment by p0deje** [comment]
@KingSupernova31 There is no way for a sandboxed application in macOS to observe when a user selects a text in a random application. Maybe Karabiner-Elements can do that, but it's not sandboxed and has larger permissions than Maccy.
