### ISSUE TITLE
Allow navigation with fzf-like keys

### ISSUE THREAD

**Issue by netmute** [p0deje/Maccy#352]
I know I'm weird, but I'd like Control-K as alternative to arrow up, and Control-J as alternative to arrow down 😅
These shortcuts already do something, but I can't figure out if that's intentional.

**Comment by p0deje** [comment]
I guess you want different keys as Vim has `<C-p>` for up arrow `<C-j>` for down arrow:

```
3. Up-down motions					*up-down-motions*

k		or					*k*
<Up>		or					*<Up>* *CTRL-P*
CTRL-P			[count] lines upward |linewise|.

j		or					*j*
<Down>		or					*<Down>*
CTRL-J		or					*CTRL-J*
<NL>		or					*<NL>* *CTRL-N*
CTRL-N			[count] lines downward |linewise|.
```

**Comment by netmute** [comment]
My bad, I probably should have explained why `Ctrl-j` and `Ctrl-k` specifically 😅

The usual keys, that many people are used, to are `j` and `k`. As these can't be used for obvious reasons, other tools, like fzf, use ctrl as modifier for j and k to navigate the search result list.
My reasoning for keeping the shortcut the same as in fzf was that it would be nice for muscle memory.

`<C-p>` and `<C-j>` are pretty unknown shortcuts, even among Vim users.

**Comment by p0deje** [comment]
Will be available in the next version. Meanwhile, you can also use Control+N/Control+P that are already supported.
