### ISSUE TITLE
Option click on menubar icon for default menu listing. 

### ISSUE THREAD

**Issue by seivan** [p0deje/Maccy#355]
I don't mind adding this PR myself if you're ok with the suggestion.

With these settings
<img width="323" alt="image" src="https://user-images.githubusercontent.com/55424/149127947-9a92c892-35b5-4387-9ceb-cce08632606f.png">

The only way to get to settings is if you use the keyboard shortcut `cmd+,`. 
The application should try to follow the convention that `option+click` on the menu bar icon should show the "default" or "full" menu, regardless of settings.

Keep in mind that not only can't you reach settings, you also can't quit, which is generally bad. 

E.g `option+click` on the Wifi menubar will show "extra" details
<img width="251" alt="image" src="https://user-images.githubusercontent.com/55424/149128227-ef054c0a-1a91-4315-92ad-63dd4d25acc4.png">

**Comment by p0deje** [comment]
Command+click is reserved for moving the menu icons so we can't use it. Frankly, Option is the only modifier we can use and it's often used by other apps to toggle them on/off (e.g. Lungo.app)

**Comment by seivan** [comment]
> Command+click is reserved for moving the menu icons so we can't use it. Frankly, Option is the only modifier we can use and it's often used by other apps to toggle them on/off (e.g. Lungo.app)

So use `option+click` as the issue stated? 
It's not used right now, `option+right-click` is used for toggling enable/disable.

**Comment by p0deje** [comment]
Option+click is used to disable/enable Maccy. Is it not working for you?

**Comment by seivan** [comment]
> Option+click is used to disable/enable Maccy. Is it not working for you?

No, only `option+rightclick` is working for me to toggle enable/disable. 

`macOS 11.6.2 (20G314)`

**Comment by p0deje** [comment]
Are you running the latest version 0.22? It works fine for me on both macOS 12 and macOS 11.

**Comment by seivan** [comment]
I am running `maccy: 0.22.0,9`

<img width="360" alt="image" src="https://user-images.githubusercontent.com/55424/149167964-7ff499fe-3099-4672-bd59-4237bd36dece.png">
