### ISSUE TITLE
Read environment variable to allow storing history in different path. 

### ISSUE THREAD

**Issue by seivan** [p0deje/Maccy#357]
I can add support for this in a PR if you're ok with the suggestions. 

It would be neat if the application would check `ENV` for where to store history. I already do this with zsh history, and I'd like the same for Maccy. 

Bonus would be if configuration of Maccy could also be done with ENV variables that would be read on launch and override existing settings. This is better than copying plist files around, not a big deal but it would be easier to integrate Maccy into my macOS setup scripts.

**Comment by p0deje** [comment]
I think it's not possible because the application is sandboxed, so it's limited to read/write to `~/Library/Containers/org.p0deje.Maccy/`.

**Comment by seivan** [comment]
@p0deje How about adding additional entitlements? 
`com.apple.security.files.user-selected.read-write`

This would open up for allowing to have not only a config path elsewhere, but also the storage. 
I don't mind helping with a PR if you're interested.
