### ISSUE TITLE
Document features, like deleting individual items. 

### ISSUE THREAD

**Issue by seivan** [p0deje/Maccy#359]
Looking through the source, I noticed you could delete individual items using `option+backspace`.
I am not sure what else I'm missing, but it would be neat if they keyboard shortcuts were listed in one place - not necessarily mutable, just listed.

**Comment by p0deje** [comment]
All the keybindings such as pin/delete are shown in each entry tooltip. Is this not enough?

**Comment by seivan** [comment]
> All the keybindings such as pin/delete are shown in each entry tooltip. Is this not enough?

This makes the assumption that the user will keep the mouse long enough to see the tooltip, I mean I did that but I was investigating. 

These are the keybinds I am aware of.
`shift+cmd+c` to open menu
<img width="426" alt="image" src="https://user-images.githubusercontent.com/55424/149315908-e358e499-f153-4fad-b3b8-7a5af113d530.png">
`option+backspace` to delete
`option+p` to pin. 

It's not an issue for me, but it could be a UX suggestion to keep them in one place/tab. In the future, you could let people record their own in case they clash, but I actually like them as they are.

**Comment by p0deje** [comment]
Thanks, for the proposal, I'm going to close it for now as I don't see anything to change at the moment - most users had no problems with learning these bindings. Let's keep things they way they are now.
