### ISSUE TITLE
Sometimes slow and then old list

### ISSUE THREAD

**Issue by frank-f** [p0deje/Maccy#36]
Hi,
I can't quite reproduce it, but sometimes if I haven't used Maccy in a while (a few minutes to hours) and then press the hotkey, it takes a few seconds to load the list. When this happens I'm always being presented an old list. So I close the context menu right away, immediately press the hotkey again - the list pops up quickly and shows the most recently copied entries.

Originally I had my historySize set to 1000. I've tried reducing it to 100, but still had the same problem. I am running 0.4.0 and I have also tried rebooting the Mac entirely. Any ideas what I could do?

Kind regards

**Comment by p0deje** [comment]
This looks really strange, I'll try to reproduce it. Do you happen to copy a lot during this period?

**Comment by frank-f** [comment]
Yes, I copy a lot. I'd guess about 50 times between using the hotkey again to open Maccy.

**Comment by max-wittig** [comment]
Thanks for your response and for creating this awesome tool! 👍 

Not sure how. I happens randomly, but a few days a day. 

My behaviour is maybe also at fault. I use it rarly (1-2 times a day), but I copy a lot of small and sometimes also big text snippets. 

Other problem which may be related that it sometimes infini-scrolls, instead of stopping at the bottom. I've also decreased the size of the history to try to fix the problem. I think it occurs less now, but not sure.

**Comment by jkrenge** [comment]
Yes, I experienced the same with the default 999 items in the list, and then copy-ing larger items like complete HTML email templates. If you have a couple of those, I assume it just takes time to load all items from swap.

**Comment by max-wittig** [comment]
I also assumed that, but it doesn't have to be. The clipboard tool on my linux doesn't stutter. No matter how large the items. There must be a bug somewhere.

**Comment by marcomayer** [comment]
I have the same issue. Sometimes it takes 10 seconds or so for the list to show after pressing the hotkey and then it might be an old version of the list. Also sometimes it's fast but shows an old version. Still thanks a lot for the tool, hopefully, this can be fixed sometime!

**Comment by saeedseyfi** [comment]
Same happens to me a lot. Showing the old menu is really bothering.
And it's quite hard to reproduce. It seems it only happens when you don't use maccy for at least some hours. Then next time you open it, will be quite slow and showing the old menu with wrong items in the list.
I guess this issue started since you put the search field on the top of the menu.

**Comment by montanaflynn** [comment]
Happens to me as well, when I trigger the hotkey there's a delay and I usually will redo the hotkey several times. Then maccy will open with the old list and when I close that it will open as many times as I triggered it.

**Comment by saeedseyfi** [comment]
@p0deje I could reproduce the issue and recorded my screen to show how it behaves:
[screen record.mp4.zip](https://github.com/p0deje/Maccy/files/3696915/screen.record.mp4.zip)

To reproduce:
1. Make sure Maccy is running in background
2. Use your normal copy/paste several times but don't use Maccy for some hours.
3. Use your hotkeys to open Maccy menu.
    - It possibly has some delay to show the menu.
    - When the menu is shown, it doesn't have a search field, shows an old list from clipboard contents.
4. Press escape to hide the menu
5. Use your Maccy hotkeys again to open menu.
    - It opens pretty quickly showing the right content and working fine.

**Comment by philihub** [comment]
Same here. I am on macOS 10.15 and Maccy is sluggish. Not sure if too many items or something else.

hotKey = "command+shift+x";
pasteByDefault = true;

**Comment by mgthantzin** [comment]
Encountered the same issue. After having delay for once, it will become responsive for some time. I thought it was due to Unicode characters (Asian texts) that I copy a lot.

**Comment by p0deje** [comment]
I made some refactoring that might potentially solve the problem and will be testing it for some time. The refactoring touched the core of Maccy so it might introduce some new bugs. It's done in 6f6eb3c. If anyone wants to participate in testing, I'm attaching the built app here.

**Comment by p0deje** [comment]
[Maccy.app.zip](https://github.com/p0deje/Maccy/files/3738429/Maccy.app.zip)

**Comment by frank-f** [comment]
Thanks, I will test that version and let you know in a few days if I've seen the error again.

**Comment by FernandoMiguel** [comment]
> [Maccy.app.zip](https://github.com/p0deje/Maccy/files/3738429/Maccy.app.zip)

downloading and testing

**Comment by frank-f** [comment]
The old-list problem seems to be fixed, but opening the list still seems to be very slow sometimes. Also I noticed that "pasteByDefault = true;" has no effect anymore.

**Comment by p0deje** [comment]
> The old-list problem seems to be fixed

Good to know that.

> opening the list still seems to be very slow sometimes

Can you record a screencast just to check how it looks like?

> Also I noticed that "pasteByDefault = true;" has no effect anymore.

Can you try removing "Maccy" from "Security & Privacy" -> "Accessibility", then restart Maccy and try again? It might be a permissions problem.

**Comment by FernandoMiguel** [comment]
> > Also I noticed that "pasteByDefault = true;" has no effect anymore.
> 
> Can you try removing "Maccy" from "Security & Privacy" -> "Accessibility", then restart Maccy and try again? It might be a permissions problem.

that seems to have worked!
thanks

**Comment by frank-f** [comment]
> > opening the list still seems to be very slow sometimes
> 
> Can you record a screencast just to check how it looks like?

So far it has not happened again. If it does, I'll try to make a video the next time.

> Can you try removing "Maccy" from "Security & Privacy" -> "Accessibility", then restart Maccy and try again? It might be a permissions problem.

That fixed it for me too, thanks! Is it maybe related to Catalina?

**Comment by p0deje** [comment]
>  Is it maybe related to Catalina?

It definitely might.

**Comment by frank-f** [comment]
> Can you record a screencast just to check how it looks like?

So far it has not happened again. So it might have been my system being slow when I saw it.

Also I've not seen the old list (without search field) since installing the beta version, so I'd say this is fixed. Thank you!

**Comment by max-wittig** [comment]
@p0deje Can we have a new release, because of this fix? Then I could just run `brew cask update` 😄

**Comment by p0deje** [comment]
I've just released 0.6.0 - https://github.com/p0deje/Maccy/releases/tag/0.6.0. If someone can upgrade it in caskroom that would be cool.
