### ISSUE TITLE
Ignore copying from Passwords pane in System Preferences

### ISSUE THREAD

**Issue by SKStrategia** [p0deje/Maccy#364]
Hi!
I'm a user of both Maccy and the new Passwords prefpane introduced in Monterey. However, when I copy passwords, Maccy saves them in the clipboard history. I was wondering if it could be set to ignore copying from there. I tried entering System Preferences into the ignore list (using both methods) and it did not work.
Thanks!

**Comment by p0deje** [comment]
I've just tried adding "System Preferences" to the ignored apps list and it works correctly, ignoring passwords I copy from there.

It seems to be the only way to do that because the copy itself is just a regular UTF-8 string with a password value.
