### ISSUE TITLE
Using Maccy with Microsoft Remote Desktop Connection, does not paste anything. It just puts a "v" character instead.

### ISSUE THREAD

**Issue by ibgbeny** [p0deje/Maccy#365]
The list of available items appears but it just doesn't do the paste.
It might have something to do with the fact the Windows expects Ctrl + V but I am not sure

**Comment by p0deje** [comment]
What happens when you press CMD+V manually in the app? Is it also not doing anything to does it paste normally?

**Comment by ibgbeny** [comment]
Using CMD+V does work and Pastes the clipboard as expected but that also happens when i press Ctrl+V which is default on windows. I think the app transforms Cmd+V to Ctrl+V automatically.

Beni Ile

**Comment by p0deje** [comment]
Interesting. What Maccy does is simply send a "Cmd+V" event so I would expect it to transform the event too. I'll need to look into this.

**Comment by ibgbeny** [comment]
Let me know if I can help with testing

Beni Ile

**Comment by p0deje** [comment]
@ibgbeny Do you happen to have an accessible Windows machine I could use to RDP to? I only have Windows VM running via Parallels Desktop, but it's Windows 11 Home Edition and I cannot enable Remote Desktop on this edition. Also, pasting works fine in Parallels Desktop.

**Comment by jnubz** [comment]
I've noticed this as well with many clipboard managers over the years. It also types a "v" when doing a remote screen share using the macOS native app to another Mac.

If you invoke Maccy, it sends a "v", but backspacing the v and then pasting normally will paste the item you wanted.

(I do this daily since I do Mac Help Desk)

I do not know if the cause is the same for ARD and MS RDP, but it might be.

**Comment by ibgbeny** [comment]
> 

Yes, i've had this issue with other clipboard managers in the past but there are some that work.
For example aText, which is a text expander working also with the clipboard, works ok with this.

**Comment by ibgbeny** [comment]
> @ibgbeny Do you happen to have an accessible Windows machine I could use to RDP to? I only have Windows VM running via Parallels Desktop, but it's Windows 11 Home Edition and I cannot enable Remote Desktop on this edition. Also, pasting works fine in Parallels Desktop.

I'll give it a try and find you a windows machine to connect to. I'll DM it to you on twitter

**Comment by ibgbeny** [comment]
@p0deje I managed to create an Azure Win 10 PC for your testing purposes. I tried DMing you but it seems I cannot. Let me know how I could send you the credentials

**Comment by p0deje** [comment]
@ibgbeny I've opened DMs on Twitter for everyone - you should be able to send the credentials there.

**Comment by p0deje** [comment]
@ibgbeny I can confirm the bug is happening on Microsft RDP. I also tried using other RDP clients (I have Jump Desktop) and pasting works correctly there. I assume there is something special about how the Microsoft RDP app handles keyboard events. I will try to figure this out, thank you for the help.

**Comment by georgesnow** [comment]
I haven’t had this issue before. Maccy, Alfred, or BTT clipboard manager in Microsoft rdp. 

I do I know for me each and every  connection inside connection manager. I have to set “redirect clipboard” under “devices & audio”

Unless I misunderstanding the context of the issue.

**Comment by ibgbeny** [comment]
> I haven’t had this issue before. Maccy, Alfred, or BTT clipboard manager in Microsoft rdp.
> 
> I do I know for me each and every connection inside connection manager. I have to set “redirect clipboard” under “devices & audio”
> 
> Unless I misunderstanding the context of the issue.

This is strange. I have the same setup but it doesn't work for me. Are you using the relatively new RDP app, or the old one?

**Comment by georgesnow** [comment]
10.7.6 (1972)

I did remeber  the other setting under 
Connections =>keyboard mode => Unicode 

you have set to Unicode. I notice the mention of the virtual keys above another app(MacPass) autotype feature would just send “v” s because of that.

**Comment by p0deje** [comment]
If I switch to "Unicode" mode under connection, it doesn't even type "v". Attempt to paste produces a macOS sound similar to the one when you try to press "Cmd+V" in a window that doesn't accept paste (e.g. Maccy preferences).

**Comment by georgesnow** [comment]
To clarify you have to select an item within the clipboard history. This actions sends or shares the clipboard contents to the remote device (as long as you have clipboard sharing turned on for that connection). You can then paste using the specified keyboard shortcut on the remote device after that.


Microsoft RDP app when using with a clipboard manager doesn't actively check the pasteboard for changes. I have found when using a any clipboard manager to be the workflow.

**Comment by p0deje** [comment]
The problem is not with copying the contents, the problem is that pasting directly from Maccy doesn't work.

**Comment by georgesnow** [comment]
Correct, and pasting directly into RDP if you use scan mode it you will get the errant v character. In the other referenced app is an a character and that's because of the method of keyboard events and specially RDP. Sorry, I am not trying suggest Unicode completely "fixes" this issue.

The point is when you are attempting to paste into RDP. It seems to be related to the keyboard events being used by maccy in relationship to the keyboard mode. 

For reference: 

There is specific post relating to the errant key

https://github.com/MacPass/MacPass/issues/1020

https://github.com/keepassxreboot/keepassxc/issues/3080

**Comment by p0deje** [comment]
Just to clarify, pasting works neither in scanmode nor unicode mode.
@georgesnow Thanks for referencing other issues, I wish I could find an example of when it works.

**Comment by georgesnow** [comment]
So I am not sure there is a way for Maccy to do it without doing something specific when RDP becomes the active app. 🤷‍♂️ 

I just checked the one other app I use. Screens by Eodvia, which is Remote Desktop client(VNC). That app has a specific feature that shares the clipboard and seems to work as expected. So it seems to be dependent on the rd app unfortunately.

**Comment by p0deje** [comment]
Yes, it indeed looks like RDP specific events handling and I'm not sure how to work it around.

**Comment by ibgbeny** [comment]
Have you tried sending Ctrl+V instead of sending Cmd + V?

Beni Ile

**Comment by p0deje** [comment]
I'm frankly out of ideas on what else to try. Would be happy if anyone chimes in?

**Comment by imleean** [comment]
It's more of a bug for Remote Desktop clients itself.
If you close the session you have and reopen it, it will works
For the copy & pastes to work, you have to close and reopen it from time to time.
The bug is not for Maccy.
When you reach the bug, you just simply can't paste anything.

**Comment by p0deje** [comment]
Thanks to FlyCut https://github.com/TermiT/Flycut/pull/18, I managed to make it work in "Scanmode" keyboard mode. I can't still make it work in "Unicode" mode but I hope it's already better. PRs that will make it work for both modes are more than welcome!
