### ISSUE TITLE
The ⌘+number shortcut is not easy to match the text, since margin is too large

### ISSUE THREAD

**Issue by divq** [p0deje/Maccy#366]
As in the screenshot, when it comes to the sixth or seventh item, I can hardly recognize which text the ⌘+number shortcut refers to, since it is too away from the text. Only by drawing a red line in the screenshot can you clearly find out the relation.

I think if you put ⌘+number shortcut to the left side so that it is close to the text item, it can be easier to recognize which refers to which

<img width="776" alt="2022-01-24 下午7 51 44" src="https://user-images.githubusercontent.com/78155141/150778230-9d1f1a53-6502-415c-b9fa-7d3f40f98e0e.png">

**Comment by p0deje** [comment]
Unfortunately, this is how NSMenu works - there is no way to place the shortcut on the left side.

In your particular case, it looks like there is some item with long text that causes this behavior. I can only recommend removing this item or decreasing the "Menu size" setting. This will make sure the item is not visible and doesn't force the whole menu to be so wide.
