### ISSUE TITLE
Unable to reset customisations

### ISSUE THREAD

**Issue by vivekkulthe** [p0deje/Maccy#367]
I made a lot of changes in the setting of the Maccy app and in that process, I disabled the preferences menu item. I am unable to open the preferences even after pressing CMD+, shortcut key.
I tried uninstalling and then reinstalling the Maccy app but the setting doesn't seem to get restored.
Is there any way I can reset the customized settings I made in the Maccy app?

**Comment by xxxAverageJoexxx** [comment]
Hi, I have the same problem, how did you solve it? Thanks and BR

**Comment by aesophor** [comment]
This should make Maccy show up in the menu bar again:
`defaults write org.p0deje.Maccy showInStatusBar -bool yes`
