### ISSUE TITLE
Option to strip style when pasting

### ISSUE THREAD

**Issue by Facens** [p0deje/Maccy#37]
It would be nice to have a separate pasting shortcut which strips styles when pasting.

**Comment by p0deje** [comment]
Can you give an example of this should be working? What do you mean by styles? Do you see this as a global option or you'd like to do this on a case-by-case basis?

**Comment by Facens** [comment]
@p0deje I currently use Flycut, which by default strips styles of anything that you paste (e.g. if you had a bold word in the text you copied, the bold will go away when pasting). While it's fair that this isn't the default, it's often handy to be able to quickly transform a rich text into plain text. I would see this so that, after opening Maccy, instead of pressing Enter you could press another key/combination to paste as plain text instead of rich text.

**Comment by michaelkar** [comment]
> It would be nice to have a separate pasting shortcut which strips styles when pasting.

Stripping style by default would be a nice option as well, I use [clipy](https://github.com/Clipy/Clipy) which supports it out of the box..

**Comment by p0deje** [comment]
@Facens @michaelkar It's currently an undocumented behavior, but Maccy already strips the styles. So, if now you copy styled text, open Maccy, and select copied item with ⌥ pressed, it will be pasted _without styles_. Is it not the behavior you're looking for?

**Comment by p0deje** [comment]
I'm going to close this for now as it's kinda working. Let me know if I should reopen this.

**Comment by sudo-suhas** [comment]
@p0deje I think the default behaviour was changed to include styles. Is there a way I can turn this off? Or is there a shortcut to paste without styles?

**Comment by p0deje** [comment]
@sudo-suhas Not at the moment. I've created #109 to track this. Please comment there about your use case so I know better how to implement this feature.
