### ISSUE TITLE
Shortcut to second to last copied item

### ISSUE THREAD

**Issue by dirchets** [p0deje/Maccy#374]
# Quickly pasting the second to last item

I would love the ability to quickly paste--_using a new shortcut such as CMD+ALT+V (just as an example!)_--the second to last copied item. I believe it would be very beneficial for my workflow.

### Reasons
I also think it would be a nice feature in general because:
- It would not be disruptive in any way for existing workflows (just an additive feature).
- Based on the principle of locality of reference (temporal, in this case), pasting the second to last copied items should reasonably be something done quite often.
- Having to open the menu just to quickly paste something that you know you copied a couple of seconds ago creates a small but noticeable workflow disruption that would be easily avoidable with an ad-hoc shortcut.

On this last point I will add, though this may not resonate with everybody, that the mental context switch associated with opening the menu is not insignificant for me. My mind has the tendency to wander and even a quick glance at something I copied earlier is sufficient to distract me a little bit, so if I could avoid it even just in the 20% of cases where I know I need to paste the last two items I copied (e.g. name and password, switching two lines of code, etc), it would be nice.

### Link to other issues
Lastly, I absolutely agree that going further than that, adding shortcuts to more items than the second to last (_such as what was suggested in #315_) could be overkill and would create problems.

### Example use case
Copying and pasting username and password:
- Copy username
- Copy password
- CMD+V to paste password
- CMD+ALT+V to paste username (instead of having to open a menu and select an item)

**Comment by p0deje** [comment]
In the next version of Maccy, there will be support for Shortcuts (as long as you run macOS 11+). So far it's very basic but allows to automate selecting/pasting the clipboard history item by its number like this.
<img width="862" alt="Screen Shot 2022-08-29 at 17 02 35" src="https://user-images.githubusercontent.com/665846/187319452-b64e2e2b-3d89-4fc2-a65f-2e23f6882907.png">

Any shortcut workflow can be called from menu bar, Dock or have a global shortcut.
