### ISSUE TITLE
Database timestamp format?

### ISSUE THREAD

**Issue by spencerc99** [p0deje/Maccy#375]
Hi! was just snooping around the database file to create an export of my copy paste data and was having trouble figuring out the format of the timestamps. Wondering if you could provide any color on that? 

For example a recent copy had a `ZLASTCOPIEDAT` value of `667100904.697671` which doesn't seem to parse in a way that makes sense for any standard parser (this also fails on python sqlite3's auto convert of timestamps to `datetime` objects). Thanks!

**Comment by p0deje** [comment]
I don't know how exactly Core Data stores "Date" format internally, but that's the type used by Maccy. This is what I found at https://developer.apple.com/documentation/coredata/handling_different_data_types_in_core_data:

> In a Core Data store, a Date attribute is a double value that represents a number of seconds since 1970. Using a variety of calendars, time zones, and locales, an app can convert a Date value to different date strings, or convert a date string to different Date values. When parsing a date string, configure the DateFormatter with the right calendar, time zone, and locale. Typically, if the string is generated by the current user, the user-perceived calendar, time zone, and locale will be the current system ones, so an app can use a default DateFormatter instance. In other cases, configure DateFormatter in the same way the app generated the string.
