### ISSUE TITLE
Discard duplicate clipboard items

### ISSUE THREAD

**Issue by SaschaLucius** [p0deje/Maccy#376]
I would like to have the option to discard duplicate items in my history.
It should be grouped with all other occurrences and the statistics:

- first copy time, last copy time and number of copies from the occurrence before should be updated if I'm copying the same content
- the previous entry in the history should be moved back to the top

**Comment by p0deje** [comment]
This is exactly how it works now. However, in some apps (e.g. Word) even if you copy the same text, it includes additional unique data. If you provide more examples of this behavior and which applications you use, I can take a look at them.

**Comment by SaschaLucius** [comment]
Hey,
thank you for your fast reply.
You are right, I have checked the behaviour and in Chrome it's all working fine.
Whats not working is: 

- Notes
- Slack
- Eclipse
- Mail

I'm on macOS Monterey 12.2.1 (21D62)

![image](https://user-images.githubusercontent.com/15611425/155949805-33f33217-beb2-4210-9b33-e8236555c727.png)

The easiest may to reproduce this for me is to hold the copy combination cmd+v. Or copy an item multiple times without pasting it. this generates most times two entries in my history. One with just 1 occurrence and a second one with multiple.

**Comment by p0deje** [comment]
Unfortunately this could happen to any formatted text. For example, in Notes.app there is additional `com.apple.notes.richtext` pasteboard type which includes new data every time you copy the same text. I'm not sure what would be the best way to work it around, should there be any.

**Comment by SaschaLucius** [comment]
if possible, my wish would be an checkbox "Ignore Formatting". This would solve my problem, since I anyways just want to have unformatted copy and paste with a clipboard Manager. Everything else works as it is with just the OS internal copy and paste mechanism. 
But I don't know how much effort this would mean in your app.

**Comment by fabifabulousity** [comment]
I don't know, how e.g. Raycast is doing it, but it seems that I do not have multiple entries with formatted text.

**Comment by tedw** [comment]
FWIW Figma also adds an entry each time I copy the exact same text 😕

**Comment by p0deje** [comment]
I think the reason Clipy doesn't have this issue is because it doesn't preserve formatting as extensively as Maccy does. Maccy should either support working with applications like PurePaste (see #429) or have an option to ignore formatting completely.

**Comment by p0deje** [comment]
I'm going to close this issue - let's consider that Pure Paste is a solution here and track the rest of the work in #429.
