### ISSUE TITLE
is there a way to respect private browsing mode?

### ISSUE THREAD

**Issue by hextion** [p0deje/Maccy#377]
Hello, thank you for awesome app!

I was wondering If there's a way to respect private browsing mode (for instance in Safari, Chrome, etc)?
I mean do not capture copied content while private browsing.
Because data can be sensitive.
But to keep capturing copied content while usual browsing.

I know there's "Turn off" flag in the app and I can enable it while private browsing.
But it's manual work.

And I can use "Ignore" tab, but the browser will be ignored at all.
But it's useful in case of Tor browser because it runs in private mode only.

**Comment by p0deje** [comment]
Unfortunately, there is no way to differentiate between content copied from the private and regular mode.
