### ISSUE TITLE
Why Maccy is paid in App Store?

### ISSUE THREAD

**Issue by NedkoHristov** [p0deje/Maccy#378]
I just found out Maccy and I really like it, but something got my attention - Maccy is free and we're even encouraged to fork it, inspect it, etc, but when I click on the `Get in App Store` the listed price there is 11 euro.

**Comment by p0deje** [comment]
Yes, it is paid in the App Store to support the development. See my thread for more details - https://twitter.com/p0deje/status/1354840386712203264.

Also happy to give away promo code if anyone wants.

**Comment by prenaux** [comment]
Imo its a good convenient way to help the author of utilities you use frequently. On the App Store its a one-click buy and you dont have to manage yet another license key.

**Comment by jfdnet** [comment]
I'd like to purchase one if there will be the iOS version and sync with the Mac version.
