### ISSUE TITLE
Could be able to store unlimited copies in the clipboard

### ISSUE THREAD

**Issue by ramakrushna137** [p0deje/Maccy#379]
Could there be an option to increase the limit to unlimited it's okay if it's a bit slow but I need all of my copied stuff 
also, my screenshots get auto copied to the clipboard not to finder so it will be nice feature 
also, keep a caution or note for people who want to enable the unlimited mode (ex slow and stuff like that)

**Comment by p0deje** [comment]
Duplicate of #310
