### ISSUE TITLE
[FEATURE REQUEST] Limit history setting

### ISSUE THREAD

**Issue by lashae** [p0deje/Maccy#38]
Hi,

I never reboot my Mac unless it is required , like a system update etc. That's why the clipboard history on Maccy grows enormously. A simple setting for history size, "Keep n clipboards" will be useful.

**Comment by p0deje** [comment]
You can limit history: https://github.com/p0deje/Maccy#history-size

**Comment by lashae** [comment]
@p0deje In deed the problem is as follows; I saw Maccy on ProductHunt and installed via maccy.app webpage. I was not aware of this repo and the README :-) 

Do you plan to add a simle preferences pane? That will improve UX dramatically.

**Comment by p0deje** [comment]
I've got plans for that, but not sure when I'll have time for that. Thanks!
