### ISSUE TITLE
not showing history

### ISSUE THREAD

**Issue by basanys** [p0deje/Maccy#380]
<img width="478" alt="Screenshot 2022-03-22 at 07 59 12" src="https://user-images.githubusercontent.com/65812993/159425592-5469bf88-a16c-4547-a2ef-0a54fbd1faff.png">
cmd + shift + c, copy and paste works, but history is not showing. I tried uninstalling several times, but didn't work. Am I doing it wrong?

**Comment by p0deje** [comment]
The history will only be saved while Maccy is running. It won't shown anything coped before.

**Comment by p0deje** [comment]
If it's grey - it means that Maccy is disabled. Just option+click the icon and it will enable again.
