### ISSUE TITLE
Can't see image preview

### ISSUE THREAD

**Issue by tony1az** [p0deje/Maccy#381]
when I open the main menu can't see the image previews 
1 and 2 were images!
![image](https://user-images.githubusercontent.com/32567205/159483303-075b7d3a-f923-4f79-b0e5-288db125bbef.png)

**Comment by p0deje** [comment]
This could happen if copied content has multiple types (images, text) and then Maccy chose the wrong representation. The best way to analyze it and fix the problem would be for you to send a copy of the Maccy database so I could investigate it (what pasteboard types are used). Could you do that? The database is stored in `$HOME/Library/Containers/org.p0deje.Maccy/Data/Library/Application Support/Maccy/Storage.sqlite`. Please make sure it doesn't have anything confidential or sensitive before uploading.

**Comment by tony1az** [comment]
Sorry, can't find this database

**Comment by p0deje** [comment]
Please run the following command in Terminal.app:

```
open "$HOME/Library/Containers/org.p0deje.Maccy/Data/Library/Application Support/Maccy"
```

**Comment by p0deje** [comment]
Hmm, it's empty - there are no records in the database 
<img width="1382" alt="Screen Shot 2022-03-23 at 09 01 32" src="https://user-images.githubusercontent.com/665846/159742939-43c9b230-3d9a-44d9-ab14-af186bc8fa53.png">

**Comment by tony1az** [comment]
![image](https://user-images.githubusercontent.com/32567205/159744731-0e515079-d978-4620-97e9-0399cd379ff6.png)
something strange)

**Comment by tony1az** [comment]
[Storage.sqlite.zip](https://github.com/p0deje/Maccy/files/8334684/Storage.sqlite.zip)
one more time

**Comment by p0deje** [comment]
Still nothing, I have a wild idea that you could be running an old version of Maccy before sandbox was introduced. Could you try checking the following folder?
```
open "$HOME/Library/Application Support/Maccy"
```

**Comment by p0deje** [comment]
1. What version of Maccy do you run? You can check in "About" section.
2. Could you try quitting Maccy and then uploading the whole directory `$HOME/Library/Containers/org.p0deje.Maccy/Data/Library/Application Support/Maccy`?

**Comment by tony1az** [comment]
Version 0.22.2 (11)

**Comment by p0deje** [comment]
Where did you copy the image from? I’m surprised to see that the pasteboard type is jpeg - I’ve always see tiff included even when copying jpg images.

Thank you,
Alex

**Comment by tony1az** [comment]
standard screenshot program on mac) I just have changed the file extension on jpeg

**Comment by tony1az** [comment]
have changed to png, and everything is ok

**Comment by p0deje** [comment]
> standard screenshot program on mac) I just have changed the file extension on jpeg

how do you do that? can you provide me exact steps to end up copying jpeg only?

**Comment by tony1az** [comment]
https://www.idownloadblog.com/2014/07/31/how-to-change-mac-screenshot-file-format/

**Comment by p0deje** [comment]
Thank you, I can now reproduce the problem and will fix it!

**Comment by tony1az** [comment]
You welcome) Thanks for your fast responses!

**Comment by ryan-efendy** [comment]
@p0deje thank you for the fix https://github.com/p0deje/Maccy/commit/e659f9ba7e0f2ea81dcad3ab182df53e195c99b6 any plan on releasing it? thanks 🙏

**Comment by tonymet** [comment]
@p0deje thank you for fixing this issue.  I had switched to use JPEG screenshots to save space in sending messages. great work.
