### ISSUE TITLE
where does Maccy store clipboard data?

### ISSUE THREAD

**Issue by mjtarr** [p0deje/Maccy#383]
Wondering if there is a way to specify where Maccy stores clipboard data - I use multiple systems and would love a common clipboard. Ideally I could just specify a file location (e.g., dropbox, box, iCloud Drive, etc) where clipboard data is kept so that the same clipboard would appear on all systems that serve up that location

**Comment by p0deje** [comment]
Maccy is a sandboxed application and its file access is limited to `$HOME/Library/Containers/org.p0deje.Maccy/Data`. At some point, I might add support for iCloud (see #182 and PRs are welcome too) but I don't think there is a way to use it with Dropbox/Box/Drive.

**Comment by p0deje** [comment]
Oh, the database itself is in `$HOME/Library/Containers/org.p0deje.Maccy/Data/Library/Application Support/Maccy/Storage.sqlite`
