### ISSUE TITLE
Can't restore to original size after image preview

### ISSUE THREAD

**Issue by LoroHeng** [p0deje/Maccy#385]
This screenshot is original size
<img width="384" alt="iShot2022-03-26 08 03 46" src="https://user-images.githubusercontent.com/35164494/160217458-ea36d815-86e7-40bf-a02e-5b4944bba934.png">
I took a screenshot and I can see the image preview
<img width="461" alt="iShot2022-03-26 08 01 26" src="https://user-images.githubusercontent.com/35164494/160217516-d1ba95b7-ac54-42f5-9910-baff942dab5e.png">
After I pressed Option-Command-Delete to clear all, it stays at that size
<img width="451" alt="iShot2022-03-26 08 03 04" src="https://user-images.githubusercontent.com/35164494/160217574-e8ed71d5-6853-4f4a-b8ca-543b706bcd61.png">

It happens occasionally and I can't reproduce it 100%. So in fact the first picture and the second picture are screenshots I took after this happened, in order to describe the issue.
Forgive my poor English.🤐

**Comment by p0deje** [comment]
The resizing of the menu is performed automatically by macOS. I agree it's not very convenient, but not so critical. I'll see if there is a way to force resize it.

**Comment by p0deje** [comment]
It looks like it's not possible to change the menu width while it's open, but the width should be correct on the next popup:

https://user-images.githubusercontent.com/665846/171914614-f10123de-294c-4a6c-91c9-e73e93051d1d.mov
