### ISSUE TITLE
Request: Display which Application the Copied Content Originated

### ISSUE THREAD

**Issue by ericpardee** [p0deje/Maccy#387]
I would be nice to have the ability to see which Application the copied content came from, i.e. Google Chrome.app. I find this feature helpful with Alfred's Clipboard Manager.

Two recommendations for implementations

1. Add line to the hover over (see `App: Google Chrome` in image)
<img width="545" alt="Maccy-App-Copy-Hover-Over" src="https://user-images.githubusercontent.com/2423679/160285797-f7d4acd3-08a5-4f29-9199-ee4a85bb9068.png">

2. Add Application Icon similar to Alfred (crud mock up)
<img width="302" alt="Maccy-App-Copy-Icons" src="https://user-images.githubusercontent.com/2423679/160286138-2aef2753-f034-4811-b827-a02867a9e14f.png">

**Comment by certainlyakey** [comment]
It would also be awesome include name of the app into search: if you type 'Chrome' all the recent items copied from there are included.

**Comment by p0deje** [comment]
In the next version, Maccy will store the source application and show its name in the tooltip.

![Screen Shot 2022-06-03 at 10 00 19](https://user-images.githubusercontent.com/665846/171911536-f862c8f5-c17c-4a3b-8397-45454352946b.jpg)

Let's start with this as I'm reluctant to show the application icon in the UI since it will no longer be that elegant. It won't be hard to add it though.

**Comment by NestorRV** [comment]
Now that this have been released, how can I enable it? Thanks!

**Comment by p0deje** [comment]
It's enabled by default:
<img width="193" alt="Screen Shot 2022-07-21 at 07 10 14" src="https://user-images.githubusercontent.com/665846/180234602-42bf5ddc-745e-4202-9b69-0e897eef699b.png">

**Comment by YunfangHou** [comment]
> In the next version, Maccy will store the source application and show its name in the tooltip.
> 
> ![Screen Shot 2022-06-03 at 10 00 19](https://user-images.githubusercontent.com/665846/171911536-f862c8f5-c17c-4a3b-8397-45454352946b.jpg)
> 
> Let's start with this as I'm reluctant to show the application icon in the UI since it will no longer be that elegant. It won't be hard to add it though.

Hi p0deje, may I ask if you plan to add the second proposal (source application icon)? I do wish this function.

**Comment by p0deje** [comment]
Fixed in https://github.com/p0deje/Maccy/commit/9d58afac7f6f77a83ae17c62ce361acd8c848465
