### ISSUE TITLE
Features of CopyQ?

### ISSUE THREAD

**Issue by createstars** [p0deje/Maccy#39]
I saw Maccy in ProductHunt although there was CopyQ which does a lot feature but buggy on macOS, it would be nice to implement some of the similar CopyQ features.

**Comment by p0deje** [comment]
Which features are you particularly interested in?

**Comment by createstars** [comment]
All of the features, I wish I could store links, attachments, references efficiently as a programmers and research purpose on the web. Some ideas you can think of Agenda iOS app too.

**Comment by p0deje** [comment]
I used CopyQ for sometime and I don't want to turn Maccy into it. Maccy is designed to be as lightweight as possible and is no replacement for full-featured manager as CopyQ. I personally wouldn't use any of its features. I guess there is no need to use Maccy if you want CopyQ exactly.
