### ISSUE TITLE
No clipboard copy at my MacBook pro, while working good at my mac mini

### ISSUE THREAD

**Issue by smart2k** [p0deje/Maccy#391]
Hi, Thanks for a good tool, 
I've tried this app for my MacBook pro for awhile, but couldn't make it working.
![image](https://user-images.githubusercontent.com/61654474/162551166-e6fbc214-2793-454d-8ff2-6c963ab89a0c.png)
The very same version of the app is just working great at my mac mini. 
Could you please let me know what kind of things I can check?

**Comment by p0deje** [comment]
Maybe you have it turned off? Check Preferences -> Advanced settings.

**Comment by smart2k** [comment]
Hi, Thanks to checking up this thread.
I didn't change anything at the preferences, is there anything possible to prevent reading my clipboard?
<img width="654" alt="image" src="https://user-images.githubusercontent.com/61654474/162837649-967b4861-7ceb-403d-be3d-70d96dc4d9d1.png">
<img width="674" alt="image" src="https://user-images.githubusercontent.com/61654474/162837676-202fc84c-a733-4b3b-9722-2a54288c01de.png">
<img width="613" alt="image" src="https://user-images.githubusercontent.com/61654474/162837711-bd83d4f8-2535-4ab0-99ac-23ae2db665e2.png">
<img width="554" alt="image" src="https://user-images.githubusercontent.com/61654474/162837741-3b4bcdd8-cbb8-4449-bb62-fa50b101ace3.png">
I'm using flycut due to this issue of maccy at my MBP, and it works well (but this app doesn't support image copy)

**Comment by p0deje** [comment]
There should be nothing that would prevent Maccy from reading the clipboard. Can you record a simple video showing how you copy text and it shows in Flycut but not in Maccy?

**Comment by p0deje** [comment]
Hrm, can you try reinstalling Maccy from scratch? Remove the app completely, run the following in Terminal.app:

```
rm -rf ~/Library/Containers/org.p0deje.Maccy
```

And then reinstall Maccy.

**Comment by smart2k** [comment]
Thanks it works after the remove and reinstalling! 
I tried before for the reinstall but at the time, no additional action at terminal with "rm -rf ~/Library/Containers/org.p0deje.Maccy".
Now it works perfectly, Thanks a lot!!

**Comment by p0deje** [comment]
Glad it worked!
