### ISSUE TITLE
Setting to clear current clipboard when clearing history

### ISSUE THREAD

**Issue by kotx** [p0deje/Maccy#392]
Sometimes I copy a password from somewhere and want to clear it- it would be nice to have a setting/button to clear the current clipboard, similar to Windows' built-in clipboard manager (Win+V).

**Comment by p0deje** [comment]
I don't have Windows, could you show screenshot and explain how it's implemented there?

**Comment by kotx** [comment]
<img width="380" alt="image" src="https://user-images.githubusercontent.com/33439542/164523631-b3999ecb-936b-4fcd-b16d-5f837cd27744.png">
Pressing the "clear all" button clears the current clipboard as well as all history.

**Comment by kotx** [comment]
@p0deje Just checking- does this make sense? I can provide more details if needed.

**Comment by p0deje** [comment]
I'm not 100% sure that's the best way to have it. What if I copied something, then sometime later I open Maccy, and clear its history. Now I don't have anything on the clipboard. Would I really want that? 

Introducing such side effects can be useful to some users but harmful to others. I wonder if there is any way to make it more obvious to the user.

**Comment by kotx** [comment]
Ah yeah, I was just suggesting a setting for it, for people to opt in if they wanted to- or, there can be a separate button to clear all? That might be better.

**Comment by p0deje** [comment]
I would happily merge PR adding this. There should be a new checkbox called "Clear the system clipboard too" in the "Advanced" preferences tab with the explanation that when enabled, clearing the history would also clear the current system clipboard.

**Comment by kotx** [comment]
Oh, whoops, seems this is resolved through that PR now? Thanks!
