### ISSUE TITLE
Expose Clipboard reading interval to perference?

### ISSUE THREAD

**Issue by shenlebantongying** [p0deje/Maccy#393]
I read this article from a senior of Microsoft, saying periodic tasks that have 1s or fewer intervals will eat a lot of resources.
https://devblogs.microsoft.com/oldnewthing/20220411-00/?p=106456

Recently, I noticed macOS doesn't have a clipboard notify API, then I realize something:
https://github.com/p0deje/Maccy/blob/06f90f657984cf339090f5e85be9a1a702fc11be/Maccy/Clipboard.swift#L10

In my Activity Monitor, the "12 hr power"(which I am not sure how mac measured it) of Maccy is 0.08, and the finder is 0.12. Maybe expose it to preference so that it can be reduced?

**Comment by p0deje** [comment]
Yes, this would be useful.

**Comment by dr-dimitru** [comment]
I'd make it 5 sec by default and a slider in the settings

**Comment by FabyoSK** [comment]
@p0deje I'm available to work on this

Where do we can add this slider?
And the default value for it should be 1, right?

**Comment by p0deje** [comment]
@FabyoSK Nice, thanks for volunteering!

1. I think it would be nice to use a number text field with a stepper to configure the timeout in milliseconds. The most recent example of using this is in https://github.com/p0deje/Maccy/commit/a451b23cfb964bc10c10e2992a277899e7bff7a5 - pretty much the same behavior and logic.
<img width="515" alt="Screenshot 2023-03-15 at 07 43 16" src="https://user-images.githubusercontent.com/665846/225345136-57415d89-2cd3-484b-9458-07b1bffe5e6d.png">

3. Let's keep it in the "Advanced" preferences tab.
4. Given it's in milliseconds, let's default to 1000.
5. Unlike the screenshot, please use the `toolTip` field for the description instead of a separate label with text explaining what this setting does.

**Comment by FabyoSK** [comment]
@p0deje You welcome.
I'm using Maccy for about a year and I really enjoy using it and now I can't just live without it, 
I'm learning Swift, so I would like to help with small features

**Comment by FabyoSK** [comment]
And for the translation...
I can get the right translation for Portuguese/English, but other languages I'm not fluent on them

**Comment by p0deje** [comment]
There is no Portuguese translation for Maccy, but if you're up to writing one, I can guide you on how to do that :)

For other languages, I usually just use Google translate. It should not be hard for this one. We can start with the following text in English:

1. Clipboard reading interval.
2. You can change how often Maccy should check the clipboard for new copies. The default is 1000 milliseconds which is optimal for most cases.

**Comment by p0deje** [comment]
Also, let's use the following boundaries:
1. No less than 100 milliseconds.
2. No bigger than 10000 milliseconds.

**Comment by p0deje** [comment]
@vincentjames501 What do you mean by the "hook"? The code lives in https://github.com/p0deje/Maccy/blob/master/Maccy/Clipboard.swift.

**Comment by FabyoSK** [comment]
@p0deje I was checking the advanced tab and it has just one column, the other tabs has two
should I refactor it to suport the two tabs? or should I made it using the current tab

<img width="660" alt="image" src="https://user-images.githubusercontent.com/64048314/227730872-409f6eb6-4b8a-4bd0-8183-c5f5ec5052ce.png">

**Comment by p0deje** [comment]
@FabyoSK You don't have to make it a grid, just have a number field + stepper and add a title after it, description below.

**Comment by FabyoSK** [comment]
I'll move forward with integrating it the code, let me know if you have any feedbacks about it

<img width="488" alt="image" src="https://user-images.githubusercontent.com/64048314/227782536-9d42ba6c-c42a-43dd-830e-e1b08d82091f.png">

**Comment by shenlebantongying** [comment]
Think. How about macOS expose its CPU scheduling handles so that we can tune it when doing different tasks?

I think we should not worry about 1% of battery.

Clipboard enhancers are popular among MacOS users. We can hope for a truly efficient solution from Apple when their "innovation" ideas run out and a better clipboard is on the top of their "next feature to absorb list".
