### ISSUE TITLE
Pin copies

### ISSUE THREAD

**Issue by FishBKK4** [p0deje/Maccy#398]
Hello, 

I'm not sure it's even there, but I was trying to pin certain copies I use all the time, so when I click "Clear" they would not be cleared. Instead of deleting 50 other copies 1 by 1 to make sure certain other copies stay on Maccy.

Not sure that makes sense... but that's the issue I have

Thanks

**Comment by Axenntio** [comment]
You can pin entries by using the combo ⌥+P while hover over an item.

After that ⌥+⌘+Delete will clear everything except items you've pinned

I hope this solve your issue

**Comment by FishBKK4** [comment]
> You can pin entries by using the combo ⌥+P while hover over an item.
> 
> After that ⌥+⌘+Delete will clear everything except items you've pinned
> 
> I hope this solve your issue

AMAZING, thank you very much that's exactly what I was looking for... I'm blown away

**Comment by p0deje** [comment]
@Axenntio Thank you the help and answering here!
