### ISSUE TITLE
[Feature Request] snippets/folders like Clipy

### ISSUE THREAD

**Issue by philihub** [p0deje/Maccy#40]
I love that somebody is actively developing a lightweight clip board manager! Thank you! 👍🏼

I would like to see two features Clipy features:
1. being able to delete individual items from the bezel
2. adding folders to the bottom to have certain clips always at hand

Cheers!

**Comment by p0deje** [comment]
Please see #34 for deleting individual entries. I'll keep this open for folders.

**Comment by p0deje** [comment]
Pinning individual items is available since 0.9.0. I don't plan to add folders support at this point.
