### ISSUE TITLE
How to delete an entry?

### ISSUE THREAD

**Issue by aximili** [p0deje/Maccy#400]
The readme says:
To delete the history item, press OPTION (⌥) + DELETE (⌫).

This doesn't work for me. I tried selecting the entry using both mouse (by hovering over it) and keyboard (using down arrow) and then pressing OPTION (⌥) + DELETE (⌫) but nothing happens.

(I've tried similar combinations, nothing worked. Clicking on the entry would paste the sensitive entry instead)

**Comment by aximili** [comment]
Solved - I found CopyQ, configured it to work like Maccy. You can easily delete (and even edit) individual entries there.

**Comment by p0deje** [comment]
If OPTION+DELETE doesn't work, it is a bug, but I cannot reproduce it.
