### ISSUE TITLE
Allow setting hotkey

### ISSUE THREAD

**Issue by ansidev** [p0deje/Maccy#401]
Problem:
- The hotkey to quickly paste the text into the editor is Cmd + {number}. This hotkey is conflicting with the VS Code hotkey.

As a user, I want to choose modifiers for the hot key dynamically such as:
- `Option`.
- `Cmd` + `Shift`.
- `Cmd` + `Option`.
- `Shift` + `Option`.
- `Cmd` + `Shift` + `Option`.

As a user, I want to be notified if the current Maccy hotkey is assigned by another application.

**Comment by p0deje** [comment]
How does it conflict with VS Code? To quickly paste, you need to popup Maccy first and then press the hotkey. The only globally available hotkey is the one to popup Maccy and it's fully configurable in the preferences.

**Comment by ansidev** [comment]
> How does it conflict with VS Code? To quickly paste, you need to popup Maccy first and then press the hotkey. The only globally available hotkey is the one to popup Maccy and it's fully configurable in the preferences.

Yes, I know that. I want the hotkey for quickly pasting to be a global hotkey, so for my case, I can press the hotkey to paste the text into the VS Code editor soon without opening the popup, choosing the copied item, and then press Enter to paste. That will save time as the item is one of the last 10 copied items.

**Comment by ansidev** [comment]
> How do you know exactly what's for example the 4th item in the history without opening popup?

I remember it.

For example:

1. Copy `Text 1`, `Text 1` will become the first item in the list which is assigned to the hotkey `Cmd` + `1`.
2. Copy `Text 2`, `Text 2` will become the first item in the list which is assigned to `Cmd` + `1`, `Text 1` will become the second one which is assigned to `Cmd` + `2`.

My expectation:
I want to paste `Text 1` by pressing `Cmd` + `1`.
I want to paste `Text 2` by pressing `Cmd` + `2`.

The problem: these hotkeys were registered by VS Code, so the pasting action does not triggered.

**Comment by p0deje** [comment]
Do you remember only 1-2 items or more?

**Comment by ansidev** [comment]
> Do you remember only 1-2 items or more?

It doesn't matter how many items I can remember, at the moment, there are only the first 9 items have assigned hotkey, it's enough or abundant.

The matters are:
- These hotkeys are not global hotkeys. => Make them as global hotkeys.
- Even if you solve the first issue, these hotkeys can be registered by another applications. => Allow user change them to solve the conflicting.

**Comment by p0deje** [comment]
Maccy doesn't register global hotkeys exactly for this reason - it should not interfere with other people's workflows or have collisions with other applications. This is the main reason why Maccy has just one global hotkey.

In any event, I think it's worth continuing the discussion either in #315 or #374.

**Comment by marcbrazil** [comment]
it should not interfere with other people's workflows or have collisions with other applications

this could be my choice no?
