### ISSUE TITLE
Ignore all events except for X.app

### ISSUE THREAD

**Issue by sanderdekoning** [p0deje/Maccy#402]
The documentation mentions it's possible to ignore all events with the following command:

`defaults write org.p0deje.Maccy ignoreEvents true # default is false`

Is it also possible to ignore all events **except** for one app? As in, I want to ignore all events except for events from Xcode.app

**Comment by p0deje** [comment]
It's not possible, but it seems like an interesting advanced feature that can be added to Maccy.

**Comment by sanderdekoning** [comment]
Awesome. Perhaps something as regex is an option to keep it flexible?

**Comment by p0deje** [comment]
Please explain how exactly would _you_ use it.

**Comment by sanderdekoning** [comment]
As a senior iOS developer myself I'll gladly contribute/review where I can

**Comment by p0deje** [comment]
Ok, that sounds like a possible implementation. However, I am curious to learn how would you use it in the real world? Do you have a use case? Can you tell me what apps would you use with Maccy and why having copies from other apps would be inconvenient?

**Comment by sanderdekoning** [comment]
Mainly peace of mind, for me personally I would really only like to have clipboard history as a fallback for when I'm working with text or code and somehow lost something; so I'd only whitelist my commonly used text editors such as xcode and vscode. Then I also don't have to remember setting up/updating Maccy when I start using new apps, especially if it's work related and can contain sensitive data

**Comment by p0deje** [comment]
I would be glad to merge PR adding this, I think the way to implement this would be to use the existing "Ignore" preferences pane with "Applications", but add an additional checkbox saying "Ignore all applications except listed". Enabling this checkbox would essentially invert the logic of ignoring apps (https://github.com/p0deje/Maccy/blob/master/Maccy/Clipboard.swift#L148-L150) and only save copies from these apps.

<img width="613" alt="Screen Shot 2022-07-31 at 15 23 31" src="https://user-images.githubusercontent.com/665846/182047652-bcb1a652-88a7-46a7-8a49-a36aed9e1c82.png">

**Comment by p0deje** [comment]
This feature will be available in the next version

<img width="472" alt="Screenshot 2023-02-26 at 12 59 51" src="https://user-images.githubusercontent.com/665846/221437003-e16e772b-4f15-4cfb-abb7-a2d7993421ae.png">

**Comment by sanderdekoning** [comment]
That's awesome @p0deje 👍 will test it soon 🙌
