### ISSUE TITLE
Launch at Login isn't working 

### ISSUE THREAD

**Issue by Jazzeus** [p0deje/Maccy#405]
Hi,
I love using Maccy, but unfortunately, Maccy won't launch after powered up my mac and logged in.
I have set the checkmark for "Launch after login", but it disappears after a reboot. My Mac Mini 2018 is currently running Monterey 12.3.1.
I would appreciate it if the problem is fixed.

**Comment by p0deje** [comment]
I cannot reproduce this issue. Are you running latest version of Maccy?

**Comment by Jazzeus** [comment]
I fixed it by moving Maccy back to the internal hard drive. Before that it was on an external hard drive.
Sorry for the confusion.
