### ISSUE TITLE
Show popup in the current focused monitor

### ISSUE THREAD

**Issue by FabyoSK** [p0deje/Maccy#410]
I have a two monitor setup, and I would like to see the Maccy popup in my current focused monitor,
this behavior occurs by default in spotlight

I would to implement this feature myself

If I didn't make myself clear I can record a video of it

**Comment by p0deje** [comment]
Could be related to #334. I'll merge PR adding this.

**Comment by FabyoSK** [comment]
I'm having issues running the code on Xcode

that's my log file
`yld[18333]: Library not loaded: @rpath/Sparkle.framework/Versions/A/Sparkle
  Referenced from: /Users/fsk/Library/Developer/Xcode/DerivedData/Maccy-anbhurwhijtczogcyctkzvsvisce/Build/Products/Debug/Maccy.app/Contents/MacOS/Maccy
  Reason: tried: '/Users/fsk/Library/Developer/Xcode/DerivedData/Maccy-anbhurwhijtczogcyctkzvsvisce/Build/Products/Debug/Sparkle.framework/Versions/A/Sparkle' (no such file), '/Users/fsk/Library/Developer/Xcode/DerivedData/Maccy-anbhurwhijtczogcyctkzvsvisce/Build/Products/Debug/PackageFrameworks/Sparkle.framework/Versions/A/Sparkle' (no such file), '/usr/lib/swift/Sparkle.framework/Versions/A/Sparkle' (no such file), '/Users/fsk/Library/Developer/Xcode/DerivedData/Maccy-anbhurwhijtczogcyctkzvsvisce/Build/Products/Debug/Maccy.app/Contents/MacOS/../Frameworks/Sparkle.framework/Versions/A/Sparkle' (code signature in <AF06CE6A-597E-3E22-ABA6-70678A1591FB> '/Users/fsk/Library/Developer/Xcode/DerivedData/Maccy-anbhurwhijtczogcyctkzvsvisce/Build/Products/Debug/Maccy.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/usr/lib/swift/Sparkle.framework/Versions/A/Sparkle' (no such file), '/Users/fsk/Library/Developer/Xcode/DerivedData/Maccy-anbhurwhijtczogcyctkzvsvisce/Build/Products/Debug/Maccy.app/Contents/MacOS/../Frameworks/Sparkle.framework/Versions/A/Sparkle' (code signature in <AF06CE6A-597E-3E22-ABA6-70678A1591FB> '/Users/fsk/Library/Developer/Xcode/DerivedData/Maccy-anbhurwhijtczogcyctkzvsvisce/Build/Products/Debug/Maccy.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/Library/Frameworks/Sparkle.framework/Versions/A/Sparkle' (no such file), '/System/Library/Frameworks/Sparkle.framework/Versions/A/Sparkle' (no such file)
(lldb) `

**Comment by p0deje** [comment]
"Screen Center" preference should do what you want. It was also improved in c4470dd62b76bce9b168fdb8cabbba443a529c50 and will be available in the next release. Please, re-open the issue if it's still present.
