### ISSUE TITLE
Paste Not Working

### ISSUE THREAD

**Issue by InspiredInk** [p0deje/Maccy#413]
Hi – 
I am trying to paste items from the clipboard into an MS Word document. I've tried using hotkeys and all of the following, and nothing seems to work.

To choose the history item and paste, press OPTION (⌥) + ENTER, or OPTION (⌥) + CLICK the item, or use OPTION (⌥) + n shortcut.

To choose the history item and paste without formatting, press OPTION (⌥) + SHIFT (⇧) + ENTER, or OPTION (⌥) + SHIFT (⇧) + CLICK the item, or use OPTION (⌥) + SHIFT (⇧) + n shortcut.

Please advise. Thank you.

**Comment by p0deje** [comment]
1. Does it work in other apps or only Word?
2. When Maccy tries pasting, it should show a dialog asking for "Accessibility" permissions to perform the paste. Do you remember seeing and accepting it?
3. Can you double-check that Maccy is present in **System Preferences / Security & Privacy / Privacy / Accessibility**? If it's not there, please add it by clicking on the "+" button and selecting Maccy.
4. If nothing works after the previous step, please share the screenshot of the "Preferences" window of Maccy.

**Comment by BowandError** [comment]
Just as a heads up, when the original dialog asking for "Accessibility" permissions popped up, I accepted and it took me to System Preferences, but Maccy was not automatically populated into the existing list. Clicking on the "+" button and selecting Maccy.app in my applications folder did add it though, and it works fine after that.

For reference, I'm using Monterey 12.0.12 (21A559) on a 2020 M1 MacBook Air. Thanks for the great utility, p0deje!
