### ISSUE TITLE
[Feature Request] HEX-color preview

### ISSUE THREAD

**Issue by philihub** [p0deje/Maccy#42]
I am often copy/pasting color codes and it is really helpful to see which one is which.

**Comment by p0deje** [comment]
Now it would try to guess the color for HEX value and draw a small image. What do you think about this?

![Screenshot 2019-09-06 at 15 25 24 ](https://user-images.githubusercontent.com/665846/64417280-9db6ad00-d0ba-11e9-95a5-0f4c46a6f889.png)

**Comment by philihub** [comment]
Looks very good!

**Comment by p0deje** [comment]
Great, will be released in a new version.

**Comment by p0deje** [comment]
@chilikasha There is no setting, but I'm open to merge a PR adding it.

**Comment by chilikasha** [comment]
@p0deje I will be grateful
