### ISSUE TITLE
Half a day of clipboard history lost

### ISSUE THREAD

**Issue by valynor** [p0deje/Maccy#422]
0.22.2 on macOS 12.4, history length 100 items

When I booted my mac today I noticed that about half a day of the latest clipboard history was gone. The newest entry was from sometime yesterday afternoon. 

I'm 100% positive that I did NOT disable Maccy accidentally, I remember copying something from the history a short time before I powered down the computer (no unusual things happened when powering down/rebooting). 
When I wanted to copy the same entry from the history today I noticed the item together with approx. half a day of other items (about 10-20) were missing. The only notable thing was that the first (latest) item in the list had some emojis in it. 

I'm sorry that I can't give you any more specific information about this but there is definitely a bug of some kind somewhere ...

If something like this happens again, is the history stored somewhere in the filesystem where I can grab it from a time machine backup?

**Comment by p0deje** [comment]
I'm currently reworking the storage mechanism - right now it keeps new entries in memory and saves to the filesystem on Maccy quit. I'm trying to make it save to filesystem periodically.

Sorry you've lost your data. Unfortunately, Time Machine is unlikely to help, but you can check the contents of `~/Library/Containers/org.p0deje.Maccy/` folder.

**Comment by valynor** [comment]
Thanks for the reply. 
The ~/Library/Containers/org.p0deje.Maccy/ folder does not exist in my filesystem, though.

**Comment by p0deje** [comment]
Going to close this for now and track the storage memory rework in #384
