### ISSUE TITLE
Time refresh function

### ISSUE THREAD

**Issue by Jerome-lara** [p0deje/Maccy#427]
Limit 200 history records
Records that exceed the limit for the longest time will be deleted

Is it possible to refresh the time of the record when it is used again?

**Comment by Jerome-lara** [comment]
For example, the longest history record is ID: 200
When it is used again, the ID is refreshed to 1
This way it won't be deleted at the end when new history is added

**Comment by Jerome-lara** [comment]
I think this will be easier to use than the fixed way,
And re paste would have been sorted to the top, and should not be cleared at the end.

**Comment by Jerome-lara** [comment]
> There is no way to do it at the moment in Maccy, though it should be easy to change. Can you explain why would you need to keep an old item in history even given it's unpinned?

I think this will be easier to use than the fixed way,
And re paste would have been sorted to the top, and should not be cleared at the end.
@p0deje

**Comment by p0deje** [comment]
Have you tried using "Time of last copy" in Preferences -> Storage -> Sort by?

**Comment by Jerome-lara** [comment]
> Have you tried using "Time of last copy" in Preferences -> Storage -> Sort by?

Yes, this is the default setting,
Although it reappears in the front row, if there is a new item added, it will still be cleared at the end.

**Comment by p0deje** [comment]
Ok, I'll implement the new logic so that clearing of exceeded items respects the "Sory by" setting.
