### ISSUE TITLE
[Feature Request] When hovering over truncated snippet show longer version

### ISSUE THREAD

**Issue by tenitski** [p0deje/Maccy#43]
When hovering over truncated snippet show a tooltip or something with a longer version of the text eg how ClipMenu  does it
<img width="637" alt="image" src="https://user-images.githubusercontent.com/1719919/64482519-780ade80-d247-11e9-8231-c2e05b078208.png">

**Comment by p0deje** [comment]
This is already done in #31 and will be available in the next release.
