### ISSUE TITLE
Maccy won't open on MacBook Pro M1

### ISSUE THREAD

**Issue by cikabo** [p0deje/Maccy#432]
I open the app, but it never opens - please find the Console log attached.

[maccy crash report.log](https://github.com/p0deje/Maccy/files/9121203/maccy.crash.report.log)

**Comment by p0deje** [comment]
Is it happening constantly? I just did a fresh install on my M1 MacBook Pro and everything loads fine. The crash report is not very helpful too as it is not symbolicated but I'll investigate.

**Comment by p0deje** [comment]
Looks like your database was somehow corrupted. Please remove it completely and try reinstalling Maccy. To remove database and preferences, run the following in Terminal.app:

```sh
rm -r ~/Library/Containers/org.p0deje.Maccy
rm -r "~/Library/Application Scripts/org.p0deje.Maccy"
```

if the issue persists after that, please reopen this ticket.

**Comment by cikabo** [comment]
Yes, it is constantly crashing. I also tried deleting and installing via
homebrew.
It’s probably worth mentioning that I migrated my account from an intel
based MacBook Pro.
Is there anything else I can try?

Alex Rodionov ***@***.***> schrieb am Fr. 15. Juli 2022 um
17:34:

**Comment by p0deje** [comment]
If you install via homebrew, can you try reinstalling wth `brew reinstall --zap maccy`?

**Comment by cikabo** [comment]
Your suggestion to clear the database fixed the issue. Thanks a lot!
