### ISSUE TITLE
Docs: The feature to option-click the menubar icon is not mentioned in Preferences > Advanced > Turn off

### ISSUE THREAD

**Issue by beausmith** [p0deje/Maccy#436]
(First of all… Fantastic app! Thank you! 😄  I was a Flycut user and I'm now on an M1 and want to avoid using Rosetta.)

### Problem 
I was confused for some time as to why Maccy stopped working, then I learned about the feature to option-click the menubar icon after searching through the GH issues.

### Request
Please update the text under `Preferences > Advanced > Turn off` to mention the behavior when there is an option-click on the the menubar icon.

<img width="467" alt="image" src="https://user-images.githubusercontent.com/28444/180635192-97a1817b-30e2-403e-96ca-a1f1290b00c2.png">

### Related Question

When the Maccy preferences window is open to the Advanced tab, and the menubar icon is option-clicked, the checkbox for "Turn off" does not toggle, but seems like it should? 🤷 

https://user-images.githubusercontent.com/28444/180635670-5cc11d13-1e0d-4fd1-9f9a-ec5e4226564c.mov

**Comment by p0deje** [comment]
> Please update the text under Preferences > Advanced > Turn off to mention the behavior when there is an option-click on the the menubar icon.

I will, just need to find a way to translate it into 13 languages.

> When the Maccy preferences window is open to the Advanced tab, and the menubar icon is option-clicked, the checkbox for "Turn off" does not toggle, but seems like it should? 🤷

It doesn't check off immediately, but it will if you re-open preferences window.
