### ISSUE TITLE
What's special about `p` and `q`?

### ISSUE THREAD

**Issue by jsoref** [p0deje/Maccy#438]
In reviewing the code, I ran across this, and I can't see any obvious reason for it:

https://github.com/p0deje/Maccy/blob/366555b0459572d69c990f23877788be4857bb16/Maccy/Storage.xcdatamodeld/Storage.xcdatamodel/contents#L8

**Comment by p0deje** [comment]
- q is for quit
- p is for pin

**Comment by jsoref** [comment]
Would you be amenable to a comment explaining this?

**Comment by p0deje** [comment]
I am not sure how to add comments to Core Data models.
