### ISSUE TITLE
[Feature Request] Support images

### ISSUE THREAD

**Issue by tenitski** [p0deje/Maccy#44]
Support coping, viewing and pasting images eg as ClipMenu does:

<img width="375" alt="image" src="https://user-images.githubusercontent.com/1719919/64482545-d59f2b00-d247-11e9-9c4c-d13f8b484eb6.png">

**Comment by afeblot** [comment]
and if not supporting image, at least fix the following bug:
Currently, each time I copy an image, the latest item is removed from the clipboard history.

**Comment by georgesnow** [comment]
yes this would be awesome!

**Comment by HugoDF** [comment]
@p0deje any idea how one would go about implementing this?

**Comment by p0deje** [comment]
First of all, Maccy currently listens for plain text copies, so it needs to start supporting images in `NSPasteboard`. Next, it needs to implement some storage mechanism for images (I assume `UserDefaults` support that). Lastly, it needs to present the copied image using `NSMenuItem` image methods.

@HugoDF Are you willing to submit PR for that?

**Comment by HugoDF** [comment]
@p0deje I'll have a go and let you know if I hit any issues

**Comment by chaucerbao** [comment]
I really like Maccy's focused, no-nonsense approach. However, I do find myself wishing I could refer back to older screenshots quite often. So I'm looking forward to this enhancement!

**Comment by dreness** [comment]
> First of all, Maccy currently listens for plain text copies, so it needs to start supporting images in `NSPasteboard`. Next, it needs to implement some storage mechanism for images (I assume `UserDefaults` support that).

Consider avoiding use of UserDefaults for storing user data other than preferences. The preferences system doesn't have any hard size limits (except on tvOS), but even so it isn't really intended for potentially large amounts of data. [CoreData](https://developer.apple.com/documentation/coredata) is likely a better choice for this use case (and probably for text storage as well).

**Comment by p0deje** [comment]
<img width="420" alt="Screen Shot 2020-03-14 at 14 57 32" src="https://user-images.githubusercontent.com/665846/76688555-2ed78500-6604-11ea-8a4e-2780b7740619.png">

How does that look? Are the images too big or too small?

**Comment by afeblot** [comment]
Ohh, awesome :-)
I would rather have them smaller. Like 1,5 times smaller. Just my own personal taste.
You may want to provide an option for the size :-)

**Comment by FernandoMiguel** [comment]
i love this.
agree it should be smaller

**Comment by p0deje** [comment]
<img width="332" alt="Screen Shot 2020-03-14 at 15 28 32" src="https://user-images.githubusercontent.com/665846/76689008-7829d380-6608-11ea-9770-6cd405a6a10a.png">

@afeblot @FernandoMiguel Like this?

**Comment by afeblot** [comment]
yeah, that could be it. Or even a bit smaller.

**Comment by alexjousse** [comment]
It looks great!!

**Comment by FernandoMiguel** [comment]
looks better.
guess i'll have to see it on my screen to have a better perception.

can this be customised? 
a env var to set the number of pixels?

**Comment by HugoDF** [comment]
Never got round to, this looks awesome

**Comment by p0deje** [comment]
This will be customizable like

```
$ defaults write org.p0deje.Maccy imageMaxHeight 15
```

Default is 40

**Comment by p0deje** [comment]
Added in 0.9.0

**Comment by HugoDF** [comment]
Amazing

**Comment by mambusskruj** [comment]
Hi!
How can I disable image support? I want to see list with text items only.

**Comment by p0deje** [comment]
@mambusskruj You can't at the moment. Feel free to submit a feature request. Also, you can set the max height so that images look like other text items:

```
defaults write org.p0deje.Maccy imageMaxHeight 16
```
