### ISSUE TITLE
Bug: Removing a pin's key hides it from the pins list

### ISSUE THREAD

**Issue by noamnelke** [p0deje/Maccy#443]
### Steps to reproduce:
1. Pin an entry
2. Open Preferences and click on Pins
3. Double click on the key for the entry you just pinned
4. Delete the character and click outside the textbox to confirm

### Observed behavior
The entry disappears. The item is still pinned (when looking at the entry list) and it even retains its title, but if you want to add a key to it, you can't.

### Expected behavior
I expect pinned items with no key to still be in the list in preferences.

### Workaround
Unpin and re-pin the item. A new random key is assigned to it and it appears in the list. Title is retained.

**Comment by p0deje** [comment]
It actually unpins an item though the history list doesn't pick it up automatically and still shows it as pinned. I'm going to either disallow removing the pin key in preferences or make sure the history list is updated when it's removed.

**Comment by noamnelke** [comment]
Suggestion to make it clear to the user:

When trying to delete the key present a popup "Removing the key will unpin this item, are you sure? [Unpin] [Keep key]".
