### ISSUE TITLE
Feature Request: Paste Multiple Items

### ISSUE THREAD

**Issue by qazzym** [p0deje/Maccy#444]
It would be super helpful to be able to paste multiple selections at once. 

There are 2 implementations I have come across that achieve this in slightly different ways. With Alfred you are able to append items to a previous clipboard entry and paste everything all at once. Another implementation is the app Paste that allows you to just select multiple clipboard entries in its UI and again paste them all at once. 

Thank you.

**Comment by p0deje** [comment]
Please see the discussion in #239 and share your use case. I have made an initial implementation but it doesn't seem to cover all cases.
