### ISSUE TITLE
Couldn't locate perferences

### ISSUE THREAD

**Issue by imleean** [p0deje/Maccy#445]
Can't locate perference for further action.
Neither with menu or keyboard shourcut.
<img width="698" alt="image" src="https://user-images.githubusercontent.com/47962427/184839665-c23b43cd-42f0-4527-a048-7fb99a2fbab4.png">
Only those list was find, no perfrerence button, and alson cmd+, didn't work.

**Comment by p0deje** [comment]
Please share the output of running `defaults read org.p0deje.Maccy` in Terminal.app.

**Comment by dr-dimitru** [comment]
Just press <kbd>⌘</kbd> + <kbd>,</kbd> when Maccy is open

**Comment by imleean** [comment]
{
    "KeyboardShortcuts_popup" = "{\\"carbonModifiers\\":768,\\"carbonKeyCode\\":8}";
    "NSStatusItem Preferred Position Item-0" = 517;
    "NSWindow Frame com.sindresorhus.Preferences.FrameAutosaveName" = "527 154 634 736 0 0 2560 1415 ";
    SUEnableAutomaticChecks = 0;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2021-05-07 08:07:58 +0000";
    SUSendProfileInfo = 0;
    enabledPasteboardTypes =     (
        "public.tiff",
        "public.utf8-plain-text",
        "public.file-url",
        "public.png"
    );
    hideFooter = 1;
    history = {length = 42, bytes = 0x62706c69 73743030 a0080000 00000000 ... 00000000 00000009 };
    historySize = 99;
    ignoredPasteboardTypes =     (
        "com.typeit4me.clipping",
        "net.antelle.keeweb",
        "Pasteboard generator type",
        "de.petermaurer.TransientPasteboardType",
        "com.agilebits.onepassword"
    );
    imageMaxHeight = 20;
    migrations =     {
        "2020-02-22-history-item-add-copied-at" = 1;
        "2020-02-22-history-item-add-number-of-copies" = 1;
        "2020-04-18-switch-storage-to-core-data" = 1;
        "2020-04-25-allow-custom-ignored-types" = 1;
        "2020-06-19-use-keyboardshortcuts" = 1;
        "2020-09-01-ignore-keeweb" = 1;
        "2021-02-20-allow-to-customize-supported-types" = 1;
    };
    pasteByDefault = 1;
    playSounds = 1;
    showRecentCopyInMenuBar = 1;
}

Please find the log as here.

The image should shows with Menu option, but it didn't.

no footer disabled, and restarting didn't work, either the Mac or the App.

**Comment by imleean** [comment]
CMD + , have been tried, it didn't work.

**Comment by imleean** [comment]
![image](https://user-images.githubusercontent.com/47962427/186069583-a43f69ea-7d37-475d-9e71-52dd4de8c3d9.png)
The park in red didn't shows up.

**Comment by p0deje** [comment]
You actually has footer disabled, run this in Terminal.app and try again:

```
defaults delete org.p0deje.Maccy hideFooter
```

**Comment by imleean** [comment]
It's working prefectly, thx~
