### ISSUE TITLE
Screenshots not recorded in new version

### ISSUE THREAD

**Issue by shysilva** [p0deje/Maccy#451]
Hello, I would like to ask if the new version no longer supports saving screenshots automatically? I am able to access texts from the menu but I cannot save screenshots on Maccy. The issue only appeared today, which is when I updated the app. Many thanks.

**Comment by p0deje** [comment]
Can you provide more details? For instance, please run `default read org.p0deje.Maccy` in Terminal.app and paste output here.

**Comment by shysilva** [comment]
command not found: default

**Comment by shysilva** [comment]
That is the only output line after copy and pasting your code to the Terminal app. I also realised after not using it for a few days, with the app running in the background, the app suddenly worked alright until I cleared the history of all stored items, which was the same action I did last time which then lead to all the issues. Another issue I have found alongside the screenshot issue is that the text does not automatically paste using the command + number button after opening up the app selection menu.

**Comment by p0deje** [comment]
> command not found: default

My bad, it should be `defaults`.

> Another issue I have found alongside the screenshot issue is that the text does not automatically paste using the command + number button after opening up the app selection menu.

Can you please enable "Paste automatically" in Maccy preferences and try again?

**Comment by shysilva** [comment]
defaults read org.p0deje.Maccy
{
    "KeyboardShortcuts_popup" = "{\\"carbonModifiers\\":768,\\"carbonKeyCode\\":8}";
    "NSStatusItem Preferred Position Item-0" = 680;
    "NSWindow Frame SUStatusFrame" = "760 731 400 134 0 0 1920 1080 ";
    "NSWindow Frame SUUpdateAlert" = "650 511 620 398 0 0 1920 1080 ";
    "NSWindow Frame com.sindresorhus.Preferences.FrameAutosaveName" = "709 411 542 461 0 0 1920 1080 ";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2022-09-08 09:47:50 +0000";
    SUSendProfileInfo = 0;
    SUUpdateGroupIdentifier = 1349365633;
    WebKitDefaultFontSize = 13;
    WebKitJavaEnabled = 0;
    WebKitJavaScriptEnabled = 0;
    WebKitPluginsEnabled = 0;
    WebKitStandardFont = "-apple-system-font";
    WebKitUserStyleSheetEnabledPreferenceKey = 1;
    WebKitUserStyleSheetLocationPreferenceKey = "/Applications/Maccy.app/Contents/Frameworks/Sparkle.framework/Resources/ReleaseNotesColorStyle.css";
    enabledPasteboardTypes =     (
        "public.tiff",
        "public.file-url",
        "public.png",
        "public.utf8-plain-text"
    );
    history = {length = 42, bytes = 0x62706c69 73743030 a0080000 00000000 ... 00000000 00000009 };
    historySize = 100;
    ignoreEvents = 0;
    ignoredPasteboardTypes =     (
        "com.agilebits.onepassword",
        "Pasteboard generator type",
        "com.typeit4me.clipping",
        "de.petermaurer.TransientPasteboardType",
        "net.antelle.keeweb"
    );
    migrations =     {
        "2020-02-22-history-item-add-copied-at" = 1;
        "2020-02-22-history-item-add-number-of-copies" = 1;
        "2020-04-18-switch-storage-to-core-data" = 1;
        "2020-04-25-allow-custom-ignored-types" = 1;
        "2020-06-19-use-keyboardshortcuts" = 1;
        "2020-09-01-ignore-keeweb" = 1;
        "2021-02-20-allow-to-customize-supported-types" = 1;
        "2021-06-28-add-title-to-history-item" = 1;
        "2021-10-16-remove-dynamic-pasteboard-types" = 1;
        "2022-08-01-rename-suppress-clear-alert" = 1;
    };
    pasteByDefault = 1;
    pinTo = top;
    popupPosition = statusItem;
    removeFormattingByDefault = 0;
}

**Comment by shysilva** [comment]
After a day of not using, the app managed to show the screenshots and photos I had copied a few days earlier. 
The automatic pasting issue has been solved. However, recently screenshotted items still doesn't show in the menu.

**Comment by p0deje** [comment]
When you make a screenshot using Cmd+Shift+4, it’s never copied to the clipboard so it won’t end up in Maccy. Can you try taking a screenshot using Cmd+Control+Shift+4 (note additional Control key) and see if it shows in Maccy?

**Comment by shysilva** [comment]
Cmd control shift 4 does not take a screenshot, and even shift command 3 does not let the screenshot show in the maccy menu

**Comment by p0deje** [comment]
Cmd control shift 4 should be taking, maybe something is different in your configuration. From https://support.apple.com/en-us/HT201361:

> To copy a screenshot to the Clipboard, press and hold the Control key while you take the screenshot. You can then paste the screenshot somewhere else. Or use [Universal Clipboard](https://support.apple.com/kb/HT209460) to paste it on another Apple device.

**Comment by shysilva** [comment]
The cmd control shift 4 does not take a partial screenshot, only shift cmd 4 does the screenshot. Same goes to shift cmd 3 if I press the control button alongside the three buttons it will not take the screenshot as well, nor does the screenshot show on maccy.

**Comment by p0deje** [comment]
Do you have the shortcuts enabled in macOS System Preferences -> Keyboard -> Keyboard Shortcuts -> Screenshots? I have it like this (but the screenshot is from the upcoming macOS Ventura, it would probably look different for you):
<img width="827" alt="Screenshot 2022-09-13 at 10 01 03" src="https://user-images.githubusercontent.com/665846/189962772-0ee8cb5d-5ebb-40d8-bb6d-4913f974ca00.png">

**Comment by p0deje** [comment]
@shysilva Could you try changing the shortcuts and see if it helps?

**Comment by p0deje** [comment]
Closing since no response.
