### ISSUE TITLE
Allow width of the clipboard window to be set

### ISSUE THREAD

**Issue by cocoonkid** [p0deje/Maccy#458]
Allow width of the clipboard window to be set

Thanks for consideration

**Comment by p0deje** [comment]
Why?

**Comment by cocoonkid** [comment]
@p0deje it's just a visual thing.

it would be very helpful too be able to set the width higher for high resolution displays especially.

I'd like to see more of the clipboard contents for long texts.

Also it is suitable to adjust to all my other applications where I have set a bigger width than the defaults.

Thank you for consideration.
