### ISSUE TITLE
Export feature?

### ISSUE THREAD

**Issue by juanito-22** [p0deje/Maccy#459]
Can you create an export feature for Maccy? There may not be much need but I'm toggling between Mac OS versions while beta testing and I'd like to duplicate my copied items.

**Comment by p0deje** [comment]
The storage is simply an SQLite database, you can copy it from "~/Library/Containers/org.p0deje.Maccy/Data/Library/Application Support/Maccy/" folder.

**Comment by ss186222** [comment]
Why not just offer this? 

For me it was, 

```
/Users/{USER}/Library/Containers/org.p0deje.Maccy/Data/Library/Application Support/Maccy/Storage.sqlite'
```
