### ISSUE TITLE
[Feature request] Classification of most used items

### ISSUE THREAD

**Issue by iJaack** [p0deje/Maccy#46]
I think it will be very useful to show the **most used and copied items first**, and then the others, instead of showing them just in chronological order.

**Comment by p0deje** [comment]
What would you consider "most used or copied"? Would it count:

1. How often the item was copied?
2. How often the item was selected inside Maccy?
3. Both?

**Comment by iJaack** [comment]
I consider the items that are copied most often, I think It would be better.

**Comment by p0deje** [comment]
Why have you close this?

**Comment by iJaack** [comment]
sorry, I t

**Comment by p0deje** [comment]
Since 0.9.0 you can now use 

```
defaults write org.p0deje.Maccy sortBy numberOfCopies
```
