### ISSUE TITLE
Bug: Crashes after searching in copy list

### ISSUE THREAD

**Issue by Drugsosos** [p0deje/Maccy#461]
### Steps to reproduce:
1. Open search list
2. Start typing

### Actual results:
- Maccy process is no longer exists (can't find it w/ `ps -A`)

> IDK, maybe I did something stupid but it wasn't behaving like that before the update (on **MacOS 12.5**)

### Notes:
- **MacOS 12.6, MacBook Air M1**
- I had screenshots in the list, maybe it's the cause

EDIT:
Actually I tried to clear search results and the problem was gone

**Comment by p0deje** [comment]
What happened is likely you copied some extravagant which Maccy failed to properly parse. Even though the search should be safe from crashes, there might be some subtle bug that caused this. It would be useful to inspect your storage and see what record causes this, but I guess it's no longer possible now that it's cleared.

Please re-open if you see this happening again and attach `"~/Library/Containers/org.p0deje.Maccy/Data/Library/Application Support/Maccy//Storage.sqlite"` to the issue (but please make sure there are no confidential information there).
