### ISSUE TITLE
Paste fails if standard MacOS Paste keyboard shortcut (command-V) is remapped

### ISSUE THREAD

**Issue by easp** [p0deje/Maccy#462]
When I have a lot of cutting and pasting to do I use the Keyboard preferences to remap the shortcut key for Edit > Paste from command-V to a single function key. However, when I do this, pasting from Maccy fails and I have to hit my custom shortcut function key to actually complete the paste into the app I'm using (specifically Edge).

It seems that Maccy is pasting by putting an item in the paste board and then emulating the keypress. Perhaps there is a more direct way for it to execute the paste? Or, perhaps it can discover the current OS shortcut.

Ideally this wouldn't be Maccy's problem. I'd be able to keep the command-v shortcut and add another one to it, but that doesn't seem to be possible, or if it is, I haven't figured out how to do it.

**Comment by p0deje** [comment]
Oh, I had no idea it was possible to remap the paste keyboard shortcut. I will search for a way to work this around in Maccy. Thank you for reporting!

**Comment by p0deje** [comment]
My initial idea was to add the "Edit" / "Paste" main menu item and then fetch the paste shortcut from it. It works fine, but whenever I override it with custom shortcut, it is not updated until I rebuild the whole app.

**Comment by p0deje** [comment]
The pushed commit makes it work fine when changing shortcuts but not when the custom shortcut is removed.

**Comment by p0deje** [comment]
Hmm, seems to work now without any changes. I'm going to spend some time testing it and unless I see problems, I'll release in the next version.

**Comment by easp** [comment]
Cool, thanks!
