### ISSUE TITLE
Allow to save information permanently.

### ISSUE THREAD

**Issue by joaogdemacedo** [p0deje/Maccy#463]
Sometimes I need to copy and paste the same thing, over and over again, e.g. my personal info, address, email, etc.
It would be cool to have the possibility to create folders with info to copy and paste instantly over time and never lose that information.

For example to copy my email:
1 - With a shortcut or in the menu bar open my created folders;
2 - Go to my "Personal info" folder I have created;
3 - Copy my email;

**Comment by p0deje** [comment]
You can pin items using Option+P - it will be stored permanently.
