### ISSUE TITLE
Can't search when enter password

### ISSUE THREAD

**Issue by ghost** [p0deje/Maccy#464]
Search not work when cursor in password box.

<img width="484" alt="image" src="https://user-images.githubusercontent.com/9608276/191229618-58185555-40a5-4d74-918e-243eea07bdaa.png">

### Mac

Apple M1 Pro
12.6

### Maccy

<img width="284" alt="image" src="https://user-images.githubusercontent.com/9608276/191230706-3347c411-5381-47f6-b571-b38bb34aaf94.png">

**Comment by p0deje** [comment]
I don’t follow, can you provide exact steps, expected and actual behavior to reproduce the issue?

**Comment by shineshane** [comment]
![maccy_cant_search_issue](https://user-images.githubusercontent.com/9608276/191645080-da1eab4c-c8ad-4271-8c75-8bc4310b44b3.gif)

In account box, search works normal, but not work in password box.

Same problem in safari and chrome.

Same problem when i sign in google, github and other systems.

**Comment by p0deje** [comment]
Oh wow, this is totally unexpected. I can reproduce the issue and will investigate further.

**Comment by p0deje** [comment]
Should be fixed in e3bacbbd56b0525de437548964295db76916faa5
