### ISSUE TITLE
Ability to paste on enter?

### ISSUE THREAD

**Issue by anwarulislam** [p0deje/Maccy#465]
I can't paste an old item just by entering that or selecting that item by mouse. It's just shown on top and ready to be pasted by default shortcut. Why not pasting it when I select the item or press enter on that item?

**Comment by p0deje** [comment]
You just need to enable “Paste automatically” in Maccy preferences.

**Comment by anwarulislam** [comment]
Hi, I enabled that option but it was not working. 

I'm using MacBook Pro 14" with M1 Pro

**Comment by p0deje** [comment]
Make sure you have added "Maccy" to "System Preferences / Security & Privacy / Accessibility".
