### ISSUE TITLE
Clear confirm window not at the top

### ISSUE THREAD

**Issue by ghost** [p0deje/Maccy#466]
when i call maccy and press `command` + `option` + `backspace` to clear all:

![maccy_clear_confirm_window_issue](https://user-images.githubusercontent.com/9608276/191647592-63f621a2-422b-469c-88a2-6585f295cb57.gif)

### Mac
Apple M1 Pro
12.6

### Maccy
0.24.0(13)

**Comment by p0deje** [comment]
Cannot reproduce this, can you restart Maccy and try again?

![2022-09-22 10 20 19](https://user-images.githubusercontent.com/665846/191811506-a187d7cb-0586-47f0-b8ca-d806ac0371ec.gif)

**Comment by shineshane** [comment]
> Cannot reproduce this, can you restart Maccy and try again?

Same problem after restart Maccy. You can set clipboard appear in the screen center and try again. (needs enough records to cover up the confirm window)

(another question: what record software)

**Comment by p0deje** [comment]
> Same problem after restart Maccy. You can set clipboard appear in the screen center and try again. (needs enough records to cover up the confirm window)

Still works fine for me.

> (another question: what record software)

Gifox

**Comment by shineshane** [comment]
> Still works fine for me.

See if anyone else has the same problem.

**Comment by rea1shane** [comment]
Same issue on 13.0. This issue is not critical, history is rarely cleared
