### ISSUE TITLE
Possibility to change "default Ignore Copy Types"

### ISSUE THREAD

**Issue by SvenJuergens** [p0deje/Maccy#468]
as described here, some copy types are ignored by default. It would be nice to have a possibility to change this default list, or better to reduce it. 
It sometimes happens that a copied element from a PasswordManager like keepassxc is needed more often, but then it is needed in the Clipboard Manager.  In this example all copied Elements form keepassxy has 'org.nspasteboard.ConcealedType' and so i have no changes to use it with maccy

**Comment by p0deje** [comment]
I've been thinking about allowing to customize this, but I have a concern about security because given the Maccy database is not encrypted it's possible for an attacker to start logging all passwords in Maccy and then obtain a copy of the database. I would like to hear more about the case when "password is needed more often" before agreeing.

**Comment by SvenJuergens** [comment]
hi, I think Maccy is a greet tool, on Linux I use Parcellite and that's what I was looking for on Mac and thought I found something with Maccy.
However, it doesn't copy some things, which then seems more like a bug than a feature to me, because it is a clipboard manager.
I think it's pretty good that you think about security, also that you have options from which tool entries are ignored.
However it is only so good because the user can decide for himself. I guess most of the users of Maccy are people who know a bit more about computers.
And are well aware of what happens when you store a password in plain text, that's why you use tools like 1password, keepassxc and co.
But here I think you decide for everyone what can be copied and what not. Maccy is a fast little tool, which should make your life easier.
Maccy does not need an encrypted database, because it is not a password manager, which has to keep things safe. 
The example you described is certainly possible, but if a hacker managed to get on a Mac, he will most likely go to other targets than logging Maccy's input.
I'm not saying it's impossible, but I think in percentage terms the probability is very low that it would happen that way.
In case there will be a possibility to change the default behavior, I would suggest to educate the user more at this point,
why it is useful settings and he should be aware that it is a change also brings a certain risk with it.
Possibly you can also ask again for the password.
But without a possibility of change, it seems for a user who is not familiar with it, as if there would be an error.

**Comment by p0deje** [comment]
>hi, I think Maccy is a greet tool, on Linux I use Parcellite and that's what I was looking for on Mac and thought I found something with Maccy.

Nice, that's the same app I was missing when I switched to Mac.

> However it is only so good because the user can decide for himself. I guess most of the users of Maccy are people who know a bit more about computers.

That's not exactly correct. I get so many support requests asking for basic explanations (e.g. enable this in preferences) and I believe the Maccy user-base is much wider than programmers and/or advanced Mac users.

> The example you described is certainly possible, but if a hacker managed to get on a Mac, he will most likely go to other targets than logging Maccy's input.

I agree. However, Maccy should not be another possible attack vector.

**Comment by p0deje** [comment]
I still haven't heard the real need for use case when "password is needed more often".

**Comment by SvenJuergens** [comment]
hello, right the use cases.

- e.g. I have to work with various external services.
Logging off from these services happens after a relatively short period of inactivity, which unfortunately happens more often than one would like. 
- Partly I have to work on remote systems, also over these systems I have to log on to external services.
- Create and manage users, use are created with local password generators and are then transferred to an online password store. 
- Github checkouts in various customer hosting applications

etc
so I have several times a day the need to access passwords faster and the extended clipboard is here very fast, uncomplicated and is always available.
To keep the security here even higher, one could perhaps also delete all passwords in the clipboard, as long as the sleep mode or screen saver comes on, keepassxc for example logs out when the sleep mode comes on.

**Comment by p0deje** [comment]
Hey @SvenJuergens!

Thank you for taking the time to explain this. I still believe that the use case is quite specific to generalize into a feature in Maccy. I would be open to this unless it posed potential security implications or opened up attack vectors. I can only recommend copying and pasting the passwords to some intermediate place (e.g. text field in the browser) and then copying it once again. This way, it won't have concealed types and Maccy would properly save it.

If it's too much of a problem, you can always fork and build your own version of Maccy with concealed types removed. They are defined in https://github.com/p0deje/Maccy/blob/5861eee877c301b48105ce535b212791ea187455/Maccy/Clipboard.swift#L15-L19
