### ISSUE TITLE
Empty entry when copying URL from Edge

### ISSUE THREAD

**Issue by turbanisch** [p0deje/Maccy#472]
Sorry for being obnoxious - I just found a weird behavior. When I navigate to the addresss bar of Microsoft Edge, copy and try to paste with Maccy, the top list item in Maccy is empty. Instead, the URL is stored as the second item.

This behavior does not occur with Firefox and not even with Chrome (also Chromium-based) with the same URL. Not sure if you can do anything about it, probably it's just Edge inserting a hidden line break somewhere.

**Comment by p0deje** [comment]
I can reproduce the issue and will work on a fix.
