### ISSUE TITLE
searching text, when no hits, it should clean up selection entry

### ISSUE THREAD

**Issue by salva-maiorano** [p0deje/Maccy#475]
using version 0.24
use case: without using the mouse, just typing some text that is not in the clipboard history, it leaves the selection entry bar in a non entry
this is minor UI bug, the find itself works all right
btw, this is great app!
<img width="547" alt="image" src="https://user-images.githubusercontent.com/23175194/195664361-70ad639b-8e54-4b14-9aad-4e9aa9e733f5.png">

**Comment by ZachovalAdam** [comment]
Hi there @salva-maiorano! I wasn't able to reproduce this bug, could you maybe provide more information about the problem? Are you maybe using some special accessibility setting? Thank you very much!

**Comment by p0deje** [comment]
I didn't manage to reproduce the bug. Please try upgrading to the latest version and re-open if you still see the problem, providing additional details:
1. Can you please provide the Maccy version you use? You can get it in the "About" window.
2. Can you please record a screen video showing the problem? You can do this using QuickTime.app.
3. Can you please share the output of running `defaults read org.p0deje.Maccy` in Terminal.app?

**Comment by alvin96** [comment]
Hi there @p0deje I am the author of #490 , after I update my Maccy to latest version (0.25.0) this bug still exist. I provided the screen recording which show how I reproduce the bug. 

### Maccy version
<img width="274" alt="image" src="https://user-images.githubusercontent.com/20142859/220804949-19fc6156-a39f-46b8-858e-029485c7b78a.png">

### Way to reproduce
https://user-images.githubusercontent.com/20142859/220805224-f96dd41b-741a-4f5a-b643-8efee47ff7ca.mov

### This is my `defaults read org.p0deje.Maccy`
<img width="1043" alt="image" src="https://user-images.githubusercontent.com/20142859/220804845-865d8307-c2a4-4b63-9586-c14d19001afb.png">




Hope this helps! Thanks

**Comment by p0deje** [comment]
@alvin96 Thank you, I've just pushed a fix in https://github.com/p0deje/Maccy/commit/b6b0a0bf14d91ac14baa178400e1f601bf21536e

**Comment by alvin96** [comment]
> @alvin96 Thank you, I've just pushed a fix in [b6b0a0b](https://github.com/p0deje/Maccy/commit/b6b0a0bf14d91ac14baa178400e1f601bf21536e)

Thanks for your fast response, appreciate it!
