### ISSUE TITLE
Can't use the command + 1-10 shortcuts

### ISSUE THREAD

**Issue by Magnusrn** [p0deje/Maccy#478]
I've been trying to use the command and n(1-10) shortcut to paste the nth item in the history but it many applications(like safari) pressing command and a number will cycle to that tab, is there a way around this? I couldn't find a way to change the shortcut prefix on these 10 items

many thanks it's a great application

**Comment by p0deje** [comment]
The shortcuts only work when the Maccy window is shown - these are no global shortcuts. There is no way to change them too.
