### ISSUE TITLE
Consider to adjust a much reasonable default value for history size

### ISSUE THREAD

**Issue by leesiongchan** [p0deje/Maccy#48]
I find it the default value for history size 999 is a little unnecessary and causing the app to be frozen while open up the app,  maybe 100 is a good default setting?

**Comment by p0deje** [comment]
I was also think about decreasing the amount. I'll see what is the maximum number that doesn't cause any performance issues.

However, I've never seen the app really being frozen while open up. Can you elaborate on this bug?

**Comment by p0deje** [comment]
I stop seeing any slowdown using fuzzy search with 200 records, so let's set it as default.
