### ISSUE TITLE
Setting that sets Maccy to pop up on a specific screen

### ISSUE THREAD

**Issue by krsjl** [p0deje/Maccy#480]
While presenting to other people it would be desired to prevent Maccy and my clipboard history to show up on the screen I am presenting from. This could be achieved by having a setting that lets the user set Maccy to pop up at the menu icon or screen center of a specific screen.

**Comment by p0deje** [comment]
If the only reason to popup on a particular screen is to prevent Maccy from being shown during the presentation, wouldn't it be easier and better to simply quit Maccy altogether?

**Comment by krsjl** [comment]
I am not referring to Powerpoint presentations but rather use cases where I am sharing my screen and using my clipboard quite a lot at times. I definitely don't want to miss Maccy in those situations, but need to make sure to not accidentally show sensitive stuff that might be in the history. Right now as a workaround I am using the pop up at Cursor option and move my cursor the screen that is not shared.

**Comment by p0deje** [comment]
In the next version of Maccy, there will be a way to set specific screen in preferences.

<img width="538" alt="Screenshot 2023-02-26 at 12 02 33" src="https://user-images.githubusercontent.com/665846/221434141-5322be24-1f4c-43e2-b6f9-07837b7d9c9c.png">
