### ISSUE TITLE
feature request: Trim whitespace

### ISSUE THREAD

**Issue by fajkovicsasa-tr** [p0deje/Maccy#481]
Hi,

I would like to request a feature to enable option in Maccy to trim whitespaces at the beginning and/or end of the copied text.

Examples:
If I copy: "  test text", I would like to paste it as "test text"
If I copy "test text. ", I would like to paste it as "test text"
If I copy "  test text", I would like to paste it as "test text"

**Comment by andrewpeal** [comment]
Agree that this doesn't really belong in the core functionality. Seems people want Maccy to become the ultimate do-everything application. While technically possible, it's diverging away from its core purpose.

**Comment by sasa-fajkovic** [comment]
In most situations, this is not needed since you don't copy the whitespace. Dealing with `yml` files which relies heavily on indentation, this can be really handy.

I would really appreciate this feature, but I completely understand if the demand is to low that the effort doesn't make sense. 

If you have an idea for another way to enable this system-wide that would also work

**Comment by p0deje** [comment]
OK, so in the upcoming version of Maccy, there will be a support to fetch **selected** item and then you can do whatever you wish with it. In the example below:

1. I defined a global workflow triggered by pressing ⌥⌘.
2. It gets the currently selected item in Maccy.
3. It then trims the leading spaces and dots.
4. Then trims the trailing spaces and dots.
5. The copies the result into the system clipboard.
6. Pastes the result into the active window.

<img width="1053" alt="Screenshot 2023-01-20 at 10 43 53" src="https://user-images.githubusercontent.com/665846/213780583-420092c6-6516-4bb2-959f-2c95b71c8849.png">

https://user-images.githubusercontent.com/665846/213781278-24bfb30a-7965-4533-bff8-78367e5521c6.mov

There is a noticeable delay while the workflow is running, but there is not much I can do in Maccy about it - that's the workflow execution delay.
