### ISSUE TITLE
Copy repeatedly and a blank line  

### ISSUE THREAD

**Issue by Zss1990** [p0deje/Maccy#484]
Hi, I found a problem:
When copying the same string multiple times with `command+c`, opening `Maccy` with `command+shift+c` will display the following image;

<img width="459" alt="image" src="https://user-images.githubusercontent.com/13251393/200283917-fc35d7fa-45da-4813-b60f-b8487d20fb55.png">

**Comment by p0deje** [comment]
Which application do you copy from?

**Comment by p0deje** [comment]
I just tried copying **exactly** the same string over and over in Xcode and there is only one record in Maccy. You're likely copying **different** strings (e.g. with trailing whitespace), so they simply look the same, while they are not in fact. If you check what is shown in the tooltip for each entry, you might be able to spot the difference.

In regards to the blank line, I need more details on what **exactly** do you copy when this happens.

**Comment by p0deje** [comment]
Closing since there was no reply.
