### ISSUE TITLE
Maccy 0.24.0版本在macOS12以及13下均无法固定项

### ISSUE THREAD

**Issue by Wn16h7** [p0deje/Maccy#485]
Maccy version 0.24.0 can't fix items under macOS12 as well as 13, version 0.23.0 can fix and unfix normally.

**Comment by p0deje** [comment]
Can you provide more details in English please?

**Comment by Wn16h7** [comment]
On my computer, maccy v0.24.0 cannot fix the paste item I want
option+P does not work, v0.23.0 does not have the same problem
My computer OS is macos 12.6.1
I have also tested on macos 13.0

**Comment by p0deje** [comment]
Option+P doesn't paste, it should pin/unpin an item.
If the paste doesn't work, can you try removing Maccy from System Settings / Privacy & Security / Accessibility and add once again? Make sure you only run one version of Maccy at a time.

**Comment by Wn16h7** [comment]
Forgive the lack of clarity, I'd like to say: option +P cannot  pin or unpin an item.

**Comment by Wn16h7** [comment]
And I confirm that I only run one version of Maccy at a time.

**Comment by p0deje** [comment]
Oh, this is weird - I don't think we ever had problems when an item cannot be pinned/unpinned. How did you install/upgrade Maccy? Can you also record a screen video showing the problem?

**Comment by Wn16h7** [comment]
[2.mp4.zip](https://github.com/p0deje/Maccy/files/9973117/2.mp4.zip)

**Comment by p0deje** [comment]
Hm, I wonder if it has something to do with the current keyboard layout that you use. Can you try switching to English language and see if it helps?

**Comment by p0deje** [comment]
Can you please share the output of running `defaults read org.p0deje.Maccy` in Terminal.app?

**Comment by Wn16h7** [comment]
{
    "KeyboardShortcuts_popup" = "{\\"carbonModifiers\\":768,\\"carbonKeyCode\\":8}";
    "NSWindow Frame com.sindresorhus.Preferences.FrameAutosaveName" = "632 350 528 446 0 0 1792 1095 ";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2022-11-09 16:16:34 +0000";
    SUUpdateGroupIdentifier = 918930926;
    enabledPasteboardTypes =     (
        "public.utf8-plain-text",
        "public.file-url",
        "public.png",
        "public.tiff"
    );
    ignoredPasteboardTypes =     (
        "net.antelle.keeweb",
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "Pasteboard generator type",
        "com.agilebits.onepassword"
    );
    migrations =     {
        "2020-04-25-allow-custom-ignored-types" = 1;
        "2020-06-19-use-keyboardshortcuts" = 1;
        "2020-09-01-ignore-keeweb" = 1;
        "2021-02-20-allow-to-customize-supported-types" = 1;
        "2021-06-28-add-title-to-history-item" = 1;
        "2021-10-16-remove-dynamic-pasteboard-types" = 1;
        "2022-08-01-rename-suppress-clear-alert" = 1;
    };
    pasteByDefault = 1;
    removeFormattingByDefault = 1;
}

**Comment by p0deje** [comment]
I'm out of ideas at the moment. Can you try uninstalling Maccy, removing all the data and installing it once again? To remove data, run the following in the Terminal:

```
rm -rf Library/Containers/org.p0deje.Maccy/
rm -rf Library/Containers/org.p0deje.Maccy-LaunchAtLoginHelper/
rm -rf Library/Application Scripts/org.p0deje.Maccy/
rm -rf Library/Application Scripts/org.p0deje.Maccy-LaunchAtLoginHelper/
rm -rf Library/Application Support/Maccy
rm Library/Preferences/org.p0deje.Maccy.plist
```

**Comment by Wn16h7** [comment]
The video you see is my screen recording after a new installation on a computer that has never installed Maccy

**Comment by Wn16h7** [comment]
To fix this I even tried reinstalling my macOS, 12.6.0, 12.6.1, 13.0, all of which I have tried

**Comment by p0deje** [comment]
Wait a second, I see on the video that you press Option+Shift+P. It should be just Option+P.

**Comment by Wn16h7** [comment]
I've tried it all, maybe it's a problem with my computer, I'll use v0.23.0 first, I look forward to your next version update, this software is very helpful to my daily work, thank you very much!

**Comment by p0deje** [comment]
Can you try without pressing Shift?

**Comment by Wn16h7** [comment]
[1.mp4.zip](https://github.com/p0d
[3.mp4.zip](https://github.com/p0deje/Maccy/files/9985927/3.mp4.zip)
eje/Maccy/files/9985917/1.mp4.zip)
[2.mp4.zip](https://github.com/p0deje/Maccy/files/9985924/2.mp4.zip)

**Comment by Wn16h7** [comment]
[1.mp4.zip](https://github.com/p0deje/Maccy/files/9985932/1.mp4.zip)
[2.mp4.zip](https://github.com/p0deje/Maccy/files/9985936/2.mp4.zip)
[3.mp4.zip](https://github.com/p0deje/Maccy/files/9985939/3.mp4.zip)

**Comment by p0deje** [comment]
You closed the ticket, so did it work and now fails again?

**Comment by Wn16h7** [comment]
yes

**Comment by Wn16h7** [comment]
Does anyone else have feedback on this issue?

**Comment by Wn16h7** [comment]
[maccy.log](https://github.com/p0deje/Maccy/files/10003728/maccy.log)

**Comment by p0deje** [comment]
Sorry, I'm out of ideas what could be the reason. If anyone else has similar, please share the details.

**Comment by Wn16h7** [comment]
From the logs and screen recordings I provided it should have been working correctly right?

**Comment by tang1189** [comment]
I have the same problem.

**Comment by p0deje** [comment]
@Wn16h7 Yes, I can see on the video that it's not working. However, I have no idea at the moment why would it happen. I'm also confused as to why it worked for some time and then stopped.

@tang1189 Can you also record a video of the problem and share?

**Comment by ssyzh** [comment]
me too, Mac OS: 13.0.1 (22A400), maccy: 13.0.1 (22A400)

**Comment by p0deje** [comment]
@Wn16h7 Can you please tell me the name of the keyboard layout you use? Also, I see some application in the menu bar (the left one) with a command key icon. What is it?

**Comment by Wn16h7** [comment]
<img width="684" alt="image" src="https://user-images.githubusercontent.com/105099466/215238066-bb5643cc-876f-4d8e-8450-42cca46e72ac.png">

**Comment by Wn16h7** [comment]
Mac OS: 12.6.3 (21G419), maccy:0.25.0. This problem occurs again！

**Comment by p0deje** [comment]
@Wn16h7 Please, tell me the title of the input source in English. It's pretty hard to find what it is based on the icon 😄

**Comment by p0deje** [comment]
@Wn16h7 I assumed this is "Pinyin - Traditional", but the keyboard looks completely different on your screen.
<img width="502" alt="Screenshot 2023-01-28 at 06 42 31" src="https://user-images.githubusercontent.com/665846/215272651-d964e0c3-7240-4723-8789-8e3306004aec.png">

**Comment by oahjhao** [comment]
macOS 12.6.2 (21G320) + maccy 0.25.0 have the same problem. try to find the triger...

**Comment by oahjhao** [comment]
> macOS 12.6.2 (21G320) + maccy 0.25.0 have the same problem. try to find the triger...

option + p can not pinned/unpinned, option + del works fine.

**Comment by p0deje** [comment]
@oahjhao  Please, tell me the title of the keyboard input source in English

**Comment by oahjhao** [comment]
> @oahjhao Please, tell me the title of the keyboard input source in English

I have 2 input source:
a. "ABC" by default
b. "Chinese, Simplified" - "pinyin - Simplified" or "sougou input method"

I tried：
a. removing all keyboard input source but ABC
b. removing all the maccy data and installing it again
still can not pin/unpin

**Comment by p0deje** [comment]
Thanks. Do you maybe also use not a standard keyboard?On Feb 8, 2023, at 17:38, Heikki ***@***.***> wrote:﻿

@oahjhao Please, tell me the title of the keyboard input source in English

I have 2 input source:
a. "ABC" by default
b. "Chinese, Simplified" - "pinyin - Simplified" or "sougou input method"
I tried：
a. removing all keyboard input source but ABC
b. removing all the maccy data and installing it again
still can not pin/unpin

**Comment by oahjhao** [comment]
> 

yes. only keyboard on my mbp and there's no other input device.

**Comment by p0deje** [comment]
@oahjhao Thank you, I can finally reproduce the bug. Will try to fix.

**Comment by p0deje** [comment]
Actually no, I still cannot reproduce the problem using "Chinese, Simplified" - "pinyin - Simplified" 😞

**Comment by oahjhao** [comment]
> Actually no, I still cannot reproduce the problem using "Chinese, Simplified" - "pinyin - Simplified" 😞

Setup ENV :
device A : mbp m1 pro    macOS 12.6.2 + maccy 0.25.0 + "Chinese, Simplified" - "pinyin - Simplified"
device B : mac mini intel  macOS 12.6.2 + maccy 0.25.0 + "Chinese, Simplified" - "pinyin - Simplified"

Debug :
device A : 
1. option + p dont work
2. GlobalHotKey popup nothing after option + p pressed, and KeyboardShortcuts and Sauce return nothing.
3. update KeyboardShortcuts to recent release version, fix some compatible problem, nothing changed.
4. modify .p → .u , pin & unpin works fine.

![f002b321f306996a905c4f23a1042d8](https://user-images.githubusercontent.com/8485666/219053851-1a062916-840c-4e6e-98c9-0beba375b35d.jpg)

device B :
1. option + p works fine...

emmm....wondering what's the special usage of option + p in macOS...

**Comment by p0deje** [comment]
I have no idea, but I cannot reproduce this at all on MBP M1 Pro with macOS 13.2.1

**Comment by chunyang-wen** [comment]
Just wonder: have you installed the snapshot application iShot? I found it setup the shortcut for Record screen. Clear the shortcut, Maccy can successfully pin and unpin.

Finally made it work!

**Comment by oahjhao** [comment]
> @oahjhao @Wn16h7 Any chance you also use iShot?

Confirmed.
Quit ishot then it works...

**Comment by p0deje** [comment]
I'll consider this working as expected - not sure what else to do here in regards to iShot. Feel free to re-open if you think differently.
