### ISSUE TITLE
feature request: apply Unicode text styling while pasting

### ISSUE THREAD

**Issue by juarezr** [p0deje/Maccy#486]
## feature request: apply Unicode text styling while pasting

First, thanks for this wonderful utility. It saves me a lot of time.

### Current behavior

Currently, Maccy only allows the following behaviors while pasting text:

1. Paste with the same source formatting (AS-IS) from what was copied/stored previously (default behavior)
2. Clear the formatting before pasting as plain text if holding the keys:
   `⇧ ⌘ (shift and Cmd)`
3. Invert the above behavior by enabling in the preferences the setting:
   `[x] Paste without formatting`

### Desired changes

It would be interesting to have a new option for applying Unicode text styling before pasting the text.

The main use cases are to allow the use of text styling while:

- writing in text editors that support Unicode but don't have support for text formatting like bold, italics, underline, etc...
- sending messages in instant messaging apps like: Skype, Whatsapp, Telegram, etc...
- while posting comments on social media sites like Facebook, and Twitter.
- using IDE/editor for putting formatted text inside comments in programming languages.
- supporting additional styles in [Markdown](https://www.markdownguide.org/) (like strikethrought).

Adding it to Maccy brings some advantages:

- One does not need an additional workaround of pasting, formatting, re-copying, and re-pasting for having styled text as:
  - opening a text processor app like: 
    - MS Word, Libre Office, Pages
    - Mail, Outlook, rich text editors
  - opening a [specialized website](https://www.makeuseof.com/unicode-text-generators-social-media-posts/) in the browser like:
    - [YayText](https://yaytext.com/styles/)
    - [Unicode Text Styler](https://www.babelstone.co.uk/Unicode/text.html)
    - [Text Editor](https://texteditor.com/font-converter/)
    - [font space](https://www.fontspace.com/font-generator)
    - [cool symbol](https://coolsymbol.com/cool-fancy-text-generator.html)

#### Example

From [YayText](https://yaytext.com/styles/):

```
YayText!
Super cool Unicode text magic. Use s̶t̶r̶i̶k̶e̶t̶h̶r̶o̶u̶g̶h̶, 𝐛𝐨𝐥𝐝, 𝒊𝒕𝒂𝒍𝒊𝒄𝒔, and 🅜🅞🅡🅔 🄲🅁🄰🅉🅈 ʷlͤoͥoͬkͩing fonts on Facebook, Twitter, and everywhere else.
```

### Desired changes

Not entering in specific details, what would be nice to have:

- An additional option in the application menu for choosing what transformation will be applied to the text before pasting.
- A predefined list of common text styles that can be used for formatting the text before pasting.
- A modifier key for triggering the transformation of the desired/selected text before pasting.
  - Maybe it would trigger a second step/menu for choosing the style before pasting.

The list of possibilities that can be created is extensive. But the people will want to use the common formatting they currently have in their editors and websites.

Bellow a simple list trying to catalog the main transformations:

- Character Styling:
  - Bold, italic, double struck / outline
  - Double spacing
- Line Styling
  - Underline, overline, strikethrough, double underline, tilde underline
- Font Styling:
  - Sans, Serif, Monospace, Gothic/Fraktur, Cursive, Script, Greek
- Character Decorations:
  - Circled/Bubbles, Squared, black circled, black circled, keycaps, diamond, big bubbles, parenthesis, censored
- Capitals:
  - Superscript, subscript, small caps
- Character Casing:
  - Uppercase, lowercase, title case
- Geometry:
  - Upside down, mirrored, flipped, 
- Emojis:
  - Before, after, replacing spaces
- Text cleaning:
  - Trimming, un-styling, plain text, fixing line-breaks

Also some of the above could be combined to create more custom styles.

**Comment by p0deje** [comment]
I think this belongs to Shortcuts, not Maccy itself. What if instead, you can create a custom Shortcut that would fetch the copied item from Maccy, apply any transformations you want and then paste it into the current app? You can then build a gallery of transformation Shortcuts that could be used in other applications as well, not just Maccy.

**Comment by juarezr** [comment]
Interesting point of view.

> you can create a custom Shortcut that would fetch the copied item from Maccy

I' try soon. At least for some...

> apply any transformations you want

Here things got harder. One will need a programming language for creating functions for handling Unicode. Swift looks like a good language...

> then build a gallery of transformation Shortcuts

Not sure if they would be practical and reusable for another users.

What if Maccy exposed another action to shortcuts for the gallery / transformation? 

Maybe it could be the best of the two worlds:
- Reusable for every Maccy user
- Scriptable in Shortcuts

**Comment by p0deje** [comment]
> Here things got harder. One will need a programming language for creating functions for handling Unicode. Swift looks like a good language...

Yes, meaning you can create a Swift application that will be able to apply the transformations and expose Shortcuts workflows for it. Something that accepts one string as input and returns a new string. The input in our case would be a string of Maccy history item.

**Comment by juarezr** [comment]
>  I don't want to turn Maccy into a text processor application that performs text transformations based on certain rules.

For this we have text processor apps, right?

> This can easily become bloated with hundreds of rules for conversion and edge cases.

I think it's a wise decision. More features, more code, and more effort to keep it running.

**Comment by p0deje** [comment]
@juarezr I've started working on advanced shortcuts in Maccy and here is a draft of how this feature could be implemented. In this example, I copy 😀 to the clipboard, then fetch the last copied item from Maccy and replace 😀 with :). It's just an example, but I suppose you could build complex replace strategies in a similar manner. 

<img width="1021" alt="Screenshot 2023-01-16 at 07 42 27" src="https://user-images.githubusercontent.com/665846/212716973-d4e809eb-114d-4fdb-b596-59c437a654fc.png">

I don't know how the styling conversions could be applied, so I'm open to any suggestions.

**Comment by p0deje** [comment]
I would like to allow fetching different types of content from each individual history item so you could then for example save it to a file. For example, on the screenshot, I copied the message I pasted above, then fetch it from Maccy as RTF and save it to the file. Then this file can be passed to some conversion scripts and copy it to the clipboard.

<img width="1019" alt="Screenshot 2023-01-16 at 08 48 52" src="https://user-images.githubusercontent.com/665846/212730088-c0052bf3-5797-4342-9901-eff4f2be3784.png">

I want to expose the following types:
* Text
* Rich Text
* HTML
* File (to be added)
* URL (to be added)
* Image (to be added)


<img width="331" alt="Screenshot 2023-01-16 at 08 49 02" src="https://user-images.githubusercontent.com/665846/212730481-da0989b2-26a6-47a2-834f-9c42993622c0.png">

**Comment by p0deje** [comment]
Please see https://github.com/p0deje/Maccy/issues/481#issuecomment-1398799499. You can use the same approach to apply any kind of conversion you want. For example, you can generate a markdown from copied rich text content with a workflow like this:

<img width="1092" alt="Screenshot 2023-01-20 at 11 43 21" src="https://user-images.githubusercontent.com/665846/213791708-2ffe80cb-0310-4f1f-98a9-7ce8f09ab867.png">


https://user-images.githubusercontent.com/665846/213791734-7901f8fd-b0e1-4ffb-b59b-380d68986358.mov



Considering there are other applications that provide workflows for the conversion of different styles, Maccy now provides many opportunities to fine-tune the copied item before pasting.
