### ISSUE TITLE
Copy from Notes doesn't get stored

### ISSUE THREAD

**Issue by veritem** [p0deje/Maccy#488]
I'm on macOS Ventura whenever I copy something from notes app it doesn't get stored in maccy!

**Comment by p0deje** [comment]
1. Can you please provide Maccy version you use? You can get it in "About" window.
2. Can you please record a screen video showing the problem? You can do this using QuickTime.app.
3. Can you please share an output of running `defaults read org.p0deje.Maccy` in Terminal.app?

**Comment by veritem** [comment]
Issue seems to be on my side, restarted and it's working

Thanks.
