### ISSUE TITLE
Questions about security

### ISSUE THREAD

**Issue by D0nn1X** [p0deje/Maccy#491]
Dear Team,
 
Hope you are well,
I am contacting you regarding Maccy, I wanted to know details about the app and the security aspect.
I am currently working as Administrator and I want to be sure that I can provide the app on production.
 
Could you please give me more detail about it ?
 
Data shared between the host and your servers
Telemetry
Actions implemented to guaranty end user’s cybersecurity
 
Thank you in advance
BR,

**Comment by p0deje** [comment]
1. Maccy is fully sandboxed (read more https://developer.apple.com/documentation/security/app_sandbox). The only requested permission is [`com.apple.security.files.user-selected.read-only`](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_files_user-selected_read-only) to allow adding applications to the ignore list.
2. Maccy has hardened runtime enabled (read more https://developer.apple.com/documentation/security/hardened_runtime).
3. Maccy uses Core Data for storage and the database is stored inside `$HOME/Library/Containers/org.p0deje.Maccy/Data/Library/Application Support/Maccy/` directory per sandbox rules (read more https://developer.apple.com/documentation/coredata).
4. Maccy doesn't make or listen to any network requests. It's forbidden by the sandbox.
5. All the code is open source and you can inspect it in this repository.
