### ISSUE TITLE
Since version 0.23 and 0.24, the third-party Chinese input method  cannot be used in search

### ISSUE THREAD

**Issue by xyiili** [p0deje/Maccy#493]
Since version 0.23 and 0.24, the third-party Chinese input method (unofficial Chinese input method) cannot be used in search.

**Comment by xyiili** [comment]
I recompiled your newly modified code. While you solved the #476 error, you also solved the bug that Chinese third-party input methods cannot input Chinese. thank you.

**Comment by p0deje** [comment]
Great, good to know that!
