### ISSUE TITLE
When on second monitor, the pasting from Maccy doesn't work

### ISSUE THREAD

**Issue by akhilesh20695** [p0deje/Maccy#494]
When on second screen, once Maccy pop-up is opened and item is selected for pasting, somehow it doesn't paste. Nothing happens. If the same is done on primary screen, pasting works fine.

Version : 0.24
OS version: macOS Monterey 12.6.1

**Comment by p0deje** [comment]
1. Can you please record a screen video showing the problem? You can do this using QuickTime.app.
2. Can you please share the output of running `defaults read org.p0deje.Maccy` in Terminal.app?
3. Does it happen in all applications or only some specific ones?

**Comment by akhilesh20695** [comment]
Restarted my Mac and it started working.! Apologies for this.!
Thanks btw.! This is an awesome utility.! :)

**Comment by 8191** [comment]
This seems to be an issue indeed. I also observed this behaviour right now.
