### ISSUE TITLE
feature request: Alternate menu bar icon(s)

### ISSUE THREAD

**Issue by darienm** [p0deje/Maccy#495]
To improve the intuitive association of the app's function, I suggest something that resembles a clipboard (offered in both black and white). I've also seen similar apps offer various shapes and orientations of scissors, a gear, etc. If you'd like some properly prepared files I can likely provide them. A dropdown under Appearance would make the most sense to select one.

**Comment by p0deje** [comment]
Unfortunately, I don't have the capacity to work on this now, but I am open to merging a pull request adding new icons and settings dropdowns allowing you to choose between them.

**Comment by FabyoSK** [comment]
I'm open to work on this, 
Can you provide me some guidance, and which Icon should I put in the dropdown?

**Comment by p0deje** [comment]
@FabyoSK Thanks for your interest. Roughly, you need to do the following:

1. Add a new row with NSPopupButton in `AppearancePreferenceViewController.xib` under `Show menu icon`.
2. This popup list would allow selecting from 3 different icons. Obviously, there will be a default one, but I suggest we use extra icons from https://developer.apple.com/sf-symbols/ since we can export them as SVG. The following makes the most sense to me:

| name | icon |
|---|---|
| `list.clipboard` | <img width="95" alt="Screenshot 2023-02-27 at 17 18 48" src="https://user-images.githubusercontent.com/665846/221727737-e0bd1586-5be2-4c32-af24-00f532350697.png"> |
| `scissors.circle` | <img width="79" alt="Screenshot 2023-02-27 at 17 20 15" src="https://user-images.githubusercontent.com/665846/221727829-14eb4c70-8e9a-4cbe-8504-615e16c7aff7.png"> |

3. Add the SVG version of icons to `Assets.xcassets`. There are some examples there. We'll also need PNG versions for the older versions of macOS, but I can help with this once it works.
4. Extend `NSImage+Names.swift` to load new images.
3. Add a new string preference called `menuIcon` to `UserDefaults+Configuration.swift`. This would default to `maccy`.
3. When the popup list is changed, change the `UserDefaults.standard.menuIcon` accordingly.
5. Add a new observer attached to  `UserDefaults.standard.menuIcon` in `Maccy.swift` that would update `statusItem` icon whenever the preference changes. See `initializeObservers()` for examples.

It's probably not detailed, but feel free to ask anything along the way :)

**Comment by FabyoSK** [comment]
Thank you for your shortly reply 😁
I'll spend some time running the project locally today, If I found any blockers I'll let you know :)

**Comment by FabyoSK** [comment]
@p0deje hello again 

I'm facing some issues running the app, since it don't have any guide, for some reason I'm not able to fetch the dependencies
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/64048314/222415679-2da923dc-95ca-47a3-b099-03c39708f31e.png">

**Comment by darienm** [comment]
Before I became aware of SF Symbols, I had mocked up a few options as transparent PNG. The Symbols look like a good option, but I would vote for shapes that are easier to visually acquire at small sizes (have more visual weight) amongst the often cluttered menubar. My votes would go to:

clipboard.fill 
![clipboard fill@2x](https://user-images.githubusercontent.com/2875381/222464649-c03d2676-576f-4d84-bf71-b91f31577f76.png)

scissors 
![scissors@2x](https://user-images.githubusercontent.com/2875381/222464567-c78e5c1e-2c77-4759-bdec-9b554c40e2d7.png)

I can also be of assistance preparing the SVG or PNG alternatives for MacOS < 11.7.4 (Big Sur) as those cannot use SF Symbols. Thank you both for your interest in working on this.

**Comment by p0deje** [comment]
@FabyoSK Strange, there is no 5.7.0 version of LaunchAtLogin https://github.com/sindresorhus/LaunchAtLogin/releases/.  Can you try removing the dependency and adding it back?

**Comment by p0deje** [comment]
@darienm Those would work well too. I don't have a strong preference, though I think rounded scissors might look better on a menubar. In any event, we'll need 5 different assets for each icon:

1. Light mode 16x16 PNG
2. Light mode 32x32 PNG
3. Dark mode 16x16 PNG
4. Dark mode 32x32 PNG
5. SVG

If you can prepare those, it would be amazing.

**Comment by FabyoSK** [comment]
@p0deje After some debug, I found out that the issue was my XCode, I needed to update it to XCode 14 in order to download the dependecies

But now I'm having this issue
<img width="960" alt="image" src="https://user-images.githubusercontent.com/64048314/224031654-2812aeef-733c-4629-89fb-d78af0b78326.png">

I can't found the root cause of it

**Comment by FabyoSK** [comment]
@p0deje NVM, I figure out that was the Sparkle framework with signin issues
Now I have the project up and running

**Comment by darienm** [comment]
I've put together a clipboard and a scissors, in both light and dark modes, in both 16x16 and 32x32 sizes for consideration. All PNG files with transparent backgrounds. SVGs also provided. Attached as Round 01. Let me know your thoughts. If these are working, I am happy to prepare others.
[maccy_alt_icons_round_1.zip](https://github.com/p0deje/Maccy/files/10938055/maccy_alt_icons_round_1.zip)

**Comment by p0deje** [comment]
@darienm Thank you, they look quite nice. I'm only curious to see why `clipboard.fill` proportions look so different between 16 and 32? It looks like the smaller version of the icon is much wider.

<img width="270" alt="Screenshot 2023-03-10 at 07 47 27" src="https://user-images.githubusercontent.com/665846/224361166-2f375fee-7501-4c76-a508-e53687185e78.png">

**Comment by darienm** [comment]
I took a small liberty with the individual pixels at the smaller size to make the shape of a clipboard more recognizable. It was intentional and not an artifact of the scaling.

**Comment by p0deje** [comment]
I would prefer the icons to be similar to each other for consistency, but frankly, I never use such a huge resolution where the smaller icon version is being used. @darienm Do you have a strong opinion on keeping them different?

<img width="113" alt="Screenshot 2023-03-10 at 08 13 02" src="https://user-images.githubusercontent.com/665846/224366708-e9d1a45a-6599-4140-8ca7-197fed117252.png">

![Screenshot 2023-03-10 at 08 12 52](https://user-images.githubusercontent.com/665846/224366807-af798cc3-ce3b-4287-8a21-972d6f03ab24.png)

**Comment by darienm** [comment]
I'm providing consistent, narrow versions of the 16px clipboards in this attachment. I can't tell if an effort is being made to vertically position the icons in the menubar based on the screenshot provided. [clipboard.fill.narrow_16.zip](https://github.com/p0deje/Maccy/files/10944873/clipboard.fill.narrow_16.zip)

**Comment by p0deje** [comment]
@darienm I think these look better, thanks!
![Screenshot 2023-03-10 at 10 42 05](https://user-images.githubusercontent.com/665846/224399331-82d06395-e78b-4503-a8f7-e574c3d12577.png)

**Comment by FabyoSK** [comment]
Can you provide the `Copy` icon?

And also provide feedback on the design? 
the dropdown should be below or on the side of `Show menu icon`?

<img width="384" alt="image" src="https://user-images.githubusercontent.com/64048314/224505496-40e7834c-2de5-464e-a35e-0cb2932ac160.png">

<img width="329" alt="image" src="https://user-images.githubusercontent.com/64048314/224505468-ff8cbd71-4099-4977-8537-3d5d875c5a4a.png">

**Comment by FabyoSK** [comment]
A quick demo of it working:
I'll waiting here for feedbacks about it

Uploading output.mp4…

**Comment by darienm** [comment]
I didn't find an icon named "copy" in SF Symbols, but guessed you meant the one that had been previously shown in this thread. The doc.on.clipboard icon set is attached. I thought logically the icon selection would appear just above the "Popup at" option near the top. (First select the icon, then select the behavior.) But that's not my call.

[doc.on.clipboard_set_round_01.zip](https://github.com/p0deje/Maccy/files/10949301/doc.on.clipboard_set_round_01.zip)
![appearance_interface](https://user-images.githubusercontent.com/2875381/224508311-5909f64c-1d4d-4904-9de1-288b2aadd789.png)

**Comment by darienm** [comment]
Side note: I don't know it's necessary to name the icons; rather let the user determine what's most appropriate for their needs.

**Comment by FabyoSK** [comment]
> Side note: I don't know it's necessary to name the icons; rather let the user determine what's most appropriate for their needs.

I think its not necessary, I put it for clarity
I can remove it if we agreed to

**Comment by p0deje** [comment]
@FabyoSK Looks great IMHO. A couple of notes for feedback:

1. Let's keep the dropdown after the "Show menu icon" checkbox.
2. I'd recommend removing titles from icons. They are not particularly important, but if we keep the titles - they need to be localized so it's extra work.

Other than that, I think it looks ready for a pull request.

**Comment by FabyoSK** [comment]
@p0deje Noted, 
I'll make my PR today, I just need to clean up the code 😉

**Comment by darienm** [comment]
That satisfies my initial request beyond expectations. Thank you!

**Comment by FabyoSK** [comment]
The PR is here: #523 
Please check it and let me know if I can improve something :)

**Comment by p0deje** [comment]
@FabyoSK Thank you for the PR, it looks and works wonderfully.
@darienm Thank you for the designs, the icons look great.

**Comment by p0deje** [comment]
Implemented in 93ddbc60446830b2120fa653132b29d2f1865b5b, thanks again folks, great job!
