### ISSUE TITLE
Feature request: alternative shortcut for paste without format

### ISSUE THREAD

**Issue by maisun** [p0deje/Maccy#497]
Thanks for the great tool, it's the best that I have tried so far!
I have configured automatically paste when enter, which works great, however if I want to paste without format I have to press Shift+Cmd+Enter, it would work better for me if I can customize to just Opt+Enter instead. I'm aware the option to always paste without format, however I sometimes do need to paste with format so a shortcut works better for me.
Appreciate your consideration of this feature!

**Comment by maliayas** [comment]
Agreed. Small but useful improvement.

**Comment by p0deje** [comment]
It's unfortunate that macOS doesn't properly handle pressing Shift in this case. It seems like a bug in NSMenu implementation.

Given we have the following items:

| NSMenuItem Number | isAlternate | keyEquivalentModifierMask |
|-------|--------|---|
| 1 | false | ⌘  |
| 2 | true | ⇧⌘ |
| 3 | true | ⌥ |

When I press ⇧ on the keyboard, I should see item 2 shown, but it's not. I have to press ⇧⌘ to see it. The bug doesn't happen when item 3 is removed.

What do you think if we switch to use just ⇧ for pasting without formatting if paste by default is enabled?

**Comment by maisun** [comment]
> 

Hi @p0deje , thank you for looking into it! I don't quite understand the technical here, I think it's most nature to use Option key for something that is different than the default behavior, however I do understand if it's not possible, in which case shift+enter sounds like a nice solution :-)

**Comment by p0deje** [comment]
@maisun The problem is that there are 2 alternative actions you can take:

1. Paste item (default), using ⌘.
2. Paste without formatting, using ⇧⌘.
3. Copy without pasting, using ⌥.

Because there are more than 2 actions, I've made a decision to somehow group related actions. In this case, there are 2 paste actions, so they all share ⌘ the key, while the formatting behavior is changed by ⇧. However, due to what I consider a bug in macOS, when you press only ⇧, the paste without formatting is not automatically shown.

**Comment by p0deje** [comment]
I am concerned to change the default behavior from ⇧⌘ to ⇧. I know ⇧⌘ is an extra key press, but both are usually within the reach of the same hand. Considering it's been like that for years, I'm going to keep this behavior.

**Comment by MohamadKh75** [comment]
Hey
I guess I'm a little confused!

Copy: `⌘ + C`
Paste: `⌘ + V`
Paste without formatting: ?

Are there any ways to paste with just shortcuts (not opening the Maccy)

**Comment by p0deje** [comment]
Are there any ways to paste with just shortcuts (not opening the Maccy)There are no such shortcuts. On Jan 1, 2024, at 04:14, Mohamad Khajavi ***@***.***> wrote:﻿
Hey
I guess I'm a little confused!
Copy: ⌘ + C
Paste: ⌘ + V
Paste without formatting: ?
Are there any ways to paste with just shortcuts (not opening the Maccy)
