### ISSUE TITLE
Feature request: Extract all history as a txt or any other format 

### ISSUE THREAD

**Issue by krushnadeore** [p0deje/Maccy#498]
Need this feature cause whenever I reboot my MacBook it automatically clears all history even I didn't ticked on that option ( clear all after quit)

**Comment by p0deje** [comment]
If it clears the history - it's obviously a bug in Maccy. I would rather fix it than implement an export functionality. 

1. Can you please provide Maccy version you use? You can get it in "About" window.
2. Can you please record a screen video showing the problem? You can do this using QuickTime.app.
3. Can you please share an output of running `defaults read org.p0deje.Maccy` in Terminal.app?

**Comment by p0deje** [comment]
Closing since there is no response.
