### ISSUE TITLE
Feature Request: Shortcut key to deactivate Maccy 

### ISSUE THREAD

**Issue by TyronSamaroo** [p0deje/Maccy#499]
Shortcut key to deactivate Maccy

**Comment by TyronSamaroo** [comment]
There is an Ignore Copied where you can click the menu icon with OPTION (⌥) pressed. To ignore only the next copy, click with OPTION (⌥) + SHIFT (⇧) pressed.

I want to option to change this to maybe something like OPTION (⌥) + SHIFT (⇧)  + X

**Comment by p0deje** [comment]
You can just use a custom Shortcut to toggle Maccy - https://www.icloud.com/shortcuts/b40d54e98fbd4eb6b46afcac887a9cbd. Once added to the Shortcuts app, you can bind it to the global keyboard shortcut (see screenshot for example):

<img width="1312" alt="Screenshot 2022-12-21 at 13 58 47" src="https://user-images.githubusercontent.com/665846/209010441-fd116a3f-f314-48fc-95bf-0af5fbe8b75a.png">
