### ISSUE TITLE
Enable paste automatically by default in settings

### ISSUE THREAD

**Issue by 1Mark** [p0deje/Maccy#500]
I had assumed `Paste automatically` was on by default (and not configurable) I realised this was not the case when I stumbled upon https://github.com/p0deje/Maccy/issues/482#issuecomment-1296291391 (I mentioned my issue here https://github.com/p0deje/Maccy/issues/148#issuecomment-1366892043) 

Wouldn't it make sense to enable this by default?

FWIW, if yes then **ideally** it should only update for new installations (not existing ones) to ensure existing users have the same functionality.

This is analogous to the behaviour provided by windows 10+

**Comment by p0deje** [comment]
I personally use Maccy w/o paste enabled so the defaults reflect my preference. I am open to changing this, but it also means that users will have to always enable accessibility on the first Maccy usage. Right now there is no need to enable it.

**Comment by 1Mark** [comment]
You make an interesting point. Maybe then a prompt to inform them if they'd like to enable it would be best?

**Comment by p0deje** [comment]
I would normally avoid extra prompts or other behavior, though it might be useful for certain users.

**Comment by maliayas** [comment]
In my opinion, that's actually a bad design of Apple. Pasting automatically should be the default for a clipboard app.

That said, there is nothing to do if you don't want an extra prompt, which is very logical.

**Comment by Kentzo** [comment]
My vote is against pasting by default as I'm very cautious about giving the Accessibility permissions.

**Comment by 1Mark** [comment]
> My vote is against pasting by default as I'm very cautious about giving the Accessibility permissions.

Valid points. I guess let's update the readme to clarify the behaviour and that it's configurable. Coming from Windows 10 I had assumed this was the default behaviour since it's built into the OS...
