### ISSUE TITLE
Feature request: "paste without format" always on

### ISSUE THREAD

**Issue by boutique-airfoil-dint** [p0deje/Maccy#506]
Hi, I would love to the see the options to always have "paste without format" (plan text copy) on. I usually only need to copy plain text and want to avoid having to press a special shortcut all the time. 

Love the App!

BR from Germany

**Comment by p0deje** [comment]
This option already exists, you can enable it Maccy Preferences

**Comment by p0deje** [comment]
This option already exists, you can enable it Maccy Preferences

**Comment by boutique-airfoil-dint** [comment]
Hey p0deje, thanks for your response. Maybe I am not seeing this option. I would love to basically use command+c and command+c on my keyboard and Maccy automatically removes the formatting. To my understanding it doesn't do it yet. You need to go into the Status bar icon and click command while mouse left clicking the entry. 

BR

**Comment by p0deje** [comment]
Yes, Maccy doesn't support that feature - you have to click the entry. If you'd like to automatically clear formatting from all your copies, please use https://apps.apple.com/us/app/pure-paste/id1611378436?mt=12. It's fully compatible with Maccy too!

**Comment by boutique-airfoil-dint** [comment]
Oh great stuff!!! Thanks a lot. Now I can enjoy using Macs even more. Appreciate the hint. Cheers
