### ISSUE TITLE
Feature request: Copy list of items and paste them separatly

### ISSUE THREAD

**Issue by deabrunner** [p0deje/Maccy#507]
This feature would allow the user to copy a list of items, and paste each item separatly. 

**How it would work:** 
The user selects a list of items and copies them. 
When pasting the user can either paste the list in full, or gets the option to iterate through the list and paste each item separatly. 

Once the user has pasted one if the items from the list, it is moved to the last position in the list, and the next item in the list is up next for being pasted. 
This continues until all items in the list have been pasted. 

I think it makes sense to also have some kind of indicator that an item from the list has already been pasted. 

Here's a suggestion of how it could look in the GUI: 
<img width="914" alt="maccy-feature-requst" src="https://user-images.githubusercontent.com/16192357/215278192-d10a4820-0c87-4eef-a029-3b8e1b327a73.png">

**Why such a feature?** 
This feature allows for automation of simpler repetitive tasks, such as entering data into a form which accepts 1 entry at the time, but you need to enter 40 entries. 
Example: Sending 40  separate email to different recipients based on a list.

**Comment by p0deje** [comment]
This looks to me a very specific use case which doesn't really belong to the clipboard manager core functionality. I'd like to keep Maccy simple and lightweight, without overwhelming with too much functionality.

I think you can try building something similar using the Shortcuts app - Maccy supports getting selected item content, then you can split it into a list by the space character, then iterate through it and paste one by one.

Please open a new issue if you want some extra functionality from Maccy available in the Shortcuts.

**Comment by p0deje** [comment]
An example using Shortcuts app is in https://github.com/p0deje/Maccy/issues/486#issuecomment-1398851697

**Comment by deabrunner** [comment]
I'll try to replicate the feature in shortcut, thanks!

**Comment by p0deje** [comment]
Please share the workflow if you build it, other might find it useful too.
