### ISSUE TITLE
We need one for Ubuntu please

### ISSUE THREAD

**Issue by DeadstarIII** [p0deje/Maccy#508]
hey there, I like the UI
Please add support for ubuntu and other linux based distros

**Comment by p0deje** [comment]
Sorry, no chance I'd port this to other OS. I can recommend https://parcellite.sourceforge.net, I used it before switching to macOS.

**Comment by DeadstarIII** [comment]
You have the code, you just need to edit a bit and compile .deb file.
Not much of hard work man!

**Comment by p0deje** [comment]
@DeadstarIII Is this some kind of a joke? The application is built with macOS AppKit, it cannot work anywhere **except** macOS.
