### ISSUE TITLE
Remove "clear history" entry

### ISSUE THREAD

**Issue by vitofasano** [p0deje/Maccy#509]
Hi, 
I suggest inserting an option in the program preferences to be able to choose whether to display the key in the menu.
thanks

**Comment by p0deje** [comment]
What is the reason to?

**Comment by vitofasano** [comment]
Thanks for the reply. It would be useful to insert this possibility of choice because it could be convenient for someone to reduce the number of entries in the menu and the possibility of deleting the history by mistake.
in fact, I suggest inserting an option in the settings to be able to choose whether or not to display the entry to the main menu for cleaning the history. By default this option remains as it is now, but it will only be activated by those who deem it useful.
Thanks to the availability
