### ISSUE TITLE
Hotkey ignores alternate keymaps

### ISSUE THREAD

**Issue by akbarnes** [p0deje/Maccy#51]
Hotkeys don't change for alternate keyboard layouts, e.g. Cmd+Shift+V becomes Cmd+Shif+K under Dvorak

**Comment by p0deje** [comment]
I've never used Dvorak so I'd appreciate some help with this. Can you provide the steps how to reproduce given I use regular QWERTY Apple keyboard?

**Comment by p0deje** [comment]
Related to soffes/HotKey#2

**Comment by akbarnes** [comment]
On your Mac, choose Apple menu  > System Preferences, click Keyboard, then click Input Sources.
Click the Add button , then search for Dvorak.
Select one or more Dvorak layouts, then click Add.

**Comment by p0deje** [comment]
In the newer version, it should properly support DVORAK (e.g. CMD+SHIFT+V will respond to physically pressing CMD+SHIFT+I on MacBook)
