### ISSUE TITLE
Lost history when updating

### ISSUE THREAD

**Issue by jonelf** [p0deje/Maccy#510]
When I updated from 0.24 to 0.25 I lost 20 days of history (it reverted back to January 11th). I don't think this happened the last time I updated.

**Comment by jonelf** [comment]
I'd rather not because now I have new history I'd like to keep. I'm sorry for not being able to reproduce this.

**Comment by p0deje** [comment]
You can backup your storage to ensure it's not lost during testing:

To backup:
1. Quit Maccy.
2. Run the following command in Terminal.app:

```bash
cp -R "$HOME/Library/Containers/org.p0deje.Maccy/Data/Library/Application Support/Maccy/" "$HOME/Downloads/maccy.backup"
```

To restore:
1. Quit Maccy.
2. Run the following command in Terminal.app:
```bash
cp -R "$HOME/Downloads/maccy.backup/"  "$HOME/Library/Containers/org.p0deje.Maccy/Data/Library/Application Support/Maccy/"
```
3. Run Maccy and check it's loaded correctly.
4. Remove backup folder `Downloads/maccy.backup/` using Finder.

**Comment by p0deje** [comment]
Closing since there is no reply for 3 weeks. Feel free to re-open with extra information.
