### ISSUE TITLE
Issue with Screen sharing

### ISSUE THREAD

**Issue by ugu5ma** [p0deje/Maccy#512]
Hi,

I am just testing the Maccy-app and must say: great work!

When working with screen sharing I run into the following issue:
SHIFT (⇧) + COMMAND (⌘) + C to popup Maccy, then e.g. press COMMAND (⌘) + 3 to paste the 3rd value of the history.
I just get a "v" pasted. Same happens with Fusion and VM-guests of Linux/Windows.

When I  click on its icon in the menu bar and select the entry all works well.

[short video to show the issue: ](https://cipv6.de/dji/maccy_screenshare.mp4)

Regards,
ugu5ma

**Comment by p0deje** [comment]
Just to confirm, this only happens when Screen Sharing is enabled, right?

**Comment by ugu5ma** [comment]
Exactly, only with Screen-sharing I run in this issue.

**Comment by p0deje** [comment]
@ugu5ma Do you open Maccy inside the guest or inside the host?

**Comment by ugu5ma** [comment]
@p0deje  I open Maccy inside the guest.

**Comment by p0deje** [comment]
Just tried to run Maccy inside Mojave guest and the pasting works fine (see video for example). Do you also run Maccy on the host? If yes, does it have the same shortcut to popup?


https://user-images.githubusercontent.com/665846/221438174-abf77016-14f2-46ac-b9a8-112fd7f885c1.mov

**Comment by ugu5ma** [comment]
@p0deje : Indeed, I run Maccy on the host in parallel. This was my problem.
The shortcuts are the same. With unique shortcuts all works well.


Thanks a lot for your support!
