### ISSUE TITLE
I want to add a function that allows users to customize the height of the project, which makes the display of long content more detailed

### ISSUE THREAD

**Issue by fxzer** [p0deje/Maccy#514]
1.Each item can only display one line of content, and the copied content can't see more detailed content, which makes me particularly uncomfortable and convenient to select. Why can't the user customize the height of the item？
![image](https://user-images.githubusercontent.com/68853957/218030002-11e2b188-8460-421c-a698-9502779e43e9.png)
2.Why is there so much free space behind long sentences in English that they are cut off and not displayed, which is different from Chinese
3.Although there are so many explanations for the Chinese label, this is still confusing. The size of the menu: every time you see it, you will first think about what you mean by the menu. I think 'the number of display items' is more appropriate
![image](https://user-images.githubusercontent.com/68853957/218031677-fb350cb6-3688-4c13-9365-90b269a80de4.png)

**Comment by p0deje** [comment]
> 1.Each item can only display one line of content, and the copied content can't see more detailed content, which makes me particularly uncomfortable and convenient to select. Why can't the user customize the height of the item？

In the upcoming version of Maccy, there will be rich previews so you should be able to see the multiline contents easily.

> 2.Why is there so much free space behind long sentences in English that they are cut off and not displayed, which is different from Chinese

I would assume because the width of individual characters is different - Chinese is much wider.

> 3.Although there are so many explanations for the Chinese label, this is still confusing. The size of the menu: every time you see it, you will first think about what you mean by the menu. I think 'the number of display items' is more appropriate

Agree, it worths renaming.
