### ISSUE TITLE
"sort by first copy time" bug

### ISSUE THREAD

**Issue by ladyrick** [p0deje/Maccy#516]
Steps to reproduce the bug:

1. Turn sort order config to "sort by first copy time"
1. Copy text `text 1`
1. Copy text `text 2`
1. Then copy  text `text 1` again

Now, I would suppose `text 1` will be at the top. But in fact it is `text 2`.

The root cause I think is that maccy auto copy the selected text to clipboard.

With this feature, maccy cannot distinguish "copy from outside" and "copy from maccy".
So for convenience on development, maccy treat a **just copied but already in the list** text as **copied before**, so maccy would not put it at the top.

**Comment by p0deje** [comment]
That's the expected behavior. When you enable sorting by first copied time, it's going to order the items by the time they were first copied in descending order (most recent at the top). Regardless of how many times you copy it. When you copy "text 1" again, since it has already been copied before, it will change the number of copies property and last copy time, but first copy time would not change.

**Comment by ladyrick** [comment]
> That's the expected behavior. When you enable sorting by first copied time, it's going to order the items by the time they were first copied in descending order (most recent at the top). Regardless of how many times you copy it. When you copy "text 1" again, since it has already been copied before, it will change the number of copies property and last copy time, but first copy time would not change.

I think this behavior is not convenient to use. When I copy a text, I would always expect it as a **new item** and shows at the top. It’s very bothering me that I need to remember whether I have copied it before. If by accidence I copied it and forget it, I would be confused that the just copied text is missing in maccy.


While “sort by first time” has the above issue, “sort by last copy time” also has issue. When I select a text in maccy, I would expect this action would not change the order of maccy list. But because maccy always copy the selected text to clipboard, the list order will always change. This also bothers me a lot. I wish maccy can offer an option to not auto copy.

**Comment by ladyrick** [comment]
In general, my wish is:
1. Every time I copy a text, it shows at the top of maccy list.
2. When I select a text from maccy list, the list order will not change.

**Comment by p0deje** [comment]
Can you elaborate on why this is important to you? Maccy exists for several years and that's the first time somebody asks for this behavior. How does that affect the **real** usage of the application?

**Comment by ladyrick** [comment]
> 1. Every time I copy a text, it shows at the top of maccy list.

This is explained before. It’s very bothering me that I need to remember whether I have copied it before. If by accidence I copied it and forget it, I would be confused that the just copied text is missing in maccy.

> 2. When I select a text from maccy list, the list order will not change.

Here is my case. I copy some items for copy to somewhere later. Each item is similar to the others (to be clear, they are a bunch of ipv6 address). And the paste order is not the order of copy. When the order always change, I need to calculate in my mind which one I should paste next, or select the right one from a bunch of very similar items. But if the order doesn't change, I can paste whatever I want.

**Comment by p0deje** [comment]
In the next version of Maccy, you should be able to add Maccy to Preferences / Ignore / Ignored applications. Then sorting by "last copied item" would work for your case.

**Comment by ladyrick** [comment]
Hello. I find this problem is still there.

**Comment by ladyrick** [comment]
I find that once I enable the checkbox "focus not allowed", this problem shows. When I disable the checkbox, Maccy works as I expected. Maybe it's a bug?

**Comment by p0deje** [comment]
In the next version of Maccy, the original source application will be preserved across copies. If you need to ignore copies from Maccy, add "org.p0deje.Maccy" to the ignore pasteboard types in preferences.
