### ISSUE TITLE
[BUG REPORT] Maccy is crashing as when I am using the search. As long as I don't use it everything works fine.

### ISSUE THREAD

**Issue by cocoonkid** [p0deje/Maccy#519]
[BUG REPORT] Maccy is crashing as when I am using the search. As long as I don't use it everything works fine.

sometimes the 5th char sometimes the 8th.

The problem is only recent. I am pretty sure it worked before without issues as I would not have noticed it otherwise.

0.25.0 
Macbook Pro M1. 
999 history size

Does it produce a log somewhere?

Thanks for this amazing tool!

**Comment by p0deje** [comment]
This would happen if something odd is in history. if you could share it with me privately via email or just upload it here, I will be able to track down the particular copy that caused this. Please do this only if there is nothing confidential!

The database is stored in `$HOME/Library/Containers/org.p0deje.Maccy/Storage.sqlite`.

If you cannot share the database, I can only recommend to either try to locate the problematic copy manually (it might look like an empty record in the list) or clear the history.

**Comment by p0deje** [comment]
There is also a chance it's fixed in https://github.com/p0deje/Maccy/commit/11497b5724bbac74a2d3570212da8f5fb6678487, but I haven't released a new version yet.

**Comment by cocoonkid** [comment]
Thanks for the prompt reply.

Alright, I will wait for the new release and test it out and if the problem still persists 'll send my history and make sure the db is cleaned of anything sensitive.

**Comment by p0deje** [comment]
Could you try running the newest unreleased version and see if it helps [Maccy.app.zip](https://github.com/p0deje/Maccy/files/10889260/Maccy.app.zip)? I wouldn't recommend using it all the time but could be fine for a quick test.

**Comment by PdreiK** [comment]
Clearing the history worked for me. Sometimes this is not a bad idea.

**Comment by p0deje** [comment]
Ok, well, there is not much I can do about it without examples. I'll close the issue - feel free to re-open with more details and preferably attached database.
