### ISSUE TITLE
Question: How Maccy monitors the clipboard?

### ISSUE THREAD

**Issue by ajitid** [p0deje/Maccy#521]
As far as I know, macOS does not provide a clipboard "has changed" event so polling would be the only way. Do you have devised a way to do this without poll? If so, you could you point me to the files/lines of code which do that? I am curious about this. Thank you.

**Comment by p0deje** [comment]
I haven't found a way to receive events so polling it is:

https://github.com/p0deje/Maccy/blob/86b6dd79b2d0f52205bb044c2561175b683a6398/Maccy/Clipboard.swift#L60-L66
