### ISSUE TITLE
Visibility of search string in the result list

### ISSUE THREAD

**Issue by valynor** [p0deje/Maccy#524]
First let me say thanks for the 0.26 update. Love the mixed search and the new rich preview popups! ❤️ 

So, when you search for something your search string in the result list gets marked in bold. 
I find this **very** hard to see especially in dark mode. I would like to suggest to use a transparent light yellow (configurable?) "text-marker" style marking instead so it really jumps into view. 

Also, if one of the search results is too long (result would be in the "..." part) there is nothing marked at all and you have to search for it in the popup. Would be nice if you could mark it there, too (the same way as suggested above). 

What do you think?

**Comment by p0deje** [comment]
> First let me say thanks for the 0.26 update. Love the mixed search and the new rich preview popups! ❤️

Thank you, it means a lot to me!

> I find this very hard to see especially in dark mode. I would like to suggest to use a transparent light yellow (configurable?) "text-marker" style marking instead so it really jumps into view.

I would then have to make it configurable. Using specific colors might work for one mode (dark) but not for others (light). I personally don't really feel any need for highlighting.

> Also, if one of the search results is too long (result would be in the "..." part) there is nothing marked at all and you have to search for it in the popup. Would be nice if you could mark it there, too (the same way as suggested above).

Do you mean to highlight inside the preview? It's technically possible, though for big texts it's not always possible to show it all even inside the preview.

**Comment by valynor** [comment]
>I would then have to make it configurable. Using specific colors might work for one mode (dark) but not for others (light). I personally don't really feel any need for highlighting.

I'm open to other ways of highlighting. The current method is just barely visible to my eyes and I feel it really should be easier to see that it is right now ... maybe underlining would work?

>Do you mean to highlight inside the preview? It's technically possible, though for big texts it's not always possible to show it all even inside the preview.

Yes, that's what I meant.

**Comment by p0deje** [comment]
Probably underlining/italic is another option for highlighting. I would be open to merging PR that allows customizing the behavior.

**Comment by gongchoong** [comment]
I would like to work on this issue

**Comment by p0deje** [comment]
@gongchoong You are more than welcome to send a PR, let me know if you need any assitance.

**Comment by gongchoong** [comment]
@p0deje 
I am trying to create PR but keep getting permission denied messages

**Comment by gongchoong** [comment]
@p0deje Opened a PR. https://github.com/p0deje/Maccy/pull/665

**Comment by p0deje** [comment]
Done in https://github.com/p0deje/Maccy/pull/728
