### ISSUE TITLE
Add a switch between All, Texts, Images and Files

### ISSUE THREAD

**Issue by free-storage** [p0deje/Maccy#526]
Hi. It will be convenient if you add a switch between All, Texts, Images and Files. You open the window, switch and can filter only pictures, for example. It would be very convenient.

**Comment by p0deje** [comment]
Duplicate of #360

**Comment by p0deje** [comment]
Sorry, it's #206

**Comment by free-storage** [comment]
@p0deje Thank you. I'm waiting for an update.
