### ISSUE TITLE
Feature request: Paste without changing what's in the clipboard

### ISSUE THREAD

**Issue by stingusss** [p0deje/Maccy#527]
Hello.
I really love the Maccy app and I would like to request a feature.

I'd like to be able to hit the app hotkey and just press on what I want to be pasted without copying it into the clipboard first (and changing the clipboard history order).

Can you please implement such feature?

Anyway, thank you for developing such an amazing app! Wish you well!

**Comment by p0deje** [comment]
There is no such feature, but you can implement this by creating a custom workflow in the Shortcuts.app, it would look something like this:

<img width="1072" alt="Screenshot 2023-03-17 at 06 51 18" src="https://user-images.githubusercontent.com/665846/225924106-c3793e88-7c61-4ca4-a115-5f4f000a25d3.png">

Now, whenever you open Maccy, select the item you want to paste, and press ⌥⌘P, it will be pasted but your current clipboard item will be preserved in the system clipboard. I didn't test it extensively so probably won't work in all cases, but worth playing around with.

Please re-open if you would like Maccy to provide extra features for Shortcuts.
