### ISSUE TITLE
Bug: Copied items not showing on MacOS until restart of Maccy

### ISSUE THREAD

**Issue by issue-submission** [p0deje/Maccy#528]
With latest version (0.26.0), when history is cleared and only pinged items remain, new items being copied do not show in Maccy. A restart of the application is needed to have the list get refreshed. This behaviour is systematically observed.

**Comment by c-hoeger** [comment]
I had the same experience (on macOS Ventura). But the list disappears again randomly.
I went back to 0.25.0.

**Comment by amer-riaz** [comment]
I'm facing the same issue with latest version (0.26.0).

**Comment by p0deje** [comment]
Can anyone record screenshots/screencasts showing what's wrong?

**Comment by chunyang-wen** [comment]
How to reproduce:

- Click the clear button of maccy
- Try to copy any text

No text will show in the history of Maccy.

**Comment by chunyang-wen** [comment]
If you restart Maccy,  the copied text will be displayed in Maccy.


Ventura 13.2.1 + Maccy 0.26.0

**Comment by p0deje** [comment]
I use Maccy daily and I don't see this happening. This is why I'm asking for screenshots/videos showing the problem, maybe I can notice something.

**Comment by chunyang-wen** [comment]
Do you have any pinned items? 

1. Pin some items
2. clear
3. try to copy text to see whether they show in Maccy

It seems something wrong when working with pinned items.

**Comment by chunyang-wen** [comment]
<img width="779" alt="image" src="https://user-images.githubusercontent.com/2911134/226518415-e8fb8b4a-f896-43bb-9c36-9c8f7ad638a9.png">


Something is wrong with this function. But I don't know how to fix.

If you have some pinned items, for example, the size is 2, then the `menuItemInserstionIndex` is 2 before line 167.

After that, you update the value to 8 (by multiplying 4 to it). But the `historyMenuItems.count` is 6 after clearing with two pinned items.

So the menu items will not be updated.

**Comment by c-hoeger** [comment]
I don't have pinned items,  but the issue showed up here. Will create a screen recording as soon as I have time to do so.

**Comment by chunyang-wen** [comment]
> I don't have pinned items, but the issue showed up here. Will create a screen recording as soon as I have time to do so.

Maybe you can first try to provide a minimum reproducible case. If you follow my steps, can you reproduce the problem?

**Comment by c-hoeger** [comment]
That doesn't fix the issue for me. When I start the new version, the clipboard is empty, all old entries are gone.

**Comment by p0deje** [comment]
@c-hoeger 
1. Can you please provide the Maccy version you use? You can get it in the "About" window.
2. Can you please record a screen video showing the problem? You can do this using QuickTime.app.
3. Can you please share the output of running `defaults read org.p0deje.Maccy` in Terminal.app?

**Comment by c-hoeger** [comment]
The issue seems to appear only when updating from a version < 0.26.x having an existing history.
Was able to reproduce it with 0.26.2 as well on my other computer.
Once I clear the history, seems to work.
The history now also seems to survive an application restart.

**Comment by c-hoeger** [comment]
Well, but now after some hours of work, the list got empty all of a sudden. That's hard to reproduce.
After installing 0.25.0, the list appears again, though.

**Comment by p0deje** [comment]
@c-hoeger There is #532, can you please check it's not the same issue? If it is, try making storage size bigger than number of items at least by 2.

**Comment by c-hoeger** [comment]
No, increasing the storage does not help. List is still empty. Doesn't matter if I increase it by 2 or 20

**Comment by p0deje** [comment]
@c-hoeger 
2. Can you please record a screen video showing the problem? You can do this using QuickTime.app.
3. Can you please share the output of running `defaults read org.p0deje.Maccy` in Terminal.app?

**Comment by c-hoeger** [comment]
Sorry, I cannot record the screen on my work Macbook for the entire day.
On my iMac at home, I didn't see the issue anymore with 0.26.2.
One difference is, that the Macbook has two displays connected in addition to the Macbook display.
Maybe that's related.

`defaults read org.p0deje.Maccy` output:

```
{
    "KeyboardShortcuts_popup" = "{\\"carbonModifiers\\":768,\\"carbonKeyCode\\":9}";
    "LaunchAtLogin__hasMigrated" = 1;
    "NSWindow Frame SUStatusFrame" = "1080 973 400 134 0 0 2560 1415 ";
    "NSWindow Frame SUUpdateAlert" = "970 775 620 398 0 0 2560 1415 ";
    "NSWindow Frame com.sindresorhus.Preferences.FrameAutosaveName" = "1512 968 532 262 0 0 2560 1415 ";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2023-03-24 14:19:39 +0000";
    SUUpdateGroupIdentifier = 881455614;
    WebKitDefaultFontSize = 13;
    WebKitJavaScriptEnabled = 0;
    WebKitPluginsEnabled = 0;
    WebKitStandardFont = "-apple-system-font";
    WebKitUserStyleSheetEnabledPreferenceKey = 1;
    WebKitUserStyleSheetLocationPreferenceKey = "/Applications/Maccy.app/Contents/Frameworks/Sparkle.framework/Resources/ReleaseNotesColorStyle.css";
    enabledPasteboardTypes =     (
        "public.html",
        "public.rtf",
        "public.utf8-plain-text"
    );
    hideSearch = 1;
    historySize = 40;
    ignoredPasteboardTypes =     (
        "Pasteboard generator type",
        "net.antelle.keeweb",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping"
    );
    maxMenuItems = 40;
    menuIcon = clipboard;
    migrations =     {
        "2020-04-25-allow-custom-ignored-types" = 1;
        "2020-06-19-use-keyboardshortcuts" = 1;
        "2020-09-01-ignore-keeweb" = 1;
        "2021-02-20-allow-to-customize-supported-types" = 1;
        "2021-06-28-add-title-to-history-item" = 1;
        "2021-10-16-remove-dynamic-pasteboard-types" = 1;
        "2022-08-01-rename-suppress-clear-alert" = 1;
        "2022-11-14-add-html-rtf-to-supported-types" = 1;
        "2023-01-22-add-regexp-search-mode" = 1;
    };
    pasteByDefault = 1;
    popupPosition = center;
    removeFormattingByDefault = 1;
    showRecentCopyInMenuBar = 0;
}
```

**Comment by p0deje** [comment]
@c-hoeger I see in your settings that number of menu items equals storage size. Please, try increasing the latter by at least 2.

**Comment by p0deje** [comment]
Right, so I was wondering why did you switch back, maybe the preference didn't save. Did you restart Maccy after changing settings?

**Comment by c-hoeger** [comment]
Ok, gave it a chance again.
Changed Storage to 30, cleared history and restarted.
Also changed "Number of Items" to 0.
No history loss again for many hours now.

```
{
    "KeyboardShortcuts_popup" = "{\\"carbonModifiers\\":768,\\"carbonKeyCode\\":9}";
    "LaunchAtLogin__hasMigrated" = 1;
    "NSWindow Frame SUStatusFrame" = "1080 973 400 134 0 0 2560 1415 ";
    "NSWindow Frame SUUpdateAlert" = "970 775 620 398 0 0 2560 1415 ";
    "NSWindow Frame com.sindresorhus.Preferences.FrameAutosaveName" = "1014 227 526 662 0 0 2560 1415 ";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2023-03-28 14:19:44 +0000";
    SUUpdateGroupIdentifier = 881455614;
    WebKitDefaultFontSize = 13;
    WebKitJavaScriptEnabled = 0;
    WebKitPluginsEnabled = 0;
    WebKitStandardFont = "-apple-system-font";
    WebKitUserStyleSheetEnabledPreferenceKey = 1;
    WebKitUserStyleSheetLocationPreferenceKey = "/Applications/Maccy.app/Contents/Frameworks/Sparkle.framework/Resources/ReleaseNotesColorStyle.css";
    enabledPasteboardTypes =     (
        "public.html",
        "public.rtf",
        "public.utf8-plain-text"
    );
    hideSearch = 1;
    historySize = 30;
    ignoredPasteboardTypes =     (
        "Pasteboard generator type",
        "net.antelle.keeweb",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping"
    );
    maxMenuItems = 0;
    menuIcon = clipboard;
    migrations =     {
        "2020-04-25-allow-custom-ignored-types" = 1;
        "2020-06-19-use-keyboardshortcuts" = 1;
        "2020-09-01-ignore-keeweb" = 1;
        "2021-02-20-allow-to-customize-supported-types" = 1;
        "2021-06-28-add-title-to-history-item" = 1;
        "2021-10-16-remove-dynamic-pasteboard-types" = 1;
        "2022-08-01-rename-suppress-clear-alert" = 1;
        "2022-11-14-add-html-rtf-to-supported-types" = 1;
        "2023-01-22-add-regexp-search-mode" = 1;
    };
    pasteByDefault = 1;
    popupPosition = center;
    removeFormattingByDefault = 1;
    showRecentCopyInMenuBar = 0;
}
```
