### ISSUE TITLE
Maccy hangs with beach ball when trying to display a tooltip with too large content (JSON?)

### ISSUE THREAD

**Issue by ADTC** [p0deje/Maccy#530]
I copied a pretty big JSON response, and when I opened Maccy menu and pointed to it, Maccy froze and the beach ball appeared. It looks like it's attempting to render the tooltip, and that's consuming all CPU. I have to open Activity Monitor and quit Maccy (no need to Force Quit) to regain control of the MacBook. Btw I have an M1 Pro CPU, and I tested using recent version 0.26.0.

Maybe a suggestion would be to truncate the amount of text content shown in the tooltip up to some threshold? If you want to test, here's the JSON which has around 15K lines (it's an output from Wise API that's publicly available - no personal data):

https://gist.github.com/ADTC/b5948fed976e477e519fcf627d108e39

To kill Maccy, open Spotlight (⌘Space) and open Activity Monitor, then click on Maccy and click Stop, then Quit. If you already have Activity Monitor in the foreground but it's not responding, you can switch to another app, then back to Activity Monitor again.

In the video, the text cursor is actually the beach ball. Not sure why it wasn't recorded as such.

https://user-images.githubusercontent.com/6047296/226632357-4b6a1077-1037-4e33-84a6-f740c1795f0c.mov

**Comment by p0deje** [comment]
This is already fixed in 4f1314bd4160cd05a4f619c2c6e5e903a675081d, please upgrade to 0.26.1 and re-open if it happens again.
