### ISSUE TITLE
Empty list when storage size <= Number of items

### ISSUE THREAD

**Issue by p0deje** [p0deje/Maccy#532]
Maccy pops up with an empty list when for example storage size is 20 and the number of visible items is 20 too.

**Comment by anthonypillot** [comment]
Hey @p0deje ! First of all, many thanks for your great work, your application is so amazing and so smooth to use. A real pleasure and it should be mandatory for every macOS user.

Speaking of which, how about these screenshots taken within 4 seconds of each other:

![image](https://github.com/p0deje/Maccy/assets/51130139/f8694f38-336f-4511-86c1-92994974d403)
... and ...
![image](https://github.com/p0deje/Maccy/assets/51130139/ffc48bf9-00d1-494f-a4fc-7d9cf37dcfcc)

There is a workaround ?

Thanks!

**Comment by p0deje** [comment]
@anthonypillot If I understand it correctly, your first screenshot shows there are no visible items? And then on the next popup - it's not empty? Does it happen all the time?

**Comment by anthonypillot** [comment]
Absolutely. First screenshot that doesn't show anything, even if my pinned elements ; then, a few seconds later, elements are return. It doesn't happen all the time. I'm trying to analyse the cause. Maybe the element size.

**Comment by anthonypillot** [comment]
Just a message to thank you for your excellent work. Your application is extraordinary and now mandatory for me @p0deje @anandaray.
