### ISSUE TITLE
One suggestion

### ISSUE THREAD

**Issue by xioqing** [p0deje/Maccy#533]
Maybe it would be better to integrate the pins together.
Thank you.

**Comment by p0deje** [comment]
What do you mean?

**Comment by xioqing** [comment]
> 

I meant to put Pins in the same folder, Instead of being scattered in the list.

**Comment by p0deje** [comment]
Got it, see #307.

**Comment by xioqing** [comment]
> Got it, see #307.

OK, Thank you
