### ISSUE TITLE
Macy doesnt auto paste on the 2nd screen

### ISSUE THREAD

**Issue by RISHANGSHARMA** [p0deje/Maccy#534]
When I try to paste using the option of "paste automatically" . It works properly on the first screen , but not on the extended display

**Comment by p0deje** [comment]
1. Can you please provide the Maccy version you use? You can get it in the "About" window.
2. Can you please record a screen video showing the problem? You can do this using QuickTime.app.
3. Can you please share the output of running `defaults read org.p0deje.Maccy` in Terminal.app?

**Comment by chunyang-wen** [comment]
@p0deje maybe you should try to create some issue template 😃

**Comment by alwaysshrek** [comment]
@p0deje I've the same issue due to which I've had to disable the pasteByDefault option. It happens when the paste option is used on two windows of the same application - for example Chrome windows which are open on both the primary and secondary monitor. When I try to paste on secondary, it pastes on Chrome in primary window instead.
Please find the info you requested for me below:
1. Version 0.26.2 (17)
2. Please find [here](https://github.com/p0deje/Maccy/assets/499593/02e9c6ed-5c57-4782-98a5-441b4c64c3f0). It got pasted on the chrome open on the primary monitor while the recording is on the secondary monitor.
3. Please see below:

```
➜ defaults read org.p0deje.Maccy
{
    "KeyboardShortcuts_popup" = "{\\"carbonModifiers\\":2048,\\"carbonKeyCode\\":8}";
    "NSStatusItem Visible Item-0" = 1;
    "NSWindow Frame SUStatusFrame" = "664 709 400 134 0 0 1728 1079 ";
    "NSWindow Frame SUUpdateAlert" = "554 510 620 398 0 0 1728 1079 ";
    "NSWindow Frame com.sindresorhus.Preferences.FrameAutosaveName" = "-1313 396 542 440 -1920 37 1920 1055 ";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2023-06-23 15:54:16 +0000";
    SUUpdateGroupIdentifier = 3693135621;
    WebKitDefaultFontSize = 13;
    WebKitJavaEnabled = 0;
    WebKitJavaScriptEnabled = 0;
    WebKitPluginsEnabled = 0;
    WebKitStandardFont = "-apple-system-font";
    WebKitUserStyleSheetEnabledPreferenceKey = 1;
    WebKitUserStyleSheetLocationPreferenceKey = "/Applications/Maccy.app/Contents/Frameworks/Sparkle.framework/Resources/ReleaseNotesColorStyle.css";
    enabledPasteboardTypes =     (
        "public.png",
        "public.rtf",
        "public.tiff",
        "public.html",
        "public.utf8-plain-text"
    );
    hideFooter = 0;
    hideTitle = 1;
    history = {length = 42, bytes = 0x62706c69 73743030 a0080000 00000000 ... 00000000 00000009 };
    historySize = 115;
    ignoredPasteboardTypes =     (
        "com.typeit4me.clipping",
        "net.antelle.keeweb",
        "de.petermaurer.TransientPasteboardType",
        "Pasteboard generator type",
        "com.agilebits.onepassword"
    );
    maxMenuItems = 10;
    migrations =     {
        "2020-02-22-history-item-add-copied-at" = 1;
        "2020-02-22-history-item-add-number-of-copies" = 1;
        "2020-04-18-switch-storage-to-core-data" = 1;
        "2020-04-25-allow-custom-ignored-types" = 1;
        "2020-06-19-use-keyboardshortcuts" = 1;
        "2020-09-01-ignore-keeweb" = 1;
        "2021-02-20-allow-to-customize-supported-types" = 1;
        "2021-06-28-add-title-to-history-item" = 1;
        "2021-10-16-remove-dynamic-pasteboard-types" = 1;
        "2022-08-01-rename-suppress-clear-alert" = 1;
        "2022-11-14-add-html-rtf-to-supported-types" = 1;
        "2023-01-22-add-regexp-search-mode" = 1;
    };
    pasteByDefault = 1;
    popupPosition = cursor;
    removeFormattingByDefault = 1;
    searchMode = fuzzy;
    showInStatusBar = 1;
    showRecentCopyInMenuBar = 0;
}
```

**Comment by harshavarma** [comment]
I have the same issue. Really appreciate it if this can be prioritised.

**Comment by p0deje** [comment]
@harshavarma @ignorantshr Do you experience it in Chrome too or in other apps?

**Comment by ignorantshr** [comment]
> @harshavarma @ignorantshr Do you experience it in Chrome too or in other apps?

Yes, reproduced in VSCode

**Comment by alwaysshrek** [comment]
I am not able to reproduce the issue after upgrading the below:
- MacOS Monterey v12.6.7 from v12.6.6 
- Maccy v0.26.2 to v0.26.5

**Comment by harshavarma** [comment]
I just upgraded Maccy to v0.26.5 and I can still reproduce. Trying to paste in the Chrome address bar on a secondary monitor simply changes the focus to the chrome window in the primary monitor without pasting. 
`MacOS 13.4.1`

**Comment by ignorantshr** [comment]
after I upgraded Maccy to v0.26.5, in runs well in vscode. MacOS 13.2.1

**Comment by p0deje** [comment]
I've just tested on Maccy 0.26.5 and macOS 13.4.1 - both Chrome and VSCode work fine. If someone can provide a reliable way to reproduce the issue or at least record a video showing the problem - it would be a good start.

**Comment by p0deje** [comment]
Going to close since no response for several months. Feel free to re-open with more details.
