### ISSUE TITLE
Make paste automatically activated by default.

### ISSUE THREAD

**Issue by FarukOzderim** [p0deje/Maccy#535]
Hello, Maccy does not paste, what might be the problem and how can I fix it?

installation: brew 
Current version: [0.26.2,17]

macOS version: 13.1
keyboard layout: us

**Comment by FarukOzderim** [comment]
https://user-images.githubusercontent.com/44067394/227779654-3d814f46-3403-4356-be4e-1684094e1024.mp4

**Comment by FarukOzderim** [comment]
nvm, the pasting was with option+return, not only return :D

Though it might make sense to enable paste automatically by default.

**Comment by p0deje** [comment]
Duplicate of #500
