### ISSUE TITLE
hotkey to directly paste 2nd item without invoking app

### ISSUE THREAD

**Issue by GorvGoyl** [p0deje/Maccy#536]
This idea comes from a clipboard manager I used on Windows. could you consider adding a hotkey that'd directly paste the 2nd item in the clipboard without having the user to invoke the app first?

**Comment by p0deje** [comment]
You can already do this by creating your own custom workflow in Shortcuts.app - see https://github.com/p0deje/Maccy/issues/374#issuecomment-1231716750 for details.
