### ISSUE TITLE
Auto update option

### ISSUE THREAD

**Issue by retrowiseninja** [p0deje/Maccy#54]
Can the app have the ability to request update or auto-update within the app

**Comment by p0deje** [comment]
Yes, of course, but that's really low in my priorities. I'd happily merge PR which implements this.

**Comment by georgesnow** [comment]
sparkle might be the way to go. It seems pretty popular for macos open source apps

**Comment by divyanshu013** [comment]
As a workaround, you may watch releases only to be notified of new releases and update manually :)

**Comment by p0deje** [comment]
Added in 0.9.0
