### ISSUE TITLE
Copying of text selected from previewed PDF in browser does not work

### ISSUE THREAD

**Issue by tonewarper** [p0deje/Maccy#542]
When clicked on as an attachment from within a very common email client (Google Workspace), sometimes copied text is captured, and sometimes not (if the highlighted selection before copying goes over more than one page). This is a frequent productivity flow. Is this because of an Ignore pasteboard type inclusion, or a bug?

<img width="405" alt="image" src="https://user-images.githubusercontent.com/46685787/229274161-7f7f983f-e8ec-44a1-af59-384860a20148.png">

Using latest Chrome.

**Comment by p0deje** [comment]
I cannot reproduce the problem, can you share step-by-step instruction including browser and PDF file?

**Comment by tonewarper** [comment]
Strange. A phantom problem. It was reproducible for me; yet now I cannot reproduce it either. Will reopen if I encounter again.
