### ISSUE TITLE
Adding HotKey Bindings to Search Box

### ISSUE THREAD

**Issue by isecret** [p0deje/Maccy#543]
In many cases, quick navigation requires the use of the search function. However, currently, the user needs to use the mouse to focus on the search box. It would be helpful to add a keyboard shortcut, such as CMD+F, to quickly focus on the search box.

**Comment by p0deje** [comment]
@isecret You don't need to focus search field - just start typing what you want to search and it will automatically focus itself.

**Comment by isecret** [comment]
> @isecret You don't need to focus search field - just start typing what you want to search and it will automatically focus itself.

Okay, it looks like I've been using the search function incorrectly before.
