### ISSUE TITLE
HEIC images don't appear as images

### ISSUE THREAD

**Issue by mhillebrand** [p0deje/Maccy#548]
<img width="474" alt="image" src="https://github.com/p0deje/Maccy/assets/286198/d6a2f4c4-7c8a-44c2-931d-95e47562fecd">

**Comment by p0deje** [comment]
That's expected because there is a difference between copying a file and its contents:
- If you copy a HEIC **file** (e.g. from Finder) - it is shown as a file.
- If you copy a HEIC **image** (e.g. open the file in Preview, right-click and copy) - it is shown as an image.
