### ISSUE TITLE
Pinned items beyond 26 get unpinned after app restart

### ISSUE THREAD

**Issue by fanfaretak** [p0deje/Maccy#552]
Pinned items beyond 26 get unpinned after app restart.
Not sure if this is an expected limitation or a bug. But it would be good if the app can save more than 26 pinned items across app restart.

Reproduce steps:
1. Have more than 26 pinned items. (At this point, those pinned items beyond 26 do show up in the pinned list but without hotkeys available since there are only 26 English alphabets, which is expected and acceptable.)
2. Restart app.
3. Only 26 pinned items are displayed in the pinned list, those pinned items beyond 26 (27th, 28th, 29th, etc) got removed from pinned list, and moved back to unpinned list.

**Comment by p0deje** [comment]
Indeed that's a limitation that I knew existed, but nobody ever complained 😀
This happens because an item is considered pinned as long as it has a "pin letter". Since 26 runs out of letters, it's not working anymore. I am not sure what's the best way to solve the issue though - allow them to be pinned but without letters?

**Comment by fanfaretak** [comment]
> Indeed that's a limitation that I knew existed, but nobody ever complained 😀
> This happens because an item is considered pinned as long as it has a "pin letter". Since 26 runs out of letters, it's not working anymore. 

oh I see. Thanks for the explanation. 
I am a heavy user and have been using Maccy daily for several months now, I love it, super lightweight and easy-to-use with all the necessary features I need, and my list of pinned items keep growing in the last a few months, eventually exceeding the number of 26, thus encountering this limitation. It would be really appreciated if it could allow more than 26 pinned items saved across restart.

>I am not sure what's the best way to solve the issue though - allow them to be pinned but without letters?

Yes. IMHO it's totally OK to not have a letter hotkey assigned to a pinned item if number is beyond 26. User can still quickly search or manually select the pinned item from the list without hotkey (as pinned items are always at the top, very easy to find, and immune from "clear history").

**Comment by p0deje** [comment]
Ok, I'll add support for keyless pins.

**Comment by p0deje** [comment]
Fixed, will be available in the next release. Please, keep in mind that you won't be able to remove keys via Preferences.
