### ISSUE TITLE
Reset to Default Settiing.

### ISSUE THREAD

**Issue by chettri015** [p0deje/Maccy#554]
I would like it to reset to the default setting.
I changed a bunch of setting from the menu bar; now I can only see the clipboard history.
I no longer see preferences when I click maccy icon on the menu bar.
I tried uninstalling and deleting supporting files and reinstalling still no luck.

**Comment by p0deje** [comment]
You can press CMD+, even if Preferences is not visible to open the window.
To fully reset, you can remove the whole Maccy directory by running the following command in Terminal.app:

```
rm -rf ~/Library/Containers/org.p0deje.Maccy
```
