### ISSUE TITLE
Rewrite rules text on paste

### ISSUE THREAD

**Issue by nurdann** [p0deje/Maccy#559]
Is it possible to rewrite certain texts? For example, wrap a link in a rich text. For example `https://github.com/p0deje/Maccy/pull/539` to `p0deje/Maccy#539` and make it clickable as well.

**Comment by p0deje** [comment]
You can totally do that by creating a custom Shortcuts workflow. Please see some examples of how to do this in https://www.reddit.com/r/macapps/comments/11sxz5t/maccy_026/.

**Comment by nurdann** [comment]
When I open Shortcuts.app, I can't see any options for Maccy
<img width="358" alt="image" src="https://github.com/p0deje/Maccy/assets/23486971/4cf815a5-aec1-4c8a-9f69-e72a4f86f8fb">

**Comment by p0deje** [comment]
Make sure you use the most recent version of Maccy.
<img width="306" alt="Screenshot 2023-07-21 at 12 22 56" src="https://github.com/p0deje/Maccy/assets/665846/9e28cfe5-b3e4-4c7d-b0a9-d3e36c6953d8">
