### ISSUE TITLE
Copy and paste between devices

### ISSUE THREAD

**Issue by jackmu95** [p0deje/Maccy#56]
When Maccy is running it prevents the [Universal Clipboard](https://support.apple.com/en-us/HT209460) feature between iOS und macOS.

Copying on macOS an pasting on iOS works.
Copying on iOS and pasting on macOS doesn't work.

**Comment by p0deje** [comment]
I've just tried this and it worked fine. I've copied on my iPhone and then pasted on macOS. Worked perfectly. Also, Maccy properly saved the copied item to history.

Can you give me more details? What do you copy? Which version of iOS and macOS?

**Comment by jackmu95** [comment]
I digged a bit into it and found out that copying text works fine.
I was originally copying a URL from Chrome. Copying a URL from Safari works fine.

iOS 13.1.3
macOS 10.15
