### ISSUE TITLE
Exclude chrome extensions from clipboard history

### ISSUE THREAD

**Issue by Aleexiiiiiii** [p0deje/Maccy#561]
Hello,
I actually use [Passbolt](https://www.passbolt.com/) as a password manager, and it only have a chrome extension, not an app. 
How can I exclude it from the clipboard history

Thx

**Comment by p0deje** [comment]
If it's a Chrome extension - it looks like a copy from Chrome itself for the system. I don't think there is a way for you to do it, but you can reach out to Passbolt developers so maybe they can find a way to adopt http://nspasteboard.org which specifies how to mark copied content as confidential - this is supported by Maccy automatically.
