### ISSUE TITLE
When copy delete double spaces

### ISSUE THREAD

**Issue by kubomubo** [p0deje/Maccy#562]
Is it possible to make an option when I copy a sentence, to delete double spaces or however many spaces there are between words and at the beginning and end of the sentence, so that when I paste the sentence will be without spaces.

- example, sentence:
`     Is it  possible to      make an option?      `
- to become:
`Is it possible to make an option?`

**Comment by Slackadays** [comment]
This might be possible if #540 gets implemented as a regex with which to ignore content

**Comment by p0deje** [comment]
You can write a custom shortcut workflow to get copy from Maccy and remove all white spaces. Please see post https://www.reddit.com/r/macapps/comments/11sxz5t/maccy_026 showing some examples.
