### ISSUE TITLE
Show full history

### ISSUE THREAD

**Issue by hariec** [p0deje/Maccy#565]
Hello! 
I tried to find some mention of viewing the entire history in open tasks, but I could not!

- I can't find buttons to view the entire history of the buffer and not just the last 10 (as many as indicated in the settings) I know that you can use the search, but you don't always remember what characters were there if it's a rarely used password!

If this is not possible, then it would be good to add such functionality, it seems to me that this can be useful to many people.

Thanks a lot!

**Comment by p0deje** [comment]
Set Numer of items to 0 in Appearance preferences.
