### ISSUE TITLE
Menu bar icon is a bit blurred

### ISSUE THREAD

**Issue by oferRounds** [p0deje/Maccy#572]
Except for that – lovvveee your library! 
<img width="153" alt="image" src="https://github.com/p0deje/Maccy/assets/1477963/fab6d03d-6fb1-4c6e-937d-623b435e6b48">

**Comment by p0deje** [comment]
@oferRounds Is it only for scissors icon? What macOS version do you use?

**Comment by oferRounds** [comment]
Hi @p0deje! Oh I see now that in fact it only happens with the scissors icon – the two others looks great and sharp
My OS version is 13.4.1
