### ISSUE TITLE
Spaces on the beginning of the text

### ISSUE THREAD

**Issue by KeesvdM** [p0deje/Maccy#573]
Whenever I want to copy a certain text after a comma, I'll put a space at the beginning of the text. But Macy doesn't copy the comma; so I have to manually insert a space. Is there a trick or solution for this issue?

**Comment by p0deje** [comment]
@KeesvdM Maccy copies exactly what you copy - it doesn't remove spaces from the copy. It hides spaces in the history list so that all items look aligned, but when you paste it - it should be there.

**Comment by KeesvdM** [comment]
Hi Alex,

In a pinned copy it doesn’t paste the space at the beginning of the text.

**Comment by p0deje** [comment]
The screenshot was not uploaded, I don't see it.

**Comment by KeesvdM** [comment]
￼

**Comment by p0deje** [comment]
When you send an email with the attached screenshot - GitHub doesn't handle it. You need to manually open this issue manually in GitHub UI and upload the screenshot.

**Comment by KeesvdM** [comment]
Here it is. 
<img width="490" alt="1 screenshot 1" src="https://github.com/p0deje/Maccy/assets/66518907/934da950-25c2-41fd-b53d-16afb3ced169">

**Comment by p0deje** [comment]
Can you also upload screenshot of preview window (it shows after a second when you hover the window)?

**Comment by KeesvdM** [comment]
Yes: 
![Uploading Screenshot 2023-07-06 at 15.27.12.png…]()

**Comment by KeesvdM** [comment]
<img width="871" alt="Screenshot 2023-07-06 at 15 27 12" src="https://github.com/p0deje/Maccy/assets/66518907/01c723e0-8069-4455-b0cf-3a5467f94683">

**Comment by p0deje** [comment]
Right, so the contents don't have the leading space, it's only the _title_ of the copy that has it. For pinned items, title can be different fro the contents.

**Comment by KeesvdM** [comment]
But how do I get a space in the content?

**Comment by p0deje** [comment]
Remove this pin, copy a new one with a leading space and pin it.

**Comment by KeesvdM** [comment]
Thanks! It works!!

**Comment by p0deje** [comment]
Great!
