### ISSUE TITLE
macOS Ventura 13.4.1 Maccy copied items disappear and reappear

### ISSUE THREAD

**Issue by barenko** [p0deje/Maccy#575]
The copied items are in maccy, but I can only see them if I copy something in the place where I want to paste, otherwise the maccy copied list appears empty.

- I have some copies in maccy. 
- I click in maccy icon (no previous copied item appeared)
- I copy some text from iterm (or other app)
- I open maccy using shortcut (cmd+shift+V) (the current copy and all others appeared to be copied)
- I change the app focus and go to maccy icon (the previous copied items disappear again)
- I change the focus to iterm and try to paste using the shortcut (no previous copied item appeared)
- I copy some text from iterm
- I use the paste shortcut (all de copied items appeared)

I think that there is some issue related to app focus loss...

The `defaults read org.p0deje.Maccy` is here:
```
{
    "KeyboardShortcuts_popup" = "{\\"carbonModifiers\\":768,\\"carbonKeyCode\\":9}";
    "LaunchAtLogin__hasMigrated" = 1;
    NSNavLastRootDirectory = "/Applications";
    NSNavPanelExpandedSizeForOpenMode = "{800, 448}";
    "NSStatusItem Preferred Position Item-0" = 181;
    "NSWindow Frame NSNavPanelAutosaveName" = "464 473 800 448 0 0 1728 1079 ";
    "NSWindow Frame SUStatusFrame" = "664 709 400 134 0 0 1728 1079 ";
    "NSWindow Frame SUUpdateAlert" = "554 510 620 398 0 0 1728 1079 ";
    "NSWindow Frame com.sindresorhus.Preferences.FrameAutosaveName" = "593 290 442 493 0 0 1728 1079 ";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2023-07-07 13:10:57 +0000";
    SUUpdateGroupIdentifier = 108853097;
    WebKitDefaultFontSize = 13;
    WebKitJavaScriptEnabled = 0;
    WebKitPluginsEnabled = 0;
    WebKitStandardFont = "-apple-system-font";
    WebKitUserStyleSheetEnabledPreferenceKey = 1;
    WebKitUserStyleSheetLocationPreferenceKey = "/Applications/Maccy.app/Contents/Frameworks/Sparkle.framework/Resources/ReleaseNotesColorStyle.css";
    clearOnQuit = 0;
    enabledPasteboardTypes =     (
        "public.html",
        "public.rtf",
        "public.tiff",
        "public.file-url",
        "public.utf8-plain-text",
        "public.png"
    );
    historySize = 15;
    ignoreEvents = 0;
    ignoredApps =     (
        "com.bitwarden.desktop"
    );
    ignoredPasteboardTypes =     (
        "com.typeit4me.clipping",
        "net.antelle.keeweb",
        "Pasteboard generator type",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType"
    );
    imageMaxHeight = 85;
    maxMenuItems = 15;
    menuIcon = scissors;
    migrations =     {
        "2020-04-25-allow-custom-ignored-types" = 1;
        "2020-06-19-use-keyboardshortcuts" = 1;
        "2020-09-01-ignore-keeweb" = 1;
        "2021-02-20-allow-to-customize-supported-types" = 1;
        "2021-06-28-add-title-to-history-item" = 1;
        "2021-10-16-remove-dynamic-pasteboard-types" = 1;
        "2022-08-01-rename-suppress-clear-alert" = 1;
        "2022-11-14-add-html-rtf-to-supported-types" = 1;
        "2023-01-22-add-regexp-search-mode" = 1;
    };
    pasteByDefault = 1;
    popupPosition = center;
    popupScreen = 0;
    searchMode = fuzzy;
    showRecentCopyInMenuBar = 0;
}
```

I uploaded a youtube video showing the issue: [BUGREPORT: macOS Ventura 13.4.1 Maccy copied items disappear and reappear](https://www.youtube.com/embed/HG_k_JKrUl0)

macOS Ventura 13.4.1
Maccy 0.26.5
the behavior using iterm is replicated on vscode, chrome and others.

**Comment by p0deje** [comment]
Hmm, could it be that you run 2 instances of Maccy at the same time? Or could you also try disabling the application that hides the menu bar icons?

**Comment by barenko** [comment]
I have only one maccy instance running:
<img width="756" alt="image" src="https://github.com/p0deje/Maccy/assets/49086/719f0e2b-df47-435d-956e-effd92dd76d2">

And I disabled the menu bar manager application (and restarted the maccy):
<img width="615" alt="image" src="https://github.com/p0deje/Maccy/assets/49086/13f0234e-7fc8-4507-82c9-b0db01e04b38">

Same behavior showed in the video...

**Comment by barenko** [comment]
I use iBar. 
I created a fresh user and the maccy works properly. I also configured iBar with maccy in this new user and maccy still works well. I don't know what can conflict with maccy, this is odd.

**Comment by p0deje** [comment]
In the current user, can you try quitting iBar and see if it helps?

**Comment by barenko** [comment]
I disabled iBar and prevent it to start on login. Restarted the mac and the issue remains. This is not related to iBar (i think).

**Comment by barenko** [comment]
What is the better way to remove all maccy cache and config files from my machine and clean reinstall maccy?

**Comment by p0deje** [comment]
Ok, then I suppose we're good. Feel free to re-open if the issue happens again.

**Comment by barenko** [comment]
I restarted the macOS after a couple of days and the issue comes back. Same problem. I didn't configure or installed anything new. (maybe some auto-updates in background, nothing more).

`defaults read org.p0deje.Maccy`
```
{
    "KeyboardShortcuts_popup" = "{\\"carbonModifiers\\":768,\\"carbonKeyCode\\":9}";
    "LaunchAtLogin__hasMigrated" = 1;
    NSNavLastRootDirectory = "/Applications";
    NSNavPanelExpandedSizeForOpenMode = "{800, 448}";
    "NSStatusItem Preferred Position Item-0" = 5608;
    "NSWindow Frame NSNavPanelAutosaveName" = "464 473 800 448 0 0 1728 1079 ";
    "NSWindow Frame com.sindresorhus.Preferences.FrameAutosaveName" = "717 539 442 493 0 0 1728 1079 ";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2023-07-16 18:03:25 +0000";
    SUUpdateGroupIdentifier = 1420399208;
    enabledPasteboardTypes =     (
        "public.tiff",
        "public.rtf",
        "public.file-url",
        "public.utf8-plain-text",
        "public.html",
        "public.png"
    );
    hideFooter = 0;
    hideTitle = 1;
    historySize = 15;
    ignoredApps =     (
        "com.bitwarden.desktop"
    );
    ignoredPasteboardTypes =     (
        "de.petermaurer.TransientPasteboardType",
        "net.antelle.keeweb",
        "com.typeit4me.clipping",
        "Pasteboard generator type",
        "com.agilebits.onepassword"
    );
    maxMenuItemLength = 85;
    maxMenuItems = 15;
    menuIcon = scissors;
    migrations =     {
        "2020-04-25-allow-custom-ignored-types" = 1;
        "2020-06-19-use-keyboardshortcuts" = 1;
        "2020-09-01-ignore-keeweb" = 1;
        "2021-02-20-allow-to-customize-supported-types" = 1;
        "2021-06-28-add-title-to-history-item" = 1;
        "2021-10-16-remove-dynamic-pasteboard-types" = 1;
        "2022-08-01-rename-suppress-clear-alert" = 1;
        "2022-11-14-add-html-rtf-to-supported-types" = 1;
        "2023-01-22-add-regexp-search-mode" = 1;
    };
    pasteByDefault = 1;
    searchMode = fuzzy;
    showRecentCopyInMenuBar = 0;
}
```

**Comment by p0deje** [comment]
Hmm, can you try increasing storage size by 1 or decreasing number of items by 1 and see if it helps?

**Comment by p0deje** [comment]
Probably duplicate of #532

**Comment by barenko** [comment]
Its right. If I reach the max storage size, I need to add a new one to the already saved items shows in the current application. I need to do it for each app.
