### ISSUE TITLE
Request: preview the content before paste

### ISSUE THREAD

**Issue by katrichnikitos** [p0deje/Maccy#578]
Would be grate to get an option to preview the content before pasting to avoid accidental paste of unrelated text. It can be a big problem with such wrong paste in a terminal for example.

**Comment by p0deje** [comment]
There is already a preview popup that shows after you hover over the history item for about a second. Delay can be changed in preferences.

**Comment by katrichnikitos** [comment]
@p0deje thanks for your reply and many thanks for the awesome app! I meant  an optional popup appearing each time before you paste. 
Anyway I found the workaround: multiline paste warn in iTerm2.
