### ISSUE TITLE
Remap Maccy Keyboard Shortcut

### ISSUE THREAD

**Issue by musabdullah0** [p0deje/Maccy#579]
I'm new to Maccy and having trouble opening the app with keyboard shortcuts. Command + Shift + C doesn't work for me as it is already mapped to entering "developer mode" on Safari. Is there a way to remap the keyboard shortcut for Maccy?

**My setup**
M1 MacBook Pro (14-inch, 2021) on Monterrey (12.5.1)

**Things I've tried**
- create a keyboard shortcut from settings to open the app, isn't possible on Mac natively
- set up an automator script to open it, but that isn't allowed

**Comment by p0deje** [comment]
You can change the shortcut in Maccy's "Preferences..." window.
