### ISSUE TITLE
Sometimes it takes at least 5 seconds to open up the menu after type the shortcut.

### ISSUE THREAD

**Issue by lucky13820** [p0deje/Maccy#58]
I am using 0.5.1. Sometimes after type the shortcut, it will take at least 5 seconds to open up the menu. Sometimes it can be opened instant. I am not sure why. It's really unreliable for me.

**Comment by cheolgook** [comment]
Maybe there were too many items on the menu?

**Comment by lucky13820** [comment]
Yeah, it could be. Although I just realized I am not using the latest version. I updated it, so far it’s working fine.
2019年10月25日 -0700 PM4:52 cheolgook <notifications@github.com>，写道：
