### ISSUE TITLE
Add paste stack to documentation

### ISSUE THREAD

**Issue by faroit** [p0deje/Maccy#580]
i can't get much information about how to use the "Paste stack" in maccy and its not clear to me how it is filled up from just using the app. Maybe a quick usage guide can be added to the documentation?

**Comment by p0deje** [comment]
There is no such thing as a "paste stack" in Maccy.

**Comment by faroit** [comment]
@p0deje My bad. I was evaluating multiple pasteboard managers at the same time. The windows seem to related but the paste stack came from another app. It was confusing me but disabling all but Maccy and the problems are solved !

**Comment by p0deje** [comment]
No worries, also you can take a look at #239 where the discussion about multi-paste happens and the paste stack is one of the proposals.
