### ISSUE TITLE
Loop into clipboard element with same(one)keyboard shortcut

### ISSUE THREAD

**Issue by fhmaisonneuve** [p0deje/Maccy#582]
Flycut have this cool feature

If you press cmd-shift-v repeatedly you switch to the next clipboard element, and so on.

That's nice, because one shortcut key can be used to switch / loop only all element since you get the good one and paste it.

**Comment by p0deje** [comment]
@fhmaisonneuve Can you record a video showing the features - I don't really understand what's so cool about it.

**Comment by rehan-pp** [comment]
I've used a similar clipboard manager on Linux. It is really helpful when you want to copy-paste multiple items from one page to another page.

Copy all items one by one using `cmd+c` they will be saved in the clipboard manager.
Go to the page where you want to paste them, paste the first item using `cmd+v` and press `cmd+shift+x` to remove the first item from the list and select the second item to paste. In this way, you can copy and paste multiple items without switching any UI and only using the keyboard.

To reduce one step, something like `cmd+shift+v` can also be introduced that will past the current item and remove it from the list and select the next item to paste.

**Comment by p0deje** [comment]
I will allow to implement this via Shortcuts, will keep you posted.

**Comment by p0deje** [comment]
In the next Maccy version, there is a way to delete an item by its position via Shortcuts. This means you can create this simple workflow to implement sequential paste and assign it a global key shortcut:

<img width="1312" alt="Screenshot 2023-11-15 at 18 37 46" src="https://github.com/p0deje/Maccy/assets/665846/0abcfa31-6dc2-455f-b971-084685eabb83">


Here is a quick demo of how it works. There is no separator between pastes, but I think it can be worked around with extra shortcuts.

https://github.com/p0deje/Maccy/assets/665846/72875a12-7879-4e7f-9a75-74188ee91147

**Comment by rehan-pp** [comment]
Thank you very much @p0deje 🙏
