### ISSUE TITLE
Name of the app incorrect (Universal Clipboard)

### ISSUE THREAD

**Issue by adyanth** [p0deje/Maccy#585]
Maccy shows the name of the open app when the clipboard was synced. If possible, showing it as external is better than showing the wrong unrelated app.

**Comment by p0deje** [comment]
So what app should be shown instead? There is no such app as Universal Clipboard.

**Comment by adyanth** [comment]
Anything unique to make it recognizable. If it is possible to get the name of the device that synced it, even better.

But this is not something that needs to be fixed. Just showing the app as external or synced from device is good enough.

PS: Love the work! One of the first apps I install on my devices.

**Comment by p0deje** [comment]
Would saying that it's from "iCloud" be good for your case?

**Comment by adyanth** [comment]
Yup, iCloud sounds correct!
