### ISSUE TITLE
Number of history items to keep.

### ISSUE THREAD

**Issue by ierique** [p0deje/Maccy#588]
Size [Value] for history items to keep is only adjustable by arrows, request to have it saved when the value is typed. 

Seems the maximum is 999. 

![SCR-20230724-oklo](https://github.com/p0deje/Maccy/assets/20937303/b0248377-d516-4924-9d95-af651cb1c0ad)

**Comment by p0deje** [comment]
If you press Enter after typing new value - it's saved.

**Comment by ierique** [comment]
Ah @p0deje - that works, thanks. I was trying 1000 and it was failing, maybe Max=999 would have helped :)

**Comment by eitama** [comment]
Wish we could have 99999 max history :)

**Comment by wookayin** [comment]
See #167 and #202

**Comment by ierique** [comment]
used `defaults write org.p0deje.Maccy historySize  ` to adjust the size 👍🏾 
![image](https://github.com/p0deje/Maccy/assets/20937303/01572a20-5000-426d-a207-749fe1b4c18e)
