### ISSUE TITLE
Show recent copy next to menu icon doesn't seem to work

### ISSUE THREAD

**Issue by 4nur4g** [p0deje/Maccy#589]
Enabling this option removes the menu icon, perhaps it's the expected behaviour. 

However, **recent copy isn't visible next to the menu icon.** 

I'm on Mac OS Ventura 13.3

**Comment by ilyagr** [comment]
I found one workaround for the icon disappearing when it touches the notch: it's possible to reduce spacing between the icons on the menu bar.

https://apple.stackexchange.com/a/465674/513181

I wish Maccy could also do something about it, e.g. warn the user or remove the clipboard text from the icon when it doesn't fit. It felt bewildering when this first occurred and it took me a bit to find this bug and to find out what was going on.
