### ISSUE TITLE
"Paste without formatting" doesn't seem to do anything

### ISSUE THREAD

**Issue by kaqqao** [p0deje/Maccy#591]
I have _Paste without formatting_ selected in the _Preferences_, but I still get formatted text pasted (unless I press the usual modifier).

**Comment by p0deje** [comment]
If you want to paste by default, you also need to enable "Paste automatically".

**Comment by kaqqao** [comment]
> If you want to paste by default, you also need to enable "Paste automatically".

Didn't realize those two options are linked (the UI doesn't prevent you from selecting one without the other). Anyway, I was hoping to get format-less paste without auto-paste. Any chance that's on the road map? I'm trying to replace the unmaintained Clipy.

**Comment by p0deje** [comment]
You can enable "Paste without formatting" and disable "Paste automatically". Then, when you want to paste w/o format, select the item with Option pressed.

**Comment by kaqqao** [comment]
I'm aware of that, but I was looking for no formatting by default, without modifier keys needed.

**Comment by p0deje** [comment]
No, this is not planned. You can instead use the PurePaste app which automatically removes all formatting from copied content.

**Comment by kaqqao** [comment]
Thanks for the quick response :)

**Comment by AB-boi** [comment]
@p0deje Can you explain how paste without formatting works?
Because it's very confusing. I tried several settings and I can't seem to be able to paste without formatting no matter what I do. Thanks in advance!

**Comment by p0deje** [comment]
> [@p0deje](https://github.com/p0deje) Can you explain how paste without formatting works? Because it's very confusing. I tried several settings and I can't seem to be able to paste without formatting no matter what I do. Thanks in advance!

It removes all pasteboard types except plain text before pasting the contents. Normally, formatting is in a separte pasteboard type like rich-text or html.

**Comment by AB-boi** [comment]
> > [@p0deje](https://github.com/p0deje) Can you explain how paste without formatting works? Because it's very confusing. I tried several settings and I can't seem to be able to paste without formatting no matter what I do. Thanks in advance!
> 
> It removes all pasteboard types except plain text before pasting the contents. Normally, formatting is in a separte pasteboard type like rich-text or html.

Okay but how do i paste something without formatting tho?

**Comment by p0deje** [comment]
Depending on your settings, it might be different. Check Maccy preferences, it clearly states how to paste w/o formatting


<img width="622" height="665" alt="Image" src="https://github.com/user-attachments/assets/f486892d-4dc9-4869-823e-2078a8b3e70b" />

**Comment by AB-boi** [comment]
I did that. It still pastes the text with the formatting.

**Comment by p0deje** [comment]
Can you record a screencast/screenshots showing the problem?

**Comment by AB-boi** [comment]
I tried it again it works, I just didn't understand the explanation you gave. You have placed the explanation immediately under the Paste without formatting checkbox, so I thought it was specifically pertaining to it. 

So If I understand it correctly,
assuming have disabled _Paste without formatting_, when I copy formatted text and paste immediately with CMD + V, it pastes with formatting. If I trigger Maccy and select the time with CMD and shift also pressed, it pastes without formatting. Now if I press CMD + V, it still pastes without formatting. If want the formatting back, I need to trigger Maccy again and just select the item without any modifiers, and now it pastes it again with original formatting.

Am i right?

What I don't understand still is the purpose of this 2nd behaviour:

<img width="470" height="125" alt="Image" src="https://github.com/user-attachments/assets/436cdcf4-81db-409a-b46e-9d79e1023413" />

_Select with CMD pressed to copy and paste the item_

What is it needed for? Doesn't just pressing enter do the same thing?

Thank you for your time!

**Comment by p0deje** [comment]
> If want the formatting back, I need to trigger Maccy again and just select the item without any modifiers, and now it pastes it again with original formatting.

You are right.

> Select with CMD pressed to copy and paste the item

It's, but you can, for example, press "CMD+2" to select the second item. This documentation section updates automatically depending on your Behavior settings, so it lists all shortcuts.

**Comment by AB-boi** [comment]
Okay oh okay. Understood!
