### ISSUE TITLE
can't paste images until accessability is granted. but MacOS wasn't prompting for this at first try

### ISSUE THREAD

**Issue by momentmal** [p0deje/Maccy#593]
Am I the only one who struggled with this?

Installed Maccy via Homebrew.
I did not get the MacOS prompt to grant accessibility rights for Maccy when trying to paste a screenshot (clicking on a screenshot entry in the popup menu), so I was not aware this is even needed and I couldnt figure out for minutes how to paste my Screenshots (yes, I know its in the FAQ, but if MacOS can prompt for this, this should always be triggered imho)

 After fiddling around with some settings (enabling automatic pasting and pasting unformatted) and trying again to paste a screenshot then i suddenly got the prompt out of nowhere. Navigated to the right settings, manually added Maccy to the list of apps and voila, it worked.

This might need some tuning so the MacOS prompt is always called on first paste attempt, even with default settings after install. (running Ventura 13.1) If this only works with "automatic pasting" on, I wonder why this is not on by default.

On a sidenote, i think cmd+shift+c instead of cmd+shift+v as a default hotkey is hella confusing, as i need the popup when pasting, not when copying.

**Comment by p0deje** [comment]
Maccy doesn't attempt to paste until you enable "Paste automatically" by default - it would instead place copy to the system clipboard so you can paste by yourself. This doesn't require any accessibility permissions.
