### ISSUE TITLE
Option(⌥) + P command doesn't reflect after installing macOS Sonoma 14.0 Beta (23A5301h)

### ISSUE THREAD

**Issue by aljustiet** [p0deje/Maccy#595]
https://github.com/p0deje/Maccy/assets/114720383/7949be61-6cbd-4919-a693-0936d0b16e73

**Comment by aljustiet** [comment]
https://github.com/p0deje/Maccy/assets/114720383/9ea1fb21-e505-4f9d-968a-63693f5658d7

**Comment by aljustiet** [comment]
https://github.com/p0deje/Maccy/assets/114720383/a03de6f7-32fb-4f47-844f-fceae57cff1b

**Comment by aljustiet** [comment]
https://github.com/p0deje/Maccy/assets/114720383/91fc59dd-191f-4202-95f7-7aef231a75f4

**Comment by aljustiet** [comment]
https://github.com/p0deje/Maccy/assets/114720383/0cceed1c-823a-4547-ad2d-714cc74398dc

**Comment by p0deje** [comment]
Duplicate of #555
