### ISSUE TITLE
 In Chinese context, characters that can be correctly parsed in Word cannot be displayed correctly in Maccy.

### ISSUE THREAD

**Issue by wang93wei** [p0deje/Maccy#597]
For example, characters like this: 
![image](https://github.com/p0deje/Maccy/assets/6371053/e688069f-f104-445d-beef-39e9b58615de)
![image](https://github.com/p0deje/Maccy/assets/6371053/00a419cb-4108-462d-b3b0-67fa61a0db3c)

in the system it is recognized as R

![image](https://github.com/p0deje/Maccy/assets/6371053/14a3eeeb-fc2b-4ee8-85d3-45ff459c2f08)

**Comment by p0deje** [comment]
@wang93wei Can you please share the text you copy?

**Comment by wang93wei** [comment]
> @wang93wei Can you please share the text you copy?

em....I feel like copy and paste is not working on MacOS, let me send you a document for you to take a look at.


[Doc1.docx](https://github.com/p0deje/Maccy/files/12318489/Doc1.docx)

I have an application developed by a Chinese developer called Hapigo. The clipboard function here can display this symbol properly, although there may be some styling issues.

<img width="400" alt="image" src="https://github.com/p0deje/Maccy/assets/6371053/a9cebabb-9cfa-4fc6-bc3a-5f121957168e">

**Comment by p0deje** [comment]
That's how it's being copied unfortunately if you try pasting it into another application - it pastes "R". I think it is just the way the Word application does it. Since it is like that in a system clipboard, I don't think I can do anything on Maccy to fix it.

**Comment by p0deje** [comment]
Please reopen with any new information.
