### ISSUE TITLE
Maccy does not enter any text

### ISSUE THREAD

**Issue by lowercasename** [p0deje/Maccy#6]
On macOS 10.14.1, when I click an item in the Maccy dropdown or menu bar icon menu, or select it with arrow keys and press Enter, no text is entered. Text isn't entered in any app, as far as I can tell.

Otherwise, Maccy is superb! ;)

**Comment by p0deje** [comment]
What do you mean by "No text is entered"? Maccy should not enter any text, it should just copy the text to your clipboard so that later you can paste it in any app.

**Comment by lowercasename** [comment]
Ah, my mistake! That works great - I didn't understand how it was meant to function at first.
