### ISSUE TITLE
Automatically paste by default doesn't work since version 0.6.0 on macOS 10.14.6

### ISSUE THREAD

**Issue by michaelkar** [p0deje/Maccy#60]
After updating to version 0.6.0, setting 
`defaults write org.p0deje.Maccy pasteByDefault true # default is false`
has no effect. 
Moving back to release 0.5.1 'paste by default' works as expected.

**Comment by p0deje** [comment]
It seems like there is a problem with how macOS identifies Maccy and its permissions. I need to figure it out, but try the following workaround for now:

1. Open "Security & Privacy" preferences pane.
2. Open "Accessibility" tab.
3. Unlock to make changes.
4. Remove Maccy from the list.
5. Restart Maccy.
6. Paste from Maccy now.

This should ask for permissions once again and it should work without issues since then.

**Comment by michaelkar** [comment]
@p0deje the proposed flow solved the issue for me. Thank you!

**Comment by Gsazraetr** [comment]
This worked, thank you. Also, I'm having to restart the app for Clear to have an effect.

**Comment by p0deje** [comment]
Should be better in 0.8.0

**Comment by synox** [comment]
Still happending with 0.8.2 on macos 10.15.2 (19C57)

**Comment by p0deje** [comment]
@synox Can you show a screenshot of "Security & Privacy" -> "Accessibility" tab?

**Comment by synox** [comment]
Testing on my second mac: I had 0.7 Past by default did not work. now upgraded to 0.8.2. Paste by default does not work. 
Accessibility does not list Maccy. 
![Screenshot 2020-01-09 at 15 48 20](https://user-images.githubusercontent.com/2250964/72077413-84876c80-32f7-11ea-9c29-62e5f19c2e75.png)

**Comment by p0deje** [comment]
It might be related to the version upgrade. Let me try installing 0.7 and then 0.8.2.

**Comment by p0deje** [comment]
Hm, still can't reproduce.

1. Installed 0.7
2. Tried pasteByDefault and it asked for accessibility permissions
3. Denied
4. Installed 0.8.2
5. Tried pasteByDefault and it asked for accessibility permissions
6. Granted

**Comment by divyanshu013** [comment]
I faced same issue @p0deje, worked after following your solution [here](https://github.com/p0deje/Maccy/issues/60#issuecomment-547497366).

**Comment by dennis-damico** [comment]
same issue as @synox mentioned. On Catalina version `10.15.6`. Can't get it to ask for permissions and doesn't show up on accessibility list

**Comment by whornsby** [comment]
Still present in 0.15.0, but the workaround fixed it
