### ISSUE TITLE
Clear history confirmation dialog not keyboard accessible

### ISSUE THREAD

**Issue by archetyped** [p0deje/Maccy#600]
The Clear History confirmation dialog is not accessible by the keyboard when the "Avoid taking application focus" setting is enabled.

While avoiding taking application focus can be useful when Maccy is displaying the clipboard history and pasting entries, it doesn't make a lot of sense for other aspects of the app (such as confirmation dialogs) to be affected by this setting.

**Comment by p0deje** [comment]
Fixed in 2.0
