### ISSUE TITLE
0.27.0 blue marker bar does not follow mouse cursor

### ISSUE THREAD

**Issue by valynor** [p0deje/Maccy#611]
macOS 13.6, Mac Studio M1

Just installed 0.27.0 and the blue marker bar does not follow the mouse cursor anymore when you open Maccy by clicking on the icon in the menu bar. 

It still works when you open the list via hotkey or if you click in the search field AFTER clicking the menu bar icon - but it stops working in all cases if you move the mouse cursor out of the list and back in.

**Comment by p0deje** [comment]
@valynor Can you record a small video showing the issue? I'm running macOS 14 already and I cannot reproduce the problem.

**Comment by valynor** [comment]
@p0deje 

Here you go: 

https://github.com/p0deje/Maccy/assets/23384233/6fddb6cb-456a-42eb-873f-c3d6a674f394

Worked fine in 0.26.x and immediately broke after installing 0.27.0
I killed & restarted Maccy, no change.

**Comment by alvin96** [comment]
I faced the same issue on my MacBook Air M1, macOS 13.5.2

**Comment by p0deje** [comment]
I only have macOS 14 and macOS 10.14 available and I cannot reproduce them there 😞

**Comment by sidamos** [comment]
Same for me on Ventura 13.6 M1 MacBook Air. Sometimes it works, most of the time it does not. 
When it works, I just need to move the mouse down and up a few times over the items, then it stops working.
But I have also seen it happen with CopyClip, just not as often.

**Comment by valynor** [comment]
@p0deje 

Is it safe to manually go back to 0.26.5 or would that break stuff?

**Comment by p0deje** [comment]
@valynor It should be safe.

**Comment by valynor** [comment]
Thanks. I restored 0.26.5 from Time Machine Backup and Maccy works perfectly again.

**Comment by p0deje** [comment]
> It still works when you open the list via hotkey or if you click in the search field AFTER clicking the menu bar icon - but it stops working in all cases if you move the mouse cursor out of the list and back in.

@valynor Hmm, are you sure it never happens when popping up via hotkey? What if change "Popup at" to "Menu icon" in Maccy "Appearance" preferences?

**Comment by alvin96** [comment]
> I faced the same issue on my MacBook Air M1, macOS 13.5.2
I updated to macOS 14.0 today and the issue seems gone 😂

**Comment by valynor** [comment]
> Hmm, are you sure it never happens when popping up via hotkey? What if change "Popup at" to "Menu icon" in Maccy "Appearance" preferences?

Can't test anymore because I went back to 0.26.5 but I remember I opened it a couple times and it worked. Moving the mouse pointer away and back on the list caused it to break again, though.

**Comment by weisJ** [comment]
I can reproduce the issue (haven't yet updated to Sonoma). The issue lies in this line

https://github.com/p0deje/Maccy/blob/a68ff52911946194ad5636b1ecbe8958d156a0cd/Maccy/RunLoopLocalEventMonitor.swift#L23

It causes mouse movement events to be swallowed (not sure exactly why. Maybe the re-dispatching mechanism doesn't work for mouse events). Changing it to `[.keyDown, .keyUp]` fixes it for me. Though according to the comment
this might cause incorrectly ordered events?

**Comment by p0deje** [comment]
Thank you, @weisJ - I am going to apply your change. My quick testing didn't reveal issues with events order, let's see if any other issue is going to be raised.

**Comment by p0deje** [comment]
@valynor Please try using Maccy 0.27.1 and comment if the issue is still there.

**Comment by sidamos** [comment]
I can confirm that this is now fixed for me on M2 Ventura. Thanks!

**Comment by valynor** [comment]
@p0deje @weisJ 
0.27.1 fixed the bug for me, thanks! ❤️
