### ISSUE TITLE
copied text in ms word gets added to bookmarks in word

### ISSUE THREAD

**Issue by apfelbaum021** [p0deje/Maccy#613]
when selecting and copying text in microsoft word, the copied text gets added to bookmarks in word automatically.

**Comment by p0deje** [comment]
How is this related to Maccy at all?

**Comment by apfelbaum021** [comment]
when maccy is open it happens, when maccy is closed it doesn‘t. that‘s why. Am 27.09.2023 um 7:08 PM schrieb Alex Rodionov ***@***.***>:﻿
How is this related to Maccy at all?

**Comment by p0deje** [comment]
1. Can you please provide the Maccy version you use? You can get it in the "About" window.
2. Can you please record a screen video showing the problem? You can do this using QuickTime.app.
3. Can you please share the output of running `defaults read org.p0deje.Maccy` in Terminal.app?

**Comment by apfelbaum021** [comment]
Anhang verfügbar bis 28.10.2023
i use the maccy version 0.27.1.
you find the video attached to the mail. 
i ran the terminal prompt after i recorded the video. here the output:
{
    "KeyboardShortcuts_popup" = "{\\"carbonModifiers\\":4096,\\"carbonKeyCode\\":9}";
    "LaunchAtLogin__hasMigrated" = 1;
    "NSStatusItem Preferred Position Item-0" = 11261;
    "NSStatusItem Visible Item-0" = 1;
    "NSWindow Frame SUStatusFrame" = "760 691 400 134 0 0 1920 1055 ";
    "NSWindow Frame SUUpdateAlert" = "401 357 638 398 0 0 1440 875 ";
    "NSWindow Frame com.sindresorhus.Preferences.FrameAutosaveName" = "684 336 551 435 0 0 1920 1055 ";
    SUAutomaticallyUpdate = 1;
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2023-09-28 5:55:17 nachm. +0000";
    SUUpdateGroupIdentifier = 1464727439;
    WebKitDefaultFontSize = 13;
    WebKitJavaEnabled = 0;
    WebKitJavaScriptEnabled = 0;
    WebKitPluginsEnabled = 0;
    WebKitStandardFont = "-apple-system-font";
    WebKitUserStyleSheetEnabledPreferenceKey = 1;
    WebKitUserStyleSheetLocationPreferenceKey = "/Applications/Maccy.app/Contents/Frameworks/Sparkle.framework/Resources/ReleaseNotesColorStyle.css";
    avoidTakingFocus = 1;
    enabledPasteboardTypes =     (
        "public.tiff",
        "public.utf8-plain-text",
        "public.html",
        "public.rtf",
        "public.png",
        "public.file-url"
    );
    hideFooter = 1;
    hideSearch = 1;
    hideTitle = 1;
    history = {length = 42, bytes = 0x62706c69 73743030 a0080000 00000000 ... 00000000 00000009 };
    historySize = 50;
    ignoredPasteboardTypes =     (
        "net.antelle.keeweb",
        "com.typeit4me.clipping",
        "de.petermaurer.TransientPasteboardType",
        "com.agilebits.onepassword",
        "Pasteboard generator type"
    );
    imageMaxHeight = 40;
    maxMenuItems = 20;
    migrations =     {
        "2020-02-22-history-item-add-copied-at" = 1;
        "2020-02-22-history-item-add-number-of-copies" = 1;
        "2020-04-18-switch-storage-to-core-data" = 1;
        "2020-04-25-allow-custom-ignored-types" = 1;
        "2020-06-19-use-keyboardshortcuts" = 1;
        "2020-09-01-ignore-keeweb" = 1;
        "2021-02-20-allow-to-customize-supported-types" = 1;
        "2021-06-28-add-title-to-history-item" = 1;
        "2021-10-16-remove-dynamic-pasteboard-types" = 1;
        "2022-08-01-rename-suppress-clear-alert" = 1;
        "2022-11-14-add-html-rtf-to-supported-types" = 1;
        "2023-01-22-add-regexp-search-mode" = 1;
    };
    pasteByDefault = 1;
    pinTo = top;
    playSounds = 0;
    popupPosition = cursor;
    removeFormattingByDefault = 0;
    showInStatusBar = 1;
    showRecentCopyInMenuBar = 0;
}
 

Zum Laden klicken
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAfB7lTVha90-5eErvENZSBwVJFcNAVb2ZzlGKNANvebc3JwdGwk500bM%2F%24%7Bf%7D%3Fo%3DAomaG8qgDolo9n8jW2Fd967weqY6VrD9LQgw25B-olBm%26v%3D1%26x%3D3%26a%3DCAogdA7kOvKqRvxJvDFYnYDCdNcDirmK2PTF0Vo1wU7Cx9sSeBCCkdvnrTEYgqHWu7cxIgEAKgkC6AMA_1krGYxSBBUkVw1aBDnTRsxqJkhOz5T3Qa2l0ZkxyBYi7uDQpEWyG_uELRTL5pLiTKJwEH0PC7bhciY9zOM5vRm0kqmj8smPKdI6-Ge-E07lhIdC7VTI06KE1Ch4Jn3LQg%26e%3D1698516275%26fl%3D%26r%3DC8D1933C-587D-4DE6-91C3-C5B95248C84C-1%26k%3D%24%7Buk%7D%26ckc%3Dcom.apple.largeattachment%26ckz%3D90C3F657-AA6E-4948-BF34-2068ED9EE18B%26p%3D127%26s%3DUXWiIqVacw58EwJ2YZg71pdmlU0&uk=2vag3Ubo6wNrVwla-73pKg&f=maccy_bug_bookmarks%20in%20ms%20word.mov&sz=54439205>maccy_bug_bookmarks in ms word.mov
54.4 MB

**Comment by p0deje** [comment]
Thank you so much for recording the video, I can reproduce the problem on my Word too. This looks really strange and I will fix it.

**Comment by p0deje** [comment]
I fixed the problem and it will be available in the next release. Thank you for a bug report!
