### ISSUE TITLE
Screenshot not automatically added to clipboard

### ISSUE THREAD

**Issue by dmurphyfa** [p0deje/Maccy#614]
When I take a screenshot it is not added to my clipboard history automatically. If I open the screenshot and explicitly copy it is then added to the clipboard history and can be pasted. I have images enabled under storage.

Maccy version: 0.27.0 (21)
macOS version: Ventura 13.6

**Comment by p0deje** [comment]
If you take a screenshot without copying it clipboard, why do you expect it to be in Maccy? You should either copy it explicitly or take screenshot _to clipboard_ using COMMAND+CONTROL+SHIFT key combination.

**Comment by dmurphyfa** [comment]
Bah new laptop, hadn't turned on the setting to automatically copy screenshots to clipboard. Sorry!
