### ISSUE TITLE
Popover location is broken in Sonoma

### ISSUE THREAD

**Issue by weisJ** [p0deje/Maccy#615]
In Sonoma the popover is always shown in the centre of the menu. This is due to the fact that apparently a menu items
view is no longer part of the menus window view hierarchy?! So far I haven't found a way to determine the location of
a menu item relative to anything. It just reports its own size located at `(0,0)` every time.
I tried to go back to the old implementation for the popover but then the application crashes as popovers have can only be shown
relative to views which are part of the view hierarchy (this was the confirmation that indeed the view is no longer attached to the window).

At this moment I don't think this can be solved without a macOS fix (not even sure they consider this a bug, I definitely do).

**Comment by weisJ** [comment]
I think I may have a lead on how to implement a (admittedly very hacky) workaround for Sonoma. Will report back whether it leads somewhere.

**Comment by p0deje** [comment]
This is reported in https://github.com/feedback-assistant/reports/issues/413, I would be happy to find a workaround or merge a PR. Thanks for looking into this!
