### ISSUE TITLE
Search freezes in Sonoma 14.0

### ISSUE THREAD

**Issue by MadSunSos** [p0deje/Maccy#617]
Since I updated to macos Sonoma 14.0 search freezes on input for about 20 seconds before filtering occurs. I am using version 0.27.1 (22). It used to work just fine before macos upgrade. I have tried restarting both Maccy and machine: Macbook pro (M1 pro).

**Comment by akucharczyk** [comment]
Same Issue!

**Comment by p0deje** [comment]
Folks, please try setting a "Number of items" to a smaller value (20-30) in Maccy's Preferences / Appearance. This should make this faster.

Unfortunately, I haven't found a workaround to this performance issue yet. This got broken by Apple and I reported a bug, but they are not responding yet - https://github.com/feedback-assistant/reports/issues/415

**Comment by gemueselasagne** [comment]
Same issue here. Make me aware of how much I love a swiftly running Maccy 🫶🥰

**Comment by forsplay** [comment]
Same issue

**Comment by alvin96** [comment]
same issue

**Comment by ShaTie** [comment]
Same issue(
Can I help somehow?

**Comment by yaroslavyaroslav** [comment]
Have anyone checked is it reproduces on 14.1 beta?

**Comment by ShaTie** [comment]
https://github.com/p0deje/Maccy/issues/555#issuecomment-1731694856 and clear history works for me

**Comment by yaroslavyaroslav** [comment]
@ShaTie Did you reach some significant amount of clipboard history yet? Like 100?

**Comment by ShaTie** [comment]
Yes, I did. I have capped it at 200 records. Works flawlessly. Even mixed search works now

**Comment by yaroslavyaroslav** [comment]
@ShaTie wow, thanks, will try it then

**Comment by basavyr** [comment]
I have it set at size=150 and it seems to work fine.

I'm on the latest version of Sonoma on a MacBook Air M1.

**Comment by parassjain** [comment]
Thanks for the bug fix, it works perfectly fine now with the update.
