### ISSUE TITLE
Window jumps while searching

### ISSUE THREAD

**Issue by weisJ** [p0deje/Maccy#619]
After chasing the content of the search field and the filtering has taken place the window moves slightly down.
Seems to do bigger jumps if the window is opened in the screen centre instead of at the cursor location. Don't know whether
this also happens on versions before Sonoma (haven't really used the search functionality that much).

**Comment by p0deje** [comment]
It's caused by https://github.com/p0deje/Maccy/commit/e71736adc911e7cd88ce287ee10544270bfa4388 and https://github.com/p0deje/Maccy/commit/58549a6825fbc4f487ff5ffe047a6c6243ad6b56tygv

**Comment by weisJ** [comment]
Running `updateFilter(filter: String)` in event tracking mode on the main thread seems to be alleviating it for me. It does move a tiny bit on the first search but afterwards no movement is visible. Also the menu doesn't flicker any more during searches.

**Comment by p0deje** [comment]
How do you run it in event tracking mode?

**Comment by weisJ** [comment]
````swift
RunLoop.main.perform(inModes: [RunLoop.Mode.eventTracking], block: {
  self.updateFilterImpl(filter: filter)
})
````

**Comment by weisJ** [comment]
This seems to also be related to #612. Looks like the after updating the menu the new position is based on the location it was opened at. While #623 should resolve #612 it does not address the this issue. Inherently the problem is still that the menu doesn't report the correct height before being opened.

**Comment by weisJ** [comment]
I have found a solution. Will PR once #623 is through
