### ISSUE TITLE
Why is Maccy sending and receiving data?

### ISSUE THREAD

**Issue by geraltofrivia** [p0deje/Maccy#62]
Activity Monitor suggests that Maccy has sent and received 38 and 68MB of data. Since the clipboard undoubtedly holds some very sensitive text, you could see why this can be troubling. 

Can you please clarify?

<img width="758" alt="Screenshot 2019-11-12 at 10 30 31" src="https://user-images.githubusercontent.com/7823009/68659623-d8fcae80-0537-11ea-877f-9e3bff35d63d.png">

**Comment by p0deje** [comment]
On your screenshot it says that Maccy has 0 in sent/rcvd bytes. What you see in the bottom is for all apps.
