### ISSUE TITLE
Does Maccy hold Command key?

### ISSUE THREAD

**Issue by mags1h** [p0deje/Maccy#621]
I use a web app which shows tooltips when a user holds Command key. Now I have a problem that when I use Maccy shortcut Shift+Command+V and click on some item in clipboard, the web app will display tooltips (while I am not holding the Command key). Paste automatically is enabled. So my question is does Maccy hold Command key when pasting item?

**Comment by p0deje** [comment]
When you select an item in Maccy it tries to paste it by simulating the Command+V press. That's why you might see the tooltip, though it should be a quick key press.

**Comment by mags1h** [comment]
Is it possible that there is a bug and it's simulating holding Command key instead? When I select an item in Maccy and a tooltip appears in the web app, the tooltip doesn't disappear until I manually press Command key, so it looks like the Command key is held. If I press Command+V it works normally and tooltip doesn't appear. Developer of the web app confirmed that tooltip appears only when holding Command key, a quick key press would not trigger it.

**Comment by mags1h** [comment]
Thank you, the web app is not available for public, and the issue is most likely in the web app itself.
