### ISSUE TITLE
Feature: Open popup at text cursor location

### ISSUE THREAD

**Issue by weisJ** [p0deje/Maccy#622]
I think an option to popup the menu at the location of the current text cursor (insertion point) would be a great addition,
as while typing one is already focused on that area of the screen.

I did some research and think that it would be possible to implement using the accessibility api. Because not all applications
adhere to this api a fallback option would probably be necessary.

What do you think about this?

**Comment by p0deje** [comment]
> I did some research and think that it would be possible to implement using the accessibility API. 

The last time I tried it wasn't possible due to App Sandbox limitations. I have a vague memory about that in #150

**Comment by weisJ** [comment]
Oh I must have missed that issue. Too bad it isn’t possible. Though I have seen some applications do this, so there probably is a way to achieve it. Probably very non-trivial though.

**Comment by weisJ** [comment]
Just a quick question. Do I understand it correctly that the issue due to sandboxing only pertains to the store version of the app? If so would enabling the feature only for the manual/brew install be an option?

**Comment by p0deje** [comment]
IIRC it was not related to the App Store / OSS version - both have app sandbox enabled and this API didn't work in both versions.

**Comment by p0deje** [comment]
You are more than welcome to give it a shot again, maybe the sandbox permits these accessibility calls nowadays.

**Comment by weisJ** [comment]
Looks like if sandboxing is enabled accessibility APIs are out of reach even if the user manually grants them through settings to the application. Weirdly enough if I turn off sandboxing then Maccy just doesn't work at all. No menubar icon is visible and the global shortcut doesn't work. Do you know why that could be?
