### ISSUE TITLE
Shortcut cmd+v is not usable anymore for pinned elements

### ISSUE THREAD

**Issue by enzolupia** [p0deje/Maccy#624]
### Maccy Version
0.27.1 (22)

### SO
macOS Sonoma 14.0

## Issue description
In previous versions I was able to use the shortcut cmd+v for pinned elements.
With the latest updated the paste command is taking precedence over the configured cmd+v shortcut.

## Steps to reproduce the issue

1. Add a new pinned element
2. Configure the pinned element shortcut to 'V'
3. Open maccy and press cmd+v 

## What's the expected result?

1. The pinned element marked with cmd+v shortcut is selected

## What's the actual result?

1. The latest copied element is pasted into the search bar.

If this new behaviour is intentional, then the 'V' should not available among the configurable shortcut.

**Comment by p0deje** [comment]
Yeah, I think we should not allow "V" to make sure it doesn't conflict with system keybinding.
