### ISSUE TITLE
[FEATURE] Paste link with metadata 

### ISSUE THREAD

**Issue by LangLangBart** [p0deje/Maccy#625]
Firstly, I want to express my gratitude for this amazing tool. It has significantly improved my productivity. I have a feature request that I believe could make it even better.

### Description
- Paste a link from the clipboard in markdown format, automatically pulling the title.

```
# Syntax
[<title>](<url>)
# Example
[title](https://www.example.com)
```

####  Gif
- The example uses the VSCode [dendronhq/dendron](https://github.com/dendronhq/dendron) extension.
  - Copy a link and execute the command `Dendron: Paste Link`.
  - The title of the link is automatically retrieved.

![Screen Recording 2023-10-05 at 20 06 06](https://github.com/p0deje/Maccy/assets/92653266/d1c5af75-123b-4761-b6ff-4fb175af6558)

### Benefit
It would allow to paste links more nicely from the clipboard when writing in markdown.

#### Possible Workflow with `Maccy`
1. The user copies a link.
2. The link is pasted using a special key combination, e.g. <kbd>⌥ Option</kbd> + <kbd>⌘ Command</kbd> + <kbd>V</kbd>
3. The task is completed.

---

### additional notes
- the  [dendronhq/dendron](https://github.com/dendronhq/dendron) extension uses the [jshemas/openGraphScrape](https://github.com/jshemas/openGraphScraper) module
  - [dendronhq/dendron - PasteLink.ts](https://github.com/dendronhq/dendron/blob/be2bd92551faddffe2e3937b6399e7e5767fe37c/packages/plugin-core/src/commands/PasteLink.ts?plain=1#L62) 
    - [dendronhq/dendron - utils.ts](https://github.com/dendronhq/dendron/blob/be2bd92551faddffe2e3937b6399e7e5767fe37c/packages/plugin-core/src/utils.ts?plain=1#L27C17-L27C17)

**Comment by p0deje** [comment]
@LangLangBart You can try implementing this via Shortcuts - Maccy has actions to retrieve items from its history. Please see some examples in https://www.reddit.com/r/macapps/comments/11sxz5t/maccy_026/.
