### ISSUE TITLE
It is again recommended to add custom pin and delete shortcut keys

### ISSUE THREAD

**Issue by vitaminx** [p0deje/Maccy#627]
@p0deje I need to customize the two shortcut keys in the red box in the picture below, because the two shortcut keys forced by the Maccy software are sometimes occupied by other software, making them unusable.

![image](https://raw.githubusercontent.com/vitaminx/pic/main/github/Maccy-p.png)

**Comment by weisJ** [comment]
Do you have an example where the shortcut collides? While Maccy is open it should take precedence over any application shortcuts.

**Comment by vitaminx** [comment]
> Do you have an example where the shortcut collides? While Maccy is open it should take precedence over any application shortcuts.

iShot
