### ISSUE TITLE
Macyy crash when I constantly deleted the clipboard contents.

### ISSUE THREAD

**Issue by noahhhi** [p0deje/Maccy#628]

**Comment by p0deje** [comment]
1. Can you please provide the Maccy version you use? You can get it in the "About" window.
2. Can you please record a screen video showing the problem? You can do this using QuickTime.app.
3. Can you please share the output of running `defaults read org.p0deje.Maccy` in Terminal.app?

**Comment by noahhhi** [comment]
> 1. Can you please provide the Maccy version you use? You can get it in the "About" window.
> 2. Can you please record a screen video showing the problem? You can do this using QuickTime.app.
> 3. Can you please share the output of running `defaults read org.p0deje.Maccy` in Terminal.app?

Addition, this won’t happen on menu bar.
1.0.27.1
2.[view in accessory.](https://1drv.ms/v/s!Aq6ciqozuYuOk6Y8HoGhhk2aWli8oQ?e=mvjPSB)
3.{
    "KeyboardShortcuts_popup" = "{\\"carbonKeyCode\\":9,\\"carbonModifiers\\":2048}";
    "LaunchAtLogin__hasMigrated" = 1;
    "NSStatusItem Preferred Position Item-0" = 422;
    "NSWindow Frame SUStatusFrame" = "520 556 400 134 0 0 1440 875 ";
    "NSWindow Frame com.sindresorhus.Preferences.FrameAutosaveName" = "643 530 542 262 0 0 1440 875 ";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2023-10-08 05:22:58 +0000";
    SUUpdateGroupIdentifier = 162219098;
    avoidTakingFocus = 1;
    enabledPasteboardTypes =     (
        "public.html",
        "public.tiff",
        "public.file-url",
        "public.rtf",
        "public.utf8-plain-text",
        "public.png"
    );
    historySize = 80;
    ignoredPasteboardTypes =     (
        "com.agilebits.onepassword",
        "Pasteboard generator type",
        "com.typeit4me.clipping",
        "net.antelle.keeweb",
        "de.petermaurer.TransientPasteboardType"
    );
    maxMenuItems = 0;
    menuIcon = clipboard;
    migrations =     {
        "2020-04-25-allow-custom-ignored-types" = 1;
        "2020-06-19-use-keyboardshortcuts" = 1;
        "2020-09-01-ignore-keeweb" = 1;
        "2021-02-20-allow-to-customize-supported-types" = 1;
        "2021-06-28-add-title-to-history-item" = 1;
        "2021-10-16-remove-dynamic-pasteboard-types" = 1;
        "2022-08-01-rename-suppress-clear-alert" = 1;
        "2022-11-14-add-html-rtf-to-supported-types" = 1;
        "2023-01-22-add-regexp-search-mode" = 1;
    };
    pasteByDefault = 1;
    searchMode = fuzzy;
    showRecentCopyInMenuBar = 0;
    sortBy = lastCopiedAt;
}
