### ISSUE TITLE
Extreme search and pin/unpin delays after macOS update

### ISSUE THREAD

**Issue by moaz-magdy** [p0deje/Maccy#638]
MacOS: 14.0 Sonoma
Maccy version: 0.27.1

I face extreme delays (beach ball for 2+ minutes) whenever I start searching after the latest macOS update.
Trying to pin/unpin items keeps loading forever till I force quit the app. On restarting the app, the pinning/unpinning is already executed.

Is there a way to back up the clipboard to uninstall and re-install?

**Comment by p0deje** [comment]
This is the same as #617, will be fixed in the next release - in the meantime see the issue for workarounds.
