### ISSUE TITLE
Pasting with `enter` not working (pasting automatically)

### ISSUE THREAD

**Issue by kelsensantos** [p0deje/Maccy#639]
This issue emerged with Mac OS Sonoma.
Pasting the item from Maccy does not work. It only copies.
After selecting an item on Maccy and hitting `enter`, it is only copied (not pasted). 
After copying it is necessary to hit `ctrl` + `v` to paste it.
Holding `option` or `cmd` before `enter` does not affect this, same behavior. Nor does the option "Paste automatically".
Was this issue addressed at new merges (or will)?

**Comment by weisJ** [comment]
Do you have the latest versions? Works fine for me.

**Comment by kelsensantos** [comment]
I have the last version on App Store. Is there any other newer version ?

**Comment by codeRSH** [comment]
I am using version 0.27.1 . 

I am able to auto paste with `enter` plain text, but images don't auto paste. I need to first select the image through enter and then click `cmd + v` to paste. 

I want to know if it's a bug or it's by design. 

Thanks, 
Ravi

**Comment by p0deje** [comment]
@codeRSH Provide an example where paste doesn't happen so I could reproduce the issue.

**Comment by codeRSH** [comment]
Sorry not able to reproduce this always. It works sometimes and sometimes doesn't. Since, it's not a dealbreaker for me , so I will continue to use the app and come back if the issue occurs repeatedly.

**Comment by p0deje** [comment]
Please try upgrading to 0.28.0 and re-open if the issue is still present.
