### ISSUE TITLE
Remove "Maccy" text from top left of window and expand the search bar?

### ISSUE THREAD

**Issue by kcmannem** [p0deje/Maccy#64]
It'd feel more native if the branding wasn't stuck on the window. Having the search bar expand the full width is also more aesthetically pleasing.

Wouldn't mind this being a hidden setting via `defaults write` either.

Hope I don't come off as insensitive for suggesting this. I like it app!

**Comment by p0deje** [comment]
It should be easy to implement. I'll do it.

**Comment by thewisenerd** [comment]
while we're at it, can we please fix the vertical offset of this search bar? this is _not quite_ vertically aligned to the center;

apologies for being pedantic

<img width="555" alt="Screen Shot 2020-01-04 at 14 17 41" src="https://user-images.githubusercontent.com/2658885/71763030-0d1f9a80-2efd-11ea-9e67-d5c83e3b0c40.png">

**Comment by p0deje** [comment]
@thewisenerd Is the white background above how it looks for you? I know the vertical offsets are a bit off, but IMO they look fine when the background is of the same color:

<img width="293" alt="Screen Shot 2020-01-04 at 10 44 10" src="https://user-images.githubusercontent.com/665846/71767903-4e08b680-2edf-11ea-8a13-7dcb8637fc6d.png">

**Comment by thewisenerd** [comment]
that might be the case, the 'grey' background if intended/unintended, does not extend all the way to the top

<img width="439" alt="Screen Shot 2020-01-04 at 23 04 37" src="https://user-images.githubusercontent.com/2658885/71769390-a3c47980-2f46-11ea-81e6-4245faeb4e37.png">

**Comment by p0deje** [comment]
@thewisenerd How do you make it look like that? Whatever I try it is always shown with the default menu background color.

**Comment by p0deje** [comment]
@kcmannem This is how it's going to look like:

<img width="500" alt="Screen Shot 2020-01-05 at 11 05 30" src="https://user-images.githubusercontent.com/665846/71782717-4adafc80-2fab-11ea-9729-b716472fd949.png">

**Comment by p0deje** [comment]
Available in 0.8.0

**Comment by kcmannem** [comment]
Thank you for working on this!

**Comment by thewisenerd** [comment]
gah! @p0deje you're right. Either setting in `Accessibility > Display`, `Increase Contrast` or `Reduce Transparency` causes this.

**Comment by p0deje** [comment]
@thewisenerd Please check 0.8.1 - it should be better now.

**Comment by thewisenerd** [comment]
awesome!

1. this fixes the background when used with `Increase Contrast` (which forces `Reduce Transparency`), 
2. but doesn't completely work with `Reduce Transparency`

eg, of 2:
<img width="442" alt="Screen Shot 2020-01-06 at 20 24 46" src="https://user-images.githubusercontent.com/2658885/71825991-f165f100-30c2-11ea-86df-34fc60d92df9.png">

Given 2 isn't my use-case, I use `Increase Contrast` this works!

**Comment by p0deje** [comment]
Nice catch! Can you try 0.8.2?

**Comment by thewisenerd** [comment]
nice! all three combinations work.

1. defaults
2. `Increase Contrast` ( + `Reduce Transparency` forced)
3. `Reduce Transparency`
