### ISSUE TITLE
Maccy keeps saying "loading"

### ISSUE THREAD

**Issue by ralphjsmit** [p0deje/Maccy#640]
First, thanks for this great tool! It's so simple that it works perfect. 

I noticed that since the upgrade to macOS Sonoma, Maccy seems to often say just "loading". I also noticed that it has a very weird pattern, I just have to click away and then click again on the icon and second time it works perfect:

https://stream.new/v/RC702h7jsFjsV7Qh2Ed3NuPloyDLbSeBL3mLM42TUlBI

Even with an empty history, it still says "loading": https://stream.new/v/R1QOgZwD8ZuuM7BgjShA00h45jKaWzLxGxI133fH9iE4.

Any idea what could be causing this pattern?

Thanks!

**Comment by p0deje** [comment]
Please try upgrading to 0.28.0 and re-open if the issue is still present.

**Comment by ralphjsmit** [comment]
Thanks Alex, works great!
