### ISSUE TITLE
ignoreEvents not triggering programatically

### ISSUE THREAD

**Issue by rkapur-gds** [p0deje/Maccy#641]
I'm trying this, which seems like it should prevent the password from being stored in Maccy, but it gets stored anyway.
```
testCopyPassword() {
    defaults write org.p0deje.Maccy ignoreEvents true
    echo "testitemcopy" | pbcopy
    defaults write org.p0deje.Maccy ignoreEvents false
}
```

It could be a timing issue where the clipboard turns on too quickly, but not sure if anyone else has encountered this.

**Comment by p0deje** [comment]
Yes, please add a delay before enabling ignoreEvents back (e.g. `sleep 0.5`.
