### ISSUE TITLE
Feature Request: Enable case-insensitive search by default

### ISSUE THREAD

**Issue by takanuva15** [p0deje/Maccy#642]
Hi, thanks for making this great app for Mac. I've been using it with my IDE for code-editing, but I noticed that the search seems to be case-sensitive by default. My code has lots of camelcase variables that I copy-paste around, so I don't want to repeatedly have to match the case while searching for a code snippet within Maccy. Is it possible to add a checkbox option to Maccy so that it can do case-insensitive searches by default when I'm typing in the search box?

(I'm not worried about performance since I don't store a lot on Maccy)

**Comment by weisJ** [comment]
Hi, can you given an example search with a result not being recognised? Search seems to be insensitive to search for me.

**Comment by takanuva15** [comment]
Ok I just realized the issue - in the Preferences, there's an option to change the default search behavior which I hadn't noticed. Mine's was set on "Regular expressions" - after switching it to "Mixed", it now does case-insensitive searching.

![image](https://github.com/p0deje/Maccy/assets/6986426/78d97fe2-aacc-4562-9db2-44a69ef96dd2)
