### ISSUE TITLE
Opening while in Spotlight blocks further keyboard input to active application

### ISSUE THREAD

**Issue by weisJ** [p0deje/Maccy#643]
This is a really weird behaviour:
- Open application where text can be entered (e.g. XCode)
- Open Spotlight
- Open Maccy through shortcut
- Close Maccy and Spotlight
- Application from first step no longer receives keyboard input

Simply by letting Spotlight perform any action e.g open any search in Safari, resolves the issue.
I could only replicate this within Xcode, however I can't rule out that other applications are also affected.
It also can't be reliably replicated. It's probably a Spotlight bug too as I don't have any clue what is happening.

**Comment by p0deje** [comment]
This is not Maccy-specific. Any application that would open above Spotlight w/o deactivating it (e.g. Homerow) would cause the same behavior. I reported this to Apple and cross-posted to https://github.com/feedback-assistant/reports/issues/464.

**Comment by weisJ** [comment]
That's what I figured. Thank you for reporting it to Apple 👍🏼
