### ISSUE TITLE
Can't use searchbar anymore 

### ISSUE THREAD

**Issue by vandrieu** [p0deje/Maccy#645]
Maccy worked great for months.

But I just updated it to the last version a few minutes ago, and now I can't search for text anymore:

https://github.com/p0deje/Maccy/assets/46876905/aaccfa1f-ebde-43ef-91e5-db50d593203f

**Comment by p0deje** [comment]
Duplicate of #617, please see the discussion there.

**Comment by vandrieu** [comment]
Upgrading to Maccy v0.28.0 fixed the issue.
