### ISSUE TITLE
Unable to delete individual history

### ISSUE THREAD

**Issue by kennethlinzj** [p0deje/Maccy#646]
Ever since updating to macOS Sonoma, I'm unable to delete the individual clipboard history using Option + delete. 

macOS Sonoma 14.0
MacBook Air M1
8GB Unified Memory

**Comment by p0deje** [comment]
Please upgrade to Maccy 0.27.1

**Comment by kennethlinzj** [comment]
I am on the latest version. The issue is happening on the latest version.

**Comment by p0deje** [comment]
1. Can you please record a screen video showing the problem? You can do this using QuickTime.app.
2. Can you please share the output of running `defaults read org.p0deje.Maccy` in Terminal.app?

**Comment by kennethlinzj** [comment]
1. 

https://github.com/p0deje/Maccy/assets/32647180/24353ec0-a6ea-4981-9819-584f7002e39a

2.

> {
    "KeyboardShortcuts_popup" = "{\\"carbonModifiers\\":768,\\"carbonKeyCode\\":8}";
    "NSStatusItem Preferred Position Item-0" = 340;
    "NSWindow Frame SUStatusFrame" = "520 570 400 134 0 0 1440 875 ";
    "NSWindow Frame SUUpdateAlert" = "410 372 620 398 0 0 1440 875 ";
    "NSWindow Frame com.sindresorhus.Preferences.FrameAutosaveName" = "408 508 442 365 0 0 1440 875 ";
    SUAutomaticallyUpdate = 1;
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2023-10-18 07:33:58 +0000";
    SUSendProfileInfo = 0;
    SUUpdateGroupIdentifier = 2078273605;
    WebKitDefaultFontSize = 13;
    WebKitJavaEnabled = 0;
    WebKitJavaScriptEnabled = 0;
    WebKitPluginsEnabled = 0;
    WebKitStandardFont = "-apple-system-font";
    WebKitUserStyleSheetEnabledPreferenceKey = 1;
    WebKitUserStyleSheetLocationPreferenceKey = "/Applications/Maccy.app/Contents/Frameworks/Sparkle.framework/Resources/ReleaseNotesColorStyle.css";
    enabledPasteboardTypes =     (
        "public.file-url",
        "public.tiff",
        "public.utf8-plain-text",
        "public.png"
    );
    hideTitle = 0;
    history = {length = 42, bytes = 0x62706c69 73743030 a0080000 00000000 ... 00000000 00000009 };
    historySize = 100;
    ignoredPasteboardTypes =     (
        "de.petermaurer.TransientPasteboardType",
        "net.antelle.keeweb",
        "com.agilebits.onepassword",
        "com.typeit4me.clipping",
        "Pasteboard generator type"
    );
    migrations =     {
        "2020-02-22-history-item-add-copied-at" = 1;
        "2020-02-22-history-item-add-number-of-copies" = 1;
        "2020-04-18-switch-storage-to-core-data" = 1;
        "2020-04-25-allow-custom-ignored-types" = 1;
        "2020-06-19-use-keyboardshortcuts" = 1;
        "2020-09-01-ignore-keeweb" = 1;
        "2021-02-20-allow-to-customize-supported-types" = 1;
        "2021-06-28-add-title-to-history-item" = 1;
        "2021-10-16-remove-dynamic-pasteboard-types" = 1;
    };
    showRecentCopyInMenuBar = 0;
}

**Comment by p0deje** [comment]
Please try upgrading to 0.28.0 and re-open if the issue is still present.

**Comment by kennethlinzj** [comment]
The issue seems partially fixed. It deletes fine, but when I scroll down, nothing can get deleted again. I need to scroll back to the top in order to delete. 


https://github.com/p0deje/Maccy/assets/32647180/7d71ee85-342c-4354-a708-79d1ccb58d60

Also I can't seem to update this app anymore in the Mac App Store, it now costs $15.

**Comment by p0deje** [comment]
> Also I can't seem to update this app anymore in the Mac App Store, it now costs $15.

What? Can you show a link? I can send a promo code to you if smth is wrong, but it shouldn't be like that.

**Comment by kennethlinzj** [comment]
Ah sorry, I think I was confused about how I originally got it. I thought it was via the Mac App Store but it’s probably through the website and I get updates automatically via the app.
