### ISSUE TITLE
Copying items between iPhone and Macbook stopped working

### ISSUE THREAD

**Issue by marcinhlybin** [p0deje/Maccy#649]
It seems that when Maccy is running copying items between iPhone and Macbook stopped working. 
Ideal would be to insert item into Maccy when copying from iPhone with an option to enable/disable this feature.

**Comment by p0deje** [comment]
Maccy doesn't do anything for copies between mac/iPhone - if it stopped working it's likely an iCloud Sync problem. Could also be just a temporary issue.
