### ISSUE TITLE
Add one more shortcut easy paste/copy shortcut to Maccy when copying or pasting to make there be ten shortcuts. (Command/Option 0)

### ISSUE THREAD

**Issue by wakmail** [p0deje/Maccy#659]

**Comment by p0deje** [comment]
I don't understand what you want, can you elaborate?

**Comment by wakmail** [comment]
Only 9 shortcuts ![image](https://github.com/p0deje/Maccy/assets/83027982/759b2960-1f71-4bbf-98f8-8aeae28328bc)

**Comment by wakmail** [comment]
Also, would it be possible to have Maccy pop-up at where I'm typing instead of where my cursor is?

**Comment by p0deje** [comment]
@wakmail What is the need for the 0 shortcut? Do you often need to insert the tenth item?

**Comment by p0deje** [comment]
Closing since no response.
