### ISSUE TITLE
Don't add "Speak selected text" to history

### ISSUE THREAD

**Issue by chrowe** [p0deje/Maccy#66]
![image](https://user-images.githubusercontent.com/240115/69751039-40ac1f80-111c-11ea-8977-21a35e66d63b.png)

I use this Mac feature all the time, which utilizes the clipboard. 

It would be great if there was a way to know that an entry was added to the clipboard using the speak selected text keyboard shortcut and not add those to the history.

**Comment by p0deje** [comment]
I've tried to reproduce this behavior, but whenever the text is spoken it doesn't get added to clipboard. Neither to Maccy nor when I press <kbd>CMD + V</kbd>.

**Comment by chrowe** [comment]
Strange, so it seems like only some applications use the clipboard and some do not.
So far it looks like Chrome, Firefox, VS Code, and Slack all are using the clipboard. These are all browsers or apps build with https://www.electronjs.org/

**Comment by p0deje** [comment]
Unfortunately, I don't think I can figure out that the copied text is coming from "Speak selected text". Both in Chrome and Firefox it's copied with the following types which doesn't allow to reason about the source of copied text: `["public.html", "public.utf8-plain-text"]`.

I'll be happy to implement this but for now, I don't see if it's possible
