### ISSUE TITLE
items copied from firefox browser do not appear in history

### ISSUE THREAD

**Issue by smokefr33** [p0deje/Maccy#662]
hello!
i've been running into this issue since updating to macOS Sonoma 14.0 (worst idea ever....) on my mac mini m1
i'm on firefox 119.0 and copying items (text, images, etc) as per usual and the item copies and pastes as expected, but when the item doesn't appear in the maccy history at all...
i thought that this might be initial growing pains as i know bugs are being worked out, but after the most recent maccy 0.28.0 (23) and still experiencing this issue.
i've also tried uninstalling and reinstalling the app, removing all exclusions from the preferences menu, etc...
any other help would be appreciated, please and thank you!

https://github.com/p0deje/Maccy/assets/149345333/f2541d7c-562c-4422-9b22-79be4f19192b

**Comment by ievgeniikurennyi** [comment]
The same happens for me. No clipboard/history from VS Code, Arc browser, Sticky notes...
Env: M2 mac, macOS 14.0 (23A344)

**Comment by p28nay** [comment]
I have the same problem with firefox too.  Only way I can get it to appear is by pressing command-c multiple times.

**Comment by Drzaln** [comment]
Hi @p28nay, you can check in the Preferences menu, make sure "turn off" is not active

<img width="446" alt="Screenshot 2023-10-31 at 12 47 40" src="https://github.com/p0deje/Maccy/assets/33492469/35afae20-8084-4131-a9b8-55df6ff3a9e2">

**Comment by smokefr33** [comment]
sorry all, i had the title incorrectly noting chrome - but i'm indeed experiencing this issue in firefox primarily...
chrome is working as expected without any issues

**Comment by p0deje** [comment]
@smokefr33 Can you please share the output of running `defaults read org.p0deje.Maccy` in Terminal.app?

**Comment by smokefr33** [comment]
> @smokefr33 Can you please share the output of running `defaults read org.p0deje.Maccy` in Terminal.app?

{
    "KeyboardShortcuts_popup" = "{\\"carbonModifiers\\":768,\\"carbonKeyCode\\":8}";
    "LaunchAtLogin__hasMigrated" = 1;
    "NSStatusItem Preferred Position Item-0" = 555;
    "NSWindow Frame com.sindresorhus.Preferences.FrameAutosaveName" = "714 836 512 436 0 0 2560 1415 ";
    "NSWindow Frame com.sindresorhus.Settings.FrameAutosaveName" = "964 596 501 819 0 0 2560 1415 ";
    enabledPasteboardTypes =     (
        "public.tiff",
        "public.png",
        "public.file-url",
        "public.rtf",
        "public.utf8-plain-text",
        "public.html"
    );
    history = {length = 42, bytes = 0x62706c69 73743030 a0080000 00000000 ... 00000000 00000009 };
    historySize = 65;
    ignoreEvents = 0;
    ignoredPasteboardTypes =     (
    );
    imageMaxHeight = 40;
    lastReviewRequestedAt = 1696994456;
    maxMenuItems = 0;
    menuIcon = clipboard;
    migrations =     {
        "2020-02-22-history-item-add-copied-at" = 1;
        "2020-02-22-history-item-add-number-of-copies" = 1;
        "2020-04-18-switch-storage-to-core-data" = 1;
        "2020-04-25-allow-custom-ignored-types" = 1;
        "2020-06-19-use-keyboardshortcuts" = 1;
        "2020-09-01-ignore-keeweb" = 1;
        "2021-02-20-allow-to-customize-supported-types" = 1;
        "2021-06-28-add-title-to-history-item" = 1;
        "2021-10-16-remove-dynamic-pasteboard-types" = 1;
        "2022-08-01-rename-suppress-clear-alert" = 1;
        "2022-11-14-add-html-rtf-to-supported-types" = 1;
        "2023-01-22-add-regexp-search-mode" = 1;
    };
    numberOfUsages = 179;
    pasteByDefault = 0;
    pinTo = top;
    popupPosition = center;
    popupScreen = 0;
    previewDelay = 1500;
    removeFormattingByDefault = 0;
    searchMode = fuzzy;
    sortBy = lastCopiedAt;
}

**Comment by p0deje** [comment]
Just to confirm, you are running latest Maccy 0.28?

**Comment by smokefr33** [comment]
> Just to confirm, you are running latest Maccy 0.28?

that's correct.
also installed and uninstalled maccy and reinstalled directly from the mac app store, reboots multiples times and in between
also on the latest version of macOS sonoma 14.0

**Comment by p0deje** [comment]
Hmm, I have seen some issues on Sonoma 14.0 (though nothing specific to Firefox) which were gone on 14.1. Any chance you could upgrade?

**Comment by smokefr33** [comment]
> Hmm, I have seen some issues on Sonoma 14.0 (though nothing specific to Firefox) which were gone on 14.1. Any chance you could upgrade?

odd, it wasn't showing 14.1 was available for me, but just poppped up
let me update to sonoma 14.1 and see if that resolves the issue...
will report back shortly!

lesson learned, don't update macOS early - more problems than not...
thanks always!

**Comment by smokefr33** [comment]
upgraded to macon sonoma 14.1.1 and still issues with maccy 0.28... 
again, video for your viewing pleasure

Uploading video1590513663.mp4…

**Comment by p0deje** [comment]
@smokefr33 Could install https://apps.apple.com/us/app/pasteboard-viewer/id1499215709?mt=12 and take a screenshot of it after copying smth from Firefox?

**Comment by smokefr33** [comment]
> @smokefr33 Could install https://apps.apple.com/us/app/pasteboard-viewer/id1499215709?mt=12 and take a screenshot of it after copying smth from Firefox?

![Screenshot 2023-11-13 at 6 11 34 PM](https://github.com/p0deje/Maccy/assets/149345333/ffb89430-a61f-4e06-9b59-d944f8ab2da3)

**Comment by p0deje** [comment]
This makes sense now! Something adds ConcealedType to Firefox copies, which essential marks it as confidential. Maccy respects that and doesn’t store this copy. Firefox itself or some extension is probably doing that. On Nov 13, 2023, at 18:12, smokefr33 ***@***.***> wrote:﻿

@smokefr33 Could install https://apps.apple.com/us/app/pasteboard-viewer/id1499215709?mt=12 and take a screenshot of it after copying smth from Firefox?

**Comment by smokefr33** [comment]
hm, i wonder if this is due to a recent firefox update in that case...
currently on 119.0.1 with private browsing mode - which may be what's marking it as 'confidential'
been looking around the settings and not sure if there's anywhere from a front end, going to look around the about:config

**Comment by smokefr33** [comment]
> @smokefr33 That's private browsing mode thing - I just tested and I can see it adds concealed type when used in private. I don't think there is anything we can do on Maccy side to make it work, so I'm going to close this issue for now. Please, share your findings in comments!

sounds good to me, but just so weird that this was working previously with this setup in firefox and macOS prior to these updates (either firefox or macOS...) 

appreciate your help and will change my process, workflow, or test not in private mode to make this work as expected - thanks again!
