### ISSUE TITLE
Sorting of the history records.

### ISSUE THREAD

**Issue by 0817weakback** [p0deje/Maccy#663]
Regarding the clipboard history sorting issue, when selecting "Last Copy Time" and using the search function (fuzzy search), the feature is not working as expected. It still sorts items based on "First Copy Time."

**Comment by p0deje** [comment]
1. Can you please provide the Maccy version you use? You can get it in the "About" window.
2. Can you please record a screen video showing the problem? You can do this using QuickTime.app.
3. Can you please share the output of running `defaults read org.p0deje.Maccy` in Terminal.app?

**Comment by 0817weakback** [comment]
last day ,i update the Maccy to 0.28.0(23),the problem still exists. and Copy record function is normal.
but today , It seems that it no longer records the clipboard properly, I restart my macbook During this time.
Now I try reinstall it.
Maccy :  0.28.0(23)
system: Macos 12.6.6
the output of running defaults read org.p0deje.Maccy : 

Last login: Tue Oct 31 10:00:42 on ttys001
➜  ~
➜  ~ defaults read org.p0deje.Maccy
{
    "KeyboardShortcuts_popup" = "{\\"carbonModifiers\\":2048,\\"carbonKeyCode\\":46}";
    "NSStatusItem Preferred Position Item-0" = 565;
    "NSWindow Frame SUStatusFrame" = "488 556 400 134 0 0 1440 875 ";
    "NSWindow Frame SUUpdateAlert" = "378 357 620 398 0 0 1440 875 ";
    "NSWindow Frame com.sindresorhus.Preferences.FrameAutosaveName" = "150 252 442 415 0 0 1440 875 ";
    "NSWindow Frame com.sindresorhus.Settings.FrameAutosaveName" = "424 359 442 415 0 0 1440 875 ";
    SUAutomaticallyUpdate = 1;
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2023-10-31 02:04:54 +0000";
    SUSendProfileInfo = 0;
    SUUpdateGroupIdentifier = 3222687160;
    WebKitDefaultFontSize = 13;
    WebKitJavaEnabled = 0;
    WebKitJavaScriptEnabled = 0;
    WebKitPluginsEnabled = 0;
    WebKitStandardFont = "-apple-system-font";
    WebKitUserStyleSheetEnabledPreferenceKey = 1;
    WebKitUserStyleSheetLocationPreferenceKey = "/Applications/Maccy.app/Contents/Frameworks/Sparkle.framework/Resources/ReleaseNotesColorStyle.css";
    enabledPasteboardTypes =     (
        "public.tiff",
        "public.file-url",
        "public.utf8-plain-text",
        "public.html",
        "public.png",
        "public.rtf"
    );
    history = {length = 42, bytes = 0x62706c69 73743030 a0080000 00000000 ... 00000000 00000009 };
    historySize = 400;
    ignoreAllAppsExceptListed = 1;
    ignoredPasteboardTypes =     (
        "net.antelle.keeweb",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
        "Pasteboard generator type",
        "com.typeit4me.clipping"
    );
    migrations =     {
        "2020-02-22-history-item-add-copied-at" = 1;
        "2020-02-22-history-item-add-number-of-copies" = 1;
        "2020-04-18-switch-storage-to-core-data" = 1;
        "2020-04-25-allow-custom-ignored-types" = 1;
        "2020-06-19-use-keyboardshortcuts" = 1;
        "2020-09-01-ignore-keeweb" = 1;
        "2021-02-20-allow-to-customize-supported-types" = 1;
        "2021-06-28-add-title-to-history-item" = 1;
        "2021-10-16-remove-dynamic-pasteboard-types" = 1;
        "2022-08-01-rename-suppress-clear-alert" = 1;
        "2022-11-14-add-html-rtf-to-supported-types" = 1;
        "2023-01-22-add-regexp-search-mode" = 1;
    };
    pasteByDefault = 0;
    popupPosition = center;

    popupScreen = 0;
    removeFormattingByDefault = 0;
    searchMode = fuzzy;
    showRecentCopyInMenuBar = 0;
    sortBy = lastCopiedAt;
}

https://github.com/p0deje/Maccy/assets/55318421/a32e06d9-da8f-495d-9836-921cff544bdc

**Comment by 0817weakback** [comment]
After clearing all data and reinstalling, the current record entries are fewer,  it's working fine now.

**Comment by p0deje** [comment]
Fuzzy changes the sorting order to show more matching items on the top - that's expected.
