### ISSUE TITLE
`opt + p` is not working to pin/unpin items

### ISSUE THREAD

**Issue by JosephTLyons** [p0deje/Maccy#664]
I couldn't remember how to pin or unpin, so I looked at this documentation:

https://github.com/p0deje/Maccy/blob/master/README.md

But `opt + p` isn't working to pin or unpin any items for me.

**Comment by p0deje** [comment]
Please upgrade to 0.28 and try again.

**Comment by JosephTLyons** [comment]
Interesting - unpinning worked for me under 0.28, but pinning does not.

**Comment by JosephTLyons** [comment]
Oh, I think its another bug. If I have to scroll down in the list to pin, then I'm not able to pin.  I can only pin items that can be seen when scrolled to the top of the list.

**Comment by p0deje** [comment]
Ok, it's a known issue fixed in https://github.com/p0deje/Maccy/commit/cb552c185ebef0d65358f2fae84182008e2b04fd, will be available in the next release.
