### ISSUE TITLE
Having to buy Maccy again?

### ISSUE THREAD

**Issue by Webbiweb** [p0deje/Maccy#667]
Maccy has disappeared from my Mac - seemingly merely because I restarted the machine. On the desktop its icon has been replaced by a generic grey and white circle with a line through it and it's no longer listed in the Finder applications. It seems I can only get it back by paying $10 or more. This doesn't seem right - even though I greatly value the app. Please help.

**Comment by p0deje** [comment]
You can always download directly from maccy.app or Github https://github.com/p0deje/Maccy/releases/tag/0.28.0

**Comment by p0deje** [comment]
> by paying $10 or more

You can enter 0 and download for free.
