### ISSUE TITLE
Is there a way to export pins to file?

### ISSUE THREAD

**Issue by troodes** [p0deje/Maccy#668]
Great app, love it and use it daily, thanks you!
Would like to know if there is a way to export/import my pins to file, or otherwise?
Would be handy for migrating pins to secondary system.

**Comment by p0deje** [comment]
There is no way to do so at the moment, though it should be possible by reading the database directly.

**Comment by HsinghaoFu** [comment]
> There is no way to do so at the moment, though it should be possible by reading the database directly.

I have checked the ZHISTORYITEMCONTENT table in the database, and it seems to be encoded in some way. Is this the expected result? How can I decode this field?

Thank you！

**Comment by p0deje** [comment]
It's a binary representation of whatever data is inside. I'm unaware of how to convert it back w/o Swift, here is the code that does that https://github.com/p0deje/Maccy/blob/aec15e84489a0ea22899346be5a060f05d6f14ac/Maccy/Models/HistoryItem.swift#L113-L164.

I would be glad to merge PR that adds `pin` to Shortcuts so you could write a workflow that exports pins.

**Comment by HsinghaoFu** [comment]
@p0deje 

Thank you for your response! I read the code section you mentioned and tried decoding some data. It seems to work well and can run independently of Swift. However, further testing is needed to determine if it can fully support all clipboard formats.

I’d be more than happy to contribute to this part of the code and submit a PR. Could you please let me know what I need to complete? May I start by creating a simple script in Python to verify its feasibility, and then we can discuss how to integrate it into the project using Swift.

**Comment by HsinghaoFu** [comment]
> It's a binary representation of whatever data is inside. I'm unaware of how to convert it back w/o Swift, here is the code that does that
> 
> https://github.com/p0deje/Maccy/blob/aec15e84489a0ea22899346be5a060f05d6f14ac/Maccy/Models/HistoryItem.swift#L113-L164
> 
> .
> I would be glad to merge PR that adds `pin` to Shortcuts so you could write a workflow that exports pins.

Hello, I have a plan for your [reference](https://github.com/p0deje/Maccy/issues/668#issuecomment-2395409694). I would like to complete this feature. Do you think my idea is feasible? Thank you very much for your reply.

**Comment by p0deje** [comment]
@HsinghaoFu Sorry for a slow reply! I am not sure how Python relates to this honestly. What I had in mind is extending an existing Shortcuts.app support that already allows to retrieve history from Maccy and add support for a pin field there https://github.com/p0deje/Maccy/blob/3c5cf30e1fe703e01b388b08a3fd744458a7b971/Maccy/Intents/HistoryItemAppEntity.swift

**Comment by HsinghaoFu** [comment]
> @HsinghaoFu Sorry for a slow reply! I am not sure how Python relates to this honestly. What I had in mind is extending an existing Shortcuts.app support that already allows to retrieve history from Maccy and add support for a pin field there https://github.com/p0deje/Maccy/blob/3c5cf30e1fe703e01b388b08a3fd744458a7b971/Maccy/Intents/HistoryItemAppEntity.swift

@p0deje Hi, thank you for your reply! I understand your perspective more clearly now. However, there's a consideration regarding content export: regardless of whether the content is pinned or not, for non-text content we need to save it in disk storage. This raises the question of user permissions - would you have any concerns about the permission requirements?

**Comment by p0deje** [comment]
> @p0deje Hi, thank you for your reply! I understand your perspective more clearly now. However, there's a consideration regarding content export: regardless of whether the content is pinned or not, for non-text content we need to save it in disk storage. This raises the question of user permissions - would you have any concerns about the permission requirements?

Since the export will happen inside Shortcuts.app, it will be asking for permissions explicitly.
