### ISSUE TITLE
Feature Request: Support string transformations when pasting. 

### ISSUE THREAD

**Issue by zakkhoyt** [p0deje/Maccy#669]
The idea I wanted to discuss is to support string transformations when invoking a `pin` (hotkey). That is when pasting, process the contents of the clipboard to some other form before pasting. 

# Prerequisites
Expanding the pinned hotkeys seem like a good place to implement this idea. Pins would contain 2 new fields in addition the 2 existing fields:
1) Key (already exists)
2) Title (already exists)
3) Regex (new field): A regex to process text on the clipboard or hightlighted. 
    a) A default value of `(.*)` or `(^.*$)` would pass the source text along unchanged
4) Template (new field): A template to apply the text that was extracted from the regex. 
    a) There are a lot of template styles to choose from. For this example I'll use `sed` capture group numbering. 
    b) A sensible default value would be `\1` which is the first regex capture group output

# Vocabulary
* `source text`: The text which the user has highlighted (or the clipboard contents). This is the input to regex. 
* `processed text`: The text which is output from the regex. In the case of capture groups, there can be multiple outputs
* `output text`: After applying `processed text` to the template, we have the final output string. 

# Data Flow
When a pin is invoked:
`source text` -> regex -> `processed text` -> template -> `output text` -> paste

# An Example
When posting on GitHub issue/PR/comment I often want to down-scale any images that I attach. GitHub will represent an image as markdown, but HTML is also supported which lets you scale the image. 

## Source Text
When an image is dragged into a GitHub editor it appears as Markdown. 
```markdown
![MyImage](https://github.com/user/project/assets/2229408/aaaa54f6-2a2e-4450-9ee6-bd56f91c5321)
```
## Regex
Markdown doesn't support image scaling, but html does. So I we need to convert markdown to html. 

Regex to extract a URL from a markdown image:
```
.*(https.*)\).*
```

## Processed Text
The processed text is the raw image URL (output from regex)
```
https://github.com/user/project/assets/2229408/aaaa54f6-2a2e-4450-9ee6-bd56f91c5321
```

## Template
Template to convert a URL to HTML image. 
```
<img src="/1" width="50%">
```

## Output Text
The final string will look like this
```html
<img src="https://github.com/user/project/assets/2229408/aaaa54f6-2a2e-4450-9ee6-bd56f91c5321" width="50%">
```

## Summary

```markdown
![MyImage](https://github.com/user/project/assets/2229408/aaaa54f6-2a2e-4450-9ee6-bd56f91c5321)
```

# Other Perspectives

What has been described above is similar to doing a regex find/replace in VSCode:
![Code_003731_zbm](https://github.com/p0deje/Maccy/assets/2229408/446d8d5f-a1f7-405b-a18a-d6261f770add)

Or processing a string with `sed`. Note: `sed` requires a lot of escapes. 

```sh
$ echo '![MyImage](https://github.com/user/project/assets/2229408/aaaa54f6-2a2e-4450-9ee6-bd56f91c5321)' | sed -E 's/.*(https.*)\).*/<img src\="\1" width\="50%"\>/g'
<img src="https://github.com/user/project/assets/2229408/aaaa54f6-2a2e-4450-9ee6-bd56f91c5321" width="50%">
```

**Comment by p0deje** [comment]
This is exactly what shortcuts are for - Maccy provides actions to get a selected item so you can transform it however you want before pasting. I guess it needs to be properly documented somewhere as it's not obvious at the moment. Фт example of such action would be 
<img width="1312" alt="Screenshot 2023-11-03 at 18 45 18" src="https://github.com/p0deje/Maccy/assets/665846/9d4a1fd5-293b-46f9-9153-073cccbbf92f">

**Comment by zakkhoyt** [comment]
@p0deje Fantastic! Didn't know maccy had intents. I'll check this out. Thank you much.
