### ISSUE TITLE
Autopaste doesn't work for searched results

### ISSUE THREAD

**Issue by xiaoweiz** [p0deje/Maccy#67]
For example, after the results are filtered by the search, press Alt + 2 doesn't paste the second item on the filtered list, but instead the second item on the original list.

**Comment by p0deje** [comment]
Indeed, thank you for the report. I'll look into this.

**Comment by xiaoweiz** [comment]
I'm using version 0.7.0

I appears a more precise description of the issue is as follows.
- Neither Alt + Number nor Cmd + Num works for the filtered list. 
- Autopast doesn't work for either the original list either or the filtered list.

**Comment by p0deje** [comment]
> Neither Alt + Number nor Cmd + Num works for the filtered list.

This drives me nuts as it _should_ work fine. The keybinding shortcuts are updated correctly and this happens somewhere on the macOS level. Just to be sure, which OS version do you use?

> Autopast doesn't work for either the original list either or the filtered list.

Please see if #60 solves the problem

**Comment by xiaoweiz** [comment]
It solves the issue that "Autopast doesn't work for either the original list either or the filtered list". But the original issue regarding the filtered list is still there.

**Comment by p0deje** [comment]
What version of macOS do you use?

**Comment by xiaoweiz** [comment]
10.14.6 Mojave

**Comment by p0deje** [comment]
It's a bit sluggish now, but fixed in 0.8.0
