### ISSUE TITLE
Question on the security

### ISSUE THREAD

**Issue by aina-kamarul-chan** [p0deje/Maccy#670]
Hello,

Can I know if there are secure coding is practiced when developing this application. I notice that you did not enable encrypted due to it affects performance and compliance issue.

Do you scanning tool such as Snyk, SonarSource to check on the code whether it has vulnerability?

Thank you in advance.

**Comment by p0deje** [comment]
I haven't run any tooling to check for security. You are welcome to do so and share the results.

**Comment by nadiah-Deriv** [comment]
Thank you for your response. So far, I did not see any issues with according to Snyk. Do you do code review before pushing the code into master branch when people submit pull request?

**Comment by aina-kamarul-chan** [comment]
Thank you for your response. So far, I did not see any issues with according to Snyk. Do you do code review before pushing the code into master branch when people submit pull request?

Due to nature of this application is offline, there are no logs collected unless we send it to you? Just asking have anyone reported security issues and how do you fix it?
