### ISSUE TITLE
Pin is not working on my Macbook Air. Pls help

### ISSUE THREAD

**Issue by dhruvkhurmi** [p0deje/Maccy#673]
<img width="549" alt="223348908-c09840b6-f2d0-47f9-8c0d-6aa55e72f795" src="https://github.com/p0deje/Maccy/assets/150987123/e2a6a0d6-4c68-441e-99e6-b37ed8cbe397">

**Comment by p0deje** [comment]
You need to pin items using ⌥P in Maccy main window first.
