### ISSUE TITLE
Proposal: Setting: "don't store strings that resemble passwords"

### ISSUE THREAD

**Issue by qpwo** [p0deje/Maccy#675]
Problem:

- can't block bitwarden chrome extension (because it's not it's own app)
- API keys are copied from browser or text editor typically, also hard to block

Solution: New setting: "don't save strings that look like passwords/secrets". (Default false)

If a string is at least 8 characters and contains uppercase+lowercase+number+?symbol with no spaces or newlines or unicode, then it's probably a  password or API key.

This would have false positives and false negatives, but I think would be quite accurate, maybe 98% accuracy or so.

**Comment by qpwo** [comment]
Oh my gosh maccy just updated and you already added this. Sweet!!

**Comment by nalmeida** [comment]
I'm using the following regexp that is working:

8 (or more) characters and contains uppercase+lowercase+number+?symbol with no spaces or newlines or unicode that are NOT URLs

```
^(?!https?:\/\/)(?=.*[A-Z])(?=.*[a-z])(?=.*\d)(?=.*[!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?])(?!.*\s).{8,}$
```
