### ISSUE TITLE
Проблема с safari

### ISSUE THREAD

**Issue by stlr00** [p0deje/Maccy#677]
Вообщем, сафари при попытке копировать изображение всегда копирует ссылку на него, в отличии от хрома.
И когда например пробуешь картинку вставить где-то ещё, например скопировал из гугла и вставил в вк, то отправляешь ссылку.

Это баг эпла, и они нивкакую не хотят годами его фиксить.
Вопрос: можно ли с помощью Maccy когда копируется ссылка из сафари попробовать в буфер обмена загружать изображение по этой ссылке? чтобы в дальнейшем оно корректно вставлялось.

Извиняюсь что не на английском, не очень хорошо пишу.

**Comment by p0deje** [comment]
@stlr00 не понимаю в чем проблема, у меня в сафари все отлично копируется если выбрать "Copy Image" в меню

**Comment by p0deje** [comment]
<img width="382" alt="Screenshot 2023-11-17 at 13 29 37" src="https://github.com/p0deje/Maccy/assets/665846/186d0935-4352-4f9f-b877-2f1927d3821e">
<img width="733" alt="Screenshot 2023-11-17 at 13 29 43" src="https://github.com/p0deje/Maccy/assets/665846/a2cfcb7f-c4e5-4976-a4b0-37074f1bb9df">

**Comment by stlr00** [comment]
@p0deje в сафари копируется именно ссылка, если в меню finder нажать "Правка -> Буфер обменна" то можно будет это увидеть (в то время как у хрома сама картинка). Многие приложения на macOS интерпретируют ссылки, как картинки сразу. Например так делает телеграмм, и видимо Maccy. Однако сайты к такому не приучены. Попробуй проверить именно ту ситуацию, про которую я говорил выше.

**Comment by p0deje** [comment]
@stlr00 В Safari копируется и ссылка, и изображение, и HTML код фрагмента, и alt текст - это можно увидеть в Pasteboard Viewer. То, какой приоритет отдает сайт/приложение когда ты пытаешься вставить такое копирование - это специфично для их реализации.

<img width="1407" alt="Screenshot 2023-11-20 at 14 59 06" src="https://github.com/p0deje/Maccy/assets/665846/dd50f8a4-e0f6-47fd-a644-d8175cf9149d">

Maccy старается не менять копирование, поэтому встроенного способа нет. Можно попробовать сделать что-то с помощью Shortcuts - брать последнее копирование, доставать из него только изображение и дальше сохранять в буфер обмена. В качестве отправной точки можно посмотреть на пример конвертами RTF в Markdown.

<img width="1310" alt="Screenshot 2023-11-20 at 14 59 55" src="https://github.com/p0deje/Maccy/assets/665846/31cf5583-5fe4-48ce-9c30-3d2df5bad4e4">

**Comment by p0deje** [comment]
Closing since there is nothing to do here, please re-open if you feel otherwise.
