### ISSUE TITLE
Maccy Menu is Not Opening at Cursor Location When Using the Shortcut to Open the Menu

### ISSUE THREAD

**Issue by rice-in-the-wind** [p0deje/Maccy#678]
It only opens at the cursor location when i am using it on my second monitor. When. i try to use the shortcut and I am on my primary monitor it just opens at the menubar of the second monitor. I've tried to reinstall and update but nothing has resolved the issue

**Comment by p0deje** [comment]
1. Can you please provide the Maccy version you use? You can get it in the "About" window.
2. Can you please record a screen video showing the problem? You can do this using QuickTime.app.
3. Can you please share the output of running `defaults read org.p0deje.Maccy` in Terminal.app?

**Comment by rice-in-the-wind** [comment]
https://github.com/p0deje/Maccy/assets/88417685/689f2b37-a398-4d4c-a059-04d89818ae85

here is the video

**Comment by p0deje** [comment]
@rice-in-the-wind Can you try running the following command in Terminal.app and let me know if it helps?

```
defaults remove org.p0deje.Maccy popupScreen
```

If not, can you also post the screenshot of System Settings / Displays / Arrange?
What macOS version do you run?

**Comment by p0deje** [comment]
> Domain (org.p0deje.Maccy) not found.
> Defaults have not been changed.


This means that Maccy is not installed 🤔 How did you install it in the first place?

**Comment by rice-in-the-wind** [comment]
Im not even sure what to make of that haha, I definitely have it installed. I initially downloaded it but after this issue started I uninstalled it and reinstalled it using homebrew. Is there maybe something wrong with the installation process that could be causing my error then?

**Comment by p0deje** [comment]
Can you please uninstall it completely (`brew uninstall --zap maccy`) and reinstall?

**Comment by rice-in-the-wind** [comment]
Hi, I did try that before but I did it again just in case using your command. The issue has not been fixed by that though

**Comment by p0deje** [comment]
I tried setting up your arrangement of displays but it still works fine for me. There were several issues in Maccy when used with macOS 14.0, could you upgrade to 14.1.2 and re-test?

**Comment by rice-in-the-wind** [comment]
Hi, I was on 14.1.2 but I just upgraded to 14.2 (the update that was released yesterday) and the issue was resolved. Sorry for all the trouble, but thank you for your patience!
