### ISSUE TITLE
Unpinning/deleting pins doesn’t work

### ISSUE THREAD

**Issue by MatzeKitt** [p0deje/Maccy#679]
I have some pinned items I want to delete. So I highlight them and then press `option + P` to unpin them, but nothing happened.

Also, `option + delete` doesn’t delete the entry so I can’t get rid of pinned items.

Using Maccy version 0.28.0 (23) on macOS 14.1.1 (23B81)

**Comment by p0deje** [comment]
1. Can you please record a screen video showing the problem? You can do this using QuickTime.app.
2. Can you please share the output of running `defaults read org.p0deje.Maccy` in Terminal.app?

**Comment by MatzeKitt** [comment]
Interesting: I was about to record it and so I just cleared my history and tried it again and it worked now. I will check again when there is some amount of history if the problem is in combination with this history.

**Comment by p0deje** [comment]
Please re-open if it happens again.

**Comment by MatzeKitt** [comment]
Indeed it happened again after I got some more content again.

https://github.com/p0deje/Maccy/assets/1018979/35c082a9-9ac7-4a10-ab5d-8743ed6681cb

You can’t see much on the video, but I’m pressing `option + P` like crazy.

The defaults:

```json
{
    "KeyboardShortcuts_popup" = "{\\"carbonKeyCode\\":4,\\"carbonModifiers\\":4352}";
    "LaunchAtLogin__hasMigrated" = 1;
    NSNavLastRootDirectory = "/Applications/Utilities";
    NSNavPanelExpandedSizeForOpenMode = "{800, 448}";
    "NSStatusItem Preferred Position Item-0" = 649;
    "NSWindow Frame NSNavPanelAutosaveName" = "500 507 800 448 0 0 1800 1125 ";
    "NSWindow Frame com.sindresorhus.Settings.FrameAutosaveName" = "624 529 513 436 0 0 1800 1125 ";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2023-12-02 09:18:30 +0000";
    SUUpdateGroupIdentifier = 1728585568;
    avoidTakingFocus = 1;
    enabledPasteboardTypes =     (
        "public.tiff",
        "public.utf8-plain-text",
        "public.png",
        "public.html",
        "public.rtf",
        "public.file-url"
    );
    hideFooter = 0;
    hideSearch = 0;
    hideTitle = 1;
    ignoredApps =     (
        "com.1password.1password",
        "com.1password.safari",
        "com.apple.keychainaccess"
    );
    ignoredPasteboardTypes =     (
        "Pasteboard generator type",
        "com.typeit4me.clipping",
        "de.petermaurer.TransientPasteboardType",
        "com.agilebits.onepassword",
        "net.antelle.keeweb"
    );
    imageMaxHeight = 64;
    maxMenuItems = 0;
    menuIcon = clipboard;
    migrations =     {
        "2020-04-25-allow-custom-ignored-types" = 1;
        "2020-06-19-use-keyboardshortcuts" = 1;
        "2020-09-01-ignore-keeweb" = 1;
        "2021-02-20-allow-to-customize-supported-types" = 1;
        "2021-06-28-add-title-to-history-item" = 1;
        "2021-10-16-remove-dynamic-pasteboard-types" = 1;
        "2022-08-01-rename-suppress-clear-alert" = 1;
        "2022-11-14-add-html-rtf-to-supported-types" = 1;
        "2023-01-22-add-regexp-search-mode" = 1;
    };
    pasteByDefault = 1;
    pinTo = bottom;
    popupPosition = center;
    popupScreen = 0;
    previewDelay = 300;
    removeFormattingByDefault = 0;
    showRecentCopyInMenuBar = 0;
}
```

Unfortunately, I can’t reopen the issue.

**Comment by p0deje** [comment]
@MatzeKitt When you have a huge history and try to pin/unpin, Maccy might freeze for a few seconds to rebuild the history (see #620) - please make sure that's not the case here. If you press pin/unpin multiple times in a second, it would not do anything for a while. 

I cannot reproduce it so far (taking into account what I wrote before).
