### ISSUE TITLE
Force set window size

### ISSUE THREAD

**Issue by LionelSelie** [p0deje/Maccy#68]
Hi,

I absolutely love Maccy and I hope we will be able to pin items soon, but I'd like to be able to set that window size because if you copy many items, it seems the window length increases. 

Is there a command we can set to force the window size is height? 

If not, could this be implemented, to be able to set a flag? Thanks

**Comment by p0deje** [comment]
Hi. I don't quite follow what do you mean by window size. Would you like to limit the height of the window so it doesn't show on the whole screen?

**Comment by LionelSelie** [comment]
Hi, thanks for looking into this! Allow me to visualize this:

This would be a more preferred window size: https://really.iamno.pro/RBuX6Wom

But if we add more items, it starts to look like this: https://really.iamno.pro/mXumR5d2

So, what I'd like to do is tell the window to not be vertically longer, than a set amount. Maybe this can be done by setting the number of items visible when opening Maccy, for instance, after 5 items, add the next item, but only visible after mousing over an arrow. Or this to be achieved by a certain amount of pixels? 

Not sure what would be the best way to handle this, but having a really long list to scroll through (Yes, I am aware we have a search option), is personally difficult for me.

Not sure if I expressed myself well here, but I hope the above, made sense?

Thanks, again!

**Comment by p0deje** [comment]
I get it thanks. I am not sure if it's doable via default macOS menu system, but I'll see how it can be done.

**Comment by LionelSelie** [comment]
<3

**Comment by p0deje** [comment]
By quick googling and checking the documentation of NSMenu, NSMenuDelegate it seems to be impossible to do in an obvious way. There is no way to access and modify the view of NSMenu. I believe it's possible to hack this around somehow, but I am not sure how to do that.

I'll keep this issue open for discussing and I'll appreciate any tips or PRs.

**Comment by LionelSelie** [comment]
Hmm.. thanks for looking into this. Could you give a look at [iPaste](https://en.toolinbox.net/iPaste/) which does this? I think after the 5th item copied, it creates a little arrow to see later items. Not sure if that'll help?

**Comment by p0deje** [comment]
Yes, I guess could do that creating a submenu. However, this means that one can't just scroll down the menu to see the items and has to navigate these submenus. 

I'd prefer to just see the same menu with the history list I currently see but with the limited height so that when there are too many items, there is a way to scroll using mouse or arrow up/down keys.

**Comment by alexjousse** [comment]
> Yes, I guess could do that creating a submenu. However, this means that one can't just scroll down the menu to see the items and has to navigate these submenus.
> 
> I'd prefer to just see the same menu with the history list I currently see but with the limited height so that when there are too many items, there is a way to scroll using mouse or arrow up/down keys.

Agreed with this, coming from ClipMenu, I hated the folder and expandable arrows instead of just having a menu where you can navigate with up/down keys!

**Comment by p0deje** [comment]
Closing since there is no obvious way to implement this without folders and I'm not going to add folders support (similar to #40)

**Comment by p0deje** [comment]
Actually, please follow #229 as it seems like I've found a way to implement something similar.
