### ISSUE TITLE
Maccy App not working in MacOS Sonoma 14.1.1

### ISSUE THREAD

**Issue by darrendelvino** [p0deje/Maccy#682]
Downloaded Maccy from the App Store and pasting does not work, through Menu bar or Hotkeys. Have tried reinstalling from the App Store.

**Comment by p0deje** [comment]
@darrendelvino Did you enable "Paste automatically" in preferences and followed the instructions?

**Comment by darrendelvino** [comment]
oh gotchu, it works now. 

thank you so much
