### ISSUE TITLE
Impaired Arrow Key Navigation in Maccy Version 0.29.0

### ISSUE THREAD

**Issue by LangLangBart** [p0deje/Maccy#686]
### version
```bash
brew info maccy
# ==> maccy: 0.29.0 (auto_updates)

sw_vers
# ProductName: Mac OS X
# ProductVersion: 10.15.7
# BuildVersion: 19H2026
```

### description
Starting with `0.29.0`, the ability to navigate using the arrow keys is impaired.
The issue didn't occur in `0.28.0`.

### to reproduce
- Install and open Maccy `0.29.0`.
- Copy a few strings.
- Press <kbd>⇧ Shift</kbd> + <kbd>⌘ Command</kbd> + <kbd>C</kbd> and then press  <kbd>⌥ Option</kbd> + <kbd>P</kbd> to pin any item.
- After pinning an item, attempt to use the arrow keys. You'll find it's not possible.
- Refer to the video below for a clearer understanding.

https://github.com/p0deje/Maccy/assets/92653266/abd8a248-18a1-4d92-81f2-310475da2977

### additional notes
Maccy was tested after uninstalling my existing version with:
```bash
brew uninstall --cask --zap maccy

```
... and then reinstalling it with
```bash
brew install --cask maccy
```

**Comment by p0deje** [comment]
> After pinning an item, attempt to use the arrow keys. You'll find it's not possible.

1. It works fine after closing and opening popup again, right?
2. Does it work if you delete an item?

**Comment by p0deje** [comment]
Possible suspects in 0.29:
- https://github.com/p0deje/Maccy/commit/94d58220a9c2e68b61692dc4d3adef8fbd45562d
- https://github.com/p0deje/Maccy/commit/cb552c185ebef0d65358f2fae84182008e2b04fd

**Comment by LangLangBart** [comment]
> > After pinning an item, attempt to use the arrow keys. You'll find it's not possible.
> 
> 1. It works fine after closing and opening popup again, right?
> 2. Does it work if you delete an item?

1. Unfortunately, the problem persists. The arrow keys are still non-functional. I would need to **quit** `Maccy` and restart it to regain arrow key functionality.
2. Deleting an item has the same impact as pinning one, resulting in non-functional arrow keys.

**Comment by p0deje** [comment]
Can you pelase re-test using 0.29.2?

**Comment by LangLangBart** [comment]
- `0.29.2` seems to fix the issue
	- only tetsed it for ~2min, will keep the ticket open another couple of hours and then close it

---

Thank you.
