### ISSUE TITLE
change hotkey did not overwrite default hotkey

### ISSUE THREAD

**Issue by april4** [p0deje/Maccy#69]
Like [issue 35](https://github.com/p0deje/Maccy/issues/35), I changed Popup Hotkey with this:  
```
defaults write org.p0deje.Maccy hotKey command+shift+z+x+c
```
Then, restart this app, "Command+Shift+Z+X+C" works, but the default key "Command+Shift+C" also still works!  
Thats not expected, cause "Command+Shift+C" are default key for Firefox/Chrome's Inspector tools.

**Comment by p0deje** [comment]
It's not possible to set a hotkey using multiple keys (Z+X+C). It will actually pick up only the last key (C) so this is why all the other key presses which include C open Maccy.

I am not even sure if creating a hotkey using multiple keys is possible. Why would you want such a complicate shortcut?

**Comment by april4** [comment]
I changed to other three keys, now press "Command+Shift+C" will not invoke Maccy.
This issue can close now.
