### ISSUE TITLE
After making some adjustments, I can't find the entrance to the preferences settings.

### ISSUE THREAD

**Issue by WchSup** [p0deje/Maccy#690]
### Before Submitting Your Bug Report

- [ ] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [ ] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

**Comment by WchSup** [comment]
<img width="409" alt="image" src="https://github.com/p0deje/Maccy/assets/44390273/54395043-aaf6-4e92-bbab-2b73101c52c0">

**Comment by WchSup** [comment]
Like this, even using Command +, I still can't find the preferences settings.

**Comment by p0deje** [comment]
For a workaround, you can run the following in Terminal.app

```
 defaults write org.p0deje.Maccy hideFooter false
```

This should show a footer so you can open Preferences. 

I can however open preferences using CMD+, even when the footer is hidden.

**Comment by WchSup** [comment]
Thanks，After reinstalling the latest version of the application, the issue was resolved. However, it was indeed strange that, before, even using Command +, couldn't open the preferences settings.

**Comment by marcelarie** [comment]
This happens to me too. 
I think when you hide the footer, the preference hot key is not available anymore.

**Comment by marcelarie** [comment]
A config file in `.config` would be really nice btw :)

**Comment by p0deje** [comment]
> I think when you hide the footer, the preference hot key is not available anymore.

That's not the case, you should be able to open preferences with <kbd>⌘,</kbd>.

> A config file in .config would be really nice btw :)

Preferences are stored in application sandbox, so it's not possible.

**Comment by okkdev** [comment]
<kbd>⌘</kbd> + <kbd>,</kbd> stopped working for me as well. Using the `default write` workaround and turning the option off again reenabled the hotkey. It hasn't been working for quite some time for me I just never bothered to check how to resolve it. I assume some update didn't initialize the hotkey with the footer missing.

**Comment by p0deje** [comment]
@okkdev You could run into this problem after upgrading to Sonoma while using an old Maccy version. Please re-test using the latest Maccy verison.

**Comment by okkdev** [comment]
Ohh, then that was it. It's working fine now, thanks. :)
