### ISSUE TITLE
Implement Hotkey for Pasting as Plain Text Without Opening Clipboard Menu

### ISSUE THREAD

**Issue by bigplayer-ai** [p0deje/Maccy#693]
### Before Submitting Your Feature Request

- [X] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

The current process of pasting as plain text in Maccy requires opening the clipboard menu, which can be time-consuming and disrupt workflow.

### Solution

Introduce a hotkey (suggested: Ctrl + Shift + V / ⌘ + ⇧ + V) that pastes as plain text directly, bypassing the need to open the clipboard menu. This would enhance Maccy's usability and efficiency, particularly for users frequently needing to paste non-formatted text.

**Comment by p0deje** [comment]
You can add your own Shortcut assigned to a specific key that would do the same thing for you. Here is an example:

<img width="1047" alt="Screenshot 2023-12-12 at 16 07 45" src="https://github.com/p0deje/Maccy/assets/665846/f05c862b-46e1-4ff3-a656-3cf19727ef64">

You can install it from https://www.icloud.com/shortcuts/72e2ec90a9d94086af6cdeacb94dc74f, then use with Control+Command+V.

**Comment by LangLangBart** [comment]
macOS does have a native shortcut for pasting as plain text.

<kbd>⇧ Shift</kbd> + <kbd>⌘ Command</kbd> + <kbd>⌥ Option</kbd> + <kbd>V</kbd>

Ref: [Hacker News thread](https://news.ycombinator.com/item?id=38144173)
