### ISSUE TITLE
After unpinning, the pinned item should show again on the top of the list.

### ISSUE THREAD

**Issue by Gitbreast** [p0deje/Maccy#694]
### Before Submitting Your Feature Request

- [X] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

For now, if accidentally unpin an old item without left-clicking on it, without copying again, it would just disappear. Sometime my cursor just accidentally moves a little bit before I press `opt+p`, an old treasure item just accidentally killed by me and disappears directly, without saying goodbye :(

### Solution

For a pinned item, after pressing `opt+p` to unpin it, it should show up on the top of the no-pinned list again. Or at least for an "old" item.

**Comment by p0deje** [comment]
Once unpinned, an item is placed in the same position it would be normally (sorted by last copied at a time). I don't think putting it at the top is the correct behavior in this case. You can always find it by searching and pin again.

**Comment by Gitbreast** [comment]
> Once unpinned, an item is placed in the same position it would be normally (sorted by last copied at a time). I don't think putting it at the top is the correct behavior in this case. You can always find it by searching and pin again.

For example, if copy a large numbers of things in a short time — large enough to make the natural position of the pinned item(e.g. item A) out of the setting range — in this situation, if want to unpin item B but accidentally unpin item A due to a little cursor moving or something else, item A would permanently disappear.
Putting it at the top is not necessary, just wonder a way to retrieve the out-of-range accidentally-unpinned item back, or consider a recycle bin for unpinned item as a buffer?

**Comment by p0deje** [comment]
Now when you unpin it would be put to its unpinned place (based on the sorting algorithm) but it would remain highlighted. So you don't actually need to search it again, you can just press ⌥P again and pin it back. Is this enough to cover your case?

**Comment by p0deje** [comment]
I would consider this working as needed now. Please re-open if you feel otherwise.
