### ISSUE TITLE
Copy multiple files shows as a single file

### ISSUE THREAD

**Issue by p0deje** [p0deje/Maccy#695]
### Before Submitting Your Bug Report

- [X] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Steps to Reproduce

Just copy multiple files at once in Finder - it currently shows as a single file in history.

**Comment by weisJ** [comment]
Is this about creating a separate entry per file or just showing all the files in the same entry? The latter seems more natural to me.

**Comment by p0deje** [comment]
It should be showing everything as a single entry. I believe the title could be filenames joined by a newline separator, while the preview should show all file:/// items one by one.
