### ISSUE TITLE
Remove tracking parameters from copied URLs

### ISSUE THREAD

**Issue by dkindler** [p0deje/Maccy#696]
### Before Submitting Your Feature Request

- [X] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

Inspired by [this tweet](https://twitter.com/jeff_weinstein/status/1740119255323222466).  

Many links contain UTM / other tracking parameters that may be unwanted.

### Solution

A simple toggle that removes tracking parameters from a URL when you copy it to your Maccy clipboard.

**Comment by p0deje** [comment]
There is a wonderful and free app https://apps.apple.com/us/app/pure-paste/id1611378436?mt=12 which already does it.
