### ISSUE TITLE
Disable sound effects

### ISSUE THREAD

**Issue by tgdn** [p0deje/Maccy#697]
### Before Submitting Your Feature Request

- [X] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

Hi, thanks for your awesome work, this is a really great tool!

Since the latest update (0.29.3 (27)), every time I copy something there is a little sound effect. Is there any way to easily disable this sound effect?

Thanks!

**Comment by tgdn** [comment]
Closing in favor of https://github.com/p0deje/Maccy/issues/692

**Comment by p0deje** [comment]
You can disable sounds in System Settings / Notifications / Maccy.
