### ISSUE TITLE
Should Maccy's free availability be listed on the top of the App Store description?

### ISSUE THREAD

**Issue by YousufSSyed** [p0deje/Maccy#698]
### Before Submitting Your Feature Request

- [X] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

I first found Maccy on the App Store after seeing a Reddit comment that its free, I thought maybe it was another dev that published it but it says "Maccy is an open source application using the MIT license. Its full source code is available at GitHub. You can inspect or change it however you want. This version is being sold on the App Store to support the development."

### Solution

The message about it being open source should be moved to the top so that users don't pay thinking that the app is not offered for free. Lots of users don't read or thoroughly read the descriptions.

**Comment by p0deje** [comment]
The goal of the App Store is to support development, so I don't think there is anything to do here. I am not trying to trick people into buying on the App Store. There is always an option to request a refund on the App Store if one changes their mind.
