### ISSUE TITLE
add feature of editting item

### ISSUE THREAD

**Issue by McJayFeng** [p0deje/Maccy#699]
### Before Submitting Your Feature Request

- [X] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

The feature of clipboard app I use the most on Windows is editting the item, so, do you ever consider add this feature into Maccy?

**Comment by p0deje** [comment]
I haven't - if you need to edit the content of the copy, you better edit it in some other app (e.g. an editor) and then copy it to the clipboard. Making Maccy an editor is an overkill from my point of view.
