### ISSUE TITLE
1Password copying not saving

### ISSUE THREAD

**Issue by arthur-lbchn** [p0deje/Maccy#700]
### Before Submitting Your Bug Report

- [X] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

0.29.3

### macOS Version

14.2.1

### Maccy Settings

```Shell
{
    "KeyboardShortcuts_delete" = "{\\"carbonKeyCode\\":51,\\"carbonModifiers\\":2048}";
    "KeyboardShortcuts_pin" = "{\\"carbonKeyCode\\":35,\\"carbonModifiers\\":2048}";
    "KeyboardShortcuts_popup" = "{\\"carbonKeyCode\\":12,\\"carbonModifiers\\":4096}";
    "LaunchAtLogin__hasMigrated" = 1;
    NSNavLastRootDirectory = "/Applications";
    NSNavPanelExpandedSizeForOpenMode = "{800, 448}";
    "NSWindow Frame NSNavPanelAutosaveName" = "356 372 800 448 0 0 1512 944 ";
    "NSWindow Frame com.sindresorhus.Settings.FrameAutosaveName" = "506 621 532 197 0 0 1512 944 ";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2024-01-07 11:19:22 +0000";
    SUUpdateGroupIdentifier = 3965865525;
    enabledPasteboardTypes =     (
        "public.html",
        "public.png",
        "public.utf8-plain-text",
        "public.rtf",
        "public.tiff",
        "public.file-url"
    );
    hideTitle = 1;
    historySize = 999;
    ignoreAllAppsExceptListed = 0;
    ignoredApps =     (
    );
    ignoredPasteboardTypes =     (
    );
    maxMenuItemLength = 50;
    maxMenuItems = 0;
    menuIcon = clipboard;
    migrations =     {
        "2020-04-25-allow-custom-ignored-types" = 1;
        "2020-06-19-use-keyboardshortcuts" = 1;
        "2020-09-01-ignore-keeweb" = 1;
        "2021-02-20-allow-to-customize-supported-types" = 1;
        "2021-06-28-add-title-to-history-item" = 1;
        "2021-10-16-remove-dynamic-pasteboard-types" = 1;
        "2022-08-01-rename-suppress-clear-alert" = 1;
        "2022-11-14-add-html-rtf-to-supported-types" = 1;
        "2023-01-22-add-regexp-search-mode" = 1;
    };
    removeFormattingByDefault = 0;
    searchMode = exact;
    showRecentCopyInMenuBar = 0;
    sortBy = lastCopiedAt;
}
```

### Description

When copying from 1Password, it's not storing in Maccy (email, name, password and etc.)

### Steps to Reproduce

1. Go to 1Password
2. Open any item.
3. Try to copy username, password, card number and etc.
4. Nothing will appear in Maccy.

**Comment by p0deje** [comment]
That's expected, copies from 1Password are sensitive content and should not be stored in Maccy.

**Comment by arthur-lbchn** [comment]
Thank you for your update. How to make it enabled? I don't want ignore 1Password copies.

**Comment by p0deje** [comment]
@arthur-lbchn The only way to do that would be to fork Maccy and change its code to allow storing copies with a concealed type, but I wouldn't merge a PR for that for security reasons.

**Comment by arthur-lbchn** [comment]
@p0deje thanks, but it's not about concealed fields, all fields in 1Password Desktop are ignored. I believe it's something else. 

I'm also using a browser extension - everything is saved in Maccy, even concealed (not revealed) fields. once you have a chance, could you please take a look again? if you already know it's not a bug, kindly allow this option to be ignored (with all security warnings about)

**Comment by p0deje** [comment]
> thanks, but it's not about concealed fields, all fields in 1Password Desktop are ignored. I believe it's something else.

That's how 1Password Desktop implements that - anything you copy from it is marked as concealed. You can install Pasteboard Viewer app and inspect copies yourself - you will see ConcealedType everywhere:

<img width="549" alt="Screenshot 2024-01-13 at 08 58 17" src="https://github.com/p0deje/Maccy/assets/665846/7a5aa178-560d-4e47-9e66-e04d9c32e85d">

> I'm also using a browser extension - everything is saved in Maccy, even concealed (not revealed) fields. once you have a chance, could you please take a look again? if you already know it's not a bug, kindly allow this option to be ignored (with all security warnings about)

Yes, because browser extension is not a desktop app and everything you copy from it looks like a regular copied text from the browser for macOS. There are no concealed types there.
