### ISSUE TITLE
Change hotheys manually

### ISSUE THREAD

**Issue by otabekgh** [p0deje/Maccy#704]
### Before Submitting Your Feature Request

- [X] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

Currently opening maccy hotkey conflict with chrome dev tools opening hotkey

**Comment by p0deje** [comment]
You can change it in the Maccy preferences.

**Comment by otabekgh** [comment]
@p0deje I really appreciate, for some reason it didn't work. I have reinstalled and works well
