### ISSUE TITLE
debounce fuzzy search

### ISSUE THREAD

**Issue by thewisenerd** [p0deje/Maccy#71]
not sure if its the searching bits, or the ui re-render, but fuzzy search with multiple items is very "blocking",

not sure what is the right solve for this either, just putting this out there.

**Comment by p0deje** [comment]
Can you give more details? How many items you have in the list? I've found that it gets slower after 200 items. Can you also record a video of how it works?

**Comment by thewisenerd** [comment]
Ah! I see that it is detailed in the readme that FuzzySearch could get slow with 200+ items; my default number of items was far higher (999 `._.`);

time taken by fuzzy search also seems to be a function of the length of the fuzzysearch string for > x number of items.

anyway, reduced that to 100 && closing this as a non-issue.
