### ISSUE TITLE
Show trailing/leading whitespace in clipboard preview

### ISSUE THREAD

**Issue by ilyagr** [p0deje/Maccy#717]
### Before Submitting Your Feature Request

- [X] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

I got two items in Maccy that look the same but are considered different. Upon investigation, one of them had a leading space. (I.e. ` https://` instead of `https://`). In Maccy's UI, the space was not shown at all (though it was there when pasted).

Apart from the confusion I described above, it'd be nice to be informed about the space before pasting.

### Solution

Replace trailing and leading whitespace with some symbol, e.g. `·` or `⎵` when showing items in the Maccy UI.

This is similar to how newlines are already replaced with a unicode symbol in the UI.

### More details

The closest related issue I found is https://github.com/p0deje/Maccy/issues/481.

Thanks for making Maccy! It's really neat. 😄 

Just to jot this down somewhere: the relevant code is https://github.com/p0deje/Maccy/blob/84422077275fc2f5e6f17b85c686e426af731e49/Maccy/History/HistoryItem.swift#L193-L196
I'm not very familiar with XCode, though.

**Comment by p0deje** [comment]
What about a text which starts with 50 spaces? Shall we show `⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵....` or somehow truncate? What if we only show them in the preview popup?

**Comment by ilyagr** [comment]
I was wondering about this as well. First of all, I think this is rare. But yeah, I'd allow trimming `⎵…⎵beginn…end⎵…⎵` for long text that has spaces before and after.

I'm not sure whether text starting with `⏎⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⏎⏎` should also be special-cased, but I guess it's OK to consider this as a string without leading whitespace and show it like `⏎.                              ⏎⏎` (the length might be a bit off).

**Comment by p0deje** [comment]
> I was wondering about this as well. First of all, I think this is rare. But yeah, I'd allow trimming long text that has more than 2 spaces before and after to ⎵…⎵beginn…end⎵…⎵, if necessary for the text to fit.

Ok, noted. I am not sure I would agree with the reasoning.

> I'm not sure whether text starting with ⏎⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⎵⏎⏎ should also be special-cased, but I guess it's OK to consider this as a string without leading whitespace and show it like ⏎                              ⏎⏎ (the length might be a bit off).

Right now, Maccy doesn't show leading newlines too, only in the preview. That's why I suggest showing leading spaces in preview too, but don't change anything in the main menu view.

**Comment by ilyagr** [comment]
I think the preview should definitely show leading spaces, though I don't necessarily like the idea of replacing leading spaces with another symbol there. That would change the assumption that what you see in the preview is what the clip will look like pasted. For this reason, I'm not sure whether there's a good way for the preview to show trailing spaces.

Additionally, I'd strongly prefer seeing leading spaces in the menu. I don't usually open the preview before pasting, and I'd like to know if my paste includes leading spaces. I'd also like to see leading spaces in the preview next to the Maccy icon. (When pasting, leading spaces are more important to know about than trailing spaces, since the trailing spaces are easier to delete afterwards).

I find the current behavior confusing. I was nerd-sniped when I saw two identical-looking entries in the clipboard, while I knew that Maccy is supposed to collapse identical clips into one entry. For this reason, I care somewhat about the trailing spaces as well.

If not everybody likes this, it could be an option. TBH, I don't see a reason somebody would dislike this at the moment, but you have a lot of experience with clipboard managers that I don't.

**Comment by ilyagr** [comment]
Another thing I just checked: if I copy a sequence of spaces (`      `), Maccy seems to just ignore it. I can imagine it being useful to keep such clips, if you are aligning a table or some ASCII art, for example.

**Comment by p0deje** [comment]
> Another thing I just checked: if I copy a sequence of spaces (      ), Maccy seems to just ignore it. I can imagine it being useful to keep such clips, if you are aligning a table or some ASCII art, for example. I think ⎵⎵⎵⎵ is a good representation of it.

That was a deliberate decision, that pretty much nobody would like to preserve spaces/newline because it would practically impossible to distinguish between them. I think this is still true even if we show spaces as a `⎵`, it might be hard to see a difference if you have several copies:

- ⎵⎵⎵⎵⎵
- ⎵⎵⎵⎵
- ⎵⎵⎵⎵⎵⎵


So far I lean towards having a setting in Appearance called "Show special symbols" (enabled by default) that would turn on visibility of the following symbols in the menu:

- Space with ⎵ (only leading and trailing)
- Tab with ⇥ (all)
- Newline with ⏎ (all)

**Comment by ilyagr** [comment]
That sounds great to me.

I don't have a strong opinion about what to do with spaces-only clips; it doesn't feel very important, so I think the current behavior is fine even though it's slightly unexpected. Even if I was doing ASCII art, I don't know whether I'd appreciate Maccy history being littered with many clips that are all a different number of spaces.

**Comment by p0deje** [comment]
Do you prefer which symbol to show for leading/trailing spaces? I like dot more because it's compact and is the same width as space in a system font.

<img width="469" alt="1" src="https://github.com/p0deje/Maccy/assets/665846/f5834fbe-e510-4c43-8559-af34e57cfb99">

**Comment by ilyagr** [comment]
Dots sound good to me, they definitely look better in your screenshot. Thank you!

**Comment by ilyagr** [comment]
Cool, thank you very much!

I'm not in a rush, so I'll probably wait until the next release to try it.
