### ISSUE TITLE
Incorrect Japanese Translation for "About" in Menu

### ISSUE THREAD

**Issue by Stocker-jp** [p0deje/Maccy#719]
### Before Submitting Your Bug Report

- [X] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

0.29.4

### macOS Version

13.6.3

### Maccy Settings

```Shell
{
    "KeyboardShortcuts_delete" = "{\\"carbonModifiers\\":2048,\\"carbonKeyCode\\":51}";
    "KeyboardShortcuts_pin" = "{\\"carbonModifiers\\":2048,\\"carbonKeyCode\\":35}";
    "KeyboardShortcuts_popup" = "{\\"carbonModifiers\\":768,\\"carbonKeyCode\\":8}";
    "LaunchAtLogin__hasMigrated" = 1;
    "NSStatusItem Visible Item-0" = 1;
    "NSWindow Frame com.sindresorhus.Settings.FrameAutosaveName" = "595 495 537 436 0 0 1728 1079 ";
    SUAutomaticallyUpdate = 1;
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2024-01-28 05:12:57 +0000";
    SUSendProfileInfo = 0;
    enabledPasteboardTypes =     (
        "public.utf8-plain-text",
        "public.file-url",
        "public.tiff",
        "public.html",
        "public.rtf",
        "public.png"
    );
    ignoredPasteboardTypes =     (
        "com.typeit4me.clipping",
        "de.petermaurer.TransientPasteboardType",
        "Pasteboard generator type",
        "com.agilebits.onepassword",
        "net.antelle.keeweb"
    );
    menuIcon = maccy;
    migrations =     {
        "2020-04-25-allow-custom-ignored-types" = 1;
        "2020-06-19-use-keyboardshortcuts" = 1;
        "2020-09-01-ignore-keeweb" = 1;
        "2021-02-20-allow-to-customize-supported-types" = 1;
        "2021-06-28-add-title-to-history-item" = 1;
        "2021-10-16-remove-dynamic-pasteboard-types" = 1;
        "2022-08-01-rename-suppress-clear-alert" = 1;
        "2022-11-14-add-html-rtf-to-supported-types" = 1;
        "2023-01-22-add-regexp-search-mode" = 1;
    };
    pasteByDefault = 1;
    popupPosition = cursor;
    removeFormattingByDefault = 1;
    searchMode = fuzzy;
    showInStatusBar = 1;
    showRecentCopyInMenuBar = 0;
}
```

### Description

I've noticed an issue with the Japanese UI translation in Maccy, the clipboard history manager app for Mac. When accessing Maccy's menu from the Mac menu bar, the "About" option is incorrectly translated to "ついて" in Japanese, which seems out of context. It would be more appropriate to use "About" (in English) or "Maccyについて" to correctly convey the intended meaning.

### Steps to Reproduce

1. Set your Mac system language to Japanese.
2. Click on the Maccy icon in the Mac menu bar.
3. Observe the translation for "About" in the dropdown menu, which appears as "ついて".
<img width="346" alt="SS 2024-01-28 19 04 04" src="https://github.com/p0deje/Maccy/assets/24154791/d8734b7d-3d20-473b-a475-2cf600a3fff2">

**Comment by p0deje** [comment]
@Stocker-jp Thanks, I don't Japanese so that's probably coming from Google Translate. Can you recommend a proper Japanese translation?

**Comment by Stocker-jp** [comment]
Thank you for your response.
For the Japanese translation of "About", I recommend using "Maccyについて". This phrase is more contextually appropriate and conveys the intended meaning accurately in Japanese. It directly translates to "About Maccy", which fits well with the purpose of the menu option, providing information about the app itself. I hope this helps improve the app's usability for Japanese-speaking users. Thank you for considering this change.

**Comment by p0deje** [comment]
Is it possible to use only “About” without “Maccy”?On Jan 28, 2024, at 16:22, Stocker-jp ***@***.***> wrote:﻿
Thank you for your response.
For the Japanese translation of "About", I recommend using "Maccyについて". This phrase is more contextually appropriate and conveys the intended meaning accurately in Japanese. It directly translates to "About Maccy", which fits well with the purpose of the menu option, providing information about the app itself. I hope this helps improve the app's usability for Japanese-speaking users. Thank you for considering this change.

**Comment by Stocker-jp** [comment]
Certainly, using just "About" is also acceptable. To clarify with examples:

Acceptable examples: "About", "Maccyについて".
Unacceptable examples: "ついて", "について".

For instance, in macOS with Japanese settings, Finder is labeled as "Finderについて", and Safari as "Safariについて". Following the macOS convention, "Maccyについて" would be the best choice. However, if the goal is to reduce the number of characters, using just "About" in English is perfectly fine and the meaning will still be clear. "About" alone is sufficient to convey the intended message.
<img width="252" alt="SS 2024-01-29 10 06 22" src="https://github.com/p0deje/Maccy/assets/24154791/0d51b7f7-680a-4c70-9826-ca1af56a5340">

**Comment by p0deje** [comment]
Thank you, this is now fixed. Please, let me know if you notice any other incorrect Japanese translations.
