### ISSUE TITLE
Maccy stops saving clips after limit is reached

### ISSUE THREAD

**Issue by akapitoha** [p0deje/Maccy#72]
Hello,
0.8.1 version
limit is set to 50

After limit is reached, new items I copy are not saved in Maccy.
Then I restart the app, copy smth - and it works, new item is added replacing 50th item at the bottom of the list.

Should this work same way without restarting the app?

**Comment by FernandoMiguel** [comment]
ohhhh so that's what is happening to mine???
it's really annoying

**Comment by p0deje** [comment]
please download 0.8.3, I think I've fixed this bug
