### ISSUE TITLE
List wrapping and graphical glitches

### ISSUE THREAD

**Issue by mblarsen** [p0deje/Maccy#722]
### Before Submitting Your Bug Report

- [X] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

0.29.4 (28)

### macOS Version

14.0 (23A344)

### Maccy Settings

```Shell
{
    "KeyboardShortcuts_delete" = "{\\"carbonKeyCode\\":51,\\"carbonModifiers\\":2048}";
    "KeyboardShortcuts_pin" = "{\\"carbonKeyCode\\":35,\\"carbonModifiers\\":2048}";
    "KeyboardShortcuts_popup" = "{\\"carbonModifiers\\":768,\\"carbonKeyCode\\":8}";
    "LaunchAtLogin__hasMigrated" = 1;
    NSNavPanelExpandedSizeForOpenMode = "{800, 448}";
    "NSStatusItem Preferred Position Item-0" = 200;
    "NSWindow Frame NSNavPanelAutosaveName" = "455 465 800 448 0 0 1710 1069 ";
    "NSWindow Frame com.sindresorhus.Settings.FrameAutosaveName" = "760 531 436 403 0 0 1710 1069 ";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2024-01-29 15:39:41 +0000";
    SUUpdateGroupIdentifier = 290336039;
    enabledPasteboardTypes =     (
        "public.tiff",
        "public.png",
        "public.utf8-plain-text",
        "public.html",
        "public.rtf",
        "public.file-url"
    );
    hideFooter = 1;
    hideSearch = 0;
    hideTitle = 1;
    historySize = 512;
    ignoredApps =     (
        "com.1password.1password",
        "com.1password.safari",
        "com.bitwarden.desktop"
    );
    ignoredPasteboardTypes =     (
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "com.agilebits.onepassword",
        "net.antelle.keeweb",
        "Pasteboard generator type"
    );
    maxMenuItems = 5;
    menuIcon = maccy;
    migrations =     {
        "2020-04-25-allow-custom-ignored-types" = 1;
        "2020-06-19-use-keyboardshortcuts" = 1;
        "2020-09-01-ignore-keeweb" = 1;
        "2021-02-20-allow-to-customize-supported-types" = 1;
        "2021-06-28-add-title-to-history-item" = 1;
        "2021-10-16-remove-dynamic-pasteboard-types" = 1;
        "2022-08-01-rename-suppress-clear-alert" = 1;
        "2022-11-14-add-html-rtf-to-supported-types" = 1;
        "2023-01-22-add-regexp-search-mode" = 1;
    };
    pinTo = top;
    popupPosition = statusItem;
    popupScreen = 0;
    previewDelay = 500;
    searchMode = exact;
    showRecentCopyInMenuBar = 0;
}
```

### Description

Possibly two issues, but comes out as one issue. 

1. The up and and down arrows are added when wrapping (it seems) despite there is enough room in the window. E.g. one item
2. When the end op the list is reach a bunch of graphical glitches appear:
    a. sometimes the longer list is shown below, eg. the matching items from a shorter search
    b. when there is only one or two items in the list items outside of the list seem to appear when wrapping.

![Kapture 2024-01-30 at 00 33 30](https://github.com/p0deje/Maccy/assets/247048/89d09d53-9055-4d6f-a741-8eaa544bb740)

### Steps to Reproduce

1. Have at least one item in clipboard history
2. Navigate up or down till the end (top or bottom) of the mach list

ps: Using both arrow keys or ctrl-n and ctrl-p gives the same result.

**Comment by p0deje** [comment]
Yes, it is a known issue on macOS 14.0, you need to upgrade to macOS 14.3.

**Comment by mblarsen** [comment]
Excellent, @p0deje , running on 14.4 now and Maccy works as expected :)
