### ISSUE TITLE
Simulate typing of the text instead of trying to paste it

### ISSUE THREAD

**Issue by notsatyarth** [p0deje/Maccy#723]
### Before Submitting Your Feature Request

- [X] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

There are certain websites that prevent pasting contents from clipboard. As such Maccy cannot paste content there.

### Solution

Could Maccy also support simulating typing the clipboard contents  so that I can paste in fields that do not support paste too

**Comment by p0deje** [comment]
Not at the moment, but I believe I could create a Shortcuts.app workflow to simulate this. Can you give me a publicly accessible example to test this?

**Comment by notsatyarth** [comment]
Thanks! I tried creating a Shortcuts app workflow for this too. I was planning to also try doing this using Hammerspoon but have not reached there yet. 
However I could not get this working using the Shortcuts workflow. 
This happens on a banking website for me. Looks like they've painstaking ensured that I cannot do anything apart from typing the input into their form. 
Do try if you can paste/auto-type anything into the "Customer Id" field at https://www.hdfcbank.com/personal/ways-to-bank/online-banking/net-banking

**Comment by p0deje** [comment]
It was actually quite easy to implement - here you go https://www.icloud.com/shortcuts/08da26c3ac0e499994c46cac0a756a06. I tested using "SafarI" -> "Services" and then ran the workflow from there, but you can also assign it to a shortcut and use "Selected" in the second action. This would allow you to call it directly from Maccy.
