### ISSUE TITLE
Hide control items

### ISSUE THREAD

**Issue by p0deje** [p0deje/Maccy#73]
From reddit (https://www.reddit.com/r/macapps/comments/ctzv30/maccy_lightweight_opensource_clipboard_manager/fbaw5ac/)

> Just found this when looking for an alternative to Flycut. This is great! The fact that it drops directly into a search is awesome! Drives me crazy having to go through my history one by one on Flycut. I essentially wanted a bash ctrl+r equivalent for my clipboard manager and this works great.
One quick question, is it possible to remove the additional entries from pop-up that aren't related to the clipboard history i.e. Launch at Login, About, Quit? Specifically this section: https://imgur.com/a/Bx7DLMH. Mainly because very rarely if ever do you need to see those lines when using the shortcut and it just clutters up the screen.
Love the app though, definitely going to be using it going forward.

**Comment by Gsazraetr** [comment]
Thanks, being able to hide the footer is a very welcome implementation. However, I feel this should not include the Clear button. 
Or else, maybe there could be a keyboard shortcut for Clear. (I would probably prefer this, in fact.)

Anyway, keep up the great work! This latest update has a lot of useful new options.
