### ISSUE TITLE
Pin search and settings box 

### ISSUE THREAD

**Issue by fleytman** [p0deje/Maccy#730]
### Before Submitting Your Feature Request

- [X] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

At the moment to get to the settings you have to scroll the menu for a long time to get to the settings
Also, if there are a lot of entries in the search pattern and you start scrolling, you can't see the search bar.

<details><summary>screenshot</summary>
<p>

<img width="544" alt="image" src="https://github.com/p0deje/Maccy/assets/1923645/e7a04c73-3bbb-4318-83be-af0438d2e0d1">

</p>
</details> 

### Solution

I suggest fixing the line with search box and settings box so that they don't scroll along with the search history.

**Comment by p0deje** [comment]
You can limit number of visible items in Appearance preferences, that's the only solution at the moment. It's not possible to "pin" individual menu item (search box) while hiding other - there is no such API in macOS.

**Comment by fleytman** [comment]
> You can limit number of visible items in Appearance preferences, that's the only solution at the moment. 

It seems to me that this is not a solution and not a particularly useful workaround: in just one day, I can copy more than 100 objects, even the current limit of 999 is very small (and I'm not the only one who thinks so https://github.com/p0deje/Maccy/issues/310). Many users, like myself, use clipboard managers to save information instead of notes, and if there is to be a limit, it should be on display, but with the ability to filter (as is done in copyq when `copyq config tray_menu_open_on_left_click true` is enabled).



> It's not possible to "pin" individual menu item (search box) while hiding other - there is no such API in macOS.

Hmm, I know of several applications that have pinned items and scroll views:
open source: [OnlySwitch](https://github.com/jacklandrin/OnlySwitch), [Itsycal](https://github.com/sfsam/Itsycal)
commercial: [JetBrains Toolbox](https://www.jetbrains.com/toolbox-app/), [Paragon NTFS](https://www.paragon-software.com/ru/home/ntfs-mac/)

**Comment by p0deje** [comment]
> It seems to me that this is not a solution and not a particularly useful workaround: in just one day, I can copy more than 100 objects, even the current limit of 999 is very small (and I'm not the only one who thinks so https://github.com/p0deje/Maccy/issues/310). Many users, like myself, use clipboard managers to save information instead of notes, and if there is to be a limit, it should be on display, but with the ability to filter (as is done in copyq when copyq config tray_menu_open_on_left_click true is enabled).

I would love to support something like that but AppKit limitations doesn't let me do so easily. There were some attempts and discussions in #229, but so far there is not a decent reliable solution. Maybe in the future macOS would implement new features to support, but for now I don't see anything. 

I use Maccy to store some info myself, but I rarely scroll through the list because I would just search for what I need instead. Limiting number of visible items + searching works just fine for me.

> Hmm, I know of several applications that have pinned items and scroll views:
> open source: [OnlySwitch](https://github.com/jacklandrin/OnlySwitch), [Itsycal](https://github.com/sfsam/Itsycal)

Both applications use NSPopover controls to implement their UI, while Maccy uses NSMenu. Unfortunately, the latter doesn't support similar functionality, at least without re-implementing its core UI.
