### ISSUE TITLE
Images not saving in Maccy

### ISSUE THREAD

**Issue by RedFish87** [p0deje/Maccy#732]
### Before Submitting Your Bug Report

- [x] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [x] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

0.29.4 (28

### macOS Version

14.2.1 (23C71)

### Description

Maccy is not including copied screenshots, only text. Not sure what I’m doing wrong.

**Comment by p0deje** [comment]
1. Check Storage settings, make sure Images are turned on.
2. Check Appearance settings, make sure image height is not 1.
3. Try coping other images (e.g. in Safari) - do they show?

**Comment by RedFish87** [comment]
Thanks for your reply.

1. Yep
2. Sorted
3. Yes, they do

Screen-shot images still not showing though. Is there anything else I could try, please?

**Comment by RedFish87** [comment]
Sorted 🙏

I needed a different command to copy a screen shot to clipboard.
