### ISSUE TITLE
Ability to edit/remove items from the list

### ISSUE THREAD

**Issue by emilio-oliveira** [p0deje/Maccy#734]
### Before Submitting Your Feature Request

- [X] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

Sometimes, we have one or two items on the clipboard that we want to remove, without needing to purge the whole list.

### Solution

Open a window with a list of all the clipboard items and allow for the deletion / reorder of items on the list. Alternatively, add a delete icon on the app window next to the item (next to where now you have the key shortcuts info).

**Comment by p0deje** [comment]
1. You can remove it by pressing OPTION+DELETE. 
2. There is no way to edit items - this is out of the scope of the clipboard manager in my opening.

**Comment by kdeyko** [comment]
Sorry for bumping into the closed issue, but the OPTION+DELETE doesn't work for me.
When I select an item in the list and press (and hold) OPTION, the selection focus disappears, and then pressing DELETE does nothing. Releasing the OPTION button makes the selection reappear, btw.

Please let me know if I should raise a new issue or make a short videoclip.

Thanks!

**Comment by p0deje** [comment]
> Sorry for bumping into the closed issue, but the OPTION+DELETE doesn't work for me.
> 
> When I select an item in the list and press (and hold) OPTION, the selection focus disappears, and then pressing DELETE does nothing. Releasing the OPTION button makes the selection reappear, btw.
> 
> 
> 
> Please let me know if I should raise a new issue or make a short videoclip.
> 
> 
> 
> Thanks!

Please make sure you are running the latest version of Maccy and try again. If the problem persists, please open a new issue and provide all the necessary details.

**Comment by kdeyko** [comment]
Ah, right, I was on a rather old version (0.28).
I upgraded to 0.31 and it works now, thanks!
