### ISSUE TITLE
Clipboard retention is limited to a day or less

### ISSUE THREAD

**Issue by p3ngu1nx** [p0deje/Maccy#735]
### Before Submitting Your Bug Report

- [X] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

Version 0.29.4 (28)

### Description

Downloaded Maccy from the App Store. For some reason I can only see two and a half screens worth of recent clipboard and no more than that. I dont see how that could be by design. The utility of the app is quite limited in that regard. Storage size is set to 300 but I dont think that matters. Can you help of im going to have to churn to another product, which I prefer not to. Thanks

**Comment by p0deje** [comment]
Can you please check what's in the "Number of items" in Maccy Appearance preference?

**Comment by p0deje** [comment]
Closing since no response. Please re-open with asked information.

**Comment by p3ngu1nx** [comment]
I have size 300. I think all items get retained as expected but are only available in search. They are not available by scrolling. The issue I have is often I dont know how to search for a particular item. items are usually grouped together, but the one I need is not searchable. An image is a great example. Hence the retention period is misleading. In reality I get about a day worth of retention. I would like to go back a week. The utility of the app is severely limited in that regard in my view. I would have switched long ago but its the only open source app I could find that is credible. ;/ Not a happy user anyhow

**Comment by twknab** [comment]
@p3ngu1nx note: You can increase the number of stored items to `999`. And then can also change the sort order to `Time of first copy` if you want to preserve the ordering exactly.

**Comment by p3ngu1nx** [comment]
Increasing the number does not help. I just want to see and use the screenshot I have taken yesterday or the day before. It's not at all possible atm

**Comment by p0deje** [comment]
@p3ngu1nx Change "Number of items" to 0 in Maccy Appearance settings.

**Comment by p3ngu1nx** [comment]
Thanks. Based on my first impressions the problem is solved!
