### ISSUE TITLE
Incorrect check for "Convert text to simplified Chinese" hotkey - it's not set in system settings, and I can't make Maccy to use it

### ISSUE THREAD

**Issue by ipanasenko** [p0deje/Maccy#736]
### Before Submitting Your Bug Report

- [X] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

0.29.4

### macOS Version

14.3.1

### Maccy Settings

```Shell
{
    "KeyboardShortcuts_delete" = "{\\"carbonKeyCode\\":51,\\"carbonModifiers\\":2048}";
    "KeyboardShortcuts_pin" = "{\\"carbonKeyCode\\":35,\\"carbonModifiers\\":2048}";
    "KeyboardShortcuts_popup" = 0;
    "LaunchAtLogin__hasMigrated" = 1;
    "NSStatusItem Preferred Position Item-0" = 6107;
    "NSWindow Frame com.sindresorhus.Settings.FrameAutosaveName" = "689 477 542 436 0 0 1920 1055 ";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2024-02-26 2:43:30\\U202fPM +0000";
    SUUpdateGroupIdentifier = 996396880;
    enabledPasteboardTypes =     (
        "public.file-url",
        "public.tiff",
        "public.rtf",
        "public.png",
        "public.utf8-plain-text",
        "public.html"
    );
    ignoredPasteboardTypes =     (
        "com.typeit4me.clipping",
        "Pasteboard generator type",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
        "net.antelle.keeweb"
    );
    migrations =     {
        "2020-04-25-allow-custom-ignored-types" = 1;
        "2020-06-19-use-keyboardshortcuts" = 1;
        "2020-09-01-ignore-keeweb" = 1;
        "2021-02-20-allow-to-customize-supported-types" = 1;
        "2021-06-28-add-title-to-history-item" = 1;
        "2021-10-16-remove-dynamic-pasteboard-types" = 1;
        "2022-08-01-rename-suppress-clear-alert" = 1;
        "2022-11-14-add-html-rtf-to-supported-types" = 1;
        "2023-01-22-add-regexp-search-mode" = 1;
    };
}
```

### Description

Hi, thanks for the app!
I would like to assign a ![image](https://github.com/p0deje/Maccy/assets/576152/ee22d20c-a17a-478f-9c11-c63dca7e544c) hotkey to open Maccy, but it says that this hotkey is in use by system settings. I'd removed shortcut and disabled it, but Maccy still doesn't allow to use it.

![image](https://github.com/p0deje/Maccy/assets/576152/dd8e1100-a7ed-423f-a353-debbb506b94e)

![image](https://github.com/p0deje/Maccy/assets/576152/446719e6-c3e5-4eb0-95fb-5a811066487f)

### Steps to Reproduce

1. Open System settings -> Keyboard -> Keyboard Shortcuts -> Services -> Text
2. Disable Simplified Chinese hotkeys and remove assigned combinations
3. Try assigning ![image](https://github.com/p0deje/Maccy/assets/576152/ee22d20c-a17a-478f-9c11-c63dca7e544c) to open Maccy

**Comment by ipanasenko** [comment]
Yes, it did help! Thank you! ❤️

**Comment by p0deje** [comment]
Are you open to making a PR with this?

**Comment by ipanasenko** [comment]
https://github.com/p0deje/Maccy/pull/737
