### ISSUE TITLE
Menu Visibility Issue: Seeking Assistance to Restore Footer Access in App

### ISSUE THREAD

**Issue by mikeghost666** [p0deje/Maccy#738]
### Before Submitting Your Bug Report

- [X] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Description

I initially chose to hide the footer/menu, but I am currently unable to restore it to view the menu or exit. Despite Maccy providing me with a shortcut key for restoration, it proves ineffective, leaving me somewhat locked out of the application. I have attempted to resolve this by deleting and reinstalling the app, but unfortunately, this did not rectify the issue.

**Comment by p0deje** [comment]
Normally you'd just open Maccy and press ⌘, to open preferences. If for some reason it's not working for me, you can reset the setting by running the following in the Terminal.app:

```
defaults delete org.p0deje.Maccy hideFooter
```
