### ISSUE TITLE
Ablity to lock clipboard history with password

### ISSUE THREAD

**Issue by adeekshith** [p0deje/Maccy#74]
Can we have a feature to auto lock the app with password after some time?
This helps secure sensitive clipboard history.

**Comment by p0deje** [comment]
Frankly one can still read history if they have access to your computer. I would say this is a generic privacy issue, so locking the app with password is not the real solution.

I'm happy to consider other solutions but I feel like clipboard managers are flawed by default.

**Comment by p0deje** [comment]
Closing since I'm not going to implement this.
