### ISSUE TITLE
Paste shortcuts not working in Chrome

### ISSUE THREAD

**Issue by bnovak99** [p0deje/Maccy#740]
### Before Submitting Your Bug Report

- [x] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [x] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Settings

```Shell
I am trying to use Command 1, Command 2, etc to paste but when I am in Chrome these shortcuts take me to a different Chrome tab. The only way that I can paste something is from the Maccy drop down menu
```

**Comment by p0deje** [comment]
That's an expected behavior, these shortcuts only work when Maccy is visible.

**Comment by bnovak99** [comment]
Not working when Maccy is visible either. Is there any way to add the paste menu to a mouse right click?

--
Brian Novak
web developer
303-570-8904

**Comment by p0deje** [comment]
> The only way that I can paste something is from the Maccy drop down menu

That's the expected behavior, does it not work? Have you enabled "Paste automatically" in Maccy preferences?
