### ISSUE TITLE
pasting will happen only on the main screen of the mac

### ISSUE THREAD

**Issue by sepehrooo** [p0deje/Maccy#741]
### Before Submitting Your Bug Report

- [X] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

0.29.4

### macOS Version

14.3.1

### Maccy Settings

```Shell
{
    "KeyboardShortcuts_delete" = "{\\"carbonModifiers\\":2048,\\"carbonKeyCode\\":51}";
    "KeyboardShortcuts_pin" = "{\\"carbonModifiers\\":2048,\\"carbonKeyCode\\":35}";
    "KeyboardShortcuts_popup" = "{\\"carbonKeyCode\\":8,\\"carbonModifiers\\":768}";
    "LaunchAtLogin__hasMigrated" = 1;
    "NSWindow Frame com.sindresorhus.Settings.FrameAutosaveName" = "739 470 542 437 0 0 1920 1055 ";
    SUAutomaticallyUpdate = 0;
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2024-03-04 14:52:38 +0000";
    SUSendProfileInfo = 0;
    enabledPasteboardTypes =     (
        "public.html",
        "public.tiff",
        "public.rtf",
        "public.file-url",
        "public.utf8-plain-text",
        "public.png"
    );
    ignoredPasteboardTypes =     (
        "Pasteboard generator type",
        "com.typeit4me.clipping",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
        "net.antelle.keeweb"
    );
    migrations =     {
        "2020-04-25-allow-custom-ignored-types" = 1;
        "2020-06-19-use-keyboardshortcuts" = 1;
        "2020-09-01-ignore-keeweb" = 1;
        "2021-02-20-allow-to-customize-supported-types" = 1;
        "2021-06-28-add-title-to-history-item" = 1;
        "2021-10-16-remove-dynamic-pasteboard-types" = 1;
        "2022-08-01-rename-suppress-clear-alert" = 1;
        "2022-11-14-add-html-rtf-to-supported-types" = 1;
        "2023-01-22-add-regexp-search-mode" = 1;
    };
    pasteByDefault = 1;
    removeFormattingByDefault = 1;
}
```

### Description

When there are multiple screens connected to my mac, when I press CMD+Shift+C, maccy will show on the correct screen. But when I select the one that I want to be pasted, it will paste it on the main screen of the laptop.

**Comment by p0deje** [comment]
Does this happen in all applications or only some specific?

**Comment by p0deje** [comment]
Closing since no response. Please re-open with asked information.

**Comment by mustafa0x** [comment]
This happens in chrome, but not in sublime nor firefox. it's quite frustrating =/

**Comment by p0deje** [comment]
@mustafa0x I see the issues reported from time-to-time related to Chrome, but I cannot ever reproduce the issue and users report it goes away. Can you record a video from 2 screens and share what exactly happens? I'm not sure how to record video from multiple screens though, but there seem to be apps for that.

**Comment by mustafa0x** [comment]
i think this bug is new. not sure what changed.

steps
- laptop + external display
- external display is main display
- chrome is on both screens
- i am typing in chrome in external display
- i press cmd+shift+v
- i select item to paste
- chrome on external display loses focus
- chrome on laptop becomes focused, and content is pasted in it

**Comment by p0deje** [comment]
I've got exactly the same setup and I cannot reproduce the issue. That's why I'm asking for a video, maybe I can spot something else that happens which lead to the bug.

**Comment by mustafa0x** [comment]
Hah, updating chrome fixed!

Thanks @p0deje.

**Comment by alex-cardenas** [comment]
I'm on MacOS Sonoma 14.4.1 with Chrome 123.0.6312.59 and I'm experiencing this issue:
I have my MacBook Pro laptop connected via one USB-C cable to a dock that connects to two external displays. This specific test follows this behavior:

- Have Chrome open on both my laptop screen (main display) and a separate Chrome window on extended display one
- Focus my cursor on extended display text field
- Shift + CMD + C to open Maccy menu
- Click text to paste (I have Paste Automatically turned on)
- Notice text is pasted on main display despite cursor being on extended display

Here is a video recording of that happening: https://imgur.com/a/xN3eLej

**Comment by alex-cardenas** [comment]
Update: I'm new to Maccy. Exploring the settings/preferences, I just tried enabling "Avoid taking application focus" in the Advanced tab and it seems to have fixed this issue. Pasting now pastes on whichever text field I am focused on

**Comment by Eyal-Bahar** [comment]
> Update: I'm new to Maccy. Exploring the settings/preferences, I just tried enabling "Avoid taking application focus" in the Advanced tab and it seems to have fixed this issue. Pasting now pastes on whichever text field I am focused on

This solved my issue! Thanks!!
