### ISSUE TITLE
Cursor is not active in Maccy's search bar by default

### ISSUE THREAD

**Issue by LePeti** [p0deje/Maccy#742]
### Before Submitting Your Bug Report

- [X] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

0.30.0

### macOS Version

14.1 (23B74)

### Maccy Settings

```Shell
{
    "KeyboardShortcuts_popup" = "{\\"carbonModifiers\\":768,\\"carbonKeyCode\\":9}";
    "LaunchAtLogin__hasMigrated" = 1;
    "NSWindow Frame com.sindresorhus.Preferences.FrameAutosaveName" = "689 105 527 666 0 0 1920 1055 ";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2023-04-10 17:33:04 +0000";
    SUUpdateGroupIdentifier = 1919263019;
    clipboardCheckInterval = "0.2";
    enabledPasteboardTypes =     (
        "public.png",
        "public.rtf",
        "public.file-url",
        "public.html",
        "public.tiff",
        "public.utf8-plain-text"
    );
    ignoredPasteboardTypes =     (
        "net.antelle.keeweb",
        "com.agilebits.onepassword",
        "Pasteboard generator type",
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping"
    );
    maxMenuItems = 10;
    menuIcon = maccy;
    migrations =     {
        "2020-04-25-allow-custom-ignored-types" = 1;
        "2020-06-19-use-keyboardshortcuts" = 1;
        "2020-09-01-ignore-keeweb" = 1;
        "2021-02-20-allow-to-customize-supported-types" = 1;
        "2021-06-28-add-title-to-history-item" = 1;
        "2021-10-16-remove-dynamic-pasteboard-types" = 1;
        "2022-08-01-rename-suppress-clear-alert" = 1;
        "2022-11-14-add-html-rtf-to-supported-types" = 1;
        "2023-01-22-add-regexp-search-mode" = 1;
    };
    pasteByDefault = 1;
    popupPosition = center;
    popupScreen = 0;
    removeFormattingByDefault = 1;
    searchMode = fuzzy;
}
```

### Description

When I invoke Maccy (usually via cmd + shift + v but same happens if I click the icon on top), the cursor used to be active in the search bar, so I can start typing/searching immediately. Since a while, this stopped working, and when I type, the search bar is not populated and search doesn't work, unless I click in the bar explicitly and then start typing.

### Steps to Reproduce

1. cmd + shift + v
2. start typing

**Comment by p0deje** [comment]
There were multiple problems in earlier versions of macOS Sonoma that were fixed. Can you try upgrading to the latest 14.4 and see if it helps?

**Comment by LePeti** [comment]
Thanks @p0deje , updating to the latest OS version helped indeed. 🙏
