### ISSUE TITLE
Defaults domain "org.p0deje.Maccy" does not exist

### ISSUE THREAD

**Issue by Sangeppato** [p0deje/Maccy#749]
### Before Submitting Your Bug Report

- [X] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

0.30.0

### macOS Version

14.4

### Maccy Settings

```Shell
Domain /Users/<user>/Library/Containers/org.p0deje.Maccy/Data/Library/Preferences/org.p0deje.Maccy does not exist
```

### Description

The defaults domain "org.p0deje.Maccy" is apparently missing. I have tried to uninstall and re-install the app and all its config files but nothing changed.

### Steps to Reproduce

1. Install Maccy
2. Try to access the "org.p0deje.Maccy" defaults domain

**Comment by p0deje** [comment]
Do you actually experience an issue with that?

**Comment by p0deje** [comment]
Can you try changing some settings in Maccy preferences and then run the command?

**Comment by Sangeppato** [comment]
I'm sorry, after rebooting my Mac it started working again for some reason..
I sincerely apologize for wasting your time, thank you for the support and the great app!

**Comment by p0deje** [comment]
No worries, glad it works now!
