### ISSUE TITLE
Copying text in Word and losing formatting

### ISSUE THREAD

**Issue by simpalsimon** [p0deje/Maccy#75]
Love the app. If I'm working with two word documents open, and want to skim through one document and copy all the bits which I want to have on the clipboard for easy re-ordering, I lose the formatting of the text by switching between what to paste.

So if I copy two bits of text from the same word document, and both have words in bold or italicised, this will be lost if I switch between the two bits in the maccy menu. Is this intended?

**Comment by p0deje** [comment]
It's not quite intended, but it's the way it is. There was a request to allow pasting without formatting so anything pasted from Maccy will lose formatting. I don't know how to support both with and without formatting at the same time as they are contradicting.

**Comment by simpalsimon** [comment]
Could this feature be toggle-able? Just a friendly suggestion.

**Comment by FernandoMiguel** [comment]
The way I did in the past is cmd shift V pastes without format

**Comment by simpalsimon** [comment]
> The way I did in the past is cmd shift V pastes without format

Can this be done in the current version?

**Comment by FernandoMiguel** [comment]
> > The way I did in the past is cmd shift V pastes without format
> 
> Can this be done in the current version?

don't think this app ever supported.
but is something, MS Office, chrome, and even some web editors supported for many years

**Comment by simpalsimon** [comment]
> > > The way I did in the past is cmd shift V pastes without format
> > 
> > 
> > Can this be done in the current version?
> 
> don't think this app ever supported.
> but is something, MS Office, chrome, and even some web editors supported for many years

Would be good to have this re-integrated into maccy then. Would like to paste with formatting preserved.

**Comment by p0deje** [comment]
> The way I did in the past is cmd shift V pastes without format
We cannot do this in Maccy, can we?

**Comment by alapolloni** [comment]
Hi.  I think that Maccy should keep/save the formatting.

Then, to paste without....you do the normal Maccy select action Shift+Cmd+C -> select what you want -> and then use the standard MacOS shortcut to past without formatting.  
> Option+Shift+Command+V to paste text without any formatting

While there are other alternatives this seems the most straightforward/easiest to implement.

**Comment by p0deje** [comment]
Hm, then you cannot use keyboard shortcuts to select for example item number 5 on the list. Don't you think that makes the whole UX inconsistent?

**Comment by alapolloni** [comment]
I think I'm missing something from your question.  
I'm using Maccy with the defaults so when I hit enter on an entry or cmd-5 then that text is copied to the clipboard(it doesn't paste).  Only then do I hit Ctr-V to paste.  If RICH text was copied to the clipboard.....then I'd have the option to use the MacOS shortcut Opt+Shift+CMD+V to paste with no formatting.

I get that my suggestion wouldn't work at all if you have **Automatically Paste by Default** turned on.   (actually, I might go and turn that option on now that I know about it 👍 ..... I went back and scanned through the documentation to answer your question.

Looking at your proposed Action/Behavior table.... both of the 1st two actions start with an "enter".  Should the second one be "shift+enter". ?  (for **removes formatting and copies item** )

**Comment by p0deje** [comment]
Ok, I think what needs to change now is to have Maccy preserve formatting. I think it should work once the work on #84 is completed. After that, if we get requests to remove formatting we can get back to adding <kbd>SHIFT</kbd> behavior to remove it.

**Comment by p0deje** [comment]
Implemented via 6a2b6aa

**Comment by lamhoangtung** [comment]
This is exact use cases I am looking for @simpalsimon. Thanks @p0deje for creating and open source such great software

Regarding UI/UX for this issue, can we learn from [Pasta](https://getpasta.com), another clipboard manager, which looks like this:

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/26834698/152162791-d3e9c5bb-4418-4819-b8d8-5e608710aa60.png">

By having a floating windows that can be pin on the screen, we can simply see the copied text visually and click into each snippet to paste it. This was almost a clone of the UX of [Office Clipboard](https://support.microsoft.com/en-us/office/use-the-office-clipboard-028903c7-66ea-4eb0-b0a1-bacdb952e3a1) which Microsoft does not support on MacOS but do on Windows.

In theory, I might just simply use Pasta. But Pasta are very buggy with MS Office, I frequently meet issue similar to #353 while using it, thus making it unusable. I tried to contact Pasta developer for help, but they seems can't fix the problem. Fortunately, I don't encounter those issue with Maccy.

How's your take on this @p0deje. Do you think adding this new UX for Maccy possible? If yes, are you willing to implement it ?

I also willing to make a fork and do the UI by myself, but I don't had any experience in Swift and in building MacOS application yet. I'm sure I can pick it up, but I will need a lot of help from you, starting with a feasibility assessment.

**Comment by p0deje** [comment]
@lamhoangtung I don't think there is a way to preserver NSMenu (which is how the popup is implemented) to remain open when selecting item. If there is one, you can try implementing a simple "anchor" button to keep the menu open. The rest should probably just work. I'm however against introducing any new UI in addition to what we currently have (e.g. custom achored window with history list).
