### ISSUE TITLE
select & copy several items at a time

### ISSUE THREAD

**Issue by noripcord** [p0deje/Maccy#750]
### Before Submitting Your Feature Request

- [x] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [x] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

I really like this app, it's lightweight and more or less does everything I expect from a clipboard manager, without being so bloated with features I'd never use. 

I come from an app called Copied for macos, and it has one feature that I really, really miss. And once you hear about it I think it'll interest you as well.

The useful thing about the selecting various items at a time and copying them is an scenario where I am programming and have values that want to convert to a list or something, and they're not together, obviously. So I used to copy one at a time and then they would all end up in the list (1 through 6, for example. ) Then I'd bring up the clipboard manager and select the six (like shift and arrow or mouse on one, then mouse on the next while holding shift), and depending on how the selection was done (top to bottom or bottom to top), the app would set the clipboard to the 6 items. It's really useful, hope this was of some small help.

### Solution

It's not really a problem, so it has no solution :)

**Comment by noripcord** [comment]
Just a small improvement that I find really useful.

**Comment by p0deje** [comment]
I guess that's pretty much #239, let's continue in the other issue
