### ISSUE TITLE
Maccy cancels out Spotlight search box

### ISSUE THREAD

**Issue by nemaa3** [p0deje/Maccy#751]
### Before Submitting Your Bug Report

- [X] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

0.30.0

### macOS Version

14.4

### Maccy Settings

```Shell
{
    "KeyboardShortcuts_delete" = "{\\"carbonModifiers\\":2048,\\"carbonKeyCode\\":51}";
    "KeyboardShortcuts_pin" = "{\\"carbonKeyCode\\":35,\\"carbonModifiers\\":2048}";
    "KeyboardShortcuts_popup" = "{\\"carbonKeyCode\\":9,\\"carbonModifiers\\":768}";
    "LaunchAtLogin__hasMigrated" = 1;
    "NSStatusItem Visible Item-0" = 0;
    "NSWindow Frame com.sindresorhus.Settings.FrameAutosaveName" = "634 474 542 436 0 0 1710 1069 ";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2024-03-23 16:01:56 +0000";
    avoidTakingFocus = 0;
    enabledPasteboardTypes =     (
        "public.file-url",
        "public.rtf",
        "public.tiff",
        "public.html",
        "public.utf8-plain-text",
        "public.png"
    );
    historySize = 20;
    ignoredPasteboardTypes =     (
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "Pasteboard generator type",
        "com.agilebits.onepassword",
        "net.antelle.keeweb"
    );
    migrations =     {
        "2020-04-25-allow-custom-ignored-types" = 1;
        "2020-06-19-use-keyboardshortcuts" = 1;
        "2020-09-01-ignore-keeweb" = 1;
        "2021-02-20-allow-to-customize-supported-types" = 1;
        "2021-06-28-add-title-to-history-item" = 1;
        "2021-10-16-remove-dynamic-pasteboard-types" = 1;
        "2022-08-01-rename-suppress-clear-alert" = 1;
        "2022-11-14-add-html-rtf-to-supported-types" = 1;
        "2023-01-22-add-regexp-search-mode" = 1;
    };
    pasteByDefault = 1;
    showInStatusBar = 0;
}
```

### Description

When I open Spotlight (Cmd + Space), then open Maccy context menu (Cmd + Shift + V), Spotlight is closed/ cancelled out, making using Maccy on Spotlight impossible.
Clip: https://www.youtube.com/watch?v=BZZPr9gkYg4

### Steps to Reproduce

1. Open Spotlight (Cmd + Space)
2. With the text cursor being inside the Spotlight search box, use Maccy 'Open' shorcut (in my case Cmd + Shift + V) to open the Maccy context menu
3. Maccy context menu does appear, but the Spotlight window is closed/ cancelled out

**Comment by p0deje** [comment]
That's expected, you can work it around by enabling "Avoid taking application focus" in Advanced preferences.
