### ISSUE TITLE
Don't show this again Pop-up

### ISSUE THREAD

**Issue by metin-durmaz** [p0deje/Maccy#753]
### Before Submitting Your Feature Request

- [ ] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [ ] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

When clearing the copy history, a pop-up appeared for verification. I had selected the option to not show this again. I want to take this option back. I want it to ask "Are you sure ?" every time I clear the history.

**Comment by p0deje** [comment]
Run the following command in Terminal.app:

```
defaults delete org.p0deje.Maccy suppressClearAlert
```
