### ISSUE TITLE
Cannot paste automatically to Spotlight

### ISSUE THREAD

**Issue by nemaa3** [p0deje/Maccy#754]
### Before Submitting Your Bug Report

- [X] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

0.30.0

### macOS Version

14.4

### Maccy Settings

```Shell
{
"KeyboardShortcuts_delete" = "{\"carbonModifiers\":2048,\"carbonKeyCode\":51}";
"KeyboardShortcuts_pin" = "{\"carbonKeyCode\":35,\"carbonModifiers\":2048}";
"KeyboardShortcuts_popup" = "{\"carbonKeyCode\":9,\"carbonModifiers\":768}";
"LaunchAtLogin__hasMigrated" = 1;
"NSStatusItem Visible Item-0" = 0;
"NSWindow Frame com.sindresorhus.Settings.FrameAutosaveName" = "634 588 442 322 0 0 1710 1069 ";
SUEnableAutomaticChecks = 1;
SUHasLaunchedBefore = 1;
SULastCheckTime = "2024-03-23 16:01:56 +0000";
avoidTakingFocus = 1;
enabledPasteboardTypes = (
"public.file-url",
"public.rtf",
"public.tiff",
"public.html",
"public.utf8-plain-text",
"public.png"
);
historySize = 20;
ignoredPasteboardTypes = (
"de.petermaurer.TransientPasteboardType",
"com.typeit4me.clipping",
"Pasteboard generator type",
"com.agilebits.onepassword",
"net.antelle.keeweb"
);
migrations = {
"2020-04-25-allow-custom-ignored-types" = 1;
"2020-06-19-use-keyboardshortcuts" = 1;
"2020-09-01-ignore-keeweb" = 1;
"2021-02-20-allow-to-customize-supported-types" = 1;
"2021-06-28-add-title-to-history-item" = 1;
"2021-10-16-remove-dynamic-pasteboard-types" = 1;
"2022-08-01-rename-suppress-clear-alert" = 1;
"2022-11-14-add-html-rtf-to-supported-types" = 1;
"2023-01-22-add-regexp-search-mode" = 1;
};
pasteByDefault = 1;
showInStatusBar = 0;
}
```

### Description

Enable "Paste automatically" option, and enable "Avoid taking application focus" option. When try pasting automatically to Spotlight, nothing happens. Works well with everything I tried so far, except for Spotlight. 
Please see this clip: https://www.youtube.com/watch?v=6PrEISjat7k

### Steps to Reproduce

1. Under 'Preference', enable "Paste automatically" option
2. Under 'Preference, enable "Avoid taking application focus" option
3. Copy something
4. Open Spotlight (Cmd + Space). The Spotlight search box is in focus
5. Open Maccy clipboard list(in my case it's Cmd + Shift + V)
6. Select an item from the list to paste automatically. Nothing happens, and I can hear a system sound that most likely means "not a valid action"

**Comment by p0deje** [comment]
Yes, there is not much that can be done about it, unfortunately. When Maccy hides itself before pasting, the Spotlight doesn't get focused and I haven't found a way to force-fully focus it before pasting.

**Comment by Chen1Plus** [comment]
If you are originally inputing something, after trigger this bug, the keyboard and mouse is not usable.
