### ISSUE TITLE
[Feature request] Convert to UPPERCASE / Capitalcase / lowercase before pasting

### ISSUE THREAD

**Issue by GorvGoyl** [p0deje/Maccy#767]
### Before Submitting Your Feature Request

- [X] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

It would be nice if the tool could do a little bit of text transformation before pasting like UPPERCASE / Capitalcase / lowercase.

**Comment by p0deje** [comment]
You can do this via Shortcuts, here is an example of trimming whitespace before pasting, but you can adapt it to uppercase/lowercase/etc

<img width="1312" alt="Screenshot 2024-04-20 at 12 11 12" src="https://github.com/p0deje/Maccy/assets/665846/93c1d922-20fb-4c81-9b13-1ea137e4ff07">
