### ISSUE TITLE
cmd+[ to dismiss maccy same as ctrl+[

### ISSUE THREAD

**Issue by tmpm697** [p0deje/Maccy#768]
### Before Submitting Your Feature Request

- [X] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

I use both `ctrl+[` and more often `cmd+[` to dismiss stuffs around (IDEs, terminals)

So it'll nice if we can add more option to use `cmd+[` works same as `ctrl+[`

ty.

**Comment by p0deje** [comment]
That's the first time I've heard about these shortcuts. Can you tell me what those are doing?

**Comment by tmpm697** [comment]
idk what is default `ctrl+[` on macos, but `ctrl+[` is default to `escape` if u use (neo)vim.

I use maccy with default settings, `ctrl-c` or `ctrl+[` has same effect (dismiss maccy).

In my case I also use left `cmd` a lot, and sometime it's quicker to use `cmd+[` than `ctrl+[`

**Comment by tmpm697** [comment]
it seems also default that i can use `ctrl+n/p` to navigate up/down entries, but it's ideal if we can re-map this to like `cmd+n/p` or `opt+n/p`

**Comment by tmpm697** [comment]
> ctrl+[ has no effect on my Maccy, I wonder how it's being closed.

that's werid, so how `normally` u dismiss maccy floating window?

and yes, i use `cmd` mainly and totally get rid of `ctrl` in my workflow, so trigger maccy and reaching `ctrl` break it.

**Comment by p0deje** [comment]
> that's werid, so how normally u dismiss maccy floating window?

I press Escape, or press the popup shortcut again (default CMD+SHIFT+C)

**Comment by tmpm697** [comment]
![Screenshot 2024-04-24 at 12 41 18 PM](https://github.com/p0deje/Maccy/assets/48467427/591a8877-0887-41cc-a200-77c6e830b03a)

weirdly, i tried cmd+shift+c, does not work for me, probably i changed some settings idk.

**Comment by p0deje** [comment]
The shortcut to close is the same as to open. In your case, it's COMMAND+D.

**Comment by tmpm697** [comment]
> The shortcut to close is the same as to open. In your case, it's COMMAND+D.

oh that's nice, but if i can keep holding `cmd` and use `cmd+n/p` to navigate up/down the list is ideal. ty.

**Comment by p0deje** [comment]
@tmpm697 Unfortunately, this means potential conflicts with pinned items using `n/p` letters. Also, this would not be consistent with the rest of macOS applications.

**Comment by p0deje** [comment]
> currently u can change pinned item via opt+p which is not cmd+p.

users can change pinned item key via settings - 
<img width="625" alt="Screenshot 2024-04-24 at 09 41 14" src="https://github.com/p0deje/Maccy/assets/665846/b10484bb-7d8a-4027-b7ea-f5e333c470b3">

P is already forbidden, but N is still allowed

**Comment by tmpm697** [comment]
![Screenshot 2024-04-25 at 12 52 44 AM](https://github.com/p0deje/Maccy/assets/48467427/fe229193-27bb-423f-b9ef-bfa37af398eb)

why my list is empty like above image? i think the keybinding implementation is due to each app?

like in vscode, i can map `cmd+n/p` to whatever i want while i'm in that app.

**Comment by p0deje** [comment]
> why my list is empty like above image? i think the keybinding implementation is due to each app? double click does not take any effect (expect to create new entry)

You need to first pin something using OPTION+P.

> like in vscode, i can map cmd+n/p to whatever i want while i'm in that app.

Yes, but CMD+N is reserved for pins. I understand your use case, but I don't see myself implementing this. There is quite a lot to do to allow customization of such shortcuts, translate into all languages that Maccy supports and somehow deal with conflicts of pins. Sorry, but I don't think Maccy should allow to change every single keybinding it supports.

You are still welcome to send PRs implementing this or feel free to fork it and replace the keybindings.

**Comment by tmpm697** [comment]
I don't mind if it's `cmd+j/k`, in fact i use `cmd+j/k` to navigate suffs more than `cmd+n/p`, 

idk why need translate into all languages but this can be just for us/uk keyboard layouts?

**Comment by p0deje** [comment]
> I don't mind if it's cmd+j/k, in fact i use cmd+j/k to navigate suffs more than cmd+n/p,

Again, those would conflict with pinned letters.

> idk why need translate into all languages but this can be just for us/uk keyboard layouts?

The settings page to change this keys would need to be translated to all languages.
