### ISSUE TITLE
Not move copied value up the list after autopaste

### ISSUE THREAD

**Issue by jmablans** [p0deje/Maccy#77]
Dear Alex, 

First of all, thanks for this great tool. It's precisely what I was looking for. Greatly improved my productivity!

I have a features request/question: Would it be possible to **not** move an item up the list after pasting it by default?

E.g. say I copy an item: `item_a`. I then select and pasteByDefault an arbitrary random other item from my copy history `item_x`. Now, `item_x` moves to the top of the list and pressing `Cmd+v` pastes `item_x`. My desired behaviour is that `item_x` does not move up the list and the top item is still `item_a`. Does this make sense? If so, is this possible in the current version of the app?

Thanks in advance, 

Jan

**Comment by p0deje** [comment]
Hi Jan,

What's the actual use case for this behavior? The current behavior makes sense if you think that list _always_ sorted chronologically so the last item in clipboard should always be on top. In your case, what is the reason to have it different?

**Comment by jmablans** [comment]
Hi Alex, 

Thanks for your swift reply (pun somewhat intended ;-) ). My use case is the following:

I am daily running mulitple repeated commands on Google Cloud Console shell to enter a certain k8 pod/compute node. 
- first, I request the list of currently active pods (their names change somewhat randomly, so I have to do this), using a command from my clipboard history (i.e. `kubectl get pods  ...`) 
- then, I copy one of the names into my clipboard
- then, to enter that pod, I need a command from my history, combined with the name I just copied. The command being `kubectl exec -it  <pod name>  --namespace=production -- /bin/bash`. I paste this command and therefore this ends up at the top of my clipboard. 
- Now comes the tricky part. I only copied the name of the pod just yet, the rest is from history. So my intuition would be that this copied value is still on the top of my clipboard and therefore under Cmd+v, but this is not the case. I have to "search" or at least select this name again to copy it easily. 

Does this explain the situation?

Kind regards,


Jan

**Comment by p0deje** [comment]
There are a few problems if I want to implement something like that:

1. The only reliable way to _paste_ is to actually _copy_ programmatical and then send CMD+V to macOS. Thus, it doesn't seem to be possible to just _paste and not copy_.
2. I can implement sorting by the time of the first copy. In your case, it means that the pod name would remain on top of the Maccy list even after you paste the kubectl exec command. However, it won't be in macOS clipboard (because of point 1), so you'll still need to open Maccy and paste pod name from there.

**Comment by p0deje** [comment]
Since 0.9.0 you can use pins or set sorting to `firstCopiedAt` to achieve your goals. Please let me know if that doesn't resolve it.
