### ISSUE TITLE
When I try and pin an item all it does is type the letter π! 

### ISSUE THREAD

**Issue by simonz21** [p0deje/Maccy#773]
### Before Submitting Your Bug Report

- [ ] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [ ] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

**Comment by p0deje** [comment]
Please provide all the required information in the bug (settings/versions/etc).

**Comment by simonz21** [comment]
Sorry, MacOS (latest), Maccy version latest. No, wait, just updated. Working now! My bad. Sorry!

 

 

From: Alex Rodionov ***@***.***>
Reply to: p0deje/Maccy ***@***.***>
Date: Saturday 27 April 2024 at 00:43
To: p0deje/Maccy ***@***.***>
Cc: Simon ***@***.***>, Author ***@***.***>
Subject: Re: [p0deje/Maccy] When I try and pin an item all it does is type the letter π! (Issue #773)

 

Please provide all the required information in the bug (settings/versions/etc).

**Comment by simonz21** [comment]
While I have your ear, can I Make a suggestion? I’m guessing you have seen ClipClip on PC? Been using it for years, and I’d be using it here if they got off their arses and did a Mac version. But I’ve been using Maccy for years too, and it’s really helpful. However, ClipClip’s ability to store clips in folders (on Google drive so my other PC’s cn access same clips) is really powerful, and turns the clipboard from an incidental short-term keyboard helper, to a long-term and heavily used productivity tool. There is a massive difference in the way I use the two machines (Mac v PC) and the reason I prefer working on my PC day-day is ClipClp. I use it several times/hour all day every day.

 

But thank you for developing Maccy as without it I would have sold my Macbook a long time ago.

 

 

 

 

 

From: Alex Rodionov ***@***.***>
Reply to: p0deje/Maccy ***@***.***>
Date: Saturday 27 April 2024 at 00:43
To: p0deje/Maccy ***@***.***>
Cc: Simon ***@***.***>, Author ***@***.***>
Subject: Re: [p0deje/Maccy] When I try and pin an item all it does is type the letter π! (Issue #773)

 

Please provide all the required information in the bug (settings/versions/etc).

**Comment by p0deje** [comment]
I think what you describe with ClipClip is a snippet manager rather than a clipboard manager tool. Even though I can see how useful it might be, I don't envision Maccy as a productivity application to store/reuse many text snippets for various common operations. I think there are better suited tools for that.
