### ISSUE TITLE
Global shortcut to Clear stored content without having to reveal current stored content

### ISSUE THREAD

**Issue by nasuoa** [p0deje/Maccy#775]
### Before Submitting Your Feature Request

- [X] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

So there's the "Clear" shortcut: ⌥⌘⌫

It seems that the only way to activate it is to have Maccy opened up (either by clicking on it, or opening it with the global shortcut).

Is it possible to make a global Clear shortcut, so one doesn't need to open up Maccy and reveal what's in the stored content? Often we need to copy-paste credential, for example imagine we copied a newly created authentication token, or something else sensitive. Quite often I am screensharing or having my system shared on another projector. It would be preferrable in such situations to Clear the content globally/directly without even opening Maccy (as that reveals the stored content). 

I do appreciate the benefit of the two-step process at the moment (Open first, then Clear) as that lets the user eyeball what's about to be deleted. But sometimes we need to directly Clear without letting other eyeballs see the content 😝

Thanks for considering!

**Comment by p0deje** [comment]
You can add the custom Shortcut workflow - https://www.icloud.com/shortcuts/e756634285ef413db90a39fc6e91d9ec. Make sure to assign it to a global shortcut you prefer like this:

<img width="862" alt="Screenshot 2024-05-01 at 15 53 21" src="https://github.com/p0deje/Maccy/assets/665846/9cb2c6ba-5e7d-4343-bc3d-9ee2ded079fb">

**Comment by p0deje** [comment]
My bad, this is now fixed and will work correctly in the next version.

**Comment by p0deje** [comment]
Once a new version of Maccy is released (for example 0.32.0), the existing shortcut will start working.
