### ISSUE TITLE
Type Clipboard

### ISSUE THREAD

**Issue by dwt** [p0deje/Maccy#776]
### Before Submitting Your Feature Request

- [ ] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [ ] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

When working with Virtual Machines or Remote Desktops, Paste often does not work as expected. This can often be worked around with clipboard sharing - if supported, but not always.

What still works is just typing out stuff - but that can be tedious, especially when using strong passwords.

Would you consider adding the feature to type the clipboard? I've seen numerous feature requests before that seem to allude to this feature but seem to have found different workarounds.

### Solution

Ideally there was a shortcut when pasting from Maccy, that would just type the content of the selected clipboard instead of pasting it.

**Comment by p0deje** [comment]
You can already do that via Shortcuts. Here is an example of taking the last item and pasting it via retyping. You can assign it to a custom shortcut in Shorctus too.

<img width="1312" alt="Screenshot 2024-05-06 at 07 47 05" src="https://github.com/p0deje/Maccy/assets/665846/fc84cfff-aa9d-45f6-a782-2bc1f6df3826">
