### ISSUE TITLE
Exclude Universal Clipboard

### ISSUE THREAD

**Issue by brstegge** [p0deje/Maccy#780]
### Before Submitting Your Feature Request

- [X] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

With Handoff turned on, Maccy collects items copied to the clipboard on my iPhone and iPad via Apple's Universal Clipboard feature. Given my MacBook is a work device, this can lead to some personal data being captured by Maccy that I would prefer it not to collect/retain as part of the clipboard history. Without Maccy, Universal Clipboard clippings would be ephemeral and displaced the next time I copied anything on MacOS or my mobile devices. 

### Solution

I'd prefer to exclude Universal Clipboard items from Maccy without needing to disable Handoff entirely (it's all or nothing, no granular controls to just disabled Universal Clipboard).

**Comment by p0deje** [comment]
You can add `com.apple.is-remote-clipboard` to ignore pasteboard types in Maccy.
