### ISSUE TITLE
Named pins

### ISSUE THREAD

**Issue by slyons** [p0deje/Maccy#782]
### Before Submitting Your Feature Request

- [X] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

I have a number of pins that have very similar-looking contents. Date times, Base64 encoded strings, etc.

### Solution

 It would be great to be able to give a name to a pin that shows up as a prefix in the UI, eg:

* ```AAAABBCCCDDEE...``` **[Bad token]** `Cmd-A`
* ```2024-01-01 00:00:00``` **[Error Timestamp]** `Cmd-B`

**Comment by p0deje** [comment]
You can give titles to pins in Maccy preferences.
