### ISSUE TITLE
Buggy with Mac clipboard. Sugestions?

### ISSUE THREAD

**Issue by JCDC85** [p0deje/Maccy#783]
### Before Submitting Your Bug Report

- [X] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [ ] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

.30.0

### macOS Version

14.4.1

### Description

It's less a bug with Maccy and more with Mac. I'm just curious if anyone else has had this problem and fixed it. Most items copy/paste. correctly and get logged in Maccy. But occasionally, I will cmd-C something and cmd-v it somewhere, but then when I try to paste it again,  it won't paste anything and does not show in Maccy history.
I have ensured no apps are ignored in the maccy settings.

**Comment by p0deje** [comment]
Some applications register a one-off copy that is removed after some time from the system clipboard. I'm not sure which ones are doing this exactly, but I recall some password-manager apps did that. Maccy would also respect that and remove such entries from its history too.

I'm going to close this for now. Feel free to re-open if there is anything to change.
