### ISSUE TITLE
app often hangs after being updated to 0.31.0

### ISSUE THREAD

**Issue by Xinghui-Wu** [p0deje/Maccy#786]
### Before Submitting Your Bug Report

- [X] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

0.31.0

### macOS Version

13.6.1

### Maccy Settings

```Shell
{
    "KeyboardShortcuts_delete" = "{\\"carbonModifiers\\":2048,\\"carbonKeyCode\\":51}";
    "KeyboardShortcuts_pin" = "{\\"carbonModifiers\\":2048,\\"carbonKeyCode\\":35}";
    "KeyboardShortcuts_popup" = "{\\"carbonModifiers\\":768,\\"carbonKeyCode\\":8}";
    "LaunchAtLogin__hasMigrated" = 1;
    "NSStatusItem Preferred Position Item-0" = 569;
    "NSWindow Frame SUUpdateAlert" = "410 357 620 398 0 0 1440 875 ";
    "NSWindow Frame com.sindresorhus.Settings.FrameAutosaveName" = "463 318 367 460 0 0 1440 875 ";
    SUAutomaticallyUpdate = 0;
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2024-05-31 03:35:25 +0000";
    SUSendProfileInfo = 0;
    SUUpdateGroupIdentifier = 4046686042;
    enabledPasteboardTypes =     (
        "public.utf8-plain-text",
        "public.file-url",
        "public.tiff",
        "public.png",
        "public.rtf",
        "public.html"
    );
    ignoredPasteboardTypes =     (
        "Pasteboard generator type",
        "net.antelle.keeweb",
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "com.agilebits.onepassword"
    );
    migrations =     {
        "2020-04-25-allow-custom-ignored-types" = 1;
        "2020-06-19-use-keyboardshortcuts" = 1;
        "2020-09-01-ignore-keeweb" = 1;
        "2021-02-20-allow-to-customize-supported-types" = 1;
        "2021-06-28-add-title-to-history-item" = 1;
        "2021-10-16-remove-dynamic-pasteboard-types" = 1;
        "2022-08-01-rename-suppress-clear-alert" = 1;
        "2022-11-14-add-html-rtf-to-supported-types" = 1;
        "2023-01-22-add-regexp-search-mode" = 1;
    };
    pasteByDefault = 0;
    searchMode = mixed;
    showRecentCopyInMenuBar = 0;
    suppressClearAlert = 1;
}
```

### Description

Maccy 0.30.0 worked well for all the functions.
However, after I updated it to 0.31.0, the app ofter hangs while pressing the shortcuts to choose the items. Even if I quit the app and try to restart it, it still hangs while launching.

### Steps to Reproduce

1. Maccy hangs when I copy anything
2. Maccy hangs when I would like to select any item
3. Maccy hangs when I restart the app or when I reboot my Mac

**Comment by Xinghui-Wu** [comment]
Especially when I would like to add new pinned items or select one of the pinned items, the app always hangs.

**Comment by Xinghui-Wu** [comment]
The activity monitor shows that CPU usage is up to 99.0+.

Even if I downgraded the app back to 0.30.0, this hanging issue still exists.

**Comment by p0deje** [comment]
Will the issue go away if you clear the history?

**Comment by Xinghui-Wu** [comment]
When I used brew to uninstall Maccy 0.31.0 and reinstall Maccy 0.30.0, this issue still existed.
However, when I used a cleaning tool (such as CleanMyMac) to uninstall Maccy 0.31.0 and reinstalled it by brew, this issue went away.
It seemed that the cleaning tool detected **a sandbox file (about 5GB) of Maccy** and deleting this file could make everything work well again.

**Comment by p0deje** [comment]
Yeah, the issue was that you had huge copies in your storage. Please, re-open if issue persists.
