### ISSUE TITLE
conflicts of command + num

### ISSUE THREAD

**Issue by dengjfeng** [p0deje/Maccy#787]
### Before Submitting Your Feature Request

- [ ] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [ ] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

Shortcut key command + number conflicts with the tab switching shortcut key of mainstream software. Hope to support modifying the shortcut key for quickly selecting a paste entry.

**Comment by p0deje** [comment]
You need to open Maccy so it's visible before attempting to use shortcut. This way there are no conflicts.
