### ISSUE TITLE
"dontIgnoreOnlyNextEvent" for when Maccy is currently ignoring

### ISSUE THREAD

**Issue by YBPN** [p0deje/Maccy#788]
### Before Submitting Your Feature Request

- [X] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

It would be nice to have this command:
`defaults write org.p0deje.Maccy dontIgnoreOnlyNextEvent true`

The `dontIgnoreOnlyNextEvent` would be for when I want Maccy to capture just the next copy event.

Thank you for Maccy!

**Comment by p0deje** [comment]
Can you elaborate on the use case?

**Comment by YBPN** [comment]
An app or website where the clipboard is frequently used by text-editing macros (implemented via Keyboard Maestro), during which Maccy should ignore the clipboard. But occasionally an explicit copy is performed (command+C) by the user, which Maccy should not ignore.

**Comment by YBPN** [comment]
And also some macros where saving the clipboard to Maccy is desired. Although, tbh, I've simply been toggling Maccy on and off via `defaults write` where relevant, so `dontIgnoreOnlyNextEvent` would just be a nice-to-have.

**Comment by p0deje** [comment]
> An app or website where the clipboard is frequently used by text-editing macros (implemented via Keyboard Maestro), during which Maccy should ignore the clipboard. But occasionally an explicit copy is performed (command+C) by the user, which Maccy should not ignore.

Hmm, I wonder if it's possible to simply integrated Maccy into Keyboard Maestro so when it performs actions, Maccy doesn't store new copies. I'm not familiar with the app though, but I think it should be possible to execute `defaults write ...` before you start a macro and afterwards too.

**Comment by p0deje** [comment]
> And also some macros where saving the clipboard to Maccy is desired. Although, tbh, I've simply been toggling Maccy on and off via defaults write where relevant, so dontIgnoreOnlyNextEvent would just be a nice-to-have.

Since there is a way to implement via existing `defaults write ...` - I'm going to close this since I don't have any capacity to add this new feature, even though it's fairly easy to implement. Please, send PRs if you are interested in adding it!
