### ISSUE TITLE
Menu bar icon disappears under some circumstances (macOS Sequoia developer beta)

### ISSUE THREAD

**Issue by meadowsys** [p0deje/Maccy#789]
### Before Submitting Your Bug Report

- [X] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

0.31.0

### macOS Version

15.0

### Maccy Settings

```Shell
{
    "KeyboardShortcuts_delete" = "{\\"carbonModifiers\\":512,\\"carbonKeyCode\\":51}";
    "KeyboardShortcuts_pin" = "{\\"carbonKeyCode\\":35,\\"carbonModifiers\\":2048}";
    "KeyboardShortcuts_popup" = "{\\"carbonModifiers\\":4864,\\"carbonKeyCode\\":8}";
    "LaunchAtLogin__hasMigrated" = 1;
    "NSStatusItem Preferred Position Item-0" = 535;
    "NSWindow Frame SUStatusFrame" = "664 709 400 134 0 0 1728 1079 ";
    "NSWindow Frame SUUpdateAlert" = "542 510 644 398 0 0 1728 1079 ";
    "NSWindow Frame com.sindresorhus.Preferences.FrameAutosaveName" = "589 634 532 262 0 0 1728 1079 ";
    "NSWindow Frame com.sindresorhus.Settings.FrameAutosaveName" = "510 547 442 322 0 0 1728 1079 ";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2024-06-11 02:34:46 +0000";
    SUSendProfileInfo = 0;
    SUUpdateGroupIdentifier = 1664455440;
    WebKitDefaultFontSize = 13;
    WebKitJavaScriptEnabled = 0;
    WebKitPluginsEnabled = 0;
    WebKitStandardFont = "-apple-system-font";
    WebKitUserStyleSheetEnabledPreferenceKey = 1;
    WebKitUserStyleSheetLocationPreferenceKey = "/Applications/Maccy.app/Contents/Frameworks/Sparkle.framework/Resources/ReleaseNotesColorStyle.css";
    avoidTakingFocus = 1;
    clearOnQuit = 0;
    clearSystemClipboard = 0;
    enabledPasteboardTypes =     (
        "public.png",
        "public.html",
        "public.rtf",
        "public.utf8-plain-text",
        "public.file-url",
        "public.tiff"
    );
    hideFooter = 0;
    hideTitle = 0;
    historySize = 500;
    ignoreEvents = 0;
    ignoreOnlyNextEvent = 0;
    ignoredPasteboardTypes =     (
    );
    imageMaxHeight = 200;
    maxMenuItemLength = 50;
    maxMenuItems = 0;
    menuIcon = maccy;
    migrations =     {
        "2020-04-25-allow-custom-ignored-types" = 1;
        "2020-06-19-use-keyboardshortcuts" = 1;
        "2020-09-01-ignore-keeweb" = 1;
        "2021-02-20-allow-to-customize-supported-types" = 1;
        "2021-06-28-add-title-to-history-item" = 1;
        "2021-10-16-remove-dynamic-pasteboard-types" = 1;
        "2022-08-01-rename-suppress-clear-alert" = 1;
        "2022-11-14-add-html-rtf-to-supported-types" = 1;
        "2023-01-22-add-regexp-search-mode" = 1;
    };
    pinTo = bottom;
    popupPosition = statusItem;
    popupScreen = 0;
    previewDelay = 200;
    removeFormattingByDefault = 0;
    searchMode = fuzzy;
    showRecentCopyInMenuBar = 0;
    sortBy = lastCopiedAt;
}
```

### Description

I've discovered after updating to macOS Sequoia developer beta, Maccy's title bar item will dissappear sometimes. The app still appears in activity monitor, and the space for the icon is still there (unlike quitting, where it disappears fully).

After messing with it more, I found out that it only disappears when the cursor is hovering over it (including the menu bar icon and the popup window). If the cursor is moved away from the menu bar icon and the popup when it closes (pressing esc or clicking outside it), it seems to be okay.

**EDIT**: The "Open" keyboard shortcut does still work, regardless of if the menu bar icon had disappeared or not

### Steps to Reproduce

1. Click menu bar icon to open the popup
2. Click it again, 
3. Observe that when it closes, the menu bar icon becomes invisible, the space stays, and clicking the space where the icon was does nothing
4. Open activity monitor, observe "Maccy" is still there and running
5. Opening Maccy via other means (dock icon, spotlight, from Finder `/Applications`, etc) restores the icon as if nothing happened

when icon stays:

1. Click menu bar icon to open the popup
2. Move mouse away from the window (move it around over the window to clear any hover tooltip if it stays around)
3. Click outside the window to close it
4. Icon stays

**Comment by mrsimzz** [comment]
Observed the same

**Comment by skhaz** [comment]
I have the same issue.

**Comment by p0deje** [comment]
I've just installed the Sequoia Developer Beta 2 and I cannot reproduce the problem by following your steps. Can you please see if Beta 2 fixed this?

https://github.com/p0deje/Maccy/assets/665846/ff823730-5ab0-495b-9a54-f4187eca415f

**Comment by skhaz** [comment]
I believe it is intermittent; for example, right now it is working fine.

**Comment by p0deje** [comment]
@skhaz If you can provide for details on how to reliably reproduce the problem, it would help a lot.

**Comment by skhaz** [comment]
Sure, I will keep an eye out for it.

**Comment by meadowsys** [comment]
well, it's been very consistent for me, hmm... that's, kinda annoying

**Comment by meadowsys** [comment]
I setup a second monitor today, and this does not happen on that monitor, while consistently happening on my builtin laptop monitor... I suspect it has to do with the MacBooks with notches in the screen, perhaps? (this Mac is MacBook Pro 16", M1 Pro, 2021, if that helps)

**Comment by niknas** [comment]
MacOS 15 beta 3, same issue with icon disappearing from menu bar, still leaving the space and still running.

**Comment by p0deje** [comment]
Does anyone care to test the recent 2.0 beta and see if it helps? https://github.com/p0deje/Maccy/discussions/818

**Comment by skhaz** [comment]
Will the beta be available on Homebrew?

**Comment by p0deje** [comment]
> Will the beta be available on Homebrew?

No, only the final release.

**Comment by meadowsys** [comment]
> Does anyone care to test the recent 2.0 beta and see if it helps? #818

it does seem to fix it!

**Comment by redneckeyeball** [comment]
MacMini M2, latest Beta 3
Problem is still present :( 
I've also filed it as a bug report with Apple

**Comment by p0deje** [comment]
Can you try checking latest Maccy 2.0 beta?On Sep 5, 2024, at 14:09, redneckeyeball ***@***.***> wrote:﻿
MacMini M2, latest Beta 3
Problem is still present :(
I've also filed it as a bug report with Apple

**Comment by redneckeyeball** [comment]
Running RC and latest beta of Maccy
So far so good :)

**Comment by p0deje** [comment]
Alright, let's see if 2.0 and RC are playing well, please re-open if the issue happens again.

**Comment by ballo** [comment]
Did this problem really get fixed? Maccy used to show on the menu bar the first time I used it, but after a reboot it doesn't show anymore and I know it's running. I tried quitting it and starting it back up manually from the Finder.

Sequoia 15.7.7
