### ISSUE TITLE
Ignore clipboard content from sensitive applications

### ISSUE THREAD

**Issue by jadchaar** [p0deje/Maccy#79]
One feature I miss from Paste is the blacklisting of copied values from secure and sensitive applications like 1Password. Paste detected a copy from 1Password and did not store it in the clipboard manager contents.

**Comment by p0deje** [comment]
It is already done in fa83d5f163592a61c1474b2f10dee4bd356a43d8 and will be availabe in the next release.

**Comment by p0deje** [comment]
Duplicate of #65

**Comment by jadchaar** [comment]
Any ETA on the next release :D? Loving Maccy by the way!
