### ISSUE TITLE
⌘⌫ is captured by search field and does not delete history entry

### ISSUE THREAD

**Issue by fdegiuli** [p0deje/Maccy#793]
### Before Submitting Your Bug Report

- [X] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

0.31.0

### macOS Version

14.5 (23F79)

### Maccy Settings

```Shell
{
    "KeyboardShortcuts_delete" = "{\\"carbonModifiers\\":256,\\"carbonKeyCode\\":51}";
    "KeyboardShortcuts_pin" = "{\\"carbonModifiers\\":256,\\"carbonKeyCode\\":35}";
    "KeyboardShortcuts_popup" = "{\\"carbonModifiers\\":768,\\"carbonKeyCode\\":9}";
    "LaunchAtLogin__hasMigrated" = 1;
    "NSWindow Frame SUUpdateAlert" = "650 492 620 398 0 0 1920 1055 ";
    "NSWindow Frame com.sindresorhus.Settings.FrameAutosaveName" = "739 448 542 436 0 0 1920 1055 ";
    SUAutomaticallyUpdate = 0;
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2024-06-19 00:08:20 +0000";
    SUSendProfileInfo = 0;
    SUUpdateGroupIdentifier = 390072107;
    avoidTakingFocus = 1;
    enabledPasteboardTypes =     (
        "public.utf8-plain-text",
        "public.png",
        "public.tiff",
        "public.html",
        "public.rtf",
        "public.file-url"
    );
    hideFooter = 1;
    hideSearch = 0;
    hideTitle = 1;
    ignoredPasteboardTypes =     (
        "de.petermaurer.TransientPasteboardType",
        "Pasteboard generator type",
        "net.antelle.keeweb",
        "com.agilebits.onepassword",
        "com.typeit4me.clipping"
    );
    menuIcon = scissors;
    migrations =     {
        "2020-04-25-allow-custom-ignored-types" = 1;
        "2020-06-19-use-keyboardshortcuts" = 1;
        "2020-09-01-ignore-keeweb" = 1;
        "2021-02-20-allow-to-customize-supported-types" = 1;
        "2021-06-28-add-title-to-history-item" = 1;
        "2021-10-16-remove-dynamic-pasteboard-types" = 1;
        "2022-08-01-rename-suppress-clear-alert" = 1;
        "2022-11-14-add-html-rtf-to-supported-types" = 1;
        "2023-01-22-add-regexp-search-mode" = 1;
    };
    pasteByDefault = 1;
    popupPosition = center;
    popupScreen = 0;
    previewDelay = 1000;
    removeFormattingByDefault = 1;
    searchMode = fuzzy;
    showRecentCopyInMenuBar = 0;
}
```

### Description

The ⌘⌫ shortcut on my mac performs "delete line until cursor".  I think this is the default behavior of Mac OS.
When trying to delete a history entry using ⌘⌫, this behavior seems to be captured by the search field, and the search field is cleared instead. The history entry remains in the list.

Changing the binding to ⇧⌫ (or anything else, really) fixes the problem.

### Steps to Reproduce

1. Have things in clipboard history
2. Open the history
3. Select an entry
4. Hit Cmd-Backspace
5. See nothing happen
6. Type text, see it populate in the search field
7. Hit Cmd-Backspace again
8. See all text disappear from search field

**Comment by p0deje** [comment]
Maccy is keyboard-driven in the sense that almost everything you press is sent to a search field. I don't think that this is generally an issue as I'd expect ⌘⌫ to remove what I entered in the search field.

I'll see what's the best way to handle this - either forbid using ⌘⌫ for "Delete" command or actually respect it.

**Comment by fdegiuli** [comment]
Ah, I thought that was the default delete command. Maybe I changed it while
I was setting up, and forgot.

**Comment by p0deje** [comment]
The default is ⌥⌫.

**Comment by p0deje** [comment]
Please try upgrading to 2.0 and see if it helps
