### ISSUE TITLE
No such module HotKey

### ISSUE THREAD

**Issue by Trixze** [p0deje/Maccy#8]
Hi

When trying to compile the project I get the compile error "No such module 'HotKey'. I know it's something to do with packages or whatever, but am lost trying to get this to work.

Help!

**Comment by p0deje** [comment]
Have you installed CocoaPods and ran `pod install`?

**Comment by Trixze** [comment]
Hi there

Thanks for your quick response.

No, I know nothing about CocoaPods

I did try setting up Package.swift, I saw a reference to needing to do this, and ran ’swift package update’ - game me a message saying package resolved or similar (can’t remember) but still no HotKey for compilation.

The information I can find on the internet is a little confusing to me.

Regards

Tim

**Comment by p0deje** [comment]
Maccy doesn't use Swift package manager - it uses CocoaPods instead. You can read more about it at https://cocoapods.org.

However, Maccy has all the packages in the repository. Does it still fail if you open using workspace?

```
$ cd Maccy
$ open Maccy.xcworkspace
```

**Comment by Trixze** [comment]
Fantastic.

That worked, after having to remove my Package.swift, thanks.

I had no idea there was a different way of opening an xcproject like that!

I appreciate your time on this.

Best regards

Tim
