### ISSUE TITLE
Popup Position terminal option seems to be ignored

### ISSUE THREAD

**Issue by dep-dt** [p0deje/Maccy#80]
I've tried the following option.

```
defaults write org.p0deje.Maccy popupPosition center # default is cursor
```

The app seems to ignore the change to `center` that I've made.  I've tried only executing this command while the app is not running and restarting the Maccy app to no avail.  The window continues to be placed next to the cursor.

Could be related to @p0deje's [fix here](https://github.com/p0deje/Maccy/commit/4a69b549d584ca17f7dd083fb2741245200b034f).

**Comment by p0deje** [comment]
This has not been released yet as I'm testing some bigger changes locally.
