### ISSUE TITLE
Love to have a Time-based Clear Option

### ISSUE THREAD

**Issue by damengilland** [p0deje/Maccy#805]
### Before Submitting Your Feature Request

- [X] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

I just want items to clear out after a customizable amount of time, say 30 minutes.

I don't often need a permanent clipboard history, I don't really want all the clutter on the list.

### Solution

<img width="644" alt="image" src="https://github.com/p0deje/Maccy/assets/1106778/0b5bab08-9055-4743-b895-62722cc71991">

On this screen, just give an option to automatically delete clips that are older than a customizable amount of time, suggest 30 minutes by default.

**Comment by mvevitsis** [comment]
I want this too, don't understand why it's not an option (for security reasons).

**Comment by p0deje** [comment]
Let's track this in #368
