### ISSUE TITLE
Maccy Free

### ISSUE THREAD

**Issue by hoyame** [p0deje/Maccy#807]
### Before Submitting Your Bug Report

- [ ] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [ ] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Settings

```Shell
Sur ton site, tu a le choix entre l'app store et un autre lien, tu peux choisir le montant, si on met 0 on obtient gratuitement l'application.
```

**Comment by p0deje** [comment]
That's correct, one can install Maccy for free.
