### ISSUE TITLE
Cannot install Maccy

### ISSUE THREAD

**Issue by mall3i** [p0deje/Maccy#81]
I'm trying to install Maccy but cannot install the package downloaded from the website as it throws a "Can't be opened" error for the unzipped .app .
Using brew cask produces an MD5 checksum error.

**Comment by p0deje** [comment]
"Can't be opened" can be worked around - see https://github.com/p0deje/Maccy/issues/52#issuecomment-571571446

Not sure about MD5 checksum error in homebrew, maybe that's a bug in the cask.
