### ISSUE TITLE
Enhancing Efficiency with Predefined Shortcut Functionality​

### ISSUE THREAD

**Issue by ivishalanand** [p0deje/Maccy#815]
### Before Submitting Your Feature Request

- [x] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [ ] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

Users often need to repeatedly type the same text snippets, whether it’s common responses, code snippets, LLM prompts, or text templates. This repetition is time-consuming and can lead to inconsistencies.

#### Solution:

**Predefined Shortcut Functionality**

1. **Shortcut Creation and Management:**
   - **Save Text with Shortcut:** Users can save selected text to a predefined shortcut by right-clicking and selecting an option such as “Save to Shortcut” or using a specific keyboard command (e.g., Command + Shift + S).
   - **Shortcut Assignment:** After saving the text, users will be prompted to assign a unique keyboard shortcut (e.g., Command + Option + 1).
   - **Shortcut List Management:** A dedicated section in the Maccy preferences will allow users to manage these shortcuts. They can view, edit, and delete saved shortcuts and their associated texts.
   - **Shortcut Activation:** When users press the assigned shortcut (e.g., Command + Option + 1), Maccy will paste the associated text snippet into the current cursor location in the active application.

2. **Use Cases:**
   - **Saving LLM Prompts:**  Users working with large language models can save frequently used prompts as shortcuts for quick access.
   - **Frequent Responses:** Customer service representatives can save common responses as shortcuts, enabling quick and consistent replies.
   - **Code Snippets:** Developers can save specific code snippets as shortcuts, improving coding efficiency.
   - **Text Templates:** Content creators can save recurring text templates as shortcuts, streamlining the content creation process.

**Comment by p0deje** [comment]
I feel like this has been asked for multiple times and always boils down to 2 responses:

1. You can already do that by creating custom workflows in Shortcuts.app with or without Maccy.
2. This functionality fits more into snipper manager applications, not clipboard.
