### ISSUE TITLE
Not a bug, but a qi

### ISSUE THREAD

**Issue by freebrowser1** [p0deje/Maccy#817]
### Before Submitting Your Bug Report

- [x] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [x] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

1.00

### macOS Version

14.5

### Description
To save my snippets I want to edit the 'Pins' and store my snippets there without manually copying and pasting each of the 20 lines.
Where can I find the file / database / etc where it is stored ?

**Comment by p0deje** [comment]
It's in `~/Library/Containers/org.p0deje.Maccy/Data/Library/Application\ Support/Maccy/Storage.sqlite`
