### ISSUE TITLE
Maccy starts when double clicking or copying

### ISSUE THREAD

**Issue by UbeCc** [p0deje/Maccy#820]
### Before Submitting Your Bug Report

- [X] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

0.31.0

### macOS Version

14.5 (23F79)

### Maccy Settings

```Shell
{
    "KeyboardShortcuts_delete" = "{\\"carbonModifiers\\":2048,\\"carbonKeyCode\\":51}";
    "KeyboardShortcuts_pin" = "{\\"carbonKeyCode\\":35,\\"carbonModifiers\\":2048}";
    "KeyboardShortcuts_popup" = "{\\"carbonKeyCode\\":8,\\"carbonModifiers\\":256}";
    "LaunchAtLogin__hasMigrated" = 1;
    "NSStatusItem Visible Item-0" = 0;
    "NSWindow Frame com.sindresorhus.Settings.FrameAutosaveName" = "295 1761 442 321 -698 900 2560 1415 ";
    SUAutomaticallyUpdate = 0;
    SUEnableAutomaticChecks = 0;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2024-07-26 03:02:29 +0000";
    SUSendProfileInfo = 0;
    enabledPasteboardTypes =     (
        "public.rtf",
        "public.html",
        "public.utf8-plain-text",
        "public.tiff",
        "public.file-url",
        "public.png"
    );
    ignoredPasteboardTypes =     (
        "Pasteboard generator type",
        "net.antelle.keeweb",
        "com.agilebits.onepassword",
        "com.typeit4me.clipping",
        "de.petermaurer.TransientPasteboardType"
    );
    migrations =     {
        "2020-04-25-allow-custom-ignored-types" = 1;
        "2020-06-19-use-keyboardshortcuts" = 1;
        "2020-09-01-ignore-keeweb" = 1;
        "2021-02-20-allow-to-customize-supported-types" = 1;
        "2021-06-28-add-title-to-history-item" = 1;
        "2021-10-16-remove-dynamic-pasteboard-types" = 1;
        "2022-08-01-rename-suppress-clear-alert" = 1;
        "2022-11-14-add-html-rtf-to-supported-types" = 1;
        "2023-01-22-add-regexp-search-mode" = 1;
    };
    searchMode = mixed;
    showInStatusBar = 0;
    suppressClearAlert = 1;
}
```

### Description

Firstly, thanks for maintaining such an awesome and useful tool for us.
However, as I'm new to maccy, I have some confusion about default actions.
Now, when I copy something or do double clicking, maccy will automatically pop up, and may block my work.
So I wonder if there is a way to disable these features so that I can only call maccy by `command+shift+c`?

### Steps to Reproduce

Click twick in a row or copy things

**Comment by p0deje** [comment]
That should never happen, can you please record a video how double-clicking something opens Maccy window?

**Comment by UbeCc** [comment]
Sure! Here is the video and I changed the hotkey to `command+C`
https://github.com/user-attachments/assets/357e5029-afcd-4b3e-9853-354c0ce0058f

**Comment by UbeCc** [comment]
It's strange that when I change the hot key not to be `command+C`, I notice that `maccy` works well. And it won't open when clicking twice. So maybe `command+C` will trigget something in macOS?

**Comment by UbeCc** [comment]
Nevertheless, thanks for your help and contribution to `maccy`!

**Comment by p0deje** [comment]
> command+C

This is the default shortcut for copying in macOS - you should not be able to use it normally.
<img width="622" alt="Screenshot 2024-07-26 at 07 14 06" src="https://github.com/user-attachments/assets/d1b02c9f-18cc-4cf1-a1ac-92bd003db111">
