### ISSUE TITLE
[v2] Popover position is not start-aligned according to the pointer coordinate

### ISSUE THREAD

**Issue by alvin96** [p0deje/Maccy#821]
### Before Submitting Your Bug Report

- [X] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

2.0.0.beta.4 (34)

### macOS Version

Sonoma 14.5

### Description

I've been using Maccy since version 0.x, and I've noticed an issue with the popover position in version 2.0.0. In version 1.x, the popover appeared next to my cursor, allowing me to easily select my most recent copy (e.g., 4..S) without moving my cursor too far. However, in version 2.0.0, the popover is center-aligned, requiring me to move my cursor up to the top to select my most recent copy. Please see the attached screenshot for reference.

v1.0.0
![image](https://github.com/user-attachments/assets/c1cabba4-3c75-45d7-8a58-566a1aec8fd2)

v2.0.0
![image](https://github.com/user-attachments/assets/3544a033-093f-4612-9166-2a16abc033be)

**Comment by alvin96** [comment]
> @alvin96 I don't quite follow what is the difference, can you please record the a video showing the issue?

Apologies for any confusion. I've added comments (in yellow text) to the attachment to show the distance between the pointer and the content I want to copy. I prefer the popover header (the section with the search bar) to appear right next to my pointer, rather than center-aligned, so I can quickly navigate to my most recent copy.
v1.0.0
![352977019-c1cabba4-3c75-45d7-8a58-566a1aec8fd2](https://github.com/user-attachments/assets/2692c5ca-0cc4-43bc-b26b-47c3f37e3e1f)

v2.0.0
![352977882-3544a033-093f-4612-9166-2a16abc033be](https://github.com/user-attachments/assets/ba388fef-afbe-4325-bf5b-976556e1dded)

**Comment by p0deje** [comment]
I see, it's likely because the popup window hits the bottom screen border and moves up to make sure it can show all its content. Can you show a full page screenshot of both 1.0 and 2.0 to compare?

One possible workaround would be for you to resize Maccy window so its height is smaller and less likely to hit the bottom screen border/

**Comment by alvin96** [comment]
> I see, it's likely because the popup window hits the bottom screen border and moves up to make sure it can show all its content.

Yes, but I prefer the v1.0.0 behaviour, which shows the latest and pinned content next to my pointer and resizes the Maccy window to a smaller height, making older content scrollable. In v2.0.0, all content is shown, but I usually only need the top 5–10 items for daily use while keeping older content. Some users may prefer the v2 full content view, so it would be great if Maccy could offer an option for this in the settings.

Here are the screenshots for both 1.0 and 2.0
v1.0.0
![v1](https://github.com/user-attachments/assets/6c4441ea-4204-44ad-843d-a1b7ed86222c)

v2.0.0
![v2](https://github.com/user-attachments/assets/d939cf49-a113-4f26-bc86-25d19ffb7d19)

**Comment by p0deje** [comment]
> but I usually only need the top 5–10 items for daily use while keeping older content

What if you resize the Maccy window so that it shows 5-10 items at most? It will persist the window size on every new open.

**Comment by alvin96** [comment]
> > but I usually only need the top 5–10 items for daily use while keeping older content
> 
> What if you resize the Maccy window so that it shows 5-10 items at most? It will persist the window size on every new open.

It works like a charm, thanks for the advice
