### ISSUE TITLE
[v2] Text is not saved if file saving is disabled

### ISSUE THREAD

**Issue by weisJ** [p0deje/Maccy#824]
https://github.com/p0deje/Maccy/blob/8a136e9cdc9d392f8436bcbb8f87780575399d88/Maccy/Settings/StorageSettingsPane.swift#L36

I also think that at least text storage should be enabled by default (maybe this is the case and I just got confused by not working if file storage is disabled)

**Comment by p0deje** [comment]
Thanks, it's a copy-paste issue. Fixed https://github.com/p0deje/Maccy/commit/ca06ce38f8f6e46e92464f4fd5d21712d28e26c6
