### ISSUE TITLE
When iterm is the active application, Maccy window disappears immediately when using the "Open" keybinding

### ISSUE THREAD

**Issue by brettwilliams** [p0deje/Maccy#828]
### Before Submitting Your Bug Report

- [X] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

1.0.0

### macOS Version

14.5

### Maccy Settings

```Shell
{
    "KeyboardShortcuts_delete" = "{\\"carbonKeyCode\\":51,\\"carbonModifiers\\":2048}";
    "KeyboardShortcuts_pin" = "{\\"carbonKeyCode\\":35,\\"carbonModifiers\\":2048}";
    "KeyboardShortcuts_popup" = "{\\"carbonModifiers\\":768,\\"carbonKeyCode\\":8}";
    "LaunchAtLogin__hasMigrated" = 1;
    "NSWindow Frame com.sindresorhus.Preferences.FrameAutosaveName" = "1329 449 542 462 0 0 3200 1308 ";
    "NSWindow Frame com.sindresorhus.Settings.FrameAutosaveName" = "1649 866 542 437 0 0 3840 1575 ";
    SUAutomaticallyUpdate = 0;
    SUEnableAutomaticChecks = 0;
    SUHasLaunchedBefore = 1;
    SUSendProfileInfo = 0;
    enabledPasteboardTypes =     (
        "public.rtf",
        "public.utf8-plain-text",
        "public.html"
    );
    history = {length = 42, bytes = 0x62706c69 73743030 a0080000 00000000 ... 00000000 00000009 };
    ignoredPasteboardTypes =     (
        "net.antelle.keeweb",
        "Pasteboard generator type",
        "com.agilebits.onepassword",
        "com.typeit4me.clipping",
        "de.petermaurer.TransientPasteboardType"
    );
    migrations =     {
        "2020-02-22-history-item-add-copied-at" = 1;
        "2020-02-22-history-item-add-number-of-copies" = 1;
        "2020-04-18-switch-storage-to-core-data" = 1;
        "2020-04-25-allow-custom-ignored-types" = 1;
        "2020-06-19-use-keyboardshortcuts" = 1;
        "2020-09-01-ignore-keeweb" = 1;
        "2021-02-20-allow-to-customize-supported-types" = 1;
        "2021-06-28-add-title-to-history-item" = 1;
        "2021-10-16-remove-dynamic-pasteboard-types" = 1;
        "2022-08-01-rename-suppress-clear-alert" = 1;
        "2022-11-14-add-html-rtf-to-supported-types" = 1;
        "2023-01-22-add-regexp-search-mode" = 1;
    };
    pinTo = bottom;
    popupPosition = statusItem;
    removeFormattingByDefault = 1;
    searchMode = fuzzy;
}
```

### Description

Maccy drop down disappears immediately if iterm is the active application when hitting the keybinding to pop it up.

It works correctly if you click the icon in the menu bar, just not with the "Open" keybinding.

This started happening a few months ago when I updated (I am not sure which version I had before).

### Steps to Reproduce

1.  Run iterm, and have it be the active application
2.  Press keybinding for Open

**Comment by p0deje** [comment]
I use Maccy and iTerm 2 all the time and this problem doesn't appear. The only case when it happens is when iTerm asks for a password, see #473 for workaround and fix.

**Comment by brettwilliams** [comment]
I have uploaded a video showing the issue.  It occurs 100% of the time for me without any involvement with a password.

https://github.com/user-attachments/assets/62b1b764-0d35-467c-9f65-655bef0be8ed

**Comment by brettwilliams** [comment]
I turned off secure keyboard entry on iterm2 (which was somehow on) and the issue is resolved.  I was not trying to do anything with a password, but it must have been related.

**Comment by p0deje** [comment]
\
