### ISSUE TITLE
Screenshot to clipboard does not insert the screenshot to history

### ISSUE THREAD

**Issue by Defman21** [p0deje/Maccy#83]
Making a screenshot that saves itself to the clipboard (Control+Shift+Command+4) does not create a history item in Maccy. It works in Clipy, though.

Maccy 0.9.0, installed via brew.

**Comment by FernandoMiguel** [comment]
this would be super useful

**Comment by alexjousse** [comment]
Hi, I have been experiencing the same and I am wondering if it's not related to [this commit](https://github.com/p0deje/Maccy/commit/fa83d5f163592a61c1474b2f10dee4bd356a43d8#diff-1d4cb04579a84067684ff2bfe19b2a60R15-R16) about discarding some NSPasteboard types...

**Comment by Defman21** [comment]
I guess it is.

>org.nspasteboard.AutoGeneratedType: This marker’s presence indicates content was generated by an application; the user had no intention to Copy this content and may not expect to find it on the pasteboard. (This marker is often found with a TransientType marker as well.) Data marked this way probably should not be recorded as part of the pasteboard history, **but (if not also marked transient) might need to be displayed as the “current” pasteboard content.**

**Comment by Defman21** [comment]
It's not. Maccy does not support `PasteboardType.png` for some reason. I'm going to provide a pull request to support it.

**Comment by jadchaar** [comment]
I am unable to access images I copied from my desktop, and I am guessing this is the same issue.

@Defman21 will this fix patch all image types (e.g. JPG)? I feel like patching individual file types can be unmaintainable in the long run.

**Comment by Defman21** [comment]
It wont. Copying files from your desktop is `PasteboardType.file-url`. And there`s no `PasteboardType.jpg`.

**Comment by p0deje** [comment]
I've tried using #84 locally but I still do not see the copied image. It looks like the screenshot done via CMD+SHIFT+4 is not added to the clipboard at all regardless of Maccy. How can I reliably reproduce this?

**Comment by georgesnow** [comment]
I think you need to add control to keyboard shortcut to copy a screenshot to the clipboard

**Comment by Defman21** [comment]
Yes, without Control it copies the screenshot to your desktop.

**Comment by alapolloni** [comment]
Press **Shift-Command 5** and the **Screenshot** floating menu pops up.  Use option to select where you want screenshots to be saved to.  There's a further option for _Remember Last Selection_    **Shift-Command-3** and **Shift-Command-4** will then save the screen shots to where ever you set that option.  After a new install of MacOS the default is your desktop.

**Comment by p0deje** [comment]
Implemented via 6a2b6aa
