### ISSUE TITLE
Normalize text on paste!

### ISSUE THREAD

**Issue by BoKKeR** [p0deje/Maccy#836]
### Before Submitting Your Feature Request

- [X] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

Many times when I copy text from sites the formatting follows from the site. This can be annoying when pasting into teams or sheets. Suddenly the color, font size are all pasted. While I only wanted text. I almost never want the text format pasted.

### Solution

Could Maccy normalize all text that is copied. As in remove the font and text size. Is this even possible? I am not sure how the information is stored.

**Comment by p0deje** [comment]
You can remove the formatting before pasting. See "General" settings in Maccy for guidance how to configure it and what shortcuts to use.
