### ISSUE TITLE
Paste stopped working

### ISSUE THREAD

**Issue by dwt** [p0deje/Maccy#843]
### Before Submitting Your Bug Report

- [X] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

1.0.0 (31)

### macOS Version

10.16

### Maccy Settings

```Shell
{
    "KeyboardShortcuts_delete" = "{\\"carbonKeyCode\\":51,\\"carbonModifiers\\":2048}";
    "KeyboardShortcuts_pin" = "{\\"carbonKeyCode\\":35,\\"carbonModifiers\\":2048}";
    "KeyboardShortcuts_popup" = "{\\"carbonModifiers\\":768,\\"carbonKeyCode\\":9}";
    "LaunchAtLogin__hasMigrated" = 1;
    NSNavPanelExpandedSizeForOpenMode = "{800, 448}";
    "NSStatusItem Preferred Position Item-0" = 407;
    "NSWindow Frame NSNavPanelAutosaveName" = "356 372 800 448 0 0 1512 944 ";
    "NSWindow Frame SUStatusFrame" = "556 607 400 134 0 0 1512 944 ";
    "NSWindow Frame SUUpdateAlert" = "437 409 638 398 0 0 1512 944 ";
    "NSWindow Frame com.sindresorhus.Settings.FrameAutosaveName" = "950 351 547 452 0 0 1512 944 ";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2024-08-16 07:19:21 +0000";
    SUUpdateGroupIdentifier = 1002684822;
    WebKitDefaultFontSize = 13;
    WebKitJavaScriptEnabled = 0;
    WebKitPluginsEnabled = 0;
    WebKitStandardFont = "-apple-system-font";
    WebKitUserStyleSheetEnabledPreferenceKey = 1;
    WebKitUserStyleSheetLocationPreferenceKey = "/Users/dwt/Applications/Utilities/Interface Enhancements/Maccy.app/Contents/Frameworks/Sparkle.framework/Resources/ReleaseNotesColorStyle.css";
    avoidTakingFocus = 0;
    enabledPasteboardTypes =     (
        "public.png",
        "public.rtf",
        "public.file-url",
        "public.utf8-plain-text",
        "public.tiff",
        "public.html"
    );
    ignoreEvents = 0;
    ignoredApps =     (
        "com.apple.keychainaccess"
    );
    ignoredPasteboardTypes =     (
        "org.nspasteboard.AutoGeneratedType",
        "Pasteboard generator type",
        "org.nspasteboardConcealedType",
        "org.nspasteboard.TransientType",
        "de.petermaurer.TransientPasteboardType",
        "net.antelle.keeweb",
        "com.typeit4me.clipping",
        "com.agilebits.onepassword"
    );
    menuIcon = clipboard;
    migrations =     {
        "2020-04-25-allow-custom-ignored-types" = 1;
        "2020-06-19-use-keyboardshortcuts" = 1;
        "2020-09-01-ignore-keeweb" = 1;
        "2021-02-20-allow-to-customize-supported-types" = 1;
        "2021-06-28-add-title-to-history-item" = 1;
        "2021-10-16-remove-dynamic-pasteboard-types" = 1;
        "2022-08-01-rename-suppress-clear-alert" = 1;
        "2022-11-14-add-html-rtf-to-supported-types" = 1;
        "2023-01-22-add-regexp-search-mode" = 1;
    };
    pasteByDefault = 1;
    searchMode = fuzzy;
    showRecentCopyInMenuBar = 0;
}
```

### Description

Since the last update Maccy has stopped pasting when clicking an entry in the history of pasteboards, or choosing an entry in there with the keyboard.

Things I have checked:
* Paste Automatically is enabled 
<img width="297" alt="image" src="https://github.com/user-attachments/assets/4d958ee8-2899-411a-ac9e-8247d9da519d">

* Prevent Focus Steal is disabled 
<img width="339" alt="image" src="https://github.com/user-attachments/assets/c93b8aa1-1efa-419e-ba5a-031460f7d15e">

* System Preferences > Privacy > Assistive is enabled: 
<img width="554" alt="image" src="https://github.com/user-attachments/assets/405413ba-a1a4-448f-aa82-8d2ee467b8b4">

Not quite sure how I bungled this, but tinkering with the various settings doesn't seem to help. :-(

### Steps to Reproduce

1. Open Maccy via shortcut or menu bar
2. Choose entry to paste via keyboard or mouse
3. nothing…

**Comment by dwt** [comment]
Restart also didn't help.

**Comment by smao-astro** [comment]
Vote for same issue. Please look into it. Thanks.

**Comment by lexpoig** [comment]
For me, lack of paste seems to be random. Sometimes it'll work, sometimes it won't.

**Comment by HerrYu123** [comment]
Vote for same issue. First time to use Maccy

**Comment by dwt** [comment]
Workaround: Paste in Maccy, then paste again with <cmd-v>. So it seems Maccy is writing to the system clipboard, but is unable to trigger the actual paste action into the Application.

**Comment by dwt** [comment]
I think I found the workaround: Removing and then re-adding Maccy in System Preferences > Privacy > Assistive Devices (not quite sure what this is called in English) 
<img width="928" alt="Bildschirmfoto 2024-09-03 um 08 56 58" src="https://github.com/user-attachments/assets/73c38091-21d8-4847-9525-5767c5cd9c2b">

In Actions:
1. Select Maccy
2. Remove it from the List with the Minus-Action
3. Select the Plus Action to re-Add it (and select it in the file chooser that opens)
4. Check that permissions are re-enabled.

This allowed Maccy to paste again for me.

@p0deje So it seems that the system somehow garbled the permissions for Maccy. Sadly now I cannot really give you a dump of them as they are now fixed for me, but perhaps one of the other persons here that shares the problem can help you? That could allow creating a detector to find such broken permissions.

At the least, I would like to add this knowledge to the FAQ, so that if everything else seems to be correct this can be another 'try this' step.

What do you think?

**Comment by p0deje** [comment]
Please try upgrading to 2.0 and see if it helps
