### ISSUE TITLE
Support showing stored items stats

### ISSUE THREAD

**Issue by 750** [p0deje/Maccy#844]
### Before Submitting Your Feature Request

- [X] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

(tried searching issues and looking though the app, didn't find this feature)

Basically I want to see what's in my Maccy storage: how many copies, their size distribution and so on.

Apart from this data being just fun it's also useful to estimate performance (if I have many big copies, search works slower)

### Solution

Stats could be shown in settings -> storage

<img width="559" alt="Screenshot 2024-08-20 at 23 31 00" src="https://github.com/user-attachments/assets/7ef6afcd-030f-4544-afa9-4c0e14ab29f7">

**Comment by p0deje** [comment]
Some information is already show in a preview popup (number of copies, timestamps, etc)

**Comment by fengmikaelson** [comment]
> Some information is already show in a preview popup (number of copies, timestamps, etc)

is there a limit of the max size count ?when i input 2000,and click the button up to 2001,it become 201;it seems like there is a bug in here

**Comment by p0deje** [comment]
Can you add a screenshot to understand better?On Sep 22, 2024, at 18:34, fengmikaelson ***@***.***> wrote:﻿

Some information is already show in a preview popup (number of copies, timestamps, etc)

is there a limit of the max size count ?when i input 2000,and click the button up to 2001,it become 201;it seems like there is a bug in here

**Comment by fengmikaelson** [comment]
> Can you add a screenshot to understand better?On Sep 22, 2024, at 18:34, fengmikaelson ***@***.***> wrote:﻿ Some information is already show in a preview popup (number of copies, timestamps, etc) is there a limit of the max size count ?when i input 2000,and click the button up to 2001,it become 201;it seems like there is a bug in here —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

could u see this video?
https://github.com/user-attachments/assets/90912207-60a9-4650-9565-8d58beb05409

**Comment by fengmikaelson** [comment]
> Can you add a screenshot to understand better?On Sep 22, 2024, at 18:34, fengmikaelson ***@***.***> wrote:﻿ Some information is already show in a preview popup (number of copies, timestamps, etc) is there a limit of the max size count ?when i input 2000,and click the button up to 2001,it become 201;it seems like there is a bug in here —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

could u see this video?

https://github.com/user-attachments/assets/73b79cfa-7e5f-45e0-a829-71d26385107f

**Comment by fengmikaelson** [comment]
> Can you add a screenshot to understand better?On Sep 22, 2024, at 18:34, fengmikaelson ***@***.***> wrote:﻿ Some information is already show in a preview popup (number of copies, timestamps, etc) is there a limit of the max size count ?when i input 2000,and click the button up to 2001,it become 201;it seems like there is a bug in here —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

and there is another bug i found ....
i enter 1000 and click up botton, it return to 100,but when i enter 999,and click up botton,it can be add to 1000 and more and won't be reset to 100

https://github.com/user-attachments/assets/311474c9-44a1-4c45-be02-5c782fd2c88a

**Comment by p0deje** [comment]
@fengmikaelson The current limit is 999 items.

**Comment by fengmikaelson** [comment]
> > Can you add a screenshot to understand better?On Sep 22, 2024, at 18:34, fengmikaelson _**@**_._**> wrote:﻿ Some information is already show in a preview popup (number of copies, timestamps, etc) is there a limit of the max size count ?when i input 2000,and click the button up to 2001,it become 201;it seems like there is a bug in here —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: _**@**_.**_>
> 
> and there is another bug i found .... i enter 1000 and click up botton, it return to 100,but when i enter 999,and click up botton,it can be add to 1000 and more and won't be reset to 100
> 
>  2024-09-28.21.35.57.mp4

@p0deje but this video,the limit can up to 1000+ and more,so is it fake? in fact ,limit is always 999?

**Comment by p0deje** [comment]
Yes, limit is 999 max. On Oct 5, 2024, at 06:05, fengmikaelson ***@***.***> wrote:﻿


Can you add a screenshot to understand better?On Sep 22, 2024, at 18:34, fengmikaelson @.> wrote:﻿ Some information is already show in a preview popup (number of copies, timestamps, etc) is there a limit of the max size count ?when i input 2000,and click the button up to 2001,it become 201;it seems like there is a bug in here —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: _@**.**_>

and there is another bug i found .... i enter 1000 and click up botton, it return to 100,but when i enter 999,and click up botton,it can be add to 1000 and more and won't be reset to 100
2024-09-28.21.35.57.mp4

@p0deje but this video,the limit can up to 1000+ and more,so is it fake? in fact ,limit is always 999?
