### ISSUE TITLE
[Feature request] Support copying files

### ISSUE THREAD

**Issue by jadchaar** [p0deje/Maccy#85]
The recent feature addition for images in https://github.com/p0deje/Maccy/issues/44 is great, but I would also like to request support for accessing copied files like PDFs and such from the clipboard history.

**Comment by Defman21** [comment]
Note that some images copied from your computer (e.g. from the Desktop folder or "Copy Media" in Telegram which copies a cached version of the media under the hood) falls into `NSPasteboard.PasteboardType.fileURL` as well.

I'd go with storing file paths in `HistoryItem`'s for anything but images (so it would look like `/Users/user/some_file.pdf` with maybe an icon to let the user know it's a file, not a string. For images, I'd still store the file path but display the actual image itself (`NSImage` can create images from fire URLs).

**Comment by p0deje** [comment]
Implemented via 6a2b6aa.

The solution will work like this:

1. Copied file is shown on the list like filename.
2. When you copy it, it will be pasted as a file when possible.
