### ISSUE TITLE
Integration w/ Clop (Clipboard Optimizer)

### ISSUE THREAD

**Issue by sanitybit** [p0deje/Maccy#851]
### Before Submitting Your Feature Request

- [X] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

I've been a longtime user and big fan of Maccy. Recently, I learned about [Clop](https://github.com/FuzzyIdeas/Clop), which is a tool that will automatically optimize screenshots as soon as they are detected in the clipboard. This usually reduces the screenshot file size by 2/3rd when I paste it into Slack or other sharing tools that send the file without modification.

For example, this screenshot is 1.8mb, but Clop auto-optimized it in my clipboard to 496kb without being written to disk.

![image](https://github.com/user-attachments/assets/59bf82d6-8167-439b-b925-7952b4c6486c)

So far, pretty excellent.

The only downside, and one I haven't found a good workaround for, is that this results in two history items for every copied screenshot, the original copy, and the optimized copy.

![image](https://github.com/user-attachments/assets/393cce7d-f1a9-4774-812d-7d212d9ca977)

I've tried adding Clop to the ignore list to see if Maccy won't track the optimized image but still let me paste it, but that doesn't seem to work, and there isn't a specific pasteboard type I can use to ignore it either. 

Pasteboard Viewer tells me the source of the optimized image is Clop, but Maccy still seems to think the optimized screenshot came from the source of the unoptimized screenshot (e.g. Firefox).

If there is a change the Clop application can make that could help this work, let me know, and I'll submit a feature request over there.

### Solution

When a screenshot or image is copied to the clipboard, and then optimized with Clop, prevent the unoptimized version from being stored in the Maccy history.

**Comment by p0deje** [comment]
One thing you could do is to add `clop.optimisation.status` to ignore pasteboard types. This will keep only the original image in the history of Maccy.

Ideally, Clop would provide a way to identify which copied image it changed so Maccy would then replace and original copy with a new one. This is for example how Pure Paste works, see  https://github.com/p0deje/Maccy/issues/429#issuecomment-1182575226 for more details. If Clop would provide this extra information. I can add support for it in Maccy.

**Comment by sanitybit** [comment]
> I did try using `clop.optimisation.status` in the ignored pasteboard types, but that didn't work. Forgot to mention that in my original post since I assumed that just wasn't something that was supported.

Ignoring `public.png` worked, but that also ignores the original screenshot as well. 

In case the above is a bug, I was testing with Maccy `1.0.0`.

I will reach out to the clop devs with the information on Pure Paste's implementation, as I also have some bugs to file with them. Thank you!

**Comment by p0deje** [comment]
I just tested adding the pasteboard type and it worked perfectly fine. I'm running Maccy 2.0 beta there are no changes related to pasteboard types handing in 2.x.
<img width="644" alt="Screenshot 2024-08-24 at 10 00 31" src="https://github.com/user-attachments/assets/9a4a30c4-dd7d-44f3-86c2-b829729d1b08">

**Comment by sanitybit** [comment]
Oh wow, late night PEBCAK. I entered it with a z instead of an s. 😭
