### ISSUE TITLE
Pin dot not showing

### ISSUE THREAD

**Issue by brettgil** [p0deje/Maccy#853]
### Before Submitting Your Bug Report

- [ ] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [ ] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

2.0.0 Beta 13

### macOS Version

14.6.1

### Maccy Settings

```Shell
"KeyboardShortcuts_delete" = "{\\"carbonModifiers\\":2048,\\"carbonKeyCode\\":51}";
    "KeyboardShortcuts_pin" = "{\\"carbonModifiers\\":2048,\\"carbonKeyCode\\":35}";
    "KeyboardShortcuts_popup" = "{\\"carbonKeyCode\\":9,\\"carbonModifiers\\":768}";
    "LaunchAtLogin__hasMigrated" = 1;
    "NSStatusItem Visible Item-1" = 0;
    "NSWindow Frame com.sindresorhus.Settings.FrameAutosaveName" = "2472 607 482 329 1728 37 1920 1055 ";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2024-08-26 16:28:11 +0000";
    SUUpdateGroupIdentifier = 2203824792;
    avoidTakingFocus = 1;
    enabledPasteboardTypes =     (
        "public.rtf",
        "public.utf8-plain-text",
        "public.html"
    );
    ignoredPasteboardTypes =     (
        "Pasteboard generator type",
        "com.typeit4me.clipping",
        "net.antelle.keeweb",
        "de.petermaurer.TransientPasteboardType",
        "com.agilebits.onepassword"
    );
    migrations =     {
        "2024-07-01-version-2" = 1;
    };
    pasteByDefault = 1;
    showFooter = 1;
    showSearch = 1;
    showTitle = 1;
    windowSize = "[450,800]";
```

### Description

I have 3 pinned items - in V1, the Pinned items had a dot to the left (denoting they were pinned) There is no dot next to them at this time. 
<img width="73" alt="Screenshot 2024-08-26 at 2 19 48 PM" src="https://github.com/user-attachments/assets/411ece51-89ae-4848-8de7-f9ee31214432">
The first 3 are pinned. 

### Steps to Reproduce

Open the history list > no dot.

**Comment by p0deje** [comment]
Yeah, v2 doesn't show dots, instead, it keeps them outside of the scroll view and never hidden.
