### ISSUE TITLE
Panel clipboard view option

### ISSUE THREAD

**Issue by Romachamp** [p0deje/Maccy#856]
### Before Submitting Your Feature Request

- [X] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

Hello! I would like to have an option for opening maccy as the panel at the bottom/top of the screen and see from which apps the items are copied from there. Basically, I want similar functionality to Paste app. 

### Solution

I will provide an attachment below of the view I would like. 

Thank you, in advance!

![IMG_1993](https://github.com/user-attachments/assets/e71587c9-742a-4b07-baa5-4d1c53bc2d16)

**Comment by p0deje** [comment]
Sorry that's not planned for Maccy, you better keep using Paste
