### ISSUE TITLE
do not scroll to select item when use arrow key to change selection.

### ISSUE THREAD

**Issue by jixiangqd** [p0deje/Maccy#859]
### Before Submitting Your Bug Report

- [x] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [x] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

2.0.0.beta.13 (44)

### macOS Version

14.6.1 (23G93)

### Maccy Settings

```Shell
{
    "KeyboardShortcuts_delete" = "{\\"carbonModifiers\\":2048,\\"carbonKeyCode\\":51}";
    "KeyboardShortcuts_pin" = "{\\"carbonModifiers\\":2048,\\"carbonKeyCode\\":35}";
    "KeyboardShortcuts_popup" = "{\\"carbonModifiers\\":768,\\"carbonKeyCode\\":8}";
    "LaunchAtLogin__hasMigrated" = 1;
    "NSStatusItem Preferred Position Item-0" = 5849;
    "NSStatusItem Visible Item-1" = 0;
    "NSWindow Frame com.sindresorhus.Settings.FrameAutosaveName" = "598 511 710 443 0 0 1728 1079 ";
    SUAutomaticallyUpdate = 0;
    SUEnableAutomaticChecks = 0;
    SUHasLaunchedBefore = 1;
    SUSendProfileInfo = 0;
    avoidTakingFocus = 1;
    enabledPasteboardTypes =     (
        "public.utf8-plain-text",
        "public.png",
        "public.file-url",
        "public.tiff",
        "public.rtf",
        "public.html"
    );
    ignoredPasteboardTypes =     (
        "com.typeit4me.clipping",
        "de.petermaurer.TransientPasteboardType",
        "net.antelle.keeweb",
        "com.agilebits.onepassword",
        "Pasteboard generator type"
    );
    maxMenuItemLength = 50;
    menuIcon = clipboard;
    migrations =     {
        "2024-07-01-version-2" = 1;
    };
    pasteByDefault = 1;
    pinTo = top;
    popupPosition = center;
    popupScreen = 0;
    removeFormattingByDefault = 0;
    searchMode = mixed;
    showFooter = 1;
    showRecentCopyInMenuBar = 0;
    showSearch = 1;
    showSpecialSymbols = 1;
    showTitle = 1;
    windowSize = "[450,800]";
}
```

### Description

I usually use short-key cmd+shift+c to pop up maccy, and direct use arrow-key(up/down) to choose which to paste, and then press enter to paste. this works fine on 1.0, but when I upgrade to 2.0, I encounter the bug that I cannot see current selection until the selection under current page of scroll, or I use mouse(pad) to scroll the unpinned items. Pinned items are ok, because there's no scroll on these items.

### Steps to Reproduce

1.copy several items, till the scroll shows.
2.use mouse scroll down.
3.use shortcut popup Maccy.
4.use down arrow key to change selection, and you can find that highlight background are missing until after many times press down arrow key and highlight under current page.

**Comment by p0deje** [comment]
Can you please record a screen video showing the problem?

**Comment by jixiangqd** [comment]
Here's the video(sorry for the poor quality for considering from the perspective of data security)
https://github.com/user-attachments/assets/996dc882-6199-4ed7-bc10-2ab53713332a

this bug only happens on upper-side.

**Comment by p0deje** [comment]
Fixed in beta 14
