### ISSUE TITLE
Bug Report: Maccy Freezes When Copying Large Text Data

### ISSUE THREAD

**Issue by Bistutu** [p0deje/Maccy#861]
### Before Submitting Your Bug Report

- [X] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Description

**Description:**

When copying very large amounts of text data (e.g., over 100MB), Maccy becomes unresponsive and crashes. After this happens, the application cannot be reopened, which prevents users from clearing the clipboard history or accessing the app at all. This significantly impacts usability, especially when handling large data sets or working in environments where large text copies are common.

**Expected Behavior:**

Maccy should handle large clipboard data more gracefully, either by limiting the size of the text that can be copied or by adding an option to set a maximum clipboard size in the application settings. This would prevent the app from freezing or crashing when large data is copied.

**Proposed Solution:**

- Introduce a configurable maximum text size limit for copied data in the application settings. If a user attempts to copy data larger than this limit, Maccy should provide a warning or prevent the copy action.
- Implement error handling and memory management improvements to better manage large clipboard entries without causing the application to crash.

### Steps to Reproduce

**Steps to Reproduce:**

1. Copy a large amount of text data (e.g., a text file over 100MB).  
2. Observe that Maccy freezes and becomes unresponsive.  
3. Attempt to reopen Maccy after the freeze — it fails to open and remains unresponsive.

**Comment by p0deje** [comment]
@Bistutu Thanks for a report:

1. Can you please check the latest 2.0 beta - there were improvements related to memory there. https://github.com/p0deje/Maccy/discussions/818
2. Can you share some text files to tests?

**Comment by Bistutu** [comment]
In fact, I am using version 2.0 beta. The text I mentioned was just something I randomly copied. For example, if you want to increase a 10MB text file to 100MB, you would copy and paste it multiple times. At some point, you might accidentally copy that 100MB text, causing the Maccy application to freeze.

<img width="284" alt="image" src="https://github.com/user-attachments/assets/85b7e6d1-0a09-437a-9882-075c92048a2c">

**Comment by 750** [comment]
@p0deje I think the searchable limit (1_000) is too low, I tried setting it to 100_000 and feeding Maccy about 1 gig of data

<details>
  <summary>this way</summary>
  <p>

```
defaults write org.p0deje.Maccy clipboardCheckInterval 0.1
```

```python
import time
import random
import subprocess 

MLN = 1_000_000
# MLN = 1

copies = sum([[
	chr(i)*MLN*random.randint(1,30)
] for i in range(48,123)], [])

print("items:", len(copies))
print("total size of all items:", int(sum(map(len, copies))/1000000), "megabytes")

for idx, copy in enumerate(copies):
	print(f"{idx+1}/{len(copies)}")
	subprocess.run("pbcopy", text=True, input=copy)
	time.sleep(0.25)

```
  </p>
</details>

And the search was still reasonably fast - took about 1 second (slower than usual but seems to be reasonable).
Same experiment for limit=1_000 makes Maccy as fast as usual
