### ISSUE TITLE
[V2] A way to reduce animation when mousing over clipboard entries

### ISSUE THREAD

**Issue by ilyagr** [p0deje/Maccy#866]
### Before Submitting Your Feature Request

- [X] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

I just tried out Maccy 2.beta.15 after Maccy 1.0, and I found the animations that happen when mousing over clipboard entries annoying (as the full view of that clipboard entry expands). They are especially headache-inducing if you move the mouse up and down and want to see several clipboard entries expanded.

I tried the Mac OS X "reduce motion" option, and while that helped slightly, it was still annoying.

### Solution

Make those animation far less prominent by default and/or have an option to disable them entirely.

I don't remember them being nearly as annoying in 1.0.

Cc: #819, which I think would also be helped by this. You can see the animation I'm talking about in the very beginning of the video at https://github.com/p0deje/Maccy/issues/819#issuecomment-2267491100. However, this request is different; I'd like that animation to just not happen entirely or be far less prominent.

**Comment by p0deje** [comment]
@ilyagr I agree with you and I'd like the animation to be disabled but there is no way to do that using built-in SwiftUI as I described in #819. For now, I'd like to focus on releasing 2.0 and later address this inconvenience  in 2.1 or implement a different approach to previews (such as a detached popover or a sliding out area).

**Comment by ilyagr** [comment]
I see, I missed that sentence in the other bug. Sad, but it makes sense.

**Comment by p0deje** [comment]
Closing in favor of #819
