### ISSUE TITLE
Change shortcut keys

### ISSUE THREAD

**Issue by angoodkind** [p0deje/Maccy#87]
Is it possible to change the keyboard shortcut, so that instead of command + 1, it's something else. The problem is that this keyboard shortcut conflicts with a number of applications. For example, in Chrome, command + 1 switches to the first tab.

**Comment by p0deje** [comment]
When Maccy is open the keyboard shortcut will only be routed to Maccy, not Chrome - there should be no conflict.

**Comment by angoodkind** [comment]
What do you mean by "open"? Does that just mean the icon shows on my menu bar? Or does "open" mean I actually need to click on the icon, which displays the dropdown?

**Comment by georgesnow** [comment]
I believe it means “focus” or active. So if Maccy is open it’s visible and active the keyboard shortcut only gets sent to maccy

**Comment by angoodkind** [comment]
Sorry, I'm not sure which choice you're referring to. It seems that this still necessitates the option to change the shortcut so it can be accessed anywhere.

**Comment by p0deje** [comment]
> Sorry, I'm not sure which choice you're referring to. It seems that this still necessitates the option to change the shortcut so it can be accessed anywhere.

You first need to open the window by clicking on the menubar icon or pressing the popup shortcut (https://github.com/p0deje/Maccy#popup-hotkey).

**Comment by elfensky** [comment]
> I believe it means “focus” or active. So if Maccy is open it’s visible and active the keyboard shortcut only gets sent to maccy

It does not. I am on (10.15.4) Catalina, and I have cmd+1,2,3 set to various screenshot functions. 
When I open Maccy (cmd+shift+c) and try to copy an item using cmd+1 for example, the screenshot triggers instead of Maccy.

**Comment by georgesnow** [comment]
@elfensky  that would be expected behavior. the Cmd+1 is a local event monitor and captures for the app. The screenshot you have is global hotkey binded to the system. Event monitors only "view" they don't interrupt (or prevent) the keys from being passed. That is why you would have it trigger both the screenshot and copying of the related item.
