### ISSUE TITLE
Add groups 

### ISSUE THREAD

**Issue by ShuratCode** [p0deje/Maccy#871]
### Before Submitting Your Feature Request

- [X] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

I want to pin several texts, but each one has a different context.
For example when I fill out a form I have things that I always paste (like email, address, mail etc.)
I want to save these in different groups so I will have context and easier search from them

### Solution

I want to be able to pin a specific text and save it in a group or a directory for my choosing, and then to be able to search that group and be able to copy only the texts in the group.
Same as Ditto for Windows do

**Comment by p0deje** [comment]
@ShuratCode Can you please provide some examples from Ditto, I'm not familiar with it?

**Comment by atmnrv** [comment]
I am not sure about Ditto, but it does sound like how Clipy used to handle pins (or “snippets”). Basically, you could either display the snippets in the main window or, very conveniently, in a separate window through another shortcut (⇧⌘X). In fact, I am still using it for that reason alone.

![687474703a2f2f636c6970792d6170702e636f6d2f696d672f73637265656e73686f74312e706e67](https://github.com/user-attachments/assets/a03b146a-63f2-428b-9b37-84371ec65928)

(But please, let us have the option to align the popup window with the cursor vertically and horizontally, even when the cursor is at the bottom of the screen: the cursor should define the top-left corner of the window, so as to alleviate mouse travel)

Congratulations on releasing version 2.0.0!

**Comment by p0deje** [comment]
@atmnrv Can you share some screenshots?

**Comment by p0deje** [comment]
Let's continue in #307
