### ISSUE TITLE
[V2] ⌥⌘⌫ does not clear copied items when footer is disabled

### ISSUE THREAD

**Issue by frankshrestha** [p0deje/Maccy#875]
### Before Submitting Your Bug Report

- [X] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

2.0.0

### macOS Version

15.0 (24A335)

### Description

⌥⌘⌫ does not clear copied items when footer is disabled.

### Steps to Reproduce

- Copy few item to the clipboard.
- Open Maccy.
- Press ⌥⌘⌫.

**Comment by p0deje** [comment]
Duplicate of #865
