### ISSUE TITLE
It does not automatically paste in Java applications in macos Sequoia

### ISSUE THREAD

**Issue by Maczinger** [p0deje/Maccy#879]
### Before Submitting Your Bug Report

- [X] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

2.0.0

### macOS Version

15.0

### Maccy Settings

```Shell
{
    "KeyboardShortcuts_delete" = "{\\"carbonKeyCode\\":51,\\"carbonModifiers\\":2048}";
    "KeyboardShortcuts_pin" = "{\\"carbonKeyCode\\":35,\\"carbonModifiers\\":2048}";
    "KeyboardShortcuts_popup" = "{\\"carbonModifiers\\":2304,\\"carbonKeyCode\\":9}";
    "LaunchAtLogin__hasMigrated" = 1;
    "NSStatusItem Preferred Position Item-0" = 5553;
    "NSStatusItem Visible Item-1" = 0;
    "NSWindow Frame SUUpdateAlert" = "636 506 647 398 0 0 1920 1055 ";
    "NSWindow Frame com.sindresorhus.Settings.FrameAutosaveName" = "665 478 597 451 0 0 1920 1055 ";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2024-09-18 07:07:33 +0000";
    SUUpdateGroupIdentifier = 2879855366;
    clearOnQuit = 0;
    enabledPasteboardTypes =     (
        "public.rtf",
        "public.tiff",
        "public.html",
        "public.utf8-plain-text",
        "public.png",
        "public.file-url"
    );
    hideFooter = 1;
    hideTitle = 1;
    historySize = 70;
    ignoredPasteboardTypes =     (
        "com.typeit4me.clipping",
        "de.petermaurer.TransientPasteboardType",
        "com.agilebits.onepassword",
        "net.antelle.keeweb",
        "Pasteboard generator type"
    );
    imageMaxHeight = 40;
    menuIcon = paperclip;
    migrations =     {
        "2020-04-25-allow-custom-ignored-types" = 1;
        "2020-06-19-use-keyboardshortcuts" = 1;
        "2020-09-01-ignore-keeweb" = 1;
        "2021-02-20-allow-to-customize-supported-types" = 1;
        "2021-06-28-add-title-to-history-item" = 1;
        "2021-10-16-remove-dynamic-pasteboard-types" = 1;
        "2022-08-01-rename-suppress-clear-alert" = 1;
        "2022-11-14-add-html-rtf-to-supported-types" = 1;
        "2023-01-22-add-regexp-search-mode" = 1;
        "2024-07-01-version-2" = 1;
    };
    pasteByDefault = 1;
    popupPosition = center;
    popupScreen = 0;
    removeFormattingByDefault = 1;
    searchMode = exact;
    showFooter = 1;
    showSearch = 1;
    showTitle = 0;
    windowSize = "[450,800]";
}
```

### Description

When I work in Netbeans, to paste an item from the clipboard I have to do cmd+alt+v, press Enter on the item I want to paste to select it, and then press cmd+v again to paste it.
In version 1, just pressing cmd+alt+v and Enter on the item pastes it.
Of course, Paste Automatically is active in Preferences

**Comment by p0deje** [comment]
Does it work in other apps?

**Comment by Maczinger** [comment]
Yes! In my system, it seems that Apache Netbeans is the only application where it doesn't work well.

**Comment by p0deje** [comment]
@Maczinger 
1. Did it work before upgrading to Sequoia?
2. Did it work on Maccy 1.0?

It looks like an old issue and I've found https://www.alfredforum.com/topic/8731-clipboard-dont-paste-in-netbeans/, but I don't know how Alfred workarounds this problem since it's closed source.

**Comment by sinjab** [comment]
After upgrading to macOS Sequoia, Maccy does not anymore automatically paste in all applications even the native text editor. It’s enabled in the Privacy & Security > Accessibility

**Comment by a76yyyy** [comment]
The phenomenon is that the cursor in the target program will be lost when maccy is used to paste automatically by shortcut keys.

**Comment by a76yyyy** [comment]
> The phenomenon is that the cursor in the target program will be lost when maccy is used to paste automatically by shortcut keys.

I found that my other applications also occupied the corresponding shortcut keys, so it triggered other applications and then triggered maccy, causing the cursor loss.

It is unclear whether MacOS has the way to automatically detect shortcut keys conflict?

**Comment by Maczinger** [comment]
so, is there no solution? 😞
