### ISSUE TITLE
Request: hotkey to open the list from the menu bar instead of on the cursor

### ISSUE THREAD

**Issue by skelly** [p0deje/Maccy#88]
From a direct email to @p0deje, I had requested an option to have the list expand from the menu bar with a hotkey, instead of on the cursor or centered on the screen, and he asked that I open an issue here. Understandable if this is of no use to anyone, it's just a personal preference.

**Comment by p0deje** [comment]
It is not exactly the same, but in new version you will be able to do this:

```sh
defaults write org.p0deje.Maccy popupPosition statusItem
```

And then Maccy will popup at the same place where icon is.
