### ISSUE TITLE
The amount of data shown on mouseover popup is too little in some cases (example)

### ISSUE THREAD

**Issue by valynor** [p0deje/Maccy#880]
### Before Submitting Your Bug Report

- [X] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

2.00

### macOS Version

15.0

### Maccy Settings

```Shell
defaults read org.p0deje.Maccy
{
    "KeyboardShortcuts_delete" = "{\\"carbonModifiers\\":2048,\\"carbonKeyCode\\":51}";
    "KeyboardShortcuts_pin" = "{\\"carbonModifiers\\":2048,\\"carbonKeyCode\\":35}";
    "KeyboardShortcuts_popup" = "{\\"carbonModifiers\\":768,\\"carbonKeyCode\\":8}";
    "LaunchAtLogin__hasMigrated" = 1;
    "NSStatusItem Preferred Position Item-0" = 260;
    "NSStatusItem Visible Item-1" = 0;
    "NSWindow Frame SUStatusFrame" = "760 781 400 134 0 0 1920 1175 ";
    "NSWindow Frame SUUpdateAlert" = "970 762 620 398 0 0 2560 1415 ";
    "NSWindow Frame com.sindresorhus.Preferences.FrameAutosaveName" = "696 509 542 435 0 0 1920 1175 ";
    "NSWindow Frame com.sindresorhus.Settings.FrameAutosaveName" = "1025 719 510 473 0 0 2560 1415 ";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2024-09-18 13:01:33 +0000";
    SUUpdateGroupIdentifier = 3935178220;
    WebKitDefaultFontSize = 13;
    WebKitJavaEnabled = 0;
    WebKitJavaScriptEnabled = 0;
    WebKitPluginsEnabled = 0;
    WebKitStandardFont = "-apple-system-font";
    WebKitUserStyleSheetEnabledPreferenceKey = 1;
    WebKitUserStyleSheetLocationPreferenceKey = "/Applications/Maccy.app/Contents/Frameworks/Sparkle.framework/Resources/ReleaseNotesColorStyle.css";
    enabledPasteboardTypes =     (
        "public.file-url",
        "public.tiff",
        "public.rtf",
        "public.utf8-plain-text",
        "public.html",
        "public.png"
    );
    highlightMatch = color;
    history = {length = 42, bytes = 0x62706c69 73743030 a0080000 00000000 ... 00000000 00000009 };
    historySize = 100;
    ignoreEvents = 0;
    ignoreOnlyNextEvent = 0;
    ignoredPasteboardTypes =     (
        "Pasteboard generator type",
        "de.petermaurer.TransientPasteboardType",
        "com.agilebits.onepassword",
        "com.typeit4me.clipping",
        "net.antelle.keeweb"
    );
    menuIcon = clipboard;
    migrations =     {
        "2024-07-01-version-2" = 1;
    };
    numberOfUsages = 1;
    pinTo = top;
    playSounds = 0;
    popupPosition = center;
    previewDelay = 750;
    searchMode = mixed;
    showFooter = 1;
    showSearch = 1;
    showTitle = 0;
    windowPosition = "[0.9107421875,1]";
    windowSize = "[459,1411]";
}
```

### Description

As you can see from the screenshot below Maccy doesn't show the full text copied in its popup. 
When I copied the requested Maccy Settings above it DOES show all of the text in the popup though - seems to be dependent on the source. 

![Screenshot 2024-09-18 at 14 57 01](https://github.com/user-attachments/assets/4be42b71-af4d-4e8c-9239-a851fd9a3fe2)
https://www.theguardian.com/world/2024/sep/17/photo-titan-submersible-wreckage

**Comment by p0deje** [comment]
Please try in 2.1.0, here is how it looks for me
<img width="1457" alt="Screenshot 2024-10-02 at 08 30 51" src="https://github.com/user-attachments/assets/4558945d-0ff8-4c6f-902b-f7d776943145">

**Comment by valynor** [comment]
@p0deje 

I tried again with the example above and I'm afraid it's exactly the same as before. 

Could this be a resolution/UI scaling issue?

**Comment by p0deje** [comment]
@valynor I don't think it's related, can you please upload a new screenshot?

**Comment by valynor** [comment]
![Screenshot 2024-10-02 at 19 20 07](https://github.com/user-attachments/assets/71f9edb6-e5cd-4c7a-949f-e3df48b0e54e)

Like I said, exactly the same.

**Comment by valynor** [comment]
@p0deje 
Hi, displaying long text seems to be fixed now but URLs are still broken. 

Example: Go to https://www.amazon.de/dp/B0DLBSF3PC/ and copy the URL from the toolbar. 
In the Maccy popup it looks like this: 

![Screenshot 2024-11-23 at 03 31 38](https://github.com/user-attachments/assets/cfca8338-0f1e-4600-94dc-4896b3e0e4dd)

**Comment by p0deje** [comment]
Yeah, this still needs improvement. The problem is that SwiftUI doesn't provide an easy solution for wrapping the text so hacky workarounds are necessary for now. I'll try to find a better way to do this.

**Comment by p0deje** [comment]
Can you update to 2.2.1, it should be a bit better (though still not perfect)

**Comment by valynor** [comment]
Updated, much better now. Even very long links wrap nicely and show completely now. Thanks again.
