### ISSUE TITLE
pasting clipboard not work on mac Sequoia

### ISSUE THREAD

**Issue by idorahamim** [p0deje/Maccy#882]
### Before Submitting Your Bug Report

- [x] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [x] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

2.0.0 (47)

### macOS Version

15.0

### Description
Maccy paste menu does not open when clicking `⌥V`

_No response_

### Steps to Reproduce
try to open Maccy clipboard by shortcuts 

_No response_

**Comment by nitzcard** [comment]
I also have this problem

**Comment by NikoMuffin** [comment]
Paging @nitzcard  & @idorahamim
This is not a issue with Maccy; it's is a major bug in macOS Sequoia. There's a reddit thread about it here.
https://www.reddit.com/r/macapps/comments/1fjpiiw/psa_macos_15_breaks_optionkey_hotkeys/
