### ISSUE TITLE
Text content not appearing in the list (not being copying by default)

### ISSUE THREAD

**Issue by wyllyan** [p0deje/Maccy#883]
### Before Submitting Your Bug Report

- [X] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

2.0.0 (47)

### macOS Version

15.0

### Maccy Settings

```Shell
{
    "KeyboardShortcuts_delete" = "{\\"carbonKeyCode\\":51,\\"carbonModifiers\\":2048}";
    "KeyboardShortcuts_pin" = "{\\"carbonModifiers\\":2048,\\"carbonKeyCode\\":35}";
    "KeyboardShortcuts_popup" = "{\\"carbonKeyCode\\":9,\\"carbonModifiers\\":768}";
    NSNavPanelExpandedSizeForOpenMode = "{800, 448}";
    NSOSPLastRootDirectory = {length = 608, bytes = 0x626f6f6b 60020000 00000410 30000000 ... 24010000 00000000 };
    "NSStatusItem Visible Item-1" = 0;
    "NSWindow Frame NSNavPanelAutosaveName" = "891 682 800 448 0 0 2560 1415 ";
    "NSWindow Frame com.sindresorhus.Settings.FrameAutosaveName" = "1025 722 510 487 0 0 2560 1415 ";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2024-09-18 14:57:25 +0000";
    SUUpdateGroupIdentifier = 4094916903;
    enabledPasteboardTypes =     (
        "public.tiff",
        "public.png",
        "public.file-url"
    );
    ignoreEvents = 0;
    ignoredApps =     (
    );
    migrations =     {
        "2024-07-01-version-2" = 1;
    };
    pasteByDefault = 0;
    removeFormattingByDefault = 0;
    searchMode = fuzzy;
    showFooter = 1;
    showSearch = 1;
    showTitle = 1;
    suppressClearAlert = 0;
    windowPosition = "[0.836328125,0.9189985272459499]";
    windowSize = "[450,169]";
}
```

### Description

Maccy not grabbing copied texts. Work only with images.

### Steps to Reproduce

1. New Install
2. Copy any text

<img width="624" alt="Captura de Tela 2024-09-18 às 12 23 24" src="https://github.com/user-attachments/assets/d3246844-2d05-4f73-96b8-d3238ab86046">

**Comment by yunake** [comment]
I'm facing the same issue – I upgraded to macos 15 & Maccy to 2.0.0 (from last 0.x release) at the same time, and now Maccy doesn't copy anything. How can I test to see if Maccy is even able to intercept the clipboard?

**Comment by tommyka** [comment]
Just tried to install it on a new machine and are experiencing the same issue.

Maccy 2.0.0 (47)
Mac v 14.6

**Comment by mikepietruszka** [comment]
I experienced the same issue with Macy 2.0.0 and macOS Sonoma 14.6.1. Installed using brew.

**Comment by PallavAg** [comment]
For me the issue was that for some reason after updating, the `Text` option was unticked in settings:
![image](https://github.com/user-attachments/assets/a8d8e7d0-10f1-47ba-be66-ad0b66b88328)

**Comment by p0deje** [comment]
Folks, please resize your Maccy window - it's too small to show anything more than 1 item.

**Comment by p0deje** [comment]
One thing to note is that it should auto-resize up to a certain point, so if it didn't - maybe there is a bug there, I need to test this more. For now, resize to your taste.

**Comment by tommyka** [comment]
It seams that my issue was the same as @PallavAg.
I would expect that text was set by default. Thats the reason for installing the app for my sake.

I hope that default will be changed.

**Comment by wyllyan** [comment]
> For me the issue was that for some reason after updating, the `Text` option was unticked in settings: ![image](https://private-user-images.githubusercontent.com/40081309/369253487-a8d8e7d0-10f1-47ba-be66-ad0b66b88328.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MzY1MDMsIm5iZiI6MTcyNjgzNjIwMywicGF0aCI6Ii80MDA4MTMwOS8zNjkyNTM0ODctYThkOGU3ZDAtMTBmMS00N2JhLWJlNjYtYWQwYjY2Yjg4MzI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDEyNDMyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyYTJkMDYyODM5MWNjY2Y1YmViZmI5ZTg3YzUwYTUyMzk2NGIzNzk3OTE1ZjI4ZTFiNDcyN2RmNzI2NDM4MDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.06Bp9fYBKY2njebTswsp_1oRlbOLlWR3KW1pBU208dE)

No way, thanks!
