### ISSUE TITLE
custom shortcut (option+c) to open maccy is not working 

### ISSUE THREAD

**Issue by vijaymihiran** [p0deje/Maccy#885]
### Before Submitting Your Bug Report

- [X] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

2.0.0 (47)

### macOS Version

15.0

### Maccy Settings

```Shell
{
    "KeyboardShortcuts_delete" = "{\\"carbonModifiers\\":2048,\\"carbonKeyCode\\":51}";
    "KeyboardShortcuts_pin" = "{\\"carbonModifiers\\":2048,\\"carbonKeyCode\\":35}";
    "KeyboardShortcuts_popup" = "{\\"carbonKeyCode\\":8,\\"carbonModifiers\\":2048}";
    "LaunchAtLogin__hasMigrated" = 1;
    "NSStatusItem Visible Item-0" = 0;
    "NSStatusItem Visible Item-1" = 0;
    "NSWindow Frame SUUpdateAlert" = "446 409 620 398 0 0 1512 944 ";
    "NSWindow Frame com.sindresorhus.Settings.FrameAutosaveName" = "501 366 510 473 0 0 1512 944 ";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2024-09-18 14:52:27 +0000";
    SUUpdateGroupIdentifier = 1487625662;
    avoidTakingFocus = 1;
    enabledPasteboardTypes =     (
        "public.html",
        "public.file-url",
        "public.png",
        "public.utf8-plain-text",
        "public.tiff",
        "public.rtf"
    );
    historySize = 99;
    ignoredPasteboardTypes =     (
        "de.petermaurer.TransientPasteboardType",
        "com.agilebits.onepassword",
        "net.antelle.keeweb",
        "Pasteboard generator type",
        "com.typeit4me.clipping"
    );
    migrations =     {
        "2024-07-01-version-2" = 1;
    };
    pasteByDefault = 1;
    popupPosition = cursor;
    showFooter = 1;
    showInStatusBar = 0;
    showSearch = 1;
    showTitle = 0;
    windowPosition = "[0.37996031746031744,0.6408898305084746]";
    windowSize = "[487,503]";
}
```

### Description

option with any letter if I select as a shortcut to open the maccy then it's not working. If I add cmd to these like cmd+option+{any letter} it works. 

### Steps to Reproduce

1. open preferences --> General
2. select the open and record the shortcut to option+c and try opening the maccy.

**Comment by NikoMuffin** [comment]
Paging @vijaymihiran    This is not a issue with Maccy; it's is a major bug in macOS Sequoia. There's a reddit thread about it here. 
https://www.reddit.com/r/macapps/comments/1fjpiiw/psa_macos_15_breaks_optionkey_hotkeys/

**Comment by minikdev** [comment]
I have the same issue, I guess we're gonna wait for a fix from apple
