### ISSUE TITLE
Packaging Issue: Cannot upgrade to 2.x using brew

### ISSUE THREAD

**Issue by LinuxLowell** [p0deje/Maccy#886]
### Before Submitting Your Bug Report

- [X] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

1.0.0 -> 2.0.0

### macOS Version

13.6.6

### Maccy Settings

```Shell
Don’t think this is applicable but I will provide regardless

{
    "KeyboardShortcuts_delete" = "{\\"carbonModifiers\\":2048,\\"carbonKeyCode\\":51}";
    "KeyboardShortcuts_pin" = "{\\"carbonModifiers\\":2048,\\"carbonKeyCode\\":35}";
    "KeyboardShortcuts_popup" = "{\\"carbonModifiers\\":768,\\"carbonKeyCode\\":8}";
    "LaunchAtLogin__hasMigrated" = 1;
    "NSWindow Frame com.sindresorhus.Settings.FrameAutosaveName" = "2604 458 542 441 1792 40 1920 1055 ";
    SUHasLaunchedBefore = 1;
    enabledPasteboardTypes =     (
        "public.tiff",
        "public.utf8-plain-text",
        "public.html",
        "public.rtf",
        "public.png",
        "public.file-url"
    );
    ignoredPasteboardTypes =     (
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "com.agilebits.onepassword",
        "net.antelle.keeweb",
        "Pasteboard generator type"
    );
    migrations =     {
        "2020-04-25-allow-custom-ignored-types" = 1;
        "2020-06-19-use-keyboardshortcuts" = 1;
        "2020-09-01-ignore-keeweb" = 1;
        "2021-02-20-allow-to-customize-supported-types" = 1;
        "2021-06-28-add-title-to-history-item" = 1;
        "2021-10-16-remove-dynamic-pasteboard-types" = 1;
        "2022-08-01-rename-suppress-clear-alert" = 1;
        "2022-11-14-add-html-rtf-to-supported-types" = 1;
        "2023-01-22-add-regexp-search-mode" = 1;
    };
    searchMode = fuzzy;
}
```

### Description

Looks like a packaging problem. I cannot upgrade to 2.0.0 using brew. The error message I get indicates that it thinks I am using an OS version older than Sonoma. I am using Ventura.

```
==> Upgrading 1 outdated package:
maccy 1.0.0 -> 2.0.0
==> Upgrading maccy
==> Purging files for version 2.0.0 of Cask maccy
Error: maccy: This software does not run on macOS versions older than Sonoma.
```

### Steps to Reproduce

1. in terminal, “brew upgrade maccy"

**Comment by brainmaniac** [comment]
+1

**Comment by LinuxLowell** [comment]
> That's expected, 2.0 requires macOS 14. See #790 for reasoning,

Then maybe the error message needs to be updated/clarified?

**Comment by p0deje** [comment]
> This software does not run on macOS versions older than Sonoma.

The error message is correct, what needs to be clarified?

**Comment by LinuxLowell** [comment]
> The error message is correct, what needs to be clarified?

You are correct. For some reason I was thinking Sonoma was an older version (pre Ventura.) Sequoia was in the back of head as the newest release. I was only half right. I am not a daily macOS user. Maybe add the macOS version number to the message?

I have not upgraded to more recent versions of macOS because I am running on Intel silicon (i9). My experience has been the newer versions introduce noticeable performance hits. At some point I am expecting Apple to drop intel support all together. I guess I’ll cross that bridge when I come to it.

Thank you. maccy is awesome, just as powerful as most clipboard managers in Linux in my opinion.

**Comment by p0deje** [comment]
> You are correct. For some reason I was thinking Sonoma was an older version (pre Ventura.) Sequoia was in the back of head as the newest release. I was only half right. I am not a daily macOS user. Maybe add the macOS version number to the message?

The error message is generated by Homebrew automatically - https://formulae.brew.sh/cask/maccy
