### ISSUE TITLE
Request on how pins are displayed and properties

### ISSUE THREAD

**Issue by alapolloni** [p0deje/Maccy#89]
Can I suggest that:
-  pinned clips live at the bottom of the list of displayed clips in a pop out folder that lists the pinned clips?
- Pinned clips could have editable properties. the short cut and a text name that is included in the search.
  - the short cut that selects it
  - a text name that describes it.
    - when using the search in Maccy, it should include the above text name in the search.
(for example, if you saved  **¯\\_(ツ)_/¯**   as a clip, you could edit and give it the text name _shrug_.  Searching _shrug_ would then find it.)

**Comment by alapolloni** [comment]
![Maccy - saved pins](https://user-images.githubusercontent.com/1752380/77259507-34773f80-6c82-11ea-8d5e-6358b342c524.png)

**Comment by rsperl** [comment]
Wow, I've been searching for a replacement for Paste, and this is really the only thing that Paste does that Maccy doesn't. This would be awesome!

**Comment by said50** [comment]
I would love to see an option to show pinned items at the bottom

**Comment by p0deje** [comment]
There is now an option to show pins at the bottom. It will be available in the next release.

**Comment by alexsereno** [comment]
@p0deje +1 to pin titles, as they're stored longer-term being able to give them a tag really helps when searching "[memes]" "[angry email templates]" etc

**Comment by mateusz-fiolka** [comment]
One small additional option request - I sometimes keep ssh / gpg passwords / secrets in snippet manager - an option per item to not show the item value would be great.

**Comment by vandreykiv** [comment]
@p0deje any ideas when it can be implemented? Thank you

**Comment by p0deje** [comment]
I don't really have the capacity to work on this now, so I can't give any ETA. PRs are always welcome! 😉
