### ISSUE TITLE
When preview a big picture, the pic popup covers all the panel

### ISSUE THREAD

**Issue by chenxiccc** [p0deje/Maccy#893]
### Before Submitting Your Bug Report

- [X] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

2.0.1

### macOS Version

15.0 (24A335)

### Maccy Settings

```Shell
{
    "KeyboardShortcuts_delete" = "{\\"carbonKeyCode\\":51,\\"carbonModifiers\\":2048}";
    "KeyboardShortcuts_pin" = "{\\"carbonKeyCode\\":35,\\"carbonModifiers\\":2048}";
    "KeyboardShortcuts_popup" = "{\\"carbonModifiers\\":4096,\\"carbonKeyCode\\":9}";
    "LaunchAtLogin__hasMigrated" = 1;
    "NSStatusItem Preferred Position Item-0" = 5506;
    "NSStatusItem Visible Item-1" = 0;
    "NSWindow Frame com.sindresorhus.Settings.FrameAutosaveName" = "608 427 510 473 0 0 1680 1025 ";
    SUAutomaticallyUpdate = 1;
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2024-09-22 05:45:54 +0000";
    SUSendProfileInfo = 0;
    SUUpdateGroupIdentifier = 2417714185;
    avoidTakingFocus = 0;
    enabledPasteboardTypes =     (
        "public.html",
        "public.tiff",
        "public.utf8-plain-text",
        "public.png",
        "public.rtf"
    );
    hideFooter = 1;
    historySize = 50;
    ignoredPasteboardTypes =     (
        "net.antelle.keeweb",
        "com.typeit4me.clipping",
        "Pasteboard generator type",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType"
    );
    imageMaxHeight = 20;
    maxMenuItems = 15;
    menuIcon = clipboard;
    migrations =     {
        "2020-04-25-allow-custom-ignored-types" = 1;
        "2020-06-19-use-keyboardshortcuts" = 1;
        "2020-09-01-ignore-keeweb" = 1;
        "2021-02-20-allow-to-customize-supported-types" = 1;
        "2021-06-28-add-title-to-history-item" = 1;
        "2021-10-16-remove-dynamic-pasteboard-types" = 1;
        "2022-08-01-rename-suppress-clear-alert" = 1;
        "2022-11-14-add-html-rtf-to-supported-types" = 1;
        "2023-01-22-add-regexp-search-mode" = 1;
        "2024-07-01-version-2" = 1;
    };
    pasteByDefault = 1;
    pinTo = bottom;
    popupPosition = cursor;
    previewDelay = 1500;
    removeFormattingByDefault = 0;
    showFooter = 0;
    showInStatusBar = 1;
    showRecentCopyInMenuBar = 0;
    showSearch = 1;
    showTitle = 1;
    windowSize = "[450,800]";
}
```

### Description

When copy a big screen shot, such as a whole screen, when preview the pic in the panel, the preview popup covers the maccy panel, and cannot select other items.
The preview popup should appears on the left or right side of the panel, should not appears in front of the panel.
<img width="1679" alt="image" src="https://github.com/user-attachments/assets/eff6f080-62d9-49c1-8b4c-295b13148f4e">

**Comment by chenxiccc** [comment]
The right position:
<img width="1677" alt="image" src="https://github.com/user-attachments/assets/cea667ed-a835-4ca1-bb28-8b530614ab93">

The wrong position:
<img width="1679" alt="image" src="https://github.com/user-attachments/assets/1f701c98-6033-4431-b6e0-6855c4f24b88">

**Comment by chenxiccc** [comment]
@p0deje I've tested 2.1.0 release, this is NOT fixed.

**Comment by p0deje** [comment]
That's the default behavior whenever there is not enough space to the left / right of the window to show the preview.

**Comment by chenxiccc** [comment]
> That's the default behavior whenever there is not enough space to the left / right of the window to show the preview.

Oh, I see. Thanks.
But when there is not enough space to the left / right of the window to show the preview, reduce the preview width to make the preview on the left/right may be better?
