### ISSUE TITLE
support Control+N/Control+P to move up and down in the list

### ISSUE THREAD

**Issue by ferdinandrau** [p0deje/Maccy#894]
### Before Submitting Your Feature Request

- [X] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

These are standard Vim keys, it would be cool if they were supported. What's strange is that i came across an old issue https://github.com/p0deje/Maccy/issues/352#issuecomment-1009584103 saying that that's supported, but it does not work for me. Only arrow keys and Control+J/Control+K seem to be enabled.

Could it have to do with these shortcuts being "claimed" by the text field?

**Comment by mrzool** [comment]
This began with 2.0 and worked fine in 1.0, so it seems more like a bug or regression... this issue might be mislabeled.

It would be great to have this fixed — for now I’ve reverted to 1.0, as this is highly disruptive for me.
