### ISSUE TITLE
Copied Items don't appear in Maccy

### ISSUE THREAD

**Issue by Xytronix** [p0deje/Maccy#895]
### Before Submitting Your Bug Report

- [X] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

Latest

### macOS Version

15.0

### Description

Unfortunately, copied items don't appear in Maccy in some rare occasions.

### Steps to Reproduce

1. Copy an Item in Arc
2. Not appearing in maccy

**Comment by p0deje** [comment]
What version of Maccy do you run?

**Comment by saifulbkhan** [comment]
This happens for me too. I am using Maccy 2.0.1 on macOS Sequoia 15.0.

**Comment by saifulbkhan** [comment]
I found my fix on [this thread](https://github.com/p0deje/Maccy/issues/883#issuecomment-2362706504). Any reason why "Text" copying is switched off by default in the new OS?

Anyway, thanks for building this awesome tool. Can't live without it :)

**Comment by p0deje** [comment]
This is now fixed in 2.0.1 though you might have to double-check if "Text" is enabled in the "Storage" settings.
