### ISSUE TITLE
Request: Add a setting for how many clips are displayed

### ISSUE THREAD

**Issue by alapolloni** [p0deje/Maccy#90]
Suggest you add a setting for how many clips are displayed.  This is in addition to History Size (and therefore search will still find and display those clips which are in the history but not initially displayed.)
>  **History Display**
>  defaults write org.p0deje.Maccy historyDispaly 20 # default is 10

**Comment by p0deje** [comment]
Added in 201e1d6d6db0d9c8e0996d686509a807bfe3dadb and will be available in the next version.
