### ISSUE TITLE
Where is the setting number of items ?

### ISSUE THREAD

**Issue by eintausendstel** [p0deje/Maccy#902]
### Before Submitting Your Feature Request

- [x] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [x] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

Where is the setting number of items and track length in the preferences of Maccy version 2 ?
<img width="536" alt="Screenshot 2024-09-27 at 15 34 56" src="https://github.com/user-attachments/assets/f654d9e8-1c63-4c29-a48c-a03f9be7c5c6">
Version 1.x.x

**Comment by dyaskur** [comment]
Do you mean history/storage size?

![CleanShot 2024-09-28 at 05 28 18@2x](https://github.com/user-attachments/assets/f6c19cb4-371f-48c6-b7cf-245e2584beae)

**Comment by p0deje** [comment]
It's gone per release 2.0

> Appearance preference Number of items removed. Instead, vertically resize the main panel window according to your needs.
