### ISSUE TITLE
create new keyboard copy shortcuts for maccy

### ISSUE THREAD

**Issue by lyzzz0101** [p0deje/Maccy#903]
### Before Submitting Your Feature Request

- [ ] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [ ] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

often copy some info that is not want to store in maccy. could it be possible to create a new copy shortcut and only used for maccy?

**Comment by p0deje** [comment]
It doesn't look to be possible.
