### ISSUE TITLE
Option-key + key shortcut to open Maccy doesn't work anymore since macOS 15 Sequoia

### ISSUE THREAD

**Issue by webdev69420** [p0deje/Maccy#904]
### Before Submitting Your Bug Report

- [X] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

2.0.1 (48)

### macOS Version

Sequoia 15.0

### Maccy Settings

```Shell
{
    "KeyboardShortcuts_delete" = "{\\"carbonModifiers\\":2048,\\"carbonKeyCode\\":51}";
    "KeyboardShortcuts_pin" = "{\\"carbonKeyCode\\":35,\\"carbonModifiers\\":2048}";
    "KeyboardShortcuts_popup" = "{\\"carbonKeyCode\\":41,\\"carbonModifiers\\":2048}";
    "LaunchAtLogin__hasMigrated" = 1;
    NSNavLastRootDirectory = "/Applications";
    NSNavPanelExpandedSizeForOpenMode = "{800, 448}";
    "NSStatusItem Preferred Position Item-0" = 454;
    "NSStatusItem Visible Item-0" = 1;
    "NSStatusItem Visible Item-1" = 0;
    NSUserKeyEquivalents =     {
    };
    "NSWindow Frame NSNavPanelAutosaveName" = "560 561 800 448 0 0 1920 1175 ";
    "NSWindow Frame SUStatusFrame" = "1080 977 400 134 0 0 2560 1415 ";
    "NSWindow Frame SUUpdateAlert" = "961 778 637 398 0 0 2560 1415 ";
    "NSWindow Frame com.sindresorhus.Preferences.FrameAutosaveName" = "496 699 584 435 0 0 2560 1415 ";
    "NSWindow Frame com.sindresorhus.Settings.FrameAutosaveName" = "1025 724 510 488 0 0 2560 1415 ";
    SUAutomaticallyUpdate = 0;
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2024-09-30 09:08:06 +0000";
    SUUpdateGroupIdentifier = 1740476263;
    WebKitDefaultFontSize = 13;
    WebKitJavaEnabled = 0;
    WebKitJavaScriptEnabled = 0;
    WebKitPluginsEnabled = 0;
    WebKitStandardFont = "-apple-system-font";
    WebKitUserStyleSheetEnabledPreferenceKey = 1;
    WebKitUserStyleSheetLocationPreferenceKey = "/Applications/Maccy.app/Contents/Frameworks/Sparkle.framework/Resources/ReleaseNotesColorStyle.css";
    enabledPasteboardTypes =     (
        "public.rtf",
        "public.tiff",
        "public.png",
        "public.utf8-plain-text",
        "public.html"
    );
    history = {length = 42, bytes = 0x62706c69 73743030 a0080000 00000000 ... 00000000 00000009 };
    historySize = 690;
    ignoreEvents = 0;
    ignoredApps =     (
        "com.bitwarden.desktop"
    );
    ignoredPasteboardTypes =     (
        "com.typeit4me.clipping",
        "de.petermaurer.TransientPasteboardType",
        "com.agilebits.onepassword",
        "net.antelle.keeweb",
        "Pasteboard generator type"
    );
    imageMaxHeight = 90;
    maxMenuItems = 0;
    migrations =     {
        "2024-07-01-version-2" = 1;
    };
    pasteByDefault = 0;
    playSounds = 0;
    popupPosition = center;
    removeFormattingByDefault = 0;
    searchMode = fuzzy;
    showFooter = 1;
    showInStatusBar = 1;
    showRecentCopyInMenuBar = 0;
    showSearch = 1;
    showTitle = 0;
    suppressClearAlert = 1;
    windowPosition = "[0.36875,0.6439674315321984]";
    windowSize = "[450,800]";
}
```

### Description

Shortcuts starting with the Option (⌥) key (for example ⌥+M) to open Maccy don't work anymore (nothing happens) since updating to macOS 15 Sequoia.

Apparently this is an [intentional change by Apple devs to increase security](https://developer.apple.com/forums//thread/763878?src=push&answerId=804374022#804374022).

Other people and apps are apparently [also impacted](https://www.reddit.com/r/macapps/comments/1fjpiiw/psa_macos_15_breaks_optionkey_hotkeys/) by this breaking change.

If I understand the technicalities correctly, this can be fixed in the non-sandboxed version of Maccy but not for the sandboxed version of Maccy (App Store).

### Steps to Reproduce

1. Set the keyboard shortcut to open Maccy to Option (⌥) + some other key on macOS Sequoia 15.0
2. Try the shortcut
3. Nothing happens (normally Maccy should open)

**Comment by webdev69420** [comment]
Workaround for people that don't want to have to change Maccy shortcuts in macOS 15.0 Sequoia:
[https://www.reddit.com/r/macapps/comments/1fjpiiw/comment/lolslnm/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button](https://www.reddit.com/r/macapps/comments/1fjpiiw/comment/lolslnm/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)

**Comment by kdanet** [comment]
I confirm this problem.
It's just awful! 
I'm so used to the `option + v` combination

**Comment by gkumarcloudbees** [comment]
> I confirm this problem. It's just awful! I'm so used to the `option + v` combination

I’m experiencing the same problem; now `Option + V` results in `ˇ`.
