### ISSUE TITLE
Visual reminder of which hotkey does which within the app

### ISSUE THREAD

**Issue by lucymhdavies** [p0deje/Maccy#905]
### Before Submitting Your Feature Request

- [x] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [x] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

Currently, we have all this information in the settings...

<img width="476" alt="image" src="https://github.com/user-attachments/assets/d3c613ea-e708-4cdf-ae06-c1e67c198b17">

but not from the main Maccy interface

<img width="724" alt="image" src="https://github.com/user-attachments/assets/40079fae-e265-451e-ae77-2ce93b0c90cd">

### Solution

Ideal solution would be to expand the list shown in the menu, similar to how we have "Press X to (un)pin" and "Press X to delete"

In my example configuration, showing something like "Press X to copy, clear formatting, and paste" would be a useful visual reminder

**Comment by p0deje** [comment]
I would consider the shortcuts to be intuitive given the default shortcut would exercise your preferred action (copy/paste) and pressing Option (Alt) would alter that.
