### ISSUE TITLE
Request: Copy sound when copy something

### ISSUE THREAD

**Issue by eserdinyo** [p0deje/Maccy#91]
It would be nice if i heard a sound when copy something to clipboard like [Paste](https://pasteapp.io/) 😊

**Comment by p0deje** [comment]
Any idea what sound that might be?

**Comment by eserdinyo** [comment]
This kind of a simple [sound](https://easyupload.io/p1r4z1) would be great ✌️

**Comment by p0deje** [comment]
I've added 2 sounds:

* on new copy https://easyupload.io/9klwcr
* on selecting https://easyupload.io/wltgqj

@eserdinyo What do you think?

**Comment by FernandoMiguel** [comment]
oh please default this to off!!!

**Comment by p0deje** [comment]
haha, it's default to off

**Comment by eserdinyo** [comment]
@p0deje sorry. but i couldn't find where to open it.

**Comment by p0deje** [comment]
mp3 files? Just click on it once and press Space - it should play it.

**Comment by eserdinyo** [comment]
ohh sorry. I thought you add to app. Yes. Both of them so nice. I like it. 😍

**Comment by p0deje** [comment]
Released in 0.14.0
