### ISSUE TITLE
Display the app icon, from which the text was copied 

### ISSUE THREAD

**Issue by Romachamp** [p0deje/Maccy#912]
### Before Submitting Your Feature Request

- [X] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

Hello! I’ve used Maccy for a long time, but the main issue I faced was not being able to instantly see, from where I copied the item. Later, I discovered I can see the app, from where I copied, but it isn’t displayed next to it, so I must click on the item to get this information. 

### Solution

The solution I want is the app icon, from where the item is copied, right next to it. In this way, I can instantly see, from where I copied anything. 

Alternatively, you could provide an option in the settings to display app icon next to the copied item, instead of the keyboard shortcut to paste that item. It would be more handy for me personally.

**Comment by p0deje** [comment]
You can see the source app in the preview, which can be shown instantly by changing Preview Delay. Is this enough for your needs?

**Comment by Romachamp** [comment]
Well, I’ve used this feature. However, in the preview the app is shown by the text and it still isn’t that handy. With app icon right next to the copied icon, I would be able to see it instantly and it would be more handy to me.

**Comment by Romachamp** [comment]
@p0deje you could add an option to the settings to show the app icon, instead of shortcuts, so people can decide what’s more handy for them. What do you think about it?

**Comment by p0deje** [comment]
I am open to merge PRs adding support for this, but I don't have capacity to implement it myself at the moment.

**Comment by weisJ** [comment]
I have this actually implemented in the branch where I keep my custom changes: ab9fb0aa666b64bfcf17964d3397d34297520798

I don't have a lot of time to clean it up and connect it to the settings, however it is a good starting point @Romachamp

**Comment by p0deje** [comment]
> I have this actually implemented in the branch where I keep my custom changes: https://github.com/p0deje/Maccy/commit/ab9fb0aa666b64bfcf17964d3397d34297520798

Screenshots or didn't happen.

**Comment by Romachamp** [comment]
Awesome, this is exactly what I wanted. It would be awesome, if it were in the app.

**Comment by Romachamp** [comment]
@p0deje Will you implement this feature now, since there is a pull request?

**Comment by p0deje** [comment]
@Romachamp There is no PR yet.
@weisJ Are you up to create a PR with this? We'd need a checkbox in Appearance setting to turn it on (with off by default) and localizations for it in all languages (I can help with that).

**Comment by weisJ** [comment]
I can create a PR. Still have to do some cleanup. Currently not satisfied with how I am handling missing icons. Also the cache needs to have some eviction strategy to ensure icons get updated when they change.

I would also add the icon to the preview popover next to the application name. Should this be toggled through the same settings switch or always be visible?

**Comment by p0deje** [comment]
> I can create a PR. Still have to do some cleanup. Currently not satisfied with how I am handling missing icons. Also the cache needs to have some eviction strategy to ensure icons get updated when they change.

I haven't looked through the code, but I'll trust your judgement with whatever is the best here.

> I would also add the icon to the preview popover next to the application name. Should this be toggled through the same settings switch or always be visible?

I think it's fine to always show in the preview, maybe with a different size to make it more compact.

**Comment by Romachamp** [comment]
Good point, I also think it’s fine to show the icon in the preview as well, but a bit smaller.

**Comment by Romachamp** [comment]
@weisJ Will you be able to implement these app icons into Maccy, after polishing the code a bit?

**Comment by Romachamp** [comment]
@p0deje There is now a PR. Will there be this feature any soon?
