### ISSUE TITLE
Copy-on-select

### ISSUE THREAD

**Issue by XZF0** [p0deje/Maccy#917]
### Before Submitting Your Feature Request

- [X] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

Cmd-C is unnecessary and annoying. 

### Solution

Copy-on-select, like unix terminals. "Copy automatically" joining the "Paste automatically" option: seems logical :)

(and a possible enhancement: no copy if the selection is followed by the "delete" keystroke. however, even the basic copy-on-select would already be **insanely** useful)

**Comment by p0deje** [comment]
It's not possible to do that in a sandboxed macOS application.
