### ISSUE TITLE
There is a problem with the icon in the status bar on the outside screen of the mac Connect monitor

### ISSUE THREAD

**Issue by wego-xuchang** [p0deje/Maccy#920]
### Before Submitting Your Bug Report

- [ ] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [ ] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

2.0

### macOS Version

15.0.1

### Description

![image](https://github.com/user-attachments/assets/a027bb26-2870-4e93-aed2-aa9084a4a5da)

There is a problem with the icon in the status bar on the outside screen of the mac Connect monitor

**Comment by cxin-william** [comment]
我也遇到了

**Comment by p0deje** [comment]
Please upgrade to 2.1 and see if it helps
