### ISSUE TITLE
some copies don't showing in Maccy 

### ISSUE THREAD

**Issue by tomkoi** [p0deje/Maccy#921]
### Before Submitting Your Bug Report

- [X] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

2.1.0 (49)

### macOS Version

14.7

### Maccy Settings

```Shell
"KeyboardShortcuts_delete" = "{\\"carbonKeyCode\\":51,\\"carbonModifiers\\":2048}";
    "KeyboardShortcuts_pin" = "{\\"carbonKeyCode\\":35,\\"carbonModifiers\\":2048}";
    "KeyboardShortcuts_popup" = "{\\"carbonKeyCode\\":9,\\"carbonModifiers\\":4096}";
    "NSStatusItem Preferred Position Item-0" = 404;
    "NSStatusItem Visible Item-1" = 0;
    "NSWindow Frame SUUpdateAlert" = "825 413 620 398 0 0 2270 925 ";
    "NSWindow Frame com.sindresorhus.Settings.FrameAutosaveName" = "894 328 510 473 0 0 2270 925 ";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2024-10-09 06:49:24 +0000";
    SUUpdateGroupIdentifier = 1623831703;
    enabledPasteboardTypes =     (
        "public.utf8-plain-text",
        "public.tiff",
        "public.png",
        "public.rtf",
        "public.html"
    );
    historySize = 500;
    ignoredPasteboardTypes =     (
    );
    imageMaxHeight = 65;
    menuIcon = clipboard;
    migrations =     {
        "2024-07-01-version-2" = 1;
    };
    pasteByDefault = 1;
    popupPosition = statusItem;
    searchMode = exact;
    showFooter = 1;
    showRecentCopyInMenuBar = 0;
    showSearch = 1;
    showSpecialSymbols = 0;
    showTitle = 1;
    sortBy = lastCopiedAt;
    windowPosition = "[0.8522026431718062,1]";
    windowSize = "[671,782]";
}
```

### Description

Some copies I do from different apps seems the Maccy app not "read" it and i can't see them in the open menu of all my clipboard history. It's really annoying because i love this app!

**Comment by p0deje** [comment]
See if resizing Maccy window helps, otherwise please attach a screenshot of the window to show what's wrong.

**Comment by tomkoi** [comment]
> See if resizing Maccy window helps, otherwise please attach a screenshot of the window to show what's wrong.

Hi!
I resize the window per your suggest.
Not sure how screenshot can help to describe the issue, but it's very simple - some copies when i click command + c keys not appears in maccy app.

**Comment by p0deje** [comment]
1. Please share a screenshot of Maccy.
2. Do you have many pinned items?

**Comment by tomkoi** [comment]
@p0deje 
thanks for the reply,
I don't have any pinned items.
This currently screenshot of the app:
<img width="668" alt="Screenshot 2024-10-15 at 9 21 53" src="https://github.com/user-attachments/assets/c4e07a07-7655-4e32-8235-2292fd09d35a">
not sure what you can see here :)

**Comment by p0deje** [comment]
> some copies when i click command + c keys not appears in maccy app.

Hmm, can you provide more details, some concrete apps?

**Comment by tomkoi** [comment]
> > some copies when i click command + c keys not appears in maccy app.
> 
> Hmm, can you provide more details, some concrete apps?
mmmm i notice it's happen randomly from SecureCRT, Google Chrome and maybe more. It's a little bit hard to say because i not always notice to it... hope you can figure it.

**Comment by p0deje** [comment]
I can only figure out if you provide exact steps how to reproduce the problem.

**Comment by tomkoi** [comment]
Thanks.
The only step I can provide it’s try to copy many times via command + c from different apps for a few times
Even now I replaying from my outlook and see it happened, I randomly did some copies only 1 of 3 I see in maccy menu


Best regards

Tom Koifman
Data Center Engineer
Nvidia Israel
• [Office] +972(74)7129340<tel:+972747129340>  •  [Mobile] +972(54)8119335<tel:+972548119335>  • [E-Mail] ***@***.******@***.***>
[A green and black logo  Description automatically generated]

Report a Lab Services Issue<https://nvidia.service-now.com/esc?id=sc_cat_item&sys_id=1e07194e97c25150275ef7300153afaf>
Request for Lab Services<https://nvidia.service-now.com/esc?id=sc_cat_item&table=sc_cat_item&sys_id=55406dad97ec1910275ef7300153af6c>

***@***.***?anonymous&ep=signature>Book time to meet with ***@***.***?anonymous&ep=plink>

From: Alex Rodionov ***@***.***>
Date: Tuesday, 15 October 2024 at 16:50
To: p0deje/Maccy ***@***.***>
Cc: Tom Koifman ***@***.***>, Author ***@***.***>
Subject: Re: [p0deje/Maccy] some copies don't showing in Maccy (Issue #921)

I can only figure out if you provide exact steps how to reproduce the problem.

**Comment by tomkoi** [comment]
@p0deje 
what you think the issue can be?

**Comment by p0deje** [comment]
@tomkoi No idea, I cannot reproduce the issue myself

**Comment by porelli** [comment]
I'm having the same issue. I use Maccy on multiple computers with more or less the setup. On one of them copies are not always stored in Maccy, I cannot reproduce accurately but I noticed this happens after a while I do not access Maccy

**Comment by p0deje** [comment]
Since there is no way to reproduce it, I'm going to close - please provide more details how I can get this issue and I'll address it.
