### ISSUE TITLE
Maccy won't remember setting to save Files 

### ISSUE THREAD

**Issue by Larsen2k4** [p0deje/Maccy#925]
### Before Submitting Your Bug Report

- [X] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

2.1.0

### macOS Version

15.0

### Maccy Settings

```Shell
{
    "KeyboardShortcuts_delete" = "{\\"carbonModifiers\\":2048,\\"carbonKeyCode\\":51}";
    "KeyboardShortcuts_pin" = "{\\"carbonModifiers\\":2048,\\"carbonKeyCode\\":35}";
    "KeyboardShortcuts_popup" = "{\\"carbonKeyCode\\":9,\\"carbonModifiers\\":768}";
    "LaunchAtLogin__hasMigrated" = 1;
    "NSStatusItem Visible Item-0" = 0;
    "NSStatusItem Visible Item-1" = 0;
    "NSWindow Frame SUUpdateAlert" = "401 373 638 398 0 0 1440 875 ";
    "NSWindow Frame com.sindresorhus.Settings.FrameAutosaveName" = "365 294 510 487 0 0 1440 875 ";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2024-10-11 20:47:21 +0000";
    SUUpdateGroupIdentifier = 3014689118;
    clearOnQuit = 1;
    clearSystemClipboard = 1;
    enabledPasteboardTypes =     (
        "public.tiff",
        "public.png",
        "public.utf8-plain-text",
        "public.html",
        "public.rtf",
        "public.file-url"
    );
    historySize = 10;
    ignoredPasteboardTypes =     (
        "com.agilebits.onepassword",
        "com.typeit4me.clipping",
        "net.antelle.keeweb",
        "de.petermaurer.TransientPasteboardType",
        "Pasteboard generator type"
    );
    imageMaxHeight = 50;
    maxMenuItems = 10;
    migrations =     {
        "2024-07-01-version-2" = 1;
    };
    pasteByDefault = 1;
    searchVisibility = always;
    showFooter = 1;
    showInStatusBar = 0;
    showSearch = 1;
    showTitle = 0;
    sortBy = lastCopiedAt;
    windowSize = "[450,800]";
}
```

### Description

Maccy doesn't save the option after quitting to keep files in history. Only images and text stay selected.

### Steps to Reproduce

1. Settings 2. Memory 3. Activate "Files" 4. Quit Maccy 5. "Files" is unchecked again,

**Comment by HarishRaj10644** [comment]
Hi there, @p0deje! I have this issue as well. I tried reinstalling maccy via Homebrew today, but it still persists. I also observed that the size of copy resets to 100 every time I restart the app.

**Comment by p0deje** [comment]
Please remove Maccy complete `brew uninstall --zap maccy` and install again.

**Comment by HarishRaj10644** [comment]
Thanks, @p0deje! That fixed the size of copy resetting, but files is still unchecked every time I restart the app.

**Comment by p0deje** [comment]
@HarishRaj10644 it's fixed in https://github.com/p0deje/Maccy/commit/3c5cf30e1fe703e01b388b08a3fd744458a7b971 but not released yet

**Comment by HarishRaj10644** [comment]
Thanks, @p0deje! Will wait for the next update.
