### ISSUE TITLE
The search input box in Maccy occasionally stops accepting keyboard input, and it only works again after restarting.

### ISSUE THREAD

**Issue by qiHuang112** [p0deje/Maccy#926]
### Before Submitting Your Bug Report

- [X] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [ ] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

2.1.0(49)

### macOS Version

14.2 (23C64)

**Comment by qiHuang112** [comment]
<img width="510" alt="image" src="https://github.com/user-attachments/assets/5028eab1-765d-4e58-a8d4-9bc79f57f624">
After restarting, the first search works fine, but the next time it won’t accept input.

**Comment by p0deje** [comment]
Please upgrade macOS to 14.7

**Comment by qiHuang112** [comment]
Thanks, upgrading to 15.0.1 (24A348) fixed it!
