### ISSUE TITLE
No way to access preferences

### ISSUE THREAD

**Issue by thedesignersdeveloper** [p0deje/Maccy#928]
### Before Submitting Your Bug Report

- [ ] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [ ] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

2.1.0

### macOS Version

14.6.1

### Maccy Settings

```Shell
Last login: Wed Oct 16 12:35:01 on ttys001
brendanfoster@Maurices-MacBook-Air ~ % defaults read org.p0deje.Maccy
{
    "KeyboardShortcuts_delete" = "{\\"carbonKeyCode\\":51,\\"carbonModifiers\\":2048}";
    "KeyboardShortcuts_pin" = "{\\"carbonKeyCode\\":35,\\"carbonModifiers\\":2048}";
    "KeyboardShortcuts_popup" = "{\\"carbonKeyCode\\":9,\\"carbonModifiers\\":768}";
    "NSStatusItem Preferred Position Item-0" = 428;
    "NSStatusItem Visible Item-1" = 0;
    "NSWindow Frame com.sindresorhus.Settings.FrameAutosaveName" = "1118 1147 510 422 -970 900 3440 1415 ";
    enabledPasteboardTypes =     (
        "public.html",
        "public.tiff",
        "public.utf8-plain-text",
        "public.png",
        "public.rtf"
    );
    ignoreEvents = 0;
    migrations =     {
        "2024-07-01-version-2" = 1;
    };
    numberOfUsages = 3;
    pasteByDefault = 1;
    showFooter = 0;
    showSearch = 0;
    showTitle = 0;
    windowSize = "[450,800]";
}
brendanfoster@Maurices-MacBook-Air ~ %
```

### Description

I've just purchased Maccy, set it up but now i have no access to the maccy preferences at all. I can only get the clipboard view. 

- Right click provides nothing
- Clicking on it doesnt replace Finder with Maccy to access preferences.
- Quiting and re-opening doesn't work.
- Option + Click 
- Deleting Maccy and re-downloading from Mac store produces the same issue.
![Uploading Screenshot 2024-10-16 at 1.37.10 PM.png…]()

Nothing will allow me to access the preferences to change the hotkey.

**Comment by p0deje** [comment]
Open Maccy and press COMMAND+,

**Comment by thedesignersdeveloper** [comment]
That didn't work.

**Comment by twknab** [comment]
> That didn't work.

Hi @thedesignersdeveloper  -- Note: you should be able to click the Maccy system tray icon > Preferences

The default palette command is `⇧ + ⌘ + C`, and will also see "Preferences" option at bottom of palette window.

**Comment by thedesignersdeveloper** [comment]
Nope that doesn't work either.

The very first time I opened it yesterday after purchasing i had access to preferences.

Now they don't appear.
Even moving the icon from applications to the mac tray doesnt allow it.
If i click on that icon i only get the display of clipboard but it doesn't even replace the 'Finder' in the top mac bar with 'Maccy'.

There is no way for me to access preferences through right click in applications and if i can't get it to appear in the top bar as any app should i can't access it's settings.

Very very strange issue i've never had with any app.

As mentioned deleting and re-downloading doesn't solve this.

Here's a 1:30 video to help make it easier to understand the problem.
If im doing something unbelievably stupid please let me know.

https://www.loom.com/share/ffff59342671493da90a6d1f42e8b6f4?sid=29bd9134-96b9-4e3a-8feb-be1d7471d113

**Comment by p0deje** [comment]
@thedesignersdeveloper You have disabled the Footer in preferences, so now the options for "Preferences" is hidden. You should be able to still open it via the`⌘,` shortcut. If it's not working, you can enable footer again by running the following command in Terminal.app


```
defaults write org.p0deje.Maccy showFooter true
```

**Comment by thedesignersdeveloper** [comment]
The ⌘ shortcut didn't work. (I even tried an external keyboard)

BUT the terminal command worked!

Thanks very much for your speedy assistance.
Problem solved i can now access the preferences.
