### ISSUE TITLE
Keyboard shortcuts (eg ⌘A) don't work in search field

### ISSUE THREAD

**Issue by vardecab** [p0deje/Maccy#93]
Hey, great app! 

Small issue, low priority.

One thing I noticed is that keyboard shortcut ⌘A doesn't work in the search field. Wanted to search for something, typed several letters but I made a mistake so wanted to quickly redo whole query but surprise — need to go one by one with the Backspace.

**Comment by vardecab** [comment]
Probably this shortcut doesn't work because it's reserved for a pinned clipboard item?

**Comment by p0deje** [comment]
The support for shortcuts is quite limited in Maccy now. You can clean the search field with `CMD+DELETE` but that's pretty much it.

Could you outline what shortcuts should be supported? I am likely to add it.

**Comment by p0deje** [comment]
I've also added support for CONTROL-W to remove the last word (d6f08de5c16b4704785b582b1137b214ef9b6ca3). Closing this for now as there is not much to do. COMMAND+A is used for pins.
