### ISSUE TITLE
Feature Request: Automatically Remove Personal Names from File Paths in Error Logs

### ISSUE THREAD

**Issue by spcx86** [p0deje/Maccy#930]
### Before Submitting Your Feature Request

- [X] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

I would like to propose a new feature for Maccy that addresses a common issue developers face when sharing error logs. Often, error messages contain file paths with personal names (e.g., computer usernames), which could unintentionally expose personal information when shared on public forums or issue trackers. This feature would automatically detect and anonymize such file paths before they are copied to the clipboard.

Problem
Many developers use their real names during computer setup, which then appear in file paths (e.g., /Users/ramesh-jores/...). When developers copy-paste error logs, they might overlook this personal information, potentially exposing sensitive data unintentionally. Manually editing file paths can be tedious and error-prone.

### Solution

Proposed Solution
Add functionality to Maccy to:

Automatically anonymize or remove the personal name component in these paths when copying error logs (for example, replacing /Users/ramesh-jores/ with /Users/<anonymous>/).
Optionally allow users to configure or input their personal name(s) to ensure they are anonymized correctly.

**Benefits**
Increased privacy and security for developers when sharing error logs.
Reduction in manual work and effort when posting logs in public forums or issue trackers.
Helps users avoid unintentional exposure of personal information.
Potential Implementation
Use regular expressions to detect and anonymize file paths.
Implement this as an optional feature that can be enabled in Maccy's settings.

Additional Context
**I would be happy to contribute this feature and help with its implementation! Please let me know if this aligns with the project's goals and how best to proceed.**

Thank you for considering this feature!

**Comment by p0deje** [comment]
It's rare when folks share logs in Maccy issues, so I don't think it's worth adding this complexity in the app.

**Comment by spcx86** [comment]
@p0deje "It's rare when folks share logs in Maccy issues" - i think you misunderstood. Its a general privacy feature aimed towards developers. 

Whenever, I as a dev, copy some error logs into some forum(stackoverflow, or some internet forum dedicated to the software, say some oss's github page), i paste the entire error logs. 

For example, yesterday, I had posted an error message which had this line to get help in one of the forums: 
`[admin] npm ERR! at location: /Users/subhapradachand/Code/Ghost/ghost/admin`

I felt a little weird giving out my whole path with my name in the location(granted I can just change the name of the user, but for office laptops these are almost always preconfigured).

I want to change this so that maccy detects this and changes it to something the user wants to like "anonymous" or maybe their github handle. 

No issues if you still find it a niche use case, I will take this idea elsewhere.

**Comment by p0deje** [comment]
I think this belongs more to an app like Pure Paste that cleans up copies - Maccy attempts to store everything w/o any modifications.

**Comment by spcx86** [comment]
cool. thanks for the recommendation.
