### ISSUE TITLE
User reports Open shortcut no longer works after latest Maccy update

### ISSUE THREAD

**Issue by mattrclanton** [p0deje/Maccy#936]
### Before Submitting Your Bug Report

- [x] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [x] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

2.1.0

### macOS Version

15.0.1

### Maccy Settings

```Shell
{
  "KeyboardShortcuts_delete" = "{\\"carbonKeyCode\\":51,\\"carbonModifiers\\":2048}";
  "KeyboardShortcuts_pin" = "{\\"carbonKeyCode\\":35,\\"carbonModifiers\\":2048}";
  "KeyboardShortcuts_popup" = "{\\"carbonKeyCode\\":11,\\"carbonModifiers\\":2048}";
  "LaunchAtLogin__hasMigrated" = 1;
  "NSStatusItem Preferred Position Item-0" = 469;
  "NSStatusItem Visible Item-1" = 0;
  "NSWindow Frame SUStatusFrame" = "-1480 896 400 134 -2560 -65 2560 1415 ";
  "NSWindow Frame SUUpdateAlert" = "-1590 697 620 398 -2560 -65 2560 1415 ";
  "NSWindow Frame com.sindresorhus.Preferences.FrameAutosaveName" = "-1551 557 542 436 -2560 -65 2560 1415 ";
  "NSWindow Frame com.sindresorhus.Settings.FrameAutosaveName" = "479 324 510 421 0 0 1440 875 ";
  SUEnableAutomaticChecks = 1;
  SUHasLaunchedBefore = 1;
  SULastCheckTime = "2024-10-24 16:57:45 +0000";
  SUUpdateGroupIdentifier = 3121509900;
  WebKitDefaultFontSize = 13;
  WebKitJavaScriptEnabled = 0;
  WebKitPluginsEnabled = 0;
  WebKitStandardFont = "-apple-system-font";
  WebKitUserStyleSheetEnabledPreferenceKey = 1;
  WebKitUserStyleSheetLocationPreferenceKey = "/Applications/Maccy.app/Contents/Frameworks/Sparkle.framework/Resources/ReleaseNotesColorStyle.css";
  avoidTakingFocus = 1;
  enabledPasteboardTypes =   (
    "public.html",
    "public.png",
    "public.utf8-plain-text",
    "public.tiff",
    "public.rtf"
  );
  ignoredPasteboardTypes =   (
    "com.agilebits.onepassword",
    "com.typeit4me.clipping",
    "Pasteboard generator type",
    "net.antelle.keeweb",
    "de.petermaurer.TransientPasteboardType"
  );
  menuIcon = maccy;
  migrations =   {
    "2024-07-01-version-2" = 1;
  };
  pasteByDefault = 1;
  showFooter = 1;
  showSearch = 1;
  showTitle = 1;
  windowSize = "[450,800]";
}
```

### Description

A user in my org who uses Maccy is reporting that the Open shortcut (Option+B) no longer works, and changing the shortcut to something else also does not work. Here's exactly what they said:

"Hey! Since I installed the updated required in my MAC, my Maccy App has not been working the way it’s supposed to. It’s supposed to open automatically with option B “ ∫” but it does nothing. When opening it manually it does work, but it considerably slows down my work flow. I’ve had this issue since last week and have tried quitting and restarting the app, changing the open command to another one (another letter or command instead of option), restarting the laptop, turning it off and off again and comparing the preferences setting specifications to my co-workers to see if anything was different on my end, and I did update the maccy version as well to the latest one.  None of this has worked yet disappointed face I’ve tried this at home and in the office so wi-fi not seems to be related, what can be going on?"

I have also instructed them to delete the app and re-install with no luck.

**Comment by p0deje** [comment]
That's macOS Sequoia limitation, you can read more in #813
