### ISSUE TITLE
Exclude Apps - PwSafe, Enpass, Lastpass

### ISSUE THREAD

**Issue by vikas027** [p0deje/Maccy#94]
How can I exclude more apps like PwSafe, Enpass, Lastpass?

Rather than hard coding the values in the [code](https://github.com/p0deje/Maccy/blob/master/Maccy/Clipboard.swift#L11-L18), maybe it is better to read through a file or env vars or something more dynamic?

Related Tickets:
- https://github.com/p0deje/Maccy/issues/79
- https://github.com/p0deje/Maccy/issues/65

**Comment by p0deje** [comment]
Fair enough. It makes sense to move it to `UserDefaults.standard.ignoredTypes`. I'll happily merge PRs for that.

**Comment by shobhitpuri** [comment]
What's the pasteboard type for LastPass to ignore it?

**Comment by p0deje** [comment]
LastPass should be filtered by default. Make sure you can default ignored types configured https://github.com/p0deje/Maccy#ignore-custom-copy-types.

**Comment by shobhitpuri** [comment]
@p0deje I have that already. I think I know the reason. Since I am using the LastPass Chrome extension, it is detecting it as coming from the Chrome browser. That's why it is showing up copied passwords from LastPass, since copying from Chrome Browser is allowed.

**Comment by p0deje** [comment]
That's probably correct. You can follow https://github.com/p0deje/Maccy/issues/125#issuecomment-646612371 to see what types are present for copied item.

**Comment by AJMiller** [comment]
I'm experiencing this problem as well. Unfortunately the LastPass extension reports the type as 'public.utf8-plain-text`. If I block that, I imagine the app effectively stops working.

**Comment by p0deje** [comment]
@AJMiller Unfortunately, neither solution will help because it will look like you copied from Chrome (or whatever browser you use with LastPass extension).

**Comment by ChrisFR06** [comment]
Could you exclude Bitwarden by default too?
