### ISSUE TITLE
AI Prompt Manger?

### ISSUE THREAD

**Issue by stanislavkozlovski** [p0deje/Maccy#940]
### Before Submitting Your Feature Request

- [x] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [x] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

Using AI prompts is a very similar problem to the clipboard management, but easier to solve:

- you have a few pre-defined AI prompts you wanna use
- you wanna be able to paste them into the AI immediately just like Maccy allows you to paste copied content

It would be amazing to have a Maccy feature directly that allows you to achieve this.
To generalize it - it's basically a separate "clipboard folder" that you manually upload clipboards to, and use different hotkeys to pull up.

**Comment by stanislavkozlovski** [comment]
One hacky idea to achieve this for myself with least effort is:
1. fork Maccy
2. change the name/etc. so it is a separate executeable. call it `Prompty`
3. very carefully upload prompts via some hacky script that a) copies them to the clipboard so they go there, b) disabled Prompty auto clipboard update via the `defaults write org.p0deje.Prompty ignoreEvents true` command (as is in the readme)

**Comment by p0deje** [comment]
I don't think that's a core functionality of the clipboard manager, I think having a separate snippet manager app for this would be better.
