### ISSUE TITLE
[Bug] Entry is wrongly selected when opening

### ISSUE THREAD

**Issue by wenfangdu** [p0deje/Maccy#941]
### Before Submitting Your Feature Request

- [X] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

First of all, thank you for making this great app! Quite frequently, maccy popup shows up while the cursor is hovering on a maccy entry, then that entry got selected, when I press `enter`, that entry is pasted, which is unintended.

### Solution

Have an option to disable hovering to select, in this case, an entry can only be selected via keyboard.

**Comment by p0deje** [comment]
please share the details of running `defaults read org.p0deje.Maccy` in Terminal.app

**Comment by wenfangdu** [comment]
```bash
$ defaults read org.p0deje.Maccy
2024-11-03 11:34:46.674 defaults[70591:13299712] 
Domain /Users/x/Library/Containers/org.p0deje.Maccy/Data/Library/Preferences/org.p0deje.Maccy does not exist
```

**Comment by wenfangdu** [comment]
@p0deje 
```bash
$ defaults read org.p0deje.Maccy
2024-11-03 11:34:46.674 defaults[70591:13299712] 
Domain /Users/x/Library/Containers/org.p0deje.Maccy/Data/Library/Preferences/org.p0deje.Maccy does not exist
```

**Comment by stephen714** [comment]
This happens for me too, regularly. I second OP's request 😊 Great app though; absolute life saver!!

**Comment by wenfangdu** [comment]
@p0deje Is it released in 2.2.0? Still reproducible in 2.2.0 though.

**Comment by wenfangdu** [comment]
@p0deje Is it released in 2.2.0? Still reproducible in 2.2.0 though, please reopen.

**Comment by wenfangdu** [comment]
@p0deje Notice "exodus" is selected which it shouldn't, the cursor isn't moved, but that entry got selected:

https://github.com/user-attachments/assets/8f02b676-c943-4138-b450-10c6365cd77c

**Comment by p0deje** [comment]
@wenfangdu I cannot reproduce this error, see how the first item remains selected when I popup 

https://github.com/user-attachments/assets/db1184df-8c6f-4fb6-94e5-b2f93848e1d9

**Comment by wenfangdu** [comment]
@p0deje Strange, what macOS version are you on? I'm on macOS 15.1.1, it's not 100% reproducible, maybe 25% chance, you can try different ways to reproduce, e.g. different app, different popup position, different cursor position, with/without clicking, etc.

With all due respect, this issue asks for an option to disable the hovering to select entirely, this could fix it once and for all. The closing commit didn't add such option, hence, this issue should be reopened.

**Comment by 750** [comment]
Not sure if this is the same issue, but here is a video of something similar:

https://github.com/user-attachments/assets/6aa4ccc4-c2a7-4965-aeca-f0b01012001b

I'm on sonoma 14.5 though

**Comment by p0deje** [comment]
@wenfangdu Please try 2.2.1, it should be a bit better. If still an issue, please provide steps how to reproduce it reliably.

**Comment by wenfangdu** [comment]
@p0deje Yes, it's a bit better, but unfortunately still reproducible:

https://github.com/user-attachments/assets/19b5bc6d-97d4-4046-bd30-b105aa31833b

**Comment by wenfangdu** [comment]
@p0deje I've edited the issue title, please reopen until it gets fixed 🙏.

**Comment by wenfangdu** [comment]
@p0deje You've asked before though.

```bash
$ defaults read org.p0deje.Maccy
2024-11-26 22:26:00.814 defaults[49208:3729202] 
Domain /Users/x/Library/Containers/org.p0deje.Maccy/Data/Library/Preferences/org.p0deje.Maccy does not exist
```

**Comment by p0deje** [comment]
@wenfangdu This is really strange and bothers me because I cannot confirm an integrity of your Maccy version. Have you ever changed any settings in Maccy?

**Comment by wenfangdu** [comment]
@p0deje Sorry, my bad, my privacy settings blocked the terminal from reading the config:

```plain
{
    "KeyboardShortcuts_delete" = "{\\"carbonKeyCode\\":51,\\"carbonModifiers\\":2048}";
    "KeyboardShortcuts_pin" = "{\\"carbonModifiers\\":2048,\\"carbonKeyCode\\":35}";
    "KeyboardShortcuts_popup" = "{\\"carbonModifiers\\":4096,\\"carbonKeyCode\\":9}";
    "LaunchAtLogin__hasMigrated" = 1;
    "NSStatusItem Preferred Position Item-0" = 540;
    "NSStatusItem Visible Item-1" = 0;
    "NSWindow Frame SUStatusFrame" = "788 691 400 134 0 0 1920 1055 ";
    "NSWindow Frame SUUpdateAlert" = "677 492 620 398 0 0 1920 1055 ";
    "NSWindow Frame com.sindresorhus.Preferences.FrameAutosaveName" = "1108 113 549 661 0 0 1920 1055 ";
    "NSWindow Frame com.sindresorhus.Settings.FrameAutosaveName" = "732 448 510 474 0 0 1920 1055 ";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2024-11-26 06:10:54 +0000";
    SUSendProfileInfo = 0;
    SUUpdateGroupIdentifier = 2169978086;
    WebKitDefaultFontSize = 13;
    WebKitJavaScriptEnabled = 0;
    WebKitPluginsEnabled = 0;
    WebKitStandardFont = "-apple-system-font";
    WebKitUserStyleSheetEnabledPreferenceKey = 1;
    WebKitUserStyleSheetLocationPreferenceKey = "/Applications/Maccy.app/Contents/Frameworks/Sparkle.framework/Resources/ReleaseNotesColorStyle.css";
    avoidTakingFocus = 0;
    enabledPasteboardTypes =     (
        "public.html",
        "public.utf8-plain-text",
        "public.png",
        "public.rtf",
        "public.tiff"
    );
    historySize = 500;
    ignoredPasteboardTypes =     (
        "Pasteboard generator type",
        "com.typeit4me.clipping",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
        "net.antelle.keeweb"
    );
    imageMaxHeight = 40;
    migrations =     {
        "2024-07-01-version-2" = 1;
    };
    pasteByDefault = 1;
    pinTo = top;
    popupPosition = window;
    removeFormattingByDefault = 0;
    showFooter = 1;
    showRecentCopyInMenuBar = 0;
    showSearch = 1;
    showTitle = 0;
    windowSize = "[450,800]";
}
```

**Comment by wenfangdu** [comment]
@p0deje Thanks for the fix, when will it be released?

**Comment by p0deje** [comment]
@wenfangdu 2.3.0 has just been released

**Comment by wenfangdu** [comment]
@p0deje Thanks, it works great!
