### ISSUE TITLE
Remove pinned items from the settings

### ISSUE THREAD

**Issue by jamesmudd** [p0deje/Maccy#946]
### Before Submitting Your Feature Request

- [X] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

It would be great if you can remove pined items from the settings e.g. here
<img width="644" alt="image" src="https://github.com/user-attachments/assets/a3e1fd3a-d133-4ce8-89d1-c122e97f9fc1">

### Solution

Add the ability to remove pinned items. A remove all might also be a nice feature.

**Comment by Valen-C12** [comment]
@jamesmudd Just run into this issue with same question.

And FYI you can use `option + P` to pin/unpin one item in the menu. I guess they just impl the setting to edit the pined items' content and shotcut

![image](https://github.com/user-attachments/assets/4e343550-9936-43cc-99e5-7ed2beed2667)
