### ISSUE TITLE
shortcut not work

### ISSUE THREAD

**Issue by shichanglin5** [p0deje/Maccy#947]
### Before Submitting Your Bug Report

- [ ] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [ ] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Settings

```Shell
see description screenshot
```

### Description

<img width="518" alt="image" src="https://github.com/user-attachments/assets/f84b7c69-4ab7-41aa-a41a-3c68660ab1e3">

**Comment by p0deje** [comment]
Duplicate of #813
