### ISSUE TITLE
Still can't paste images

### ISSUE THREAD

**Issue by ricoliu1995** [p0deje/Maccy#95]
I noticed the latest version support image copy&paste, however this didn't work for me, when I copy a image, the panel only shows and pastes the image file name, did I miss something?

**Comment by ricoliu1995** [comment]
And can the panel show "clear" option if I set hideFooter on? Thanks.

**Comment by p0deje** [comment]
I cannot reproduce the problem. Can you give me more details? What file do you copy? Where do you try to paste it?

**Comment by ricoliu1995** [comment]
all image files in Finder, no matter where I try to paste, it only paste the file name text, the macOS system is 10.13.6.

**Comment by p0deje** [comment]
This is not copy of image, but copy of file. Will be supported in newer version of Maccy. Duplicate of #85

**Comment by ricoliu1995** [comment]
got it, looking forward to the update.
