### ISSUE TITLE
The UI animation of the appearance of specific copy context is too laggy

### ISSUE THREAD

**Issue by EthanPixar** [p0deje/Maccy#950]
### Before Submitting Your Feature Request

- [X] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

The UI animation is the macOS default, but it is somehow not appropriate to use here. Since checking one's clipboard is such a static and professional work, I think it would create a better experience if the UI not bouncing all the time. Great thanks for this app!

**Comment by p0deje** [comment]
We're tracking the possible solutions to this problem in #819
