### ISSUE TITLE
The same content will be displayed multiple times

### ISSUE THREAD

**Issue by small-thanks** [p0deje/Maccy#951]
### Before Submitting Your Bug Report

- [ ] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [ ] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

2.1.0

### macOS Version

15.1

### Description

<img width="449" alt="image" src="https://github.com/user-attachments/assets/5c75207a-c278-4b71-a98c-932b03cc9361">

I copied the same content in different apps and it was displayed multiple times. I think the same string should only be displayed once in any app.

**Comment by p0deje** [comment]
It's likely a different content that looks the same (e.g. has different formatting or spaces/newlines)

**Comment by small-thanks** [comment]
No, they are the same, because I performed the following test
1. I copied the message from app A, and then checked maccy and found a record
2. I copied the message saved in maccy to app B
3. I pressed command + A from app B and then copied, checked maccy, and found two identical records

<img width="710" alt="image" src="https://github.com/user-attachments/assets/51772828-2673-4cdc-b513-773648caf8a4">

**Comment by p0deje** [comment]
You'd be surprised how much extra information is added to each copy by each app, which makes it look like completely different things. In your case, every browser adds the source URL for each copy in a different way, this makes these copies look separated in Maccy:

<img width="818" alt="Screenshot 2024-11-15 at 06 02 56" src="https://github.com/user-attachments/assets/b35d0258-da40-4756-b380-22e98831b6ed">
<img width="818" alt="Screenshot 2024-11-15 at 06 02 38" src="https://github.com/user-attachments/assets/577f225e-3347-4d0c-a01b-f1a16d9b9463">
