### ISSUE TITLE
Enhance visual differentiation between pinned items and temporary items

### ISSUE THREAD

**Issue by Gitbreast** [p0deje/Maccy#954]
### Before Submitting Your Feature Request

- [X] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

When you want to locate the first item without keyboard, it’s too slow under the new UI, need more time to see and locate.
(I use this a lot because some items cannot be pasted in some apps, unless I choose them again in Maccy. For example, after using iPhone’s OCR in Photos, the copied text will be synced to my Mac, but it cannot be pasted in some Apps for unknown reason, once I choose them again in Maccy, it can be pasted.)

### Solution

Please consider adding something or providing an option to enhance visual differentiation between pinned items and temporary items. Such as adding a divide between pinned and temp, or adding dots in front of pinned items, or so on.

**Comment by samtsevich** [comment]
Agree.
That would be cool to see a divider (horizontal line) that will separate Maccy window into 2 boxes – Pinned and history
I am pretty sure, this is a cosmetic feature, but still will be cool to see :)
