### ISSUE TITLE
remove tracking token from links

### ISSUE THREAD

**Issue by flyingisawol** [p0deje/Maccy#955]
### Before Submitting Your Feature Request

- [x] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [x] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

would love to see a feature added where tracking tokens are automatically removed before storing the item on the clipboard

example:

Original link copied: 
https://open.spotify.com/track/12ZTpSvqoRhlZh6GZZEvuR?si=00852593046d4a37

link saved to clipboard:
https://open.spotify.com/track/12ZTpSvqoRhlZh6GZZEvuR

### Solution

i guess it's a case of adding a filter when copying links to check if they contain `?si=` and if so, creating a new array upto the index location of the `?`

**Comment by p0deje** [comment]
That's implemented in the Pure Paste app, I suggest you use it.
