### ISSUE TITLE
Show last copy in menu bar 

### ISSUE THREAD

**Issue by 750** [p0deje/Maccy#958]
### Before Submitting Your Feature Request

- [X] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

It would be nice to support showing N symbols of last copy in the menu bar.

N should be configurable, the feature should be togglable.

IMO this feature would be in line with Maccy's mission, @p0deje do you agree? 

I realise that this would not be a top priority, maybe I'll try to implement this myselft

(would have to think about how to show non-text copies)

**Comment by p0deje** [comment]
There is already support for this in Settings / Appearance, have you checked it?

**Comment by 750** [comment]
🤦 my bad, found it, thank you.
