### ISSUE TITLE
软件权限不够覆盖mac自带的输入法

### ISSUE THREAD

**Issue by Mr-Yxx** [p0deje/Maccy#963]
### Before Submitting Your Feature Request

- [X] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

我想设置快捷键option+v打开剪切板，但是我输入快捷键之后出来的是√这个符号，原本设置好了应该能覆盖掉系统原本的快捷键，以前旧版是可以的

### Solution

希望可以安装设置快捷键后直接覆盖系统原本的符号快捷键，正常使用就好

**Comment by p0deje** [comment]
Apple forbids Option-only shortcuts in macOS 15+.
