### ISSUE TITLE
MacOS 15.1.1 Refuses Opt+V to Open 

### ISSUE THREAD

**Issue by PFarrell90** [p0deje/Maccy#967]
### Before Submitting Your Bug Report

- [X] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

Version 2.1.0 (49)

### macOS Version

15.1.1

### Maccy Settings

```Shell
{
    "KeyboardShortcuts_delete" = "{\\"carbonModifiers\\":2048,\\"carbonKeyCode\\":51}";
    "KeyboardShortcuts_pin" = "{\\"carbonModifiers\\":2048,\\"carbonKeyCode\\":35}";
    "KeyboardShortcuts_popup" = "{\\"carbonModifiers\\":6144,\\"carbonKeyCode\\":9}";
    "NSStatusItem Visible Item-0" = 1;
    "NSStatusItem Visible Item-1" = 0;
    "NSWindow Frame SUStatusFrame" = "664 709 400 134 0 0 1728 1079 ";
    "NSWindow Frame SUUpdateAlert" = "554 510 620 398 0 0 1728 1079 ";
    "NSWindow Frame com.sindresorhus.Preferences.FrameAutosaveName" = "593 334 542 462 0 0 1728 1079 ";
    "NSWindow Frame com.sindresorhus.Settings.FrameAutosaveName" = "525 459 510 473 0 0 1728 1079 ";
    SUEnableAutomaticChecks = 0;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2024-11-22 21:05:18 +0000";
    SUSendProfileInfo = 0;
    WebKitDefaultFontSize = 13;
    WebKitJavaScriptEnabled = 0;
    WebKitStandardFont = "-apple-system-font";
    WebKitUserStyleSheetEnabledPreferenceKey = 1;
    WebKitUserStyleSheetLocationPreferenceKey = "/Applications/Maccy.app/Contents/Frameworks/Sparkle.framework/Resources/ReleaseNotesColorStyle.css";
    avoidTakingFocus = 1;
    enabledPasteboardTypes =     (
        "public.rtf",
        "public.utf8-plain-text",
        "public.png",
        "public.tiff",
        "public.html"
    );
    fuzzySearch = 1;
    history = {length = 42, bytes = 0x62706c69 73743030 a0080000 00000000 ... 00000000 00000009 };
    historySize = 204;
    ignoredPasteboardTypes =     (
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "com.agilebits.onepassword",
        "net.antelle.keeweb",
        "Pasteboard generator type"
    );
    menuIcon = maccy;
    migrations =     {
        "2024-07-01-version-2" = 1;
    };
    pasteByDefault = 0;
    pinTo = top;
    searchMode = fuzzy;
    showFooter = 1;
    showInStatusBar = 1;
    showSearch = 1;
    showTitle = 1;
    suppressClearAlert = 0;
    windowSize = "[450,800]";
}
```

### Description

After updating to MacOS 15.1.1, I can no longer Open/Pop-up Maccy with Opt + V. Previously, on MacOS 14.7 I was able to. 

I have tried:
- Changing my keyboard input from `ABC` to `Unicode 8` to prevent the `√` character on Opt+V press : no change
- Removing any builtin Mac OS Keyboard Shortcuts/Custom App Shortcuts that use `Opt+V` : no change
- Uninstalling/reinstalling the latest Maccy app version via `brew`: no change
- Restarting Maccy multiple times

### Steps to Reproduce

1. Under Maccy Settings -> General, set the `Open` shortcut to `Opt+V`
2. Press `Opt+V`
3. Maccy does not open with the current clipboard values/history

Note: This does _not_ happen when using `Ctrl+Opt+V`, but this was not required before updating to 15.1.1

**Comment by weisJ** [comment]
This a limitation with macOS 15. It no longer allows applications to set shortcuts with the `opt` modifier.

@p0deje I think it would be worth while to pin one of these issues. Might mitigate the flood of created issues.

**Comment by PFarrell90** [comment]
Thanks so much for the quick response @weisJ -- I must've missed that in the MacOS `15` changelog. 

Also, I failed to find the previous issue for this -- that's my failing: https://github.com/p0deje/Maccy/issues/872 

I'll close this as a duplicate.
