### ISSUE TITLE
Using the accessibility feature of Spoken "Content->Speak selection" copies the selected text

### ISSUE THREAD

**Issue by yotamcons** [p0deje/Maccy#968]
### Before Submitting Your Bug Report

- [X] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

2.2.1 (53)

### macOS Version

14.7.1

### Maccy Settings

```Shell
{
    "KeyboardShortcuts_delete" = "{\\"carbonModifiers\\":2048,\\"carbonKeyCode\\":51}";
    "KeyboardShortcuts_pin" = "{\\"carbonKeyCode\\":35,\\"carbonModifiers\\":2048}";
    "KeyboardShortcuts_popup" = "{\\"carbonKeyCode\\":8,\\"carbonModifiers\\":768}";
    "NSStatusItem Visible Item-1" = 0;
    "NSWindow Frame com.sindresorhus.Settings.FrameAutosaveName" = "1025 719 510 473 0 0 2560 1415 ";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2024-11-27 07:35:07 +0000";
    enabledPasteboardTypes =     (
        "public.rtf",
        "public.png",
        "public.utf8-plain-text",
        "public.tiff",
        "public.html",
        "public.file-url"
    );
    menuIcon = clipboard;
    migrations =     {
        "2024-07-01-version-2" = 1;
    };
    searchMode = fuzzy;
    showApplicationIcons = 1;
    showFooter = 1;
    showRecentCopyInMenuBar = 0;
    showSearch = 1;
    showSpecialSymbols = 1;
    showTitle = 1;
    windowSize = "[450,800]";
}
```

### Description

I use the native accessibility feature of "Spoken Content"->"Speak selection", where you select any text throughout the system, click `alt + esc` and the text is read out to you.
I installed Maccy today and found that every text i select for reading is automatically copied to the clipboard.

### Steps to Reproduce

1. Activate speak selection in system preferences -> Accessibility -> Spoken Content -> Speak selection
2. Select some text and use the keyboard shortcut for speaking the text (default is `alt + esc`)
3. examine the Maccy clipboard

**Comment by p0deje** [comment]
How do you select the text to read out? Do you hover the cursor over an item or you also click on it?

**Comment by yotamcons** [comment]
I click and carry the mouse to select the text. I’m not sure it is relevant - the copying (indicated by a notification) is only triggered when I use the keyboard shortcut for speaking the selected text. ‫ב-27 בנוב׳ 2024, בשעה 16:18, ‏‏Alex Rodionov ***@***.***> כתב/ה:‬﻿
How do you select the text to read out? Do you hover the cursor over an item or you also click on it?

**Comment by p0deje** [comment]
> I click and carry the mouse to select the text. 

But when you click on the item in Maccy, it's copied to the clipboard immediately - that's the core Maccy functionality.

**Comment by yotamcons** [comment]
You miss understand me, the issue is real.
At no point did I click the text in Maccy, I clicked the text in my browser
to select it, just the normal way of selecting text.
Pot would be helpful to reproduce it according to the instructions.

בתאריך יום ד׳, 27 בנוב׳ 2024 ב-18:32 מאת Alex Rodionov <
***@***.***>:

**Comment by weisJ** [comment]
I just tried to replicate it. Selected text in the browser and pressed `opt + esc` to have it read out loud. It does not copy it to my clipboard. Also doesn't appear in Maccy. Can you please clarify what you are doing exactly? A screen recording of the issue would be very helpful.

**Comment by p0deje** [comment]
I just tried to select text in the browser and read it out. It worked, but nothing was copied or shown in Maccy. This is similar to what @weisJ reports.

What browser do you use? Does it only happen in the browser or other applications as well?

Ideally, please record a video showing the problem.

**Comment by yotamcons** [comment]
So far I've noticed the issue in google chrome and not other applications, and strange things seem to go on in the copy-paste regard. the first seconds of the recording look ok, but then the word "The" reappears in the clipboard, and a few moments later when i mark part of the word "united states" it is being copied 
https://github.com/user-attachments/assets/fa799a29-19ac-4d70-8772-c5f6cbc17d1d

**Comment by p0deje** [comment]
@weisJ This is not an issue for me given the same shortcut and Chrome, I can't reproduce.

@yotamcons Is there Any chance you have a Chrome extension installed that enables "Copy on select text" functionality (e.g. https://chromewebstore.google.com/detail/copy-on-select/kdfngfkkopeoejecmfejlcpblohnbael?hl=en)?

**Comment by yotamcons** [comment]
The issue is not related to the shortcut, as the copying doesn't happen while clicking `Cmd + shift + C` but by clicking the `alt esc`. I turned off all of my extensions and the issue persists. 
Two peculiar things:
1. The issue doesn't happen with every click. @p0deje do you have the spoken feature on? when you do, you might be able to reproduce if you repeat the initiation of speaking.   
2. The copied text is sometimes entered into the second positions
3. Could this be related to or fixed by some pasteboard types?

**Comment by p0deje** [comment]
1. Yes, I tried pressing Option+ESC, the text is spoken but not copied to the clipboard.
2. What do you mean by second positions?
3. Can you inspect the contents of copy after using Pasteboard Viewer app?

**Comment by yotamcons** [comment]
Thank you for taking the time to try and reproduce it.
By second position i mean it doesn't appear at the top of the list when i look at the Maccy clipboard. If you look at my screen recording at second 39 you will see that the newly copied text got into position number two.

Coming to think about it, apple might have the spoken text widget save the last copy in a temporary position, use the clipboard to pass the text to read to where it is needed, and then place the last copy back into the clipboard. If that is the case, is there a way to show it?

**Comment by p0deje** [comment]
> BTW, I've upgraded to Sequoia (15.1.1) last evening, so the issue apparently stayed with the next os as well.. what OS do you use @p0deje ?
can you try the speaking out on a file in finder as well?

Just tried and no new copy was registered. I'm using macOS 15.2 beta, but I don't think it's related at all. Sounds like there could be OS-level or some app that copies the content that is spoken over.

**Comment by yotamcons** [comment]
I will look into that, thank you for taking the time to try and resolve the issue

**Comment by yotamcons** [comment]
After investigating the issue it appears to be a regular behavior of MacOS under some settings to copy spoken text to the clipboard. Thank you again @p0deje  and @weisJ !
