### ISSUE TITLE
Maccy popup window disappears when moving mouse off it

### ISSUE THREAD

**Issue by freebrowser1** [p0deje/Maccy#969]
### Before Submitting Your Bug Report

- [x] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [x] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

2.2.1

### macOS Version

14.7

### Maccy Settings

```Shell
{
    "KeyboardShortcuts_delete" = "{\\"carbonModifiers\\":2048,\\"carbonKeyCode\\":51}";
    "KeyboardShortcuts_pin" = "{\\"carbonModifiers\\":2304,\\"carbonKeyCode\\":20}";
    "KeyboardShortcuts_popup" = "{\\"carbonModifiers\\":4352,\\"carbonKeyCode\\":18}";
    "LaunchAtLogin__hasMigrated" = 1;
    "NSStatusItem Preferred Position Item-0" = 526;
    "NSStatusItem Visible Item-1" = 0;
    "NSWindow Frame SUUpdateAlert" = "650 511 620 398 0 0 1920 1080 ";
    "NSWindow Frame com.sindresorhus.Settings.FrameAutosaveName" = "1985 355 482 311 1280 -280 1920 1080 ";
    SUAutomaticallyUpdate = 0;
    SUEnableAutomaticChecks = 0;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2024-09-20 11:34:58 +0000";
    SUSendProfileInfo = 0;
    avoidTakingFocus = 1;
    enabledPasteboardTypes =     (
        "public.png",
        "public.html",
        "public.tiff",
        "public.utf8-plain-text",
        "public.rtf"
    );
    ignoredPasteboardTypes =     (
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "Pasteboard generator type",
        "com.agilebits.onepassword",
        "net.antelle.keeweb"
    );
    migrations =     {
        "2024-07-01-version-2" = 1;
    };
    searchVisibility = always;
    showFooter = 1;
    showSearch = 1;
    showTitle = 1;
    sortBy = lastCopiedAt;
    windowSize = "[450,800]";
}
```

### Description

When being in the Terminal app and clicking the hotkey to popup Maccy, moving the mouse arrow closes the popup.

### Steps to Reproduce

1. Start Terminal.app
2. Press Maccy hotkey (or click on it in the Menu Bar)
3. Move mouse outside Maccy popup
4.Here the window disappears

This is very inconvenient, the window should remain open and be closed by a kind of a close button or the red button on the standard macOS stoplight which must be implemented then.

**Comment by p0deje** [comment]
Please record a video showing this behavior. This is a really strange behavior that I have never seen before.

**Comment by freebrowser1** [comment]
> Please record a video showing this behavior. This is a really strange behavior that I have never seen before.

This: 
https://github.com/user-attachments/assets/99fc4d67-590e-48ff-81ae-cb07fc116b4d

**Comment by p0deje** [comment]
Does it only happen in Terminal.app or other applications as well?

**Comment by p0deje** [comment]
This means you have focus follows mouse enabled. Please see if disabling it helps:

```
defaults write com.apple.Terminal FocusFollowsMouse false
```

**Comment by freebrowser1** [comment]
No does not work.
The issue is that when I move the mouse of an app window without clicking (such as Maccy) the windows should not disappear.

**Comment by weisJ** [comment]
I can reproduce your issue with Terminal with `defaults write com.apple.Terminal FocusFollowsMouse 1`. Though as @p0deje already mentioned this behaviour is expected. Maccy hides itself when it looses focus, which in this case happens as soon as the mouse move back over the terminal window. `FocusFollowsMouse` means that the terminal window takes focus every time the mouse moves over the window. Taking focus of course has to take away the focus from Maccy.

**Comment by freebrowser1** [comment]
> I can reproduce your issue with Terminal with `defaults write com.apple.Terminal FocusFollowsMouse 1`. Though as @p0deje already mentioned this behaviour is expected. **Maccy hides itself when it looses focus, which in this case happens as soon as the mouse move back over the terminal window.** `FocusFollowsMouse` means that the terminal window takes focus every time the mouse moves over the window. Taking focus of course has to take away the focus from Maccy.

Exactly, that is the bug. An app window should not disappear when the mouse moves off its window. No other app on macOS (and Linux / Windows) does this. 
`defaults write com.apple.Terminal FocusFollowsMouse 0` does not help preventing this.

**Comment by weisJ** [comment]
> Exactly, that is the bug. An app window should not disappear when the mouse moves off its window. No other app on macOS (and Linux / Windows) does this. 

It doesn’t close because the mouse moves outside the window. It closed because it looses focus. The shouldn’t think of the Maccy window as a classical application window but rather a menu. E.g if terminal has FocusFollowsMouse enabled try to open the WiFi settings window in the menu bar and move your mouse over the terminal. It will close too.

> `defaults write com.apple.Terminal FocusFollowsMouse 0` does not help preventing this.

You have to completely quit (Cmd+Q) Terminal for the changes to take effect. Please also try to delete the setting using `defaults delete com.apple.Terminal FocusFollowsMouse`.

**Comment by freebrowser1** [comment]
Indeed quitting and re-opening terminal helps: the Maccy windows does not close anymore
Thanks, that worked.

BTW, the wifi settings windows (opened by the wifi icon -> Wifi settings...) is just the standard "System settings" app and does not close when moving the mouse off the window. But it is, unlike Maccy, a standard window with a horizontal stoplight in the top bar requiring pressing the red button to close.

**Comment by p0deje** [comment]
> BTW, the wifi settings windows (opened by the wifi icon -> Wifi settings...) is just the standard "System settings" app and does not close when moving the mouse off the window. But it is, unlike Maccy, a standard window with a horizontal stoplight in the top bar requiring pressing the red button to close.

It still closes if you move the mouse to the Terminal window when `FocusFollowsMouse` is turned on.
