### ISSUE TITLE
Hotkey binding to command + # possible 

### ISSUE THREAD

**Issue by skekec1** [p0deje/Maccy#97]
Hi,

first of all I want to thank you for this great app. 

I have a short question regarding the hotkey binding:

Is it possible to bind command + # as hotkey. I have tried all possible variations without success. Maybe you can give me a hint?!

**Comment by p0deje** [comment]
I've just tried `defaults write org.p0deje.Maccy hotKey command+shift+3` and it worked. Is this what you were looking for?

**Comment by p0deje** [comment]
Closing since the issue cannot be reproduced and no response for more than a month.
