### ISSUE TITLE
Loosing input focus when Maccy opens

### ISSUE THREAD

**Issue by Drun555** [p0deje/Maccy#973]
### Before Submitting Your Bug Report

- [X] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### macOS Version

Sequoia 15.1.1

### Description

So... As we know, current macOS have some issues with keybindings via Option key, and thing unlikely gonna change. It's ok, since we have wonderful Karabiner - with this tool we can actually bind Option+Key to run Maccy.

```
{
    "description": "Maccy Option+V",
    "manipulators": [
        {
            "from": {
                "key_code": "v",
                "modifiers": { "mandatory": ["option"] }
            },
            "to": [{ "shell_command": "open -b org.p0deje.Maccy" }],
            "type": "basic"
        }
    ]
}
```

And it would be a great solution, but it doesn't actually work. Opening Maccy with shell command, unfortunately, blurring input focus. 

https://github.com/user-attachments/assets/4569ef8b-7ca5-44f6-b8d1-d15e917e5a06

To be polite - I'm not actually sure if it's Maccy issue - it can be that loosing focus is in nature of "shell_command" execution.

**Comment by p0deje** [comment]
1. If you wait until macOS 15.2, the Option+V will work again because Apple reverted their changes.
2. `open` will always focus on the opened application, it's not Maccy doing that.

**Comment by Drun555** [comment]
It's good to hear, thank you for answering!

By the way, I found out that -gj argument with 'open' solves the issue anyway.
