### ISSUE TITLE
🪲 Option Backslash will make the menu look cleared (causing panic but actually it's no cause for concern)

### ISSUE THREAD

**Issue by ADTC** [p0deje/Maccy#984]
### Before Submitting Your Bug Report

- [X] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [x] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

~0.31.0 (30)~ 2.3.0

### macOS Version

14.7.1 (23H222)

### Maccy Settings

```Shell
{
    "KeyboardShortcuts_delete" = "{\\"carbonModifiers\\":2048,\\"carbonKeyCode\\":51}";
    "KeyboardShortcuts_pin" = "{\\"carbonKeyCode\\":35,\\"carbonModifiers\\":2048}";
    "KeyboardShortcuts_popup" = "{\\"carbonModifiers\\":2304,\\"carbonKeyCode\\":9}";
    "LaunchAtLogin__hasMigrated" = 1;
    "NSStatusItem Preferred Position Item-0" = 488;
    "NSStatusItem Visible Item-0" = 1;
    "NSWindow Frame SUStatusFrame" = "664 713 400 134 0 0 1728 1085 ";
    "NSWindow Frame SUUpdateAlert" = "554 515 620 398 0 0 1728 1085 ";
    "NSWindow Frame com.sindresorhus.Preferences.FrameAutosaveName" = "598 264 542 435 0 0 1728 1085 ";
    "NSWindow Frame com.sindresorhus.Settings.FrameAutosaveName" = "1005 471 442 322 0 0 1728 1085 ";
    SUAutomaticallyUpdate = 1;
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2024-12-11 06:39:59 +0000";
    SUSendProfileInfo = 0;
    SUUpdateGroupIdentifier = 480808934;
    WebKitDefaultFontSize = 13;
    WebKitJavaScriptEnabled = 0;
    WebKitPluginsEnabled = 0;
    WebKitStandardFont = "-apple-system-font";
    WebKitUserStyleSheetEnabledPreferenceKey = 1;
    WebKitUserStyleSheetLocationPreferenceKey = "/Applications/Maccy.app/Contents/Frameworks/Sparkle.framework/Resources/ReleaseNotesColorStyle.css";
    avoidTakingFocus = 1;
    enabledPasteboardTypes =     (
        "public.utf8-plain-text",
        "public.png",
        "public.tiff",
        "public.file-url",
        "public.html",
        "public.rtf"
    );
    hideFooter = 0;
    hideSearch = 1;
    hideTitle = 1;
    highlightMatch = underline;
    historySize = 50;
    ignoreEvents = 0;
    ignoredPasteboardTypes =     (
        "com.typeit4me.clipping",
        "de.petermaurer.TransientPasteboardType",
        "net.antelle.keeweb",
        "Pasteboard generator type",
        "com.agilebits.onepassword"
    );
    imageMaxHeight = 40;
    maxMenuItemLength = 50;
    maxMenuItems = 60;
    menuIcon = clipboard;
    migrations =     {
        "2020-04-25-allow-custom-ignored-types" = 1;
        "2020-06-19-use-keyboardshortcuts" = 1;
        "2020-09-01-ignore-keeweb" = 1;
        "2021-02-20-allow-to-customize-supported-types" = 1;
        "2021-06-28-add-title-to-history-item" = 1;
        "2021-10-16-remove-dynamic-pasteboard-types" = 1;
        "2022-08-01-rename-suppress-clear-alert" = 1;
        "2022-11-14-add-html-rtf-to-supported-types" = 1;
        "2023-01-22-add-regexp-search-mode" = 1;
    };
    pasteByDefault = 1;
    pinTo = bottom;
    popupPosition = cursor;
    previewDelay = 1500;
    removeFormattingByDefault = 1;
    searchMode = fuzzy;
    showInStatusBar = 1;
    showRecentCopyInMenuBar = 0;
}
```

### Description

I opened the menu from menu bar and I was pressing Option Delete (backspace) `⌥ ⌫` but once I accidentally pressed Option Backslash `⌥ \` the entire menu cleared out:

<img width="456" alt="image" src="https://github.com/user-attachments/assets/dcfcd704-ad63-43dd-bd8d-5da3ea79a157">

I panicked that I must have erased all the history (including pinned items). However, thankfully this was just a UI anomaly, and the items were still safe in the internal history. When I closed the menu and re-opened it, the items appeared again.

Same thing happens when opening the menu at the current cursor location using the keyboard shortcut, then pressing Option Backslash `⌥ \`.

### Steps to Reproduce

1. Open the Maccy menu.
2. Press Option Backslash `⌥ \`.

**Comment by p0deje** [comment]
Can you re-test on the latest Maccy version (2.2.1)?

**Comment by ADTC** [comment]
Oh wow, I have not seen all these version upgrades. Have you considered adding a "new version" alert system?

Anyway I updated to `2.3.0` your latest release. @p0deje 

It still does what I said when pressing Option Backslash `⌥ \` though now the menu height animates and the items fade out instead of disappearing immediately. Is this a "feature" of some kind?

BTW, separate issue but there is this weird scrolling problem in the menu (for the unpinned list):

https://github.com/user-attachments/assets/7c998d0b-2ed3-4dcb-ae2b-e34f7d0b411f

**Comment by p0deje** [comment]
> Oh wow, I have not seen all these version upgrades. Have you considered adding a "new version" alert system?

Um, there is a built-in auto-update feature.

> It still does what I said when pressing Option Backslash ⌥ \ though now the menu height animates and the items fade out instead of disappearing immediately. Is this a "feature" of some kind?

I am not sure what Option+\ means on your keyboard, mine doesn't do anything outstanding.

> BTW, separate issue but there is this weird scrolling problem in the menu (for the unpinned list):

Resize Maccy window to fit more items.

**Comment by ADTC** [comment]
> Um, there is a built-in auto-update feature.

Oh right, I see it now. But I don't know why 0.31.0 didn't alert me of newer versions though.

> I am not sure what Option+\ means on your keyboard, mine doesn't do anything outstanding.

So nothing happens for you when you press Option Backslash after opening Maccy menu? The keyboard shortcut doesn't do anything in particular for me outside of Maccy.

> Resize Maccy window to fit more items.

Ah, I see. It's a feature.

**Comment by ADTC** [comment]
@p0deje I cleared Maccy data using AppCleaner:

<img width="468" alt="Screenshot 2024-12-12 at 5 16 51 AM" src="https://github.com/user-attachments/assets/2317565a-d2c2-4c47-8c7c-6b4ef3d5f79e" />


And I tried again with some dummy data. I can still reproduce the issue. Watch the video. The items disappear when I press Option Backslash on my keyboard:

https://github.com/user-attachments/assets/69fff71c-0ac4-45e8-be3f-5c8e9834077f

**Comment by p0deje** [comment]
> So nothing happens for you when you press Option Backslash after opening Maccy menu? The keyboard shortcut doesn't do anything in particular for me outside of Maccy.

On my keyboard, it would type "«" character into the search field. Maybe it also types something there but you can't see it since you've hidden the search field. Can you enable it and see what's there?

**Comment by ADTC** [comment]
Ah YES! That's it.

<img width="466" alt="image" src="https://github.com/user-attachments/assets/a1ed31c5-6359-4879-85ba-0b8c21377dbb" />

Perhaps showing a "No search results." message when the search field is completely hidden will reduce the chance of confusion.

Anyway for now I have enabled the search field with the choice of "During search" so at least I know that the search is active, without always showing the search field.
