### ISSUE TITLE
Pasting when selecting should be the default

### ISSUE THREAD

**Issue by Ecco** [p0deje/Maccy#987]
### Problem

It's very counter-intuitive that Maccy would *not* paste an item when selecting it. I understand there's an option for it in the settings, but this option should be selected by default.

Actually, I don't even understand why this is even an option to begin with: when would you *not* want to paste an item after selecting it?

### Solution

Pasting an item when selecting it in Maccy's should be the default behavior. I mean, it's the first FAQ for a reason…

**Comment by p0deje** [comment]
I don't use paste automatically and often find it too obtrusive. Plus, it requires extra permissions.

**Comment by Ecco** [comment]
> I don't use paste automatically

Interesting. What's your workflow like then?

**Comment by p0deje** [comment]
I copy something from history, and then paste it manually wherever I need it. I don't usually place the cursor exactly where I need to paste.

**Comment by Ecco** [comment]
It goes without saying that you're free to use your own software the way you please 😄 

That being said, I'm pretty sure many people use it the other way around, for a couple reasons:
1. Because it's more efficient
2. Because you had to include an FAQ entry specifically for that matter

Indeed, putting the cursor first and selecting the item to paste afterwards is more efficient because:
1. You'll need to put the cursor at the right location at some point anyway
2. Most of the time, as you're typing, the cursor is *already* at the location where you want to paste stuff
3. It doesn't require thinking in advance: as you're typing, you realize you'd like to paste something older. It's very convenient to just peek at the history at this point. (As opposed to having to _anticipate_ that you will need an old pasteboard entry).

I would kindly suggest that you reconsider this issue. Note that I'm not advocating for removal of a use case, but merely for making what I think is the most common one the default.

You do make a good point regarding the extra permission, but I believe there could be a couple solutions:
1. Just ask for the permission anyway, because it's a common use-case
2. Better, do it in a lazy way, at runtime : when selecting an entry for the first time, Maccy could ask the user whether they intend to paste entries right away (which would be an opportunity to explain why an extra permission is needed, and therefore ask for that permission) or whether they'd rather just replace the current pasteboard entry without pasting it.

**Comment by p0deje** [comment]
I understand all your points and I agree with them. However, there are hundreds of users who use Maccy in a different way - their workflow (and mine) requires Maccy to be as unobtrusive as possible, and simulating paste on every selection is just too much at this point.

My reasoning for **default** settings is the following - they need to be as minimalistic as possible w/o extra side effects or permissions. I think the current default settings are better suited with this goal in mind.
