### ISSUE TITLE
Make the footer menu more compact

### ISSUE THREAD

**Issue by Ecco** [p0deje/Maccy#988]
### Problem

This issue is related to the third item of the FAQ, named "How to restore hidden footer?".

I believe the option to hide the footer is misguided.
<img width="319" alt="image" src="https://github.com/user-attachments/assets/1ae2f7b7-29a2-4343-9436-8dbf3b87bf59" />

More specifically I think it's the wrong solution to the (real) problem. Personally I was interested in hiding the footer because it just takes too much screen real estate. However this footer is (sometimes) useful, and if you hide it completely then you end up with a messy situation where you have to create an FAQ entry and add a warning in the settings menu.

### Solution

I think a much better solution would be to have a menu that's always visible but a lot more compact. This way this menu wouldn't get in the way, so users would not have the itch to hide it. Plus it'd still be present when users would need it, once in a while.

Here's a design suggestion, leveraging the search field:
<img width="546" src="https://github.com/user-attachments/assets/0546871e-10e3-4a5e-9514-efb326ae6045" />

Note that I got rid of the "About" menu item and of the "Quit" menu item, because is universally accessible with `⌘-Q` anyway, so I don't think it really requires its own icon. One could be added though, but I think it would needlessly clutter the user interface.

**Comment by p0deje** [comment]
For historical reasons, it was very hard to implement this in the old UI. It's fairly easy now, but I am not sure it's worth cluttering the header with rarely used features. 

Note that even if you hide the footer, you can still access clear/preferences using keyboard shortcuts.

**Comment by Ecco** [comment]
> For historical reasons, it was very hard to implement this in the old UI. It's fairly easy now, but I am not sure it's worth cluttering the header with rarely used features.

Personally I really like the "Show search field during search" option, and in that case the header is not even visible to begin with. So no clutter whatsoever.

> Note that even if you hide the footer, you can still access clear/preferences using keyboard shortcuts.

Yes, you're right, but this is also extremely *not* intuitive as you'd need to remember obscure shortcuts. The reason that this had to be an FAQ entry speaks for itself.

I would kindly ask that you reconsider this option, because I think it is a really good UX tradeoff. Indeed, adding a couple icons next to the search field means that:
1. We'd be adding a couple icons in a location that does not need to always be visible (so people who care about minimalistic interface wouldn't be annoyed by this)
2. We'd be making better use of screen real estate : indeed the right part of the search field is probably rarely used anyway, as I don't think users would realistically type more than a dozen characters when searching their history.
3. We'd alleviate the need to remember weird keyboard shortcuts (this would simplify the settings UI) and prevent people from locking themselves out (and therefore allow us to get rid of a FAQ entry).
