### ISSUE TITLE
Cannot reorder pins and not assign all letters

### ISSUE THREAD

**Issue by freebrowser1** [p0deje/Maccy#989]
### Before Submitting Your Bug Report

- [x] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [x] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

2.3.0

### macOS Version

15.1

### Maccy Settings

```Shell
{
    "KeyboardShortcuts_delete" = "{\\"carbonModifiers\\":2048,\\"carbonKeyCode\\":51}";
    "KeyboardShortcuts_pin" = "{\\"carbonModifiers\\":2304,\\"carbonKeyCode\\":20}";
    "KeyboardShortcuts_popup" = "{\\"carbonModifiers\\":4352,\\"carbonKeyCode\\":18}";
    "LaunchAtLogin__hasMigrated" = 1;
    "NSStatusItem Preferred Position Item-0" = 526;
    "NSStatusItem Visible Item-1" = 0;
    "NSWindow Frame SUUpdateAlert" = "650 511 620 398 0 0 1920 1080 ";
    "NSWindow Frame com.sindresorhus.Settings.FrameAutosaveName" = "1985 206 532 460 1280 -280 1920 1080 ";
    SUAutomaticallyUpdate = 0;
    SUEnableAutomaticChecks = 0;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2024-12-11 13:27:17 +0000";
    SUSendProfileInfo = 0;
    avoidTakingFocus = 1;
    enabledPasteboardTypes =     (
        "public.tiff",
        "public.rtf",
        "public.html",
        "public.utf8-plain-text",
        "public.png"
    );
    ignoredPasteboardTypes =     (
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "Pasteboard generator type",
        "com.agilebits.onepassword",
        "net.antelle.keeweb"
    );
    migrations =     {
        "2024-07-01-version-2" = 1;
    };
    searchVisibility = always;
    showFooter = 1;
    showSearch = 1;
    showTitle = 1;
    sortBy = lastCopiedAt;
    windowSize = "[450,800]";
}
```

### Description

When I change a pinned item, I cannot change the pinned item itself, but have to remove it, add a new one and re-pin it. Not a big deal.
But the shortcut letters (cmd+letter) cannot be used anymore, e.g. when cmd+a was used previously it cannot be used.
And the order of the pins can neither be changed.

### Steps to Reproduce

1. Pin a clipping and use cmd+a as shortcut
2. remove the clipping
3. Pin another clipping 
4. Now cmd+a cannot be used anymore.

And pins cannot be ordered, they are arranged in a random order.

**Comment by p0deje** [comment]
1. Cmd+A is a reserved shortcut and not available for pins anymore.
2. Reordering pins is to be implemented in #342
