### ISSUE TITLE
screenshot search

### ISSUE THREAD

**Issue by mowhits** [p0deje/Maccy#992]
being able to find text in screenshots sounds like a great feature, although i'm not sure how hard it is to implement or how resource-intensive it can be.

**Comment by Coin-ZZ** [comment]
Adding OCR would greatly improve efficiency. It would be very convenient to extract text directly from a screenshot saved to the clipboard. However, I’m also not sure how hard it is to implement or how resource-intensive it might be.

**Comment by p0deje** [comment]
I have a prototype that works by OCRing the image and storing its text internally. It will not show it anywhere, but it can still be searched. Does it make sense to you folks?

<img width="944" alt="Screenshot 2024-12-16 at 19 29 08" src="https://github.com/user-attachments/assets/49ba6586-a9a5-4ba8-ae4c-869101e6a94e" />

**Comment by BrunoSap** [comment]
@p0deje, is it possible for the image text to be pasted in addition to being just searchable?

<img width="968" height="236" alt="Image" src="https://github.com/user-attachments/assets/7610b43e-a836-4c16-afab-917bdd541377" />

**Comment by weisJ** [comment]
There was a PR adding support for it #1152 however it wasn't updated for some time now. The plan is to make it available through the paste without formatting option.
