### ISSUE TITLE
Can our UI be refactored to be similar to paste? Horizontal display makes it easier to find the content to be pasted

### ISSUE THREAD

**Issue by Allsochen** [p0deje/Maccy#995]
### Before Submitting Your Feature Request

- [ ] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [ ] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

Horizontal display makes it easier to find the content to be pasted and make sure the grid size of each content is the same.

Paste：
![image](https://github.com/user-attachments/assets/2109e98e-52d6-4c24-8c42-06d57380e22e)

**Comment by p0deje** [comment]
It's too much work to be honest, I think you better stick to Paste then.
