### ISSUE TITLE
No Maccy on menu bar

### ISSUE THREAD

**Issue by familieslifedev** [p0deje/Maccy#996]
### Before Submitting Your Bug Report

- [X] I have verified that there isn't already an issue reporting the same bug to prevent duplication.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Maccy Version (see 'About' window)

2.3.0 (54)

### macOS Version

14.7.1

### Maccy Settings

```Shell
{
    "KeyboardShortcuts_delete" = "{\\"carbonModifiers\\":2048,\\"carbonKeyCode\\":51}";
    "KeyboardShortcuts_pin" = "{\\"carbonKeyCode\\":35,\\"carbonModifiers\\":2048}";
    "KeyboardShortcuts_popup" = "{\\"carbonKeyCode\\":8,\\"carbonModifiers\\":768}";
    "LaunchAtLogin__hasMigrated" = 1;
    "NSStatusItem Visible Item-0" = 1;
    "NSStatusItem Visible Item-1" = 0;
    "NSWindow Frame SUUpdateAlert" = "554 515 620 398 0 0 1728 1085 ";
    "NSWindow Frame com.sindresorhus.Settings.FrameAutosaveName" = "509 515 710 409 0 0 1728 1079 ";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2024-12-18 09:35:19 +0000";
    SUUpdateGroupIdentifier = 1744807858;
    clearOnQuit = 1;
    clearSystemClipboard = 1;
    enabledPasteboardTypes =     (
        "public.html",
        "public.utf8-plain-text",
        "public.file-url",
        "public.tiff",
        "public.rtf",
        "public.png"
    );
    ignoredPasteboardTypes =     (
        "net.antelle.keeweb",
        "de.petermaurer.TransientPasteboardType",
        "Pasteboard generator type",
        "com.typeit4me.clipping",
        "com.agilebits.onepassword"
    );
    menuIcon = maccy;
    migrations =     {
        "2024-07-01-version-2" = 1;
    };
    pinTo = top;
    popupPosition = cursor;
    searchMode = fuzzy;
    showApplicationIcons = 1;
    showFooter = 1;
    showInStatusBar = 1;
    showRecentCopyInMenuBar = 1;
    showSearch = 1;
    showTitle = 1;
    suppressClearAlert = 1;
    windowSize = "[450,800]";
}
```

### Description

https://github.com/user-attachments/assets/2d3b6bc1-ddec-41dd-8834-8b8e4dcc068e

There seems to be an issue with the Maccy menu bar icon no longer showing up. It started either yesterday or Monday (16-17/12/24). This causes me to have to search for Maccy in Spotlight whenever I need to get something back, which is a little annoying, considering I'm used to just getting it from the menu bar.

### Steps to Reproduce

1. Make sure Maccy is on the version specified
2. Open Maccy and check your menu bar
3. Check settings to ensure menu bar icon is enabled
4. Type in Maccy in Spotlight

*Expected Result*
Maccy menu bar icon stays in my menu bar and I don't have to search for the app to open it

*Actual Result*
Menu bar icon is not visible despite the option being enabled in Preferences.

**Comment by familieslifedev** [comment]
Fixed the issue; it's just Mac being dumb 😑 
Sorry about the report lol

**Comment by 1ucian0** [comment]
How did you fix it @familieslifedev ? I have the same issue after installation.

**Comment by familieslifedev** [comment]
> How did you fix it @familieslifedev ? I have the same issue after installation.

Honestly, it was just because I had too many things on my Menu Bar 😅. Any apps you don't need open, try closing down/removing from your menu bar. Hopefully it should show then.
