### ISSUE TITLE
Limit the amount of items you can see when you open the app/popup

### ISSUE THREAD

**Issue by icougil** [p0deje/Maccy#997]
### Before Submitting Your Feature Request

- [X] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

I like this app very much... but it is not very convenient to see a big list of entries (> 50, 100?) when you open the app/popup (it is not very handy to see 30 or 40 options in a list and it is always easier to search than having a look to which entry you'd like to select)

### Solution

It will be really convenient to be able to limit the amount of entries you can see in the app when we open it (ex: 10-20 by default?) and if the user needs it, to be able to change it...

**Comment by p0deje** [comment]
You can resize the window to show as little or many items as you want.

**Comment by icougil** [comment]
jajajaj it is totally true!! 😅🤦‍♂️🤣 
Thank you very much!
