### ISSUE TITLE
Move footer options 

### ISSUE THREAD

**Issue by Gittykittymitty** [p0deje/Maccy#999]
### Before Submitting Your Feature Request

- [X] Check that there isn't already a similar feature request to avoid creating a duplicate.
- [X] I have seen the [FAQ](https://github.com/p0deje/Maccy?tab=readme-ov-file#faq).

### Problem

Maccys footer menu takes up way to much space and is in the way. 

### Solution

Move the footer menu to a right click on the menubar icon.

**Comment by p0deje** [comment]
You can hide it in settings if you don't need it.

**Comment by Gittykittymitty** [comment]
But how will I get back into settings? Or how will I clean the clipboard? I know theres a settings keyboard shortcut, but those are easy to forget...

**Comment by p0deje** [comment]
The shortcuts are a way to go!
- Settings - Command+, - this is used in every native macOS application
- Clear - Command+Option+Delete
